### PR TITLE
PartitioningStrategyFactory no longer caching in static map

### LINKED ISSUE #8634: PartitioningStrategyFactoryTest.whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance
```
java.lang.AssertionError: expected same:<com.hazelcast.partition.strategy.StringPartitioningStrategy@5a927881> was not:<com.hazelcast.partition.strategy.StringPartitioningStrategy@11bf4347>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotSame(Assert.java:828)
	at org.junit.Assert.assertSame(Assert.java:771)
	at org.junit.Assert.assertSame(Assert.java:782)
	at com.hazelcast.map.impl.PartitioningStrategyFactoryTest.whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance(PartitioningStrategyFactoryTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK8/com.hazelcast$hazelcast/280/testReport/junit/com.hazelcast.map.impl/PartitioningStrategyFactoryTest/whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSameInstance/

### PR DESCRIPTION
**Pull request by vbekiaris**
A PartitioningStrategyFactory instance per Hazelcast node is constructed and used via `MapServiceContextImpl` to avoid potential clashes when running multiple nodes in same JVM.

Fixes #8634

### CODE REVIEW

**Comment by ahmetmircik** [comment]
👍 (when tests passed)

File: hazelcast/src/test/java/com/hazelcast/map/impl/PartitioningStrategyFactoryTest.java [hunk 1]
```diff
@@ -98,16 +112,49 @@ public void whenStrategyForMapAlreadyDefined_getPartitioningStrategy_returnsSame
...
     @Test
     public void whenStrategyInstantiationThrowsException_getSamePartitioningStrategy_rethrowsException() {
-        NodeEngine nodeEngine = mock(NodeEngine.class);
-        RuntimeException e = new RuntimeException("expected exception");
-        Mockito.when(nodeEngine.getConfigClassLoader()).thenThrow(e);
+        PartitioningStrategyConfig cfg = new PartitioningStrategyConfig();
+        cfg.setPartitioningStrategyClass("NonExistentPartitioningStrategy");
+
+        // while attempting to get partitioning strategy, ClassNotFound exception will be thrown and wrapped in HazelcastException
+        expectedException.expect(new IsInstanceOf(HazelcastException.class));
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/impl/PartitioningStrategyFactoryTest.java]: I've written a class `RootCauseMatcher` some time ago, which you can use to check for the original exception in cases like this. It will just call `getCause()` down to the bottom, so it doesn't matter in how many exceptions the original one was wrapped. You can see the usage in `ClientDurableExecutorServiceTest`.

**Comment by Donnerbart** [comment]
I really like the removal of the `NodeEngine` dependency in the factory. You can already see in the unit test for the class, that it's much easier to use now.

I have a small suggestion for a test improvement, beside that :+1:

File: hazelcast/src/test/java/com/hazelcast/map/impl/PartitioningStrategyFactoryTest.java (hunk 1 above)
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/map/impl/PartitioningStrategyFactoryTest.java]: Good one, updated to use `RootCauseMatcher`

Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/impl/PartitioningStrategyFactoryTest.java]: Looks good, feel free to merge once the build is green again.
