### PR TITLE
fixes incorrect master answer sending when join request comes from cu…

### LINKED ISSUE #5276: [TEST-FAILURE] SplitBrainHandlerTest failures
com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge
com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave
```
java.lang.AssertionError: expected:<Address[127.0.0.1]:5703> but was:<Address[127.0.0.1]:5702>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cluster.SplitBrainHandlerTest.testClusterMerge_when_split_not_detected_by_slave_and_restart_during_merge(SplitBrainHandlerTest.java:710)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.maintenance-nightly/474/#showFailuresLink

### PR DESCRIPTION
**Pull request by eminn**
…rrent master introduced by 7ed8ea9617fea5d8fdc78b7203572b934b7fe233 , fixes #5276

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java [hunk 1]
```diff
@@ -604,15 +604,17 @@ public void handleJoinRequest(JoinRequest joinRequest, Connection connection) {
             return;
         }
 
-        if (!node.isMaster()) {
-            sendMasterAnswer(joinRequest.getAddress());
+        Address target = joinRequest.getAddress();
+        boolean isRequestFromCurrentMaster = target.equals(node.getMasterAddress());
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: Looks good. Nice catch. Can you add some explanation about the reason of this check as a comment? I don't want to miss the logic here.

Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: done

**Comment by mdogan** [comment]
:+1:
