### PR TITLE
ThreadLocalRandomProvide does not rely on non-arg constructor of Random

### LINKED ISSUE #9985: ClientTxnMultiMapTest.testConcrruentTxnPut
```
java.lang.AssertionError: expected null, but was:<com.hazelcast.transaction.TransactionNotActiveException: Transaction is not active>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.junit.Assert.assertNull(Assert.java:747)
	at com.hazelcast.client.txn.ClientTxnMultiMapTest.testConcrruentTxnPut(ClientTxnMultiMapTest.java:144)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast%20Maintenance/job/Hazelcast-3.maintenance-ZuluJDK6-freestyle/10/testReport/junit/com.hazelcast.client.txn/ClientTxnMultiMapTest/testConcrruentTxnPut/

### PR DESCRIPTION
**Pull request by jerrinot**
some JDK implementations do not have thread-safe  seed generation -> 2 concurrent calls
could create Random instances initialized with the same seed. As a result UUIDUtil could
generate the same UUID.

fixed #9985

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java [hunk 1]
```diff
@@ -38,7 +40,8 @@ private ThreadLocalRandomProvider() {
     public static Random get() {
         Random random = THREAD_LOCAL_RANDOM.get();
         if (random == null) {
-            random = new Random();
+            long seed = SEED_GENERATOR.nextLong();
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java]: Random is just thread-safe since Java 7, isn't it? May this cause issues when this method is called from different threads?

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java]: "thread-safe since Java 7" <-- really?

Comment (noctarius) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java]: Yeah, on Java 6 we'll need to fallback on CAS operations

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java]: in Sun Java 6 the seed generator is not thread-safe: 2 threads can create 2 instances of `Random` initialized with the same seed. 

However when you have a single `Random` instance then 2 threads calling `getLong()` will get different results. The CAS loop is inside `Random`. It has been like this since at least Java 5. See http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6362070

Comment (noctarius) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java]: Oh yeah, you're right. Missed you're using a generator now. Sorry :)

Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ThreadLocalRandomProvider.java]: Okay, so after some discussions and readings this is my actual state of knowledge:
* using the same `Random` instance from multiple threads should be fine since Java 5
* this might have an impact on performance, since there is a CAS loop inside of e.g. `Random::nextLong()`
* so for performance reasons we want to use multiple `Random` instances (here via `ThreadLocal`)
* there can still be an issue with generating multiple `Random` instances from multiple threads -> they can have same random seed
* this is the reason for the `SEED_GENERATOR`, which should be thread-safe due to the same `Random` instance being used

**Comment by Donnerbart** [comment]
I think we need a backport for 3.8.1 as well, don't we?

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run

**Comment by hasancelik** [comment]
run-lab-run
