### PR TITLE
Removes generics in the ResultSet. Fixes #11489

### LINKED ISSUE #11489: Regression after returning ResultSet instead of SortedQueryResultSet
First see this [group question](https://groups.google.com/d/msgid/hazelcast/0a3f8ed6-2fed-4fc2-8ad1-d7aa1d99a175%40googlegroups.com?utm_medium=email&utm_source=footer).

Problem occurs in [getSortedQueryResultSet](https://github.com/hazelcast/hazelcast/blob/28d373e90dcbbba2dcaabdde33f8349b1dfbef38/hazelcast/src/main/java/com/hazelcast/util/SortingUtil.java#L158) method: 
When returned object is [SortedQueryResultSet](https://github.com/hazelcast/hazelcast/blob/13026001f507ea67deff19157f146b4371d2b6b8/hazelcast/src/main/java/com/hazelcast/map/impl/query/SortedQueryResultSet.java) there is no problem but when it is [ResultSet](https://github.com/hazelcast/hazelcast/blob/28d373e90dcbbba2dcaabdde33f8349b1dfbef38/hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/ResultSet.java) failure happens.

### PR DESCRIPTION
**Pull request by tombujok**
Fixes #11489

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java [hunk 1]
```diff
@@ -1191,6 +1194,26 @@ public void testIfWeCarryRecordVersionInfoToReplicas() {
     }
 
     @Test
+    public void github_11489() throws Exception {
+        HazelcastInstance hz = createHazelcastInstance();
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java]: Has to be `HazelcastInstance hz = instances[1];`, since we already got a test factory.

File: hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java [hunk 2]
```diff
@@ -1191,6 +1194,26 @@ public void testIfWeCarryRecordVersionInfoToReplicas() {
...
+        IMap test = hz.getMap("test");
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java]: Should be `IMap<Integer, Integer> test = hz.getMap("test");` (no need for a generics warning here).

File: hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java [hunk 3]
```diff
@@ -1191,6 +1194,26 @@ public void testIfWeCarryRecordVersionInfoToReplicas() {
     }
 
     @Test
+    public void github_11489() throws Exception {
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java]: This is a bad name, since it doesn't describe what it does. You can put a link to the issue in JavaDoc, e.g.
```java
    /**
     * Test for https://github.com/hazelcast/hazelcast/issues/11489
     */
```

File: hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java [hunk 4]
```diff
@@ -1191,6 +1194,30 @@ public void testIfWeCarryRecordVersionInfoToReplicas() {
...
+        IMap test = getInstance().getMap("github_11489");
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java]: Should be `IMap<Integer, Integer> test = getInstance().getMap("github_11489");`, no need to generate generics warnings.

**Comment by tombujok** [comment]
run-lab-run
