### PR TITLE
Improve "fixing" async stack traces for classes without expected constructor signature[HZ-1243]

### LINKED ISSUE #20357: For some types of exceptions the exception cloning process lose the root cause (ExceptionUtil#cloneExceptionWithFixedAsyncStackTrace) [HZ-1243]
**Bug description**
Method `com.hazelcast.internal.util.ExceptionUtil#cloneExceptionWithFixedAsyncStackTrace` can return not only

> _a cloned exception with the current stacktrace is added on top of the original exceptions stack-trace the cloned exception has the same cause and the message as the original exception_

but also a `null` value (the calling side should be aware of that). And in case of `null` value the calling side should apply appropriate procedures so that the root cause is not lost during exception wrapping. Otherwise the requestor won't have a chance to find out the cause of the encountered issue.
In my case `cloneExceptionWithFixedAsyncStackTrace` method returns `null` for the exception of `org.eclipse.persistence.exceptions.DatabaseException` type.

**Expected behavior**
Correct approach is applied in following methods in `com.hazelcast.spi.impl.AbstractInvocationFuture` class:
```java
    private static RuntimeException wrapRuntimeException(RuntimeException cause) {
        if (cause instanceof WrappableException) {
            return ((WrappableException) cause).wrap();
        }
        RuntimeException wrapped = cloneExceptionWithFixedAsyncStackTrace(cause);
        return wrapped == null ? new HazelcastException(cause) : wrapped;
    }

    private static Error wrapError(Error cause) {
        Error result = cloneExceptionWithFixedAsyncStackTrace(cause);
        return result == null ? cause : result;
    }
```

Where the original exception is taken into consideration when the cloning method returns `null`.

I would expect similar approach as in `wrapRuntimeException` and `wrapError` methods also in following method in `com.hazelcast.spi.impl.operationservice.impl.InvocationFuture` class:

```java
    public static <T> T returnOrThrowWithGetConventions(Object response) throws ExecutionException, InterruptedException {
        if (!(response instanceof ExceptionalResult)) {
            return (T) response;
        }
        response = ((ExceptionalResult) response).getCause();
        if (response instanceof WrappableException) {
            response = ((WrappableException) response).wrap();
        } else if (response instanceof RuntimeException || response instanceof Error) {
            response = cloneExceptionWithFixedAsyncStackTrace((Throwable) response); // here is the cloning procedure that may return null
            // expected behaviour would be as follows:
            // var cloned = cloneExceptionWithFixedAsyncStackTrace((Throwable) response);
            // response = cloned == null ? response : cloned;
        }
        if (response instanceof CancellationException) {
            throw (CancellationException) response;
        } else if (response instanceof ExecutionException) {
            throw (ExecutionException) response;
        } else if (response instanceof InterruptedException) {
            throw (InterruptedException) response;
        } else {
            throw new ExecutionException((Throwable) response); // and thanks to above fixes null value won't become a root cause for the wrapped exception 
        }
    }
```

**Additional context**

Hazelcast version: 5.0

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Unreflect even private constructor + make it accessible to clone exceptions with non-public constructor.

Return original, non-modified exception if nothing can be appended as a fallback (better exception without async stack trace, than nothing).

Fixes #20357

Checklist:
- [ ] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] Send backports/forwardports if fix needs to be applied to past/future releases
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java [hunk 1]
```diff
@@ -345,7 +355,7 @@ public static <T extends Throwable> T cloneExceptionWithFixedAsyncStackTrace(T o
             return (T) clone;
         }
 
-        return null;
+        return original;
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java:358]: Seeing null checks based on return type of this method, can we also remove those null checks?
Additionally, when cloning is failed, we are not returning a wrapped exception any more but the original one, this will be a breaking change, better to mention in release docs.

File: hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java [hunk 2]
```diff
@@ -240,14 +241,23 @@ public static <T extends Throwable> T tryCreateExceptionWithMessageAndCause(Clas
     private static <T extends Throwable> T cloneException(Class<? extends Throwable> exceptionClass,
                                                           String message, @Nullable Throwable cause,
                                                           ConstructorMethod constructorMethod) {
+        Constructor<? extends Throwable> reflectedConstructor = null;
+        boolean isAccessible = false;
         try {
-            MethodHandle constructor = MethodHandles.publicLookup()
-                    .findConstructor(exceptionClass, constructorMethod.signature());
+            reflectedConstructor = exceptionClass.getDeclaredConstructor(constructorMethod.signature().parameterArray());
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java:247]: i'm not sure whether it is good practice to create an object by using its non-public constructor, there can be a reason to restrict access to it.

Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java:247]: In general, I agree. But we here hack this nevertheless, by artifically manipulating the stacktrace.

Alternatively we can wrap should exception in some generic one, WDYT?

Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java:247]: yes, wrapping seems better to me.

**Review by utku-caglayan — APPROVED** [review]
Looks good!

File: hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java (hunk 2 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java]: I went with just sending original exception; detecting non-public constructor and wrapping would only make code messier, IMHO not worth in the end

**Review by mdumandag — APPROVED** [review]
