### PR TITLE
Cache creation should not take into account output of CacheCreateConfigOp

### LINKED ISSUE #11432: [cache] CacheBasicClientTest.cacheManagerOfCache_cannotBeOverwrittenConcurrently
```
java.lang.AssertionError: Unexpected exception thrown: A cache named the-cache already exists.
	at com.hazelcast.cache.CacheBasicAbstractTest.cacheManagerOfCache_cannotBeOverwrittenConcurrently(CacheBasicAbstractTest.java:949)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:785)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.8/com.hazelcast$hazelcast-client/725/testReport/junit/com.hazelcast.client.cache/CacheBasicClientTest/cacheManagerOfCache_cannotBeOverwrittenConcurrently/

### PR DESCRIPTION
**Pull request by vbekiaris**
In this PR:
- Added javadoc in `CacheCreateConfigOperation` to document caveats with this operation
- Amended `AbstractHazelcastCacheManager` to disregard ambiguous response of `CacheCreateConfigOperation` (see https://github.com/hazelcast/hazelcast/issues/11432#issuecomment-332513148).
- Removed `HazelcastClientCacheManager.configs` as it duplicates the purpose of `ClientCacheProxyFactory.configs` and in one case was not updated properly.

Fixes #11432

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheHelper.java [hunk 1]
```diff
@@ -98,27 +97,27 @@ private ClientCacheHelper() {
...
+     *                           imply that when this method exits the {@code CacheConfig} is already created on all members.
      * @param <K>                type of the key of the cache
      * @param <V>                type of the value of the cache
      * @return the created cache configuration
+     * @see com.hazelcast.cache.impl.operation.CacheCreateConfigOperation
      */
     static <K, V> CacheConfig<K, V> createCacheConfig(HazelcastClientInstanceImpl client,
-                                                      ConcurrentMap<String, CacheConfig> configs,
-                                                      String cacheName,
+                                                      CacheConfig<K, V> existingConfig,
```
Comment (vbekiaris) [inline hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheHelper.java]: The existing `configs` map was solely used to obtain an already existing `CacheConfig` (if available). In general, the utility methods in `ClientCacheHelper` aren't used much outside of `HazelcastClientCacheManager`, so it would make sense to turn them to instance methods, however I left this cleanup for #11190 .

File: hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/HazelcastClientCacheManager.java [hunk 2]
```diff
@@ -47,7 +44,6 @@
 
     private final HazelcastClientInstanceImpl client;
     private final ClientCacheProxyFactory clientCacheProxyFactory;
-    private final ConcurrentMap<String, CacheConfig> configs = new ConcurrentHashMap<String, CacheConfig>();
```
Comment (vbekiaris) [inline hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/HazelcastClientCacheManager.java]: This map duplicates whatever is already available in `ClientCacheProxyFactory.configs`
