### PR TITLE
ClientRegressionWithMockNetworkTest instances checks [HZ-1836]

### LINKED ISSUE #20590: com.hazelcast.client.ClientRegressionWithMockNetworkTest [HZ-1836]
_5.0.z_ (commit 66205d3ebb195e129fb552d88a11730c16ca0851)

Failed on Zing JDK 8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/38/testReport/com.hazelcast.client/ClientRegressionWithMockNetworkTest/com_hazelcast_client_ClientRegressionWithMockNetworkTest/

It failed in the same run as https://github.com/hazelcast/hazelcast/issues/20589 - those issues can be related.

<details><summary>Stacktrace:</summary>

```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='gracious_turing', node=[127.0.0.1]:5701}]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:46)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testOperationRedo in 8.444 seconds.
19:09:46,219  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
19:09:46,219 DEBUG || - [JobCoordinationService] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Added a shutting-down member: f474fd28-7ca1-497b-b26b-aa0f7e3598da
19:09:46,220  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down connection manager...
19:09:46,220  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Shutting down node engine...
19:09:46,234  INFO || - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Destroying node NodeExtension.
19:09:46,237  INFO || - [Node] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] Hazelcast Shutdown is completed in 18 ms.
19:09:46,237  INFO || - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.0.3-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
```

</details>

### PR DESCRIPTION
**Pull request by TomaszGaweda**
1. shutdown changed to terminate for instant quit
2. added "instances left" assertion after each test to quickly discover which test leaked
3. tests run in serial - after 2. I saw that sometimes instance termination was causing problems with other running tests

Fixes #20590

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Comment by mdumandag** [comment]
I did some research on why this test can fail like this, and I think I found the cause. I believe, we should fix the actual cause, or otherwise, changes in this PR won't really help.

When I looked at the failed test logs, I see that the not-shutdown instance is always started in `testClientReconnect_thenCheckRequestsAreRetriedWithoutException`. When I looked at that test, I saw that it is not going to do what is expected under some scenarios and can cause such failures.

The problematic part is these two snippets

```java
        CountDownLatch clientStartedDoingRequests = new CountDownLatch(1);
        new Thread(() -> {
            try {
                clientStartedDoingRequests.await();
            } catch (InterruptedException ignored) {
            }

            hazelcastInstance.shutdown();

            hazelcastFactory.newHazelcastInstance();

        }).start();
```

```java
        int mapSize = 1000;
        for (int i = 0; i < mapSize; i++) {
            if (i == mapSize / 4) {
                clientStartedDoingRequests.countDown();
            }
            try {
                map.put(i, i);
            } catch (Exception e) {
                fail("Requests should not throw exception with this configuration. Last put key: " + i);
            }
        }
```

So, when we are at `i=250`, we count down a latch and continue the put operations. Now, imagine that the thread we started earlier hasn't been rescheduled yet, so the instance is not shut down. We will happily continue our put requests. Everything will work, and it is certainly possible that we can finish all of the 1000 operations before the thread comes to `hazelcastInstance.shutdown();` line. So, if that happens, the test will finish, and we will execute the `@After` part, and shut down all the instances that have been created. But, since we didn't wait for the thread we started to finish its execution, the `hazelcastFactory.newHazelcastInstance();` line can be executed after `hazelcastFactory.shutdownAll();`, and that can cause after class statements to fail.

I think what we should do is, we should add a second latch to the test, countdown it after `hazelcastInstance.shutdown();` line in the started thread, and wait for that latch to open after calling `clientStartedDoingRequests.countDown();`. We should also wait for the thread we created to finish before finalizing the test.

**Comment by mdumandag** [comment]
I am not %100 sure about the second latch though, as maybe the test author wanted to test the scenario when some put request was in-flight and the instance is shut down in the meantime.

**Comment by ldziedziul** [comment]
Great finding @mdumandag!

**Comment by TomaszGaweda** [comment]
Great finding @mdumandag, thanks! I've added a latch to control this scenario

File: hazelcast/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java [hunk 1]
```diff
@@ -714,6 +715,7 @@ public void testClientReconnect_thenCheckRequestsAreRetriedWithoutException() {
             hazelcastInstance.shutdown();
 
             hazelcastFactory.newHazelcastInstance();
+            restartFinished.countDown();
```
Comment (ldziedziul) [inline hazelcast/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java:718]: Maybe put it in `finally` block of this `try`?

**Review by mdumandag — APPROVED** [review]

**Comment by vbekiaris** [comment]
Has the fix been backported to other 5.y branches? There is a failure on `5.0.z` branch [here](https://github.com/hazelcast/hazelcast/pull/23226#issuecomment-1358371279)
