### PR TITLE
[IBM JDK] #13534 fix package lookup in Byte Buddy

### LINKED ISSUE #13534: ServiceLoaderTest.testSkipHookLoadedByDifferentClassloader failure
*master* (commit 4525ce5ac463caa640d330ceafbef750448256e9)

Failing constantly only on IBM JDK 8: https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8/lastCompletedBuild/testReport/com.hazelcast.util/ServiceLoaderTest/testSkipHookLoadedByDifferentClassloader/

Other failures (with same stacktrace): 
ServiceLoaderTest.testSkipHooksWithImplementingTheExpectedInterfaceButLoadedByDifferentClassloader
ServiceLoaderTest.testFailFastWhenHookDoesNotImplementExpectedInteface

Stacktrace:
```
java.lang.IllegalStateException: Cannot access final java.lang.Package java.lang.ClassLoader.getDefinedPackage(java.lang.String)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm.apply(ByteArrayClassLoader.java:561)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:439)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ClassDefinitionAction.run(ByteArrayClassLoader.java:409)
	at java.security.AccessController.doPrivileged(AccessController.java:666)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:262)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:925)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:870)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:853)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:402)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.load(ByteArrayClassLoader.java:220)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:285)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:120)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:79)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4376)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4362)
	at com.hazelcast.util.ServiceLoaderTest.newInterface(ServiceLoaderTest.java:243)
	at com.hazelcast.util.ServiceLoaderTest.testSkipHookLoadedByDifferentClassloader(ServiceLoaderTest.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)
Caused by: java.lang.IllegalAccessException: Class net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm can not access a member of class java.lang.ClassLoader with modifiers "final"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:114)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:399)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:391)
	at java.lang.reflect.Method.invoke(Method.java:501)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForJava9CapableVm.apply(ByteArrayClassLoader.java:559)
	... 29 more
```

The failure is constant, actually much earlier, but because of Jenkins jobs migration, I'm reporting it now with quite a big delay, sorry about that.

### PR DESCRIPTION
**Pull request by kwart**
Fixes #13534.
The package lookup in Byte Buddy doesn't work correctly on IBM Java 8 (raphw/byte-buddy#510).

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java [hunk 1]
```diff
@@ -436,7 +436,7 @@ public static ProxySource of(Class<?> klass, ClassLoader targetClassLoader) {
         public static final AllAsPublicConstructorStrategy INSTANCE = new AllAsPublicConstructorStrategy();
 
         @Override
-        public MethodRegistry inject(MethodRegistry methodRegistry) {
+        public MethodRegistry inject(TypeDescription instrumentedType, MethodRegistry methodRegistry) {
```
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java]: Is this leftover?

**Comment by mdogan** [comment]
Shouldn't we update byte-buddy to version `1.8.17`?

**Comment by kwart** [comment]
I was in a wrong directory while adding the files into the commit, so the root `pom.xml` wasn't included. Thanks for noticing, Mehmet. It's fixed now.

There is another issue with the new byte-buddy (raphw/byte-buddy#513), let's see if other pieces of the testsuite are influenced.

File: hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java (hunk 1 above)
Comment (kwart) [reply hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastProxyFactory.java]: It's not a leftover, the ByteBuddy API has changed in the new versions.
