### PR TITLE
Fail fast when there is no factory for a configured discovery strategy

### LINKED ISSUE #10993: [discovery] No Warning or Info message given when DiscoveryStrategy SPI not on classpath
There was a typo on discovery-strategy config, and it may hard to find w/out proper log message when hazelcast starts.
```$xml
<discovery-strategies>
                <discovery-strategy class="com.hazelcast.eurekast.one.EurekastOneDiscoveryStrategy" enabled="true">
                </discovery-strategy>
</discovery-strategies>
```
It should be `EurekaOneDiscoveryStrategy`

Below you can find log output.
```
docker@vm2:~$ docker logs 3a5ac5e866c0
########################################
# RUN_JAVA=
# JAVA_OPTS=
# starting now....
########################################
Jul 27, 2017 10:25:40 AM com.hazelcast.config.XmlConfigLocator
INFO: Loading 'hazelcast.xml' from working directory.
Jul 27, 2017 10:25:41 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.8.2] Prefer IPv4 stack is true.
Jul 27, 2017 10:25:41 AM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.8.2] Picked [172.18.0.4]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
Jul 27, 2017 10:25:41 AM com.hazelcast.system
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Hazelcast 3.8.2 (20170518 - a60f944) starting at [172.18.0.4]:5701
Jul 27, 2017 10:25:41 AM com.hazelcast.system
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
Jul 27, 2017 10:25:41 AM com.hazelcast.system
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Configured Hazelcast Serialization version : 1
Jul 27, 2017 10:25:42 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Backpressure is disabled
Jul 27, 2017 10:25:43 AM com.hazelcast.instance.Node
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Activating Discovery SPI Joiner
Jul 27, 2017 10:25:43 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Starting 2 partition threads
Jul 27, 2017 10:25:43 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Starting 3 generic threads (1 dedicated for priority tasks)
Jul 27, 2017 10:25:44 AM com.hazelcast.core.LifecycleService
INFO: [172.18.0.4]:5701 [dev] [3.8.2] [172.18.0.4]:5701 is STARTING
Jul 27, 2017 10:25:44 AM com.hazelcast.system
INFO: [172.18.0.4]:5701 [dev] [3.8.2] Cluster version set to 3.8
Jul 27, 2017 10:25:44 AM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
INFO: [172.18.0.4]:5701 [dev] [3.8.2]


Members [1] {
	Member [172.18.0.4]:5701 - 361531c1-c5b8-4df3-9b91-ad1e2b2940b3 this
}

Jul 27, 2017 10:25:44 AM com.hazelcast.core.LifecycleService
INFO: [172.18.0.4]:5701 [dev] [3.8.2] [172.18.0.4]:5701 is STARTED
```

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #10993

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java [hunk 1]
```diff
@@ -155,11 +155,17 @@ private boolean validateCandidate(DiscoveryNode candidate) {
...
+                //as a side-effect the buildDiscoveryStrategy() removes a config of the created strategy
                 DiscoveryStrategy discoveryStrategy = buildDiscoveryStrategy(factory, discoveryStrategyConfigs);
                 if (discoveryStrategy != null) {
                     discoveryStrategies.add(discoveryStrategy);
                 }
             }
+            if (!discoveryStrategyConfigs.isEmpty()) {
+                throw new ValidationException("There is no factory to create these strategies: '"
+                        + discoveryStrategyConfigs + "' Is it a typo in a strategy classname? "
+                        + "Perhaps you forgot to include implementation is not present on a classpath?");
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: > Perhaps you forgot to include implementation is not present on a classpath?
The grammar here needs a little overhaul.

File: hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java [hunk 2]
```diff
@@ -155,11 +155,17 @@ private boolean validateCandidate(DiscoveryNode candidate) {
 
             List<DiscoveryStrategy> discoveryStrategies = new ArrayList<DiscoveryStrategy>();
             for (DiscoveryStrategyFactory factory : factories) {
+                //as a side-effect the buildDiscoveryStrategy() removes a config of the created strategy
                 DiscoveryStrategy discoveryStrategy = buildDiscoveryStrategy(factory, discoveryStrategyConfigs);
                 if (discoveryStrategy != null) {
                     discoveryStrategies.add(discoveryStrategy);
                 }
             }
+            if (!discoveryStrategyConfigs.isEmpty()) {
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: Can't we just compare `discoveryStrategies.size() < discoveryStrategyConfigs.size()` instead of modifying the config object?

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: it's certainly possible. then you'd need to run additional logic to produce a sensible error message. I don't think it's worth it.

File: hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java (hunk 1 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: good catch, thanks!

File: hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: I agree with David. It isn't nice if an object gets modified in a verification method.

File: hazelcast/src/test/java/com/hazelcast/spi/discovery/DiscoverySpiTest.java [hunk 3]
```diff
@@ -96,6 +97,21 @@
     private static final MemberVersion VERSION = MemberVersion.of(BuildInfoProvider.getBuildInfo().getVersion());
     private static final ILogger LOGGER = Logger.getLogger(DiscoverySpiTest.class);
 
+
+    @Test(expected = InvalidConfigurationException.class)
+    public void test_discoveryStrategyFailFastWhenStrategyClassnameDoesNotExist() {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/discovery/DiscoverySpiTest.java]: whenStrategyClassNameNotExist_thenFailFast.

File: hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java (hunk 2 above)
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: I think it should be quite easy to accomplish. Currently we iterate in this order:
```java
for (DiscoveryStrategyFactory factory : factories) {
   for (DiscoveryStrategyConfig config : discoveryStrategyConfigs) {
   }
}
```
If we switch those loops, we should be able to directly throw the exception, when no factory was found for a configuration (right now that `return null` in `buildDiscoveryStrategy()` is not an immediate error, since the next factory could be the matching one).

Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: Just a draft (untested):
```java
            List<DiscoveryStrategy> discoveryStrategies = new ArrayList<DiscoveryStrategy>();
            for (DiscoveryStrategyConfig config : discoveryStrategyConfigs) {
                DiscoveryStrategy discoveryStrategy = buildDiscoveryStrategy(config, factories);
                discoveryStrategies.add(discoveryStrategy);
            }
            return discoveryStrategies;
```
```java
    private DiscoveryStrategy buildDiscoveryStrategy(DiscoveryStrategyConfig config, List<DiscoveryStrategyFactory> factories) {
        String factoryClassName = getFactoryClassName(config);
        for (DiscoveryStrategyFactory factory : factories) {
            Class<? extends DiscoveryStrategy> discoveryStrategyType = factory.getDiscoveryStrategyType();
            String className = discoveryStrategyType.getName();
            if (className.equals(factoryClassName)) {
                Map<String, Comparable> properties = buildProperties(factory, config, className);
                return factory.newDiscoveryStrategy(discoveryNode, logger, properties);
            }
        }
        throw new ValidationException("There is no factory to create these strategies...");
    }
```

Comment (Donnerbart) [reply hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: Any progress on this one?

Comment (jerrinot) [reply hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java]: thanks for a reminder. I'll push an update today.

**Comment by tkountis** [comment]
@jerrinot any update on this one ?

**Comment by jerrinot** [comment]
just pushed an update

**Comment by jerrinot** [comment]
run-lab-run
