### PR TITLE
Fix for #6080

### LINKED ISSUE #6080: Inconsistent and potentially buggy design in BasicCompletableFuture
While working on a follow up of the #6062 together with Marko we've noticed some inconsistent and potentially buggy design in BasicCompletableFuture.
A pull request with an Unit Test will document what is meant here.

We've also came up with a couple of improvements that may be done in BasicCompletableFuture and AbstractCompletableFuture as soon as #6062 is merged.

### PR DESCRIPTION
**Pull request by tombujok**
Follow up on #6020 #6062 and #6081; Fixes #6080

Key points:
* All the Futures extending AbstractCompletableFuture have been refactored in order to take advantage of the features added to AbstractCompletableFuture. Thus, all the latches and synchronisation mechanisms could have been removed making the code of a couple of Future's much simpler. 
* BasicCompletableFuture has been fixed, documented, unit-tested and made more "digestible".
* After all classes that extend AbstractCompletableFuture had been refactored the class itself was also modified to make some methods final / protected and basically to keeps its state "more" secure. There have also been some minor fixes in the get() or getResult() methods

### CODE REVIEW

File: hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java [hunk 1]
```diff
@@ -269,25 +261,10 @@ public boolean cancel(boolean mayInterruptIfRunning) {
...
         @Override
-        public boolean isCancelled() {
-            return cancelled;
-        }
-
-        @Override
-        public void setResult(Object result) {
+        protected void setResult(Object result) {
             super.setResult(result);
-            latch.countDown();
```
Comment (mtopolnik) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java]: The entire `setResult` shoudl be deleted now.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java [hunk 2]
```diff
@@ -130,6 +131,13 @@ public boolean cancel(boolean mayInterruptIfRunning) {
                 return false;
             }
 
+            if (shouldCancel == null) {
+                shouldCancel = shouldCancel(mayInterruptIfRunning);
+                if (!shouldCancel) {
+                    return false;
+                }
+            }
+
```
Comment (mtopolnik) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: For me this would be clearer if the local variable was `alreadyAskedShouldCancel` or similar because you only check the actual `shouldCancel` result once. Currently the semantics of the tri-state variable are confusing.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java [hunk 3]
```diff
@@ -161,17 +181,23 @@ public boolean isCancelled() {
...
-            return get(Long.MAX_VALUE, TimeUnit.MILLISECONDS);
-        } catch (TimeoutException e) {
-            logger.severe("Unexpected timeout while processing " + this, e);
-            return null;
+    public final V get() throws InterruptedException, ExecutionException {
+        for (; ; ) {
+            try {
+                return get(Long.MAX_VALUE, TimeUnit.MILLISECONDS);
+            } catch (TimeoutException e) {
+            }
```
Comment (mtopolnik) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: To forestall future raised eyebrows and suspicion, maybe add a comment here, such as: 
```
 // A timeout here can only be a spurious artifact.
 // It should never happen and even if it does, we must retry.
```

File: hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java (hunk 1 above)
Comment (tombujok) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java]: Unfortunately it's used in line 120 and 133, so I can't get rid of it completely

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java (hunk 3 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: Done

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java (hunk 2 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: Argh, this wasn't actually meant to be like this. Thx for spotting.  I fixed it - it's called once only but the result should be saved for next iterations should the first one fail to set the result.
```
if (shouldCancel == null) {
                shouldCancel = shouldCancel(mayInterruptIfRunning);
            }
            if (!shouldCancel) {
                return false;
            }
```

File: hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java (hunk 1 above)
Comment (mtopolnik) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java]: I don't get it... if you delete `@Override protected setResult(x) { super.setResult(x); }`, you should be able to continue using it just the same, unless there's another class in the same package that wants to call `setResult` from the outside.

Comment (tombujok) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapReduceProxy.java]: It's kind of an SCJP-style problem :) 
These are two independent inner classes (ClientJob & ClientCompletableFuture) that are based in one outer class (ClientMapReduceProxy).
ClientJob can't access a protected method from ClientCompletableFuture's super class (AbstractCompletableFuture) since it's neither in AbstractCompletableFuture's package nor in it's inheritance tree.
However, ClientJob could access ClientCompletableFuture's protected method since they are both located in the same outer class, thus we need this setResult() method.

**Comment by tombujok** [comment]
verify

**Comment by tombujok** [comment]
verify

**Comment by metanet** [comment]
:+1:
