### PR TITLE
Fix NPE thrown in MasterJobContext#onStartExecutionComplete

### LINKED ISSUE #19428: NullPointerException (Target is required! Preconditions.java:59). (SenderTasklet.call(SenderTasklet.java:114).  (JobTerminateRequestedException.java:28) (ProcessorTasklet.java:629)
5.0-SNAPSHOT (20210827 - 7e99ac3, 4dadc2d) starting
#### Remaining Ones
jet split brain test /disk1/workspace/split-x/5.0-SNAPSHOT/2021_08_27-09_37_33/jet
```
./output/HZ/HzMember2HZAA/out.txt-SEVERE: [10.0.0.144]:5701 [HZ] [5.0-SNAPSHOT] Target is required!
./output/HZ/HzMember2HZAA/out.txt:java.lang.NullPointerException: Target is required!
./output/HZ/HzMember2HZAA/out.txt:	at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:59)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OutboundOperationHandler.send(OutboundOperationHandler.java:45)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl.send(OperationServiceImpl.java:466)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.verifyClusterInformation(JobExecutionService.java:456)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.JobExecutionService.runLightJob(JobExecutionService.java:329)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.operation.InitExecutionOperation.doRun(InitExecutionOperation.java:93)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:196)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:249)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:214)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipant(LightMasterContext.java:220)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.LightMasterContext.invokeOnParticipants(LightMasterContext.java:206)
./output/HZ/HzMember2HZAA/out.txt-	at com.hazelcast.jet.impl.LightMasterContext.<init>(LightMasterContext.java:137)
```

```
SEVERE: [10.0.0.91]:5701 [HZ] [5.0-SNAPSHOT] job '06b5-fdbb-8a25-0005', execution 06b5-fdbb-8a25-0005 encountered an exception in Processor.close(), ignoring it
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.close(ProcessorTasklet.java:629)
	at com.hazelcast.jet.impl.execution.ExecutionContext.completeExecution(ExecutionContext.java:246)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$completeExecution$559b0d71$1(JobExecutionService.java:528)
	at com.hazelcast.jet.function.RunnableEx.run(RunnableEx.java:31)
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:516)
	at com.hazelcast.jet.impl.JobExecutionService.completeExecution(JobExecutionService.java:528)
	at com.hazelcast.jet.impl.JobExecutionService.lambda$beginExecution0$14(JobExecutionService.java:593)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

#### Resolved Ones

```
Aug 27, 2021 9:41:57 AM com.hazelcast.jet.impl.EnterpriseMasterContext
SEVERE: [10.0.0.91]:5701 [HZ] [5.0-SNAPSHOT] Exception during callback
java.lang.NullPointerException
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.onStartExecutionComplete(MasterJobContext.java:602)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:473)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1563)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
 which is addressed on #19460

```
Aug 27, 2021 10:31:37 AM com.hazelcast.jet.impl.execution.TaskletExecutionService
WARNING: [10.0.0.64]:5701 [HZ] [5.0-SNAPSHOT] Exception in SenderTasklet{ordinal=0, destinationAddress=[10.0.0.204]:5701, sourceVertexName='Index(IMap[partitioned.mapBak1HD_put-addidx])'}
java.lang.NullPointerException
	at com.hazelcast.jet.impl.execution.SenderTasklet.call(SenderTasklet.java:114)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 
which is addressed on #19471 (I think it's ready to merge)

### PR DESCRIPTION
**Pull request by ufukyilmaz**
This PR fixes the NPE that is thrown in the callback of
`StartExecutionOperation`.

See the stack trace:
```
Aug 27, 2021 9:41:57 AM com.hazelcast.jet.impl.EnterpriseMasterContext
SEVERE: [10.0.0.91]:5701 [HZ] [5.0-SNAPSHOT] Exception during callback
java.lang.NullPointerException
	at com.hazelcast.jet.impl.exception.JobTerminateRequestedException.<init>(JobTerminateRequestedException.java:28)
	at com.hazelcast.jet.impl.MasterJobContext.onStartExecutionComplete(MasterJobContext.java:602)
	at com.hazelcast.jet.impl.MasterJobContext.lambda$invokeStartExecution$6(MasterJobContext.java:473)
	at com.hazelcast.jet.impl.MasterContext.lambda$invokeOnParticipant$3(MasterContext.java:312)
	at com.hazelcast.jet.impl.util.ExceptionUtil.lambda$withTryCatch$0(ExceptionUtil.java:172)
	...
```

Consider this scenario that this NPE occurs:

- InitExecutionOperation's are performed on all of the members
- Split brain is occurred and master sends some member removed
events (MembershipEvents) to the members and simultaneously
 invokes StartExecutionOperations on members 
- On some of the members, the member removal handling took place
before the start execution operation and cancelled the local execution
there. Then, it throws `ExecutionNotFoundException` after it couldn't
find a running execution in `StartExecutionOperation`.

In this case, requestedTerminationMode becomes null and we get NPE
while handling this `ExecutionNotFoundException`. I made this
 `onStartCallback` to handle this case as if it had unexpected failure.

Partly fixes #19428

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [x] Request reviewers if possible

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 1]
```diff
@@ -595,10 +595,15 @@ private void onStartExecutionComplete(Throwable error, Collection<Entry<MemberIn
...
+                // If the StartExecutionOperation didn't find the execution and requestedTerminationMode
+                // is not null it means that we must have cancelled it.
                 // Let's pretend that the StartExecutionOperation returned JobTerminateRequestedException
-                assert requestedTerminationMode != null && !requestedTerminationMode.isWithTerminalSnapshot();
+                // Note that the local execution cancellation need not be performed only on
+                // an explicit user cancellation request. In this case, requestedTerminationMode
+                // becomes null. For example, this local cancellation can happen in
+                // JobExecutionService#onMemberRemoved. We will continue to handle these cases as if we
+                // would handle an unspecific exception
                 error = new JobTerminateRequestedException(requestedTerminationMode);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:607]: We must actually use something else because the `requestedTerminationMode` is null:
```suggestion
                TerminationMode mode = this.requestedTerminationMode;
                error = new JobTerminateRequestedException(mode != null ? mode : CANCEL_FORCEFUL);
```

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 2]
```diff
@@ -595,10 +595,15 @@ private void onStartExecutionComplete(Throwable error, Collection<Entry<MemberIn
...
+            if (error instanceof ExecutionNotFoundException && requestedTerminationMode != null) {
+                // If the StartExecutionOperation didn't find the execution and requestedTerminationMode
+                // is not null it means that we must have cancelled it.
                 // Let's pretend that the StartExecutionOperation returned JobTerminateRequestedException
-                assert requestedTerminationMode != null && !requestedTerminationMode.isWithTerminalSnapshot();
+                // Note that the local execution cancellation need not be performed only on
+                // an explicit user cancellation request. In this case, requestedTerminationMode
+                // becomes null. For example, this local cancellation can happen in
+                // JobExecutionService#onMemberRemoved. We will continue to handle these cases as if we
+                // would handle an unspecific exception
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:606]: The comment contradicts itself: "it means that we must have cancelled it" and then "it might not be only us cancelling it, but also `onMemberRemoved`".

```java
                // If the StartExecutionOperation didn't find the execution, it means that it was cancelled.
                // This can be either because the master cancelled it, or it can also happen that some participant
                // left and the target cancelled the execution locally in JobExecutionService.onMemberRemoved().
                // Let's pretend that the StartExecutionOperation returned JobTerminateRequestedException.
```

**Review by viliam-durina — CHANGES_REQUESTED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (ufukyilmaz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:607]: I changed the condition of the if block above. In this null case, I was throwing the `ExecutionNotFoundException` without changing it rather than a `JobTerminateRequestedException` so that a execution failure would occur. Maybe I can add an else block and turn this `ExecutionNotFoundException`  into a more understandable exception. What do you think if I convert it to `TopologyChangedException`?

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 2 above)
Comment (ufukyilmaz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: I split the comment block and updated the comment as you wanted. Thanks for the suggestion.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: Ah, sorry, I missed that. Translating exceptions to other exceptions in general is dangerous - it often only confuses the failure analysis.

Now I think what you did is maybe the best option. If the exception was not found and we requested a cancellation, then we can convert. If we didn't request the cancellation, maybe it's better to keep the original exception.

Maybe it would be even good to put the ENFE as a cause of the JTRE.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 3]
```diff
@@ -596,10 +596,17 @@ private void onStartExecutionComplete(Throwable error, Collection<Entry<MemberIn
...
             if (error instanceof ExecutionNotFoundException) {
-                // If the StartExecutionOperation didn't find the execution, it means that we must have cancelled it.
-                // Let's pretend that the StartExecutionOperation returned JobTerminateRequestedException
-                assert requestedTerminationMode != null && !requestedTerminationMode.isWithTerminalSnapshot();
-                error = new JobTerminateRequestedException(requestedTerminationMode);
+                // If the StartExecutionOperation didn't find the execution, it means that it was cancelled.
+                if (requestedTerminationMode != null) {
+                    // This cancellation can be because the master cancelled it upon to a user
+                    // request. Let's pretend that case as the StartExecutionOperation returned
+                    // JobTerminateRequestedException.
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:603]:
```suggestion
                    // This cancellation can be because the master cancelled it. If that's the case, convert the exception
                    // to JobTerminateRequestedException.
```

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 4]
```diff
@@ -596,10 +596,17 @@ private void onStartExecutionComplete(Throwable error, Collection<Entry<MemberIn
...
+                    error = new JobTerminateRequestedException(requestedTerminationMode);
+                }
+                // The cancellation can also happen that some participants left and
+                // the target cancelled the execution locally in JobExecutionService.onMemberRemoved().
+                // Since this is an unexpected cancellation, we don't turn it into a post-handled
+                // exception type and let the execution complete with failure.
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:609]:
```suggestion
                // The cancellation can also happen if some participant left and
                // the target cancelled the execution locally in JobExecutionService.onMemberRemoved().
                // We keep this (and possibly other) exceptions as they are
                // and let the execution complete with failure.
```

**Review by viliam-durina — APPROVED** [review]

**Review by gurbuzali — APPROVED** [review]
