### PR TITLE
Do not check split-brain-protected presence when not enabled in config

### LINKED ISSUE #16507: Quorum enabled="false" does not affect
Declarative quorum configuration for hazelcast member has **enabled** flag. When it is **false**, I simply expect to have not split brain protection. When the cluster size is less than **quorum-size**, hazelcast client still gets **QuorumException** for the map which has reference for this quorum definition.

    <quorum name="quorumRule" enabled="false">
        <quorum-size>2</quorum-size>
        <quorum-type>READ_WRITE</quorum-type>
    </quorum>

```
com.hazelcast.quorum.QuorumException: Split brain protection exception: quorumRuleForMaps has failed!
	at com.hazelcast.quorum.impl.QuorumImpl.newQuorumException(QuorumImpl.java:262)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:257)
	at com.hazelcast.quorum.impl.QuorumImpl.ensureQuorumPresent(QuorumImpl.java:252)
	at com.hazelcast.quorum.impl.QuorumServiceImpl.ensureQuorumPresent(QuorumServiceImpl.java:224)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureQuorumPresent(OperationRunnerImpl.java:287)
```

Hazelcast version: **3.12.3**

### PR DESCRIPTION
**Pull request by mdogan**
Fixes #16507

### CODE REVIEW

**Comment by mdogan** [comment]
Unrelated test failure: https://github.com/hazelcast/hazelcast/issues/16512

File: hazelcast/src/test/java/com/hazelcast/splitbrainprotection/SplitBrainProtectionTest.java [hunk 1]
```diff
@@ -53,6 +53,26 @@
...
+
+        MapConfig mapConfig = new MapConfig(randomMapName())
+                .setSplitBrainProtectionName(disabledSBPName);
+
+        Config config = new Config()
+                .addSplitBrainProtectionConfig(disabledSBPConfig)
+                .addMapConfig(mapConfig);
+        HazelcastInstance instance = createHazelcastInstance(config);
+
+        SplitBrainProtectionService quorumService = instance.getSplitBrainProtectionService();
```
Comment (blazember) [inline hazelcast/src/test/java/com/hazelcast/splitbrainprotection/SplitBrainProtectionTest.java]: Uber-minor: naming it `splitBrainProtectionService` or simply not extracting the local variable might be a better alternative since it's not called `QuorumService` anymore.

Comment (mdogan) [reply hazelcast/src/test/java/com/hazelcast/splitbrainprotection/SplitBrainProtectionTest.java]: Ah copy-paste from 3.x branch 🤦‍♂
