### PR TITLE
Synced SecondsBasedEntryTaskScheduler to overcome race conditions

### LINKED ISSUE #6141: LeaseLock simulator test hanging, 3-6.SNAPSHOT
I see all 10 threads of all 4 boxes hanging for ever 

```
grep -r --include *.out LeaseLockTest .
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.174.3/54.209.174.3-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.168.17/54.209.168.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.163.81/54.209.163.81-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest$Worker.run(LeaseLockTest.java:64)
./54.209.172.17/54.209.172.17-serverJstack.out:	at com.hazelcast.simulator.tests.concurrent.lock.LeaseLockTest.run(LeaseLockTest.java:48)
```

The line.
```
find ~ -name LeaseLockTest.java | xargs cat -n | grep 64
    64	                    lock.lock(lease, TimeUnit.MILLISECONDS);
```

the essential test code 

```
   24	    public int lockCount = 500;
    25	    public int maxleaseTime = 100;
    26	    public int maxTryTime = 100;
```

```
  56	            while (!testContext.isStopped()) {
    57	                int i = random.nextInt(lockCount);
    58	                ILock lock = targetInstance.getLock(basename+i);
    59
    60	                int lease = 1 + random.nextInt(maxleaseTime);
    61	                int tryTime = 1 + random.nextInt(maxleaseTime);
    62
    63	                if (random.nextBoolean()) {
    64	                    lock.lock(lease, TimeUnit.MILLISECONDS);
    65	                }else {
    66	                    try {
    67	                        lock.tryLock(tryTime, TimeUnit.MILLISECONDS, lease, TimeUnit.MILLISECONDS);
    68	                    } catch (InterruptedException e) {
    69	                        e.printStackTrace();
    70	                    }
    71	                }
    72	            }
```

### PR DESCRIPTION
**Pull request by gurbuzali**
- Removed `flush` and `size` methods from `EntryTaskScheduler` interface since they were not used
- Removed `ScheduleType.SCHEDULE_IF_NEW` since it was not used, no need to maintain something which we do not use.
- Made SecondsBasedEntryTaskScheduler synchronized to overcome race conditions, converted `ConcurrentMap`s to normal maps since they are not necessary anymore.

fixes https://github.com/hazelcast/hazelcast/issues/7094
fixes #6141

### CODE REVIEW

**Comment by gurbuzali** [comment]
unrelated test failure
```
com.hazelcast.client.cache.CacheBasicClientTest.testIteratorDuringRemoval_withoutEviction

Error Message

Without eviction, there should not be `NoSuchElementException`: java.util.NoSuchElementException

Stacktrace

java.lang.AssertionError: Without eviction, there should not be `NoSuchElementException`: java.util.NoSuchElementException
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringRemoval(CacheBasicAbstractTest.java:455)
	at com.hazelcast.cache.CacheBasicAbstractTest.testIteratorDuringRemoval_withoutEviction(CacheBasicAbstractTest.java:464)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/642/

**Comment by gurbuzali** [comment]
run-lab-run

**Comment by gurbuzali** [comment]
also fixes https://github.com/hazelcast/hazelcast/issues/6141

File: hazelcast/src/main/java/com/hazelcast/util/scheduler/SecondsBasedEntryTaskScheduler.java [hunk 1]
```diff
@@ -68,15 +67,15 @@ public int compare(ScheduledEntry o1, ScheduledEntry o2) {
         }
     };
 
-    private final ConcurrentMap<Object, Integer> secondsOfKeys = new ConcurrentHashMap<Object, Integer>(1000);
-    private final ConcurrentMap<Integer, ConcurrentMap<Object, ScheduledEntry<K, V>>> scheduledEntries
-            = new ConcurrentHashMap<Integer, ConcurrentMap<Object, ScheduledEntry<K, V>>>(1000);
+    private final Map<Object, Integer> secondsOfKeys = new HashMap<Object, Integer>(1000);
+    private final Map<Integer, Map<Object, ScheduledEntry<K, V>>> scheduledEntries
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/util/scheduler/SecondsBasedEntryTaskScheduler.java]: we could use `Int2ObjectHashMap` map here

**Comment by jerrinot** [comment]
@gurbuzali: is there any area where this could in theory cause contention? What part of system use the scheduler most intensively?

**Comment by metanet** [comment]
Partition system uses it a lot to schedule migrations, replications etc.

**Comment by gurbuzali** [comment]
Although partition system uses it a lot, it is used only when a partition-mismatch happens or a re-partitioning happens. So it is not a hot-path really.
LockService uses it a lot to release expired locks.

**Comment by metanet** [comment]
yeah, i totally agree that it is not on the hot path. I just pointed a place it has been used

**Comment by gurbuzali** [comment]
queue and replicated-map use it too. replicated-map for entry expiration, queue for cleaning empty queues

**Comment by jerrinot** [comment]
:+1:

**Comment by metanet** [comment]
:+1:

**Comment by pveentjer** [comment]
Have benchmarks been run to see if there is any performance regression?
