### PR TITLE
Decrease local parallelism of processors in JdbcSqlConnector [HZ-1637]

### LINKED ISSUE #22567: Map.clear w/ GenericMapStore and default settings fails w/ small amount of data
**Describe the bug**
When a map is configured with a `GenericMapStore`, and `map.clear()` is used, this operation can take longer than expected or even timeout completely on a small amount of data in the map (couple hundred entries). This is with the default Hikari CP settings. Errors observed in the logs are (full log attached):

Member:
```
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.hazelcast.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
        at com.hazelcast.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
        at com.hazelcast.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
        at com.hazelcast.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at com.hazelcast.datastore.impl.CloseableDataSource.getConnection(CloseableDataSource.java:53)
        at com.hazelcast.jet.sql.impl.connector.jdbc.SelectProcessorSupplier.lambda$get$d66573d5$1(SelectProcessorSupplier.java:80)
        at com.hazelcast.function.SupplierEx.get(SupplierEx.java:45)
        at com.hazelcast.jet.impl.connector.ReadJdbcP.init(ReadJdbcP.java:126)
...
```

Client (where `map.clear()` is executed):
```
Exception in thread "main" com.hazelcast.client.UndefinedErrorCodeException: Class name: com.hazelcast.sql.HazelcastSqlException, Message: com.hazelcast.jet.JetException: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08d2-d01b-08ae-0001/Select (people)#0}: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.hazelcast.client.UndefinedErrorCodeException.wrap(UndefinedErrorCodeException.java:64)
        at com.hazelcast.client.UndefinedErrorCodeException.wrap(UndefinedErrorCodeException.java:34)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:110)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95)
        at com.hazelcast.client.impl.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:40)
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
        at com.hazelcast.client.impl.spi.ClientProxy.invoke(ClientProxy.java:215)
        at com.hazelcast.client.impl.proxy.ClientMapProxy.clear(ClientMapProxy.java:1665)
        at com.qe.TimerClient.main(TimerClient.java:124)
```

Also note: `com.hazelcast.client.UndefinedErrorCodeException` doesn't look so good. This error should be defined, and a helpful hint may be provided to the user if possible.

**Expected behavior**
Should complete `map.clear()` in a "reasonable" amount of for a such a small data set (single-digit seconds or less). The loading of the same data happens much faster.

**To Reproduce**
Prerequisite: a database with an existing table that can be used with a `GenericMapStore`-backed `IMap`. In my setup, I'm using a Postgres docker container w/ port 5432 published to the host. HZ member and client are both running on the host machine directly.

1. Start a member with `external-data-store` and `map` configured similar to the below example
2. Load some data into the map. It can be from external store (i.e. `MapLoader.loadAll()`) or `IMap` put/set. In my case 200 entries caused the `clear()` to fail consistently. With smaller numbers, the issue was intermittent but the operation still takes long to complete, and HikariCP timeouts are still observed on the member side.
3. Run `IMap.clear()` from the client
4. Observe the timeout exceptions like those listed above

config:
```
    <map name="people">
        <map-store enabled="true">
            <class-name>com.hazelcast.mapstore.GenericMapStore</class-name> 
            <properties>
                <property name="external-data-store-ref">postgres</property> 
            </properties>
        </map-store>
    </map>
    <external-data-store name="postgres">
        <class-name>com.hazelcast.datastore.JdbcDataStoreFactory</class-name>
        <properties>
            <property name="jdbcUrl">jdbc:postgresql://127.0.0.1:5432/test</property>
            <property name="username">postgres</property>
            <property name="password">***</property>
        </properties>
    </external-data-store>
```

**Additional context**

[member.log](https://github.com/hazelcast/hazelcast/files/9839332/member.log)

### PR DESCRIPTION
**Pull request by frant-hartm**
The call to `Map#clear` with enabled `MapStore` results in at least 1 call to `MapStore#deleteAll` for each partition.  The ultimate fix would be to add `MapStore#deleteAll` method, but the benefit of such API in MapStore is unclear.

However, it made the following issue visible:

When not explicitly set via forceTotalParallelismOne or setLocalParallelism the local parallelism default value is larger than
1. This results in 2 or more processors being created for each insert/update/delete/sink into.  Each processor requests a connection from a pool. It is possible that 2 concurrently running queries borrow 1 connection each, exhausting the pool and resulting in a deadlock, which ends after a 30 s timeout (default) from the connection pool.

It is arguably a user error that the connection pool size is too low, but with localParallelism>1 it is really easy to hit this issue (as seen in the `Map#clear`)

Also, it is theoretically possible to hit this issue across multiple members (the processor on one member successfully obtains a connection from the pool, but waits on another member and vice versa), but I didn't manage to reproduce this, so I didn't focus on fixing that issue.

In the future, we can make this behaviour smarter for insert/sink into or update/delete which have input and could make use of higher local parallelism.

Fixes #22567

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

**Review by TomaszGaweda — COMMENTED** [review]
Theoretically it should be executed on 1 member, but I guess it's a different pool, so little risk or exhausting connections.

I'm not very convinced why `insert` has localParallelism=1 and not update, sink into and delete. IMHO all of them should have the same value, am I wrong?

**Comment by frant-hartm** [comment]
So after this PR we have the following:
- SELECT - always uses forceTotalParallelismOne, no risk of deadlock
- UPDATE/DELETE - depending if they have input or not they either use forceTotalParallelismOne
https://github.com/hazelcast/hazelcast/blob/4f741f94c13d509f6255d2e317fb200db48aa03f/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L450-L465
or LP=1 already
https://github.com/hazelcast/hazelcast/blob/4f741f94c13d509f6255d2e317fb200db48aa03f/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java#L466-L470
- INSERT/SINK INTO - runs on all members with LP=1, e.g. stream from kafka into a table, *this PR changes both*

**Review by ldziedziul — APPROVED** [review]

**Review by TomaszGaweda — APPROVED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java [hunk 1]
```diff
@@ -354,7 +354,7 @@ public VertexWithInputConfig insertProcessor(@Nonnull DagBuildContext context) {
                         builder.query(),
                         table.getBatchLimit()
                 )
-        ));
+        ).localParallelism(1));
```
Comment (k-jamroz) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java:357]: this will likely increase run time for larger inserts

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java [hunk 2]
```diff
@@ -501,7 +501,7 @@ public Vertex sinkProcessor(@Nonnull DagBuildContext context) {
                             upsertStatement,
                             jdbcTable.getBatchLimit()
                     )
-            );
+            ).localParallelism(1);
```
Comment (k-jamroz) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/jdbc/JdbcSqlConnector.java:504]: same as above - cap for parallelism increases runtime

**Comment by k-jamroz** [comment]
This change impacts performance of normal SQL queries, not only generic map store.

**Comment by k-jamroz** [comment]
> SELECT - always uses forceTotalParallelismOne, no risk of deadlock

IMO in the future we may implement some strategy to partition such selects, eg. `where id % processorsCount = processorIndex`
