### PR TITLE
Fix MemberReconnectionStressTest  [HZ-1617]

### LINKED ISSUE #22649: com.hazelcast.jet.core.MemberReconnectionStressTest.test
_master_ (commit 470f95b02543901406fa5e3b232545b5faf8b7c8)

Failed on ZingJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK8-nightly/4/testReport/com.hazelcast.jet.core/MemberReconnectionStressTest/test/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.jet.core.JobNotFoundException: Job with id 08df-340e-bca2-0001 not found
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$callWithJob$46(JobCoordinationService.java:924)
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$55(JobCoordinationService.java:1327)
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:807)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:617)
	at com.hazelcast.jet.impl.JobProxy.getStatus0(JobProxy.java:72)
	at com.hazelcast.jet.impl.AbstractJobProxy.getStatus(AbstractJobProxy.java:177)
	at com.hazelcast.jet.core.JetTestSupport.lambda$ditchJob$6(JetTestSupport.java:410)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1338)
	at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:409)
	at com.hazelcast.jet.core.JetTestSupport.shutdownJobsAndGetLeakedClassLoaders(JetTestSupport.java:134)
	at com.hazelcast.jet.core.JetTestSupport.shutdownFactory(JetTestSupport.java:106)
	at sun.reflect.GeneratedMethodAccessor373.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50)
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:807)

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK8-nightly/4/Hazelcast-master-ZingJDK8-nightly-4.zip

### PR DESCRIPTION
**Pull request by orcunc**
- The test was creating two threads but was not stopping them at the end.
- When the test is closed, the test fixture was trying to wait for the result of jobs that did not exist

Fixes #22649

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java [hunk 1]
```diff
@@ -116,5 +120,14 @@ public void test() {
...
         }
+        //Test finished, close the threads
+        try {
+            terminated.set(true);
+
+            connectionThread.join();
+            newJobThread.join();
+        } catch (Exception e) {
+            throw new RuntimeException(e);
+        }
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java:131]: nitpick: We can just add throws Exception to the test.

File: hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java [hunk 2]
```diff
@@ -116,5 +120,14 @@ public void test() {
             }
             sleepMillis(100);
         }
+        //Test finished, close the threads
+        try {
+            terminated.set(true);
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java:125]: I think we can make `terminated` local variable and remove the `after` method completely.

**Review by frant-hartm — CHANGES_REQUESTED** [review]

File: hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java (hunk 1 above)
Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java]: Oj

File: hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java (hunk 2 above)
Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/jet/core/MemberReconnectionStressTest.java]: Ok

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 3]
```diff
@@ -440,28 +444,28 @@ private static void ditchJob0(@Nonnull Job job, @Nonnull HazelcastInstance... in
                     job.join();
                 } catch (JobNotFoundException e) {
                     SUPPORT_LOGGER.fine("Job " + job.getIdString() + " is gone.");
-                    return;
+                    return false;
```
Comment (krzysztofslusarski) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:447]: We managed to execute ```cancel()```, but we fail on ```join()```. Shouldn't we treat it as successful ditch and return ```true```? cc: @frant-hartm

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 4]
```diff
@@ -440,28 +444,28 @@ private static void ditchJob0(@Nonnull Job job, @Nonnull HazelcastInstance... in
...
                 } catch (CompletionException e) {
                     if (e.getCause() instanceof JobNotFoundException) {
                         SUPPORT_LOGGER.fine("Job " + job.getIdString() + " is gone.");
-                        return;
+                        return false;
```
Comment (krzysztofslusarski) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:451]: Same here

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java (hunk 3 above)
Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:447]: After ditch0() call, the test suite is trying to assert that the job is not runnning. Therefore any JobNotFoundException in ditch0() is a failed ditch.

Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java]: I've added a try/catch block to the  assertTrueEventually() that checks if the job is running or not. There is no need to check the return result of ditchJob0().

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 5]
```diff
@@ -404,15 +404,21 @@ public void cleanUpCluster(HazelcastInstance... instances) {
...
+            //If a member throws exception ignore it
+            try {
+                assertNotEquals(RUNNING, job.getStatus());
+                for (HazelcastInstance instance : instances) {
+                    Job instanceJob = instance.getJet().getJob(job.getId());
+                    if (instanceJob != null) {
+                        assertNotEquals(RUNNING, instanceJob.getStatus());
+                    }
                 }
+            } catch (Exception ignored) {
```
Comment (krzysztofslusarski) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:421]: Maybe we should log the exception here? I would also prefer to try/catch in the ```for``` loop. Right now if one member throws we do wait for stopping the job on the other member.

**Review by krzysztofslusarski — CHANGES_REQUESTED** [review]

**Review by frant-hartm — APPROVED** [review]

**Comment by frant-hartm** [comment]
Approved, but krzysztof's comment needs to be addressed.

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java (hunk 5 above)
Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java]: I have changed the code to catch exception for each member check

**Review by krzysztofslusarski — APPROVED** [review]
