### PR TITLE
Extract migration queue from InternalPartitionServiceImpl

### LINKED ISSUE #7191: ClusterRollingRestartTest.test_rollingRestart[clusterState:FROZEN,partitionAssignmentType:NEVER]
```
java.lang.AssertionError: Cluster size is not correct. Expected: 3 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:694)
	at com.hazelcast.test.HazelcastTestSupport$10.run(HazelcastTestSupport.java:713)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:835)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:709)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:704)
	at com.hazelcast.cluster.impl.ClusterRollingRestartTest.test_rollingRestart(ClusterRollingRestartTest.java:86)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.8/78/com.hazelcast$hazelcast/testReport/com.hazelcast.cluster.impl/ClusterRollingRestartTest/test_rollingRestart_clusterState_FROZEN_partitionAssignmentType_NEVER_/

### PR DESCRIPTION
**Pull request by metanet**
Extract management of migrations tasks into a separate class. It makes it easier to manage migration state of the partition service. It also solves the race problem occurs during starting a migration task polled from the migration queue. 

Fixes #7191

### CODE REVIEW

**Comment by metanet** [comment]
run-lab-run

**Comment by mdogan** [comment]
:+1:

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java [hunk 1]
```diff
@@ -2102,15 +2102,22 @@ public void run() {
...
-            for (; ; ) {
+            for (; ;) {
                 if (!isMigrationAllowed()) {
                     break;
                 }
-                Runnable r = migrationQueue.poll(1, TimeUnit.SECONDS);
+
+                Runnable r = migrationQueue.peek();
                 if (r == null) {
+                    Thread.sleep(100);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: We are not checking 10 more frequent than before? Because initially the frequency was 1/second and now 10/second.

**Comment by pveentjer** [comment]
Could you add a short explanation of the race?

**Comment by metanet** [comment]
MigrationThread polls a migration task from migrationQueue and sets the migrating flag but this is not an atomic operation. hasOnGoingMigrationLocal() returns false when a migration task is polled from the queue but the flag is not set yet. This fix first sets the flag before polling the task from the queue.

**Comment by metanet** [comment]
@pveentjer pr description is updated

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 1 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: @metanet ping.

Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: Before this change, ``poll()`` is used with 1 second of timeout. So if there is no migration task, it will be checked every 1 second. Once a migration task is put into the queue, it will be polled immediately. I used 100 ms sleep duration to get the migration task without too much delay.

**Comment by pveentjer** [comment]
Sorry for my stupidity; so apparently another thread than the MigrationThread is suffering from this non atomic behavior. And this thread makes the wrong conclusion; it thinks there are no migrations since the flag isn't set, but actually there are migrations. Is my understanding correct?

Which thread is this other thread?
What are the consequences of this race?

**Comment by metanet** [comment]
Any code that checks about the safety of the partitions may think that there is no migration while there is a migration task to be runned. For example, instance shut down.

**Comment by pveentjer** [comment]
But if the calling code would have called e.g. just before the MigrationThread would have done its work, it would also see a 'stale' value since the flag hasn't been set. So why is it important that the other threads needs to see 'the most actual' value?

**Comment by metanet** [comment]
There are 2 cases:
1) There is migration task in the queue
2) Migration task is polled from the queue and being run

For both of these cases, ``hasOnGoingMigrationLocal()``, which can be called by any other thread,must return true. Between step 1 and step 2, there is a race which is fixed by this test.

**Comment by pveentjer** [comment]
Sorry for my never ending stupidity. Would it not make sense to have an AtomicLong that is incremented with every migration task and decremented when a tasks is completed? To check if there are ongoing migration, check if the value > 0. 

My lack of understanding the threading for this particular section is causing problems.

**Comment by metanet** [comment]
Np. That was our other solution but it creates its own problems because for some parts of the codes, migrationQueue is updated within a lock; for some other parts, it is updated without a lock. 

We will refactor these parts while working on partition service for 3.7

**Comment by pveentjer** [comment]
So something like this:

'''
 private class MigrationThread extends Thread implements Runnable {
        private final long sleepTime = max(250L, partitionMigrationInterval);
        private final AtomicLong migrationTaskCount = new AtomicLong();

        MigrationThread(Node node) {
            super(node.getHazelcastThreadGroup().getInternalThreadGroup(),
                    node.getHazelcastThreadGroup().getThreadNamePrefix("migration"));
        }

        @Override
        public void run() {
            try {
                while (!isInterrupted()) {
                    doRun();
                }
            } catch (InterruptedException e) {
                if (logger.isFinestEnabled()) {
                    logger.finest("MigrationThread is interrupted: " + e.getMessage());
                }
            } catch (OutOfMemoryError e) {
                OutOfMemoryErrorDispatcher.onOutOfMemory(e);
            } finally {
                migrationQueue.clear();
            }
        }
        
        private void doRun() throws InterruptedException {
            for (; ; ) {
                if (!isMigrationAllowed()) {
                    break;
                }
                Runnable r = migrationQueue.poll(1, TimeUnit.SECONDS);
                if (r == null) {
                    break;
                }

                processTask(r);
                if (partitionMigrationInterval > 0) {
                    Thread.sleep(partitionMigrationInterval);
                }
            }
            boolean hasNoTasks = migrationQueue.isEmpty();
            if (hasNoTasks) {
                if (migrating) {
                    migrating = false;
                    logger.info("All migration tasks have been completed, queues are empty.");
                }
                evictCompletedMigrations();
                Thread.sleep(sleepTime);
            } else if (!isMigrationAllowed()) {
                Thread.sleep(sleepTime);
            }
        }
        private void postTask(Runnable task){
            if(task instanceof MigrateTask){
                migrationTaskCount.incrementAndGet();
            }
            migrationQueue.add(task);
        }
        boolean processTask(Runnable r) {
            if (r == null || isInterrupted()) {
                return false;
            }

            try {
                r.run();
            } catch (Throwable t) {
                logger.warning(t);
            }

            if(r instanceof MigrateTask){
                migrationTaskCount.decrementAndGet();
            }

            return true;
        }

        void stopNow() {
            migrationQueue.clear();
            interrupt();
        }

        boolean isMigrating() {
            return migrationTaskCount.get()>0;
        }
    }
'''

**Comment by pveentjer** [comment]
After a short discussion with Basri, the solution with the counter makes sense to some point. However there is a lot of complex queue interaction like clear which could leave the counter in a permanently inconsistent state. I'll do some more thinking.

**Comment by pveentjer** [comment]
@metanet I currently have a bunch of other tasks on my plate. Please have a look at the following code that should simplify the logic.

```
 static class MigrationQueue {
        private final AtomicInteger migrationTaskCount = new AtomicInteger();
        private final BlockingQueue<Runnable> taskQueue = new LinkedBlockingQueue<Runnable>();

        public Runnable poll(int timeout, TimeUnit unit) throws InterruptedException {
            return taskQueue.poll(timeout, unit);
        }

        public void add(Runnable task){
            if(task instanceof MigrateTask){
                migrationTaskCount.incrementAndGet();
                taskQueue.add(new MigrationTaskWrapper((MigrateTask)task));
            }else{
                taskQueue.add(task);
            }
        }

        public void clear() {
            List<Runnable> sink = new LinkedList<Runnable>();
            taskQueue.drainTo(sink);

            for(Runnable task: sink){
                if(task instanceof MigrateTask){
                    migrationTaskCount.decrementAndGet();
                }
            }
        }

        public boolean hasMigrations(){
            return migrationTaskCount.get()>0;
        }

        public boolean isEmpty() {
            return taskQueue.isEmpty();
        }

        public int size() {
            return taskQueue.size();
        }

         class MigrationTaskWrapper implements Runnable{
            private final MigrateTask task;

            public MigrationTaskWrapper(MigrateTask task) {
                this.task = task;
            }

            @Override
            public void run() {
                try {
                    task.run();
                }finally {
                    migrationTaskCount.decrementAndGet();
                }
            }
        }
    }
```

**Comment by metanet** [comment]
@pveentjer pr is updated

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java [hunk 2]
```diff
@@ -1254,8 +1252,8 @@ private boolean hasOnGoingMigrationMaster(Level level) {
 
     @Override
     public boolean hasOnGoingMigrationLocal() {
-        return !activeMigrations.isEmpty() || !migrationQueue.isEmpty()
-                || migrationThread.isMigrating();
+        return !activeMigrations.isEmpty() || migrationQueue.isNonEmpty()
+                || migrationQueue.hasMigrations();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: why the complex query? The MigrationQueue knows if there is a MigrationTask pending or executing. So we does activeMigrations and migrationQueue no empty be used?

So why not just:

```
 public boolean hasOnGoingMigrationLocal() {return migrationQueue.hasMigrations();}
```

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java [hunk 3]
```diff
@@ -2130,15 +2124,18 @@ private void doRun() throws InterruptedException {
...
             try {
+                if (r == null || isInterrupted()) {
+                    return false;
+                }
+
                 r.run();
             } catch (Throwable t) {
                 logger.warning(t);
+            } finally {
+                migrationQueue.afterTaskCompletion(r);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: Why did you remove the wrapper task? With the wrapper task all this stuff remains an implementation detail of the queue. Now you have added the complexity to the thread.

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+import static org.junit.Assert.assertTrue;
+import static org.mockito.Mockito.mock;
+
+@Category(QuickTest.class)
+public class MigrationQueueTest {
+
+    private final MigrationQueue migrationQueue = new MigrationQueue();
+
+    @Test
+    public void test_migrationTaskCount_incremented_onMigrateTask() {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: Why does every test have 'test_migrationTaskCount' as prefix? It doesn't seem to add a lot of additional info,

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+        migrationQueue.add(mock(InternalPartitionServiceImpl.MigrateTask.class));
+        migrationQueue.poll(1, TimeUnit.SECONDS);
+
+        assertTrue(migrationQueue.hasMigrations());
+    }
+
+    @Test
+    public void test_migrateTaskCount_decremented_afterMigrateTaskCompleted()
+            throws InterruptedException {
+        final InternalPartitionServiceImpl.MigrateTask migrateTask = mock(InternalPartitionServiceImpl.MigrateTask.class);
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: Can you make this a static import?

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 3 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: `migrationQueue` itself is also a detail, it's directly bound to the partition service. Moving complexity from one side to another doesn't make any difference.

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 2 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: Only master node knows `migrationQueue`, on other nodes it's always empty. `activeMigrations ` check is required for non-master nodes.

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+    public void test_migrateTaskCount_notDecremented_afterNonMigrateTaskCompleted()
+            throws InterruptedException {
+        migrationQueue.add(mock(InternalPartitionServiceImpl.MigrateTask.class));
+        migrationQueue.afterTaskCompletion(mock(Runnable.class));
+
+        assertTrue(migrationQueue.hasMigrations());
+    }
+
+    @Test
+    public void test_migrateTaskCount_decremented_onClear() {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: most test in HZ have the following naming convention:

nameMethod_whenFoo_thenBla.

This makes it very easy to figure out where the test of the method is found and which cases are being tested. 

In this case I would expect the method to be called clear_whenMigrationTaskQueued_thenMigrationCountDecreased

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+        migrationQueue.add(mock(InternalPartitionServiceImpl.MigrateTask.class));
+        migrationQueue.clear();
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: Also add a line of white space between your setup and your action. Even though your test methods are very small, it still helps to see the general structure faster.

File: hazelcast/src/main/java/com/hazelcast/partition/impl/MigrationQueue.java [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+package com.hazelcast.partition.impl;
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.concurrent.BlockingQueue;
+import java.util.concurrent.LinkedBlockingQueue;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicInteger;
+
+class MigrationQueue {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/MigrationQueue.java]: Can you add a few lines of javadoc for other engineers what the purpose is of this class?

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: Probably it would make sense to add some comments to explain to for others.

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java (hunk 7 above)
Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: No, i won't. Test is already too short

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java (hunk 6 above)
Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: This is my preference. Unless there is a strict rule against my preference, i wont change it.

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 3 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: It does. Now you have a mo ecomplex method than needs to be. With the wrapper task approach I have given, this is fully an implementation detail of the MigrationQueue. The logic for this thread is simplified since it doesn't need to do any callbacks to the queue. In my book this is cleaner code since incrementing and decrementing the counter is a implementation detail of the MigrationQueue.

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java (hunk 5 above)
Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: It is a non static inner class

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java (hunk 4 above)
Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: It is just my preference

**Comment by metanet** [comment]
I am done with this pr. I wont make any change related to its style.

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 3 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: If we start to talk things in our books then I think there's no need to discuss about this PR anymore. Discussion here started to become about esthetics and choices, again and again.

File: hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java (hunk 4 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/partition/impl/MigrationQueueTest.java]: Do you think it is wise if we allow everybody to have their own preference when writing a test? Imho it makes code harder to understand. 

We have a test practices page on the wiki where we have a naming approach. If you don't like it and want to improve it, I'm all ear. But imho we should do this consistently using the whole system. I

**Comment by pveentjer** [comment]
There are some other comments that need to be addressed like a few lines  of Javadoc. Just to give the reader a quick understanding of the purpose (providing info of a migration is pending/executing) of the class (don't care about the methods).

File: hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java (hunk 3 above)
Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/partition/impl/InternalPartitionServiceImpl.java]: Partition service already manages the whole migration process. Migration queue is only responsible for managing migration tasks. Therefore, having an extra callback method doesn't seem problematic to me. The other approach, wrapping the given runnable, is also ok but I don't think it is necessary and I want to keep our current approach.

**Comment by metanet** [comment]
I added Javadoc for ``MigrationQueue`` class. I also updated commit message and pr description to make purpose of the pr more understandable. Lastly, I answered your concern about the callback in my reply above.

**Comment by pveentjer** [comment]
Good.

**Comment by pveentjer** [comment]
:+1:
