### PR TITLE
Fix Discovery SPI cluster join when WAIT_SECONDS_BEFORE_JOIN is 0

### LINKED ISSUE #17586: When using Discovery SPI, cluster join only happens via split-brain mechanism
**Describe the bug**
When using `TcpIpJoiner` or `MulticastJoin` methods, everything works correctly,
but when using `networkConfig.getJoin().getDiscoveryConfig().setDiscoveryServiceProvider()` mechanism,
the cluster isn't joined, and the freshly-started node only sees itself.
However, when split brain timeout is reached, the split-brain mechanism is used to join the cluster
NOTE: This only happens when `WAIT_SECONDS_BEFORE_JOIN` is set to zero.

**Expected behavior**
Cluster join should happen on startup time instead of waiting for split-brain logic

**To Reproduce**
- pull https://github.com/flowlogix/hazelcast-issues
- in the directory CacheTester run `mvn -Prun test`
- do the same in an additional window and watch the logs

**Additional context**
Hazelcast version is 4.1-SNAPSHOT (latest)
Java 8
Here are the logs from the second node. First node works as expected:

```
Sep 20, 2020 9:01:18 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.1-SNAPSHOT] Using public address: [127.0.0.1]:5711
Sep 20, 2020 9:01:18 PM com.hazelcast.system
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Hazelcast 4.1-SNAPSHOT (20200920 - 6ed5868) starting at [127.0.0.1]:5711
Sep 20, 2020 9:01:18 PM com.hazelcast.instance.impl.Node
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Using Discovery SPI
Sep 20, 2020 9:01:18 PM com.hazelcast.cp.CPSubsystem
WARNING: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
Sep 20, 2020 9:01:19 PM com.hazelcast.internal.diagnostics.Diagnostics
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
Sep 20, 2020 9:01:19 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] [127.0.0.1]:5711 is STARTING
Sep 20, 2020 9:01:19 PM com.hazelcast.internal.cluster.ClusterService
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5711 - 78f83873-16c2-47e4-8d28-1993c778e9c4 this
]

Sep 20, 2020 9:01:19 PM com.hazelcast.instance.impl.Node
WARNING: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Config seed port is 5710 and cluster size is 1. Some of the ports seem occupied!
Sep 20, 2020 9:01:19 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] [127.0.0.1]:5711 is STARTED
<c> to create cache, <d> to destroy, <p> to print, <l> to lock, <u> to unlock
blank to exit <h> for help, anything else to put in cache ...

*** initial startup, the node sees only itself ***

Sep 20, 2020 9:01:24 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Initialized new cluster connection between /127.0.0.1:64664 and /127.0.0.1:5710
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.impl.ClusterJoinManager
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] We should merge to [127.0.0.1]:5710, both have the same data member count: 1

*** now split-brain merge mechanism activated after the merge timeout ***

Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.impl.DiscoveryJoiner
WARNING: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] [127.0.0.1]:5711 is merging [tcp/ip] to [127.0.0.1]:5710
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Locking cluster state. Initiator: [127.0.0.1]:5711, lease-time: 60000
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.impl.operations.LockClusterStateOp
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Extending cluster state lock. Initiator: [127.0.0.1]:5711, lease-time: 20000
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.impl.operations.CommitClusterStateOp
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Changing cluster state from ClusterState{state=ACTIVE, lock=LockGuard{lockOwner=[127.0.0.1]:5711, lockOwnerId='7972e4d0-186e-45ca-bbf2-3f2ae64e4173', lockExpiryTime=1600653764043}} to ClusterStateChange{type=class com.hazelcast.cluster.ClusterState, newState=FROZEN}, initiator: [127.0.0.1]:5711, transient: false
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.impl.operations.MergeClustersOp
WARNING: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] [127.0.0.1]:5711 is merging to [127.0.0.1]:5710, because: instructed by master [127.0.0.1]:5711
Sep 20, 2020 9:01:24 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] [127.0.0.1]:5711 is MERGING
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.ClusterService
WARNING: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Resetting local member UUID. Previous: 78f83873-16c2-47e4-8d28-1993c778e9c4, new: fbe0e9ae-29f9-4d04-9c7b-231fbd569316
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Connection[id=1, /127.0.0.1:64664->/127.0.0.1:5710, qualifier=null, endpoint=[127.0.0.1]:5710, alive=false, connectionType=MEMBER] closed. Reason: TcpServer is stopping
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.server.tcp.TcpServerConnector
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Connecting to /127.0.0.1:5710, timeout: 10000, bind-any: true
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.server.tcp.TcpServerConnection
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] Initialized new cluster connection between /127.0.0.1:64665 and /127.0.0.1:5710
Sep 20, 2020 9:01:24 PM com.hazelcast.internal.cluster.ClusterService
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] 

Members {size:2, ver:4} [
	Member [127.0.0.1]:5710 - cff4c063-ebf6-458d-8bef-1f819e6947d6
	Member [127.0.0.1]:5711 - fbe0e9ae-29f9-4d04-9c7b-231fbd569316 this
]

Sep 20, 2020 9:01:24 PM com.hazelcast.core.LifecycleService
INFO: [127.0.0.1]:5711 [dev] [4.1-SNAPSHOT] [127.0.0.1]:5711 is MERGED
*** only now the cluster nodes see each other ***
```

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #17586

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/DiscoveryJoiner.java [hunk 1]
```diff
@@ -71,6 +71,10 @@ public DiscoveryJoiner(Node node, DiscoveryService discoveryService, boolean use
 
     @Override
     protected Collection<Address> getPossibleAddressesForInitialJoin() {
+        if (maximumWaitingTimeBeforeJoinSeconds == 0) {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/DiscoveryJoiner.java:74]: Fix is confirmed, thanks for digging to the bottom of this issue @lprimak!

I think the issue was introduced in https://github.com/hazelcast/hazelcast/commit/ffc399a1c07cdb2ea128a0c5158ccc7a00abbe0a which changed `getPossibleAddressesForInitialJoin()`:
- prior to that commit, there was at least 1 call to `getPossibleAddresses` and its result would be returned
- after that commit, it is possible that we do not enter the deadline loop at all and return `Collections.emptyList()` which is wrong

Instead of treating `maximumWaitingTimeBeforeJoinSeconds == 0` as a special case, I 'd rather change this method's logic like this:

```
Collection<Address> possibleAddresses = null;
long deadLine = ... // code continues as is - possibleAddresses can be updated in the for loop
...

return (possibleAddresses == null) ? getPossibleAddresses() : possibleAddresses;
```

wdyt @lprimak ?

Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/DiscoveryJoiner.java:74]: sure, done

**Comment by vbekiaris** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+    @Rule
+    public final OverridePropertyRule overridePropertyRule2 = set(DISCOVERY_SPI_ENABLED.getName(), "true");
+    @Rule
+    public final OverridePropertyRule overridePropertyRule3 = set(WAIT_SECONDS_BEFORE_JOIN.getName(), "0");
+    private TestHazelcastInstanceFactory fact;
+
+    public static class DS implements DiscoveryService  {
+        private static final List<DiscoveryNode> nodes = new ArrayList<>();
+
+        public DS(DiscoveryServiceSettings settings) {
```
Comment (JamesHazelcast) [inline hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java:65]: Nitpick: could we name the class something more descriptive, like `TestDiscoveryService` instead of `DS`

File: hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+@RunWith(HazelcastSerialClassRunner.class)
+@Category(QuickTest.class)
+public class DiscoverySPIJoinTest extends HazelcastTestSupport {
+    @Rule
+    public final OverridePropertyRule overridePropertyRule = set(HAZELCAST_TEST_USE_NETWORK, "true");
+    @Rule
+    public final OverridePropertyRule overridePropertyRule2 = set(DISCOVERY_SPI_ENABLED.getName(), "true");
+    @Rule
+    public final OverridePropertyRule overridePropertyRule3 = set(WAIT_SECONDS_BEFORE_JOIN.getName(), "0");
+    private TestHazelcastInstanceFactory fact;
```
Comment (JamesHazelcast) [inline hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java:60]: Nitpick: could we name this `factory`, since "fact" is a normal word on its own :)

**Review by JamesHazelcast — APPROVED** [review]
Thanks for your contribution @lprimak, we appreciate it.

Just a couple of very small nitpicks from me, but happy to approve regardless.

File: hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java (hunk 3 above)
Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cluster/impl/DiscoverySPIJoinTest.java]: Fixed

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
thanks @lprimak for yet another contribution!
