### PR TITLE
[#12203] Throw an initialization exception when Symmetric Encryption is configured on Hazelcast OS version

### LINKED ISSUE #12203: Throw an initialization exception when Symmetric Encryption is configured on Hazelcast OS version
It's possible to configure symmetric encryption on Hazelcast member in open-source edition. Nevertheless the configuration is silently ignored.

Enabling the Symmetric encryption on an OS member should behave in the same way as enabling security or TLS. The initialization should fail.

```java
    Config cfg = new Config();
    SymmetricEncryptionConfig symmetricEncryptionConfig= new SymmetricEncryptionConfig().setEnabled(true);
    cfg.getNetworkConfig().setSymmetricEncryptionConfig(symmetricEncryptionConfig);
    HazelcastInstance instance = Hazelcast.newHazelcastInstance(cfg);
```

### PR DESCRIPTION
**Pull request by kwart**
Fixes #12203.

This commit applies the fail-fast approach on symmetric-encryption configuration for OS Hazelcast edition.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java [hunk 1]
```diff
@@ -124,6 +125,12 @@ private void checkSecurityAllowed() {
                 throw new IllegalStateException("Security requires Hazelcast Enterprise Edition");
             }
         }
+        SymmetricEncryptionConfig symmetricEncryptionConfig = node.getConfig().getNetworkConfig().getSymmetricEncryptionConfig();
```
Comment (tkountis) [inline hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java]: This is a bit tricky, we just don't allow the use of the feature, but the actual mechanism is still there for anyone to use. I think we could do better, by having this mechanism live in EE.

Comment (kwart) [reply hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java]: If you mean by mechanism the encryption inbound/outbound handlers, then they live in the EE under package `com.hazelcast.nio.tcp`.

Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/instance/DefaultNodeExtension.java]: Yes, my mistake. I misread the issue as if someone could use symmetric on OS. Looks good to me!
