### PR TITLE
Use mock network in ReplicatedMapMergePolicyTest

### LINKED ISSUE #10069: ReplicatedMapMergePolicyTest.testMapMergePolic
```
java.lang.AssertionError: expected:<PutIfAbsentValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.ReplicatedMapMergePolicyTest$1.run(ReplicatedMapMergePolicyTest.java:114)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.replicatedmap.ReplicatedMapMergePolicyTest.testMapMergePolicy(ReplicatedMapMergePolicyTest.java:108)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1276/testReport/junit/com.hazelcast.replicatedmap/ReplicatedMapMergePolicyTest/testMapMergePolicy_PutIfAbsentMapMergePolicy_/

### PR DESCRIPTION
**Pull request by metanet**
Fixes #10069

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java [hunk 1]
```diff
@@ -77,30 +69,38 @@ public void killAllHazelcastInstances() {
     @Parameterized.Parameter
     public ReplicatedMapMergePolicyTestCase testCase;
 
+    private TestHazelcastInstanceFactory factory;
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: `HazelcastTestSupport` already has a `TestHazelcastInstanceFactory` which also stops the created HZ instances. Right now this seems to be missing in the test. I would remove the factory and use the provided methods from `HazelcastTestSupport`.

Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: there is no instance termination in this test class since it is being handled by the `HazelcastTestSupport`, as you say. This one only creates a factory to create instances in the test method. What is the issue here?

Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: The termination can't be handled by `HazelcastTestSupport` if you don't use its factory and methods. You are creating your own factory in the test, those instances will not be terminated.

Remove
```java
private TestHazelcastInstanceFactory factory;

   @Before
    public void init() {
        factory = createHazelcastInstanceFactory(2);
    }
```
and use
```java
        final HazelcastInstance h1 = createHazelcastInstance(config);
        final HazelcastInstance h2 = createHazelcastInstance(config);
```
to create the instances. That should solve the issue (and needs less code).

Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: Termination is being handled by `HazelcastTestSupport.shutdownNodeFactory()` automatically. `HazelcastTestSupport.createHazelcastInstanceFactory()` also sets the created factory class into the internal field so that it will be able to terminate it automatically.

File: hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java [hunk 2]
```diff
@@ -57,11 +54,6 @@
 @Category(NightlyTest.class)
```
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: You can even change category to quicktest .

File: hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java (hunk 1 above)
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: Ah, forget it, sorry. I misread the `createHazelcastInstanceFactory(2)` as `new TestHazelcastInstanceFactory()`.

File: hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java (hunk 2 above)
Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/replicatedmap/ReplicatedMapMergePolicyTest.java]: I couldn't be sure about it because it still takes more than a minute to complete all the tests but I can do it if it is ok
