### PR TITLE
Lazy SQL OBJECT deserialization

### LINKED ISSUE #19281: Deserialize OBJECT columns in SQL result lazily
When the result contains OBJECT field and the client doesn't have the class, it fails when iterating such a row. It should fail only when trying to access the OBJECT field.
```java
class Address { String street, city; }
class Person { String name; Address address;}

SqlResult result = sql.execute("SELECT * FROM person_map");
 // fails with serialization error, if the client doesn't have Address class on the classpath
SqlRow firstRow = result.iterator.next();
// it should not fail above, but here:
Object address = firstRow.getObject("address");
```

### PR DESCRIPTION
**Pull request by gierlachg**
Fixes #19281

### CODE REVIEW

**Comment by mdumandag** [comment]
We should port this change to other clients as well, hence I added the label to auto-create issues

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java [hunk 1]
```diff
@@ -80,16 +76,16 @@ public SqlRowImpl(SqlRowMetadata rowMetadata, Row row, LazyTargetDeserializer la
             LazyTarget res0 = (LazyTarget) res;
 
             if (deserialize) {
-                assert lazyTargetDeserializer != null;
-
-                res = lazyTargetDeserializer.deserialize((LazyTarget) res);
+                res = lazyDeserializer.deserialize((LazyTarget) res);
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java:79]: Minor
```suggestion
                res = lazyDeserializer.deserialize(res0);
```

File: hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlClientResult.java [hunk 2]
```diff
@@ -183,6 +185,16 @@ public void close() {
         }
     }
 
+    @Override
+    public Object deserialize(Object value) {
+        return service.deserializeRowValue(value);
+    }
+
+    @Override
+    public Object deserialize(LazyTarget value) {
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlClientResult.java:194]: Can an object of type `LazyTarget` be received by the client? I am asking this because we didn't have such logic on the non-Java clients

Comment (gierlachg) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlClientResult.java:194]: Doing that is not possible with public API.

**Review by mdumandag — APPROVED** [review]
OK from client perspective

**Review by viliam-durina — COMMENTED** [review]
Can we add some test? We have `sample-pojo-1.0-person.jar` in the test code, you can load an instance of it into some map and ensure that the query fails only when accessing it. You can put it to the value and have a primitive key - you should be able to read the key, but not the value.

**Comment by gierlachg** [comment]
We already have one, see `SqlErrorClientTest`.

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlErrorClientTest.java [hunk 3]
```diff
@@ -296,11 +296,14 @@ public void testRowError_deserialization() {
...
 
-                for (SqlRow ignore : result) {
+                for (SqlRow row : result) {
                     if (first) {
                         BadValue.READ_ERROR.set(true);
 
                         first = false;
+                    } else {
+                        // row values are deserialized lazily, on access
+                        row.getObject("this");
```
Comment (viliam-durina) [inline hazelcast-sql/src/test/java/com/hazelcast/sql/SqlErrorClientTest.java:306]: We should also select `__key` and ensure that we can read it successfully.

This might be more readable:
```java
Iterator it = result.iterator();
SqlRow row = iterator.next();
row.getObject("this");
SqlRow row = iterator.next();
row.getObject("__key"); // suceeds
assertThatThrownBy(() -> row.getObject("this"));
```
