### PR TITLE
Fixes potential NullPointerException when invalidation metadata missing

### LINKED ISSUE #13700: NullPointerException Failed to execute ScheduledFutureTask InvalidationMetaDataFetcher repairUuids
in test

https://hazelcast-l337.ci.cloudbees.com/view/kill/job/kill-members/3/console

is see this logged on the client side.

```
Sep 06, 2018 10:53:48 AM com.hazelcast.client.spi.ClientExecutionService
SEVERE: hz.client_0 [HZ] [3.11-SNAPSHOT] Failed to execute java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2dae9baf
java.lang.NullPointerException
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.repairUuids(InvalidationMetaDataFetcher.java:139)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.processMemberMetadata(InvalidationMetaDataFetcher.java:126)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.fetchMetadata(InvalidationMetaDataFetcher.java:77)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.runAntiEntropyIfNeeded(RepairingTask.java:156)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.run(RepairingTask.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

```
 <connection-strategy async-start="true" reconnect-mode="ASYNC">
        <connection-retry enabled="true">
            <initial-backoff-millis>333</initial-backoff-millis>
            <max-backoff-millis>30000</max-backoff-millis>
            <multiplier>2</multiplier>
        </connection-retry>
    </connection-strategy>
```

```
Sep 06, 2018 10:53:48 AM com.hazelcast.client.map.impl.nearcache.invalidation.ClientMapInvalidationMetaDataFetcher
WARNING: hz.client_0 [HZ] [3.11-SNAPSHOT] Can't extract invalidation meta-data of Member [10.0.0.30]:5701 - 3abd29df-3336-4398-b69a-6d5d877cbaea
java.util.concurrent.ExecutionException: com.hazelcast.client.HazelcastClientOfflineException: Client is offline.
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:109)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:178)
	at com.hazelcast.client.map.impl.nearcache.invalidation.ClientMapInvalidationMetaDataFetcher.extractMemberMetadata(ClientMapInvalidationMetaDataFetcher.java:70)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.processMemberMetadata(InvalidationMetaDataFetcher.java:117)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.fetchMetadata(InvalidationMetaDataFetcher.java:77)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.runAntiEntropyIfNeeded(RepairingTask.java:156)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.run(RepairingTask.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: com.hazelcast.client.HazelcastClientOfflineException: Client is offline.
	at com.hazelcast.client.connection.nio.DefaultClientConnectionStrategy.beforeGetConnection(DefaultClientConnectionStrategy.java:58)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.checkAllowed(ClientConnectionManagerImpl.java:329)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getConnection(ClientConnectionManagerImpl.java:304)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.getOrTriggerConnect(ClientConnectionManagerImpl.java:295)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.getOrTriggerConnect(SmartClientInvocationService.java:73)
	at com.hazelcast.client.spi.impl.SmartClientInvocationService.invokeOnTarget(SmartClientInvocationService.java:68)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:165)
	at com.hazelcast.client.spi.impl.ClientInvocation.invoke(ClientInvocation.java:146)
	at com.hazelcast.client.map.impl.nearcache.invalidation.ClientMapInvalidationMetaDataFetcher.fetchMetadataOf(ClientMapInvalidationMetaDataFetcher.java:62)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.fetchMembersMetadataFor(InvalidationMetaDataFetcher.java:99)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.fetchMetadata(InvalidationMetaDataFetcher.java:73)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.runAntiEntropyIfNeeded(RepairingTask.java:156)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.run(RepairingTask.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	... 16 more

Sep 06, 2018 10:53:48 AM com.hazelcast.client.spi.ClientExecutionService
SEVERE: hz.client_0 [HZ] [3.11-SNAPSHOT] Failed to execute java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2dae9baf
java.lang.NullPointerException
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.repairUuids(InvalidationMetaDataFetcher.java:139)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.processMemberMetadata(InvalidationMetaDataFetcher.java:126)
	at com.hazelcast.internal.nearcache.impl.invalidation.InvalidationMetaDataFetcher.fetchMetadata(InvalidationMetaDataFetcher.java:77)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.runAntiEntropyIfNeeded(RepairingTask.java:156)
	at com.hazelcast.internal.nearcache.impl.invalidation.RepairingTask.run(RepairingTask.java:125)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

### PR DESCRIPTION
**Pull request by vbekiaris**
When an exception occurs while fetching invalidation metadata,
there is no reason to proceed processing null metadata.
`IllegalStateException`s are now logged at finest level, covering
member-side `HazelcastInstanceNotActive` and client-side
`HazelcastClientOffline` and `HazelcastClientNotActive` exceptions.

Fixes #13700

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/InvalidationMetaDataFetcher.java [hunk 1]
```diff
@@ -115,18 +115,23 @@ private void processMemberMetadata(Member member, InternalCompletableFuture futu
         MetadataHolder resultHolder = new MetadataHolder();
         try {
             extractMemberMetadata(member, future, resultHolder);
-        } catch (HazelcastInstanceNotActiveException e) {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/InvalidationMetaDataFetcher.java]: `fetchMembersMetadataFor` method in this class seems to have same defect.

File: hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/InvalidationMetaDataFetcher.java [hunk 2]
```diff
@@ -115,18 +115,23 @@ private void processMemberMetadata(Member member, InternalCompletableFuture futu
...
+            handleExceptionWhileProcessingMetadata(member, e);
+            return;
         }
 
         repairUuids(resultHolder.partitionUuidList, handlers);
         repairSequences(resultHolder.namePartitionSequenceList, handlers);
     }
 
+    protected void handleExceptionWhileProcessingMetadata(Member member, Exception e) {
+        if (e instanceof HazelcastInstanceNotActiveException) {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/invalidation/InvalidationMetaDataFetcher.java]: what about handling only `IllegalStateException` here? By doing this we can handle all possible cases i think, for example `HazelcastClientNotActiveException` is missing now despite the fix in this PR.

**Comment by vbekiaris** [comment]
@pierregangloff this PR has been merged since 3.11, here is the commit https://github.com/hazelcast/hazelcast/commit/0a20dbb8ca1fd93caa9175949222b400e0cc254f . Release notes document lists most prominent fixes, for an exhaustive list of all PRs/issues fixed in a specific version you can have a look at the milestone on github (eg [here is the link to 3.11 milestone](https://github.com/hazelcast/hazelcast/milestone/106))
