### PR TITLE
Map-loader validation fixes

### LINKED ISSUE #11078: MapLoader NPE on loadAllKeys()
This code
```
	@Override
	public Iterable<String> loadAllKeys() {
		Collection<String> result = new ArrayList<>();
		result.add(null);
		return result;
	}
```
gives
```
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.getPartitionId(InternalPartitionServiceImpl.java:845) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$2.apply(MapKeyLoaderUtil.java:113) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$2.apply(MapKeyLoaderUtil.java:110) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.IterableUtil$2.next(IterableUtil.java:60) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil.nextBatch(MapKeyLoaderUtil.java:86) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$1.next(MapKeyLoaderUtil.java:76) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoaderUtil$1.next(MapKeyLoaderUtil.java:65) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader.sendKeysInBatches(MapKeyLoader.java:341) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader.access$200(MapKeyLoader.java:72) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:191) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.map.impl.MapKeyLoader$1.call(MapKeyLoader.java:188) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:228) ~[hazelcast-3.8.3.jar!/:3.8.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_144]
```

### PR DESCRIPTION
**Pull request by tombujok**
Fixes #11078 #11079 #11081 by improving validation
Does not change any MapLoader behavior - it just sends nicer message to the user.

### CODE REVIEW

**Comment by tombujok** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java [hunk 1]
```diff
@@ -70,8 +71,12 @@ public void run() throws Exception {
             Object previousValue = recordStore.putFromLoad(key, value);
 
             callAfterPutInterceptors(value);
+            // Null-pointer here, in case of null key loaded by MapLoader
+            checkNotNull(key, "Key loaded by a MapLoader cannot be null.");
```
Comment (gokhanoner) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: Shouldn't we make this key check & value check before everything else, even before `recordStore.putLoad`, which internally checks null keys & values. Then we can remove the extra check inside `DefaultRecordStore.putFromLoadInternal`. Currently is key/value is null, we still call afterPut Interceptor, but this data won't be added to map.

Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: Expecting to see these validation checks during initial loading of keys. As i see that is added in this PR. 
But how can a key be null inside `PutFromLoadAllOperation`? Maybe only adding `assert key != null` can be sufficient here.

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: @gokhanoner putFromLoad will ignore those anyway. I didn't want to change much stuff, just add a better message where it blows, but actually we may move the key validation before the interceptors, so I just did.

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: @ahmetmircik I didn't want to change the existing logic, though it's slightly broken. 
The LoadAllOperation is called here, the mapper will map null keys to partitions anyway.
https://github.com/tombujok/hazelcast/blob/16bd03c7794322b5989d1bd5641c80352c1117cb/hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java#L342

If I add validation before, the batch won't be half-loaded - since now it loads the data until it reaches null, I didn't want to change that... Will need to be fixed in 4.0

Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: actually, the intended behaviour was not throw exception in case of null key or value, silently continue processing and print a warning message. This operation can be a continuation of that intended behaviour.  You can see this here: [isKeyAndValueLoadable](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java#L949)

Seems until 4.0 we can preserve it.

Comment (gokhanoner) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: @tombujok OK but if value is null, we're still calling interceptor. I believe we're not saving null values to Map, right ?

Also, as you said, `recordStore.putFromLoad(key, value);` check for both key & value. In this case, even value is null, we're still calling interceptor, just precent NPE inside if block, raise event etc.

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: That is true, I mean it was like this before, but there's not reason we can't fix it now. So I added a guard for the interceptor, plus I moved the key validation higher to avoid de-serialization calls. The value validation has to stay where it is, otherwise it would be a change of behavior.

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/PutFromLoadAllOperation.java]: Sure, I'm fully with you, but I didn't change any behaviour in this PR. The thing is that the code blows up in these places without the checks anyway. It's just a nasty NullPointerException on the `Record record = recordStore.getRecord(key);` So the line I added just prints a nicer message.

The only behaviour change that this PR is doing is not calling the interceptor if the value is null, but this is a clear bug fix, since earlier the interceptor was called even though the putFromLoad ignored this null value.
