### PR TITLE
[3.7.3] Do not change keyLoaderState when loading keys supplied by user

### LINKED ISSUE #9255: MapLoader.loadAll(true) doesn't reload after reloading with new keys
Reproducer: https://github.com/amitgsoni/hazelcast

1. Start cache server (Don't load any map) 
2. Load map first time --> Using `com.hazelcast.client.HazelcastClient.getMap().size()` 
3. Reload Update key(s) of given map --> Using `com.hazelcast.client.HazelcastClient getMap().loadAll(keys, true);`

-- Once we do operation of step-3 the getMap().loadAll(true) is not working as expected

ZD 2149

### PR DESCRIPTION
**Pull request by jerrinot**
The LoadAllOperation is used in 2 contexts:
1. loadAll() - when all entries are reloaded
2. loadAll(keys) - when reload of specific keys is requested by user

The first case uses a complex key-loading coordination and state transitions,
while the 2nd case is fairly simple - every member receives a set of keys
directly from the user.

This changeset fix the behaviour in the 2nd case where the
state was changed by accident and this led to a buggy
behaviour.

Fixes #9255
EE-part: https://github.com/hazelcast/hazelcast-enterprise/pull/1135

Port of #9262 into the 3.7.3 release branch
(cherry picked from commit 734509d)

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/map/impl/operation/DefaultMapOperationProvider.java [hunk 1]
```diff
@@ -215,8 +215,9 @@ public MapOperation createGetOperation(String name, Data dataKey) {
     }
 
     @Override
-    public MapOperation createLoadAllOperation(String name, List<Data> keys, boolean replaceExistingValues) {
-        return new LoadAllOperation(name, keys, replaceExistingValues);
+    public MapOperation createLoadAllOperation(String name, List<Data> keys, boolean replaceExistingValues,
+                                               boolean localOnlyLoad) {
+        return new LoadAllOperation(name, keys, replaceExistingValues, localOnlyLoad);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/DefaultMapOperationProvider.java]: maybe we can use `withUserSuppliedKeys` instead of `localOnlyLoad`. `localOnlyLoad` seemed not clear

File: hazelcast/src/main/java/com/hazelcast/map/impl/operation/LoadAllOperation.java [hunk 2]
```diff
@@ -39,15 +39,20 @@
...
 
-    public LoadAllOperation(String name, List<Data> keys, boolean replaceExistingValues) {
+    public LoadAllOperation(String name, List<Data> keys, boolean replaceExistingValues, boolean localOnlyLoad) {
         super(name);
         this.keys = keys;
         this.replaceExistingValues = replaceExistingValues;
+        this.localOnlyLoad = localOnlyLoad;
+        // the localOnlyLoad field piggy-backs on Operation flags for serialization
+        // as the field was introduced in a patch release
+        setFlag(localOnlyLoad, BITMASK_LOAD_ALL_LOCAL_ONLY);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/LoadAllOperation.java]: nice hack

File: hazelcast/src/main/java/com/hazelcast/map/impl/operation/DefaultMapOperationProvider.java (hunk 1 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/DefaultMapOperationProvider.java]: can do. @tombujok: WDYT?

File: hazelcast/src/main/java/com/hazelcast/map/impl/operation/LoadAllOperation.java (hunk 2 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/LoadAllOperation.java]: I blame Tom for this evil genius-kind of hack! :)

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/LoadAllOperation.java]: Thx Jaromir, let's say it's our joint work ;)
