### PR TITLE
Handle HazelcastClientNotActiveException in ClientReliableTopicProxy

### LINKED ISSUE #10291: Warning level exception when shutting down the client
When shutting down a client with a topic subscription, it logs a warning level excepiton which seems harmless. But it is not good to log a harmless exception as warning. See the stacktrace below: 

```
2017-04-06 16:15:45,715 WARN [main] com.hazelcast.client.proxy.ClientReliableTopicProxy - hz.client_1 [dev] [3.8] Terminating MessageListener TopicMessageLostTest$MyClient@6075b2d3 on topic: my-topic. Reason: Unhandled exception, message: Internal executor rejected task: com.hazelcast.spi.impl.AbstractInvocationFuture$1@160396db, because client is shutting down... 
java.util.concurrent.RejectedExecutionException: Internal executor rejected task: com.hazelcast.spi.impl.AbstractInvocationFuture$1@160396db, because client is shutting down... 
at com.hazelcast.client.spi.impl.ClientExecutionServiceImpl$2.rejectedExecution(ClientExecutionServiceImpl.java:81) ~[hazelcast-all-3.8.jar:3.8] 
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) ~[?:1.8.0_102] 
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) ~[?:1.8.0_102] 
at com.hazelcast.client.spi.impl.ClientExecutionServiceImpl.execute(ClientExecutionServiceImpl.java:98) ~[hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.spi.impl.AbstractInvocationFuture.unblock(AbstractInvocationFuture.java:239) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.spi.impl.AbstractInvocationFuture.unblockAll(AbstractInvocationFuture.java:225) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:362) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:159) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.client.spi.impl.ClientInvocationServiceSupport.shutdown(ClientInvocationServiceSupport.java:186) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.shutdown(ClientSmartInvocationServiceImpl.java:31) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.client.impl.HazelcastClientInstanceImpl.doShutdown(HazelcastClientInstanceImpl.java:728) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.client.impl.LifecycleServiceImpl.shutdown(LifecycleServiceImpl.java:141) [hazelcast-all-3.8.jar:3.8] 
at com.hazelcast.client.impl.HazelcastClientProxy.shutdown(HazelcastClientProxy.java:285) [hazelcast-all-3.8.jar:3.8] 
at TopicMessageLostTest$MyClient.stop(TopicMessageLostTest.java:104) [classes/:?] 
at TopicMessageLostTest.test(TopicMessageLostTest.java:53) [classes/:?] 
at TopicMessageLostTest.main(TopicMessageLostTest.java:29) [classes/:?]
```

### PR DESCRIPTION
**Pull request by sancar**
Because of shutdown order of events, invocation was getting
RejectedExecutionException from EventService rather than
HazelcastClientNotActiveException.
Both the shutdown order fix and handling the Exception is added to pr.

Since this only effects logging I could not add any test
fixes #10291

### CODE REVIEW

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableTopicProxy.java [hunk 1]
```diff
@@ -338,4 +346,11 @@ private boolean terminate(Throwable failure) {
         }
     }
 
+    private Throwable getCauseIfAvailable(Throwable t) {
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableTopicProxy.java]: There is a method in ExceptionUtil called 'peel' which afaik does the same thing.

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run
