### PR TITLE
At load-all operation, exception should not be wrapped and underlying exception should be propagated.

### LINKED ISSUE #7125: Client-side JCache TCK test failures related with load all
https://hazelcast-l337.ci.cloudbees.com/job/JCache-TCK-Client-master/lastCompletedBuild/javax.cache$specific-implementation-tester/testReport/org.jsr107.tck.integration/

Should be introduced by this PR https://github.com/hazelcast/hazelcast/pull/7061
Not looked at detailed yet but I think, `onFailure`, `Throwable` should not be wrapped into `CacheException` if it is an `Exception`.

It should be like this:
``` java
@Override
public void onFailure(Throwable t) {
    if (completionListener != null) {
        if (t instanceof Exception) {
            completionListener.onException((Exception) t);
        } else {
            completionListener.onException(new CacheException(t));
        }
    }
}
```

### LINKED ISSUE #7126: [TEST-FAILURE] com.hazelcast.client.cache.jsr.CacheLoaderTest.shouldLoadWhenAccessingWithEntryProcessor
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/com.hazelcast$hazelcast-client/890/testReport/junit/com.hazelcast.client.cache.jsr/CacheLoaderTest/shouldLoadWhenAccessingWithEntryProcessor/

Possibly related with this PR https://github.com/hazelcast/hazelcast/pull/7061 due to non-waiting behaviour for on-going load all tasks on cache close so they might effect each other tests as far as I could reproduced it on my local.

### PR DESCRIPTION
**Pull request by serkan-ozal**
… Also on cache close, on-going load-all calls should be waited to finish.

Fixes #7125 
Fixes #7126

### CODE REVIEW

**Comment by serkan-ozal** [comment]
run-lab-run

File: hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientCacheProxyBase.java [hunk 1]
```diff
@@ -166,16 +211,19 @@ protected ClientMessage invoke(ClientMessage clientMessage, Data keyData) {
...
+            delegatingFuture = new ClientDelegatingFuture(future, serializationService, LOAD_ALL_DECODER);
+            final Future delFuture = delegatingFuture;
+            loadAllCalls.put(delegatingFuture, completionListener != null ? completionListener : NULL_COMPLETION_LISTENER);
             delegatingFuture.andThen(new ExecutionCallback<V>() {
                 @Override
                 public void onResponse(V response) {
+                    loadAllCalls.remove(delFuture);
                     if (completionListener != null) {
                         completionListener.onCompletion();
                         onLoadAll(keys, response, start, System.nanoTime());
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientCacheProxyBase.java]: shouldn't onLoadAll be called even if completionListener is not null?

File: hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientCacheProxyBase.java [hunk 2]
```diff
@@ -87,9 +113,28 @@ public void close() {
...
+        Iterator<Map.Entry<Future, CompletionListener>> iterator = loadAllCalls.entrySet().iterator();
+        while (iterator.hasNext()) {
+            Map.Entry<Future, CompletionListener> entry = iterator.next();
+            Future f = entry.getKey();
+            CompletionListener completionListener = entry.getValue();
+            try {
+                f.get(TIMEOUT, TimeUnit.SECONDS);
+            } catch (Throwable t) {
+                logger.finest("Error occurred at loadAll operation execution while waiting it to finish on cache close!", t);
+                if (completionListener != NULL_COMPLETION_LISTENER) {
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientCacheProxyBase.java]: sometimes completionListener check is compared to null and sometimes NULL_COMPLETION_LISTENER. I think it would be nice if would be one or the other. See also the onResponse / onFailure

File: hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientCacheProxyBase.java (hunk 1 above)
Comment (serkan-ozal) [inline hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/AbstractClientCacheProxyBase.java]: @cangencer :+1: good catch

**Comment by cangencer** [comment]
:+1:
