### PR TITLE
Fix flaky Log4jLoggerTest

### LINKED ISSUE #19976: com.hazelcast.logging.Log4jLoggerTest.logEvent_withLogLevelOff_shouldNotLog
srknzl:fixMemoryLeakGetDistrObject (commit 67c97dc6e6c5a73b6b7a4de25919023b02c547d7)

Failed on Hazelcast PR Builder: [INSERT_LINK_TO_JENKINS_TEST_RESULT_HERE](https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/8339/testReport/junit/com.hazelcast.logging/Log4jLoggerTest/logEvent_withLogLevelOff_shouldNotLog/)

<details><summary>Stacktrace:</summary>

```
org.opentest4j.AssertionFailedError: 
[Expected 0 log events but got 1] 
Expecting:
 <1>
to be equal to:
 <0>
but was not.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.hazelcast.logging.Log4jTrackingAppender.assertNumberOfLoggedEvents(Log4jTrackingAppender.java:58)
	at com.hazelcast.logging.Log4jTrackingAppender.assertNoLoggedEvents(Log4jTrackingAppender.java:62)
	at com.hazelcast.logging.Log4jLoggerTest.logEvent_withLogLevelOff_shouldNotLog(Log4jLoggerTest.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: isLoggable_whenLevelOff_shouldReturnFalse in 0.003 seconds.
BuildInfo right after logEvent_withLogLevelOff_shouldNotLog(com.hazelcast.logging.Log4jLoggerTest): BuildInfo{version='5.1-SNAPSHOT', build='20211123', buildNumber=20211123, revision=a5e8499, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'logEvent_withLogLevelOff_shouldNotLog(com.hazelcast.logging.Log4jLoggerTest):'
12:44:15, accumulated pauses: 119 ms, max pause: 117 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```

</details>

### PR DESCRIPTION
**Pull request by frant-hartm**
The parallel runner may run multiple tests at the same time using same
logger instance because they are reused for tests logEvent_shouldLog and
logEvent_withLogLevelOff_shouldNotLog.

Fixes #19976 (test failure seen in PR builder of #19999)

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/logging/Log4jLoggerTest.java [hunk 1]
```diff
@@ -41,7 +41,7 @@
 import static org.mockito.Mockito.verify;
 import static org.mockito.Mockito.verifyNoInteractions;
 
-@RunWith(HazelcastParallelClassRunner.class)
+@RunWith(HazelcastSerialClassRunner.class)
```
Comment (ldziedziul) [inline hazelcast/src/test/java/com/hazelcast/logging/Log4jLoggerTest.java:44]: What do you think about keeping it parallel and instead replacing `LOG_EVENT` and `LOG_EVENT_OFF` fields with `AbstractLoggerTest#someEvent` method:
```java
static LogEvent someEvent(Level level, String loggerName) {
        LogRecord logRecord = new LogRecord(level, MESSAGE);
        logRecord.setThrown(THROWABLE);
        logRecord.setLoggerName(loggerName);
        return new LogEvent(logRecord, new SimpleMemberImpl());
}
```
and then use it like this:
```diff
    @Test
    public void logEvent_shouldLog() {
-       LogRecord logRecord = LOG_EVENT.getLogRecord();    
-       Log4jTrackingAppender trackingAppender = registerTrackingAppender(logRecord.getLoggerName());
+       String loggerName = "logEvent_shouldLog";
+       LogEvent logEventWarn = someEvent(Level.WARNING, loggerName);
+       Log4jTrackingAppender trackingAppender = registerTrackingAppender(loggerName);
        trackingAppender.assertNoLoggedEvents();

        hazelcastLogger.log(logEventWarn);

        verifyNoInteractions(mockLogger);
        trackingAppender.assertNumberOfLoggedEvents(1);
    }
```

**Review by ldziedziul — APPROVED** [review]
Looks good, thanks for the fix!
