### PR TITLE
Fixes Member Update Ordering problem

### LINKED ISSUE #5393: MigrationAwareServiceTest Failures
```
java.lang.AssertionError: expected:<542> but was:<506>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK8-Quality-Outreach/com.hazelcast$hazelcast/72/testReport/junit/com.hazelcast.spi/MigrationAwareServiceTest/testPartitionDataSize_whenNodesStartedParallel_withSingleBackup/

### PR DESCRIPTION
**Pull request by eminn**
Member update ordering problem solved when receiving member list updates from master node that leads to an inconsistent member-list views across cluster members by ignoring and requesting new member-list from master when an inconsistency happens. Fixes #5393.

Thanks @mdogan for his time on providing a base fix for this pull request.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java [hunk 1]
```diff
@@ -1060,6 +1074,44 @@ public void updateMembers(Collection<MemberInfo> members) {
...
+        // member-update process only accepts new member updates
+        if (currentMembersSize == newMembersSize) {
+            Set<MemberInfo> currentMemberInfos = createMemberInfoSet(currentMembers.values());
+            if (currentMemberInfos.containsAll(newMemberInfos)) {
+                logger.finest("Received a periodic member update, no need to process...");
+            } else {
+                logger.warning("Received an inconsistent member update "
+                        + "which contains new members and removes some of the current members! "
+                        + "Ignoring and requesting a new member update...");
+                nodeEngine.getOperationService().send(new TriggerMemberListPublishOperation(), getMasterAddress());
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: can't this lead to a "MemberInfoUpdateOperation-storm" when:
1. a master is first to detect a memberX is dead
2. a new member joins
?

then a master will send

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java [hunk 2]
```diff
@@ -1060,6 +1074,44 @@ public void updateMembers(Collection<MemberInfo> members) {
         }
     }
 
+    private boolean shouldProcessMemberUpdate(Map<Address, MemberImpl> currentMembers,
+                                              Collection<MemberInfo> newMemberInfos) {
+
+        int currentMembersSize = currentMembers.size();
+        int newMembersSize = newMemberInfos.size();
+
+        if (currentMembersSize > newMembersSize) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: I don't understand the reasoning behind this. 
how `currentMembersSize > newMembersSize` implies the update is old? perhaps a master was just faster when detecting dead members?

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java (hunk 1 above)
Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: Until the member removal event is delivered to this node.

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: it can hog network for quite a few seconds and cause additional troubles

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java (hunk 2 above)
Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: Master is the only one detects the dead members, and when it is detected a dead member it fires a member removal event. And this is not the place where we handle member removals.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java (hunk 1 above)
Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: Your scenario cannot happen at the same since the operations done under the cluster service lock. If the member is dead, we remove that and sent the event to other members then join starts. So I assume that event will arrive first then if the inconsistency happens we request member-list again. I cannot foresee the case that it will hog the network.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java (hunk 2 above)
Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: Image cluster size is increasing consequently, which is most likely when the cluster is just forming, in a 10 node cluster if we just receive 9 node member-list we can assume that is old. Even though the cluster size decreased this is not the place we update the member-list for dead member since it just updates the member-list. We have to wait for event to properly declare the node as dead.

**Comment by pveentjer** [comment]
I don't see a single test being added.

**Comment by pveentjer** [comment]
Can you give a clear explanation how the ordering problem has happened? I hear from jaromir that it has to do with the operations being executed on the generic thread and because of this, operations can be executed out of order and you run in this particular problem. Is this understanding correct? If not, can you add a clear explanation of what is happening?

**Comment by eminn** [comment]
@pveentjer your understanding is correct.

I like the testing idea with custom deserializer, it is definitely worth trying. Currently, when we add a delay with some randomization directly on the codebase, the issue appears more quickly.

I will update the PR with the tests, thanks for the idea.

**Comment by pveentjer** [comment]
Hi Emin; normally that is also how I would get started; just add a few hacks to see if I can quickly trigger the problem. But eventually a testing harness is needed to make sure the solution really works.

Can you add a lit of explanation of what the solution is? 

Perhaps I'm missing something, but AFAIK the issue is that you are processing an old event even though a new event already has been processed. And this leads to the out of order execution. Would it not make more sense to reject any out of old event? So you keep track of the master/time-stamp and if you receive an event from the same master, but an older timestamp, then you just discard it.

Again.. I'm not that familiar with this section of the codebase.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java (hunk 2 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: as discussed - there is still the problem when 2 members disappear and 1 new member joins.

**Comment by gurbuzali** [comment]
verify

**Comment by pveentjer** [comment]
Since there is no test added (also the original problem has not been reproduced) this PR can't be merged.

I think it is better to close this PR and increase the frequency of member updates. So it can be that you get out of sync temporarily due to a out of order execution, but a few seconds later you will be in sync again.

I think this is a lot less risky than having a lot of untested changes in the system. Especially at a brittle system like the cluster service.

**Comment by eminn** [comment]
Pull request is updated with a test case, I had to introduce a flag to override default serialization hierarchy since Operation class implements DataSerializable and serialization service picks up DataSerializer for every operation regardless of custom serializer registration.

**Comment by mesutcelik** [comment]
verify

**Comment by eminn** [comment]
verify

**Comment by pveentjer** [comment]
Did you run the test case without your changes and did you see the bar turn red? I'll run it locally as well to verify that the test cases shows the system is broken.

File: hazelcast/src/main/java/com/hazelcast/instance/GroupProperties.java [hunk 3]
```diff
@@ -276,26 +277,26 @@
     /**
      * Controls the frequency of a BackupAwareOperation getting its async backups converted to a sync backups. This is needed
      * to prevent an accumulation of asynchronous backups and eventually running into stability issues.
-     *
+     * <p/>
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/instance/GroupProperties.java]: Please remove all these <p/>. They are illegal for Java 8. So please update your intellij to stop inserting it.

File: hazelcast/src/main/java/com/hazelcast/instance/GroupProperties.java [hunk 4]
```diff
@@ -375,6 +375,14 @@
     public static final String PROP_QUERY_MAX_LOCAL_PARTITION_LIMIT_FOR_PRE_CHECK
             = "hazelcast.query.max.local.partition.limit.for.precheck";
 
+    /**
+     * If enabled, the default serialization hierarchy (DataSerializable -> Portable -> Constant -> Custom )
+     * will be overrided and custom serialization will be checked first to serialize objects.
+     */
+    public static final String PROP_SERIALIZATION_CUSTOM_OVERRIDE
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/instance/GroupProperties.java]: No need for a public property imho. This is a hack to test certain behavior; we don't want to expose it to the outside world. Therefor it should not be added to GroupProperties; so this whole class can be reverted.

**Comment by pveentjer** [comment]
More untested changes. So this PR is not in a state to get merged.

File: hazelcast/src/test/java/com/hazelcast/cluster/JoinStressTest.java [hunk 5]
```diff
@@ -199,4 +240,46 @@ private void initNetworkConfig(NetworkConfig networkConfig, int basePort, int po
...
+
+        }
+    }
+
+    public static class DelayedMemberInfoUpdateOperation extends MemberInfoUpdateOperation {
+
+        public DelayedMemberInfoUpdateOperation() {
+        }
+
+        @Override
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/JoinStressTest.java]: Why do you copy paste all this logic? You can just add a sleep and then call super.run().

**Comment by pveentjer** [comment]
I believe you are using this test to shows that there is a bug in the system:

testJoincompletesCorrectlyWhenMultipleNodesStartedParallel

When I run this test in isolation, the test doesn't fail when  remove the bugfixing-code. When I run the test together with all the test methods it sometimes fails. 

So this test is not yet good enough to reproduce the problem. If you put a @Repeat(value = 100) above the test, I was able to reproduce the bug on every run. So can you add this annotation to make sure the test becomes a reliable mechanism to reproduce the problem (and therefor to show that the fix works).

**Comment by pveentjer** [comment]
The simplest thing you can do to reproduce the problem is to let the MemberInfoUpdateOperation read out a system property and based on that you do a delay. Currently you have made a lot of changes in production code just to trigger this behavior. Just adding a system property check in the MemberInfoUpdate is the lesser of 2 evils to trigger the behavior because the code changes are way smaller.

**Comment by pveentjer** [comment]
Looks good.

@jerrinot can you have one more look at it? Afaik you also know a few things about the reordering issue.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java [hunk 6]
```diff
@@ -1060,6 +1074,44 @@ public void updateMembers(Collection<MemberInfo> members) {
...
+            logger.severe("Received an older member update, no need to process...");
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterServiceImpl.java]: Don't you want to send the trigger message here? I think that's what we discussed.

Also I wouldn't use the severe log-level. I don't see anything severe on this - given the current design it's something we can totally expect.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/operations/TriggerMemberListPublishOperation.java [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+ * Requests member list publish from master node
+ */
+public class TriggerMemberListPublishOperation extends AbstractClusterOperation {
+
+    public TriggerMemberListPublishOperation() {
+    }
+
+    @Override
+    public void run() throws Exception {
+        final ClusterServiceImpl clusterService = getService();
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/operations/TriggerMemberListPublishOperation.java]: what if we are no longer a master at this point?

Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/operations/TriggerMemberListPublishOperation.java]: it is already handled inside the sendMemberListToMember() method, which we just do nothing if we are not master.

**Comment by eminn** [comment]
verify

File: hazelcast/src/main/java/com/hazelcast/nio/serialization/SerializationServiceImpl.java [hunk 8]
```diff
@@ -115,6 +119,7 @@ public Object getPartitionKey(Object key) {
         this.managedContext = managedContext;
         this.globalPartitioningStrategy = partitionStrategy;
         this.outputBufferSize = initialOutputBufferSize;
+        this.overrideCustomSerialization = parseBoolean(System.getProperty(SERIALIZATION_CUSTOM_OVERRIDE, "false"));
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/nio/serialization/SerializationServiceImpl.java]: just a trivial readability thing: you can use `Boolean.getBoolean()` method for this.

**Comment by jerrinot** [comment]
looks good to me.

**Comment by metanet** [comment]
:+1:
