### PR TITLE
Check queue capacity limit correctly when IQueue.addAll

### LINKED ISSUE #20919: IQueue.addAll does not adhere to the queues capacity limit
**Describe the bug**
The IQueue.addAll(Collection<?>) method allows the entire collection to be added into the queue, even when this exceeds the max size of the queue.

This appears to be because the run method in com.hazelcast.collection.impl.queue.operations.AddAllOperation , only checks if there is *any* capacity in the queue
if (queueContainer.hasEnoughCapacity()) {
rather than maybe checking if there is enough capacity for the collection e.g. 
if (queueContainer.hasEnoughCapacity(dataList.size())) {

**Expected behavior**
I would expect that addAll would not modify the queue if the entire collection cannot be added. 

**To Reproduce**

public class QueueTest {

    private static final String CAPACITY_QUEUE = "TEST_QUEUE";
    private static final int QUEUE_CAPACITY = 2;

    private static HazelcastInstance instance;

    @Before
    public void setup() {
        Config memberConfig = new Config();
        memberConfig.addQueueConfig(new QueueConfig().setName(CAPACITY_QUEUE).setMaxSize(QUEUE_CAPACITY));
        instance = Hazelcast.newHazelcastInstance(memberConfig);
    }

    @Test
    public void testAddingTwentyThings() {

        final IQueue<String> queue = instance.getQueue(CAPACITY_QUEUE);

        final List<String> collection = Collections.nCopies(20, "Hello");
        final boolean added = queue.addAll(collection);
        //Assert.assertFalse(added); //Should not be added but we add all 20

        //Now we can pull 20 things out of the queue, despite its capacity of 2
        List<String> drainTo = new ArrayList<>();
        queue.drainTo(drainTo);
        Assert.assertEquals(0, drainTo.size());

    }

}

**Additional context**

### PR DESCRIPTION
**Pull request by albertzuh**
Check queue capacity limit correctly when IQueue.addAll

Fixes #20919

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    @Test
+    public void testQueueLimitEffective() {
+        final IQueue<String> queue = instance.getQueue(CAPACITY_QUEUE);
+        final List<String> collection = Collections.nCopies(20, "Hello");
+        final boolean added = queue.addAll(collection);
+        Assert.assertFalse(added);
+        List<String> drainTo = new ArrayList<>();
+        queue.drainTo(drainTo);
+        Assert.assertEquals(0, drainTo.size());
+    }
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java:54]: Could you please move this test to https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueAbstractTest.java#L376-L375 and follow the same style as there.

**Review by frant-hartm — CHANGES_REQUESTED** [review]
Hi, thank you very much for your PR! Please see the comment.

**Comment by frant-hartm** [comment]
@albertzuh Could you also please sign the CLA (click on the `Details` link next to the `license/cla`) check.

File: hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+        memberConfig.addQueueConfig(new QueueConfig().setName(CAPACITY_QUEUE).setMaxSize(QUEUE_CAPACITY));
+        instance = Hazelcast.newHazelcastInstance(memberConfig);
+    }
+
+    @Test
+    public void testQueueLimitEffective() {
+        final IQueue<String> queue = instance.getQueue(CAPACITY_QUEUE);
+        final List<String> collection = Collections.nCopies(20, "Hello");
+        final boolean added = queue.addAll(collection);
+        Assert.assertFalse(added);
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java:50]: This is actually incorrect. The contract of `java.util.Collection#addAll` says:
```
     * @throws IllegalStateException if not all the elements can be added at
     *         this time due to insertion restrictions
```

Comment (albertzuh) [reply hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java:53]: Hi @frant-hartm 
This actually not call java.util.Collection#addAll, but call by com.hazelcast.collection.impl.queue.QueueProxyImpl#addAll
It will return false if all the elements can not be added. 

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/collection/impl/queue/QueueProxyImpl.java

`    @Override
    public boolean addAll(@Nonnull Collection<? extends E> es) {
        checkNotNull(es, "Null collection is not allowed!");

        return addAllInternal(toDataList(es));
    }
`

**Comment by albertzuh** [comment]
Hi @frant-hartm 

Thanks for review. MR is updated according to review. 
Could you please take a look at it?

File: hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java (hunk 2 above)
Comment (frant-hartm) [reply hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java]: What I meant is that if you can't add all the elements due to some restriction (like exceeding the capacity) an `IllegalStateException` should be thrown, the test tests it returns false.

This is incorrect according to the contract of `Collection#addAll`, which we generally don't change, unless there is a very good reason to do so.

Comment (albertzuh) [reply hazelcast/src/test/java/com/hazelcast/collection/impl/queue/QueueCapacityTest.java]: Hi @frant-hartm 
I got what you mean, the previous logic returned the false. I changed that logic to throw IllegalStateException instead of return false, and push another commit.

**Review by frant-hartm — APPROVED** [review]

**Comment by mdumandag** [comment]
run-lab-run

**Review by mdumandag — APPROVED** [review]

**Comment by frant-hartm** [comment]
@albertzuh Thank you very much for your contribution!
