### PR TITLE
Fix PickAnyAccumulator [HZ-1228]

### LINKED ISSUE #18695: Buggy pick-any aggregation [HZ-1228]
I have this test:
```
    @Test
    public void foo() {
        Pipeline pipeline = Pipeline.create();
        pipeline.readFrom(TestSources.itemStream(1))
                .withNativeTimestamps(5000)
                .window(WindowDefinition.sliding(10_000, 1000))
                .aggregate(AggregateOperations.pickAny())
                .writeTo(Sinks.logger());
        jetInstance.newJob(pipeline).join();
    }
```
and I can see it prints this:
```
[...]
15:19:35,792  INFO || - [WriteLoggerP] hz.sleepy_turing.jet.blocking.thread-1 - [127.0.0.1]:5700 [spring-cluster] [5.0-SNAPSHOT] [0632-dc90-2280-0001/loggerSink#0] WindowResult{start=15:19:20.000, end=15:19:30.000, value='SimpleEvent(timestamp=15:14:37.000, sequence=0)', isEarly=false}
15:19:36,792  INFO || - [WriteLoggerP] hz.sleepy_turing.jet.blocking.thread-1 - [127.0.0.1]:5700 [spring-cluster] [5.0-SNAPSHOT] [0632-dc90-2280-0001/loggerSink#0] WindowResult{start=15:19:21.000, end=15:19:31.000, value='SimpleEvent(timestamp=15:14:37.000, sequence=0)', isEarly=false}
[...]
```
This makes no sense. It says the window bounded by `(start=15:19:21.000, end=15:19:31.000)` contains an item with a timestamp set to `15:14:37.000`. Clearly this item does not belong to the window as specified by the bounds. 

The problem is in the impl of [pick any](https://github.com/hazelcast/hazelcast/blob/7e5bbad3eb23600ff807c8d1efd22c466f23b16c/hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java#L42) accumulator: The accumulator had observed an item. The item is later deducted. but the accumulator is still yielding the deducted item. as long as there is at least one non-deducted item. any item.

The fix should be backported into Jet 4.5.z

### PR DESCRIPTION
**Pull request by viliam-durina**
The `deduct` function was wrong, could result in an incorrect result.

Fixes #18695

### CODE REVIEW

**Review by ramizdundar — COMMENTED** [review]
LGTM, I have one question though. Is Jet supposed to work with one minor version below like IMDG? 

- If yes would serialization changes in this PR cause a problem? 
- If no, how would RU supposed to work with Jet?

**Comment by viliam-durina** [comment]
> Is Jet supposed to work with one minor version below like IMDG?
No. Jet's compatibility is to compile in any matching major version. But there's no binary or RU compatibility, i.e. the job has to be resubmitted from code using the newer version. Also the client versions must match.

File: hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java [hunk 1]
```diff
@@ -47,11 +46,9 @@ public PickAnyAccumulator() {
      * the parameters.
      *
      * @param value the picked object
-     * @param count the count of accumulated objects
      */
-    public PickAnyAccumulator(T value, long count) {
+    public PickAnyAccumulator(T value) {
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java:50]: Are the changes in this file affect the public API we offer to the users?

File: hazelcast/src/main/java/com/hazelcast/jet/accumulator/AccumulatorSerializerHooks.java [hunk 2]
```diff
@@ -276,12 +276,11 @@ public int getTypeId() {
                 @Override
                 public void write(@Nonnull ObjectDataOutput out, @Nonnull PickAnyAccumulator acc) throws IOException {
                     out.writeObject(acc.get());
-                    out.writeLong(acc.count());
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/jet/accumulator/AccumulatorSerializerHooks.java:279]: Can we somehow send this accumulator to the older versions? Let's say the server has version 5.0, but the client is 5.2. Do we expect this to work?

Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/accumulator/AccumulatorSerializerHooks.java:279]: These are the compatibility guarantees we provide for Jet.

https://jet-start.sh/docs/operations/version-compatibility#summary-table

Member version must have a matching PATCH version to execute jobs, but I think that currently there is no check for this and it just blows up.

For client-member they must have a matching MINOR version, so this PR is ok in 5.2. I also think this is ok to backport, because the accumulator is never sent between client and member (only a Supplier is).

File: hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java (hunk 1 above)
Comment (mdumandag) [reply hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java:50]: OK, I see. It is still a breaking change but a less risky one, one we have to do to fix a defect. I think it should be acceptable to have it then :+1:

**Review by mdumandag — APPROVED** [review]

**Review by frant-hartm — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java (hunk 1 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/accumulator/PickAnyAccumulator.java:50]: Exactly, it's a bugfix. The class is Core API, that is public API. But it's supposed to be used through `AggregateOperations.pickAny()`. From there, the `deduct` method documented as being optional. We had to remove that method, because it was implemented incorrectly and cannot be implemented correctly.

File: hazelcast/src/main/java/com/hazelcast/jet/accumulator/AccumulatorSerializerHooks.java (hunk 2 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/accumulator/AccumulatorSerializerHooks.java:279]: And it's also not sent to the client.
