### PR TITLE
Fix broken watermark counters in unordered mapUsingServiceAsync [HZ-1928]

### LINKED ISSUE #23245: Unordered mapUsingServiceAsync loses items when there are no watermarks [HZ-1928]
**Describe the bug**

Unordered `mapUsingServiceAsync` loses last items when there are no watermarks. 

**To Reproduce**

https://hazelcastcommunity.slack.com/archives/C013LM6JK7S/p1671652200501389

### PR DESCRIPTION
**Pull request by k-jamroz**
mapUsingServiceAsync in unordered mode used wrong condition to check if the processing is complete and wrong number of currently processed items to propagate watermarks. This could lead to lost items when the pipeline was completed and to crashes during processing of streams containing the same item multiple times.

Fixes #23245

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java [hunk 1]
```diff
@@ -172,6 +176,34 @@ public void test_forwardMultipleWatermarksWithoutItems() {
...
+                .verifyProcessor(getSupplier((ctx, item) ->  completedFuture(singleton(item + "-1"))))
+                .hazelcastInstance(instance())
+                .input(asList("a", "a", wm(10), "a"))
+                .outputChecker((expected, actual) ->
+                        actual.equals(asList("a-1", "a-1", wm(10), "a-1"))
+                        // last item may be reordered with watermark in current implementation
+                        // but this is not required.
+                        || (!ordered && actual.equals(asList("a-1", "a-1", "a-1", wm(10))))
+                        // after snapshot restore watermark may be duplicated
+                        || (!ordered && actual.equals(asList("a-1", "a-1", wm(10), "a-1", wm(10))))
```
Comment (k-jamroz) [inline hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java:201]: @viliam-durina  I think that watermark duplication is allowed. Is that true?

File: hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java [hunk 2]
```diff
@@ -95,6 +98,22 @@
...
     @SuppressWarnings("unchecked")
     private SortedMap<Long, Integer>[] watermarkCounts = new SortedMap[0];
+    /**
+     * Current inflight items.
+     * <p>
+     * Invariant: sum of all values in {@link #inFlightItems} is equal to
+     * {@link #asyncOpsCounter}
+     * <p>
+     * We keep items with the same key as single entry with counter. This may
+     * lead to starvation of watermarks in a sequence of events like:
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java:108]: do we care? should be rather rare unless someone uses a source that emits the same item in constant interval which is later processed using `mapUsingServiceAsync`.

**Comment by k-jamroz** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java (hunk 1 above)
Comment (viliam-durina) [reply hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java:201]: It's not allowed, they must be strictly monotonic.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java (hunk 2 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java:108]: I think your comment is wrong. I don't see any starvation. If the processing takes 10s but item is emitted every 5s, then `maxAsyncOps` will eventually be reached, no more items will be taken from the input, then input queue will fill up and the source will not be able to emit every 5s.

Also, WMs are emitted according to `watermarkCounts`, so in your scenario, the count of events before the watermark will get to 0, even if it's the same item all the time, and the WM will be forwarded. Can you reproduce this case?

Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java:108]: You are right, I mixed `inflightItems` and `watermarkCounts`

File: hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java (hunk 1 above)
Comment (k-jamroz) [reply hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java:201]: Watermark order with regards to items is preserved.
After a lot of debugging I confirmed that WM duplication is partially caused by the fact that we do not store `lastEmittedWms` in the snapshot. So if at the time of getting snapshot we have:

1. WM that was already emitted and no new WM was received
2. inflight item

then, after restore we get:

1. that old, already emitted, WM in `lastReceivedWms`
2. inflight item that assumes that it was received before any snapshot (`Long.MIN_VALUE`) even though to be strict it should be related to the WM (`lastReceivedWms` field is updated after restored items are sent for processing)
3. when inflight item completes, it triggers emission of WM from `lastReceivedWms` (check in `watermarkCount.isEmpty() && lastReceivedWms[i] > lastEmittedWms[i]`) which seems to make sense at least for other cases

I think this actually may be by design that given WM can be repeated after snapshot because, as the comment says:
> we restart at the oldest WM any instance was at the time of snapshot

Comment (k-jamroz) [reply hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java:201]: also the duplication does not occur during single execution, duplicated WM is emitted after restore from snapshot. But because of "we restart at the oldest WM any instance was at the time of snapshot" it probably can go backwards.

Still, emitting WM after unrelated item seems at least counter-intuitive.

Comment (viliam-durina) [reply hazelcast/src/test/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServicePTest.java:201]: I debugged it too and yes, the observed output is legal. The duplicate WMs aren't emitted from a single instance of a processor (that wouldn't be legal), but from the processor after restore.

We save a simplified state to the snapshot. Before saving, we know exactly which item was received before which WM. But we can't save it exactly like this, because after restore, the WM can go back in at-least-once mode, and items can be re-partitioned, and we can't re-partition the `watermarkCounts`. I think we don't even have to save `lastReceivedWm` at all, we can just rely on the new WMs received after restore, but it's not too important to change, I can be wrong here.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java [hunk 3]
```diff
@@ -83,18 +83,44 @@
...
 
     Separately, we track watermark counts for each key, which we increment for each WM key when an event is received,
-    and decrement when a response is processed. The count is the count of events received _before_ that WM, since
-    the previous WM. When the count gets to 0, we know we can emit the watermark, because all the responses
+    and decrement when a response is processed. The count is the count of events received _since_ that WM, _before_
+    the next WM. When the count gets to 0, we know we can emit the next watermark, because all the responses
     for events received before it were already sent.
+
+    Snapshot contains in-flight elements at the time of taking the snapshot.
+    They are replayed when state is restored from the snapshot, so we get only at-least-once guarantee.
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java:91]: The guarantee is still exactly-once, but under the hood the processing is retried at least once, but that doesn't break the guarantee.

**Review by viliam-durina — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java (hunk 3 above)
Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/processor/AsyncTransformUsingServiceUnorderedP.java]: updated comment

**Review by burakgok — APPROVED** [review]

**Review by Fly-Style — APPROVED** [review]

**Comment by k-jamroz** [comment]
run-lab-run
