### PR TITLE
Ensures FrozenPartitionTableTest waits for partitions update

### LINKED ISSUE #17505: FrozenPartitionTableTest.partitionTable_shouldBeFixed_whenMemberRestarts_usingNewUuid failure
**Error Message**

```
com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [127.0.0.1]:5703 - bd5d6faf-9735-4300-8038-c4ac23167ce8 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.internal.partition.impl.FrozenPartitionTableTest$NonRetryablePartitionOperation, service: null
```
**Stacktrace**
```
java.util.concurrent.CompletionException: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [127.0.0.1]:5703 - bd5d6faf-9735-4300-8038-c4ac23167ce8 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.internal.partition.impl.FrozenPartitionTableTest$NonRetryablePartitionOperation, service: null
	at com.hazelcast.spi.impl.AbstractInvocationFuture.returnOrThrowWithJoinConventions(AbstractInvocationFuture.java:761)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowWithJoinConvention(AbstractInvocationFuture.java:777)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:537)
	at com.hazelcast.internal.partition.impl.FrozenPartitionTableTest.partitionTable_shouldBeFixed_whenMemberRestarts_usingNewUuid(FrozenPartitionTableTest.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.spi.exception.WrongTargetException: WrongTarget! local: Member [127.0.0.1]:5703 - bd5d6faf-9735-4300-8038-c4ac23167ce8 this, expected-target: null, partitionId: 0, replicaIndex: 0, operation: com.hazelcast.internal.partition.impl.FrozenPartitionTableTest$NonRetryablePartitionOperation, service: null
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.ensureNoPartitionProblems(OperationRunnerImpl.java:375)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:231)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:452)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:166)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:136)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2262/

### PR DESCRIPTION
**Pull request by vbekiaris**
Before sending partition operation, ensure
partition table is updated on all members

Fixes #17505

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java [hunk 1]
```diff
@@ -38,6 +38,7 @@
 import com.hazelcast.test.TestHazelcastInstanceFactory;
 import com.hazelcast.test.annotation.ParallelJVMTest;
 import com.hazelcast.test.annotation.QuickTest;
+import com.hazelcast.test.annotation.Repeat;
```
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java:41]: unused import.

**Review by mdogan — APPROVED** [review]

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2284/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2284/Hazelcast-pr-builder-2284.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java:41:8: Unused import - com.hazelcast.test.annotation.Repeat. [UnusedImports]
--------------------------
</details>
</pre>

File: hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java (hunk 1 above)
Comment (vbekiaris) [reply hazelcast/src/test/java/com/hazelcast/internal/partition/impl/FrozenPartitionTableTest.java]: 🤦

**Review by blazember — APPROVED** [review]
