### PR TITLE
Check the invocation on remote node before issuing OperationTimeOutEx…

### LINKED ISSUE #4398: OperationTimeoutException when calling get on task future after hazelcast.operation.call.timeout.millis
I am executing some tests with a build of Hazelcast 3.4.1-dev from December 22 2014. I discovered a problem with long-running tasks similar to issue #1949. It seems to be new in 3.4/3.4.1.

The problem is the following: If you execute a task that takes at least two times as long as the configured hazelcast.operation.call.timeout.millis, and you call get on a remote future sometime after two times the timeout, an OperationTimeoutException (message "No response for x ms. Aborting invocation!...") is thrown. This can easily happen if you execute a long-running task and call get on all futures, since the first get will block until the task has finished on the corresponding node.

The following unit test can be used to reproduce the problem. It fails with the beforementioned Hazelcast 3.4.1 build, but not with e.g., 3.3.4:

```java
import com.hazelcast.config.Config;
import com.hazelcast.config.XmlConfigBuilder;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IExecutorService;
import com.hazelcast.core.Member;
import com.nm.test.hazelcast.TestHazelcast;
import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;
import java.io.Serializable;
import java.util.Map;
import java.util.concurrent.Callable;
import java.util.concurrent.Future;
import junit.framework.TestCase;

public class TestTask2 extends TestCase {

	private static final Logger logger = Logger.getLogger(TestTask1.class);

	@Override
	protected void setUp() throws Exception {

		// configure logging
		if (!TestHazelcast.loggingInitialized) {
			TestHazelcast.loggingInitialized = true;
			BasicConfigurator.configure();
		}
	}

	public void testTask2() throws Exception {

		// create hazelcast config
		Config config = new XmlConfigBuilder().build();
		config.setProperty("hazelcast.logging.type", "log4j");

		// set call timeout to 1 second to make the problem appear quicker
		config.setProperty("hazelcast.operation.call.timeout.millis", "2000");

		// create two Hazelcast instances
		HazelcastInstance hcInstance1 = Hazelcast.newHazelcastInstance(config);
		HazelcastInstance hcInstance2 = Hazelcast.newHazelcastInstance(config);
		try {

			// submit the long-running task
			IExecutorService executorService = hcInstance1.getExecutorService("default");
			Map<Member, Future<Object>> futures = executorService.submitToAllMembers(new SleepingTask());

			// call get on the "remote" member
			Member remoteMember = hcInstance2.getCluster().getLocalMember();
			// wait for 5 seconds
			// when we call get on the future after sleeping, the OperationTimeoutException will be raised in Hazelcast 3.4.1-20141222 dev
			Thread.sleep(5000);
			String result = (String) futures.get(remoteMember).get();

			assertEquals("Success", result);

		} finally {
			// shutdown Hazelcast instances
			hcInstance1.getLifecycleService().shutdown();
			hcInstance2.getLifecycleService().shutdown();
		}

		logger.info("Test done.");
	}

	private static class SleepingTask implements Callable<Object>, Serializable {

		private static final long serialVersionUID = 1L;

		@Override
		public Object call() throws Exception {
			Thread.sleep(6000);
			return "Success";
		}

	}

}
```

Thanks for taking a look and cheers,
Andreas

### PR DESCRIPTION
**Pull request by metanet**
Check the invocation on remote node before issuing OperationTimeOutException

* Check if the invocation is still running on remote node before issuing OperationTimeoutException

This change is originally taken from mdogan's own repo: https://github.com/mdogan/hazelcast/commit/a5db746d227b5ea0206e4f7f35025c0bd6c66cca
He has already fixed the issue. Since he is away this week and I can't contact him, I just applied his changes. 

Fixes #4398

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/IsStillRunningService.java [hunk 1]
```diff
@@ -73,15 +76,56 @@ public boolean isOperationExecuting(Invocation invocation) {
...
         } catch (Exception e) {
-            invocation.logger.warning("While asking 'is-executing': " + toString(), e);
+            invocation.logger.warning("While asking 'is-executing': " + invocation, e);
         }
-        invocation.logger.warning("'is-executing': " + executing + " -> " + toString());
+        invocation.logger.warning("'is-executing': " + executing + " -> " + invocation);
         return executing;
     }
 
+    public void timeoutInvocationIfNotExecuting(final Invocation invocation) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/IsStillRunningService.java]: Can you add some public javadoc?

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/IsStillRunningService.java [hunk 2]
```diff
@@ -73,15 +76,56 @@ public boolean isOperationExecuting(Invocation invocation) {
...
+        try {
+            final Operation isStillExecuting = createCheckOperation(invocation);
+            final ExecutionCallback callback = new ExecutionCallback() {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/IsStillRunningService.java]: Can you pull out this anonymous inner class. It makes the method very hard to understand.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/IsStillRunningService.java [hunk 3]
```diff
@@ -73,15 +76,56 @@ public boolean isOperationExecuting(Invocation invocation) {
...
+                    setOperationTimeout();
+                }
+
+                private void setOperationTimeout() {
+                    InvocationFuture future = invocation.invocationFuture;
+                    future.set(invocation.newOperationTimeoutException(future.getMaxCallTimeout()));
+                }
+            };
+
+            nodeEngine.getExecutionService().execute(SYSTEM_EXECUTOR, new Runnable() {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/IsStillRunningService.java]: Also pull out this inner class.

**Comment by gurbuzali** [comment]
do we need back-port here ?
