### PR TITLE
Fix ClientScheduledExecutorServiceSlowTest.schedule_withLongSleepingCallable_blockingOnGet  [API-1658]

### LINKED ISSUE #22068: com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceSlowTest.schedule_withLongSleepingCallable_blockingOnGet [API-1658]
_master_ (commit 65b9ec8df306750307d3de049728a80b13ee26e5)

Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/454/testReport/com.hazelcast.client.scheduledexecutor/ClientScheduledExecutorServiceSlowTest/schedule_withLongSleepingCallable_blockingOnGet/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.hazelcast.scheduledexecutor.impl.ScheduledExecutorServiceSlowTest.schedule_withLongSleepingCallable_blockingOnGet(ScheduledExecutorServiceSlowTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

<details><summary>Standard output:</summary>

```
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MetricsConfigHelper] schedule_withLongSleepingCallable_blockingOnGet - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [logo] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220825 - 65b9ec8) starting at [127.0.0.1]:5701
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Cluster name: dev
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
01:56:11,369  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
01:56:11,372  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MetricsConfigHelper] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
01:56:11,375  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [CPSubsystem] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
01:56:11,378  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Diagnostics] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
01:56:11,378  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTING
01:56:11,378  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClusterService] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 1e005fa2-a2d8-4f91-ab9e-9d21c16864fb this
]

01:56:11,378  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is STARTED
01:56:11,378  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MetricsConfigHelper] schedule_withLongSleepingCallable_blockingOnGet - [LOCAL] [dev] [5.2-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
01:56:11,378  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [logo] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
01:56:11,379  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
01:56:11,379  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Platform 5.2-SNAPSHOT (20220825 - 65b9ec8) starting at [127.0.0.1]:5702
01:56:11,379  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Cluster name: dev
01:56:11,379  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
01:56:11,379  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [system] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
01:56:11,381  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MetricsConfigHelper] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
01:56:11,384  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [CPSubsystem] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
01:56:11,386  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Diagnostics] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
01:56:11,386  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTING
01:56:11,386  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MockServer] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-1e005fa2-a2d8-4f91-ab9e-9d21c16864fb, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=bd3f94d1-8a25-411f-95cd-472d1b75ff54], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=1e005fa2-a2d8-4f91-ab9e-9d21c16864fb], alive=true}
01:56:11,386  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MockServer] hz.cool_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-bd3f94d1-8a25-411f-95cd-472d1b75ff54, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=1e005fa2-a2d8-4f91-ab9e-9d21c16864fb], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=bd3f94d1-8a25-411f-95cd-472d1b75ff54], alive=true}
01:56:11,386  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClusterService] hz.cool_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 1e005fa2-a2d8-4f91-ab9e-9d21c16864fb this
	Member [127.0.0.1]:5702 - bd3f94d1-8a25-411f-95cd-472d1b75ff54
]

01:56:11,486  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClusterService] hz.condescending_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 1e005fa2-a2d8-4f91-ab9e-9d21c16864fb
	Member [127.0.0.1]:5702 - bd3f94d1-8a25-411f-95cd-472d1b75ff54 this
]

01:56:11,486  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is STARTED
01:56:11,487  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [PartitionStateManager] schedule_withLongSleepingCallable_blockingOnGet - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing cluster partition table arrangement...
01:56:17,377  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [InvocationMonitor] hz.cool_moore.InvocationMonitorThread - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Invocations:1 timeouts:0 backup-timeouts:1
01:56:17,379  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [AbstractConfigLocator] schedule_withLongSleepingCallable_blockingOnGet - Loading 'hazelcast-client-default.xml' from the classpath.
01:56:17,392  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientInvocationService] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] Running with 2 response threads, dynamic=true
01:56:17,393  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220825 - 65b9ec8) is STARTING
01:56:17,393  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220825 - 65b9ec8) is STARTED
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientConnectionManager] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] Trying to connect to cluster: dev
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientConnectionManager] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] Trying to connect to [127.0.0.1]:5701
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [HazelcastClient] schedule_withLongSleepingCallable_blockingOnGet - Created connection to endpoint: [127.0.0.1]:5701, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never, connected server version=null}}
01:56:17,394 DEBUG |schedule_withLongSleepingCallable_blockingOnGet| - [AuthenticationMessageTask] hz.cool_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Processing authentication with clientUuid 78d7f933-6135-4168-9773-42181270d0f5 and clientName hz.client_1814
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [AuthenticationMessageTask] hz.cool_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, successfully authenticated, clientUuid: 78d7f933-6135-4168-9773-42181270d0f5, client name: hz.client_1814, client version: 5.2-SNAPSHOT
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220825 - 65b9ec8) is CLIENT_CONNECTED
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientConnectionManager] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] Authenticated with server [127.0.0.1]:5701:1e005fa2-a2d8-4f91-ab9e-9d21c16864fb, server version: 5.2-SNAPSHOT, local address: /127.0.0.1:40001
01:56:17,394  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Diagnostics] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
01:56:17,394 TRACE |schedule_withLongSleepingCallable_blockingOnGet| - [ClientListenerService] hz.client_1814.internal-2 - hz.client_1814 [dev] [5.2-SNAPSHOT] Register attempt of ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-08-25 01:56:17.394, lastWriteTime=2022-08-25 01:56:17.394, closedTime=never, connected server version=null}}
01:56:17,395  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientClusterService] hz.client_1814.event-11838 - hz.client_1814 [dev] [5.2-SNAPSHOT] 

Members [2] {
	Member [127.0.0.1]:5701 - 1e005fa2-a2d8-4f91-ab9e-9d21c16864fb
	Member [127.0.0.1]:5702 - bd3f94d1-8a25-411f-95cd-472d1b75ff54
}

01:56:17,395  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [HazelcastClient] schedule_withLongSleepingCallable_blockingOnGet - Created connection to endpoint: [127.0.0.1]:5702, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=null, lastReadTime=never, lastWriteTime=never, closedTime=never, connected server version=null}}
01:56:17,395 TRACE |schedule_withLongSleepingCallable_blockingOnGet| - [ClientListenerService] ForkJoinPool.commonPool-worker-3 - hz.client_1814 [dev] [5.2-SNAPSHOT] Registered ClusterViewListenerHandler to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-08-25 01:56:17.395, lastWriteTime=2022-08-25 01:56:17.394, closedTime=never, connected server version=null}}
01:56:17,396 DEBUG |schedule_withLongSleepingCallable_blockingOnGet| - [AuthenticationMessageTask] hz.condescending_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Processing authentication with clientUuid 78d7f933-6135-4168-9773-42181270d0f5 and clientName hz.client_1814
01:56:17,396  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [AuthenticationMessageTask] hz.condescending_moore.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Received auth from MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}, successfully authenticated, clientUuid: 78d7f933-6135-4168-9773-42181270d0f5, client name: hz.client_1814, client version: 5.2-SNAPSHOT
01:56:17,396  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientConnectionManager] schedule_withLongSleepingCallable_blockingOnGet - hz.client_1814 [dev] [5.2-SNAPSHOT] Authenticated with server [127.0.0.1]:5702:bd3f94d1-8a25-411f-95cd-472d1b75ff54, server version: 5.2-SNAPSHOT, local address: /127.0.0.1:40002
01:56:17,397 TRACE |schedule_withLongSleepingCallable_blockingOnGet| - [ClientListenerService] hz.client_1814.eventRegistration- - hz.client_1814 [dev] [5.2-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@13e621b5, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@7d49f037} to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2022-08-25 01:56:17.396, lastWriteTime=2022-08-25 01:56:17.396, closedTime=never, connected server version=null}}
01:56:17,397 TRACE |schedule_withLongSleepingCallable_blockingOnGet| - [ClientListenerService] hz.client_1814.eventRegistration- - hz.client_1814 [dev] [5.2-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@13e621b5, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@7d49f037} to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2022-08-25 01:56:17.397, lastWriteTime=2022-08-25 01:56:17.397, closedTime=never, connected server version=null}}
01:56:17,397 TRACE |schedule_withLongSleepingCallable_blockingOnGet| - [ClientListenerService] hz.client_1814.eventRegistration- - hz.client_1814 [dev] [5.2-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@13e621b5, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@7d49f037} to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-08-25 01:56:17.395, lastWriteTime=2022-08-25 01:56:17.394, closedTime=never, connected server version=null}}
01:56:17,397 TRACE |schedule_withLongSleepingCallable_blockingOnGet| - [ClientListenerService] hz.client_1814.eventRegistration- - hz.client_1814 [dev] [5.2-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$1@13e621b5, handler=com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$BackupEventHandler@7d49f037} to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-08-25 01:56:17.397, lastWriteTime=2022-08-25 01:56:17.397, closedTime=never, connected server version=null}}
01:56:17,398  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientStatisticsService] schedule_withLongSleepingCallable_blockingOnGet - Client statistics is enabled with period 5 seconds.
01:56:27,425  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - hz.client_1814 [dev] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220825 - 65b9ec8) is SHUTTING_DOWN
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientConnectionManager] main - hz.client_1814 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702:bd3f94d1-8a25-411f-95cd-472d1b75ff54, connection: MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2022-08-25 01:56:27.400, lastWriteTime=2022-08-25 01:56:27.399, closedTime=2022-08-25 01:56:27.426, connected server version=null}}
01:56:27,426  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [TestClientRegistry$MockedServerConnection] pool-4949-thread-1 - Server connection closed: null
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MockServer] pool-4949-thread-1 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40002, uuid=78d7f933-6135-4168-9773-42181270d0f5], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientConnectionManager] main - hz.client_1814 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701:1e005fa2-a2d8-4f91-ab9e-9d21c16864fb, connection: MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-08-25 01:56:27.400, lastWriteTime=2022-08-25 01:56:22.399, closedTime=2022-08-25 01:56:27.426, connected server version=null}}
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - hz.client_1814 [dev] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220825 - 65b9ec8) is CLIENT_DISCONNECTED
01:56:27,426  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [TestClientRegistry$MockedServerConnection] pool-4947-thread-1 - Server connection closed: null
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MockServer] pool-4947-thread-1 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:40001, uuid=78d7f933-6135-4168-9773-42181270d0f5], connection: MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}
01:56:27,426  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [TwoWayBlockableExecutor] pool-4949-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=false, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2022-08-25 01:56:27.400, lastWriteTime=2022-08-25 01:56:27.399, closedTime=2022-08-25 01:56:27.426, connected server version=null}}
01:56:27,426  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [TwoWayBlockableExecutor] pool-4947-thread-1 - Dropping incoming runnable since other end closed. Server Closed EOF. MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=false, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2022-08-25 01:56:27.400, lastWriteTime=2022-08-25 01:56:22.399, closedTime=2022-08-25 01:56:27.426, connected server version=null}}
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientEndpointManager] hz.condescending_moore.event-11832 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40002, localAddress = [127.0.0.1]:5702, connectionId = 2}, clientUuid=78d7f933-6135-4168-9773-42181270d0f5, clientName=hz.client_1814, authenticated=true, clientVersion=5.2-SNAPSHOT, creationTime=1661392577396, latest clientAttributes=lastStatisticsCollectionTime=1661392587398,enterprise=false,clientType=JVM,clientVersion=5.2-SNAPSHOT,clusterConnectionTimestamp=1661392577395,clientAddress=127.0.0.1,clientName=hz.client_1814,credentials.principal=null,os.committedVirtualMemorySize=9353871360,os.freePhysicalMemorySize=56095113216,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=370,os.processCpuTime=5048829653000,os.systemLoadAverage=0.18,os.totalPhysicalMemorySize=66548486144,os.totalSwapSpaceSize=0,runtime.availableProcessors=4,runtime.freeMemory=2457511088,runtime.maxMemory=4294967296,runtime.totalMemory=4294967296,runtime.uptime=2921775,runtime.usedMemory=1837456208, labels=[]}
01:56:27,426  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClientEndpointManager] hz.cool_moore.event-11827 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Destroying ClientEndpoint{connection=MockedNodeConnection{ remoteAddress = [127.0.0.1]:40001, localAddress = [127.0.0.1]:5701, connectionId = 1}, clientUuid=78d7f933-6135-4168-9773-42181270d0f5, clientName=hz.client_1814, authenticated=true, clientVersion=5.2-SNAPSHOT, creationTime=1661392577394, latest clientAttributes=lastStatisticsCollectionTime=1661392582398,enterprise=false,clientType=JVM,clientVersion=5.2-SNAPSHOT,clusterConnectionTimestamp=1661392577394,clientAddress=127.0.0.1,clientName=hz.client_1814,credentials.principal=null,os.committedVirtualMemorySize=9353871360,os.freePhysicalMemorySize=56094695424,os.freeSwapSpaceSize=0,os.maxFileDescriptorCount=1048576,os.openFileDescriptorCount=370,os.processCpuTime=5048756967000,os.systemLoadAverage=0.19,os.totalPhysicalMemorySize=66548486144,os.totalSwapSpaceSize=0,runtime.availableProcessors=4,runtime.freeMemory=2474013880,runtime.maxMemory=4294967296,runtime.totalMemory=4294967296,runtime.uptime=2916775,runtime.usedMemory=1820953416, labels=[]}
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - hz.client_1814 [dev] [5.2-SNAPSHOT] HazelcastClient 5.2-SNAPSHOT (20220825 - 65b9ec8) is SHUTDOWN
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
01:56:27,427  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Terminating forcefully...
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MockServer] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=bd3f94d1-8a25-411f-95cd-472d1b75ff54], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=1e005fa2-a2d8-4f91-ab9e-9d21c16864fb], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=bd3f94d1-8a25-411f-95cd-472d1b75ff54], alive=false}
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MockServer] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5701, uuid=1e005fa2-a2d8-4f91-ab9e-9d21c16864fb], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=bd3f94d1-8a25-411f-95cd-472d1b75ff54], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=1e005fa2-a2d8-4f91-ab9e-9d21c16864fb], alive=false}
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [MembershipManager] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Removing Member [127.0.0.1]:5702 - bd3f94d1-8a25-411f-95cd-472d1b75ff54
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [PartitionStateManager] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID bd3f94d1-8a25-411f-95cd-472d1b75ff54
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [ClusterService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:3} [
	Member [127.0.0.1]:5701 - 1e005fa2-a2d8-4f91-ab9e-9d21c16864fb this
]

01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down node engine...
01:56:27,427  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [TransactionManagerService] hz.cool_moore.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: bd3f94d1-8a25-411f-95cd-472d1b75ff54
01:56:27,432  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [NodeExtension] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
01:56:27,434  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 7 ms.
01:56:27,434  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
01:56:27,434  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
01:56:27,434  WARN |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Terminating forcefully...
01:56:27,434  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
01:56:27,434  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Shutting down node engine...
01:56:27,437  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [NodeExtension] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
01:56:27,437  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [Node] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
01:56:27,437  INFO |schedule_withLongSleepingCallable_blockingOnGet| - [LifecycleService] main - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after schedule_withLongSleepingCallable_blockingOnGet(com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceSlowTest): BuildInfo{version='5.2-SNAPSHOT', build='20220825', buildNumber=20220825, revision=65b9ec8, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'schedule_withLongSleepingCallable_blockingOnGet(com.hazelcast.client.scheduledexecutor.ClientScheduledExecutorServiceSlowTest):'
01:56:10, accumulated pauses: 188 ms, max pause: 61 ms, pauses over 1000 ms: 0
01:56:15, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:56:20, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
01:56:25, accumulated pauses: 27 ms, max pause: 15 ms, pauses over 1000 ms: 0
```

</details>

### PR DESCRIPTION
**Pull request by orcunc**
System.currentTimeMillis() is replaced with System.nanoTime() to use the same clock within the test

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Request reviewers if possible

closes #22068

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java [hunk 1]
```diff
@@ -68,14 +68,19 @@ public void schedule_withLongSleepingCallable_blockingOnGet() throws Exception {
...
 
-        assertOpenEventually(initCountLatch);
-
         int sleepPeriod = 10000;
         long start = System.currentTimeMillis();
-        new Thread(() -> {
+        Thread thread = new Thread(() -> {
+            //This is to make sure that the executorService has scheduled the task
+            //and waiting for waitCountLatch
+            assertOpenEventually(initCountLatch);
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java:76]: I didn't get this fix. When you look at the old state of the test, to start this thread, we have to see that the `initCountLatch` is open. And, it is only open when the executor service calls countdown on it. So, the executor service must have started before we call `thread.start`

Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java:76]: You are right. My fix is not correct.  I don't think the problem is about the threads. Probably it is about using different clocks for sleeping and measuring elapsed time. For sleeping System.nanoTime() is used but for measuring elapsed time System.currentTimeMillis(); is used.  It would be better to use System.nanoTime for everything. Do you want me to implement a fix like that ? Or do you want to assign the issue to somebody else and close the pull request ?

Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java:76]: I also believe that the issue is related to measurements on time. I don't think we have a flaw in the test logic or in the implementation. 

I think we can do the fix in this PR as you suggested.

Comment (srknzl) [reply hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java:76]: I agree. The actual fix is `thread.join` call I think.

Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java:76]: Not necessarily. I mean, yeah we could wait for the thread termination here, but normally, the `double result = future.get();` call will return after `waitCountLatch` is counted down. So, we were effectively waiting for the thread termination. Calling join or not will not help if the time reported by `System.currentTimeMillis()` is not inline with the amount of time we sleep with the help of `System.nanoTime()`

Comment (orcunc) [reply hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java]: I have changed the test to use System.nanoTime() to check for slept time

File: hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java [hunk 2]
```diff
@@ -70,16 +70,20 @@ public void schedule_withLongSleepingCallable_blockingOnGet() throws Exception {
...
-        int sleepPeriod = 10000;
-        long start = System.currentTimeMillis();
+        long sleepPeriod = 10;
+        long sleepPeriodInMillis = SECONDS.toMillis(sleepPeriod);
+        long sleepPeriodInNanos = SECONDS.toNanos(sleepPeriod);
+
+        long start = System.nanoTime();
         new Thread(() -> {
-            sleepAtLeastMillis(sleepPeriod);
+
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceSlowTest.java:79]: minor: we can remove this new line

**Review by mdumandag — APPROVED** [review]

**Comment by mdumandag** [comment]
Can you also update the PR body with the new fix?
