### PR TITLE
Fail if MapLoader.loadAll loads unexpected keys

### LINKED ISSUE #11462: IMap with mapstore has duplicate keys
97043970-8cb5-4bc9-94b8-7dd1b9c127f8

### PR DESCRIPTION
**Pull request by blazember**
Contract of MapLoader.loadAll(keys) defines exactly which items should be loaded from the map store.
Loading other items may lead to duplications in the map and to wasted resources in form of increased memory usage, load time and replication costs.
This fix makes loadAll failing fast if keys other than the given ones are loaded.

Fixes #11462

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapStoreWrapper.java [hunk 1]
```diff
@@ -174,11 +173,26 @@ public Map loadAll(Collection keys) {
...
+            validateLoadedMap(mapLoaded, keys);
+            return mapLoaded;
         }
         return null;
     }
 
+    private void validateLoadedMap(Map mapLoaded, Collection expectedKeys) {
+        if (mapLoaded != null) {
+            for (Object loadedKey : mapLoaded.keySet()) {
+                if (!expectedKeys.contains(loadedKey)) {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapStoreWrapper.java]: Seems it is legal to expect some of the keys cannot be loaded(because they don't exist in database at the time of loading). Maybe as an alternative solution we can check partitions of the keys returned from `MapDataStore#loadAll` for the fix?

**Comment by blazember** [comment]
run-lab-run

**Comment by blazember** [comment]
run-lab-run

**Comment by taburet** [comment]
Sorry, we don't need partition hashes on insertion, so no concerns at all :)
