### PR TITLE
Block communication between instances before closing connections in CompactFormatSplitBrainTest [API-1760]

### LINKED ISSUE #22353: com.hazelcast.internal.serialization.impl.compact.integration.CompactFormatSplitBrainTest [API-1760]
_master_ (commit 40701e7d06bfd9feff165c04fd0744f2ff365f29)

Failed on Sonar build (Oracle JDK 11): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/1353/testReport/com.hazelcast.internal.serialization.impl.compact.integration/CompactFormatSplitBrainTest/testSplitBrainHealing_whenBothClusterHaveSameSchemas/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1021)
	at com.hazelcast.test.HazelcastTestSupport.lambda$assertClusterSizeEventually$9(HazelcastTestSupport.java:1056)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1253)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1056)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1034)
	at com.hazelcast.internal.serialization.impl.compact.integration.CompactFormatSplitBrainTest.splitCluster(CompactFormatSplitBrainTest.java:171)
	at com.hazelcast.internal.serialization.impl.compact.integration.CompactFormatSplitBrainTest.testSplitBrainHealing_whenBothClusterHaveSameSchemas(CompactFormatSplitBrainTest.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

Standard output can be found here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/1353/

### PR DESCRIPTION
**Pull request by mdumandag**
This test failed a couple of times because the smaller brain was unable to form a cluster of two members.

The reason was that we were closing the connections between members (by making them suspect each other) before isolating both of the clusters.

When I examine the logs from the failed runs, I have seen that the second member of the smaller cluster was dropping the first member of the smaller cluster from its member list and closing its connection to it. When the first member was trying to claim mastership after we have isolated it from the larger cluster, the second member was rejecting that claim because that member was not in its member list, and we were unable to form the two-member smaller cluster.

That was possible because at the time the first member is isolated from the larger cluster, the second member has a perfectly healthy connection to the larger cluster, and can receive membership changes from the master of the larger cluster.

As a solution, I block communication between the
larger and smaller clusters, before making them suspect each other, drop from their member list, and close connections.

Also, I have cleaned up the test a bit and used
random instances in various steps of the test
to improve it.

Also, I have touched a couple of other split brain related tests to simplify them.

closes #22353

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/integration/CompactFormatSplitBrainTest.java [hunk 1]
```diff
@@ -81,108 +86,136 @@ public void teardown() {
...
-        for (HazelcastInstance splitAInstance : splitA) {
-            for (HazelcastInstance splitBInstance : splitB) {
-                SplitBrainTestSupport.unblockCommunicationBetween(splitAInstance, splitBInstance);
-            }
-        }
+        largerBrain.mergeWith(smallerBrain);
 
-        assertClusterSizeEventually(5, instance1, instance2, instance3, instance4, instance5);
+        assertClusterSizeEventually(allInstances.size(), allInstances);
+        waitAllForSafeState(allInstances);
```
Comment (srknzl) [inline hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/integration/CompactFormatSplitBrainTest.java:214]: Why did you add this? Why not add it to splitCluster as well?

Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/integration/CompactFormatSplitBrainTest.java:214]: I saw that it is being used in the `SplitBrainTestSupport`. Let me add it there as well

**Review by emreyigit — APPROVED** [review]
