### PR TITLE
Several migration fixes

### LINKED ISSUE #16601: NullPointerException SparseBitSet.java:97 add JVM freeze
http://jenkins.hazelcast.com/view/freeze/job/freeze-all/12/console

fail HzMember2HZ put-mapBak1Obj hzcmd.map.PutRandomStylePerson threadId=0 java.lang.NullPointerException

http://54.147.27.51/~jenkins/workspace/freeze-all/4.0/2020_02_03-18_20_04/stable/sql/bit-map

/disk1/jenkins/workspace/freeze-all/4.0/2020_02_03-18_20_04/stable/sql/bit-map

```
(base) [jenkins@ip-10-72-134-107 bit-map]$ cat ./output/HZ/HzMember2HZ/exception.txt
java.lang.NullPointerException
	at com.hazelcast.query.impl.bitmap.SparseBitSet.add(SparseBitSet.java:97)
	at com.hazelcast.query.impl.bitmap.Bitmap.update(Bitmap.java:103)
	at com.hazelcast.query.impl.BitmapIndexStore.update(BitmapIndexStore.java:216)
	at com.hazelcast.query.impl.AbstractIndex.putEntry(AbstractIndex.java:145)
	at com.hazelcast.query.impl.Indexes.putEntry(Indexes.java:271)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.saveIndex(IndexingMutationObserver.java:168)
	at com.hazelcast.map.impl.recordstore.IndexingMutationObserver.onUpdateRecord(IndexingMutationObserver.java:69)
	at com.hazelcast.map.impl.recordstore.CompositeMutationObserver.onUpdateRecord(CompositeMutationObserver.java:85)
	at com.hazelcast.map.impl.recordstore.AbstractRecordStore.updateRecord(AbstractRecordStore.java:208)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.putInternal(DefaultRecordStore.java:768)
	at com.hazelcast.map.impl.recordstore.DefaultRecordStore.put(DefaultRecordStore.java:748)
	at com.hazelcast.map.impl.operation.PutOperation.runInternal(PutOperation.java:36)
	at com.hazelcast.map.impl.operation.MapOperation.run(MapOperation.java:112)
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:184)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:228)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:217)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:160)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:138)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:123)
```

### PR DESCRIPTION
**Pull request by mdogan**
Several fixes in migration system. See individual commits for more details:

* PartitionStateOperation should not be sent to unknown members
* Migration operations should rely master member observed by PartitionService
* Fix race between fetching the most recent partition table and ongoing migration
* Only first migration fragment should set active migration in MigrationOperation
* Avoid unnecessary empty replication operations

Fixes #16601

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/partition/operation/FetchPartitionStateOperation.java [hunk 1]
```diff
@@ -42,12 +42,11 @@ public FetchPartitionStateOperation() {
     @Override
     public void run() {
         Address caller = getCallerAddress();
-        NodeEngine nodeEngine = getNodeEngine();
-        Address master = nodeEngine.getMasterAddress();
-        if (!caller.equals(master)) {
-            String msg = caller + " requested our partition table but it's not our known master. " + "Master: " + master;
+        InternalPartitionServiceImpl service = getService();
+        if (!service.isMemberMaster(caller)) {
+            String msg = caller + " requested our partition table but it's not our known master.";
```
Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/internal/partition/operation/FetchPartitionStateOperation.java]: should we still throw `IllegalStateException` if the caller is different than `clusterService.getMasterAddress()` here?

Comment (mdogan) [reply hazelcast/src/main/java/com/hazelcast/internal/partition/operation/FetchPartitionStateOperation.java]: yes, 👍 It seems we already have tests for both cases.
