### PR TITLE
Cn 124 add external service label for Kubernetes

### LINKED ISSUE #19143: [CN-124] Add external service label filtering parameter(s) to Kubernetes configuration
In Kubernetes, Hazelcast resolves its public addresses by finding an individual service that points to the given Hazelcast pod. If there are multiple services pointing to one pod, then the discovery may not work or might choose the wrong service. We should add a parameter to filter external services by the label.

Related PR(s):

- https://github.com/hazelcast/hazelcast-kubernetes/pull/331
- https://github.com/hazelcast/hazelcast/pull/19111

### PR DESCRIPTION
**Pull request by leszko**
Changes in the Kubernetes plugin
- Add label-based filtering for the Kubernetes Service per Pod
- Add matching service and pod by name (if there are multiple Services Per Pod is configured, then the priority takes a service with the same name as the pod, before it was a random service)
- Add resolving loadbalancer service if "hostname" is defined (before it was only based on the "ip" field)

PR was started by @zpqrtbnk 

Fixes #19143

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [x] Request reviewers if possible
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [x] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java [hunk 1]
```diff
@@ -96,6 +96,17 @@
...
     public static final PropertyDefinition POD_LABEL_VALUE = property("pod-label-value", STRING);
 
+    /**
+     * <p>Configuration key: <code>service-per-pod-label-name</code></p>
+     * Defines the label name of the service used to expose one Hazelcast pod (for the external smart client use case).
+     */
+    public static final PropertyDefinition SERVICE_PER_POD_LABEL_NAME = property("service-per-pod-label-name", STRING);
+    /**
+     * <p>Configuration key: <code>service-per-pod-label-value</code></p>
+     * Defines the label name of the service used to expose one Hazelcast pod (for the external smart client use case).
```
Comment (SeriyBg) [inline hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java:106]: Small neat: Defines the label _value_?

**Review by SeriyBg — APPROVED** [review]
One small comment, but other than that LGTM

File: hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java [hunk 2]
```diff
@@ -376,11 +401,15 @@ private static String extractZone(JsonObject nodeJson) {
...
             List<Endpoint> endpoints = parseEndpoints(item);
+
             // Service must point to exactly one endpoint address, otherwise the public IP would be ambiguous.
             if (endpoints.size() == 1) {
                 EndpointAddress address = endpoints.get(0).getPrivateAddress();
-                if (left.contains(address)) {
-                    result.put(address, service);
+                if (privateAddresses.contains(address)) {
+                    // If multiple services match the pod, then match service and pod names
+                    if (!result.containsKey(address) || service.equals(extractTargetRefName(item))) {
```
Comment (zpqrtbnk) [inline hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java:410]: Just to make sure I understand... if a `servicePerPodLabel` has been provided, the load-balancer should not be part of the services, even if it points to only 1 pod, and therefore we should not even run this code - good. If `servicePerPodLabel` has *not* been provided, and the load-balancer points to only 1 pod, we will end up running this code. In which case we want to add the address (to `result`) only if the service name `service` matches the target name. But I'm not too sure about `!result.containsKey(address)`: it means that if you consider the load-balancing service first, you will add it (since the address hasn't been added already) regardless of the name?

**Comment by zpqrtbnk** [comment]
Just to be sure I understand it all, WRT the original guide at https://guides.hazelcast.org/kubernetes-external-client/.

**Using the member image without further configuration**

The guide example will "just work" because since no `servicePerPodLabel` is configured, we will match service and pod names, and therefore will not confuse the discovery service (`hz-hazelcast`) with a member service.

**Using configuration**

Say we want to configure a servicePerPodLabel filter to identify the services that actually match a pod. The original PR did a `!=` comparison to *exclude* the discovery service. This PR uses a `=` comparison to *identify* the member services. So we need something to identify these member services. (The guide does need not provide this).

Instructions would be:

1. Label each member service N with `kubectl label svc hz-hazelcast-N role=hz-member`
2. Configure each member with `servicePerPodLabel name='role', value='hz-member'`

Is this all making sense?

File: hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java (hunk 2 above)
Comment (leszko) [reply hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java:410]: > Just to make sure I understand... if a `servicePerPodLabel` has been provided, the load-balancer should not be part of the services, even if it points to only 1 pod, and therefore we should not even run this code - good. 

Yes, I guess if you provide the explicit configuration, then load-balancer should not be part of the external services even if it fits.

> If `servicePerPodLabel` has _not_ been provided, and the load-balancer points to only 1 pod, we will end up running this code. In which case we want to add the address (to `result`) only if the service name `service` matches the target name. But I'm not too sure about `!result.containsKey(address)`: it means that if you consider the load-balancing service first, you will add it (since the address hasn't been added already) regardless of the name?

I guess that if you don't provide `service-per-pod` label, then we try to automatically find the "right" services. So any service pointing to only one pod will do, but the priority takes the service with the same name. But if there is no service with the same name as the pod, then we proceed with any service that points to one pod only. This way we're backward-compatible.

Comment (zpqrtbnk) [reply hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java:410]: I need to run tests. It looks like if the first address that you consider is the discovery service, because it's not in `result` already you're going to add it regardless of names, and then the original issue (discovery service being reported as a member service) is not fixed. But I may be wrong.

Comment (leszko) [reply hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java:410]: Discussed offline. It should be fine as it is.

**Comment by leszko** [comment]
> **Using the member image without further configuration**
> 
> The guide example will "just work" because since no `servicePerPodLabel` is configured, we will match service and pod names, and therefore will not confuse the discovery service (`hz-hazelcast`) with a member service.

Yes, exactly. It will just work, because the name of the service match the pod name.

> **Using configuration**
> 
> Say we want to configure a `servicePerPodLabel` filter to identify the services that actually match a pod. The original PR did a `!=` comparison to _exclude_ the discovery service. This PR uses a `=` comparison to _identify_ the member services. So we need something to identify these member services. (The guide does need not provide this).
> 
> Additional instructions would be:
> 
> 1. Label each member service N with `kubectl label svc hz-hazelcast-N role=hz-member`
> 2. Configure each member with `servicePerPodLabel name='role', value='hz-member'`
> 
> Is this all making sense?

Yes, exactly. I think that I'll add this info to the guide at some point. But you're right. We should label all services pointing to pods and use this label in the configuration.

File: hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java (hunk 2 above)
Comment (zpqrtbnk) [reply hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesClient.java:410]: Tested OK.

**Review by zpqrtbnk — APPROVED** [review]
Tested OK, happy.

File: hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java (hunk 1 above)
Comment (leszko) [reply hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesProperties.java:106]: 👍
