### PR TITLE
fixes ClientQueueDisruptionTest to test the way we guarentee. 

### LINKED ISSUE #4549: [TEST-FAILURE] ClientQueueDisruptionTest.clientsConsume_withNodeShutdown
```
com.hazelcast.spi.exception.TargetDisconnectedException: null
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:110)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:91)
	at com.hazelcast.client.spi.ClientProxy.invokeInterruptibly(ClientProxy.java:141)
	at com.hazelcast.client.proxy.ClientQueueProxy.invokeInterruptibly(ClientQueueProxy.java:293)
	at com.hazelcast.client.proxy.ClientQueueProxy.poll(ClientQueueProxy.java:144)
	at com.hazelcast.client.proxy.ClientQueueProxy.poll(ClientQueueProxy.java:193)
	at com.hazelcast.client.queue.ClientQueueDisruptionTest.clientsConsume_withNodeShutdown(ClientQueueDisruptionTest.java:66)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast-client/460/testReport/junit/com.hazelcast.client.queue/ClientQueueDisruptionTest/clientsConsume_withNodeShutdown/

### PR DESCRIPTION
**Pull request by sancar**
fixes #4549

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/queue/ClientQueueDisruptionTest.java [hunk 1]
```diff
@@ -54,25 +57,51 @@ public void clientsConsume_withNodeShutdown() throws InterruptedException {
...
-            assertTrue(cluster.getRandomNode().getQueue("Q1").offer(i));
-            assertTrue(cluster.getRandomNode().getQueue("Q2").offer(i));
-
-            TestCase.assertEquals(expect, client1.getQueue("Q1").poll());
-            TestCase.assertEquals(expect, client2.getQueue("Q2").poll());
-
-            expect++;
+            final int index = i;
+
+            makeSureExactlyOneSuccessfulRun(new AssertTask() {
```
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/queue/ClientQueueDisruptionTest.java]: Why not call it assertExactlyOneSuccessfulRun.

Assert is the prefix we use to assert things.

Comment (sancar) [inline hazelcast-client/src/test/java/com/hazelcast/client/queue/ClientQueueDisruptionTest.java]: I changed the name with direct commit.
