### PR TITLE
Query engine should not attempt to use indexes until all migrations are committed

### LINKED ISSUE #8257: PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex
```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.impl.operation.PostJoinMapOperationTest.testPostJoinMapOperation_mapWithIndex(PostJoinMapOperationTest.java:223)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x/com.hazelcast$hazelcast/5164/testReport/junit/com.hazelcast.map.impl.operation/PostJoinMapOperationTest/testPostJoinMapOperation_mapWithIndex/

### PR DESCRIPTION
**Pull request by vbekiaris**
There is a time window between partition table update and `commitMigration` execution is completed, during which the `QueryEngineImpl` will attempt to use an index, however the index may have not been created yet. In order to avoid this, in `MapMigrationAwareService` we keep track of the count of `beforeMigration` invocations vs `commitMigration`/`rollbackMigration` and only allow the `QueryEngineImpl` to use an index when this counter is 0.
This is a temporary workaround for 3.7, the root cause will be fixed in 3.8 (see #8385).
Fixes #8257 , #8046, #4517.
An EE counterpart is required.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java [hunk 1]
```diff
@@ -141,9 +142,13 @@ public QueryResult queryLocalPartitions(String mapName, Predicate predicate, Ite
...
     protected QueryResult tryQueryUsingIndexes(Predicate predicate, Collection<Integer> partitions, MapContainer mapContainer,
-                                               IterationType iterationType) {
+                                               IterationType iterationType, int initialPartitionStateVersion) {
 
-        if (partitionService.hasOnGoingMigrationLocal()) {
+        // if a migration is in progress, do not attempt to use an index as they may have not been created yet.
+        // MapService.getMigrationsInFlight() returns the number of currently executing migrations (for which
+        // beforeMigration has been executed but commit/rollback is not yet executed).
+        // This is a temporary fix for 3.7, the actual issue will be addressed with an additional migration hook in 3.8.
+        if (partitionService.hasOnGoingMigrationLocal() || mapServiceContext.getService().getMigrationsInFlight() > 0) {
```
Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java]: do we still need this check? you are already tracking the partition owner migrations yourself. 'hasOnGoingMigrationLocal()` returns `true` for both partition owner and backup migrations. If current node is master, it also returns `true` for pending migrations. So it can cause a long delay since index will be disabled for irrelevant partitions.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/DelegatingMigrationAwareService.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+/**
+ * A {@link MigrationAwareService} that delegates to another {@link MigrationAwareService} and keeps track of the number of
+ * migrations concerning the primary replica (either as current or new replica index) currently in-flight.
+ */
+public class DelegatingMigrationAwareService implements MigrationAwareService {
+
+    private static final int PRIMARY_REPLICA_INDEX = 0;
+
+    private final MigrationAwareService migrationAwareService;
+    private final AtomicInteger migrationsInFlight;
```
Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/DelegatingMigrationAwareService.java]: minor comment: can you add a comment or rename the field to specify it tracks only the partition owner migrations?

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java (hunk 1 above)
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java]: Thanks for catching this, I will update the condition.

**Comment by jerrinot** [comment]
:+1: good work!

**Comment by metanet** [comment]
👍

**Comment by vbekiaris** [comment]
Thanks @metanet & @jerrinot for your review

**Comment by pveentjer** [comment]
Since there are 2 thumbs up, I'll hit the merge button.
