### PR TITLE
CompletionStage leftovers

### LINKED ISSUE #15688: Subtle change of behaviour of ExecutionCallback during shutdown
In Hazelcast 3.x,  `IMap#submitToKey(K, EntryProcessor, ExecutionCallback` returns immediately. The supplied `ExecutionCallback` is executed after `EntryProcessor` is done, invoking its `onResponse/onFailure` methods respectively. If execution of `ExecutionCallback` fails due to the async executor rejecting execution (eg during Hazelcast shutdown), user is notified by invoking its onFailure method with the `RejectedExecutionException` as argument.

In Hazelcast 4.0, execution callback is submitted via `whenCompleteAsync`, [adapted to a `BiConsumer`](https://github.com/hazelcast/hazelcast/blob/83d814eefb9864187b3a43736d29422a1581f0aa/hazelcast/src/main/java/com/hazelcast/map/impl/proxy/MapProxySupport.java#L1262). If the `BiConsumer` is not executed due to `RejectedExecutionException`, then `ExecutionCallback.onFailure` is not executed -> user is not notified of the failure to execute their callback.

Same issue also applies for other `IExecutorService` methods which accept `ExecutionCallback` as argument.

### LINKED ISSUE #15796: CompletableFuture migration leftovers
- [ ] Handle `RejectedExecutionException` of user provided callbacks (#15688)
- [ ] Default `CompletionStage` method implementations should schedule execution on default async executor instead of completion thread
- [ ] Consider brief spin-wait before parking in `AbstractInvocationFuture` blocking methods
- [x] Remove leftover references to `ICompletableFuture` 
  (PRs: #15825 & https://github.com/hazelcast/hazelcast-client-protocol/pull/253 )
- [x] Ensure public API only exposes `CompletionStage`
    (PRs: https://github.com/hazelcast/hazelcast/pull/15797 & https://github.com/hazelcast/hazelcast-enterprise/pull/3248)

### PR DESCRIPTION
**Pull request by vbekiaris**
- Removes `IMap.submitToKey(K, EntryProcessor, ExecutionCallback)`
Since migrating public APIs to `CompletionStage`, the same and richer functionality
is available by using the `CompletionStage` returned from
`submitToKey(K, EntryProcessor)` to register user callbacks.

- Fixes executor callback not being notified when rejected from executor
User supplied callbacks in `IExecutorService#submit` variants
were previously not notified in case they were not executed due to
executor throwing a `RejectedExecutionException`. This is now handled so
the user supplied `ExecutionCallback#onFailure` method is invoked with
the `RejectedExecutionException` as argument.

- Changes default executor for non-async `CompletionStage` callbacks 
All default non-async and async completions now use the `DEFAULT_ASYNC_EXECUTOR`.
Reasoning: execution from completion thread could result
in halting Hazelcast threads when executing blocking user code.
Also, unifies member- and client-side behaviour, so on the client
side instead of the user executor, we also use the default
async executor (ie `ForkJoinPool#commonPool` or thread-per-
task if common pool's parallelism level is < 2).

Additionally:
- fixes handling of `RejectedExecutionException` when
executing user callback from a registered wait node
- fixes dependent completions count in `AbstractInvocationFuture`
- cleans up multiple instances of DEFAULT_ASYNC_EXECUTOR in
different `CompletableFuture` implementations

Fixes #15796 
Fixes #15688

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/client/impl/ClientDelegatingFuture.java [hunk 1]
```diff
@@ -150,12 +148,12 @@ protected ClientInvocationFuture getFuture() {
 
     @Override
     public <U> CompletableFuture<U> thenApply(Function<? super V, ? extends U> fn) {
-        return future.thenApply(new DeserializingFunction<>(fn));
+        return future.thenApplyAsync(new DeserializingFunction<>(fn), defaultExecutor());
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/client/impl/ClientDelegatingFuture.java]: shouldn't this be ran inside user thread in a callers-run-fashion?

File: hazelcast/src/main/java/com/hazelcast/internal/util/ConcurrencyUtil.java [hunk 2]
```diff
@@ -44,6 +45,20 @@ public String toString() {
...
+    public static final Executor DEFAULT_ASYNC_EXECUTOR;
+
+    static {
+        Executor asyncExecutor;
+        if (ForkJoinPool.getCommonPoolParallelism() > 1) {
+            asyncExecutor = ForkJoinPool.commonPool();
+        } else {
+            asyncExecutor = command -> new Thread(command).start();
+        }
+        DEFAULT_ASYNC_EXECUTOR = asyncExecutor;
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ConcurrencyUtil.java]: can we have a way of logging for chosen executor for diagnostic purposes?

File: hazelcast/src/main/java/com/hazelcast/client/impl/ClientDelegatingFuture.java (hunk 1 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/client/impl/ClientDelegatingFuture.java]: That was the case previously, the user-supplied callback would be executed either in the calling thread (if the future was already completed) or by the thread that completes the future (for example when the future was not completed at the time the `Function` is registered as a dependent). The problem with this approach is that the thread that completes the future can be a Hazelcast response thread and allowing arbitrary blocking user code to be executed on hazelcast threads can result in halting Hazelcast. For example the following function executed from a client-side input thread may fail to complete:
```
IMap<Integer, Integer> map = hz.getMap("test");
map.put(1, 2);
map.put(2, 4);
CompletionStage<Integer> stage = map.getAsync(1).thenApply(v -> {
    System.out.println(Thread.currentThread()); // never completes when executed from hz.client_0.IO.thread-in-*
    return map.get(v);
});
```

`CompletionStage` [javadoc](https://docs.oracle.com/javase/8/docs/api/index.html?java/util/concurrent/CompletionStage.html) reads:
> Additionally, execution of a new stage's computations may be arranged in any of three ways: default execution, default asynchronous execution (using methods with suffix async that employ the stage's default asynchronous execution facility), or custom (via a supplied Executor). The execution properties of default and async modes are specified by CompletionStage implementations, not this interface.

So I think that this change is aligned with `CompletionStage` contract and will save users from risk of blocking critical hazelcast threads.

File: hazelcast/src/main/java/com/hazelcast/internal/util/ConcurrencyUtil.java (hunk 2 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/internal/util/ConcurrencyUtil.java]: sounds good, but this is initialized in a static context and IIRC we avoid obtaining `ILogger`s to avoid initializing logging with wrong context (eg disregarding properties in `Config` object). wdyt?

**Comment by sancar** [comment]
@vbekiaris 
With changing the ClientInvocationFuture, we have changed the behaviour of the users future. They are not using the userExecutor anymore in most of the places. But, when I follow ClientExecutionService.getUserExecutor methods, I still see some usages. 

1. DurableExecutor and Executor , NearcachedClientMapProxy , ClientRingBufferProxy.readManyAsync , ClientReliableTopicProxy. These seems like needs to use `DEFAULT_ASYNC_EXECUTOR` instead.
3. ClientInvocation.getUserExecutor. Looks like it is unused now. We can delete it. 
4. ClientICMPManager. Looks like a mistake. I think It should not use the user executor but it should use the internal one. 

If we clear all, we can delete the userExecutor from ClientExecutionServiceImpl together with its property from ClientProperties.

**Comment by vbekiaris** [comment]
@sancar thanks for the analysis. I prepared the removal of user executor however since it is a rather large change (affects 30+ files, includes removal of `executorPoolSize` from configuration classes/XSD etc), I would rather create a separate PR for that.

File: hazelcast/src/main/java/com/hazelcast/internal/util/ConcurrencyUtil.java (hunk 2 above)
Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/internal/util/ConcurrencyUtil.java]: Maybe inside a `DiagnosticsPlugin`? But not sure about which one or even if it is worth to create a new one.

**Comment by vbekiaris** [comment]
@ahmetmircik @sancar thanks for the reviews
