### PR TITLE
Offload non-cooperative ProcessorSupplier.init and ProcessorMetaSupplier.init [HZ-1204]

### LINKED ISSUE #21499: Incorrect handling of blocking calls in ProcessorSupplier.init() [HZ-1204]
According to its contract, the `init()` and `close()`  methods in `Processor`, `ProcessorSupplier` and `ProcessorMetaSupplier` are allowed to block, even for cooperative processors. It's explicitly written in `Processor` javadoc, but it's assumed in the docs, as the methods are used for resource initialization and cleanup. We also use it this way in our code, e.g. for opening the HZ client for remote map reader.

However, if the methods are blocking for a long time, they can easily starve thread pools:
- the coordinator thread pool, with four hard-coded threads, on master member. When all threads are blocked, most operations in the `Job` class are blocked too
- the generic operation thread pool, with configurable size. When all threads in this pool are blocked, it blocks many non-Jet operations, such as `IMap.values()`.

There are 2 possible solutions:

1. we will offload these methods to their own pool (shared with "cached" threads) so that they don't block anything else other than the initialization of other jobs. The handling of `InitExeutionOperation` will need to become async. This will create extra overhead for most processors that don't do any blocking calls in `init` or `close` and will slow down the job deploy+cleanup time. We can guard with methods akin to `Processor.closeIsCooperative()`, but that's an extra burden for the developer and it's easy to omit.

2. we can change the contract of these methods to specify that they can block only for a short time. If they need to block longer, they should move the initialization later and do it lazily in `process()`. This includes fixing all our processors to comply.

Below are tests that can be added to `ExecutionLifecycleTest`, should we implement the 1st approach. Today these tests fail.

```java
    @Test
    public void when_pmsInitBlocks_then_otherJobsNotBlocked() throws ExecutionException, InterruptedException {
        // Given
        DAG dagBlocking = new DAG().vertex(new Vertex("test",
                new MockPMS(() -> new MockPS(MockP::new, MEMBER_COUNT)).initBlocks()));
        DAG dagNormal = new DAG().vertex(new Vertex("test",
                new MockPS(MockP::new, MEMBER_COUNT)));

        List<Future<Job>> submitFutures = new ArrayList<>();

        // When
        int numJobs = 16;
        for (int i = 0; i < numJobs; i++) {
            submitFutures.add(spawn(() -> newJob(dagBlocking)));
        }

        // Then
        // JetService.getJobs()
        if (useLightJob) {
            assertEquals(0, instance().getJet().getJobs().size());
        } else {
            assertTrueEventually(() -> assertEquals(numJobs, instance().getJet().getJobs().size()), 5);
        }
        // newJob()
        instance().getJet().newJob(dagNormal).join();
        // newLightJob()
        instance().getJet().newLightJob(dagNormal).join();
        // generic API operation - generic API threads should not be starved
        for (Object m : instance().getMap("m").values()) {
            System.out.println(m);
        }

        for (int i = 0; i < submitFutures.size(); i++) {
            MockPS.unblock();
        }
        for (Future<Job> f : submitFutures) {
            f.get().join();
        }
    }

    @Test
    public void when_psInitBlocks_then_otherJobsNotBlocked() throws Exception {
        // Given
        DAG dagBlocking = new DAG().vertex(new Vertex("test",
                new MockPS(MockP::new, MEMBER_COUNT).initBlocks()));
        DAG dagNormal = new DAG().vertex(new Vertex("test",
                new MockPS(MockP::new, MEMBER_COUNT)));

        List<Future<Job>> submitFutures = new ArrayList<>();

        // When
        int numJobs = 16;
        for (int i = 0; i < numJobs; i++) {
            submitFutures.add(spawn(() -> newJob(dagBlocking)));
        }

        // Then
        // JetService.getJobs()
        if (useLightJob) {
            assertEquals(0, instance().getJet().getJobs().size());
        } else {
            assertTrueEventually(() -> assertEquals(numJobs, instance().getJet().getJobs().size()), 5);
        }
        // newJob()
        instance().getJet().newJob(dagNormal).join();
        // newLightJob()
        instance().getJet().newLightJob(dagNormal).join();
        // generic API operation - generic API threads should not be starved
        for (Object m : instance().getMap("m").values()) {
            System.out.println(m);
        }

        for (int i = 0; i < submitFutures.size() * MEMBER_COUNT; i++) {
            MockPS.unblock();
        }
        for (Future<Job> f : submitFutures) {
            f.get().join();
        }
    }

    @Test
    public void when_processorInitBlocks_then_otherJobsNotBlocked() throws Exception {
        // Given
        DAG dagBlocking = new DAG().vertex(new Vertex("test",
                () -> new MockP().initBlocks()));
        DAG dagNormal = new DAG().vertex(new Vertex("test",
                MockP::new));

        List<Future<Job>> submitFutures = new ArrayList<>();

        // When
        int numJobs = 16;
        for (int i = 0; i < numJobs; i++) {
            submitFutures.add(spawn(() -> newJob(dagBlocking)));
        }

        // Then
        // JetService.getJobs()
        if (useLightJob) {
            assertEquals(0, instance().getJet().getJobs().size());
        } else {
            assertTrueEventually(() -> assertEquals(numJobs, instance().getJet().getJobs().size()), 5);
        }
        // newJob()
        instance().getJet().newJob(dagNormal).join();
        // newLightJob()
        instance().getJet().newLightJob(dagNormal).join();
        // generic API operation - generic API threads should not be starved
        for (Object m : instance().getMap("m").values()) {
            System.out.println(m);
        }

        for (int i = 0; i < submitFutures.size() * MEMBER_COUNT * parallelism; i++) {
            MockP.unblock();
        }
        for (Future<Job> f : submitFutures) {
            f.get().join();
        }
    }
```

For these tests, the `TestProcessors` class also needs to be modified according to the [TestProcessors.txt](https://github.com/hazelcast/hazelcast/files/8800214/TestProcessors.txt) file.

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Allow ProcessorMetaSupplier.init and ProcessorSupplier.init to be offloaded to a different thread to not starve the partition thread. User can mark PS/PMS as (non-)cooperative by overriding PMS#initIsCooperative and PS#initIsCooperative method.  

Fixes #21499

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] ~Send backports/forwardports if fix needs to be applied to past/future releases~
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc

The change is extensive. Won't be backported.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/jet/core/Processor.java [hunk 1]
```diff
@@ -159,6 +159,10 @@ default boolean isCooperative() {
     default void init(@Nonnull Outbox outbox, @Nonnull Context context) throws Exception {
     }
 
+    default boolean initIsCooperative() {
+        return true;
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/core/Processor.java:163]: We should default to `false`, for b-w compatibility. Same as in `closeIsCooperative`.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java [hunk 2]
```diff
@@ -90,16 +94,59 @@ protected CompletableFuture<?> doRun() {
...
         ExecutionPlan plan = deserializePlan(serializedPlan);
-        if (isLightJob) {
-            return service.getJobExecutionService().runLightJob(jobId(), executionId, caller,
-                    coordinatorMemberListVersion, participants, plan);
+        InitExecutionOffload initExecutionAction = new InitExecutionOffload(service, plan);
+        boolean isCooperative = plan.getVertices().stream()
+                .allMatch(v -> {
+                    ProcessorSupplier supplier = v.processorSupplier();
+                    if (!supplier.initIsCooperative()) return false;
+                    return supplier.get(1).iterator().next().initIsCooperative(); // todo: better detection?
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java:102]: I'm not sure we can do this. We can't ask the `ProcessorSupplier` to provide 1 processor, if local parallelism is different. Some processors split the work among expected number of processors. They also can track processors they created. This is not a good idea...

File: hazelcast/src/test/java/com/hazelcast/jet/SimpleTestInClusterSupport.java [hunk 3]
```diff
@@ -94,7 +95,9 @@ public void supportAfter() {
         SUPPORT_LOGGER.info("Ditching " + jobs.size() + " jobs in SimpleTestInClusterSupport.@After: " +
                 jobs.stream().map(j -> idToString(j.getId())).collect(joining(", ", "[", "]")));
         for (Job job : jobs) {
-            ditchJob(job, instances());
+            if (!job.isLightJob()) {
```
Comment (viliam-durina) [inline hazelcast/src/test/java/com/hazelcast/jet/SimpleTestInClusterSupport.java:98]: We don't need to cancel light jobs?

**Comment by TomaszGaweda** [comment]
Note to reviewers: most of the lines marked as changed are just moved inside some lambda (and because of that, identation changed). Instead of blocking code in various places I'm composing a chain of actions using CompletableFuture. Each CF may be executed on offload executor

**Comment by TomaszGaweda** [comment]
Those tests are passing for me, there are some Jenkins issues pending, I guess it's related to them

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java [hunk 4]
```diff
@@ -316,27 +315,24 @@ public CompletableFuture<RawJobMetrics> runLightJob(
...
-
-
-        // initial log entry with all of jobId, jobName, executionId
-        logger.info("Execution plan for jobId=" + idToString(jobId)
-                + ", jobName=" + (execCtx.jobName() != null ? '\'' + execCtx.jobName() + '\'' : "null")
-                + ", executionId=" + idToString(executionId) + " initialized");
+        jobClassloaderService.prepareProcessorClassLoaders(jobId);
+        Set<Address> addresses = participants.stream().map(MemberInfo::getAddress).collect(toSet());
+        ClassLoader jobCl = jobClassloaderService.getClassLoader(jobId);
+        return doWithClassLoader(jobCl, () -> execCtx.initialize(coordinator, addresses, plan))
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java:328]: This is not correct. It sets thread-local values, but then possibly executes on another thread.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java (hunk 4 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java:328]: After analyzing I see what you mean. However, I think the doWithClassLoader here is not necessary, as ExecutionPlan.initProcSuppliers and others already wraps every processor creation in the doWithClassLoader. This one seems to be made "just in case", IMHO it's ok to remove it. Do you agree?

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java]: The comment was about `jobClassloaderService.prepareProcessorClassLoaders()`.

Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java]: Oh, you are right! However, the comment is similar - we don't use deserializeWithCustomClassLoader, so we don't need this call. I removed it in the next commit.

File: hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java [hunk 5]
```diff
@@ -438,7 +442,7 @@ public void when_executionCancelled_then_jobCompletedWithCancellationException()
     }
 
     @Test
-    public void when_executionCancelledBeforeStart_then_jobFutureIsCancelledOnExecute() {
+    public void when_executionCancelledBeforeStart_then_jobFutureIsCancelledOnExecute() throws ExecutionException, InterruptedException {
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java:445]: Just `throws Exception` is fine in tests.

File: hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java [hunk 6]
```diff
@@ -700,6 +704,171 @@ public void when_memberLeft_then_jobFails() {
...
+        int numJobs = 2;
+        for (int i = 0; i < numJobs; i++) {
+            String name = "pmsInitBlocking_" + i;
+            submitFutures.add(spawn(() -> newJob(name, dagBlocking)));
+        }
+
+        // Then
+        instance().getJet().newJob(dagNormal).join();
+        instance().getJet().newLightJob(dagNormal).join();
+//         generic API operation - generic API threads should not be starved
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java:727]:
```suggestion
        // generic API operation - generic API threads should not be starved
```

File: hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java [hunk 7]
```diff
@@ -55,6 +64,13 @@ default void init(@Nonnull Context context) throws Exception {
     @Nonnull
     Collection<? extends Processor> get(int count);
 
+    /**
+     * If true, then {@link #close(Throwable)} should not block by e.g. doing IO.
+     */
+    default boolean closeIsCooperative() {
+        return true;
```
Comment (frant-hartm) [inline hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java:71]: Same here - should default to false.

**Review by frant-hartm — CHANGES_REQUESTED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java [hunk 8]
```diff
@@ -135,6 +142,13 @@ default void init(@Nonnull Context context) throws Exception {
     @Nonnull
     Function<? super Address, ? extends ProcessorSupplier> get(@Nonnull List<Address> addresses);
 
+    /**
+     * If true, then {@link #close(Throwable)} should be cooperative, meaning it shouldn't block (e.g. by doing IO).
+     */
+    default boolean closeIsCooperative() {
+        return true;
+    }
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java:150]: Well, I was about to ask you the same :P IMHO backward-compatible behaviour is the same as if the processors were cooperative. After this change, some processors may declare itself non-cooperative, but before all init/close were treated as cooperative. However, this is an implementation details, so IMHO no user should rely on this.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 9]
```diff
@@ -124,6 +129,8 @@ public class MasterJobContext {
     public static final int SNAPSHOT_RESTORE_EDGE_PRIORITY = Integer.MIN_VALUE;
     public static final String SNAPSHOT_VERTEX_PREFIX = "__snapshot_";
 
+    private static final ExecutorService START_JOB_MERGE_EXECUTOR = Executors.newSingleThreadExecutor();
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:132]: Previously the refactored parts were running on the coordinator thread, so I think it's ok. I also like it uses one of the existing executors.

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java [hunk 10]
```diff
@@ -198,12 +220,15 @@ public Function<Address, ProcessorSupplier> get(@Nonnull List<Address> addresses
...
             assertEquals("all PS that have been init should have been closed at this point",
                     MockPS.initCount.get(), MockPS.closeCount.get());
-            assertTrue("Close called without calling init()", initCalled.get());
-            assertTrue("PMS.close() already called once",
-                    closeCalled.compareAndSet(false, true)
-            );
+            assertTrue("Close called more times than init was called. Init count: "
+                    + initCount.get() + " close count: " + closeCount, initCount.get() >= closeCount.get());
+            assertTrue("Close called " + closeCount.get() + " times, but init called "
+                    + initCount.get() + " times!", closeCount.get() <= initCount.get());
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java:243]: Actually this explains the comment about: https://github.com/hazelcast/hazelcast/pull/21595#discussion_r907403873
it's just typo

File: hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java (hunk 7 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorSupplier.java:77]: Done

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by ufukyilmaz** [comment]
run-nightly-tests

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 11]
```diff
@@ -633,15 +669,18 @@ void cancelExecutionInvocations(long jobId, long executionId, TerminationMode mo
...
-            final Runnable nonSynchronizedAction;
             mc.lock();
+            JobStatus status = mc.jobStatus();
+            if (status == COMPLETED || status == FAILED) {
+                logIgnoredCompletion(failure, status);
+            }
+            mc.unlock();
+          })
+          .thenComposeAsync(r -> completeVertices(failure))
+          .thenAccept(ignored -> {
```
Comment (ufukyilmaz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:680]: The task in this `thenAccept` block must be run on the coordinator thread but currently it's not guaranteed to run on it. 
Please check: https://stackoverflow.com/a/46062939/4793261

Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: True, I've pushed a change that will force coordination thread executor here.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 12]
```diff
@@ -194,57 +200,89 @@ private boolean isCancelled() {
...
+                    if (tuple != null) {
+                        initExecution(tuple.membersView, tuple.plans);
+                    }
+                }))
+                .whenComplete((r, e) -> {
+                    if (e != null) {
+                        finalizeJob(peel(e));
+                    }
+                })
+                .join();
```
Comment (ufukyilmaz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:260]: Formerly, we didn't block the execution here, I believe we must not block here. It seems to be the cause of the deadlock in the `ParallelStressTest`.

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
PR passed [soak tests](http://jenkins.hazelcast.com/job/jet-soak-tests-tomasz/45/)

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java [hunk 13]
```diff
@@ -277,28 +278,23 @@ public CompletableFuture<RawJobMetrics> runLightJob(
...
-            ClassLoader jobCl = jobClassloaderService.getClassLoader(jobId);
-            // We don't create the CL for light jobs.
-            assert jobClassloaderService.getClassLoader(jobId) == null;
-            doWithClassLoader(
-                    jobCl,
-                    () -> execCtx.initialize(coordinator, addresses, plan)
-            );
-        } catch (Throwable e) {
-            completeExecution(execCtx, new CancellationException());
-            throw e;
```
Comment (ufukyilmaz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java:291]: Previously, we were rethrowing the exception here and this thrown exception is handled differently than the exception propagated through the returned future. See the exception handling in the `AsyncJobOperation` here: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/jet/impl/operation/AsyncOperation.java#L56-L60. 
In this place, we're logging the thrown exceptions as an error but for the exceptions propagated through the future, we're not doing the same. I thought for handling this but I couldn't find a proper way for solving this discrepancy. I can only think of an ugly way that logging the exceptions in the more deeper place rather than inside the `AsyncOperation`. 
cc: @viliam-durina, @frant-hartm what do you suggest for handling this? 

By the way, this is my only remaining review item, other than that this PR looks good to me.

Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java:291]: Do you have any particular example?
The whenComplete() section also completes the execution context. whenComplete cannot recover from exceptions, so it's carried over to the caller - just like "throw e" is doing here, just that it's wrapped in ExecutionException. I _think_ the handling is more or less the same, maybe I'm missing something

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
Interesting, those tests are passing on my laptop...

File: hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java [hunk 14]
```diff
@@ -700,6 +703,166 @@ public void when_memberLeft_then_jobFails() {
...
+        // Given
+        DAG dagBlocking = new DAG().vertex(new Vertex("test",
+                new MockPMS(() -> new MockPS(MockP::new, MEMBER_COUNT)).initBlocks()));
+        DAG dagNormal = new DAG().vertex(new Vertex("test",
+                new MockPS(MockP::new, MEMBER_COUNT)));
+
+        List<Future<Job>> submitFutures = new ArrayList<>();
+
+        // When
+        int numJobs = 1;
```
Comment (ufukyilmaz) [inline hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java:717]: Could you increase the number of jobs to be more than both the operation thread count and coordination executor thread count since both of these thread pools may get stuck by these init/close calls. I'd suggest this change for all other tests below.

**Comment by TomaszGaweda** [comment]
run-nightly-tests

File: hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java (hunk 14 above)
Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java:717]: I'm limited by the size of offloadable executor. If number of job exceeds the offloadable executor capacity, the tests are stuck even if functionality is ok.

Alternatively, I can "hack" to pass custom executor size 🤔

Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java]: Done

File: hazelcast/src/main/java/com/hazelcast/jet/impl/LightMasterContext.java [hunk 15]
```diff
@@ -123,7 +123,9 @@ public LightMasterContext(
         dag.iterator().forEachRemaining(vertices::add);
         Map<MemberInfo, ExecutionPlan> executionPlanMapTmp;
         try {
-            executionPlanMapTmp = createExecutionPlans(nodeEngine, members, dag, jobId, jobId, config, 0, true, subject);
+            executionPlanMapTmp =
+                    createExecutionPlans(nodeEngine, members, dag, jobId, jobId, config, 0, true, subject)
+                            .get();
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/LightMasterContext.java]: Done

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java [hunk 16]
```diff
@@ -197,13 +227,21 @@ public Function<Address, ProcessorSupplier> get(@Nonnull List<Address> addresses
...
+        @Override
+        public void close(Throwable error) throws InterruptedException {
+            System.out.println("MockPMS.close called on " + Thread.currentThread().getName());
+            if (closeBlocks) {
+                blockingSemaphore.acquire();
+            }
+            closeCount.incrementAndGet();
+
+            assertEquals("Close called more times than init was called. Init count: "
+                    + initCount.get() + " close count: " + closeCount, initCount.get(), closeCount.get());
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java:243]: It seems that these assertion errors are caught in `com.hazelcast.jet.impl.MasterJobContext#completeVertices` - I see failures in the logs, but the test passes.

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java [hunk 17]
```diff
@@ -249,14 +296,38 @@ public MockPS setCloseError(Throwable closeError) {
...
+            System.out.println("MockPS.init called on " + Thread.currentThread().getName());
             initCalled = true;
             initCount.incrementAndGet();
 
             if (initError != null) {
                 throw sneakyThrow(initError);
             }
+
+            if (initBlocks) {
+                blockingSemaphore.acquire();
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java:329]: Let's add something like `Thread.sleep(new Random().nextInt(500));` after all `blockingSemaphore.acquire()`, to make the blocking more unpredictable.

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java [hunk 18]
```diff
@@ -197,13 +227,21 @@ public Function<Address, ProcessorSupplier> get(@Nonnull List<Address> addresses
         }
 
         @Override
-        public void close(Throwable error) {
-            assertEquals("all PS that have been init should have been closed at this point",
-                    MockPS.initCount.get(), MockPS.closeCount.get());
-            assertTrue("Close called without calling init()", initCalled.get());
-            assertTrue("PMS.close() already called once",
-                    closeCalled.compareAndSet(false, true)
-            );
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java:206]: These assertions don't have an equivalent in the new code.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java [hunk 19]
```diff
@@ -237,33 +268,45 @@ public CompletableFuture<Void> beginExecution(TaskletExecutionService taskletExe
...
+                ProcessorSupplier processorSupplier = vertex.processorSupplier();
+                RunnableEx closeAction = () -> {
+                    try {
+                        ClassLoader processorCl = isLightJob ?
+                                null : jobClassloaderService.getProcessorClassLoader(jobId, vertex.name());
+                        doWithClassLoader(processorCl, () ->  processorSupplier.close(error));
+                    } catch (Throwable e) {
+                        logger.severe(jobNameAndExecutionId()
+                                + " encountered an exception in ProcessorSupplier.close(), ignoring it", e);
+                    }
```
Comment (frant-hartm) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java:303]: Here we catch exceptions from `ProcessorSupplier#close` so the asserts in MockPS won't do anything. This is NOT new issue introduced in this PR, but let's fix it (in the test ...).

**Review by frant-hartm — CHANGES_REQUESTED** [review]

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java [hunk 20]
```diff
@@ -150,13 +153,16 @@ public boolean complete() {
 
     public static class MockPMS implements ProcessorMetaSupplier {
 
-        static AtomicBoolean initCalled = new AtomicBoolean();
-        static AtomicBoolean closeCalled = new AtomicBoolean();
+        static AtomicInteger initCount = new AtomicInteger();
+        static AtomicInteger closeCount = new AtomicInteger();
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java:194]: Added assertion method that is called only when test is using MockPMS and expects 1 job

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java [hunk 21]
```diff
@@ -155,11 +161,37 @@ public ExecutionContext initialize(
...
+    }
+
+    private InternalSerializationService createSerializationService(JobClassLoaderService jobClassLoaderService,
+                                                                    JetServiceBackend jetServiceBackend) {
+        if (isLightJob) {
+            return jetServiceBackend.createSerializationService(jobConfig.getSerializerConfigs());
+        }
+        InternalSerializationService internalSerializationService;
+        try {
+            jobClassLoaderService.prepareProcessorClassLoaders(jobId);
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java]: Right, my mistake

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java]: Tests reworked to raise assertion error after each test, while close() is only collecting what is wrong

File: hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java (hunk 18 above)
Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/core/TestProcessors.java:206]: 1 - restored
2 - restored
3 - restored by additional method used in only some tests, in which we use MockPMS and have only one job

**Comment by TomaszGaweda** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java [hunk 22]
```diff
@@ -237,33 +250,44 @@ public CompletableFuture<Void> beginExecution(TaskletExecutionService taskletExe
...
+                        + " encountered an exception in Processor.close(), ignoring it", e);
             }
         }
 
         JobClassLoaderService jobClassloaderService = jetServiceBackend.getJobClassLoaderService();
         ClassLoader classLoader = jobClassloaderService.getClassLoader(jobId);
+        List<CompletableFuture<Void>> futures = new ArrayList<>(vertices.size());
+
+        ExecutorService offloadExecutor = nodeEngine.getExecutionService().getExecutor(JOB_OFFLOADABLE_EXECUTOR);
         doWithClassLoader(classLoader, () -> {
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/ExecutionContext.java:274]: Unnecessary `doWithClassLoader`

File: hazelcast/src/main/java/com/hazelcast/jet/impl/LightMasterContext.java [hunk 23]
```diff
@@ -122,56 +137,72 @@ public LightMasterContext(
...
+                }
+                jobCompletionFuture.completeExceptionally(fail);
             }
-            jobCompletionFuture.completeExceptionally(failure);
+        });
+    }
+
+    private void invokeClose(@Nullable Throwable failure, ProcessorMetaSupplier metaSupplier) {
+        try {
+            metaSupplier.close(failure);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/LightMasterContext.java:202]: Missing `doWithClassLoader`

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 24]
```diff
@@ -773,25 +810,39 @@ private void logIgnoredCompletion(@Nullable Throwable failure, JobStatus status)
...
 
-    private void completeVertices(@Nullable Throwable failure) {
+    private CompletableFuture<Void> completeVertices(@Nullable Throwable failure) {
         if (vertices != null) {
+            ExecutorService offloadExecutor =
+                    mc.nodeEngine().getExecutionService().getExecutor(JOB_OFFLOADABLE_EXECUTOR);
+            List<CompletableFuture<Void>> futures = new ArrayList<>(vertices.size());
             JobClassLoaderService classLoaderService = mc.getJetServiceBackend().getJobClassLoaderService();
             JetDelegatingClassLoader jobCl = classLoaderService.getClassLoader(mc.jobId());
             doWithClassLoader(jobCl, () -> {
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:820]: Unnecessary `doWithClassLoader`

**Review by viliam-durina — CHANGES_REQUESTED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 25]
```diff
@@ -194,57 +200,88 @@ private boolean isCancelled() {
...
+                    if (tuple != null) {
+                        initExecution(tuple.membersView, tuple.plans);
+                    }
+                }))
+                .whenComplete((r, e) -> {
+                    if (e != null) {
+                        finalizeJob(peel(e));
+                    }
+                });
+    }
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: I've tried it, but some tests started to fail. I will try again tomorrow

**Comment by TomaszGaweda** [comment]
run-nightly-tests

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 25 above)
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: I think current version is even better (very humble, I know), can you check? :)

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java [hunk 26]
```diff
@@ -553,38 +545,41 @@ public CompletableFuture<RawJobMetrics> beginExecution(
...
-                        logger.fine("Execution of " + execCtx.jobNameAndExecutionId() + " was cancelled");
-                    } else if (e != null) {
-                        logger.fine("Execution of " + execCtx.jobNameAndExecutionId()
-                                + " completed with failure", e);
-                    } else {
-                        logger.fine("Execution of " + execCtx.jobNameAndExecutionId() + " completed");
-                    }
-                }));
+                      .handle((r, e) -> {
+                          RawJobMetrics terminalMetrics;
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobExecutionService.java:549]: I think you are visiting old commit; now it's:
```java
if (collectMetrics && e == null) {
```

So metrics collection won't be invoked in "bad case". I could replace it with thenApply + whenComplete, but IMHO it's just easier to read this way

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java [hunk 27]
```diff
@@ -377,8 +391,8 @@ public JobConfig getJobConfig() {
         return jobConfig;
     }
 
-    void addVertex(VertexDef vertex) {
-        vertices.add(vertex);
+    synchronized void setVertex(int position, VertexDef vertex) {
```
Comment (ufukyilmaz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:394]: I couldn't completely understand the reason for changing it to a synchronized method. Could you explain with which accesses are we trying to synchronize this setVertex? I am asking it since only making this method synchronized alone may not be enough.

Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:394]: Now all vertices' meta suppliers initialization may be done on different thread; see `ExecutionPlanBuilder#createExecutionPlans`, where we interate over each vertex, init it and add to the plan. Because different threads may add vertices, we must synchronize access to the collection, otherwise different threads may overwrite it's writes

Comment (ufukyilmaz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:394]: If we only need to synchronize the writes to different indexes on the collection, this synchronized block may not be necessary after replacing this ArrayList with a fixed sized collection. Of course, the effect of this on performance may be negligible, I'm just writing it to just consider it. cc: @krzysztofslusarski

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java [hunk 28]
```diff
@@ -148,125 +152,135 @@ public class ExecutionPlan implements IdentifiedDataSerializable {
...
+                  int memberIndex, int memberCount, boolean isLightJob, Subject subject, int expectedVerticesCount) {
         this.partitionAssignment = partitionAssignment;
         this.jobConfig = jobConfig;
         this.lastSnapshotId = lastSnapshotId;
         this.memberIndex = memberIndex;
         this.memberCount = memberCount;
         this.isLightJob = isLightJob;
         this.subject = subject;
+        this.vertices = new ArrayList<>(expectedVerticesCount);
+        for (int i = 0; i < expectedVerticesCount; i++) {
```
Comment (krzysztofslusarski) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:164]: Can we change it to fixed size array?

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java (hunk 27 above)
Comment (krzysztofslusarski) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java:394]: If we can switch to fixed size array then that ```synchronized``` is not needed. 

You also shouldn't use ```synchronized``` on ```this```, better way is to create an ```private static final Object MUX = new Object();``` and synchronize on that. The difference is with ```synchronized``` on ```this``` you have no control if someone do:

```java
ExecutionPlan executionPlan = new ExecutionPlan();
synchronized (executionPlan) {
    // ...
}
```

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java (hunk 28 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/init/ExecutionPlan.java]: Done

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by ufukyilmaz** [comment]
Note for other reviewers: 
This failing `when_memberLeft_then_jobFails` also fails with the current master in the same way when we use client as a job submitter. So, we can ignore this failure by changing the root cause assertion to `TargetNotMemberException or MemberLeftException`. For the checking this behavior, you can try:
```
@Test
public void when_memberLeft_withClient_then_jobFails() {
    // Test for https://github.com/hazelcast/hazelcast/issues/18844

    // This test doesn't use the shared cluster because it shuts down one of the members
    HazelcastInstance inst1 = createHazelcastInstance();
    HazelcastInstance inst2 = createHazelcastInstance();
    Address inst1Address = inst1.getCluster().getLocalMember().getAddress();
    String inst1AddressStr = inst1Address.getHost() + ":" + inst1Address.getPort();
    HazelcastInstance client = createHazelcastClient(new ClientConfig().setNetworkConfig(
            new ClientNetworkConfig()
                    .setSmartRouting(false)
                    .setAddresses(Collections.singletonList(inst1AddressStr))));
    DAG dag = new DAG();
    dag.newVertex("v", () -> new MockP().streaming());

    Job job = client.getJet().newLightJob(dag);
    assertJobRunningEventually(inst1, job, null);
    inst2.getLifecycleService().terminate();

    assertThatThrownBy(() -> job.join())
            .hasRootCauseInstanceOf(MemberLeftException.class);
}
```

**Comment by ufukyilmaz** [comment]
Could you override the `initIsCooperative` and `closeIsCooperative` to return true in `MetaSupplierFromProcessorSupplier`? I believe these calls of this wrapper are cooperative.

**Comment by ufukyilmaz** [comment]
run-nightly-tests

**Review by ufukyilmaz — APPROVED** [review]
It looks good to me. Thanks for your huge effort on this PR. 

Just one note for a future PR: we should iterate over all the existing PS/PMS'es. If they are cooperative, marking them as cooperative will be better.

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-nightly-tests

File: hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java [hunk 29]
```diff
@@ -696,8 +710,178 @@ public void when_memberLeft_then_jobFails() {
...
 
-        assertThatThrownBy(() -> job.join())
-                .hasRootCauseInstanceOf(MemberLeftException.class);
+        try {
+            job.join();
+        } catch (Throwable t) {
+            Throwable cause = getRootCause(t);
+            assertTrue("exception must be of type MemberLeftException or TargetNotMemberException, but was "
+                    + cause.getClass(),
+                    cause instanceof MemberLeftException || cause instanceof TargetNotMemberException);
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java:719]:
```suggestion
            assertThat(cause).isInstanceOfAny(MemberLeftException.class, TargetNotMemberException.class);
```

File: hazelcast/src/test/java/com/hazelcast/jet/impl/JobSummaryTest.java [hunk 30]
```diff
@@ -128,8 +128,10 @@ public void when_streamingJobLifecycle() {
...
 
     @Test
-    public void when_lightJob() {
+    public void when_lightJob() throws InterruptedException {
         Job job = instance.getJet().newLightJob(newStreamPipeline());
+        // wait till jobs are scanned
+        Thread.sleep(200);
 
         List<JobSummary> list = getJetClientInstanceImpl(client).getJobSummaryList();
         assertEquals(1, list.size());
```
Comment (frant-hartm) [inline hazelcast/src/test/java/com/hazelcast/jet/impl/JobSummaryTest.java:137]: This will be flaky when we get overloaded Jenkins (which we do sometimes). Better to put the assertion into `assertTrueEventually`.

**Review by frant-hartm — APPROVED** [review]
Apart from the failing tests, which we should fix, it looks fine. Thanks @TomaszGaweda for pushing this through.

Plus two minor suggestions.

**Comment by krzysztofslusarski** [comment]
Please, do not merge the PR before I finish benchmarks. The first run is ending in 15 minutes, next round will finish tomorrow.

**Comment by krzysztofslusarski** [comment]
First round of latency tests:
image
image
image
image
image
image
image
image
image
image
image

**Comment by krzysztofslusarski** [comment]
Second round:
image
image
image
image
image
image
image
image
image
image
image

File: hazelcast/src/test/java/com/hazelcast/jet/impl/JobSummaryTest.java (hunk 30 above)
Comment (TomaszGaweda) [reply hazelcast/src/test/java/com/hazelcast/jet/impl/JobSummaryTest.java]: Done in d9e64de72ad5a2a2d17c33c976eb9876f41dbb50

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
Can I not hit another flaky for once? :|

**Comment by frant-hartm** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-nightly-tests

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by frant-hartm** [comment]
run-lab-run

**Comment by frant-hartm** [comment]
The `JobLifecycleMetricsTest` is run with `HazelcastParallelClassRunner`, but uses the `TestProcessors` which should be only used with serial runner. The parallel runner can explain the failure, but I haven't managed to reproduce it.

I have reviewed all the tests using the `TestProcessors` and sent a separate PR because the issue is on master as well. #21976

**Comment by frant-hartm** [comment]
run-lab-run

**Comment by frant-hartm** [comment]
run-ee-compile

**Comment by frant-hartm** [comment]
run-lts-compilers
