### PR TITLE
ClientMultiMapLockTest fixed

### LINKED ISSUE #6914: ClientMultiMapLockTest.testLockTTLExpired_whenLockedBySelf
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.hazelcast.client.multimap.ClientMultiMapLockTest.testLockTTLExpired_whenLockedBySelf(ClientMultiMapLockTest.java:328)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast-client-legacy/740/testReport/junit/com.hazelcast.client.multimap/ClientMultiMapLockTest/testLockTTLExpired_whenLockedBySelf/

### PR DESCRIPTION
**Pull request by muratayan**
fixes #6914

### CODE REVIEW

**Comment by sancar** [comment]
There are two classes with name ClientMultiMapLockTest. Old and new client. Don't forget the other one.

File: hazelcast-client-legacy/src/test/java/com/hazelcast/client/multimap/ClientMultiMapLockTest.java [hunk 1]
```diff
@@ -324,8 +324,13 @@ public void testLockTTLExpired_whenLockedBySelf() throws Exception {
...
-        sleepSeconds(2);
-        assertFalse(mm.isLocked(key));
+
+        assertTrueEventually(new AssertTask() {
+            @Override
+            public void run() throws Exception {
+                assertFalse(mm.isLocked(key));
+            }
+        });
     }
```
Comment (cangencer) [inline hazelcast-client-legacy/src/test/java/com/hazelcast/client/multimap/ClientMultiMapLockTest.java]: the previous test testLockTTLExpired() can have the same problem, is it possible to change that too?

**Comment by cangencer** [comment]
:+1:

**Comment by sancar** [comment]
:+1:

File: hazelcast-client-legacy/src/test/java/com/hazelcast/client/multimap/ClientMultiMapLockTest.java [hunk 2]
```diff
@@ -324,8 +328,13 @@ public void testLockTTLExpired_whenLockedBySelf() throws Exception {
 
         mm.lock(key);
         mm.lock(key, 1, TimeUnit.SECONDS);
-        sleepSeconds(2);
-        assertFalse(mm.isLocked(key));
+
+        assertTrueEventually(new AssertTask() {
```
Comment (pveentjer) [inline hazelcast-client-legacy/src/test/java/com/hazelcast/client/multimap/ClientMultiMapLockTest.java]: I would introduce a method 'assertIsUnlockedEventually to prevent copy/paste. Apart from that it looks like good test improvements.
