### PR TITLE
Fix throttling interval calculation for SQL [HZ-1413]

### LINKED ISSUE #21983: Incorrect assignment of watermark throttling interval [HZ-1413]
We assign the allowed lag time to watermark throttling interval, which is nonsense. In Pipeline API we assign the GCD of all the window sizes in the pipeline, or 100ms otherwise. We should do something similar in SQL.

https://github.com/hazelcast/hazelcast/blob/7b0b3b67500f5d5500fc4ab3b63041c497901f97/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/WatermarkRules.java#L110

### PR DESCRIPTION
**Pull request by Fly-Style**
Fixes #21983

### CODE REVIEW

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+                for (RelNode child : node.getInputs()) {
+                    visit0(child, sw);
+                }
+            } else if (node instanceof SlidingWindowAggregatePhysicalRel) {
+                SlidingWindowAggregatePhysicalRel slidingWindow = (SlidingWindowAggregatePhysicalRel) node;
+                long windowSize = slidingWindow.windowPolicyProvider().apply(eec).windowSize();
+                gcd = gcd >= 0L ? Util.gcd(gcd, windowSize) : windowSize;
+
+                visit0(slidingWindow.getInput(), slidingWindow);
+            } else if (node instanceof SlidingWindow) {
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java:88]: We don't need any watermarks for `SlidingWindow`, it's just mapping, not a streaming aggregation.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+            visit0(node, null);
+        }
+
+        private void visit0(RelNode node, @Nullable RelNode sw) {
+            if (node instanceof ShouldNotExecuteRel) {
+                gcd = 0L;
+                return;
+            }
+
+            if (node instanceof BiRel || node instanceof Union) {
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java:77]: We don't need to separately handle `BiRel` or `Union` or `FullScan`. We need to descend to children for all nodes, including to inputs of `SlidingWindowAggregate`.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+        GCDCalculatorVisitor(ExpressionEvalContext eec) {
+            this.eec = eec;
+        }
+
+        @Override
+        public void visit(RelNode node, int ordinal, @Nullable RelNode parent) {
+            visit0(node, null);
+        }
+
+        private void visit0(RelNode node, @Nullable RelNode sw) {
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java:71]: We must also handle stream-to-stream joins, which also need watermarks. For those we can use some hard-coded value, e.g. 100ms, and GCD with that.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+    private final GCDCalculatorVisitor visitor;
+    private final SlidingWindowDetector swDetector;
+
+    public WindowSizeGCDCalculator(ExpressionEvalContext eec) {
+        this.visitor = new GCDCalculatorVisitor(eec);
+        this.swDetector = new SlidingWindowDetector();
+    }
+
+    public void calculate(PhysicalRel rel) {
+        if (shouldRun(rel)) {
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java:44]: We don't need the `shouldRun` method after we fix the traversal in the normal visitor I think.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+            visitor.go(rel);
+        }
+    }
+
+    public long get() {
+        return visitor.gcd > 0 ? visitor.gcd : DEFAULT_THROTTLING_FRAME_SIZE;
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGCDCalculator.java:50]: We should max the GCD at 100ms for large window sizes. This is good for observing the progression of event time in metrics. 10 WMs per second are negligible.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/WatermarkLogicalRel.java [hunk 6]
```diff
@@ -61,7 +57,6 @@ public int watermarkedColumnIndex() {
     @Override
     public RelWriter explainTerms(RelWriter pw) {
         return super.explainTerms(pw)
-                .item("eventTimePolicyProvider", eventTimePolicyProvider)
```
[the remark this answers is not in the document]
Comment (Fly-Style) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/WatermarkLogicalRel.java:64]: We shouldn't. That rel shoudn't never be printed, acutally. if it is printed - we have buggy surprise.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+        private void visit0(RelNode node) {
+            if (node instanceof SlidingWindowAggregatePhysicalRel) {
+                SlidingWindowAggregatePhysicalRel slidingWindow = (SlidingWindowAggregatePhysicalRel) node;
+                long windowSize = slidingWindow.windowPolicyProvider().apply(eec).windowSize();
+                gcd = gcd > 0L ? Util.gcd(gcd, windowSize) : windowSize;
+            } else if (node instanceof StreamToStreamJoinPhysicalRel) {
+                StreamToStreamJoinPhysicalRel s2sJoin = (StreamToStreamJoinPhysicalRel) node;
+                long windowSize = s2sJoin.minWindowSize();
+                if (windowSize == 0L) {
+                    windowSize = 1L; // minimum available watermark interval is 1 ms.
```
Comment (krzysztofslusarski) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java:68]: [minor] so maybe ```1L``` should be a constant with proper name?

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+        @Override
+        public void visit(RelNode node, int ordinal, @Nullable RelNode parent) {
+            visit0(node);
+        }
+
+        private void visit0(RelNode node) {
+            if (node instanceof SlidingWindowAggregatePhysicalRel) {
+                SlidingWindowAggregatePhysicalRel slidingWindow = (SlidingWindowAggregatePhysicalRel) node;
+                long windowSize = slidingWindow.windowPolicyProvider().apply(eec).windowSize();
+                gcd = gcd > 0L ? Util.gcd(gcd, windowSize) : windowSize;
```
Comment (krzysztofslusarski) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java:63]: [minor] static import of ```gcd```?

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/CreateDagVisitor.java [hunk 9]
```diff
@@ -106,6 +107,7 @@ public class CreateDagVisitor {
     private final Address localMemberAddress;
     private final QueryParameterMetadata parameterMetadata;
     private final WatermarkKeysAssigner watermarkKeysAssigner;
+    private final WindowSizeGcdCalculator windowSizeGCDCalculator;
```
Comment (krzysztofslusarski) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/CreateDagVisitor.java:110]: Maybe we should be consistent with letter capitalization? Either ```gcd```/```Gcd``` or ```GCD````.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java (hunk 7 above)
Comment (Fly-Style) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java:68]: 1 was never considered as magic number, so, I guess, its okay. WDYT?

Comment (krzysztofslusarski) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java:68]: You just paste a comment ```// minimum available watermark interval is 1 ms.``` for explanation, IMO it would be better to remove comment and add proper name to the constant.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/CreateDagVisitor.java (hunk 9 above)
Comment (Fly-Style) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/CreateDagVisitor.java:110]: Leftover after renaming, thanks.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java (hunk 8 above)
Comment (krzysztofslusarski) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java:63]: Sure :+1:

**Review by burakgok — CHANGES_REQUESTED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+            } else if (node instanceof StreamToStreamJoinPhysicalRel) {
+                StreamToStreamJoinPhysicalRel s2sJoin = (StreamToStreamJoinPhysicalRel) node;
+                long windowSize = s2sJoin.minWindowSize();
+                if (windowSize == 0L) {
+                    windowSize = MINIMUM_WATERMARK_INTERVAL;
+                }
+                // we don't want to overflow input events buffers, that’s why gcd is limited with default frame size.
+                gcd = gcd > 0L ? Util.gcd(gcd, windowSize) : Util.gcd(DEFAULT_THROTTLING_FRAME_SIZE, windowSize);
```
[the remark this answers is not in the document]
Comment (Fly-Style) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/WindowSizeGcdCalculator.java:72]: Good catch, thanks

**Review by burakgok — APPROVED** [review]

**Review by krzysztofslusarski — APPROVED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/WatermarkLogicalRel.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/logical/WatermarkLogicalRel.java:64]: It could appear while debugging

**Comment by Fly-Style** [comment]
run-lab-run

**Comment by krzysztofslusarski** [comment]
run-lab-run

**Comment by Fly-Style** [comment]
run-lab-run

**Review by viliam-durina — APPROVED** [review]

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by viliam-durina** [comment]
run-lts-compilers
