### PR TITLE
Fix reconnect flood when members separated by proxy

### LINKED ISSUE #18320: Continuous reconnection when Hazelcast placed behind a proxy
When a member is disconnected from the cluster, the alive cluster members still try to reconnect if the dying member connection is not closed explicitly. This is done [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerContext.java#L182) by checking if the disconnection cause is `null` or not.

However, in some cases, the connection is explicitly closed with a cause (such as `Connection reset by peer` or `Remote socket closed!`). Moreover, a new connection can still be established if the member is placed behind a proxy. This scenario might end up with opening & closing connections continuously. 

A similar use case happens in Hazelcast cluster setup with Istio Service Mesh. Just follow the embedded scenario [in this guide](https://guides.hazelcast.org/istio/) and delete a pod to reproduce the issue. The logs below are produced in this setup:

```
2021-03-01 15:11:27.434  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=7, /172.17.0.6:34111->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=MEMBER] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.442  INFO 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=8, /127.0.0.1:5701->/127.0.0.1:54516, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=MEMBER] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.449  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.480  WARN 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=9, /172.17.0.6:44813->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=9, /172.17.0.6:44813->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-2

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.487  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.492  WARN 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=10, /172.17.0.6:41725->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=10, /172.17.0.6:41725->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-0

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.493  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.498  WARN 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=11, /172.17.0.6:52527->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=11, /172.17.0.6:52527->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-1

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.499  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.505  WARN 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=12, /172.17.0.6:56057->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=12, /172.17.0.6:56057->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-2

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.506  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.510  WARN 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=13, /172.17.0.6:38717->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=13, /172.17.0.6:38717->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-0

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.513  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.547  WARN 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=14, /172.17.0.6:43179->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Exception in Connection[id=14, /172.17.0.6:43179->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=true, connectionType=NONE], thread=hz.stupefied_visvesvaraya.IO.thread-in-1

java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.8.0_275]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:119) ~[hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:382) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:367) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:293) [hazelcast-all-4.0.2.jar:4.0.2]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:248) [hazelcast-all-4.0.2.jar:4.0.2]

2021-03-01 15:11:27.557  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.564  INFO 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=15, /172.17.0.6:34923->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.568  INFO 1 --- [cached.thread-1] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.574  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=16, /172.17.0.6:44791->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.583  INFO 1 --- [cached.thread-6] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.590  INFO 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=17, /172.17.0.6:45355->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.590  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.594  INFO 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=18, /172.17.0.6:34205->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.595  INFO 1 --- [cached.thread-2] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.598  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=19, /172.17.0.6:55751->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.599  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.613  INFO 1 --- [.IO.thread-in-1] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=20, /172.17.0.6:38683->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.614  INFO 1 --- [cached.thread-6] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.616  INFO 1 --- [.IO.thread-in-2] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=21, /172.17.0.6:53979->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
2021-03-01 15:11:27.617  INFO 1 --- [cached.thread-3] c.h.internal.nio.tcp.TcpIpConnector      : [172.17.0.6]:5701 [dev] [4.0.2] Connecting to /172.17.0.7:5701, timeout: 10000, bind-any: true
2021-03-01 15:11:27.619  INFO 1 --- [.IO.thread-in-0] c.h.internal.nio.tcp.TcpIpConnection     : [172.17.0.6]:5701 [dev] [4.0.2] Connection[id=22, /172.17.0.6:54381->/172.17.0.7:5701, qualifier=null, endpoint=[172.17.0.7]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
```

After this moment, more than 5400 connections opened & closed in a few minutes.

### PR DESCRIPTION
**Pull request by jbartok**
Fixes #18320

The root cause of this problem seems to be that, due to the proxy present, not being able to connect from one member to another doesn't behave as expected.

The expected behaviour is that a connection attempt is made, it fails, another one is made, it fails and after a certain number of attempts we give up and behave accordingly.

What happens here instead is that a connection attempt is made, it succeeds connecting to the proxy, the proxy tries to connect to the other side, fails, drops the incoming connection. So instead of an "attempt-fail, attempt-fail, ..." sequence of events we get "attempt-succeed-drop, attempt-succeed-drop, ..." sequence and that's not being handled correctly by the current code.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java [hunk 1]
```diff
@@ -55,11 +55,12 @@ synchronized void onError(Throwable cause) {
         }
     }
 
-    synchronized void reset() {
+    synchronized TcpServerConnectionErrorHandler reset() {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java:58]: I prefer the old style `void reset()` as it is more consistent with other `reset` usages around the codebase, but that's just me

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java [hunk 2]
```diff
@@ -175,28 +255,26 @@ public void onConnectionClose(TcpServerConnection connection, Throwable cause, b
...
+                        }
                         // not using removeIf due to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8078645
-                        Iterator<TcpServerConnection> connections = plane.connectionMap.values().iterator();
-                        while (connections.hasNext()) {
-                            TcpServerConnection cxn = connections.next();
-                            if (cxn.getConnectionId() == connection.getConnectionId()) {
-                                connections.remove();
-                                removed = true;
-                            }
+                        if (p.removeConnectionsWithId(connection.getConnectionId())) {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java:275]: The comment in above line should be moved inside `removeConnectionsWithId` implementation, because now it is out of context.

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java [hunk 3]
```diff
@@ -113,14 +119,88 @@ void refreshNetworkStats() {
...
+            connectionMap.put(address, connection);
+        }
+
+        void putConnectionIfAbsent(Address address, TcpServerConnection connection) {
+            connectionMap.putIfAbsent(address, connection);
+        }
+
+        void removeConnection(TcpServerConnection connection) {
+            removeConnectionInProgress(connection.getRemoteAddress());
+            connectionMap.entrySet().removeIf(entry -> entry.getValue().equals(connection));
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java:146]: `removeIf` implementation is affected by https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8078645 which is not fixed in any JDK 8 release as far as I can tell. Best to follow an approach similar to `removeConnectionsWithId`.

File: hazelcast/src/test/java/com/hazelcast/cluster/TcpIpMemberConnectionLossTest.java [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+
+        HazelcastInstance h1 = Hazelcast.newHazelcastInstance(config);
+        HazelcastInstance h2 = Hazelcast.newHazelcastInstance(config);
+        assertClusterSize(2, h1, h2);
+
+        InetSocketAddress address = Accessors.getNodeEngineImpl(h1).getThisAddress().getInetSocketAddress();
+        RejectionProxy rejectionProxy = new RejectionProxy(address.getHostName(), address.getPort());
+        try {
+            //when a member disappears
+            h1.shutdown();
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/cluster/TcpIpMemberConnectionLossTest.java:82]: `shutdown()` is graceful ie notifies master, ensures migrations are done then closes connections and shuts down. I think you may want to use `h1.getLifecycleService().terminate();` here (and in previous test) instead.

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java [hunk 5]
```diff
@@ -113,14 +119,88 @@ void refreshNetworkStats() {
...
+        }
+
+        public Set<Address> getAddresses(TcpServerConnection connection) {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java:149]: method seems unused, leftover?

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java (hunk 1 above)
Comment (jbartok) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java:58]: I'll revert. I had some plans with that reset, which then didn't materialize, but still, I left it there.

Comment (jbartok) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java:58]: Usually I'm all for consistency, but in this case I would say that better not violate the single responsibility principle. Cleaner this way.

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java (hunk 5 above)
Comment (jbartok) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java:149]: Ahh... Some of these refactoring are from the hostname related branch I'm also working on, because I accidentaly started working on this on that branch, then moved it over to master. It's used there, I'll remove it here.

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java (hunk 1 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java:58]: I prefer it returning `void` too. How do we violate the SRP here? And I don't see the return value being actually used.

File: hazelcast/src/test/java/com/hazelcast/cluster/TcpIpMemberConnectionLossTest.java [hunk 6]
```diff
@@ -0,0 +1,155 @@
...
+        RejectionProxy rejectionProxy = new RejectionProxy(address.getHostName(), address.getPort());
+        try {
+            //when a member disappears
+            h1.getLifecycleService().terminate();
+            //and connections to it don't succeed (they can be established, but immediately drop)
+            //(for example a TCP proxy might do this)
+            rejectionProxy.start();
+
+            //then it eventually gets dropped from the cluster
+            assertTrueEventually(() -> assertClusterSize(1, h2));
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/cluster/TcpIpMemberConnectionLossTest.java:88]: Kudos for figuring out a way to test this issue with the `RejectionProxy`. One issue is that the test doesn't fail with current `master` behaviour, because after 60 seconds the heartbeat timeout kicks in and removes the gone member -> assertion passes. So in order to make sure this fails in case of regression, I would prolong heartbeat timeout and add an explicit, lower timeout to `assertTrueEventually` eg:
```
config.setProperty(MAX_NO_HEARTBEAT_SECONDS.getName(), "120");
...
assertTrueEventually(() -> assertClusterSize(1, h2), 45);
```

Comment (jbartok) [reply hazelcast/src/test/java/com/hazelcast/cluster/TcpIpMemberConnectionLossTest.java:88]: Ok, will do.

**Comment by jbartok** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java (hunk 1 above)
Comment (jbartok) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java:58]: image

This getter should get the error handler and that's it, not have a reset as a side effect inside.

Comment (jbartok) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionErrorHandler.java:58]: The return value is just for the ability to chain calls together.

**Review by kwart — APPROVED** [review]
