### PR TITLE
fix #4533

### LINKED ISSUE #4533: hazelcast.xml variable replacement only works at the front of an xml attribute string
For example, I would like to do:
```xml
<hazelcast>
  <import resource="hazelcast/group-${env}-config.xml"/>
  ...
```
But this tries to import a file called "qa-config.xml" instead of "hazelcast/group-qa-config.xml"

Here is a unit test that demonstrates the same problem.  I am on version 3.4
```java
    @Test
    public void testXmlVariableReplacement() throws Exception {

        String xml = "<hazelcast>\n" +
                "    <properties>\n" +
                "        <property name=\"${env}-with-suffix\">local-with-suffix</property>\n" +
                "        <property name=\"with-prefix-${env}\">with-prefix-local</property>\n" +
                "    </properties>\n" +
                "</hazelcast>";

        // Simulate setenv.sh service configuration
        System.setProperty("env", "local");

        InputStream is = IOUtils.toInputStream(xml, "UTF-8");
        Config config = new XmlConfigBuilder(is).build();
        Properties properties = config.getProperties();
        
        // ok
        assertEquals(properties.getProperty("local-with-suffix"), "local-with-suffix");

        // this fails because "with-prefix-${env}" resolved as "local"
        assertEquals(properties.getProperty("with-prefix-local"), "with-prefix-local");
    }
```

### PR DESCRIPTION
**Pull request by bilalyasar**
only changed XmlConfigPreProcessor.java#replaceVariables.
1) node.value copied to stringBuilder.
2) all replacements are made on stringBuilder
3) finally string builder value is copied to node.value

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java [hunk 1]
```diff
@@ -500,6 +501,54 @@ public void testXmlDeniesDuplicateMemberAttributesConfig() throws Exception {
...
+    public void testXmlVariableReplacementAsSubstring() throws Exception {
+
+        String xml = "<hazelcast>\n" +
+                "    <properties>\n" +
+                "        <property name=\"${env}-with-suffix\">local-with-suffix</property>\n" +
+                "        <property name=\"with-prefix-${env}\">with-prefix-local</property>\n" +
+                "    </properties>\n" +
+                "</hazelcast>";
+
+        System.setProperty("env", "local");
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: Can you try it without setting a sytem property? The same goes for the other test. The replacement mechanism should work using normal properties as well.

File: hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java [hunk 2]
```diff
@@ -500,6 +501,54 @@ public void testXmlDeniesDuplicateMemberAttributesConfig() throws Exception {
...
+        String xml = "<hazelcast>\n" +
+                "    <import resource=\"file://" + "${file}" + "\"/>\n" +
+                "</hazelcast>";
+
+        ByteArrayInputStream bis = new ByteArrayInputStream(xml.getBytes());
+        System.setProperty("file", file.getAbsolutePath());
+        XmlConfigBuilder configBuilder = new XmlConfigBuilder(bis);
+        Config config = configBuilder.build();
+        JoinConfig join = config.getNetworkConfig().getJoin();
+        assertFalse(join.getMulticastConfig().isEnabled());
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: Personally I would not use the network override to detect if a file is correctly imported. I needed to look at the config to determine what the defaults were. Personally I would go for adding a property in the property section. 

```
<properties>
   <property name="foo">bar</name>
</properties>
```

And then check if the property 'foo' has value 'bar'.

**Comment by pveentjer** [comment]
Minor review comments. Apart from that it looks good to me.

**Comment by bilalyasar** [comment]
@pveentjer, very thanks Peter for your comments, updated.

File: hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java [hunk 3]
```diff
@@ -500,6 +501,56 @@ public void testXmlDeniesDuplicateMemberAttributesConfig() throws Exception {
...
+        configBuilder.setProperties(properties);
+        Config config = configBuilder.build();
+
+        assertEquals(config.getProperty("local-with-suffix"), "local-with-suffix");
+        assertEquals(config.getProperty("with-prefix-local"), "with-prefix-local");
+    }
+
+    @Test
+    public void testXmlImportWithVariableReplacementAsSubstring() throws Exception {
+        Properties properties = new Properties();
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: A tip; only declare your variable at the moment you really need it. Now it is spread over the method and makes it more difficult to follow. You do the same thing with the previous test although not that bad.

Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: Also there is some copy paste programming to make a Config. Please pull it out in a method to reduce copy paste + increase readiblity. E.g.

```
 @Test
    public void testXmlVariableReplacementAsSubstring() throws Exception {
        String xml = "<hazelcast>\n" +
                "    <properties>\n" +
                "        <property name=\"${env}-with-suffix\">local-with-suffix</property>\n" +
                "        <property name=\"with-prefix-${env}\">with-prefix-local</property>\n" +
                "    </properties>\n" +
                "</hazelcast>";

 	Properties properties = new Properties();
        properties.setProperty("env", "local");

	Config config = build(xml, properties);

        assertEquals(config.getProperty("local-with-suffix"), "local-with-suffix");
        assertEquals(config.getProperty("with-prefix-local"), "with-prefix-local");
    }

public Config build(String xml, Properties props){
        ByteArrayInputStream bis = new ByteArrayInputStream(xml.getBytes());
        XmlConfigBuilder configBuilder = new XmlConfigBuilder(bis);
        configBuilder.setProperties(properties);
        return configBuilder.build();
}
```

Please consider cleaning up the rest of the methods to make use of the same build method.

Comment (bilalyasar) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: okey, i will cleanup whole methods in this test class according to your suggestions.. thanks

Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: You could even consider something like this (building on top of a varargs of string):

```
    Config config = build(xml, properties, "env", "local");
```

Much cleaner than that you can't get it. Saves you another few non interesting lines from your test.

```
  public void testXmlVariableReplacementAsSubstring() throws Exception {
        String xml = "<hazelcast>\n" +
                "    <properties>\n" +
                "        <property name=\"${env}-with-suffix\">local-with-suffix</property>\n" +
                "        <property name=\"with-prefix-${env}\">with-prefix-local</property>\n" +
                "    </properties>\n" +
                "</hazelcast>";

      Config config = build(xml, "env", "local");

        assertEquals(config.getProperty("local-with-suffix"), "local-with-suffix");
        assertEquals(config.getProperty("with-prefix-local"), "with-prefix-local");
    }
```

File: hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java [hunk 4]
```diff
@@ -500,6 +501,56 @@ public void testXmlDeniesDuplicateMemberAttributesConfig() throws Exception {
...
+                "    <import resource=\"file://" + "${file}" + "\"/>\n" +
+                "</hazelcast>";
+
+        ByteArrayInputStream bis = new ByteArrayInputStream(xml.getBytes());
+        properties.setProperty("file", file.getAbsolutePath());
+        XmlConfigBuilder configBuilder = new XmlConfigBuilder(bis);
+        configBuilder.setProperties(properties);
+        Config config = configBuilder.build();
+        JoinConfig join = config.getNetworkConfig().getJoin();
+        assertFalse(join.getMulticastConfig().isEnabled());
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: I see you are still relying on network config to determine of the substitution has worked. I really would use the same approach as you do in test testXmlVariableReplacementAsSubstring

File: hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java (hunk 3 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: Thanks.

Please keep in mind: readability for tests is extremely important because they are an executable specification if your system. If they are more difficult to read than needs to be, the loose their value because people have a hard time figuring out the purpose of a test.

So for normal code readability is important, but for tests imho even more so.

Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: +1

**Comment by bilalyasar** [comment]
@pveentjer, updated.

File: hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java [hunk 5]
```diff
@@ -213,10 +186,7 @@ public void testImportEmptyResourceThrowsException() throws Exception {
         String xml = "<hazelcast>\n" +
                 "    <import resource=\"\"/>\n" +
                 "</hazelcast>";
-
-        ByteArrayInputStream bis = new ByteArrayInputStream(xml.getBytes());
-        XmlConfigBuilder configBuilder = new XmlConfigBuilder(bis);
-        configBuilder.build();
+        buildConfig(xml, null);
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/config/XMLConfigPreProcessorTest.java]: I'm not going to be very problematic about this; but normally I would create an additional buildConfig method which doesn't need a null. And perhaps it just forwards to buildConfig(xml, null)... but at least you don't see it in the code.

You don't need to change it, but passing in null values to an argument always gives me an strange feeling + decreases readability of the test because the reader is going to think.. what is going on here! And he is getting confused..

**Comment by pveentjer** [comment]
Looks good to me. @gurbuzali can you also have a look?
