### PR TITLE
Local statistics latency resolution is not enough for low latencies

### LINKED ISSUE #10025: ClientMapBasicTest.testMapStatistics_withClientOperations
```
java.lang.AssertionError: get latency
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.client.map.ClientMapBasicTest.testMapStatistics_withClientOperations(ClientMapBasicTest.java:1192)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-OracleJDK1.6-freestyle/32/testReport/junit/com.hazelcast.client.map/ClientMapBasicTest/testMapStatistics_withClientOperations/

### LINKED ISSUE #10938: Statistics getTotalGetLatency, getTotalRemoveLatency, getTotalPutLatency works incorrectly
Local statistics uses milliseconds for get/put/remove latencies. It is very usual for latencies to be around microseconds, hence the values may become 0 very easily. Especially the accumulative statistics such as totalGetLatencies and such, it does not make sense to stay at 0 even though there are millions of gets each below millisecond latency.

E.g. Our get latency for a single get is usually in microseconds around 100-200usecs. If you do 1 million get, then we normally expect the latency to be 1 million * 200 usec=200 sec. But since latency for each request is less than a millisecond, it is recorded as to be zero and the total becomes zero.

### PR DESCRIPTION
**Pull request by ihsandemir**
Local statistics uses milliseconds for get/put/remove latencies. It is very usual for latencies to be around microseconds, hence the values may become 0 very easily. Especially the accumulative statistics such as totalGetLatencies and such, it does not make sense to stay at 0 even though there are millions of gets each below millisecond latency.

Changed the stats impl. so that the latencies are now kept at microseconds resolution. The json contract still uses milliseconds resolution.

related to #10025

fixes #10938

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java [hunk 1]
```diff
@@ -36,17 +38,17 @@ protected AbstractMapPutMessageTask(ClientMessage clientMessage, Node node, Conn
...
     @Override
     protected void beforeProcess() {
-        startTime = System.currentTimeMillis();
+        startTime = System.nanoTime();
     }
 
     @Override
     protected void beforeResponse() {
-        final long latency = System.currentTimeMillis() - startTime;
+        final long latency = System.nanoTime() - startTime;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: To prevent confusion; I always add the unit of time to to the name of the variable. So latencyNanos. Dealing with unit mismatch is a PITA.

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java [hunk 2]
```diff
@@ -36,17 +38,17 @@ protected AbstractMapPutMessageTask(ClientMessage clientMessage, Node node, Conn
...
         final MapService mapService = getService(MapService.SERVICE_NAME);
         MapContainer mapContainer = mapService.getMapServiceContext().getMapContainer(getDistributedObjectName());
         if (mapContainer.getMapConfig().isStatisticsEnabled()) {
             mapService.getMapServiceContext().getLocalMapStatsProvider().getLocalMapStatsImpl(getDistributedObjectName())
-                    .incrementPuts(latency);
+                    .incrementPuts(NANOSECONDS.toMicros(latency));
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: I would rename this method to 'incrementPutLatencyNanos'.

File: hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java [hunk 3]
```diff
@@ -378,9 +388,12 @@ public String toString() {
                 + ", getCount=" + getCount
                 + ", putCount=" + putCount
                 + ", removeCount=" + removeCount
-                + ", totalGetLatencies=" + totalGetLatencies
-                + ", totalPutLatencies=" + totalPutLatencies
-                + ", totalRemoveLatencies=" + totalRemoveLatencies
+                + ", totalGetLatencies=" + totalGetLatencies + " microseconds"
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java]: Could this break compatibility (the addition of microseconds to the string) ??

Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java]: I someone relies on this for automatic parsing, it will break anyway, when the unit is changed (silently).

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java (hunk 2 above)
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: I would be `incrementPutLatencyMicros`, but I would prefer to rename the parameters, not the method name:
`incrementPuts(long latency)` -> `incrementPuts(long latencyMicros)`
`incrementPuts(long delta, long latency)` -> `incrementPuts(long delta, long latencyMicros)`
etc.

**Comment by ahmetmircik** [comment]
I think, only fixing the failed test should be sufficient. (For example: to test get latency a slow EP can be written) 

So far, local stats are returning in milliseconds in all previous versions but with this change, i believe, we will break that by returning nanoseconds instead without a strong reason to do it.

File: hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java (hunk 3 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java]: Reverting it.

**Comment by ihsandemir** [comment]
@ahmetmircik I am going to keep the interface the same, I will keep nanos internally but will return milliseconds at the API so that the contract is not changed.

Yes, I will also make the test succeed by introducing enough latency. That will also be part of this PR but also keeping nanos internally will make the total latencies more meaningful for the users. We will still return the total latencies as ms but totalling nanoseconds may now result in non-zero total latency as opposed to it being zero for the current implementation for get requests since each individual request latency is below millisecond. 

Would this solution be OK?

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java (hunk 2 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: Putting the unit into the method name looked more clear for its usage since the parameter is a primitive type of long.

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java (hunk 1 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: OK, changed.

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java (hunk 2 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: OK, changed.

File: hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java (hunk 3 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java]: OK, changed.

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java (hunk 2 above)
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: That's what we have our IDEs for :) There is a real-time preview including the parameter name, at least in IDEA (example):
idea-to-the-rescue

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java [hunk 4]
```diff
@@ -28,25 +28,25 @@
...
     @Override
     protected void beforeProcess() {
-        startTime = System.currentTimeMillis();
+        startTimeNanos = System.nanoTime();
     }
 
     @Override
     protected void beforeResponse() {
-        final long latency = System.currentTimeMillis() - startTime;
+        final long latency = System.nanoTime() - startTimeNanos;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: To prevent any form of unit conversion I would rename this to latencyNanos

File: hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java [hunk 5]
```diff
@@ -201,70 +205,70 @@ public long getPutOperationCount() {
...
-        TOTAL_REMOVE_LATENCIES.addAndGet(this, latency);
-        setMax(this, MAX_REMOVE_LATENCY, latency);
+        TOTAL_REMOVE_LATENCIES.addAndGet(this, latencyNanos);
+        setMax(this, MAX_REMOVE_LATENCY, latencyNanos);
     }
 
     @Override
     public long getTotalPutLatency() {
-        return totalPutLatencies;
+        return NANOSECONDS.toMillis(totalPutLatencies);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java]: I would also rename totalPutLatencies to totalPutLatencyNanos.

**Comment by pveentjer** [comment]
:+1: 

If you can have a look at the variable names so they include 'nanos' to prevent any future confusion

File: hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java (hunk 5 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/monitor/impl/LocalMapStatsImpl.java]: OK, changed.

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java (hunk 4 above)
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/AbstractMapPutMessageTask.java]: OK, changed.
