### PR TITLE
Fixes #7959 & #6056

### LINKED ISSUE #6056: MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading
```
java.lang.AssertionError: Cluster size is not correct expected:<2> but was:<3>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:662)
    at com.hazelcast.map.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading(MapLoaderFailoverTest.java:112)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/655/testReport/junit/com.hazelcast.map.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedAfterLoading/

### LINKED ISSUE #7959: MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoadingAndNoBackups
```
java.lang.AssertionError: expected:<10000> but was:<9840>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.mapstore.MapLoaderFailoverTest.testLoadsAll_whenInitialLoaderNodeRemovedWhileLoadingAndNoBackups(MapLoaderFailoverTest.java:164)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.6/com.hazelcast$hazelcast/881/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoadingAndNoBackups/

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/454/testReport/junit/com.hazelcast.map.impl.mapstore/MapLoaderFailoverTest/testLoadsAll_whenInitialLoaderNodeRemovedWhileLoadingAndNoBackups/

### PR DESCRIPTION
**Pull request by tombujok**
closes #7959 

How it is fixed: The startLoading call is deferred to the commitMigration call if the RecordStore is created during a Migration. Otherwise the startLoading call does not see a proper state of the partitionTable and it's needed to calculate the roles of the recordStore in the loading process.

closes #6056

How it is fixed: The problem with the current migration algorithm is that it may promote & migrate a record store. It means that there's not only a "local" promotion, but there's also a "remote" promotion, meaning that a recordStore with replicaIndex==1 may be migrated to other node with replicaIndex==0. In order not to trigger a load again the loadStatus has to be migrated too. Earlier it wasn't the cases since there was no promotion & migration - a promotion was always a "local" operation. Thus to fix it I had to send a migration flag whether the load has been finished or not. It's the preMigrationLoadedStatus

### CODE REVIEW

**Comment by tombujok** [comment]
run-lab-run

**Comment by tombujok** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java [hunk 1]
```diff
@@ -349,6 +349,11 @@
     void startLoading();
 
     /**
+     * Starts mapLoader
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java]: can elaborate this a bit? maybe some explanation, why is it needed, etc.

**Comment by jerrinot** [comment]
:+1: with a minor comment

File: hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java (hunk 1 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java]: I'll change it - it's a copy/paste javadoc

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/RecordStore.java]: Fixed.

**Comment by ahmetmircik** [comment]
Milestone for #6056 is 3.6.3, do you plan to send a backport?

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java [hunk 2]
```diff
@@ -439,4 +451,14 @@ public String toString() {
     public void onKeyLoad(ExecutionCallback<Boolean> callback) {
         loadFinished.andThen(callback, execService.getExecutor(MAP_LOAD_ALL_KEYS_EXECUTOR));
     }
+
+    public void promoteToLoadedOnMigration() {
+        state.next(State.LOADING);
+        state.next(State.LOADED);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java]: can't we do just `state.next(State.LOADED)`? Why do we need `state.next(State.LOADING)`?

File: hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java [hunk 3]
```diff
@@ -73,6 +73,12 @@
     protected final MapKeyLoader keyLoader;
     // loadingFutures are modified by partition threads and could be accessed by query threads
     protected final Collection<Future> loadingFutures = new ConcurrentLinkedQueue<Future>();
+    // record store may be created with or without triggering the load
+    // this flag guards that the loading on create is invoked not more than once should the record streo be migrated.
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java]: typo `record streo`?

**Comment by ahmetmircik** [comment]
Can you please put some small explanation (what is fixed? how is it fixed?) here https://github.com/hazelcast/hazelcast/pull/7992#issue-149773993?

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java (hunk 2 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java]: The state machine cannot skip states - it's like a graph with connections. I don't want to modify the graph for this particular case, since it may be a smell in different cases.

File: hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java (hunk 3 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java]: corrected, thx

**Comment by tombujok** [comment]
Sure, I've added two comment how the issues have been fixed.

**Comment by tombujok** [comment]
We will not backport this since it's related to the data-loss on migration PR that won't be backported either.

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java (hunk 2 above)
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java]: Ok. Maybe at least we can add your [statement](https://github.com/hazelcast/hazelcast/pull/7992#discussion_r61106721) to the `promoteToLoadedOnMigration ` method for the future reviewers? Because at first glance `state.next(State.LOADED)` seems enough.

**Comment by ahmetmircik** [comment]
👍 with minor comment

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java (hunk 2 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapKeyLoader.java]: Sure, added
