### PR TITLE
Fixes ClientInvocationFutureTests

### LINKED ISSUE #17099: ClientInvocationFutureTest test_applyEither
- Fails on `Hazelcast-4..maintenance-ZingJDK8`
- Fails on [Build #183 (Jun 16, 2020 10:56:24 PM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-4..maintenance-ZingJDK8/183/testReport/junit/com.hazelcast.client.impl.spi.impl/ClientInvocationFutureTest/test_applyEither/)
- Error
```
expected:<null> but was:<ClientMessage{connection=null, length=42, operation=null, isRetryable=false, correlationId=0, messageType=10201, isEvent=false, isfragmented=false}>
```
- Stacktrace
```
ava.lang.AssertionError: expected:<null> but was:<ClientMessage{connection=null, length=42, operation=null, isRetryable=false, correlationId=0, messageType=10201, isEvent=false, isfragmented=false}>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationFutureTest.test_applyEither(ClientInvocationFutureTest.java:295)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
- Possible commits
```
CP Client message tasks should not deserialize responses (detail / githubweb)
[BACKPORT] Fixes interoperability issues with CompletableFuture (#17048) (detail / githubweb)
```

kindly check.

### PR DESCRIPTION
**Pull request by vbekiaris**
Tests of *Either and *Both methods are guaranteed
to have the returned future completed with `null`
value.

Fixes #17099

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/client/impl/spi/impl/ClientInvocationFutureTest.java [hunk 1]
```diff
@@ -278,29 +277,25 @@ public void test_handle() throws Exception {
...
         verify(callIdSequence).forceNext();
-        verify(callIdSequence, times(2)).complete();
+        verify(callIdSequence, times(1)).complete();
     }
 
     @Test
     public void test_applyEither() throws Exception {
-        CompletableFuture nextStage = invocationFuture.applyToEither(newCompletedFuture(null),
-                (t) -> t);
-        invocationFuture.complete(response);
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/client/impl/spi/impl/ClientInvocationFutureTest.java:292]: Completing the `invocationFuture` is both unnecessary (because it is sufficient for one `CompletableFuture` to be completed for `*Either` methods to be executed) and using a value other than `null` may result in `(t) -> t` function to return that value as there is no guarantee which `CompletableFuture`'s completion value will be passed in the `Function`.
