### PR TITLE
fix to a regression caused by #7635.

### LINKED ISSUE #7527: CacheClientListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown
```
java.lang.AssertionError: Cache operations should not hang when sync listener is present!, failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:761)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:747)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_AfterAction(CacheListenerTest.java:331)
	at com.hazelcast.cache.CacheListenerTest.testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown(CacheListenerTest.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:88)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:82)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.lang.Thread.run(Thread.java:701)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK6/com.hazelcast$hazelcast-client/117/testReport/junit/com.hazelcast.client.cache/CacheClientListenerTest/testSyncListener_shouldNotHang_whenHazelcastInstanceShutdown/

### PR DESCRIPTION
**Pull request by sancar**
Invocations of dead connections were handling as soon as connection
is closed before #7635. With the change in #7635, the invocations
are started to handled by a separate thread periodically.
Since that thread is closed when client itself closes, there can
be some invocations left unhandled. This pr makes sure they are
handled in ClienInvocationService shutdown.

fixes #7527

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java [hunk 1]
```diff
@@ -169,7 +169,9 @@ public boolean isShutdown() {
     public void shutdown() {
         isShutdown = true;
         responseThread.interrupt();
-        callIdMap.clear();
+        CleanResourcesTask cleanResourcesTask = new CleanResourcesTask();
+        cleanResourcesTask.run();
```
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java]: In this call, there seems to be unnecessary wait logic: waitForPacketsProcessed

Can we just call ClientInvocationServiceSupport::cleanResources directly?

Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java]: 1) Since all connections are closed already at this point, waitForPacketsProcessed logic guaranteed to not run. 
2) We don't such a method to call directly.
3) Assert check is not for to check something and recover. Assert is just to state that it can not be not empty here. If it is , than it means a bug and we need to fix it.

**Comment by ihsandemir** [comment]
:+1:

**Comment by mustafaiman** [comment]
:+1:
