### PR TITLE
Fix Throwable.initCause when exception already has cause API-1387

### LINKED ISSUE #21414: IMap.get gets blocked forever when Cassandra NoNodeAvailableException is thrown from the MapStore [API-1387]
**Describe the bug**
The IMap.get() call will be blocked forever  when a `com.datastax.oss.driver.api.core.NoNodeAvailableException` is thrown from the MapStore.

**Setup:**
Hazelcast v5.1.1
Cassandra SDK v4.14.1
Client-server setup
Read through cache, Cassandra DB gets called on a cache miss.
 
**Test scenario: Read through cache, Cassandra server is down:**

We tested the scenario when the Cassandra datastore is down and the client tries to load an entry from the cache and there's a cache miss. It turned out that Hazelcast incorrectly handles the exception from Cassandra as it assumes that there will be always a cause property from the exception that comes from the data store in case of an issue. When the Cassandra cluster is down Hazelcast receives a `com.datastax.oss.driver.api.core.NoNodeAvailableException`, it tries to clone this exception and call the initCause on a Throwable that throws an exception as the cause cannot be null.

Exception thrown:

```
java.lang.RuntimeException: Exception creation failed 
	at com.hazelcast.internal.util.ExceptionUtil.cloneException(ExceptionUtil.java:250) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.ExceptionUtil.tryCreateExceptionWithMessageAndCause(ExceptionUtil.java:225) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:345) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.createException(ClientExceptionFactory.java:330) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.handleResponse(ClientResponseHandlerSupplier.java:164) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.process(ClientResponseHandlerSupplier.java:141) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier.access$300(ClientResponseHandlerSupplier.java:60) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:251) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.spi.impl.ClientResponseHandlerSupplier$DynamicResponseHandler.accept(ClientResponseHandlerSupplier.java:243) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.connection.tcp.TcpClientConnection.handleClientMessage(TcpClientConnection.java:245) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.handleMessage(ClientMessageDecoder.java:135) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.client.impl.protocol.util.ClientMessageDecoder.onRead(ClientMessageDecoder.java:89) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:136) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:383) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[hazelcast-5.1.1.jar:5.1.1]
Caused by: java.lang.IllegalStateException: Can't overwrite cause with a null
	at java.base/java.lang.Throwable.initCause(Throwable.java:462) ~[na:na]
	at com.hazelcast.internal.util.ExceptionUtil$ConstructorMethod$4.cloneWith(ExceptionUtil.java:314) ~[hazelcast-5.1.1.jar:5.1.1]
	at com.hazelcast.internal.util.ExceptionUtil.cloneException(ExceptionUtil.java:246) ~[hazelcast-5.1.1.jar:5.1.1]
	... 17 common frames omitted
Caused by: com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710) ~[na:na]
	at com.hazelcast.internal.util.ExceptionUtil$ConstructorMethod$4.cloneWith(ExceptionUtil.java:313) ~[hazelcast-5.1.1.jar:5.1.1]
	... 18 common frames omitted
```

Hazelcast's ExceptionUtil.java - tryCreateExceptionWithMessageAndCause():
```
        try {
            constructor = LOOKUP.findConstructor(exceptionClass, MT_INIT);
            T clone = (T) constructor.invokeWithArguments();
            clone.initCause(cause);
            return clone;
        } catch (ClassCastException | WrongMethodTypeException...)
```

Throwable.java:
```
    public synchronized Throwable initCause(Throwable cause) {
        if (this.cause != this)
            **throw new IllegalStateException("Can't overwrite cause with " +
                                            Objects.toString(cause, "a null"), this);**
        if (cause == this)
            throw new IllegalArgumentException("Self-causation not permitted", this);
        this.cause = cause;
        return this;
    }
``` 

**Current workaround:**
Catch the NoNodeAvailableException in the MapStore's load method and throw a different runtime exception.
    
**Expected behavior**
The `ExceptionUtil.cloneException()` should handle the scenario when an exception type is thrown without a cause property and should not block the client forever but fail fast.

**To Reproduce**

1. Create a MapStore like this
```
public class FooStore implements MapStore<String, String> {

    @Override
    public String load(String key) {
        throw new com.datastax.oss.driver.api.core.NoNodeAvailableException();
    }
```
2. Call a HazelcastClientProxy.get()

### PR DESCRIPTION
**Pull request by srknzl**
Some libraries may set cause even no cause is provided like this exception (its parents set cause to null by default): https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/api/core/NoNodeAvailableException.java

`Throwable.initCause()` check if cause is set before. Even if it's set to `null`, it will throw `IllegalStateException`. If that happens we ignore now.

Fixes #21414

Breaking changes (list specific methods/types/messages):
- None

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x ] Send backports/forwardports if fix needs to be applied to past/future releases
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java [hunk 1]
```diff
@@ -297,7 +297,12 @@ MethodType signature() {
             <T extends Throwable> T cloneWith(MethodHandle constructor, String message,
                                               @Nullable Throwable cause) throws Throwable {
                 T cloned = (T) constructor.invokeWithArguments(message);
-                cloned.initCause(cause);
+                try {
+                    cloned.initCause(cause);
+                } catch (IllegalStateException ignored) {
+                    // Cause can be already set by the exception. It can be set to null as well.
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java:303]: Not being able to tell the difference between if the cause is not set by the constructor or set to null is a bummer. I didn't like using exception handling for this scenario, but it seems like this is our only option.

File: hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java [hunk 2]
```diff
@@ -1104,10 +1104,55 @@ public void storeAll(Map<Integer, Integer> map) {
         assertEquals(1_500, map.size());
     }
 
+    // See https://github.com/hazelcast/hazelcast/issues/21414
+    @Test(timeout = 120000)
+    public void testBugFix_21414() {
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java:1109]: I believe it would be better to add the proper test to `ExceptionUtilTest`.

**Review by mdumandag — COMMENTED** [review]
The fix looks good to me, but we should definitely get a review from the core team, as this fix is more like a core team problem

File: hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java (hunk 2 above)
Comment (srknzl) [reply hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java:1109]: It may be more reasonable to do that. Do you think this test should stay?

File: hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java (hunk 1 above)
Comment (srknzl) [reply hazelcast/src/main/java/com/hazelcast/internal/util/ExceptionUtil.java:303]: me neither.

File: hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java (hunk 2 above)
Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java:1109]: I think we don't need to have it, the map store problem is just a by-product of something else

Comment (srknzl) [reply hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/MapStoreTest.java:1109]: moved the test to ExceptionUtilTest

**Review by mdumandag — APPROVED** [review]

**Review by vbekiaris — APPROVED** [review]
It's a pity we can't preserve cause information.
Thanks for the fix @srknzl

**Comment by srknzl** [comment]
@vbekiaris Thanks for the review. Should this issue be backported to older versions? If so, which versions?

**Comment by vbekiaris** [comment]
Yes, please backport to actively maintained ones (4.1.z and above)
