### PR TITLE
Shutdown client cluster thread when shutdown called explicitly

### LINKED ISSUE #10237: Impossible to stop Hazelcast Client service if it has never connected to the server.
Using service commons-daemon, in the stop() method.

Please help to me to understand how to force a shutdown of the connections and of the initialization.

After the shutdown of the service, this 2 threads are still running, no matter if you run shutdown, onShutdown, thread.interrupt(), thread.close(). 

       HazelcastInstanceFactory.terminateAll();
        hazelcasts.stream().map(instance -> (HazelcastClientInstanceImpl)instance).forEach(client -> {
            client.getConnectionManager().shutdown();
            for (ClientConnection connection : client.getConnectionManager().getActiveConnections()){
                connection.close("shutdown relay", new ShutdownChannelGroupException());
            }
            client.doShutdown();
        });
        hazelcasts.forEach(HazelcastInstance::shutdown);

Threads still up and running. 

```
2017-04-06 08:09:43,928 -  WARN -  - hz.Cluster.IO.thread-in-0 - com.hazelcast.client.connection.nio.ClientConnection - Cluster [CDDS Server] [3.8] ClientConnection{alive=false, connectionId=1, socketChannel=DefaultSocketChannelWrapper{socketChannel=java.nio.channels.SocketChannel[connected local=/172.31.1.8:57201 remote=/172.31.0.148:5701]}, remoteEndpoint=null, lastReadTime=2017-04-06 08:09:40.896, lastWriteTime=never, closedTime=2017-04-06 08:09:40.912, lastHeartbeatRequested=never, lastHeartbeatReceived=never, connected server version=null} lost. Reason: java.io.EOFException[Remote socket closed!]
2017-04-06 08:09:51,846 -  WARN -  - hazelcast-initialization-2-thread-1 - com.hazelcast.client.spi.impl.ClusterListenerSupport - Cluster [CDDS Server] [3.8] Unable to get alive cluster connection, try in 0 ms later, attempt 1 of 2147483647.
```

### PR DESCRIPTION
**Pull request by sancar**
Shutdown client cluster thread when shutdown called explicitly

When client cluster thread trying to connect to a cluster, it
was not checking if client is running correctly. It was quitting
only after `connection-attemp-limit` runs out.

fixes #10237

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java [hunk 1]
```diff
@@ -770,6 +770,7 @@ private void connectToClusterInternal() {
                 try {
                     Thread.sleep(remainingTime);
                 } catch (InterruptedException e) {
+                    Thread.currentThread().interrupt();
```
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: what is the reason for this?

Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: see https://github.com/hazelcast/hazelcast/issues/6219

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java [hunk 2]
```diff
@@ -744,17 +744,19 @@ public void connectToCluster() {
...
 
-            final Collection<InetSocketAddress> socketAddresses = getSocketAddresses();
+            Collection<InetSocketAddress> socketAddresses = getSocketAddresses();
             for (InetSocketAddress inetSocketAddress : socketAddresses) {
                 if (!client.getLifecycleService().isRunning()) {
                     if (logger.isFinestEnabled()) {
                         logger.finest("Giving up on retrying to connect to cluster since client is shutdown.");
                     }
-                    break;
+                    break mainLoop;
```
Comment (asimarslan) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: 😱
