### PR TITLE
IOBalancer: Change misleading logging message

### LINKED ISSUE #10840: IO-Balancer Max Events value looks wrong
```
2017-06-27T16:07:06,052 TRACE [IOBalancer] [XXX]:47501 [prod] [3.8.2] No imbalance has been detected. Max. events: *-9223372036854775808* Min events: 0.
```
Looks like a bitshift by one bit too much :) You might want to consider using Long.MAX_VALUE :)

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #10840
When each thread has at most 1 handler assigned then max value
is kept at its initial setting - Long.MIN_VALUE.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancer.java [hunk 1]
```diff
@@ -139,7 +139,12 @@ private void scheduleMigrationIfNeeded(LoadTracker loadTracker) {
             if (logger.isFinestEnabled()) {
                 long min = loadImbalance.minimumEvents;
                 long max = loadImbalance.maximumEvents;
-                logger.finest("No imbalance has been detected. Max. events: " + max + " Min events: " + min + ".");
+                if (max == Long.MIN_VALUE) {
+                    logger.finest("There is at most 1 handler associated with each thread. " +
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/internal/networking/nio/iobalancer/IOBalancer.java]: `+` needs to go to the next line
