### PR TITLE
Fix WM handling in AggregateSlidingWindowRule

### LINKED ISSUE #21920: Streaming aggregation gives incorrect results for non-executable query
Currently, the `AggregateSlidingWindowPhysicalRule` checks that the aggregation groups by any field that is watermarked. This isn't correct. It must check that the aggregation groups by the window bound.

The issue is visible in `SqlTumbleTest.test_nested*()` - the queries there group by `window_start_inner`, which is a normal field from the other `TUMBLE` call. They must group by `window_start` or `window_end`. In current shape, they must fail.

### PR DESCRIPTION
**Pull request by viliam-durina**
Fixes #21920

### CODE REVIEW

**Review by Fly-Style — APPROVED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/AggregateSlidingWindowPhysicalRule.java [hunk 1]
```diff
@@ -236,6 +238,11 @@ private static Integer findWatermarkedField(
         if (watermarkedFields == null) {
             return null;
         }
-        return watermarkedFields.findFirst(logicalAggregate.getGroupSet());
+        ImmutableBitSet windowBoundIndexes = ImmutableBitSet.builder()
+                .addAll(windowStartIndexes)
+                .addAll(windowEndIndexes)
+                .build()
+                .intersect(logicalAggregate.getGroupSet());
```
Comment (krzysztofslusarski) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/physical/AggregateSlidingWindowPhysicalRule.java:245]: From what I see the builder also has ```intersect``` method, that will save us creating some litter. The ```intersect``` in ```ImmutableBitSet```:
```java
  public ImmutableBitSet intersect(ImmutableBitSet that) {
    final Builder builder = rebuild();
    builder.intersect(that);
    return builder.build();
  }
```
It just creates a builder. Unfortunately the ```intersect``` in builder doesn't returns it's instance.

**Review by krzysztofslusarski — CHANGES_REQUESTED** [review]

**Review by krzysztofslusarski — APPROVED** [review]
