### PR TITLE
Workaround for unexpected Selector.select behavior

### LINKED ISSUE #7943: Too much cpu used when Hazelcast is idle V 3.6.2
As requested by @noctarius creating new ticket.
Am using 3.6.2 new release still taking high CUP usage.
Verified in java 1.7.0_75 and 1.8.0_77.
Tomcat 7.0.68 (java 1.7),Tomcat 8.0.30 (java 1.8).
OS Windows 7.
Use case - We are using apache shiro as security framework and hazelcast is beeing used to store user session in hazelcast map. We are observing high cpu when no user has logged in for around 3 hours.

[hazelcast.txt](https://github.com/hazelcast/hazelcast/files/215087/hazelcast.txt)

untitled1
untitled

### PR DESCRIPTION
**Pull request by vbekiaris**
This PR introduces a workaround for unexpected `Selector.select` behavior (fixes #7943).
Under unknown circumstances, `Selector.select(timeout)` may enter a state in which it unblocks immediately, without any of the conditions described in its javadoc having been in effect (no keys selected, not woken up, not interrupted and timeout did not pass). Detection is introduced in `NonBlockingIOThread` and `SocketAcceptorThread`, the workaround being to build a new `Selector`.

A new system property `hazelcast.io.selectorMode` is introduced. Possible values are `selectnow` (use `Selector.selectNow` experimental mode) and `selectwithfix` (use default select loop with selector rebuild on bug detection); any other value will default to using the standard select(timeout) loop.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 1]
```diff
@@ -56,43 +59,52 @@
...
     @Probe
     private final SwCounter completedTaskCount = newSwCounter();
+    // count number of times the selector was rebuilt (if selectWorkaround is enabled)
+    @Probe
+    private final SwCounter selectorRebuildCount = newSwCounter();
 
     private final ILogger logger;
 
-    private final Selector selector;
+    private volatile Selector selector;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: Does it need to be volatile? Afaik it isn't needed.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 2]
```diff
@@ -307,6 +346,29 @@ public final void shutdown() {
         interrupt();
     }
 
+    // this method is always invoked in this thread
+    // after we have blocked for selector.select in #runSelectLoopWithSelectorFix
+    private void rebuildSelector() {
+        selectorRebuildCount.inc();
+        Selector newSelector = NonBlockingIOThread.newSelector(logger);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: Can't the 'newSelector method be used?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 3]
```diff
@@ -307,6 +346,29 @@ public final void shutdown() {
...
+        Selector selector = this.selector;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: I would call this one 'oldSelector'.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader.java [hunk 4]
```diff
@@ -245,6 +245,20 @@ public String toString() {
         return connection + ".socketReader";
     }
 
+    @Override
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader.java]: Do we need this method at all? Why can't the AbstractHandler take care of this instead of adding more methods to the subclasses?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java (hunk 1 above)
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: `NonBlockingIOThread.getSelector()` is invoked from `AbstractHandler.getSelectionKey` and `AbstractHandler.onFailure`. Apart from the former's usage in `NonBlockingSocketReader.init`, I think all other cases in which the `selector` is obtained come from the IO thread itself, so assuming the case of `init` invocation is irrelevant, `volatile` could be removed. Can you confirm?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader.java (hunk 4 above)
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader.java]: Something like this for `AbstractHandler.reschedule`?
```java
    private void reschedule() {
        if (this instanceof Runnable) {
            ioThread.addTaskAndWakeup((Runnable) this);
        }
        else {
            ioThread.addTaskAndWakeup(new Runnable() {
                @Override
                public void run() {
                    try {
                        handle();
                    } catch (Exception e) {
                        onFailure(e);
                    }
                }
            });
        }
    }
```

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java [hunk 5]
```diff
@@ -39,9 +42,9 @@
     protected final TcpIpConnection connection;
     protected final TcpIpConnectionManager connectionManager;
     protected final IOService ioService;
-    protected Selector selector;
     protected NonBlockingIOThread ioThread;
-    protected SelectionKey selectionKey;
+    // is a Handler shared among threads?
+    protected volatile SelectionKey selectionKey;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java]: It will not be touched by multiple threads. So volatile isn't needed.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java [hunk 6]
```diff
@@ -56,14 +59,15 @@ public AbstractHandler(TcpIpConnection connection, NonBlockingIOThread ioThread,
...
         this.ioThreadId = ioThread.id;
-        this.selector = ioThread.getSelector();
         this.socketChannel = connection.getSocketChannelWrapper();
         this.connectionManager = connection.getConnectionManager();
         this.ioService = connectionManager.getIoService();
         this.logger = ioService.getLogger(this.getClass().getName());
         this.initialOps = initialOps;
     }
 
+    protected abstract void reschedule();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java]: Probably this method doesn't need to be implemented at every subclass. We should be able to implement it directly.

I need to think about the implementation, because it could bite with the migration.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java (hunk 1 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: Confirmed.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java [hunk 7]
```diff
@@ -98,11 +102,33 @@ final void unregisterOp(int operation) throws IOException {
...
     public void onFailure(Throwable e) {
         if (e instanceof OutOfMemoryError) {
             ioService.onOutOfMemory((OutOfMemoryError) e);
         }
+
+        // if our selection key was cancelled due to replacement of the selector
+        // (see NonBlockingIOThread#selectWorkaround), then reschedule this handler for execution
+        if (e instanceof CancelledKeyException && selectionKey != null
+                && selectionKey.selector() != ioThread.getSelector()) {
+            // the selector was replaced, so obtain a new key for the new selector
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java]: @pveentjer If a migration is in progress, perhaps we risk overwriting the new `selectionKey` created in the new owner thread executing `completeMigration`. Should this condition be amended as follows to avoid interfering with a migration in progress? In this scenario, `this.ioThread` has already been substituted by `startMigration` with the new owner thread, while `onFailure` would still be executing a task on the previous owner.
```java
if (e instanceof CancelledKeyException && selectionKey != null
                && ioThread == Thread.currentThread()
                && selectionKey.selector() != ioThread.getSelector()) {
```

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java [hunk 8]
```diff
@@ -47,8 +49,20 @@
     private final SwCounter eventCount = newSwCounter();
     @Probe
     private final SwCounter exceptionCount = newSwCounter();
+    // count number of times the selector was recreated (if selectWorkaround is enabled)
+    @Probe
+    private final SwCounter selectorRecreateCount = newSwCounter();
+    // last time select returned
     private volatile long lastSelectTimeMs;
 
+    // When true, enables workaround for bug occuring when SelectorImpl.select returns immediately
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: I would pull this logic into a method e..g 

selectorRebuildEnabled and add a log statement when it is true.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java [hunk 9]
```diff
@@ -77,46 +91,89 @@ public void run() {
...
-                if (sk.isValid() && sk.isAcceptable()) {
-                    eventCount.inc();
-                    acceptSocket();
+            handleSelectionKeys(it);
+        }
+    }
+
+    private void acceptLoopWithSelectorFix() throws IOException {
+        int idleCount = 0;
+        while (connectionManager.isLive()) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: Why are you using connectionManager.isAlive instead of isInterrupted?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 10]
```diff
@@ -307,6 +346,29 @@ public final void shutdown() {
...
+
+        // cancel the old keys
+        for (SelectionKey key: oldSelector.keys()) {
+            key.cancel();
+        }
+
+        try {
+            // close the old selector
+            oldSelector.close();
+
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: Why this white line?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 11]
```diff
@@ -307,6 +346,29 @@ public final void shutdown() {
...
+        } catch (Throwable t) {
+            logger.warning("Failed to close selector.", t);
+        }
+        logger.fine("Recreated Selector because of possible java/network stack bug.");
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: Would it make sense to put this on warning because it is a pretty severe case?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader.java (hunk 4 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingSocketReader.java]: we can get rid of the reschedule completely. When you create the new selectionkey with the same interest set as the old key, then on the next selector.select you will be immediately notified since the underlying conditions to trigger the key in the first place, are still there. If data was available for reading, it will still be available for reading. If space is available for writing, it still is available.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java (hunk 7 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java]: If a migration is in progress, you can't get any events since your selection key is closed.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java [hunk 12]
```diff
@@ -98,11 +101,33 @@ final void unregisterOp(int operation) throws IOException {
...
+            SelectableChannel ch = selectionKey.channel();
+            int ops = selectionKey.interestOps();
+            Object att = selectionKey.attachment();
+
+            // register the channel with the new selector now
+            try {
+                SelectionKey sk = ch.register(ioThread.getSelector(), ops, att);
+                this.selectionKey = sk;
+            } catch (ClosedChannelException ignore) {
+                EmptyStatement.ignore(ignore);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java]: Instead of returning, I would continue with the original flow of the exception. So closing the connection.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 13]
```diff
@@ -307,6 +346,29 @@ public final void shutdown() {
...
 
+    // this method is always invoked in this thread
+    // after we have blocked for selector.select in #runSelectLoopWithSelectorFix
+    private void rebuildSelector() {
+        selectorRebuildCount.inc();
+        Selector newSelector = NonBlockingIOThread.newSelector(logger);
+        Selector oldSelector = this.selector;
+        this.selector = newSelector;
+
+        // cancel the old keys
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: This happens automatically when the selector is closed.

Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: One thing just crossed my head. Probably you can rebuild the selection keys here as well because through the selectionkeys you can read all read/write handlers and then force a rebuild of the selection key. No need to rely on the onFailure.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java (hunk 6 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/AbstractHandler.java]: This method can be removed completely.

**Comment by pveentjer** [comment]
@vbekiaris is there an update or still enjoying yourself with the deadlock?

**Comment by vbekiaris** [comment]
Back from the deadlock, working on simulating bug detection to test selector rebuild code.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java (hunk 9 above)
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: This is the same as plain acceptLoop above.

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java (hunk 8 above)
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: This is now logged on acceptor thread startup: https://github.com/vbekiaris/hazelcast/blob/9e10fffc8d5a3b4c54ad506816d9cfb138df7de8/hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java#L96

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java [hunk 14]
```diff
@@ -77,46 +92,93 @@ public void run() {
             logger.finest("Starting SocketAcceptor on " + serverSocketChannel);
         }
 
-        Selector selector = null;
+        if (selectorWorkaround) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: I would do this coordinated at a single place. Otherwise you will get 3+3+1 of these log entries.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java [hunk 15]
```diff
@@ -77,46 +92,93 @@ public void run() {
...
+            // of course it is acceptable!
+            if (sk.isValid() && sk.isAcceptable()) {
+                eventCount.inc();
+                acceptSocket();
             }
         }
     }
 
-    private void closeSelector(Selector selector) {
+    private void closeSelector() {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: Can be replaced by IOUtil.closeResource.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 16]
```diff
@@ -171,10 +190,15 @@ public final void run() {
...
-                    } else {
-                        runSelectLoop();
+                    switch (selectorMode) {
+                        case CPU_WORKAROUND:
+                            runSelectLoopWithSelectorFix();
+                            break;
+                        case NOW:
+                            runSelectNowLoop();
+                            break;
+                        default:
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: I would not use 'default' for runSelect loop. Add a third 'case' and in the default an exception can be thrown.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 17]
```diff
@@ -171,10 +190,15 @@ public final void run() {
         try {
             for (; ; ) {
                 try {
-                    if (selectNow) {
-                        runSelectNowLoop();
-                    } else {
-                        runSelectLoop();
+                    switch (selectorMode) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: I would rename this to select mode. Because it says something about which select approach is being used; not the selector.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 18]
```diff
@@ -171,10 +190,15 @@ public final void run() {
...
+                        case CPU_WORKAROUND:
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: I would rename the 3 methods:
selectLoop
selectNowLoop
selectLoopWithFix

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 19]
```diff
@@ -307,8 +360,42 @@ public final void shutdown() {
...
+                logger.info("Channel was closed while trying to register with new selector.");
+            } catch (CancelledKeyException e) {
+                // a CancelledKeyException may be thrown in key.interestOps
+                // in this case, since the key is already cancelled, just do nothing
+                EmptyStatement.ignore(e);
+            }
+            key.cancel();
+        }
+
+        IOUtil.closeResource(oldSelector);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: I would use a static import here.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThreadingModel.java [hunk 20]
```diff
@@ -54,10 +53,16 @@
...
+    // experimental settings; default value is "default" and implies using Selector.select(timeout)
+    // Other possible values:
+    //   "now" -> use Selector.selectNow
+    //   "cpu-workaround" -> use Selector.select(timeout) with workaround for bug occurring when
+    //                       SelectorImpl.select returns immediately with no channels selected,
+    //                       resulting in 100% CPU usage while doing no progress.
+    // See issue: https://github.com/hazelcast/hazelcast/issues/7943
+    private SelectorMode selectorMode;
     private volatile IOBalancer ioBalancer;
+    private boolean selectorWorkaroundTest = Boolean.getBoolean("hazelcast.io.selector.workaround.test");
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThreadingModel.java]: Can you add note we need to convert this to HazelcastProperty. But this requires some deeper changes since in this class we have no access to the HazelcastProperties. So something for 3.8

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/SelectorMode.java [hunk 21]
```diff
@@ -0,0 +1,51 @@
...
+
+package com.hazelcast.nio.tcp.nonblocking;
+
+import com.hazelcast.util.StringUtil;
+
+/**
+ * Controls the mode in which IO and acceptor thread selectors will be operating
+ */
+public enum SelectorMode {
+    DEFAULT("default"),
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/SelectorMode.java]: I would rename this to:
select
selectnow
selectwithfix

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java (hunk 14 above)
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SocketAcceptorThread.java]: Logging the selector mode once in `NonBlockingIOThreadingModel.start` should be sufficient, will remove this log entry (https://github.com/vbekiaris/hazelcast/blob/master-nio-workaround/hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThreadingModel.java#L125-L125).

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 22]
```diff
@@ -307,8 +360,42 @@ public final void shutdown() {
         interrupt();
     }
 
+    // this method is always invoked in this thread
+    // after we have blocked for selector.select in #runSelectLoopWithSelectorFix
+    private void rebuildSelector() {
+        selectorRebuildCount.inc();
+        Selector newSelector = NonBlockingIOThread.newSelector(logger);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: why do you need NonBLockingIOThread. ?

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java [hunk 23]
```diff
@@ -307,8 +360,42 @@ public final void shutdown() {
...
+        Selector oldSelector = this.selector;
+        this.selector = newSelector;
+
+        // reset each handler's selectionKey, cancel the old keys
+        for (SelectionKey key : oldSelector.keys()) {
+            AbstractHandler att = (AbstractHandler) key.attachment();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/NonBlockingIOThread.java]: I would call this handler or attachment. att was not immediately clear.

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by pveentjer** [comment]
👍

**Comment by mdogan** [comment]
👍 
good job.

**Comment by vbekiaris** [comment]
run-lab-run
