### PR TITLE
Threads with name 'pool' fixes

### LINKED ISSUE #9210: thread names assigned to all threads created by Hazelcast
it would be nice to have names assigned to all threads created by Hazelcast (and not default ones eg: pool-2-thread-1, pool-2-thread-2)
I have found 2 case where Hazelcast creates ThreadPool - but without name pattern
TcpIpConnectionManager:
private final ScheduledExecutorService scheduler = new ScheduledThreadPoolExecutor(4);
and
MetricsRegistryImpl
private final ScheduledExecutorService scheduledExecutorService = new ScheduledThreadPoolExecutor(2);

Have nice day (-:

### PR DESCRIPTION
**Pull request by pveentjer**
MetricsRegistryImpl and TcpIpConnectionManager create a bunch of threads
but the created threads don't have an clear name. This pr fixes that.

Fixes #9210

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnectionManager.java [hunk 1]
```diff
@@ -129,7 +130,8 @@ public TcpIpConnectionMonitor createNew(Address endpoint) {
     @Probe
     private final MwCounter closedCount = newMwCounter();
 
-    private final ScheduledExecutorService scheduler = new ScheduledThreadPoolExecutor(4);
+    private final ScheduledExecutorService scheduler
+            = new ScheduledThreadPoolExecutor(4, new ThreadFactoryImpl("TcpIpConnectionManager-thread-"));
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnectionManager.java]: I think I can do that

Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/TcpIpConnectionManager.java]: There will be a quite a big set of changes required because now there is going to be a reliance of the HazelcastThreadGroup. Not only on the server, but also on the client.

**Comment by pveentjer** [comment]
Too much work. I'm going to close the ticket and let the users deal with their pool threads.

**Comment by pveentjer** [comment]
I'm going to re-open this.

My suggestion is the following. I'll create a new github ticket where we add the naming of cluster group. The current naming (without the clustergroup) is already an improvement because at least it is clear who created the threads. Also in most cases people have only a single hz instance
