### PR TITLE
Change semantics and name of assumeThatJDK8

### LINKED ISSUE #14379: W3cDomTest.testYamlExtendedTestFromInputStream
Failed on OracleJDK6 : https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-OracleJDK6/532/testReport/com.hazelcast.config.yaml/W3cDomTest/testYamlExtendedTestFromInputStream/

**Stacktrace**
```
com.hazelcast.internal.yaml.YamlException: An error occurred while loading and parsing the YAML stream
	at com.hazelcast.internal.yaml.YamlLoader.load(YamlLoader.java:56)
	at com.hazelcast.config.yaml.W3cDomTest.testYamlExtendedTestFromInputStream(W3cDomTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.UnsupportedOperationException: Processing YAML documents requires Java 8 or higher version
	at com.hazelcast.internal.yaml.YamlLoader.getLoad(YamlLoader.java:158)
	at com.hazelcast.internal.yaml.YamlLoader.load(YamlLoader.java:51)
```

### PR DESCRIPTION
**Pull request by blazember**
The primary intention of this change is to ignore `W3cDomTest` on JDK6.
Since we test our builds with JDK8+ versions as well, assumeThatJDK8 ignores the affected tests on JDK8+ builds, therefore changed the name and the semantics of the assumeThatJDK8 method. From now it ignores the affected tests on JDK6 and JDK7 only.

Fixes #14379

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/config/yaml/W3cDomTest.java [hunk 1]
```diff
@@ -47,11 +48,13 @@
...
 @RunWith(HazelcastParallelClassRunner.class)
 @Category(QuickTest.class)
-public class W3cDomTest {
+public class W3cDomTest extends HazelcastTestSupport {
     private static final int NOT_EXISTING = 42;
 
     @Test
-    public void testYamlExtendedTestFromInputStream() {
+    public void testW3cDomAdapter() {
+        assumeThatJDK8();
```
Comment (tezc) [inline hazelcast/src/test/java/com/hazelcast/config/yaml/W3cDomTest.java]: It won't run on JDK9+ I think, do we need sth like : 
```
assumeThatNoJDK6();
assumeThatNoJDK7();
```

Comment (blazember) [reply hazelcast/src/test/java/com/hazelcast/config/yaml/W3cDomTest.java]: Good point. Shuffled the things a bit, renamed `assumeThatJdk8()` to `assumeThatJdk8OrHigher()` and changed it's logic accordingly, see the updated description.

**Comment by blazember** [comment]
Thanks for the reviews @mustafaiman @tezc
