### PR TITLE
[2.x] Fixes issue #3308: FactoryImpl.lsInstanceListeners leaks after client is disconnected

### LINKED ISSUE #3308: FactoryImpl maintaining references to ClientEndpoint objects after connection is closed leading to memory leak
In 2.x, FactoryImpl maintains references to ClientEndpoint objects even after the client connection has been closed.  Those lingering ClientEndpoint instances, in turn, prevent their CallContext objects from being garbage-collected (we have reported another issue that causes a leak of CallContext objects here: https://github.com/hazelcast/hazelcast/issues/2829).  This causes a memory leak as our client services are restarted.

See the heap dump below.  Note that the connection is not live, and that the ClientEndpoint objects are successfully removed from the ClientHandlerService's references.  The first image is an instance of ClientEndpoint with a connection that is still live, for comparison.

image

image

### PR DESCRIPTION
**Pull request by mdogan**
Fixes #3308

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/impl/ClientHandlerService.java [hunk 1]
```diff
@@ -240,6 +240,10 @@ public ClientEndpoint getClientEndpoint(Connection conn) {
         return mapClientEndpoints.get(conn);
     }
 
+    Collection<ClientEndpoint> getClientEndpoints() {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/impl/ClientHandlerService.java]: is this added just for sake of tests?

Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/impl/ClientHandlerService.java]: yes
