### PR TITLE
Fixed leaking memory from ItemCounter on LoadTracker

### LINKED ISSUE #6496: IOBalancerMemoryLeakTest.testMemoryLeak
```
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:776)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:773)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1324)
	at com.hazelcast.internal.ascii.HTTPCommunicator.doGet(HTTPCommunicator.java:140)
	at com.hazelcast.internal.ascii.HTTPCommunicator.getClusterInfo(HTTPCommunicator.java:81)
	at com.hazelcast.nio.tcp.nonblocking.iobalancer.IOBalancerMemoryLeakTest.testMemoryLeak(IOBalancerMemoryLeakTest.java:52)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/745/testReport/junit/com.hazelcast.nio.tcp.nonblocking.iobalancer/IOBalancerMemoryLeakTest/testMemoryLeak/

### PR DESCRIPTION
**Pull request by eminn**
ItemCounters are leaking memory by holding references to the SocketReader/SocketWriters. When a connection is added/removed a task is created on the queue of IOBalancer, and IOBalancer will process these tasks to notify LoadTrackers to make necessary cleanups . By doing that LoadTrackers will only accessed by IOBalancer thread which eliminates the requirement of thread-safe ItemCounters.

Memory Usage before this fix : 
screen shot 2016-03-02 at 12 02 47 pm

Memory Usage after this fix : 
screen shot 2016-03-02 at 12 03 00 pm

Thanks @mahileeb for reporting this issue.

Fixes #6496 #6199

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/iobalancer/LoadTracker.java [hunk 1]
```diff
@@ -56,6 +58,8 @@
 
     private final LoadImbalance imbalance;
 
+    private final Queue<Runnable> tasks = new LinkedBlockingQueue<Runnable>();
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/nonblocking/iobalancer/LoadTracker.java]: do we want to have unbound capacity?

**Comment by jerrinot** [comment]
I guess https://github.com/hazelcast/hazelcast/pull/7647/files#diff-e4c708098b570991740972bbb9ac7d54R57 can now use a simpler structure as it's accessed by a single thread only

**Comment by jerrinot** [comment]
:+1:

**Comment by gurbuzali** [comment]
:+1:
