### PR TITLE
Listener registration race fixed

### LINKED ISSUE #6724: [TEST-FAILURE] CacheBasicClientTest.testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce
**Error Message**
expected:<1> but was:<2>

**Stacktrace**
```
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.cache.CacheBasicAbstractTest$11.run(CacheBasicAbstractTest.java:545)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:825)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:839)
	at com.hazelcast.cache.CacheBasicAbstractTest.testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce(CacheBasicAbstractTest.java:541)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Standard Output**
```
Finished Running Test: CacheBasicAbstractTest.testIteratorDuringRemoval_withEviction in 30.698 seconds.
16:03:24,216  INFO [LifecycleService] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - HazelcastClient[hz.client_1011_dev][3.6-RC1-SNAPSHOT] is SHUTTING_DOWN
16:03:24,217  INFO [ClientEndpointManager] hz._hzInstance_1318_dev.event-11639 - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Destroying ClientEndpoint{conn=MockedNodeConnection{ remoteEndpoint = Address[127.0.0.1]:6978, localEndpoint = Address[127.0.0.1]:6273, connectionId = 1}, principal='ClientPrincipal{uuid='1873f3fc-7e43-4f26-ad58-48753dd2e772', ownerUuid='f7b608b4-9a02-4dbf-af5e-50ee82d6c39b'}', firstConnection=true, authenticated=true}
16:03:24,217  INFO [LifecycleService] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - HazelcastClient[hz.client_1011_dev][3.6-RC1-SNAPSHOT] is SHUTDOWN
16:03:24,217  INFO [LifecycleService] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Address[127.0.0.1]:6273 is SHUTTING_DOWN
16:03:24,217  WARN [Node] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Terminating forcefully...
16:03:24,217  INFO [Node] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Shutting down multicast service...
16:03:24,217  INFO [Node] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Shutting down connection manager...
16:03:24,217  INFO [Node] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Shutting down node engine...
16:03:24,229  INFO [NodeExtension] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Destroying node NodeExtension.
16:03:24,229  INFO [Node] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Hazelcast Shutdown is completed in 12 ms.
16:03:24,229  INFO [LifecycleService] testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce - [127.0.0.1]:6273 [dev] [3.6-RC1-SNAPSHOT] Address[127.0.0.1]:6273 is SHUTDOWN
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast-client/16796/testReport/junit/com.hazelcast.client.cache/CacheBasicClientTest/testRemovingSameEntryTwiceShouldTriggerEntryListenerOnlyOnce/

### PR DESCRIPTION
**Pull request by sancar**
Lots of tests are added to verify the correct behaviour.
Since listener registration and deregistration are not in hot paths
and simplicity a lock on member variable is used in the fix.

fixes #6724 #6695 #6694 #6654 #6622 #6620 #6580 #6545

### CODE REVIEW

**Comment by hasancelik** [comment]
run-lab-run

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java [hunk 1]
```diff
@@ -408,6 +408,7 @@ public V put(K key, V value, long ttl, TimeUnit timeunit) {
     protected V putInternal(long ttl, TimeUnit timeunit, Data keyData, Data valueData) {
         ClientMessage request = MapPutCodec.encodeRequest(name, keyData, valueData,
                 ThreadUtil.getThreadId(), getTimeInMillis(ttl, timeunit));
+//        Logger.getLogger(IMap.class).warning(" Doing put");
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java]: line can be deleted

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java [hunk 2]
```diff
@@ -157,14 +158,16 @@ public String addMembershipListener(MembershipListener listener) {
...
-        if (listener instanceof InitialMembershipListener) {
-            // TODO: needs sync with membership events...
-            final Cluster cluster = client.getCluster();
-            ((InitialMembershipListener) listener).init(new InitialMembershipEvent(cluster, cluster.getMembers()));
+        synchronized (initialMembershipListenerMutex) {
+            String id = addMembershipListenerWithoutInit(listener);
+            Cluster cluster = client.getCluster();
+            if (listener instanceof InitialMembershipListener) {
+                Collection<Member> memberCollection = members.get().values();
+                LinkedHashSet<Member> members = new LinkedHashSet<Member>(memberCollection);
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java]: should we use unmodifiableSet here as well?

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java [hunk 3]
```diff
@@ -174,12 +177,15 @@ private String addMembershipListenerWithoutInit(MembershipListener listener) {
...
-                InitialMembershipEvent event = new InitialMembershipEvent(cluster, cluster.getMembers());
-                ((InitialMembershipListener) membershipListener).init(event);
+        synchronized (initialMembershipListenerMutex) {
+            for (MembershipListener membershipListener : listeners.values()) {
+                if (membershipListener instanceof InitialMembershipListener) {
+                    Cluster cluster = client.getCluster();
+                    Collection<Member> memberCollection = members.get().values();
+                    LinkedHashSet<Member> members = new LinkedHashSet<Member>(memberCollection);
+                    InitialMembershipEvent event = new InitialMembershipEvent(cluster, members);
+                    ((InitialMembershipListener) membershipListener).init(event);
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java]: seems partly duplicate code as addMembershipListener, could be refactored into a common method

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientMembershipListener.java [hunk 4]
```diff
@@ -94,7 +94,7 @@ public void handle(Set<Member> initialMembers) {
 
         final List<MembershipEvent> events = detectMembershipEvents(prevMembers);
         if (events.size() != 0) {
-            applyMemberListChanges();
+            LOGGER.info(membersString());
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientMembershipListener.java]: could we add more context to the log? i.e got initial members
Same as the other logging

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java (hunk 1 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java]: I am removing it.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java (hunk 2 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java]: Yes, it should be unmodifiable. Changing it in both new  and old client.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java (hunk 3 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java]: Also updating this part accordingly.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java [hunk 5]
```diff
@@ -22,101 +22,126 @@
...
+
+            if (registration == null) {
+                return false;
+            }
+
+            ClientMessage request = registration.getCodec().encodeRemoveRequest(registration.getServerRegistrationId());
+            try {
+                Future future = new ClientInvocation(client, request).invoke();
+                future.get();
+                removeEventHandler(registration.getCallId());
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: previously we removed the event handler before the invocation, now it's done after. Is this intentional?

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java [hunk 6]
```diff
@@ -20,103 +20,112 @@
...
-        return userRegistrationId;
     }
 
-    private void invoke(ClientRegistrationKey registrationKey, Address address) {
-        ClientMessage request = registrationKey.getRequest();
+    private void invoke(ClientRegistrationKey registrationKey, Address address) throws Exception {
+        ListenerMessageCodec codec = registrationKey.getCodec();
+        ClientMessage request = codec.encodeAddRequest(true);
         EventHandler handler = registrationKey.getHandler();
         handler.beforeListenerRegister();
```
Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java]: handler.beforeListenerRegister and handler.afterListenerRegister will now be called once for every member it is registered to. Is this intentional?

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java (hunk 5 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: Yes. In case of we fail to deregister the listener on server side, we are throwing an exception saying we fail to deregister. In this case, user will expect events to continue coming. That is why I am doing it only if future.get returns without throwing exception.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java (hunk 6 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java]: This callbacks are mainly used for cache invalidation. This is the safer approach to not have invalid near cache. We could argue for better solution later. 

>> This will also mean that the events will get fired again when a new member is added
I did not understand what you mean by this. Do you mean ,for example,  entryUpdated can be fired twice for same event when a new node joined ?

Comment (cangencer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java]: No I meant that the beforeListenerRegister and onListenerRegister events will get fired twice, i.e. the cache will be invalidated every time a new member is added

Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java]: So my first answer applies.

**Comment by cangencer** [comment]
:+1: looks good to me, besides a few comments which have been answered

**Comment by sancar** [comment]
@cangencer 
I made the changes locally. Waiting for @ihsandemir to review also. I will push all changes at once.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/ProxyManager.java [hunk 7]
```diff
@@ -305,13 +306,13 @@ private Connection getTargetOrOwnerConnection(final Address target) throws IOExc
...
         Member liteMember = null;
 
         final LoadBalancer loadBalancer = client.getLoadBalancer();
         for (int i = 0; i < clusterSize; i++) {
-            final Member member = loadBalancer.next();
-            if (!member.isLiteMember()) {
+            Member member = loadBalancer.next();
+            if (member != null && !member.isLiteMember()) {
                 return member.getAddress();
             } else if (liteMember == null) {
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/ProxyManager.java]: do we need this else if since liteMember is guaranteed to be null at this point.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java [hunk 8]
```diff
@@ -205,54 +210,38 @@ private ClientConfig getClientConfig() {
...
+
+            fireMembershipEvent(event);
         }
-        sb.append("\n}\n");
-        return sb.toString();
     }
 
-    void fireMembershipEvent(final MembershipEvent event) {
-        ClientExecutionService clientExecutionService = client.getClientExecutionService();
-        clientExecutionService.execute(new Runnable() {
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java]: Was it off-loaded to a thread after the IO thread before this point?

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientMembershipListener.java [hunk 9]
```diff
@@ -144,7 +144,7 @@ void initialMembers(ClientInitialMembershipEvent event) {
 
     private void memberRemoved(Member member) {
         members.remove(member);
-        applyMemberListChanges();
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientMembershipListener.java]: why is this deleted?

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/ProxyManager.java (hunk 7 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/ProxyManager.java]: if at first a lite member comes, than a null comes, than we can hit this `else` lite member as far as I understand.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java (hunk 8 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientClusterServiceImpl.java]: No, this is not IO thread.
These are event threads. Same as all other listeners callbacks.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/ProxyManager.java (hunk 7 above)
Comment (metanet) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/ProxyManager.java]: In ``liteMember`` reference, we just keep the first lite member we hit.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientMembershipListener.java (hunk 9 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/ClientMembershipListener.java]: Method was two lines. 
```
    private void applyMemberListChanges() {		
        updateMembersRef();		
        LOGGER.info(clusterService.membersString());		
  }
```
We don't need updateMembersRef anymore but rather updating the members in clusterService.handleMembershipEvent method. After that method become line, and I removed the method and put the one line here.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java [hunk 10]
```diff
@@ -23,100 +23,134 @@
...
-        return userRegistrationId;
+    public String registerListener(BaseClientAddListenerRequest addRequest,
+                                   BaseClientRemoveListenerRequest removeRequest, EventHandler handler) {
+        synchronized (listenerRegLock) {
+            String userRegistrationId = UuidUtil.newUnsecureUuidString();
+            ClientRegistrationKey registrationKey =
+                    new ClientRegistrationKey(userRegistrationId, addRequest, removeRequest, handler);
+            try {
+                ClientEventRegistration registration = invoke(registrationKey);
+                registrations.put(registrationKey, registration);
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: can you decrease the lock scope by putting the synchronization at this point?

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java [hunk 11]
```diff
@@ -23,100 +23,134 @@
...
+                return false;
+            }
+
+            BaseClientRemoveListenerRequest removeRequest = registration.getRemoveRequest();
+            removeRequest.setRegistrationId(registration.getServerRegistrationId());
+            try {
+                Future future = new ClientInvocation(client, removeRequest).invoke();
+                future.get();
+                removeEventHandler(registration.getCallId());
+                registrations.remove(key);
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: don't you need listenerRegLock synchronization at this point as performed in registerListener?

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java [hunk 12]
```diff
@@ -23,100 +23,134 @@
...
+    public void connectionAdded(Connection connection) {
+        executionService.executeInternal(new Runnable() {
+            @Override
+            public void run() {
+                synchronized (listenerRegLock) {
                     for (ClientRegistrationKey registrationKey : registrations.keySet()) {
-                        invoke(registrationKey);
+                        try {
+                            ClientEventRegistration registration = invoke(registrationKey);
+                            registrations.put(registrationKey, registration);
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: you can decrease the lock holding time if do the invocations first and get the lock and then put all the registrations into the map and release the lock.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java [hunk 13]
```diff
@@ -23,100 +23,134 @@
...
     @Override
-    public void memberRemoved(MembershipEvent membershipEvent) {
-        Address ownerConnectionAddress = client.getClientClusterService().getOwnerConnectionAddress();
-        if (membershipEvent.getMember().getAddress().equals(ownerConnectionAddress)) {
-            for (ClientEventRegistration registration : registrations.values()) {
-                removeEventHandler(registration.getCallId());
+    public void connectionRemoved(Connection connection) {
+        synchronized (listenerRegLock) {
+            for (Map.Entry<ClientRegistrationKey, ClientEventRegistration> entry : registrations.entrySet()) {
+                removeEventHandler(entry.getValue().getCallId());
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: The lock holding time can also be decreased here by separating the invocations from map removals.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java [hunk 14]
```diff
@@ -23,100 +23,134 @@
...
+    //For Testing
+    public Collection<ClientEventRegistration> getActiveRegistrations(String uuid) {
+        synchronized (listenerRegLock) {
+            ClientEventRegistration registration = registrations.get(new ClientRegistrationKey(uuid));
+            if (registration == null) {
+                return Collections.EMPTY_LIST;
+            }
+            LinkedList<ClientEventRegistration> activeRegistrations = new LinkedList<ClientEventRegistration>();
+            if (getEventHandler(registration.getCallId()) != null) {
+                activeRegistrations.add(registration);
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: Multiple calls to getActiveRegistrations with the same uuid will increase activeRegistrations on each call. Is this what 's desired from this method?

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java [hunk 15]
```diff
@@ -19,102 +19,116 @@
...
+                                   EventHandler handler) {
+        addRequest.setLocalOnly();
+        String userRegistrationId = UuidUtil.newUnsecureUuidString();
+        synchronized (listenerRegLock) {
 
-        Collection<Member> members = client.getClientClusterService().getMemberList();
+            ClientRegistrationKey registrationKey =
+                    new ClientRegistrationKey(userRegistrationId, addRequest, removeRequest, handler);
+            registrations.put(registrationKey, new ConcurrentHashMap<Address, ClientEventRegistration>());
+            try {
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java]: it seems like we can release the lock at this point, before time consuming invoke calls.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java (hunk 14 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: There is only one registration for a uuid. And there is no loop. So there is no way to activeRegistrations.add(registration) called twice in this method.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java (hunk 13 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: ??? There is no invocation here.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java (hunk 15 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientSmartListenerService.java]: We can not. Main purpose of this lock is to sync members list iteration with member added and member removed on other methods.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java (hunk 11 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: I did not understand the question. 
All method is already inside listenerRegLock .

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java (hunk 12 above)
Comment (sancar) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientNonSmartListenerService.java]: Lets assume, I removed the lock from the invocations, 
Lets say we have connection added and deregister together. Deregister get the lock removed it from map still holding the lock. 

Then connection added starting sending invocations to remote which will be completely wrong registrations.  Locks purpose is violated here.

File: hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientListenerServiceImpl.java [hunk 16]
```diff
@@ -118,4 +122,7 @@ public int getKey() {
             return packet.getPartitionId();
         }
     }
+
+    //For Testing
+    public abstract Collection<ClientEventRegistration> getActiveRegistrations(String uuid);
```
Comment (ihsandemir) [inline hazelcast-client-legacy/src/main/java/com/hazelcast/client/spi/impl/listener/ClientListenerServiceImpl.java]: public method for testing?

**Comment by ihsandemir** [comment]
:+1:

**Comment by mdogan** [comment]
@sancar: EE repo is not compiling because of this change.

**Comment by sancar** [comment]
I will push the fix asap.
