### PR TITLE
Make dynamic config available on lite members

### LINKED ISSUE #10926: [config] [dynamic-config] Ensure dynamic configuration is available before HazelcastInstance is returned to user
Dynamic configuration currently relies on replication operation to distribute dynamically added configs to new members. This has two consequences:
- dynamic configs are not available in lite members
- the `HazelcastInstance` is returned to the user before the replication operations are done, so a user may create a proxy before the dynamic config is known to the local member.

### LINKED ISSUE #10946: DynamicConfigBouncingTest
**com.hazelcast.internal.dynamicconfig.DynamicConfigBouncingTest.doNotThrowExceptionWhenMemberIsGone**
```java

com.hazelcast.core.HazelcastInstanceNotActiveException: Member [127.0.0.1]:5004 is currently passive! Operation: com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation{serviceName='configuration-service', identityHash=517224855, partitionId=-1, replicaIndex=0, callId=2646, invocationTime=1500382435066 (2017-07-18 12:53:55.066), waitTimeout=-1, callTimeout=60000}
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:229)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:178)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:120)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9834/testReport/junit/com.hazelcast.internal.dynamicconfig/DynamicConfigBouncingTest/doNotThrowExceptionWhenMemberIsGone/

### PR DESCRIPTION
**Pull request by vbekiaris**
* Pre-join operations are now executed on the joining member before any other operations
* `ClusterWideConfigurationService` now implement `PreJoinAwareService` so lite members are also aware of dynamic configs.
* Member list version as observed on operation source member at time of `AddDynamicConfig` creation is verified to be the same when operation finishes on target member to avoid races between applying the dynamic config and updating the member list as members are added or removed to/from the cluster.
* `HazelcastInstanceNotActiveException` is also considered as a topology change indication (may be thrown when `AddDynamicConfig` is sent to a shutting down member) so is also ignored by the `IGNORE_CLUSTER_TOPOLOGY_CHANGES` exception handler.
* Fixes a typo when applying event journal dynamic config
* Cleanup: removes unnecessary casts to `ClusterServiceImpl`

Fixes #10926
Fixes #10946
Supersedes #10981  

See each separate commit for easier review.

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/AddDynamicConfigOperation.java [hunk 1]
```diff
@@ -17,43 +17,66 @@
...
     }
 
     @Override
     public int getId() {
         return ConfigDataSerializerHook.ADD_DYNAMIC_CONFIG_OP;
     }
 
+    @Override
+    public ExceptionAction onInvocationException(Throwable throwable) {
+        return (throwable instanceof ClusterTopologyChangedException) ? ExceptionAction.THROW_EXCEPTION
```
Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/AddDynamicConfigOperation.java]: why is `ClusterTopologyChangedException` marked as `RetryableException` when it is thrown here?
