### PR TITLE
Make StatisticsAwareServices self-registering as metrics providers

### LINKED ISSUE #16136: ServiceNotFoundException on startup
```java
Hazelcast.newHazelcastInstance();
``` 
fails with the following logs.

```
Nov 28, 2019 12:53:11 PM com.hazelcast.internal.config.AbstractConfigLocator
INFO: Loading 'hazelcast-default.xml' from the classpath.
Nov 28, 2019 12:53:13 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.0-SNAPSHOT] Prefer IPv4 stack is true, prefer IPv6 addresses is false
Nov 28, 2019 12:53:13 PM com.hazelcast.instance.AddressPicker
INFO: [LOCAL] [dev] [4.0-SNAPSHOT] Picked [10.216.1.17]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Nov 28, 2019 12:53:13 PM com.hazelcast.system
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Hazelcast 4.0-SNAPSHOT (20191128 - 5ddc7e7) starting at [10.216.1.17]:5701
Nov 28, 2019 12:53:13 PM com.hazelcast.system
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Copyright (c) 2008-2019, Hazelcast, Inc. All Rights Reserved.
Nov 28, 2019 12:53:13 PM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Backpressure is disabled
Nov 28, 2019 12:53:14 PM com.hazelcast.instance.impl.Node
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Creating MulticastJoiner
Nov 28, 2019 12:53:14 PM com.hazelcast.cp.CPSubsystem
WARNING: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
Nov 28, 2019 12:53:14 PM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Starting 4 partition threads and 3 generic threads (1 dedicated for priority tasks)
Nov 28, 2019 12:53:14 PM com.hazelcast.instance.impl.Node
WARNING: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Terminating forcefully...
Nov 28, 2019 12:53:14 PM com.hazelcast.instance.impl.Node
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Shutting down multicast service...
Nov 28, 2019 12:53:19 PM com.hazelcast.internal.cluster.impl.MulticastService
WARNING: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Failed to shutdown MulticastService in 5 seconds!
Nov 28, 2019 12:53:19 PM com.hazelcast.instance.impl.Node
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Shutting down connection manager...
Nov 28, 2019 12:53:19 PM com.hazelcast.instance.impl.Node
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Shutting down node engine...
Nov 28, 2019 12:53:19 PM com.hazelcast.instance.impl.NodeExtension
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Destroying node NodeExtension.
Nov 28, 2019 12:53:19 PM com.hazelcast.instance.impl.Node
INFO: [10.216.1.17]:5701 [dev] [4.0-SNAPSHOT] Hazelcast Shutdown is completed in 5018 ms.
Exception in thread "main" com.hazelcast.core.HazelcastException: Service with name 'hz:impl:cacheService' not found!
	at com.hazelcast.spi.impl.NodeEngineImpl.getService(NodeEngineImpl.java:404)
	at com.hazelcast.spi.impl.NodeEngineImpl.start(NodeEngineImpl.java:240)
	at com.hazelcast.instance.impl.Node.start(Node.java:426)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:122)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:242)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:221)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:159)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:91)
	at Test.main(Test.java:27)
Caused by: com.hazelcast.spi.exception.ServiceNotFoundException: Service with name 'hz:impl:cacheService' not found!
	... 9 more
```

I think the problem is we only register the cache service if the JCache is on the classpath. But we are trying to get it (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/impl/NodeEngineImpl.java#L240) without this kind of check.

### PR DESCRIPTION
**Pull request by blazember**
Recent change removed `StatisticsAwareMetricsSet` that was responsible for
providing metrics for `StatisticsAwareServices`. This changed to unconditionally
register the implementer services in `NodeEngineImpl`, which failed if the
cache was not initialized (if the `jcache.jar` is not present). Therefore,
all services made self-registering. They register themselves in `init()`
if the datastructure metrics are enabled. There are two exceptions: the
`DistributedExecutorService` and `(Enterprise)WanReplicationService` that
doesn't check the value of the datastructure flag.

Also, an `NPE` is fixed in `EnterpriseWanReplicationService`'s
provider method by checking if the distributed data structure counters are
present.

Additionally, an assertion is added to fail during the metrics
collection if the collection cycle encounters an exception AND the test
is testing metrics collection specifically by directly calling
`MetricRegistry.collect()` (otherwise the `AssertionError` is thrown on a
different thread). This means it is a best-effort assertion. In the
future, we might want to introduce a junit rule that reads out this info
from the metrics collection.

Fixes #16136 and hazelcast/hazelcast-enterprise#3391

EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/3393

### CODE REVIEW

**Comment by blazember** [comment]
cc @puzpuzpuz @mdumandag

File: hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/DynamicMetricsCollectionTest.java [hunk 1]
```diff
@@ -180,8 +180,13 @@ public void testDynamicProviderExceptionsAreNotPropagated() {
 
         });
 
-        metricsRegistry.collect(collectorMock);
-        // we just expect there is no exception
+        // we just expect there is no exception apart from AssertionError,
+        // which is for testing only
+        try {
+            metricsRegistry.collect(collectorMock);
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/DynamicMetricsCollectionTest.java]: Needs a `fail()` after this statement, otherwise test will pass even when `metricsRegistry.collect` does not throw `AssertionError`. Also, annotate the test with `@RequireAssertEnabled` to ensure assertions are enabled.

Comment (blazember) [reply hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/DynamicMetricsCollectionTest.java]: Added, thanks :+1:

**Comment by blazember** [comment]
Merging with an unrelated test failure caused by big hiccups.
