### PR TITLE
SimpleEntry from SupplierConsumingMapper extracted into a top-level class

### LINKED ISSUE #7398: ClassCastException in DistinctValueAggregation.DistinctValueMapper.map() when gettings values from PredicateSupplier
Assume having the following Entities and I want to get a set of unique values for an attribute "type":

E1: {"assetId":"a", "type":"car"}
E2: {"assetId":"b", "type":"paper"}
E3: {"assetId":"c", "type":"blub"}
E3: {"assetId":"d", "type":"car"}

I just want to take a look into entities E1, E2 and E4 and the result should be a set containing "car" and "paper". Due to that I wrote the following code sinppet:

```
com.hazelcast.query.Predicate<String, SampleEntity> assetIdsRestriction = Predicates.in("assetId", "a", "b", "d");
Supplier<String, SampleEntity, String> typeExtractorSupplier = Supplier.all(entity -> entity.getType());
Supplier<String, FleetEntity, String> supplier = Supplier.fromPredicate(assetIdsRestriction, typeExtractorSupplier );
Aggregation<String, String, Set<String>> aggregation = Aggregations.distinctValues();
        return map.aggregate(supplier, aggregation);
```

And what I get is a ClassCastException in DistinctValueAggregation.DistinctValueMapper.map():
```
Caused by: java.lang.ClassCastException: com.hazelcast.mapreduce.aggregation.impl.DistinctValuesAggregation$SimpleEntry cannot be cast to com.hazelcast.query.impl.Extractable
	at com.hazelcast.query.impl.predicates.AbstractPredicate.readAttributeValue(AbstractPredicate.java:129)
	at com.hazelcast.query.impl.predicates.AbstractPredicate.apply(AbstractPredicate.java:55)
	at com.hazelcast.mapreduce.aggregation.impl.PredicateSupplier.apply(PredicateSupplier.java:58)
	at com.hazelcast.mapreduce.aggregation.impl.DistinctValuesAggregation$DistinctValueMapper.map(DistinctValuesAggregation.java:202)
	at com.hazelcast.mapreduce.impl.task.KeyValueSourceMappingPhase.executeMappingPhase(KeyValueSourceMappingPhase.java:49)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.processMapping(MapCombineTask.java:135)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.processPartitionMapping(MapCombineTask.java:304)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask.access$700(MapCombineTask.java:68)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionBasedProcessor.processPartitions(MapCombineTask.java:356)
	at com.hazelcast.mapreduce.impl.task.MapCombineTask$PartitionBasedProcessor.run(MapCombineTask.java:333)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at com.hazelcast.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:67)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

This is because DistinctValueAggregation.DistinctValueMapper.SimpleEntry only implements Map.Entry<K, V> 
```
private static final class SimpleEntry<K, V> implements Map.Entry<K, V> { }
```

and doesn´t extend from QueryableEntry as done in SupplierConsumingMapper.SimpleEntry:

```
static final class SimpleEntry<K, V> extends QueryableEntry<K, V> 
```

---This only happens on Hazelcast 3.6-RC1.----

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #7398
 The SimpleEntry is now re-used in DistinctValuesAggregation.

 It removes code duplication and fixes ClassCastException as the old inner class
 used in DistinctValuesAggregation didn't implement the interface QueryEngine
 expects.

### CODE REVIEW

**Comment by jerrinot** [comment]
backport to 3.6 will follow

**Comment by gurbuzali** [comment]
checkstyle :(

**Comment by messo** [comment]
It would be awesome if this class could be public, since a custom Aggregation/Mapper implementation would use this in 99% of the cases. I had to copy the definitition of this class, but i would gladly use it if it would be public. What do you think?

**Comment by tombujok** [comment]
:+1: Looks good!  It's similar to this one #7149

@messo QueryableEntry is located in the impl package thus it's a part of HZ internals that should not be used by the users.

File: hazelcast/src/main/java/com/hazelcast/util/HashUtil.java [hunk 1]
```diff
@@ -494,7 +494,7 @@ public static int hashToIndex(int hash, int length) {
      * keys are nearly-ordered by their hashed values so when adding one container's
      * values to the other, the number of collisions can skyrocket into the worst case
      * possible.
-     * <p/>
+     * <p/>f
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/util/HashUtil.java]: I think this doesn't belong here. I would recommend a direct edit after merge, if there is no other need for an PR update.

**Comment by Donnerbart** [comment]
:+1:

**Comment by messo** [comment]
@tombujok I do understand this, but I cannot see any other way to start the implementation of the `Mapper#map()` method, than to invoke `supplier.apply()` on the entry created from the key value pairs (the same way as the standard implementations).

```java
public class CustomAggregation implements Aggregation<KeyIn, ValueOut, Result> {
    
    // [...]

    public Mapper<KeyIn, ValueIn, KeyOut, ValueOut> getMapper(Supplier<KeyIn, ?, ValueOut> supplier) {
        return new Mapper<KeyIn, ValueIn, KeyOut, ValueOut>() {
            @Override
            public void map(KeyIn key, ValueIn value, Context<KeyOut, ValueOut> context) {
                // [...]
                // [recreate entry from key, value pairs
                ValueOut valueOut = supplier.apply(entry);
                // possible invocation of context.emit()
            }
        }
    }
}
```

An other solution would be that _a)_ do not unwrap the entry, and change the interface from (key, value, context) to (entry, context) or _b)_ it wouldn't need to invoke the supplier manually. Both of these induce API change.

However it might not be the best place to ask about this issue -- please guide me where should I ask this question.

Thanks!

**Comment by jerrinot** [comment]
@messo: Hello, I agree there shouldn't be the need to invoke a `supplier.apply()` from a mapper. This is a separate concern. @noctarius: Any idea what is it implemented this way?

**Comment by noctarius** [comment]
Not sure I understand the problem. Supplier is part of aggregations and not mapreduce itself, therefore this implementation exists (separation of concerns) but probably I got the problem wrong :)

**Comment by jerrinot** [comment]
for the record: I had a side-channel conversation with @noctarius. It appears the right is to provide some sort of `AbstractSuplyingMapper`.

This would hide the supply part from the user without doing incompatible API changes.

**Comment by messo** [comment]
@jerrinot that sounds perfect, like if the implementation would be similar to this:

```java
public class CustomAggregation implements Aggregation<KeyIn, ValueOut, Result> {
    
    // [...]

    public Mapper<KeyIn, ValueIn, KeyOut, ValueOut> getMapper(Supplier<KeyIn, ?, ValueOut> supplier) {
        return new AbstractSupplyingMapper<KeyIn, ?, KeyOut, ValueOut>(supplier) {
            @Override
            public void map(ValueOut value, Context<KeyOut, ValueOut> context) {
                // possible invocation of context.emit()
            }
        }
    }
}
```

That would be really helpful. Will you let me know about this enhancement/improvement (issue number / commit id)?

**Comment by Donnerbart** [comment]
FYI: I just fixed that tiny issue in `HashUtil`, which was introduced with this PR: https://github.com/hazelcast/hazelcast/commit/0413499896bf3b3027f7daadb9dbc3cbef1b5f52

**Comment by jerrinot** [comment]
@Donnerbart: thanks a lot!
@messo: no issue was created yet. can you please open a new GitHub issue and describe what behaviour you would expect from `AbstractSupplyingMapper` ? cheers!
