### PR TITLE
Resolved performance problem with PagingPredicate JDK8

### LINKED ISSUE #17207: Severe performance degradation on Java 8 for PagingPredicate
If I run the following code, elapsed time is:

OpenJDK 11.0.7 - 662 milliseconds
OpenJDK 1.8.0_252 - 27837 milliseconds

All looks ok on Java 11.
Hazelcast 3.9 is ok, but 3.10 through to 4.0 exhibit the slowdown.

Code
```
public class Main {
    private static final String MAP_NAME = System.getProperty("user.name");
    private static final int MAX = 1000;
    private static final int PAGE_SIZE = 100;
    private static final int LOOPS = 5;

    public static void main(String[] args) throws Exception {
        Config config = new Config();
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
        IMap map = instance.getMap(MAP_NAME);

        for (int i = 0; i < MAX; i++) {
            MyData value = new MyData();
            value.setI(i);
            map.set(i, value);
        }
        
        long start = System.currentTimeMillis();

        for (int i = 0 ; i < LOOPS ; i++) {
            System.out.println("LOOP " + i + " @ " + new Date());
            Predicate predicate = new SqlPredicate("i > 0");
            PagingPredicate pagingPredicate = Predicates.pagingPredicate(predicate, PAGE_SIZE);

            Collection results = map.values(pagingPredicate);
            while (results != null && results.size() > 0) {
                pagingPredicate.nextPage();
                results = map.values(pagingPredicate);
            }
        }
        
        long elapsed = System.currentTimeMillis() - start;

        instance.shutdown();
        
        System.out.println("ELAPSED " + elapsed);
    }

    @SuppressWarnings("serial")
    private static class MyData implements Comparable<MyData>, Serializable {
        private int i;

        public int getI() {
            return i;
        }

        public void setI(int i) {
            this.i = i;
        }

        public int compareTo(MyData that) {
            return this.i - that.getI();
        }
    }
```

### PR DESCRIPTION
**Pull request by pveentjer**
There is a very severe performance issue with JDK 8 in combination with
the paging predicate. This is caused by SubList.sort. This issue is resolved
with JDK9 but we need to fix the issue for a large number of people using 
JDK 8

The problem is fixed by switching from LinkedList to ArrayList in the
QueryResult. Benchmarks are included in the ticket

fix #17207

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1454/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1454/Hazelcast-pr-builder-1454.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryResult.java:33:8: Unused import - java.util.ArrayList. [UnusedImports]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1455/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1455/Hazelcast-pr-builder-1455.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder_2/hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryResult.java:35:8: Unused import - java.util.LinkedList. [UnusedImports]
--------------------------
</details>
</pre>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1458/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1458/Hazelcast-pr-builder-1458.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientReliableTopicOnClusterRestartTest.shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant:185->lambda$shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant$5:187
[INFO] 
[ERROR] Tests run: 31114, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by pveentjer** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryResult.java [hunk 1]
```diff
@@ -62,7 +62,7 @@
  */
 public class QueryResult implements Result<QueryResult>, Iterable<QueryResultRow> {
 
-    private List rows = new LinkedList();
+    private List rows = new ArrayList();
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/QueryResult.java:65]: `QueryResult` constructor has `resultLimit`, it can be better to pass it to `ArrayList` as an initial capacity. Seems initial capacity can be applied also for `QueryResult#readData`.
