### PR TITLE
Delay invocation retry during split brain

### LINKED ISSUE #3754: Queue poll operation - WrongTargetException
We're running a 2 node client-server deployment based on 3.2.5 running on AWS EC2.

After one of the nodes disconnected and reconnected, a merge operation occurred, following it we started to get a crazy amount of the following message, and more importantly - clients that were connected to SERVER1 were stuck on Poll, not polling any items even though the queue was not empty:
```
» 12:41:05.080 WARNING: [SERVER1]:5701 [dev] [3.2.5] Op: com.hazelcast.queue.PollOperation@5be9d2c5, com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this:Address[SERVER1]:5701, target:Address[SERVER2]:5701, partitionId: 199, replicaIndex: 0, operation: com.hazelcast.spi.impl.WaitNotifyServiceImpl$WaitingOp, service: hz:impl:queueService
» 12:41:05.080 Oct 01, 2014 9:41:13 AM com.hazelcast.spi.impl.WaitNotifyServiceImpl$WaitingOp
```

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #3754, #3395 and #8546
See commit messages for details. 

The newly added test works as a regression test for both changes - if you undo any of them then the test is occasionally failing. 

Thanks to @mdogan for his help with this issue.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/spi/impl/waitnotifyservice/impl/TestRecoveryAfterSplitBrain.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+import com.hazelcast.test.annotation.NightlyTest;
+import org.junit.experimental.categories.Category;
+import org.junit.runner.RunWith;
+
+import static com.hazelcast.test.HazelcastTestSupport.assertWaitingOperationCountEventually;
+import static com.hazelcast.test.HazelcastTestSupport.generateKeyOwnedBy;
+
+@RunWith(HazelcastSerialClassRunner.class)
+@Category(NightlyTest.class)
+public class TestRecoveryAfterSplitBrain extends SplitBrainTestSupport {
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/waitnotifyservice/impl/TestRecoveryAfterSplitBrain.java]: I'm going to rename this.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 2]
```diff
@@ -480,6 +481,8 @@ private void complete(Object value) {
     private void handleRetry(Object cause) {
         context.retryCount.inc();
 
+        context.logger.info("Retrying invocation: " + toString() + ", Reason: " + cause);
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: Info retry log? Isn't that going to be noisy?

File: hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java [hunk 3]
```diff
@@ -63,15 +63,14 @@ protected QueueOperation(String name, long timeoutMillis) {
...
-            }
+        QueueContainer queueContainer;
+        QueueService queueService = getService();
+        try {
+            queueContainer = queueService.getOrCreateContainer(name, this instanceof BackupOperation);
+        } catch (Exception e) {
+            throw new RetryableHazelcastException(e);
         }
-        return container;
+        return queueContainer;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java]: Flavor warning.

```
  protected final QueueContainer getOrCreateContainer() {
        QueueService queueService = getService();
        try {
            return queueService.getOrCreateContainer(name, this instanceof BackupOperation);
        } catch (Exception e) {
            throw new RetryableHazelcastException(e);
         }
         }
	}
```

To reduce the amount of horizontal noise.

File: hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java [hunk 4]
```diff
@@ -63,15 +63,14 @@ protected QueueOperation(String name, long timeoutMillis) {
...
-            try {
-                container = queueService.getOrCreateContainer(name, this instanceof BackupOperation);
-            } catch (Exception e) {
-                throw new RetryableHazelcastException(e);
-            }
+        QueueContainer queueContainer;
+        QueueService queueService = getService();
+        try {
+            queueContainer = queueService.getOrCreateContainer(name, this instanceof BackupOperation);
+        } catch (Exception e) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java]: The original code already does it; but do we want to retry on any exception? Imagine we have a NPE or a ClassNotFoundException. There is no point in retrying.

File: hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java [hunk 5]
```diff
@@ -99,6 +98,7 @@ public void afterRun() throws Exception {
 
     @Override
     public void beforeRun() throws Exception {
+        container = getOrCreateContainer();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java]: Could this container 'resetting' by an issue with other operations like Lock/CountdownLatch etc?

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: 1: Do we want to do this on info? Could generate a lot of noise.
2: I don't see a logging guard (could be that it is there; but this overview isn't showing it).

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: good one. it's a left-over from analysis/testing. thanks!

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 6]
```diff
@@ -494,10 +497,32 @@ private void handleRetry(Object cause) {
 
             if (invokeCount < MAX_FAST_INVOCATION_COUNT) {
                 // fast retry for the first few invocations
-                context.asyncExecutor.execute(this);
+                context.asyncExecutor.execute(new InvocationRetryTask());
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: Does this invocation still need to implement Runnable? I like the cleanup in the sense that I don't care about a bit of litter in case of retrying and now you responsibility from the invocation class.

File: hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java (hunk 4 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java]: I don't dare to change it in this PR. feel to send a new PR.

File: hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java (hunk 5 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/collection/impl/queue/operations/QueueOperation.java]: you are right, I'll have a look. 

by the way I'm about to push an update with slightly different logic. here is the idea:
1. in `beforeRun()` always initialises the `container` field
2. all other methods use `getContainer()` which just returns the content of the field.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 7]
```diff
@@ -314,6 +314,7 @@ boolean initInvocationTarget() {
         invTarget = getTarget();
 
         if (invTarget == null) {
+            context.logger.warning("Invocation target is null, completing invocations with error!");
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: Don't you want to provide some context, e.g. to toString of the invocation?

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: the log shouldn't be there at all. it's left-over from testing. thanks!

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java (hunk 6 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: good one. fixed.

**Comment by pveentjer** [comment]
Can you do a rename next time in a different pr? This makes it a lot easier to understand if something is a potential critical change, or just a automated code change.

**Comment by pveentjer** [comment]
:+1:

**Comment by jerrinot** [comment]
run-lab-run

**Comment by mdogan** [comment]
👍
