### PR TITLE
[HZ-1877] NoMigrationClusterStateTest.promotions_shouldHappen_whenMemberLeaves asserts fix

### LINKED ISSUE #19917: com.hazelcast.internal.cluster.impl.NoMigrationClusterStateTest.promotions_shouldHappen_whenMemberLeaves [HZ-1877]
_5.0.z_ (commit d9fb7bbbf1b5cb66567ba251f9fc51ec6e8aa65d)

Failed on Sonar: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-sonar/46/testReport/com.hazelcast.internal.cluster.impl/NoMigrationClusterStateTest/promotions_shouldHappen_whenMemberLeaves/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<5588425575302382289> but was:<-3578293097019783973>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.internal.cluster.impl.NoMigrationClusterStateTest.promotions_shouldHappen_whenMemberLeaves(NoMigrationClusterStateTest.java:103)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: rebalancing_shouldNotHappen_whenMemberLeaves in 39.571 seconds.
02:44:33,037  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers| - [HealthMonitor] hz.priceless_cannon.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=882.7M, heap.memory.free=284.3M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=75.60%, heap.memory.used/max=43.08%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=0.00%, load.system=100.00%, load.systemAverage=14.74, thread.count=1740, thread.peakCount=2726, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2183, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:33,341  INFO |lostPartitions_shouldBeAssigned_toNewMembers| - [HealthMonitor] hz.elegant_cannon.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=899.9M, heap.memory.free=267.1M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=77.00%, heap.memory.used/max=43.88%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=63.89%, load.system=100.00%, load.systemAverage=17.64, thread.count=1740, thread.peakCount=2726, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=7, executor.q.priorityOperation.size=0, operations.completed.count=1105, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=2, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:33,437  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers_whenMembersRemovedWhenClusterPASSIVE| - [HealthMonitor] hz.serene_cannon.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=904.1M, heap.memory.free=262.9M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=77.39%, heap.memory.used/max=44.10%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=50.00%, load.system=100.00%, load.systemAverage=17.64, thread.count=1740, thread.peakCount=2726, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=2, executor.q.priorityOperation.size=0, operations.completed.count=905, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:33,839  INFO |lostPartitions_shouldBeAssigned_toNewMembers| - [HealthMonitor] hz.hardcore_cannon.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=929.4M, heap.memory.free=237.6M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=78.87%, heap.memory.used/max=44.94%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=11.85%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-201, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1689, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:34,227  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers_whenMembersRemovedWhenClusterPASSIVE| - [HealthMonitor] hz.distracted_cannon.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=944.7M, heap.memory.free=222.3M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=80.85%, heap.memory.used/max=46.07%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=47.62%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-15, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=6, executor.q.priorityOperation.size=0, operations.completed.count=1297, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=2, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0

Metrics recorded during the test:
[angry_cannon] [02:44:16,841] [partitionId=17,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=28,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=39,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.runningPartitionCount]=0
[angry_cannon] [02:44:16,841] [unit=ns,metric=partitions.elapsedMigrationTime]=0
[angry_cannon] [02:44:16,841] [metric=runtime.usedMemory]=920539096
[angry_cannon] [02:44:16,841] [unit=ns,metric=partitions.totalElapsedMigrationTime]=0
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.maxHeap]=2147483648
[angry_cannon] [02:44:16,841] [partitionId=190,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [unit=ns,metric=partitions.totalElapsedMigrationOperationTime]=0
[angry_cannon] [02:44:16,841] [metric=os.processCpuTime]=28779300000000
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [partitionId=16,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=27,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=38,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=49,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedRunnableCount]=275
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedPacketCount]=269
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.totalCompletedMigrations]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [partitionId=19,unit=count,metric=operation.partition.executedOperationsCount]=21
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.runningGenericCount]=1
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedRunnableCount]=292
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedPacketCount]=259
[angry_cannon] [02:44:16,841] [metric=os.totalSwapSpaceSize]=4294963200
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [partitionId=29,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=18,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [unit=ms,metric=gc.minorTime]=51788
[angry_cannon] [02:44:16,841] [unit=count,metric=event.eventQueueSize]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedRunnableCount]=245
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=2
[angry_cannon] [02:44:16,841] [unit=boolean,metric=partitions.migrationActive]=1
[angry_cannon] [02:44:16,841] [unit=count,metric=client.endpoint.totalRegistrations]=0
[angry_cannon] [02:44:16,841] [metric=runtime.freeMemory]=301828384
[angry_cannon] [02:44:16,841] [unit=ms,metric=cluster.heartbeat.lastHeartbeat]=1636425853633
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [partitionId=13,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=24,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=35,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=46,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=57,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=68,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=79,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedRunnableCount]=320
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.invocations.delayedExecutionCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=event.syncDeliveryFailureCount]=0
[angry_cannon] [02:44:16,841] [unit=ms,metric=cluster.clock.clusterTimeDiff]=-127
[angry_cannon] [02:44:16,841] [unit=count,metric=proxy.createdCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [partitionId=12,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=23,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=34,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=45,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=56,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=67,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=78,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=89,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [unit=ms,metric=operation.invocations.heartbeatBroadcastPeriodMillis]=30000
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedRunnableCount]=211
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.totalPhysical]=405449981952
[angry_cannon] [02:44:16,841] [metric=os.systemLoadAverage]=16.31
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedRunnableCount]=0
[angry_cannon] [02:44:16,841] [metric=thread.totalStartedThreadCount]=632248
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [partitionId=15,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=26,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=37,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=48,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=59,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedRunnableCount]=291
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.queueSize]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.invocations.heartbeatPacketsSent]=1
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.replicaSyncRequestsCounter]=0
[angry_cannon] [02:44:16,841] [partitionId=14,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=25,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=36,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=47,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=58,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=69,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [metric=runtime.maxMemory]=2147483648
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.invocations.heartbeatPacketsReceived]=1
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=56
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedPacketCount]=3
[angry_cannon] [02:44:16,841] [metric=os.processCpuLoad]=25.0
[angry_cannon] [02:44:16,841] [genericId=4,unit=count,metric=operation.generic.executedOperationsCount]=4
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedRunnableCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedPacketCount]=321
[angry_cannon] [02:44:16,841] [partitionId=263,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=252,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=241,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=230,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[angry_cannon] [02:44:16,841] [partitionId=120,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=131,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=142,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=153,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=164,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=175,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=186,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=197,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.normalPendingCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=raft.missingMembers]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=58
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedPacketCount]=2
[angry_cannon] [02:44:16,841] [genericId=3,unit=count,metric=operation.generic.executedOperationsCount]=3
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedRunnableCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedPacketCount]=285
[angry_cannon] [02:44:16,841] [partitionId=264,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=253,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=242,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=231,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=220,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=198,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[angry_cannon] [02:44:16,841] [partitionId=110,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=121,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=132,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=143,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=154,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=165,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=176,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=187,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [metric=thread.peakThreadCount]=2726
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.maxBackupCount]=1
[angry_cannon] [02:44:16,841] [unit=ms,metric=operation.invocations.invocationTimeoutMillis]=120000
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=58
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedPacketCount]=5
[angry_cannon] [02:44:16,841] [metric=runtime.totalMemory]=1223688192
[angry_cannon] [02:44:16,841] [unit=ms,metric=operation.invocations.backupTimeoutMillis]=5000
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedRunnableCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.responses.errorCount]=0
[angry_cannon] [02:44:16,841] [service=hz:core:proxyService,unit=count,metric=event.listenerCount]=2
[angry_cannon] [02:44:16,841] [partitionId=140,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=151,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=162,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=173,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=184,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=195,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=250,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=261,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.freePhysical]=201352282112
[angry_cannon] [02:44:16,841] [unit=ns,metric=partitions.totalElapsedDestinationCommitTime]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.responses.timeoutCount]=0
[angry_cannon] [02:44:16,841] [partitionId=0,unit=count,metric=operation.partition.executedOperationsCount]=21
[angry_cannon] [02:44:16,841] [metric=os.openFileDescriptorCount]=624
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.invocations.backupTimeouts]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [unit=count,metric=transactions.startCount]=0
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.usedMetadata]=0
[angry_cannon] [02:44:16,841] [unit=ms,metric=partitions.lastRepartitionTime]=0
[angry_cannon] [02:44:16,841] [partitionId=262,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=130,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=141,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=152,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=163,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=174,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=185,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=196,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=240,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=251,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=event.eventsProcessed]=388
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.parker.parkQueueCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.responses.normalCount]=183
[angry_cannon] [02:44:16,841] [unit=count,metric=client.endpoint.count]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedPacketCount]=302
[angry_cannon] [02:44:16,841] [partitionId=160,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=171,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=182,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=193,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=270,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [unit=ms,metric=gc.majorTime]=568
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.runningCount]=1
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [metric=classloading.loadedClassesCount]=83847
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedPacketCount]=271
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedPacketCount]=17
[angry_cannon] [02:44:16,841] [partitionId=150,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=161,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=172,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=183,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=194,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=260,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [metric=os.maxFileDescriptorCount]=120000
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedPacketCount]=292
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.plannedMigrations]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[angry_cannon] [02:44:16,841] [partitionId=180,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=191,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [unit=count,metric=proxy.destroyedCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.operationTimeoutCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedPacketCount]=4
[angry_cannon] [02:44:16,841] [unit=count,metric=transactions.rollbackCount]=0
[angry_cannon] [02:44:16,841] [metric=runtime.uptime]=9972695
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedPacketCount]=284
[angry_cannon] [02:44:16,841] [unit=count,metric=raft.nodes]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[angry_cannon] [02:44:16,841] [partitionId=170,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=181,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=192,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.priorityPendingCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.stateStamp]=-7163830008390872202
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.usedHeap]=932785640
[angry_cannon] [02:44:16,841] [metric=classloading.totalLoadedClassesCount]=104919
[angry_cannon] [02:44:16,841] [unit=ns,metric=partitions.elapsedDestinationCommitTime]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.genericQueueSize]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.replicaSyncSemaphore]=10
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.genericThreadCount]=5
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedOperationCount]=8
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.completedCount]=2405
[angry_cannon] [02:44:16,841] [partitionId=106,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=117,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=128,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=139,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=205,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=216,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=227,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=238,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=249,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=0
[angry_cannon] [02:44:16,841] [partitionId=6,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.adhoc.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [metric=classloading.unloadedClassesCount]=21072
[angry_cannon] [02:44:16,841] [metric=os.committedVirtualMemorySize]=44855549952
[angry_cannon] [02:44:16,841] [unit=count,metric=partitions.migrationQueueSize]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=event.threadCount]=5
[angry_cannon] [02:44:16,841] [unit=ms,metric=cluster.clock.maxClusterTimeDiff]=-127
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedOperationCount]=6
[angry_cannon] [02:44:16,841] [partitionId=107,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=118,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=129,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=206,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=217,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=228,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=239,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.committedHeap]=1223688192
[angry_cannon] [02:44:16,841] [unit=count,metric=raft.terminatedRaftNodeGroupIds]=0
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.freeHeap]=290629744
[angry_cannon] [02:44:16,841] [partitionId=5,unit=count,metric=operation.partition.executedOperationsCount]=21
[angry_cannon] [02:44:16,841] [metric=os.freePhysicalMemorySize]=201352282112
[angry_cannon] [02:44:16,841] [unit=count,metric=event.totalFailureCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedOperationBatchCount]=20
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedOperationCount]=12
[angry_cannon] [02:44:16,841] [partitionId=269,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=258,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=247,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=236,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=104,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=115,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=126,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=137,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=148,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=159,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=203,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=214,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=225,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [unit=ms,metric=operation.invocations.invocationScanPeriodMillis]=1000
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.responses.backupCount]=0
[angry_cannon] [02:44:16,841] [partitionId=80,unit=count,metric=operation.partition.executedOperationsCount]=20
[angry_cannon] [02:44:16,841] [partitionId=91,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=8,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=47
[angry_cannon] [02:44:16,841] [unit=count,metric=raft.metadata.activeMembersCommitIndex]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.asyncOperations]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedOperationCount]=22
[angry_cannon] [02:44:16,841] [partitionId=259,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=248,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=105,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=116,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=127,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=138,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=149,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=204,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=215,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=226,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=237,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=90,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=7,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [service=hz:core:clusterService,unit=count,metric=event.publicationCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=54
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.callTimeoutCount]=0
[angry_cannon] [02:44:16,841] [genericId=0,unit=count,metric=operation.generic.executedOperationsCount]=22
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=10
[angry_cannon] [02:44:16,841] [partitionId=267,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=256,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=245,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=234,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=223,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=212,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=102,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=113,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=124,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=135,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=146,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=157,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=168,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=179,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=201,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=2,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.errorCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=62
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.responses.missingCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedOperationCount]=12
[angry_cannon] [02:44:16,841] [unit=count,metric=raft.metadata.groups]=0
[angry_cannon] [02:44:16,841] [partitionId=268,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=257,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=246,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=235,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=224,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=103,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=114,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=125,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=136,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=147,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=158,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=169,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=202,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=213,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedOperationCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.retryCount]=0
[angry_cannon] [02:44:16,841] [partitionId=1,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=52
[angry_cannon] [02:44:16,841] [unit=bytes,metric=memory.maxNative]=0
[angry_cannon] [02:44:16,841] [unit=percent,metric=operation.invocations.usedPercentage]=0.0
[angry_cannon] [02:44:16,841] [genericId=2,unit=count,metric=operation.generic.executedOperationsCount]=2
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedOperationCount]=8
[angry_cannon] [02:44:16,841] [service=hz:core:proxyService,unit=count,metric=event.publicationCount]=0
[angry_cannon] [02:44:16,841] [partitionId=265,unit=count,metric=operation.partition.executedOperationsCount]=17
[angry_cannon] [02:44:16,841] [partitionId=254,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=243,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=232,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=221,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=210,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=199,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=100,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=111,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=122,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=133,unit=count,metric=operation.partition.executedOperationsCount]=19
[angry_cannon] [02:44:16,841] [partitionId=144,unit=count,metric=operation.partition.executedOperationsCount]=8
[angry_cannon] [02:44:16,841] [partitionId=155,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [partitionId=166,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [partitionId=177,unit=count,metric=operation.partition.executedOperationsCount]=18
[angry_cannon] [02:44:16,841] [partitionId=188,unit=count,metric=operation.partition.executedOperationsCount]=7
[angry_cannon] [02:44:16,841] [unit=ms,metric=gc.unknownTime]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedOperationCount]=0
[angry_cannon] [02:44:16,841] [partitionId=4,unit=count,metric=operation.partition.executedOperationsCount]=0
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=64
[angry_cannon] [02:44:16,841] [unit=ms,metric=cluster.clock.clusterUpTime]=23821
[angry_cannon] [02:44:16,841] [genericId=1,unit=count,metric=operation.generic.executedOperationsCount]=5
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[angry_cannon] [02:44:16,841] [service=hz:core:clusterService,unit=count,metric=event.listenerCount]=1
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedRunnableCount]=0
[angry_cannon] [02:44:16,841] [unit=count,metric=operation.partitionThreadCount]=8
[angry_cannon] [02:44:16,841] [thread=hz.angry_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedOperationCount]=8
[angry_cannon] [02:44:16,841] [metric=thread.threadCount]=1
...[truncated 1714184 chars]...
rtition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=228,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=239,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedRunnableCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.committedHeap]=1223688192
[boring_cannon] [02:43:59,129] [unit=count,metric=raft.terminatedRaftNodeGroupIds]=0
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.freeHeap]=300571096
[boring_cannon] [02:43:59,129] [partitionId=5,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [metric=os.freePhysicalMemorySize]=201372184576
[boring_cannon] [02:43:59,129] [unit=count,metric=event.totalFailureCount]=0
[boring_cannon] [02:43:59,129] [partitionId=269,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=258,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=247,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=236,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=104,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=115,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=126,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=137,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=148,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=159,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=203,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=214,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=225,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedRunnableCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [unit=ms,metric=operation.invocations.invocationScanPeriodMillis]=1000
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.responses.backupCount]=0
[boring_cannon] [02:43:59,129] [partitionId=80,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=91,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=8,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=raft.metadata.activeMembersCommitIndex]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.asyncOperations]=0
[boring_cannon] [02:43:59,129] [partitionId=259,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=248,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=105,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=116,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=127,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=138,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=149,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=204,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=215,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=226,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=237,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedRunnableCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [partitionId=90,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=7,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [service=hz:core:clusterService,unit=count,metric=event.publicationCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=32
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.callTimeoutCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedTotalCount]=125
[boring_cannon] [02:43:59,129] [genericId=0,unit=count,metric=operation.generic.executedOperationsCount]=13
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [partitionId=267,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=256,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=245,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=234,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=223,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=212,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=201,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [partitionId=102,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=113,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=124,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=135,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=146,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=157,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=168,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=179,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedRunnableCount]=0
[boring_cannon] [02:43:59,129] [partitionId=2,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedPacketCount]=6
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedTotalCount]=122
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.responses.missingCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [unit=count,metric=raft.metadata.groups]=0
[boring_cannon] [02:43:59,129] [partitionId=268,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=257,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=246,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=235,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=224,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=213,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [partitionId=103,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=114,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=125,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=136,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=147,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=158,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=169,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=202,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.retryCount]=0
[boring_cannon] [02:43:59,129] [partitionId=1,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedPacketCount]=1
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.maxNative]=0
[boring_cannon] [02:43:59,129] [unit=percent,metric=operation.invocations.usedPercentage]=0.0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedTotalCount]=119
[boring_cannon] [02:43:59,129] [genericId=2,unit=count,metric=operation.generic.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [service=hz:core:proxyService,unit=count,metric=event.publicationCount]=0
[boring_cannon] [02:43:59,129] [partitionId=265,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=254,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=243,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=232,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=221,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=210,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=199,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=188,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [partitionId=100,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=111,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=122,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=133,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=144,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=155,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=166,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=177,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [unit=ms,metric=gc.unknownTime]=0
[boring_cannon] [02:43:59,129] [partitionId=4,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-0,unit=count,metric=operation.thread.completedPacketCount]=5
[boring_cannon] [02:43:59,129] [unit=ms,metric=cluster.clock.clusterUpTime]=6028
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedTotalCount]=106
[boring_cannon] [02:43:59,129] [genericId=1,unit=count,metric=operation.generic.executedOperationsCount]=5
[boring_cannon] [02:43:59,129] [service=hz:core:clusterService,unit=count,metric=event.listenerCount]=1
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.partitionThreadCount]=8
[boring_cannon] [02:43:59,129] [metric=thread.threadCount]=1991
[boring_cannon] [02:43:59,129] [partitionId=266,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=255,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=244,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=233,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=222,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=211,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=200,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=101,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=112,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=123,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=134,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=145,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=156,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=167,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=178,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=189,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [unit=count,metric=partitions.partitionCount]=271
[boring_cannon] [02:43:59,129] [partitionId=3,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedRunnableCount]=64
[boring_cannon] [02:43:59,129] [service=hz:core:partitionService,unit=count,metric=event.publicationCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedPacketCount]=37
[boring_cannon] [02:43:59,129] [metric=thread.daemonThreadCount]=1530
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=14
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.freeNative]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=cluster.size]=3
[boring_cannon] [02:43:59,129] [unit=count,metric=event.rejectedCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-3,unit=count,metric=operation.thread.completedTotalCount]=3
[boring_cannon] [02:43:59,129] [partitionId=20,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=31,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=42,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=53,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=64,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=75,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=86,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=97,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedRunnableCount]=40
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedPacketCount]=50
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=30
[boring_cannon] [02:43:59,129] [dir=user.home,unit=bytes,metric=file.partition.freeSpace]=14389190656
[boring_cannon] [02:43:59,129] [unit=ms,metric=cluster.clock.localClockTime]=1636425839046
[boring_cannon] [02:43:59,129] [unit=count,metric=gc.majorCount]=2
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [partitionId=30,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=41,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=52,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=63,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=74,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=85,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=96,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.priorityQueueSize]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=16
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [unit=count,metric=proxy.proxyCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [partitionId=99,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-1,unit=count,metric=operation.thread.completedTotalCount]=1
[boring_cannon] [02:43:59,129] [partitionId=11,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=22,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=33,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=44,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=55,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=66,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=77,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=88,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.committedNative]=0
[boring_cannon] [02:43:59,129] [unit=ns,metric=partitions.elapsedMigrationOperationTime]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=20
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.genericPriorityQueueSize]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=gc.minorCount]=5837
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-6,unit=count,metric=operation.thread.completedOperationBatchCount]=4
[boring_cannon] [02:43:59,129] [metric=os.freeSwapSpaceSize]=4294963200
[boring_cannon] [02:43:59,129] [metric=os.totalPhysicalMemorySize]=405449981952
[boring_cannon] [02:43:59,129] [metric=os.systemCpuLoad]=100.0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [metric=runtime.availableProcessors]=8
[boring_cannon] [02:43:59,129] [partitionId=98,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.generic-operation.thread-2,unit=count,metric=operation.thread.completedTotalCount]=6
[boring_cannon] [02:43:59,129] [partitionId=10,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=21,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=32,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=43,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=54,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=65,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=76,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=87,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedRunnableCount]=28
[boring_cannon] [02:43:59,129] [unit=count,metric=gc.unknownCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.responseQueueSize]=0
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.maxMetadata]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.parker.totalParkedOperationCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=partitions.localPartitionCount]=91
[boring_cannon] [02:43:59,129] [partitionId=209,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [partitionId=60,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=71,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=82,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=93,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedRunnableCount]=44
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=24
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.invocations.lastCallId]=195
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=transactions.commitCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=raft.destroyedGroupIds]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=partitions.activePartitionCount]=91
[boring_cannon] [02:43:59,129] [partitionId=70,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=81,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=92,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=9,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [service=hz:core:partitionService,unit=count,metric=event.listenerCount]=9
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.invocations.pending]=0
[boring_cannon] [02:43:59,129] [unit=bytes,metric=memory.usedNative]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-5,unit=count,metric=operation.thread.completedRunnableCount]=32
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-1,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=24
[boring_cannon] [02:43:59,129] [dir=user.home,unit=bytes,metric=file.partition.totalSpace]=21460156416
[boring_cannon] [02:43:59,129] [unit=ms,metric=cluster.clock.clusterStartTime]=1636425833016
[boring_cannon] [02:43:59,129] [unit=ms,metric=cluster.clock.clusterTime]=1636425839051
[boring_cannon] [02:43:59,129] [partitionId=108,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=119,unit=count,metric=operation.partition.executedOperationsCount]=2
[boring_cannon] [02:43:59,129] [partitionId=207,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=218,unit=count,metric=operation.partition.executedOperationsCount]=1
[boring_cannon] [02:43:59,129] [partitionId=229,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-3,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [dir=user.home,unit=bytes,metric=file.partition.usableSpace]=14389190656
[boring_cannon] [02:43:59,129] [partitionId=40,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=51,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=62,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=73,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=84,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=95,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.invocations.normalTimeouts]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=raft.metadata.activeMembers]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=operation.failedBackups]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=partitions.memberGroupsSize]=3
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-4,unit=count,metric=operation.thread.completedRunnableCount]=60
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=22
[boring_cannon] [02:43:59,129] [unit=count,metric=event.queueCapacity]=1000000
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.priority-generic-operation.thread-0,unit=count,metric=operation.thread.errorCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-7,unit=count,metric=operation.thread.priorityPendingCount]=0
[boring_cannon] [02:43:59,129] [partitionId=109,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=208,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=219,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [thread=hz.boring_cannon.partition-operation.thread-2,unit=count,metric=operation.thread.completedOperationCount]=0
[boring_cannon] [02:43:59,129] [unit=count,metric=partitions.completedMigrations]=0
[boring_cannon] [02:43:59,129] [partitionId=50,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [partitionId=61,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=72,unit=count,metric=operation.partition.executedOperationsCount]=4
[boring_cannon] [02:43:59,129] [partitionId=83,unit=count,metric=operation.partition.executedOperationsCount]=0
[boring_cannon] [02:43:59,129] [partitionId=94,unit=count,metric=operation.partition.executedOperationsCount]=3
[boring_cannon] [02:43:59,129] [name=hz:cluster,unit=count,metric=executor.internal.maximumPoolSize]=2
[boring_cannon] [02:43:59,129] [name=hz:cluster,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster,unit=count,metric=executor.internal.completedTasks]=1
[boring_cannon] [02:43:59,129] [name=hz:cluster,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:cluster:event,unit=count,metric=executor.internal.maximumPoolSize]=1
[boring_cannon] [02:43:59,129] [name=hz:cluster:event,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:event,unit=count,metric=executor.internal.completedTasks]=18
[boring_cannon] [02:43:59,129] [name=hz:cluster:event,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:event,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:offloadable,unit=count,metric=executor.internal.maximumPoolSize]=8
[boring_cannon] [02:43:59,129] [name=hz:offloadable,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:offloadable,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:offloadable,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:offloadable,unit=count,metric=executor.internal.remainingQueueCapacity]=100000
[boring_cannon] [02:43:59,129] [name=hz:client,unit=count,metric=executor.internal.maximumPoolSize]=8
[boring_cannon] [02:43:59,129] [name=hz:client,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:client,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:client,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:client,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[boring_cannon] [02:43:59,129] [name=hz:cluster:mastership,unit=count,metric=executor.internal.maximumPoolSize]=1
[boring_cannon] [02:43:59,129] [name=hz:cluster:mastership,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:mastership,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:mastership,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:mastership,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:async,unit=count,metric=executor.internal.maximumPoolSize]=8
[boring_cannon] [02:43:59,129] [name=hz:async,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:async,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:async,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:async,unit=count,metric=executor.internal.remainingQueueCapacity]=100000
[boring_cannon] [02:43:59,129] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.maximumPoolSize]=160
[boring_cannon] [02:43:59,129] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[boring_cannon] [02:43:59,129] [name=hz:mc,unit=count,metric=executor.internal.maximumPoolSize]=2
[boring_cannon] [02:43:59,129] [name=hz:mc,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:mc,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:mc,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:mc,unit=count,metric=executor.internal.remainingQueueCapacity]=2000
[boring_cannon] [02:43:59,129] [name=hz:client-query,unit=count,metric=executor.internal.maximumPoolSize]=8
[boring_cannon] [02:43:59,129] [name=hz:client-query,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:client-query,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:client-query,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:client-query,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[boring_cannon] [02:43:59,129] [name=hz:scheduled,unit=count,metric=executor.internal.maximumPoolSize]=16
[boring_cannon] [02:43:59,129] [name=hz:scheduled,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:scheduled,unit=count,metric=executor.internal.completedTasks]=101
[boring_cannon] [02:43:59,129] [name=hz:scheduled,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:scheduled,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[boring_cannon] [02:43:59,129] [name=hz:system,unit=count,metric=executor.internal.maximumPoolSize]=8
[boring_cannon] [02:43:59,129] [name=hz:system,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:system,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:system,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:system,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=MetricsPublisher,unit=count,metric=executor.internal.maximumPoolSize]=16
[boring_cannon] [02:43:59,129] [name=MetricsPublisher,unit=count,metric=executor.internal.poolSize]=1
[boring_cannon] [02:43:59,129] [name=MetricsPublisher,unit=count,metric=executor.internal.completedTasks]=5
[boring_cannon] [02:43:59,129] [name=MetricsPublisher,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=MetricsPublisher,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.maximumPoolSize]=2
[boring_cannon] [02:43:59,129] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.maximumPoolSize]=1
[boring_cannon] [02:43:59,129] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:query,unit=count,metric=executor.internal.maximumPoolSize]=16
[boring_cannon] [02:43:59,129] [name=hz:query,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:query,unit=count,metric=executor.internal.completedTasks]=0
[boring_cannon] [02:43:59,129] [name=hz:query,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:query,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.maximumPoolSize]=16
[boring_cannon] [02:43:59,129] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.completedTasks]=9
[boring_cannon] [02:43:59,129] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[boring_cannon] [02:43:59,129] [name=hz:scheduled:cqc:f3451b1f-0523-45fa-9324-163a4287bc11,unit=count,metric=executor.internal.maximumPoolSize]=1
[boring_cannon] [02:43:59,129] [name=hz:scheduled:cqc:f3451b1f-0523-45fa-9324-163a4287bc11,unit=count,metric=executor.internal.poolSize]=0
[boring_cannon] [02:43:59,129] [name=hz:scheduled:cqc:f3451b1f-0523-45fa-9324-163a4287bc11,unit=count,metric=executor.internal.completedTasks]=2
[boring_cannon] [02:43:59,129] [name=hz:scheduled:cqc:f3451b1f-0523-45fa-9324-163a4287bc11,unit=count,metric=executor.internal.queueSize]=0
[boring_cannon] [02:43:59,129] [name=hz:scheduled:cqc:f3451b1f-0523-45fa-9324-163a4287bc11,unit=count,metric=executor.internal.remainingQueueCapacity]=10000

02:44:35,026  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers| - [HealthMonitor] hz.musing_cannon.HealthMonitor - [127.0.0.1]:5704 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1005.8M, heap.memory.free=161.2M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=86.15%, heap.memory.used/max=49.09%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=0.66%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-3, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=4, executor.q.priorityOperation.size=0, operations.completed.count=2451, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:35,033  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers_whenMembersRemovedWhenClusterPASSIVE| - [HealthMonitor] hz.crazy_cannon.HealthMonitor - [127.0.0.1]:5703 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1006.3M, heap.memory.free=160.7M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=86.13%, heap.memory.used/max=49.08%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=76.92%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-3, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1281, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:35,031  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers| - [HealthMonitor] hz.confident_cannon.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1005.8M, heap.memory.free=161.2M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=86.04%, heap.memory.used/max=49.03%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=78.57%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-15, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=10, executor.q.priorityOperation.size=0, operations.completed.count=2413, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=2, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:35,029  INFO |rebalancing_shouldHappen_whenStateBecomesActive| - [HealthMonitor] hz.flamboyant_cannon.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1004.8M, heap.memory.free=162.2M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=86.06%, heap.memory.used/max=49.04%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=75.00%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=4808, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:35,040  INFO |lostPartitions_shouldBeAssigned_toAvailableMembers| - [HealthMonitor] hz.mystifying_cannon.HealthMonitor - [127.0.0.1]:5703 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1010.5M, heap.memory.free=156.5M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=85.70%, heap.memory.used/max=48.83%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=65.00%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-4, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=3, executor.q.priorityOperation.size=0, operations.completed.count=2382, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:35,137  INFO |rebalancing_shouldHappen_whenStateBecomesActive| - [HealthMonitor] hz.blissful_cannon.HealthMonitor - [127.0.0.1]:5703 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1015.3M, heap.memory.free=151.7M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=86.91%, heap.memory.used/max=49.53%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=100.00%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=4999, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:44:35,441  INFO |lostPartitions_shouldBeAssigned_toNewMembers| - [HealthMonitor] hz.silly_cannon.HealthMonitor - [127.0.0.1]:5703 [dev] [5.0.1-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=187.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=1.0G, heap.memory.free=137.2M, heap.memory.total=1.1G, heap.memory.max=2.0G, heap.memory.used/total=88.20%, heap.memory.used/max=50.26%, minor.gc.count=5844, minor.gc.time=51906ms, major.gc.count=2, major.gc.time=568ms, load.process=70.00%, load.system=100.00%, load.systemAverage=17.64, thread.count=1742, thread.peakCount=2726, cluster.timeDiff=-10, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=1, executor.q.priorityOperation.size=0, operations.completed.count=1849, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=1, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
```

</details>

### PR DESCRIPTION
**Pull request by ivanthescientist**
Potentially fixes #19917

Asserts currently do not account for further changes to the partition table post assignment of replicas/pruning of invalid replicas.

### CODE REVIEW

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/NoMigrationClusterStateTest.java [hunk 1]
```diff
@@ -100,8 +100,10 @@ public void promotions_shouldHappen_whenMemberLeaves() {
         assertClusterSizeEventually(2, instances[2]);
         assertAllPartitionsAreAssigned(instances[2], 1);
 
-        assertEquals(getPartitionService(instances[1]).getPartitionStateStamp(),
-                getPartitionService(instances[2]).getPartitionStateStamp());
+        assertTrueEventually(() -> {
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/NoMigrationClusterStateTest.java:103]: alternatively you could `waitForClusterSafe` to ensure promotions are done before the assertion, but eventual assertion will work as well
