### PR TITLE
Fix ClientMapNearCacheTest to start the instances before the client listener registration

### LINKED ISSUE #10024: ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member
```
java.lang.AssertionError: Expecting only 1 clear event expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest$29.run(ClientMapNearCacheTest.java:1053)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:967)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:984)
	at com.hazelcast.client.map.impl.nearcache.ClientMapNearCacheTest.receives_one_clearEvent_after_mapEvictAll_call_from_member(ClientMapNearCacheTest.java:1050)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-freestyle/134/testReport/junit/com.hazelcast.client.map.impl.nearcache/ClientMapNearCacheTest/receives_one_clearEvent_after_mapEvictAll_call_from_member_batchInvalidationEnabled_false_/

possibly related to #9940

### PR DESCRIPTION
**Pull request by ihsandemir**
Initialises the members before the client initialisation and invalidation listener registration so that the test does not fail due to the scenario described at https://github.com/hazelcast/hazelcast/issues/10024#issuecomment-306776701 .

Also, changed some tests to run with two instances instead of one so that it tests better the case where only one invalidation event is received.

fixes #10024

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java [hunk 1]
```diff
@@ -911,48 +911,50 @@ public void receives_one_clearEvent_after_mapClear_call_from_client() {
         IMap<Object, Object> anotherClientMap = anotherClient.getMap(clientMap.getName());
         anotherClientMap.clear();
 
-        // sleep for a while to see there is another clear event coming
-        sleepSeconds(2);
-
         assertTrueEventually(new AssertTask() {
```
Comment (ahmetmircik) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java]: seems this assertion is redundant

Comment (sancar) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java]: Could not assertTrueAllTheTime fail without this check ?

Comment (ahmetmircik) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java]: Two assertions makes it hard to aware what is being tested. We can introduce 2 test instead if two assertions are needed. 

Also you are right, `assertTrueAllTheTime` was confused me.

Comment (ihsandemir) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java]: OK, added nightly versions of the tests as well.

File: hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java [hunk 2]
```diff
@@ -83,6 +84,9 @@
 
     protected final TestHazelcastFactory hazelcastFactory = new TestHazelcastFactory();
 
+    private static final Random rand = new Random();
```
Comment (Donnerbart) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java]: `Random` should not be static (and if an UPPERCASE name should be used). Would be better to make it a normal final field, so each test gets its own random generator.

Comment (ihsandemir) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/nearcache/ClientMapNearCacheTest.java]: Ok, removed Random :)
