### PR TITLE
Reset write behind store on clear [HZ-1671] 

### LINKED ISSUE #22601: Issues with Map in 5.2.0 [HZ-1671]
**Describe the bug**
In version 5.2.0, for Maps with Loader configured, `map.set` will now trigger the loader's `load`.
Also, _clearing_ the map does not actually remove an entry that was set.

**Expected behavior**
I expected Map to behave similarly to version 5.1.x and earlier, where:
- `map.set` does not trigger the loader.
- `map.clear` removes all entries, requesting a key that existed before (but the loader cannot find it) returns null

**To Reproduce**
The following small app demonstrates the issues with map in version 5.2.0
Running it with version 5.1.4 works exactly as expected.

```java
public class App {
    public static class MyLoader implements MapLoader<String, String> {
        @Override
        public String load(String key) {
            System.out.println("Load request: " + key);
            return null;
        }

        @Override
        public Map<String, String> loadAll(Collection<String> keys) {
            throw new RuntimeException("loadAll request:" + keys);
        }

        @Override
        public Iterable<String> loadAllKeys() {
            return null;
        }
    }

    public static void main(String[] args) throws IOException {
        var config = new Config();
        config.getNetworkConfig().getInterfaces().setEnabled(false).clear();
        config.getUserCodeDeploymentConfig().setEnabled(true);
        var jc = config.getNetworkConfig().getJoin();
        jc.getMulticastConfig().setEnabled(false);
        jc.getAwsConfig().setEnabled(false);
        jc.getTcpIpConfig().setEnabled(true).setMembers(List.of("127.0.0.1"))
                .setConnectionTimeoutSeconds(1);
        config.addMapConfig(new MapConfig("*").setBackupCount(0).setAsyncBackupCount(0));
        config.addMapConfig(new MapConfig("TestMap")
                .setMapStoreConfig(new MapStoreConfig()
                        .setClassName(MyLoader.class.getName())
                        .setWriteDelaySeconds(10)
                        .setWriteBatchSize(100)
                        .setWriteCoalescing(true)
                        .setInitialLoadMode(MapStoreConfig.InitialLoadMode.LAZY))
                .setEvictionConfig(new EvictionConfig()
                        .setEvictionPolicy(EvictionPolicy.LRU)
                        .setSize(500)
                        .setMaxSizePolicy(MaxSizePolicy.PER_NODE))
                .setMaxIdleSeconds(60)
                .setBackupCount(0).setAsyncBackupCount(0)
        );
        try {
            var hz = Hazelcast.newHazelcastInstance(config);
            IMap<String, String> map = hz.getMap("TestMap");
            System.out.println("just setting value, not expecting a load");
            map.set("test", "tost");

            System.out.println("clearing map");
            map.clear();

            System.out.println("getting back test value");
            var value = map.get("test");
            System.out.println("value is:" + value);

        } finally {
            System.out.println("stopping");
            Hazelcast.shutdownAll();
        }
    }
}
```

**Additional context**
Output when running with version 5.1.4:
```
just setting value, not expecting a load
clearing map
getting back test value
Load request: test
value is:null
stopping
```

Output when running with version 5.2.0:
```
just setting value, not expecting a load
Load request: test
clearing map
getting back test value
value is:tost
stopping
```

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes #22601

Added missing reset to align behavior with not-offloaded clear op.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/writebehind/MapStoreWriteBehindTest.java [hunk 1]
```diff
@@ -576,6 +576,36 @@ public void testDelete_thenPutIfAbsent_withWriteBehindEnabled() {
...
+        final int keyCount = 1_000;
+
+        for (int i = 0; i < keyCount; i++) {
+            map.set(i, i);
+        }
+
+        map.clear();
+
+        for (int i = 0; i < keyCount; i++) {
+            map.get(i);
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/writebehind/MapStoreWriteBehindTest.java:596]: you could add an assertion that values obtained from `get` are `null` here

Comment (ahmetmircik) [reply hazelcast/src/test/java/com/hazelcast/map/impl/mapstore/writebehind/MapStoreWriteBehindTest.java:596]: i think null is not required, any value which is loaded by map-loader is ok.

**Review by vbekiaris — APPROVED** [review]

**Review by frant-hartm — APPROVED** [review]

**Comment by ahmetmircik** [comment]
run-lab-run
