### PR TITLE
[API-1356] Check for the minimum size of the bytes read only once per frame

### LINKED ISSUE #21498: ClientMessage frame read for a message may be broken in case of large messages [HZ-1200]
Please see [this](https://github.com/hazelcast/hazelcast/blob/v5.1.1/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientMessageReader.java#L68) line of code.

The ClientMessageReader is basically copying data from one buffer to another buffer.
The source buffer (src in the code) is bytes received directly from the client socket connection.
The destination buffer is an application byte[] , which is wrapped inside an object called ClientMessage.
(Its actually slight more complex ... ClientMessage has multiple buffers called Frames, and within ClientMessage there is a linked list of Frames, each Frame has its own byte[])

There is an important variable called readOffset; this denotes the offset in the current destination buffer where we should put the next set of bytes.
-1 is the initial state meaning no data has been copied yet. The reason that readOffset is a member variable is because the class is stateful and the main readFrom method in the class is called in a loop.
This is important to understand , so here is an example ... we might invoke the readFrom method with 25,000 bytes in the src buffer. Within the readFrom method,  we might derive the overall expected length of the frame is 75,000 bytes. The code will still copy the available 25,000 bytes from the src into the destination buffer, and it will set the readOffset to 25,000. The method will then complete and return false (false == 'incomplete').
Then on the next iteration/call to readFrom , we might have 30,000 new bytes in the src. Again it will copy those bytes into the destination (starting at the readOffset 25,000), then it will bump the readOffset pointer forward to 55,000, and so on and so on ... until it receives the full frame of 75,000 bytes.
Once a frame is full (i.e. we have copied the number of bytes specified in the frame header) , the code will start populating a new frame.
Once a frame is full and it is flagged as IS_FINAL_FLAG = true .. that whole ClientMessage is complete, and the readFrom will return true .

Setup for error:

We have large messages being sent from client to server therefore they tend to span fairly large number of tcp packets.
We also have data being sent from cloud to onprem ... so sometimes those tcp packets can be a few micros apart.
This leads to plenty of occurrences where readFrom is invoked when the src buffer does not have the entire dataset (frame) available. And thus our larger messages are often built up iteratively as described above. That generally works well ... apart from 1 case ..
Sometimes when readFrom is called, the src buffer has the data needed to complete the destination message except the last few bytes of the final frame (5 bytes say).
So, we process as described above what we have, and create an almost complete ClientMessage in memory in ClientMessageReader. Then micros later the remaining data becomes available in the src buffer, and we can append that by another call to readFrom. So that is invoked .. but it hits this check ...

int remaining = src.remaining(); 
if (remaining < SIZE_OF_FRAME_LENGTH_AND_FLAGS) {
  // we don't have even the frame length and flags ready    
  return false;    
}

which won't read the src buffer if its size is less that 6 bytes.

So, then we can't complete the frame / message because the residual part is too small to pass through the above check.
The connection then stays in that state, until at some point later, something else is received in the src buffer (typically a hearbeat). At that point we get through this guard because the buffer exceeds the minimum size, and we can process the 5 bytes that have been sat there waiting (and the heartbeat).

I think the above check should only occur when we are at the beginning of frames i.e. just moved down to iinside the

if (readOffset == -1) {

block.

### PR DESCRIPTION
**Pull request by mdumandag**
Before this fix, while reading a message frame, we were mistakenly
checking that the bytes we haven't read yet are less than 6 bytes
each time the `ClientMessageReader#readFrame` is called.

This is problematic for frames that are read in multiple calls,
as the size of the last piece of the frame we are reading might be
actually less than 6 bytes and that is definitely valid. However,
in that case, we were not able to read the remaining part and
continue.

This PR aims to fix this problem by having that check only at the
beginning for each frame, only once per frame. Once we read the frame
length and flags, we will be able to read any number of bytes no
matter how small it is.

Closes #21498

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientMessageReader.java [hunk 1]
```diff
@@ -63,13 +63,15 @@ public void reset() {
...
-            // we don't have even the frame length and flags ready
-            return false;
-        }
         if (readOffset == -1) {
+            // Check for the minimum buffer size only if we
+            // haven't read the frame length and flags.
+            int remaining = src.remaining();
+            if (remaining < SIZE_OF_FRAME_LENGTH_AND_FLAGS) {
+                // we don't have even the frame length and flags ready
+                return false;
```
Comment (emreyigit) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientMessageReader.java:72]: If we return here, in which case exception will be thrown at line 77? I'm confused if at the first read, the `remaining` less than 6 bytes, how we expect `frameLength` will be also less than 6 bytes? Is there any case that we throw `IllegalArgumentException`?

File: hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageReaderTest.java [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+        byte[] part1 = new byte[750];
+        buffer.get(part1, 0, 750);
+        byte[] part2 = new byte[buffer.remaining()];
+        buffer.get(part2);
+
+        ByteBuffer part1Buffer = ByteBuffer.wrap(part1);
+        ByteBuffer part2Buffer = ByteBuffer.wrap(part2);
+
+        ClientMessageReader reader = new ClientMessageReader(-1);
+        assertFalse(reader.readFrom(part1Buffer, true));
```
Comment (emreyigit) [inline hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageReaderTest.java:117]: I couldn't understand why it cannot read `part1Buffer`?

**Comment by emreyigit** [comment]
Have commented. Also, it would be nice to have test case for the total length is less than 6 bytes. WDYT?

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientMessageReader.java (hunk 1 above)
Comment (mdumandag) [reply hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientMessageReader.java:72]: The first check is to make sure that there are at least 6 bytes we read from the socket so that we can read the frame length and flags.

The second check is there to ensure that the value we read from the first 4 bytes of that 6 bytes (describing the length of the frame) is not an illegal value. Converting the 4 bytes to an integer should yield a value greater than 6 due the protocol.

So, both checks are necessary

File: hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageReaderTest.java (hunk 2 above)
Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/client/impl/protocol/util/ClientMessageReaderTest.java:117]: Returning false here indicates that the client message is not fully read, and we would need to call this method again

**Review by emreyigit — APPROVED** [review]

**Review by ihsandemir — APPROVED** [review]
