### PR TITLE
Fix race in NodeId innitialization in FlakeId proxy

### LINKED ISSUE #16609: AssertionError: nodeId out of range: -1 invokeWithArguments(MethodHandle.java:627)
http://jenkins.hazelcast.com/view/freeze/job/freeze-all/13/console

Hazelcast Enterprise 4.1-SNAPSHOT (20200205 - 37bffaf, 1e23c41)

```
02:21:26.259 /disk1/jenkins/workspace/freeze-all/4.0/2020_02_04-11_09_34/stable/destroy/create-use-destroy Failed
02:21:26.265 fail HzClient4HZ _create-use-destroy_createUseDestroy_reliableId hzcmd.id.flake.CreateUseDestroy threadId=0 java.lang.AssertionError: nodeId out of range: -1 [0m
02:21:26.500 http://54.147.27.51/~jenkins/workspace/freeze-all/4.0/2020_02_04-11_09_34/stable/destroy/create-use-destroy
```

```
java.lang.AssertionError: nodeId out of range: -1
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.tryWrapInSameClass(AbstractInvocationFuture.java:1954)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapError(AbstractInvocationFuture.java:1945)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.wrapOrPeel(AbstractInvocationFuture.java:1931)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ExceptionalResult.wrapForJoinInternal(AbstractInvocationFuture.java:1395)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.resolveAndThrowForJoinInternal(AbstractInvocationFuture.java:592)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.joinInternal(AbstractInvocationFuture.java:576)
	at com.hazelcast.client.impl.proxy.ClientFlakeIdGeneratorProxy.newIdBatch(ClientFlakeIdGeneratorProxy.java:58)
	at com.hazelcast.client.impl.proxy.ClientFlakeIdGeneratorProxy.access$000(ClientFlakeIdGeneratorProxy.java:33)
	at com.hazelcast.client.impl.proxy.ClientFlakeIdGeneratorProxy$1.newIdBatch(ClientFlakeIdGeneratorProxy.java:45)
	at com.hazelcast.flakeidgen.impl.AutoBatcher.newId(AutoBatcher.java:58)
	at com.hazelcast.client.impl.proxy.ClientFlakeIdGeneratorProxy.newId(ClientFlakeIdGeneratorProxy.java:52)
	at hzcmd.id.flake.CreateUseDestroy.timeStep(CreateUseDestroy.java:11)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
	at remote.bench.BenchThread.call(BenchThread.java:41)
	at remote.bench.BenchThread.call(BenchThread.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #16609

Reasoning:
The `nextNodeIdUpdate` timestamp was updated BEFORE the `nodeId` field.
This means when 2 threads were initializing the proxy concurrently
then the 2nd thread could see the timestamp already updated then skip the
IF branch and return a stale version of nodeId - which was not updated yet.

This problem is fixed by updating the timestamp after the nodeId field.

Additionally when the IF branch is not taken we still have to dereference
the nodeId field. Otherwise we would return a stale value we had dereferenced
before the IF branch.

### CODE REVIEW

**Comment by jerrinot** [comment]
the test looks scary long runnnig, but it's not too bad:
image

File: hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java [hunk 1]
```diff
@@ -199,7 +199,9 @@ IdBatchAndWaitTime newIdBaseLocal(long now, int nodeId, int batchSize) {
      * </ul>
      */
     private int getNodeId() {
-        return getNodeId(System.nanoTime());
+        int nodeId = getNodeId(System.nanoTime());
+        assert nodeId > 0 || nodeId == NODE_ID_OUT_OF_RANGE : "getNodeId() returned invalid value";
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java:203]: enforcing the contract as described in JavaDoc

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2575/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2575/Hazelcast-pr-builder-2575.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientQueryCacheRecreationTest.query_cache_recreates_itself_after_server_restart:112->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->lambda$query_cache_recreates_itself_after_server_restart$0:114 expected:<200> but was:<191>
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31979, Failures: 2, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java [hunk 2]
```diff
@@ -226,10 +227,18 @@ int getNodeId(long nanoTime) {
 
                 // we ignore possible double initialization
                 this.nodeId = nodeId;
+                nextNodeIdUpdate = nanoTime + NODE_ID_UPDATE_INTERVAL_NS;
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java:230]: Your code is OK, so I'm approving. This also works, I find it easier. If you like it you can replace it:
```java
        long nextNodeIdUpdate = this.nextNodeIdUpdate;
        int nodeId = this.nodeId;
        if (nextNodeIdUpdate <= nanoTime) {
            if (nodeId == NODE_ID_OUT_OF_RANGE) {
                return nodeId;
            }
            int newNodeId = getNodeEngine().getClusterService().getMemberListJoinVersion();
            assert newNodeId >= 0 : "newNodeId=" + newNodeId;
            newNodeId += nodeIdOffset;
            if (newNodeId != nodeId) {
                nodeId = newNodeId;

                // If our node ID is out of range, assign NODE_ID_OUT_OF_RANGE to nodeId
                if ((nodeId & -1 << bitsNodeId) != 0) {
                    outOfRangeMembers.add(getNodeEngine().getClusterService().getLocalMember().getUuid());
                    logger.severe("Node ID is out of range (" + nodeId + "), this member won't be able to generate IDs. "
                            + "Cluster restart is recommended.");
                    nodeId = NODE_ID_OUT_OF_RANGE;
                }

                // we ignore possible double initialization
                this.nodeId = nodeId;
                this.nextNodeIdUpdate = nanoTime + NODE_ID_UPDATE_INTERVAL_NS;
                if (logger.isFineEnabled()) {
                    logger.fine("Node ID assigned to '" + name + "': " + nodeId);
                }
            }
        }
```
It ensures that it's impossible to see no need to update before `nodeId` was assigned to some valid value.

**Review by viliam-durina — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java [hunk 3]
```diff
@@ -226,10 +227,18 @@ int getNodeId(long nanoTime) {
...
                 if (logger.isFineEnabled()) {
                     logger.fine("Node ID assigned to '" + name + "': " + nodeId);
                 }
             }
+        } else if (nodeId == NODE_ID_NOT_YET_SET) {
+            // There is a race between the IF branch above and the local nodeId assignment just above the branch.
+            // It could be we didn't take the branch yet the local nodeId variable still contains the
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java:237]: Minor: did you want to say "It could be that we did take the branch, yet the local nodeId variable is set to NODE_ID_NOT_YET_SET"? I must admit, I know what you did with the else branch but I don't understand the comment :)

**Review by mmedenjak — APPROVED** [review]

**Comment by mmedenjak** [comment]
Thank you for the fix and the review, everyone! 🙇
