### PR TITLE
Sets connection type on reading MEMBER protocol bytes

### LINKED ISSUE #14543: AdvancedNetworkClientIntegrationTest.clientSmokeTest
_master_ (commit b04e92cd992e7299844dc361b491103208cd2335)

Failed on ZuluJDK7 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZuluJDK7/8/testReport/com.hazelcast.client.io/AdvancedNetworkClientIntegrationTest/clientSmokeTest/

**Stacktrace**
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:315)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:160)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:225)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:219)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:584)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:334)
	at com.hazelcast.client.io.AdvancedNetworkClientIntegrationTest.clientSmokeTest(AdvancedNetworkClientIntegrationTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by vbekiaris**
Also adds cleanup for hazelcast clients used in AdvancedNetworkClientIntegrationTest

Fixes #14543

### CODE REVIEW

**Comment by vbekiaris** [comment]
The cleanup is still necessary, but the test failure is not fixed by this PR. Still working on it.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/BindHandler.java [hunk 1]
```diff
@@ -88,6 +89,9 @@ private synchronized boolean bind(TcpIpConnection connection, ExtendedBindMessag
         // is created from an outbound port (eg 192.168.1.1:54003 --> 192.168.1.2:5701), but
         // in 192.168.1.2:5701's connectionsMap the connection must be registered with
         // key 192.168.1.1:5701.
+        assert (tcpIpEndpointManager.getEndpointQualifier() != EndpointQualifier.MEMBER
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/BindHandler.java]: Ensures that a `BindHandler` constructed in the context of a `MEMBER` endpoint manager will handle bind requests for connections with `MEMBER` connection type already set. Connection type of other connections can be set later (eg client connections are assigned their type upon client authentication).

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/SingleProtocolDecoder.java [hunk 2]
```diff
@@ -97,6 +100,13 @@ private String loadProtocol() {
         return bytesToString(protocolBytes);
     }
 
+    private void initConnection() {
+        if (supportedProtocol == ProtocolType.MEMBER) {
+            TcpIpConnection connection = (TcpIpConnection) channel.attributeMap().get(TcpIpConnection.class);
+            connection.setType(ConnectionType.MEMBER);
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/SingleProtocolDecoder.java]: This is the fix to ensure connection type is set immediately after protocol bytes have been received -> it will be available in `BindHandler` processing
