### PR TITLE
IdentifyConverter converts NULL-values into NULL-objects

### LINKED ISSUE #5807: IndexImpl.getRecords fails with NPE
In #4525 muratayan suggested using following:
```java
final Predicate emptyFieldPredicate = Predicates.notEqual("field", "value");
final Predicate nullPredicate = Predicates.equal("field", null);
final Collection<TestClass> emptyFieldValues = map.values(Predicates.or(emptyFieldPredicate, nullPredicate));
```

On  hazelcast  launched  with xml configuration contained:
```xml
<map name="map">
  <backup-count>0</backup-count>
  <async-backup-count>0</async-backup-count>
  <read-backup-data>true</read-backup-data>
  <indexes>
    <index>field</index>
  </indexes>
</map>
```
I tried it and got:

```
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333) ~[na:1.7.0_79]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988) ~[na:1.7.0_79]
	at com.hazelcast.query.impl.UnsortedIndexStore.getRecords(UnsortedIndexStore.java:190) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.impl.IndexImpl.getRecords(IndexImpl.java:129) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.Predicates$EqualPredicate.filter(Predicates.java:779) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.Predicates$OrPredicate.filter(Predicates.java:578) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.PagingPredicate.filter(PagingPredicate.java:169) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.impl.IndexService.query(IndexService.java:95) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.map.impl.operation.QueryOperation.run(QueryOperation.java:84) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:750) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:726) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicOperationService.runOperationOnCallingThread(BasicOperationService.java:253) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocation.doInvokeLocal(BasicInvocation.java:280) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:262) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:229) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:48) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.map.impl.client.AbstractMapQueryRequest.createInvocations(AbstractMapQueryRequest.java:140) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.map.impl.client.AbstractMapQueryRequest.invoke(AbstractMapQueryRequest.java:74) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.client.impl.client.InvocationClientRequest.process(InvocationClientRequest.java:27) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:434) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:353) [hazelcast-3.4.4.jar:3.4.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-3.4.4.jar:3.4.4]
2015-07-28 16:04:52,396 ERROR HZC     [hz._hzInstance_1_dev.client.thread-54] c.h.c.ClientEngine [192.168.168.77]:5701 [dev] [3.4.4] While executing request: com.hazelcast.map.impl.client.MapQueryRequest@ff1b76 -> null
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333) ~[na:1.7.0_79]
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988) ~[na:1.7.0_79]
	at com.hazelcast.query.impl.UnsortedIndexStore.getRecords(UnsortedIndexStore.java:190) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.impl.IndexImpl.getRecords(IndexImpl.java:129) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.Predicates$EqualPredicate.filter(Predicates.java:779) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.Predicates$OrPredicate.filter(Predicates.java:578) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.PagingPredicate.filter(PagingPredicate.java:169) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.query.impl.IndexService.query(IndexService.java:95) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.map.impl.operation.QueryOperation.run(QueryOperation.java:84) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.handle(BasicOperationService.java:750) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicOperationService$OperationHandler.access$500(BasicOperationService.java:726) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicOperationService.runOperationOnCallingThread(BasicOperationService.java:253) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocation.doInvokeLocal(BasicInvocation.java:280) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocation.doInvoke(BasicInvocation.java:262) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocation.invoke(BasicInvocation.java:229) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.spi.impl.BasicInvocationBuilder.invoke(BasicInvocationBuilder.java:48) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.map.impl.client.AbstractMapQueryRequest.createInvocations(AbstractMapQueryRequest.java:140) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.map.impl.client.AbstractMapQueryRequest.invoke(AbstractMapQueryRequest.java:74) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.client.impl.client.InvocationClientRequest.process(InvocationClientRequest.java:27) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.processRequest(ClientEngineImpl.java:434) ~[hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.client.impl.ClientEngineImpl$ClientPacketProcessor.run(ClientEngineImpl.java:353) ~[hazelcast-3.4.4.jar:3.4.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-3.4.4.jar:3.4.4]
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-3.4.4.jar:3.4.4]
```
 Another question is. 

Is it by design that
```java
Predicates.not(Predicates.equal("field", "value"));
```
still returns null values while

```java
Predicates.notEquals("field", "value");
```
does not?

### PR DESCRIPTION
**Pull request by jerrinot**
Fixed #5807

It changes TypeConverter to be an abstract class instead of interface. It's not part of user API and it's the simplest way to make sure all converters deal with NULL input values correctly. 

Also a few small consistency related clean-ups. See commits for more informations.

### CODE REVIEW

**Comment by jerrinot** [comment]
I'll send a PR with a backport of the fix once this is reviewed.

File: hazelcast/src/main/java/com/hazelcast/query/impl/IdentityConverter.java [hunk 1]
```diff
@@ -21,10 +21,10 @@
 /**
  * Converts to the same value
  **/
-public class IdentityConverter implements TypeConverter {
+public class IdentityConverter extends TypeConverter {
 
     @Override
-    public Comparable convert(final Comparable value) {
+    public Comparable convertInternal(final Comparable value) {
```
Comment (serkan-ozal) [inline hazelcast/src/main/java/com/hazelcast/query/impl/IdentityConverter.java]: should not be `public`

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/IdentityConverter.java]: thanks!
resolved

File: hazelcast/src/main/java/com/hazelcast/query/impl/IdentityConverter.java [hunk 2]
```diff
@@ -21,10 +21,10 @@
 /**
  * Converts to the same value
  **/
-public class IdentityConverter implements TypeConverter {
+public class IdentityConverter extends TypeConverter {
```
Comment (serkan-ozal) [inline hazelcast/src/main/java/com/hazelcast/query/impl/IdentityConverter.java]: As far as I see, with this PR, `IdentityConverter` is only access over `TypeConverters.IDENTITY_CONVERTER`, so should we keep this still public?
Can it cause to backward-compatibility issue if we remove `public` class modifier?

File: hazelcast/src/main/java/com/hazelcast/query/impl/UUIDConverter.java [hunk 3]
```diff
@@ -21,18 +21,10 @@
...
-public final class UUIDConverter implements TypeConverters.TypeConverter {
-
-    /**
-     * Singleton
-     */
-    public static final TypeConverters.TypeConverter INSTANCE = new UUIDConverter();
-
-    private UUIDConverter() {
-    }
+public final class UUIDConverter extends TypeConverters.TypeConverter {
```
Comment (serkan-ozal) [inline hazelcast/src/main/java/com/hazelcast/query/impl/UUIDConverter.java]: Do we still need this class as public?

**Comment by serkan-ozal** [comment]
Can you add a test as user mentioned that reproduces the issue?
I mean can we simply use the reproducer code given by user as test?

**Comment by jerrinot** [comment]
@serkan-ozal: done

**Comment by serkan-ozal** [comment]
@jerrinot Great, you have given my :+1:

**Comment by jerrinot** [comment]
@serkan-ozal: awesome!
I nominate @ajermakovics to be the 2nd reviewer as he is the original author of `IdentityConverter` class.

**Comment by serkan-ozal** [comment]
right, @ajermakovics should have a look also

File: hazelcast-client/src/test/java/com/hazelcast/client/map/impl/query/ClientQueryAdvancedTest.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+
+        SampleObjects.ValueType valueType = new SampleObjects.ValueType("name");
+        SampleObjects.Value value1 = new SampleObjects.Value("notNull", valueType, 1);
+        SampleObjects.Value value2 = new SampleObjects.Value("null", null, 1);
+        map.put(1, value1);
+        map.put(2, value2);
+
+        final Predicate nullPredicate = equal("type", null);
+        final Collection<SampleObjects.Value> emptyFieldValues = map.values(nullPredicate);
+        assertThat(emptyFieldValues, hasSize(1));
```
Comment (ajermakovics) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/query/ClientQueryAdvancedTest.java]: Should probably assert that the correct item is in the collection

Comment (jerrinot) [inline hazelcast-client/src/test/java/com/hazelcast/client/map/impl/query/ClientQueryAdvancedTest.java]: done

File: hazelcast/src/main/java/com/hazelcast/query/impl/TypeConverters.java [hunk 5]
```diff
@@ -37,20 +37,26 @@
...
 
-    public interface TypeConverter {
-        Comparable convert(Comparable value);
-    }
+    public abstract static class TypeConverter {
+        abstract Comparable convertInternal(Comparable value);
 
-    static class EnumConverter implements TypeConverter {
-        @Override
         public Comparable convert(Comparable value) {
```
Comment (ajermakovics) [inline hazelcast/src/main/java/com/hazelcast/query/impl/TypeConverters.java]: It'd be good to mark this method as `final` since its not intended to be overriden

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/TypeConverters.java]: I can do that. I guess it can be always removed later if needed (I doubt that)

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/TypeConverters.java]: done

**Comment by ajermakovics** [comment]
:+1: once green

**Comment by jerrinot** [comment]
@serkan-ozal, @ajermakovics: guys, thanks for review. it's green -> I'm going to merge it.
what about a backport? I'd suggest to not backport the hierarchy change, but just introduce the null check where missing. WDYT?

**Comment by serkan-ozal** [comment]
Yes, IMO just null check in `IdentityTypeConverter` is enough for backport.
