### PR TITLE
Retry cluster shutdown until it succeeds in ClusterShutdownTest

### LINKED ISSUE #6504: [TEST-FAILURE] ClusterShutdownTest.cluster_mustBeShutDown_by_singleMember_when_clusterState_ACTIVE
```
java.lang.AssertionError: expected:<SHUT_DOWN> but was:<ACTIVE>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.cluster.ClusterShutdownTest$3.run(ClusterShutdownTest.java:97)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:828)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:842)
	at com.hazelcast.cluster.ClusterShutdownTest.assertNodesShutDownEventually(ClusterShutdownTest.java:93)
	at com.hazelcast.cluster.ClusterShutdownTest.testClusterShutdownWithSingleMember(ClusterShutdownTest.java:65)
	at com.hazelcast.cluster.ClusterShutdownTest.cluster_mustBeShutDown_by_singleMember_when_clusterState_ACTIVE(ClusterShutdownTest.java:26)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-pr-builder/com.hazelcast$hazelcast/16376/testReport/junit/com.hazelcast.cluster/ClusterShutdownTest/cluster_mustBeShutDown_by_singleMember_when_clusterState_ACTIVE/

### PR DESCRIPTION
**Pull request by metanet**
* It may fail because of the ongoing replications or migrations and it will succeed once they are completed

Fixes #6504

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java [hunk 1]
```diff
@@ -56,11 +57,19 @@ private void testClusterShutdownWithSingleMember(final ClusterState clusterState
         final Thread thread = new Thread(new Runnable() {
             @Override
             public void run() {
-                instances[0].getCluster().shutdown();
+                while (true) {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: Hmmm.. This looks strange to me. So it can happen that a shutdown call throws an exception and is ignored??

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java [hunk 2]
```diff
@@ -56,11 +57,19 @@ private void testClusterShutdownWithSingleMember(final ClusterState clusterState
...
+                    try {
+                        instances[0].getCluster().shutdown();
+                        break;
+                    } catch (Exception ignored) {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: I would definitely log the exception.

**Comment by mdogan** [comment]
@metanet: what about removing ` warmUpPartitions(instances)` line from the shutdown tests? Is it required?

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java (hunk 2 above)
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: log why? this is a test and it's known that `shutdown()` can fail. Logging them will be just noise in the logs.

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java (hunk 1 above)
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: Why strange?

**Comment by metanet** [comment]
@mdogan actually it is intentional. I wanted to test the cluster shutdown while partitions are assigned. Actually, after the fix we made yesterday on node shutdown, maybe we can put some data to increment partition versions in this tests too.

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java (hunk 1 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: I would expect the shutdown not to fail. Also in most applications, people don't take that much care of protecting the shutdown and a whole bunch of things are shutdown sequentially. If an exception is thrown, then the following services (which could be db connection pool etc) are not closed.

So I would expect a shutdown not to fail. If it does; it must be a programming error and this should be resolved, not suppressed.

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: See previous comments. In my book a failing shutdown is a system error and should be resolved.

Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: It is a cluster shutdown which terminates all nodes one by one. It will not fail while actually shutting down the nodes, it will fail during moving the cluster to the shut-down-able state. Since we know it will fail because of replica sync operations, I ignored the exception. How can a cluster shutdown operation fail is well-documented in javadocs.

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java (hunk 1 above)
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: This is a distributed shutdown and shutdowns all cluster members. A distributed operation is expected to fail. And also it's clearly defined in its doc. 

```
* @throws IllegalStateException    if member-list changes during the transaction
 * @throws TransactionException     if there's already an ongoing transaction
 *                                  or this transaction fails
 *                                  or this transaction timeouts
```

**Comment by mdogan** [comment]
@metanet: We are already doing cluster-state changes while partitions are assigned. I think we can remove warmup here and just test shutdown behaviour.

File: hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: Ok. 

It still feels funny for the above reasons. In my book shutdowns should not fails because they can cause problems for other components in a system that also need to shut down. It can leave a system in an undefined half shut down state

Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/cluster/ClusterShutdownTest.java]: there is an old saying, you know :)

"timeo hominem unius libri"

Joking aside, I fully understand your concern. As I stated, if cluster shutdown fails, it means that:
- Either cluster state failed to move into a shut-down-able (PASSIVE) state which creates no problem since everything will work fine. 
- Or cluster state is moved to (PASSIVE) state, some of the nodes has actually shut down but some others hasn't shutdown because of any failure (message loss etc.). In this case, still-running nodes must be shut-down by triggering the shutdown process on these nodes. Otherwise, they will not accept any operations since they are in PASSIVE state. This is still a safe state.

**Comment by metanet** [comment]
unrelated test failure

**Comment by metanet** [comment]
verify

**Comment by mdogan** [comment]
:+1:
