### PR TITLE
Defer cache key-value type resolution until actually needed

### LINKED ISSUE #11505: [cache] Member cannot join 3.9 cluster when using Cache with a key/value type only resolvable from user code deployment repository
__Use case:__
- Start cluster members with user code deployment enabled
- Create a typed `Cache` whose key or value type is resolvable on the current cluster members (`CacheManager.createCache("test", new CacheConfig<String, Person>().setTypes(String.class, Person.class))`).
- Start a new cluster member missing the key or value type from its local classpath with user code deployment enabled.

__Expected:__
 New cluster member should join cluster as missing type should be resolved from remote members.
__Actual:__ 
New member cannot join cluster and fails startup.

__The cause__ is that as of 3.9 `CacheConfig`s become known to the joining member in a pre-join operation; at the time this operation is deserialized (in `FinalizeJoinOp`) the joining member has not yet updated its cluster members list and cannot resolve the missing class remotely.

### PR DESCRIPTION
**Pull request by vbekiaris**
Introduces new wire format for transferring cache configs in the pre-join `Cache` op.

Reasoning: the pre-join op must not resolve the key/value classes if
defined in the cache config, because user code deployment cannot kick
in as the pre-join op is being deserialized and may result in unexpected
failure to add the cache config. Instead, the key/value types are loaded
whenever getKeyType/getValueType is invoked which only occurs after the
joining member's member list has been updated, allowing resolution of
classes from remote user code deployment repository.

Fixes #11505

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/cache/impl/operation/OnJoinCacheOperation.java [hunk 1]
```diff
@@ -59,7 +60,14 @@ public void run() throws Exception {
         if (isJCacheAvailable(getNodeEngine().getConfigClassLoader())) {
             ICacheService cacheService = getService();
             for (CacheConfig cacheConfig : configs) {
-                cacheService.putCacheConfigIfAbsent(cacheConfig);
+                // RU_COMPAT_38 since 3.9, configs are instances of OnJoinCacheConfig
+                CacheConfig cacheConfigToAdd;
+                if (cacheConfig instanceof OnJoinCacheConfig) {
+                    cacheConfigToAdd = ((OnJoinCacheConfig) cacheConfig).asCacheConfig();
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/operation/OnJoinCacheOperation.java]: `OnJoinCacheConfig` should not leak outside `OnJoinCacheOperation`, so it is transformed to a `CacheConfig` as it is added to the `CacheService`'s config registry.

File: hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java [hunk 2]
```diff
@@ -597,6 +595,8 @@ public void readData(ObjectDataInput in) throws IOException {
 
         mergePolicy = in.readUTF();
         disablePerEntryInvalidationEvents = in.readBoolean();
+
+        setClassLoader(in.getClassLoader());
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java]: Keep a reference to `SerializationService`'s class loader, so when `keyType`/`valueType` are being resolved, the proper classloader will be used.

**Comment by vbekiaris** [comment]
`com.hazelcast.client.ClientMaxAllowedInvocationTest.testMaxAllowed_andThenInternal: test timed out after 300000 milliseconds` 

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11108/testReport/junit/com.hazelcast.client/ClientMaxAllowedInvocationTest/testMaxAllowed_andThenInternal/

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java [hunk 3]
```diff
@@ -287,11 +297,57 @@ public HotRestartConfig getHotRestartConfig() {
...
+                throw new HazelcastException("Could not resolve key type", e);
+            }
+        }
+        if (keyType == null) {
+            keyType = (Class<K>) Object.class;
+        }
+        return keyType;
+    }
+
+    private Class<V> resolveValueType() {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java]: `resolveKeyType` and `resolveValueType` methods look similar with one another. Seems two method can be reduced to a single method to do same thing.

File: hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+ * used (by means of {@link CacheConfig#getKeyType()} or {@link CacheConfig#getValueType()}). This allows resolution of
+ * these classes from remote user code deployment repositories (which are not available while the pre-join operation is being
+ * deserialized and executed).
+ *
+ * @param <K> the key type of this cache configuration
+ * @param <V> the value type
+ * @since 3.9
+ */
+@PrivateApi
+public class OnJoinCacheConfig<K, V> extends CacheConfig<K, V> implements IdentifiedDataSerializable {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: Can't we keep `OnJoinCacheConfig ` in internal cache package, instead of `com.hazelcast.config`?

Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: Can be renamed as `PreJoinCacheConfig`?

File: hazelcast/src/test/java/com/hazelcast/config/OnJoinCacheConfigTest.java [hunk 5]
```diff
@@ -0,0 +1,162 @@
...
+
+import static com.hazelcast.config.helpers.CacheConfigHelper.getEvictionConfigByClassName;
+import static com.hazelcast.config.helpers.CacheConfigHelper.getEvictionConfigByImplementation;
+import static com.hazelcast.config.helpers.CacheConfigHelper.getEvictionConfigByPolicy;
+import static com.hazelcast.config.helpers.CacheConfigHelper.newCompleteCacheConfig;
+import static com.hazelcast.config.helpers.CacheConfigHelper.newDefaultCacheConfig;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.fail;
+
+public class OnJoinCacheConfigTest {
```
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/config/OnJoinCacheConfigTest.java]: missing `@Category`

File: hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+    @Override
+    public int getId() {
+        return ConfigDataSerializerHook.ON_JOIN_CACHE_CONFIG;
+    }
+
+    /**
+     * @return this configuration as a {@link CacheConfig}
+     */
+    public CacheConfig asCacheConfig() {
+        CacheConfig<K, V> cacheConfig = new CacheConfig<K, V>();
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: Can't you use `return new CacheConfig<K, V>(this)` to avoid duplicating all these setter calls?

File: hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java [hunk 7]
```diff
@@ -0,0 +1,163 @@
...
+     * Constructor that copies given {@code cacheConfig}'s properties to a new {@link OnJoinCacheConfig}. It is assumed that
+     * the given {@code cacheConfig}'s key-value types have already been resolved to loaded classes.
+     * @param cacheConfig   the original {@link CacheConfig} to copy into a new {@link OnJoinCacheConfig}
+     */
+    public OnJoinCacheConfig(CacheConfig cacheConfig) {
+        this(cacheConfig, true);
+    }
+
+    @SuppressWarnings("checkstyle:executablestatementcount")
+    public OnJoinCacheConfig(CacheConfig cacheConfig, boolean resolved) {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: We should figure out a way to avoid duplicating all these setter calls.

File: hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java (hunk 6 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: The `CacheConfig(CompleteConfiguration)` constructor will immediately resolve `keyType` & `valueType`. What we need here is to only set the key/value class names in the transformed-to `CacheConfig`, so the actual classes will be loaded later.

File: hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java (hunk 4 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: Done

Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/config/OnJoinCacheConfig.java]: Moved to `com.hazelcast.cache.impl` package.

File: hazelcast/src/test/java/com/hazelcast/config/OnJoinCacheConfigTest.java (hunk 5 above)
Comment (vbekiaris) [reply hazelcast/src/test/java/com/hazelcast/config/OnJoinCacheConfigTest.java]: Added category & runner

File: hazelcast/src/main/java/com/hazelcast/config/ConfigDataSerializerHook.java [hunk 8]
```diff
@@ -87,8 +88,9 @@
     public static final int QUORUM_LISTENER_CONFIG = 45;
     public static final int CACHE_PARTITION_LOST_LISTENER_CONFIG = 46;
     public static final int SIMPLE_CACHE_ENTRY_LISTENER_CONFIG = 47;
+    public static final int ON_JOIN_CACHE_CONFIG = 48;
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/config/ConfigDataSerializerHook.java]: This can be moved to `CacheDataSerializerHook`.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
`com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeASYNCSingleMemberStartLate: com.hazelcast.client.HazelcastClientOfflineException: Client is offline.`

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/11122/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeASYNCSingleMemberStartLate/

**Comment by vbekiaris** [comment]
run-lab-run
