### PR TITLE
Use eventual assertions for backups in map & cache split-healing tests

### LINKED ISSUE #12263: MapSplitBrainTest
**com.hazelcast.map.merge.MapSplitBrainTest.testSplitBrain[format:BINARY, mergePolicy:class com.hazelcast.spi.merge.PassThroughMergePolicy]**
```java
java.lang.AssertionError: expected:<PassThroughValue2> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.map.merge.MapSplitBrainTest.afterMergePassThroughMergePolicy(MapSplitBrainTest.java:342)
	at com.hazelcast.map.merge.MapSplitBrainTest.onAfterSplitBrainHealed(MapSplitBrainTest.java:188)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/13240/testReport/junit/com.hazelcast.map.merge/MapSplitBrainTest/testSplitBrain_format_BINARY__mergePolicy_class_com_hazelcast_spi_merge_PassThroughMergePolicy_/

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #12263

Reasoning:
Backup are created asynchronously during a split-brain healing hence
assertion should be eventual too.

As a by-product created an abstraction for accessing backup
records in tests.

The same has to be done for JCache tests.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/TestBackupUtils.java [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+
+    private TestBackupUtils() {
+
+    }
+
+    /**
+     * Access backup records in a given replica. Use {@link #newMapAccessor(HazelcastInstance[], String)}
+     * to create an instance for your data structure.
+     *
+     * @param <K>
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/TestBackupUtils.java]: The `@param` and `@return` JavaDoc in this class should be completed or removed, in this state there will be a lot of warnings in IDEA.

File: hazelcast/src/test/java/com/hazelcast/map/TestBackupUtils.java [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+
+import static com.hazelcast.test.HazelcastTestSupport.assertTrueEventually;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertNull;
+
+/**
+ * Convenience for accessing backup records.
+ *
+ */
+public final class TestBackupUtils {
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/TestBackupUtils.java]: We will need this for `ICache` and `ReplicatedMap` as well. Therefore I would directly move this class to `com.hazelcast.test.backup` and make the `BackupAccessor` a first class citizen (shorter classnames in the tests). I would also pull out `MapBackupAccessor` as package private class, since there will be more implementations.

File: hazelcast/src/test/java/com/hazelcast/map/TestBackupUtils.java [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+
+    private static class MapBackupAccessor<K, V> implements BackupAccessor<K, V> {
+        private final HazelcastInstance[] cluster;
+        private final String mapName;
+        private final int replicaIndex;
+        private final InternalSerializationService serializationService;
+        private final InternalPartitionService partitionService;
+
+        private MapBackupAccessor(HazelcastInstance[] cluster, String mapName, int replicaIndex) {
+            if (replicaIndex < 1) {
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/map/TestBackupUtils.java]: You might also want to check for `IPartition.MAX_BACKUP_COUNT` here.

File: hazelcast/src/test/java/com/hazelcast/test/TestTaskExecutorUtil.java [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+import static java.util.concurrent.TimeUnit.SECONDS;
+
+/**
+ * Convenience for executing {@link Callable} on a partition thread.
+ * Unlike regular {@link PartitionSpecificRunnable} it's easy to return a value back to a caller.
+ *
+ * This is intended to be used in tests only.
+ *
+ */
+public final class TestTaskExecutorUtil {
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/test/TestTaskExecutorUtil.java]: test-only convenience

File: hazelcast/src/test/java/com/hazelcast/test/TestTaskExecutorUtil.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+     *
+     * @param instance Hazelcast instance to be used for task executin
+     * @param task the task to be executed
+     * @param partitionId selects partition thread
+     * @param <T> type of the result
+     * @return result as returned by the callable
+     */
+    public static <T> T runOnPartitionThread(HazelcastInstance instance, final Callable<T> task, final int partitionId) {
+        InternalOperationService operationService = getNodeEngineImpl(instance).getOperationService();
+        final BlockingQueue<Object> resultQueue = new ArrayBlockingQueue<Object>(1);
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/test/TestTaskExecutorUtil.java]: probably not very efficient, good enough for tests.

File: hazelcast/src/test/java/com/hazelcast/test/backup/TestBackupUtils.java [hunk 6]
```diff
@@ -0,0 +1,344 @@
...
+import java.util.concurrent.Callable;
+
+import static com.hazelcast.test.HazelcastTestSupport.assertTrueEventually;
+import static com.hazelcast.test.HazelcastTestSupport.getNode;
+import static com.hazelcast.test.HazelcastTestSupport.getNodeEngineImpl;
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertNull;
+
+/**
+ * Convenience for accessing and asserting backup records.
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/test/backup/TestBackupUtils.java]: again, a test only abstraction. I've got fed-up with ad-hoc way to access backup data in tests.

File: hazelcast/src/test/java/com/hazelcast/test/backup/TestBackupUtils.java [hunk 7]
```diff
@@ -0,0 +1,344 @@
...
+            @Override
+            public void run() {
+                int actualSize = accessor.size();
+                assertEquals("Expected size: ' " + expectedSize + "' actual size: " + actualSize, expectedSize, actualSize);
+            }
+        });
+    }
+
+
+    // ######################################################################
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/test/backup/TestBackupUtils.java]: implementations of accessors is a pretty awful & fragile code to be honest. but it's isolated awfulness :)
