### PR TITLE
fixing-npe-when-config-havent-root

### LINKED ISSUE #19039: NPE for invalid client Yaml
With 5.0-SNAPSHOT (20210712) if I do

```
new YamlClientConfigBuilder("application.yml").build();
```

And the YAML file contains no `hazelcast-client:` ssection I get an NPE instead of a helpful diagnostic

```
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.lambda$validate$0(YamlConfigSchemaValidator.java:72) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline.count(Unknown Source) ~[?:?]
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:73) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.parseAndBuildConfig(YamlClientConfigBuilder.java:160) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:132) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:120) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
	at com.hazelcast.client.config.YamlClientConfigBuilder.build(YamlClientConfigBuilder.java:115) ~[hazelcast-enterprise-5.0-SNAPSHOT.jar!/:5.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by fkardashov**
Fix NPE if no root node in config file

Fixes #19039 

Add check rootNode != null

### CODE REVIEW

**Comment by viliam-durina** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Thank you for the PR! @hazelcast/apis @blazember can you take a look?

File: hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java [hunk 1]
```diff
@@ -69,8 +69,9 @@ public void validate(YamlMapping rootNode) {
             // this could be expressed in the schema as well, but that would make all the schema validation errors much harder
             // to read, so it is better to implement it here as a semantic check
             long definedRootNodeCount = PERMITTED_ROOT_NODES.stream()
-                    .filter(rootNodeName -> rootNode.child(rootNodeName) != null)
+                    .filter(rootNodeName -> rootNode != null && rootNode.child(rootNodeName) != null)
```
Comment (blazember) [inline hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java:72]: The fix looks fine to me. It would be good to have tests for the failing cases in the `Yaml*ConfigBuilderTest` classes. @fkardashov can you add them?

Comment (fkardashov) [reply hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java:72]: ok. I can

Comment (fkardashov) [reply hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java:72]: added some negative cases.
sorry, but now that's all

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java [hunk 2]
```diff
@@ -76,4 +76,23 @@ public void causingExceptionsWrapped() {
     public void emptyObject() {
         new YamlConfigBuilder(getClass().getResourceAsStream("/com/hazelcast/config/empty-object.yaml")).build();
     }
+
+    @Test(expected = InvalidConfigurationException.class)
+    public void witoutRootObject() {
```
Comment (blazember) [inline hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java:81]: Minor: typo in the method name.

**Review by blazember — APPROVED** [review]
Thanks for the fix :+1: One minor only.

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java (hunk 2 above)
Comment (fkardashov) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java]: fixed

**Comment by mmedenjak** [comment]
run-lab-run

**Review by sancar — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java [hunk 3]
```diff
@@ -556,6 +556,27 @@ public void readPortCount() {
...
+
+    @Test(expected = SchemaViolationConfigurationException.class)
+    public void negativeCount() {
+        Config config = buildConfig(""
+                + "hazelcast:\n"
+                + "  network:\n"
+                + "    port:\n"
+                + "      port-count: -200\n"
+                + "      port: 5701\n");
+    }
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java:578]: There is a comment at the top saying that

```
 * NOTE: This test class must not define test cases, it is meant only to
 * implement test cases defined in {@link AbstractConfigBuilderTest}.
```
So, I am not sure if it is OK to add new test cases here. 

Also, these are not really related to fix, so maybe we can move them to a separate PR. But, I am OK with having them here. Same for other new tests.

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java [hunk 4]
```diff
@@ -3953,6 +3996,21 @@ public void testPersistentMemoryConfiguration_SystemMemoryMode() {
...
+                + "hazelcast:\n"
+                + "  native-memory:\n"
+                + "    persistent-memory:\n"
+                + "      enabled: true\n"
+                + "      mode: SYSTEM_MEMORY1\n";
+
+        Config config = buildConfig(yaml);
+        PersistentMemoryConfig pmemConfig = config.getNativeMemoryConfig().getPersistentMemoryConfig();
+        assertTrue(pmemConfig.isEnabled());
+        assertEquals(SYSTEM_MEMORY, pmemConfig.getMode());
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java:4011]: These are probably unnecessary as the `buildConfig` call would fail

**Review by mdumandag — COMMENTED** [review]
I am generally OK about the PR, but I see that it is targeted to `5.0-BETA-1`. Shouldn't it be master?

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java (hunk 3 above)
Comment (fkardashov) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java:578]: I think have to  move tests to other pr

**Comment by mmedenjak** [comment]
I changed the base branch for this PR but now the commits need to be cleaned up, so please do so as well @fkardashov . Thank you.

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java (hunk 4 above)
Comment (fkardashov) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java]: fixed

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java (hunk 3 above)
Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java:578]: What I meant is that, you should probably define the test cases in `AbstractConfigBuilderTest` and implement them here and in other necessary places. 

And yes, I believe it would be good to move them to another PR, as you move the test definition to the correct place, you would have to add XML config validation tests as well.

Comment (fkardashov) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigBuilderTest.java]: ok. I removed tests from that pr. there is only NPE fix.
I am going to open another one with tests with XML and Yaml format.

thanks.

**Comment by mdumandag** [comment]
@fkardashov  you deleted too much :smile: 
Let's leave `hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java` related changes here, in this PR.

**Comment by fkardashov** [comment]
> @fkardashov you deleted too much 😄
> Let's leave `hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java` related changes here, in this PR.
done

**Comment by mdumandag** [comment]
@fkardashov I cannot see the test. You might forgot to add test changes to your latest commit

**Comment by fkardashov** [comment]
add test without root yaml

File: hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java [hunk 5]
```diff
@@ -81,4 +81,9 @@ public void lenientPrimitiveValidationIsEnabled() {
...
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java:86]:
```suggestion
    public void withoutRootObject() {
```
Please change this as well. Then, we should be good to go.

Comment (fkardashov) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java:86]: fixed.
thanks for patience

Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/config/YamlConfigSchemaValidatorTest.java:86]: Thanks, no problem. Thank you too.

**Comment by mdumandag** [comment]
run-lab-run

**Review by mdumandag — APPROVED** [review]
