### PR TITLE
Do not mutate ReplicatedMapConfig while constructing read-only variant

### LINKED ISSUE #12222: Dynamically Adding Configuration
Hi guys. I'm using hazelcast 3.9.2 and one of new features as 'Dynamically Adding Configuration'. My application has a module structure: there are several modules and core. Instance of the hazelcast is created by core, others modules are able to add some maps dinamically after that. Also i use spring 5.0.

here is sample of creating a map in a module:

```java
    @Bean
    public ReplicatedMap<String, Compilation> compilations(HazelcastInstance hazelcastInstance) {
        ReplicatedMapConfig config = new ReplicatedMapConfig(COMPILATION_MAP);
        config.setInMemoryFormat(InMemoryFormat.OBJECT);
        config.setAsyncFillup(false);
        hazelcastInstance.getConfig().addReplicatedMapConfig(config);
        return hazelcastInstance.getReplicatedMap(COMPILATION_MAP);
    }
```

when i only start one node, all works perfectly, but when second node is started i get an exception on him:

```
Failed to instantiate [com.hazelcast.core.ReplicatedMap]: Factory method 'compilations' threw exception; nested exception is com.hazelcast.config.ConfigurationException: Cannot add a dynamic configuration 'ReplicatedMapConfig{name='compilation.map'', inMemoryFormat=OBJECT', concurrencyLevel=32, replicationDelayMillis=100, asyncFillup=false, statisticsEnabled=true, mergePolicy='com.hazelcast.replicatedmap.merge.PutIfAbsentMapMergePolicy'}' as there is already a conflicting configuration 'ReplicatedMapConfig{name='compilation.map'', inMemoryFormat=OBJECT', concurrencyLevel=32, replicationDelayMillis=100, asyncFillup=false, statisticsEnabled=true, mergePolicy='com.hazelcast.replicatedmap.merge.PutIfAbsentMapMergePolicy'}'
```

But both configs are equals into text of exception and you can see that.

Is it a bug or i do something wrong?

### PR DESCRIPTION
**Pull request by vbekiaris**
Also, aligns `ReplicatedMapService` to use `findReplicatedMapConfig` to locate and obtain a read-only copy of the `ReplicatedMapConfig` instead of `getReplicatedMapConfig`, as other services do.

Fixes #12222

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java [hunk 1]
```diff
@@ -295,7 +295,7 @@ public ReplicatedRecordStore getReplicatedRecordStore(String name, boolean creat
     }
 
     public void initializeListeners(String name) {
-        List<ListenerConfig> listenerConfigs = config.getReplicatedMapConfig(name).getListenerConfigs();
+        List<ListenerConfig> listenerConfigs = getReplicatedMapConfig(name).getListenerConfigs();
         for (ListenerConfig listenerConfig : listenerConfigs) {
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java]: If `listenerConfigs` is `null` (which seems to be allowed), this `for each` will throw a NPE, correct?

Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/ReplicatedMapService.java]: `getListenerConfigs()` creates and returns an empty `ArrayList` if `listenerConfigs` is found to be `null`.

**Comment by vbekiaris** [comment]
run-lab-run
