### PR TITLE
Reduce re-creation of ExecutionContext after job failure

### LINKED ISSUE #19897: clients generate load via sql queries eventually OOME members in cluster [HZ-726]
clients making concurrent sql queries which might perhaps result in a large results set, eventually cause the OOME of members in cluster

```
Installing core
installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-enterprise/5.1-SNAPSHOT/hazelcast-enterprise-5.1-SNAPSHOT.jar
installing /home/ec2-user/.m2/repository/com/hazelcast/hazelcast-sql/5.1-SNAPSHOT/hazelcast-sql-5.1-SNAPSHOT.jar
HzMember2HZ Started 10.0.0.22 2003@ip-10-0-0-22.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzMember1HZ Started 10.0.0.96 2014@ip-10-0-0-96.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzMember3HZ Started 10.0.0.170 1984@ip-10-0-0-170.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzMember4HZ Started 10.0.0.107 1985@ip-10-0-0-107.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzClient4HZ Started 10.0.0.107 2287@ip-10-0-0-107.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzClient1HZ Started 10.0.0.96 2314@ip-10-0-0-96.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzClient2HZ Started 10.0.0.22 2303@ip-10-0-0-22.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
HzClient3HZ Started 10.0.0.170 2283@ip-10-0-0-170.ec2.internal /home/ec2-user/hz-root/hz-lib/5.1-SNAPSHOT
load_mapBak1Obj hzcmd.map.member.LoadInt driver=Member threads=1 duration=0 bench=Roll interval=0 keyDomain=10000000 name=mapBak1Obj
load_mapBak1Bin hzcmd.map.member.LoadInt driver=Member threads=1 duration=0 bench=Roll interval=0 keyDomain=10000000 name=mapBak1Bin
load_mapBak1HD hzcmd.map.member.LoadInt driver=Member threads=1 duration=0 bench=Roll interval=0 keyDomain=10000000 name=mapBak1HD
loadInt Done
size_mapBak1HD hzcmd.map.validate.Size driver=Member threads=1 duration=0 bench=Roll interval=0 size=10000000 name=mapBak1HD
size_mapBak1Bin hzcmd.map.validate.Size driver=Member threads=1 duration=0 bench=Roll interval=0 size=10000000 name=mapBak1Bin
size_mapBak1Obj hzcmd.map.validate.Size driver=Member threads=1 duration=0 bench=Roll interval=0 size=10000000 name=mapBak1Obj
validate Done
sql_mapBak1HD hzcmd.map.sql.service.selectAll driver=Client threads=4 duration=0 bench=Roll interval=0 valueClass=java.lang.Integer name=mapBak1HD
sql_mapBak1Obj hzcmd.map.sql.service.selectAll driver=Client threads=4 duration=0 bench=Roll interval=0 valueClass=java.lang.Integer name=mapBak1Obj
sql_mapBak1Bin hzcmd.map.sql.service.selectAll driver=Client threads=4 duration=0 bench=Roll interval=0 valueClass=java.lang.Integer name=mapBak1Bin
fail HzClient2HZ sql_mapBak1HD hzcmd.map.sql.service.selectAll threadId=0 com.hazelcast.sql.HazelcastSqlException: Cluster topology changed while a query was executed: Member cannot be reached: [10.0.0.96]:5701
output/HZ/HzClient3HZ/exception.txt
output/HZ/HzClient4HZ/exception.txt
output/HZ/HzMember1HZ/HzMember1HZ.hprof
output/HZ/HzClient2HZ/exception.txt

(base) [ec2-user@ip-10-0-0-252 sql-service-all]$ pwd
/disk1/workspace/stable-x4/5.1-SNAPSHOT/2021_11_03-07_50_10/sql-service-all
```

/disk1/workspace/stable-x4/5.1-SNAPSHOT/2021_11_03-07_50_10/sql-service-all

load generated from clients running repeated sql queries  
hzcmd.map.sql.service.selectAll
```
        sqlStatement.setSql("select * from \""+name+"\"");
        SqlResult sqlResult = sqlService.execute(sqlStatement);
        sqlResult.close();
```

verbosegc log

```
Problem Suspect 1

One instance of "com.hazelcast.map.impl.PartitionContainer[]" loaded by "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x80401238" occupies 1,432,417,440 (67.05%) bytes. The memory is accumulated in one instance of "com.hazelcast.map.impl.PartitionContainer[]", loaded by "jdk.internal.loader.ClassLoaders$AppClassLoader @ 0x80401238", which occupies 1,432,417,440 (67.05%) bytes.
```

Screenshot 2021-11-04 at 16 00 06

Screenshot 2021-11-04 at 16 03 37

http://jenkins.hazelcast.com/view/stable/job/stable-x4/
hz-bench-run-jenkins-stable hz/stress/sql-service-all 0

### PR DESCRIPTION
**Pull request by viliam-durina**
We used to re-create the ExecutionContext, if a data packet is received
after the execution terminated. This is quite likely to happen after a
failure or cancellation as executions are concurrently completing on
members (in 10% of cases in local tests).

We greatly mitigate by storing the failed execution IDs for 5 seconds
after they fail. The timeout is short reduce the amount of work in
query-heave scenarios, if it's not enough the old mechanism still
applies.

Fixes #19897

### CODE REVIEW

**Review by frant-hartm — APPROVED** [review]
LGTM, maybe we could also test that the `failedJobs` is also cleaned.

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java [hunk 1]
```diff
@@ -108,4 +117,42 @@ public void when_resultClosed_then_jobCancelled_withNoResults() {
...
+        assertTrueEventually(() -> {
+            String remainingContexts = contexts.stream()
+                    .map(c -> idToString(c.executionId()))
+                    .collect(Collectors.joining(", "));
+            assertEquals("remaining execIds: " + remainingContexts, 0, contexts.size());
+        }, 5);
+
+        // assert that failedJobs is also cleaned up
+        ConcurrentMap<Long, Long> failedJobs = jetService.getJobExecutionService().getFailedJobs();
+        assertTrueEventually(() -> assertEquals(0, failedJobs.size()));
```
Comment (frant-hartm) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java:156]: If you are worried about the test duration you could move this assertion to the previous `assertTrueEventually` block and increase the timeout there from 5 to some higher number (not sure what the exact number would be, the cleanup job runs every 1 second, the failedJobs has TTL 5 seconds, maybe there is something else that could cause a delay).

But because this test is also `ParallelJVMTest` I think it's ok as is.

**Review by frant-hartm — APPROVED** [review]

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java (hunk 1 above)
Comment (viliam-durina) [reply hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java:156]: That will not make the test faster, the time is measured since the last job fails. It's not triggered by the test.

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java [hunk 2]
```diff
@@ -108,4 +117,42 @@ public void when_resultClosed_then_jobCancelled_withNoResults() {
...
+        createMapping("map", Integer.class, Integer.class);
+
+        for (int i = 0; i < 100; i++) {
+            SqlResult result = sql.execute("SELECT * FROM map");
+            result.close();
+        }
+
+        JetServiceBackend jetService = getJetServiceBackend(instance());
+        Collection<ExecutionContext> contexts = jetService.getJobExecutionService().getExecutionContexts();
+        // assert that all ExecutionContexts are eventually cleaned up
```
Comment (ufukyilmaz) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlClientTest.java:146]: minor: could you also note that this assertion passes only if handling time of a network package from old execution doesn't exceed `JobExecutionService#FAILED_EXECUTION_EXPIRY_NS`(although this is not possible under normal load conditions)?

**Review by ufukyilmaz — APPROVED** [review]
It looks good to me. I just requested adding a note to the test so that it doesn't mislead anyone.
