### PR TITLE
Removed PID management from start/stop scripts

### LINKED ISSUE #15831: bin/start.sh only allows one process
Try starting two hazelcast instances using the `./bin/start.sh script. ` 

Because there is only very basic PID management it fails and asks the user to create another copy of the bin directory.  **This is poor user experience**.

I've tested other distributions from Redis and Kafka.  They provide more advanced PID management that allows running multiple processes.

Allow start.sh to run more processes without the need to copy the bin directory.  In hand with this the `/bin/stop.sh` script should take a PID.

### PR DESCRIPTION
**Pull request by alparslanavci**
Stop scripts now kill all instances running in the box.

Fixes:
https://github.com/hazelcast/hazelcast/issues/15831 
https://github.com/hazelcast/hazelcast/issues/15509
https://github.com/hazelcast/hazelcast/issues/11625

### CODE REVIEW

**Comment by alparslanavci** [comment]
verify

**Comment by alparslanavci** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
@jerrinot I added you as a reviewer. Feel free to review yourself or delegate to someone. This needs at least 2 reviewers.

**Comment by alparslanavci** [comment]
run-lab-run

**Comment by mesutcelik** [comment]
@alparslanavci Do we have to change anything in the reference manual, code samples etc.?

**Comment by alparslanavci** [comment]
@mesutcelik yes, we need to change the related [reference manual section](https://docs.hazelcast.org/docs/latest/manual/html-single/#using-the-scripts-in-the-package) and the readme file in Enterprise repo.

**Comment by mmedenjak** [comment]
Does this address https://github.com/hazelcast/hazelcast/issues/15509?

**Comment by alparslanavci** [comment]
run-lab-run

**Comment by alparslanavci** [comment]
@mmedenjak Yes, this also fixes #15509

File: hazelcast/src/main/resources/stop.sh [hunk 1]
```diff
@@ -1,21 +1,12 @@
...
-HAZELCAST_HOME=`cd "$PRGDIR/.." >/dev/null; pwd`
-PID_FILE="${HAZELCAST_HOME}"/bin/hazelcast_instance.pid
 
-if [ ! -f "${PID_FILE}" ]; then
-    echo "No hazelcast instance is running."
-    exit 0
-fi
+#### This script kills all the instances started with start.sh script.
+
+PIDS=$(ps ax | grep com.hazelcast.core.server.HazelcastMemberStarter | grep -v grep | awk '{print $1}')
```
[the remark this answers is not in the document]
Comment (alparslanavci) [reply hazelcast/src/main/resources/stop.sh]: Added 👍No need to add on Win script, since `taskkill` already prints some info.

File: hazelcast/src/main/resources/stop.sh [hunk 2]
```diff
@@ -1,21 +1,14 @@
...
```
Comment (kwart) [inline hazelcast/src/main/resources/stop.sh]: Could you consider this:
```bash
PIDS=$(pgrep -f HazelcastMemberStarter)
```

**Comment by kwart** [comment]
We could also give a try to a `java.exe` on the `%Path%` in the `start.bat`:

```batch
if "x%JAVA_HOME%" == "x" (
  echo The JAVA_HOME environment variable is not defined! Expecting java on the system PATH.
  set RUN_JAVA=java
) else (
  set "RUN_JAVA=%JAVA_HOME%\bin\java"
)
```

File: hazelcast/src/main/resources/start.bat [hunk 3]
```diff
@@ -25,30 +25,19 @@ if NOT "%MAX_HEAP_SIZE%" == "" (
...
-)
-
 ECHO ########################################
 ECHO # RUN_JAVA=%RUN_JAVA%
 ECHO # JAVA_OPTS=%JAVA_OPTS%
 ECHO # starting now...."
 ECHO ########################################
 
-start "hazelcast %CLASSPATH%" "%RUN_JAVA%" %JAVA_OPTS% -cp "%CLASSPATH%" "com.hazelcast.core.server.HazelcastMemberStarter"
+start "hazelcast-imdg" "%RUN_JAVA%" %JAVA_OPTS% -cp "%CLASSPATH%" "com.hazelcast.core.server.HazelcastMemberStarter"
```
Comment (kwart) [inline hazelcast/src/main/resources/start.bat]: I would suggest the same as for the shell script - run it directly in the foreground:

```batch
"%RUN_JAVA%" %JAVA_OPTS% -cp "%CLASSPATH%" "com.hazelcast.core.server.HazelcastMemberStarter"
```

File: hazelcast/src/main/resources/start.sh [hunk 4]
```diff
@@ -48,12 +47,4 @@ echo "# JAVA_OPTS=$JAVA_OPTS"
...
-PID=$(cat "${PID_FILE}");
-if [ -z "${PID}" ]; then
-    echo "Process ID for Hazelcast instance is written to location: {$PID_FILE}"
-    $RUN_JAVA -server $JAVA_OPTS com.hazelcast.core.server.HazelcastMemberStarter &
-    echo $! > ${PID_FILE}
-else
-    echo "Another Hazelcast instance (PID=${PID}) is already started in this folder. To start a new instance, please unzip hazelcast-${project.version}.zip/tar.gz in a new folder."
-    exit 0
-fi
+$RUN_JAVA -server $JAVA_OPTS com.hazelcast.core.server.HazelcastMemberStarter &
```
[the remark this answers is not in the document]
Comment (alparslanavci) [reply hazelcast/src/main/resources/start.sh]: 👍

File: hazelcast/src/main/resources/readme.html [hunk 5]
```diff
@@ -125,8 +125,8 @@ <h3 id="folders">Folders</h3>
 				<li><strong>hazelcast-full-example.xml</strong> &mdash; It is the Hazelcast IMDG configuration file that includes all the configuration elements and attributes with their descriptions.</li>
 				<li><strong>start.bat</strong> &mdash; Starts a Hazelcast IMDG member for Windows users.</li>
 				<li><strong>start.sh</strong> &mdash;  Starts a Hazelcast IMDG member for Linux users.</li>
-                                      <li><strong>stop.bat</strong> &mdash; Stops the current running Hazelcast IMDG member for Windows users.</li>
-                                      <li><strong>stop.sh</strong> &mdash; Stops the current running Hazelcast IMDG member for Linux users.</li>
+                                      <li><strong>stop.bat</strong> &mdash; Stops all of the running Hazelcast IMDG member for Windows users.</li>
```
[the remark this answers is not in the document]
Comment (alparslanavci) [reply hazelcast/src/main/resources/readme.html]: 👍

File: hazelcast/src/main/resources/stop.sh (hunk 2 above)
Comment (alparslanavci) [reply hazelcast/src/main/resources/stop.sh]: 👍

File: hazelcast/src/main/resources/start.bat (hunk 3 above)
Comment (alparslanavci) [reply hazelcast/src/main/resources/start.bat]: I kept this one the same, since it is already starting on a separate window.

**Comment by alparslanavci** [comment]
@kwart thank you for the comments, I applied the most of them. Can you please review again?
