### PR TITLE
Ensure cache is created in test

### LINKED ISSUE #16566: ClientCacheCreationTest recreateCacheOnRestartedCluster_whenMaxConcurrentInvocationLow
- Fails on `Hazelcast-3.x-IbmJDK8-fips-nightly`
- Fails on [Build #121 (Jan 25, 2020 9:11:16 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/121/testReport/com.hazelcast.client.cache/ClientCacheCreationTest/recreateCacheOnRestartedCluster_whenMaxConcurrentInvocationLow/)
- Error
```
Maximum invocation count is reached. maxConcurrentInvocations = 1
```
- Stack trace
```
com.hazelcast.core.HazelcastOverloadException: Maximum invocation count is reached. maxConcurrentInvocations = 1
	at com.hazelcast.spi.impl.sequence.FailFastCallIdSequence.handleNoSpaceLeft(FailFastCallIdSequence.java:43)
	at com.hazelcast.spi.impl.sequence.AbstractCallIdSequence.next(AbstractCallIdSequence.java:63)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.invoke(ClientInvocation.java:138)
	at com.hazelcast.client.cache.impl.ClientCacheHelper.createCacheConfig(ClientCacheHelper.java:101)
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.createCacheConfig(HazelcastClientCacheManager.java:143)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCacheInternal(AbstractHazelcastCacheManager.java:119)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCache(AbstractHazelcastCacheManager.java:147)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.createCache(AbstractHazelcastCacheManager.java:65)
	at com.hazelcast.client.cache.ClientCacheCreationTest.recreateCacheOnRestartedCluster_whenMaxConcurrentInvocationLow(ClientCacheCreationTest.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:811)
```
kindly check.

### PR DESCRIPTION
**Pull request by vbekiaris**
In `ClientCacheCreationTest` cache recreation is
tested with a low concurrent invocation limit.
With unlucky timing, the limit obstructs even the
original cache creation during test setup.

Fixes #16566 on `master`

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/client/cache/ClientCacheCreationTest.java [hunk 1]
```diff
@@ -120,7 +121,15 @@ public void recreateCacheOnRestartedCluster_whenMaxConcurrentInvocationLow() {
         HazelcastClientCachingProvider cachingProvider = createClientCachingProvider(client);
         final CacheManager cacheManager = cachingProvider.getCacheManager();
         MutableConfiguration configuration = new MutableConfiguration();
-        cacheManager.createCache("xmlCache", configuration);
+        // ensure cache is created despite the low concurrent invocation limit
+        while (true) {
```
Comment (ihsandemir) [inline hazelcast/src/test/java/com/hazelcast/client/cache/ClientCacheCreationTest.java]: Can you convert it to assertTrueEventually to avoid possibility of infinite wait? (practically can not be more than the test timeout anyway)

Comment (vbekiaris) [reply hazelcast/src/test/java/com/hazelcast/client/cache/ClientCacheCreationTest.java]: done

**Comment by vbekiaris** [comment]
run-lab-run
