### PR TITLE
[21785] Fix negative map hits [HZ-1313]

### LINKED ISSUE #21785: Incorrect map.hits metric value [HZ-1313]
**Describe the bug**
Incorrect `map.hits` metric values are reported by metrics started after the map is populated. If all members are started before the map is ppopulated - all members return correct values.

**Expected behavior**
All members should report a correct hits value, in this particular case 0.

**To Reproduce**
1. Run the following code:
```
package com.promanenko.scenarios.negative_metrics;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.map.IMap;

public class NegativeHitsMetric {

    public static void main(String[] args) throws InterruptedException {
        Config config = new Config().setClusterName("C-1");
        HazelcastInstance hazelcastInstance =
                Hazelcast.newHazelcastInstance(config);

        IMap<String, Object> map = hazelcastInstance.getMap("map-1");
        for (int i = 0; i < 100; i++) {
            map.put("key=" + i, "value-" + i);
        }

        Hazelcast.newHazelcastInstance(config);
        Hazelcast.newHazelcastInstance(config);
    }
}
```
2. Connect with Management Center and go to Maps screen
image

3. Only the first member reports correct `map.hits` metric value, all other members report negative values.

```
192.168.88.248:5701 [name=map-1,unit=count,metric=map.hits,excludedTargets={}] = 0
192.168.88.248:5702 [name=map-1,unit=count,metric=map.hits,excludedTargets={}] = -37
192.168.88.248:5703 [name=map-1,unit=count,metric=map.hits,excludedTargets={}] = -44
```

image

**Additional context**

Hazelcast 5.2-SNAPSHOT
Java 11

### PR DESCRIPTION
**Pull request by arodionov**
Negative `map.hits` metric values are reported by members started after the map is populated.
The cause of the issue is that the default `Record#getHits()` method returns -1.

Fixes #21785 

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Comment by arodionov** [comment]
run-lab-run

**Comment by arodionov** [comment]
run-lab-run

**Comment by arodionov** [comment]
run-ee-compile

File: hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java [hunk 1]
```diff
@@ -70,6 +70,11 @@ public boolean casCachedValue(Object expectedValue, Object newValue) {
         return true;
     }
 
+    @Override
+    public int getHits() {
```
Comment (ldziedziul) [inline hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java:74]: Shouldn't we change `Record#getHits` to return `0` as the default value?

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java:74]: Yes, that makes sense and is most intuitive. But it will be the exception from the `Record` class logic.
Let's @ahmetmircik comment on this, as a `Record` class author.

Comment (ldziedziul) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java:74]: From `UNSET` javadoc:
```
     * Represents an unset value. This is the default
     * value of ttl, max-idle or anything unavailable.
```
`hits` is a different kind of field than `ttl`, `max-idle` etc. It's just a counter AFAIK, so in the initial state it's natural to be equal to `0`. I think that `hits` is never `unavailable`

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java:74]: Good point!

**Comment by arodionov** [comment]
run-ee-compile

**Review by ldziedziul — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java (hunk 1 above)
Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java]: UNSET is used at places where no such stats is expected, by returning zero we loss this info and we cannot distinguish cases where stats is not available and where it is zero. And also in `EntryView` public api, we return -1, returning 0 also breaks that api. Seems it is better to keep it as is.

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java]: @ahmetmircik would you prefer to introduce the `SimpleRecord#getHits()` that returns 0?

File: hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java [hunk 2]
```diff
@@ -52,8 +51,27 @@
...
+        for (int i = 0; i < 100; i++) {
+            iMap.put(i, i);
+        }
+
+        HazelcastInstance instance2 = factory.newHazelcastInstance(getConfig());
+        HazelcastInstance instance3 = factory.newHazelcastInstance(getConfig());
+        waitAllForSafeState(instance1, instance2, instance3);
+        assertEquals(0, instance1.getMap("test-hits").getLocalMapStats().getHits());
+        assertEquals(0, instance2.getMap("test-hits").getLocalMapStats().getHits());
+        assertEquals(0, instance3.getMap("test-hits").getLocalMapStats().getHits());
```
Comment (ahmetmircik) [inline hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java:70]: Good have this test since putting a new entry should not generate hits, only updates and gets should generate it.
As far as i see, the main issue which makes hits < 0 is updating hits during replication. Removing that update should be sufficient to fix the issue behind this PR. 

@arodionov how does this sound?

**Review by ahmetmircik — CHANGES_REQUESTED** [review]
please see comments

File: hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java (hunk 1 above)
Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java]: Returning `UNSET` is fine. By this we can distinguish cases where `perEntryStatsEnabled` is true or false. It can only return 0 when `perEntryStatsEnabled` is true.

File: hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java (hunk 2 above)
Comment (arodionov) [reply hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java:70]: Is it that update?
https://github.com/arodionov/hazelcast/blob/e6a706fced9d3e69ee75fe5039e862d7f1ded325/hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/DefaultRecordStore.java#L234

File: hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java (hunk 1 above)
Comment (ldziedziul) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java]: > By this we can distinguish cases where `perEntryStatsEnabled` is true or false

Is that a bit hackish way of determining that?

Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/map/impl/record/SimpleRecord.java]: No, it is not, we create records based on `perEntryStatsEnabled` flag. What i was trying to say is, having an impossible value, it is -1 in this case, makes issues visible in the code as in this issue. Here when `perEntryStatsEnabled` is `false` we don't expect any hit. Otherwise, this issue could still be a latent error.

File: hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java (hunk 2 above)
Comment (ahmetmircik) [reply hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java:70]: yes, it should be that.

Comment (arodionov) [reply hazelcast/src/test/java/com/hazelcast/map/LocalMapStatsMultipleNodeTest.java:70]: I think in that case the enterprise version should also update https://github.com/hazelcast/hazelcast-enterprise/blob/master/hazelcast-enterprise/src/main/java/com/hazelcast/map/impl/recordstore/EnterpriseTieredRecordStore.java#L161

**Review by ahmetmircik — APPROVED** [review]

**Comment by ahmetmircik** [comment]
@arodionov will there be an EE counterpart?

**Comment by arodionov** [comment]
> @arodionov will there be an EE counterpart?

Yes, in a few minutes
