### PR TITLE
Fulfill correct JOIN clause validation

### LINKED ISSUE #20061: Incorrect error for batch-to-stream inner join or for stream-to-stream join
Here we throw an error saying `The right side of a LEFT JOIN or the left side of a RIGHT JOIN cannot be a streaming source`. But we do throw this error also for stream-to-stream join or to batch-to-stream INNER or CROSS or COMMA join.

https://github.com/hazelcast/hazelcast/blob/2cd6cc364be22165022b8a74be47d5dfd0cf6825/hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java#L332-L342

In case of batch-to-stream INNER join, we should also swap sides to convert it to stream-to-batch join, which is supported.

### PR DESCRIPTION
**Pull request by Fly-Style**
Fixes #20061

### CODE REVIEW

**Review by krzysztofslusarski — APPROVED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java [hunk 1]
```diff
@@ -352,22 +352,39 @@ protected void validateOrderList(SqlSelect select) {
...
-                if (containsStreamingSource(join.getLeft())) {
-                    throw newValidationError(join, RESOURCE.streamingSourceOnWrongSide());
+                if (leftInputIsStream) {
+                    throw newValidationError(join, RESOURCE.streamingSourceOnWrongSide("left", "RIGHT"));
                 }
                 break;
             case FULL:
                 throw QueryException.error(SqlErrorCode.PARSING, "FULL join not supported");
+            case INNER:
+                // Batch-to-stream INNER join, swap sides to convert it to stream-to-batch join, which is supported.
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java:376]: The swapping from batch-to-stream to stream-to-batch isn't implemented. And if it was, then INNER, COMMA and CROSS would work too, COMMA and CROSS is just a different syntax for INNER join.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java (hunk 1 above)
Comment (Fly-Style) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java:376]: https://github.com/hazelcast/hazelcast/issues/20486

**Review by viliam-durina — APPROVED** [review]
