### PR TITLE
Fix around midnight RowAssignmentTypeCoercionTest failures

### LINKED ISSUE #18962: com.hazelcast.jet.sql.impl.validate.RowAssignmentTypeCoercionTest
_master_ (commit 2cc059b39e18d5245f1019a4c4d523d6fe3454a3)

Failed on Sonar nightly build (Oracle JDK 11): http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-sonar/905/testReport/com.hazelcast.jet.sql.impl.validate/RowAssignmentTypeCoercionTest/

It can has the same cause as https://github.com/hazelcast/hazelcast/issues/18944

Following tests from `com.hazelcast.jet.sql.impl.validate.RowAssignmentTypeCoercionTest` failed with the same exception:
- `test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]`
- `test_insertSelect[TestParams{id=2013, srcType=TIME, targetType=TIMESTAMP WITH TIME ZONE, value=01:42:00, targetValue=2021-06-22T01:42Z, expectedFailureRegex=null}]`
- `test_update_columns[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]`
- `test_update_columns[TestParams{id=2013, srcType=TIME, targetType=TIMESTAMP WITH TIME ZONE, value=01:42:00, targetValue=2021-06-22T01:42Z, expectedFailureRegex=null}]`

Stacktrace (for `test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]` as an example):
```
java.lang.AssertionError: expected:<2021-06-22T01:42> but was:<2021-06-23T01:42>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.jet.sql.impl.validate.RowAssignmentTypeCoercionTest.test_insertSelect(RowAssignmentTypeCoercionTest.java:613)
	at jdk.internal.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Standard output (for `test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]` as an example):
```
Started Running Test: test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]
CREATE MAPPING src TYPE TestBatch OPTIONS ('names'='v', 'types'='TIME', 'values'='01:42:00')
00:03:26,777  INFO |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [RowAssignmentTypeCoercionTest] test_insertSelect - CREATE MAPPING target TYPE IMap OPTIONS('keyFormat'='int', 'valueFormat'='java', 'valueJavaClass'='com.hazelcast.sql.support.expressions.ExpressionValue$LocalDateTimeVal')
00:03:26,778  INFO |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [RowAssignmentTypeCoercionTest] test_insertSelect - SINK INTO target SELECT 0, v, 0 FROM src
00:03:26,779 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [JetSqlBackend] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Before logical opt:
LogicalTableModify(table=[[hazelcast, public, target[projects=[0, 1, 2, 3]]]], operation=[INSERT], flattened=[false])
  LogicalProject(__key=[0], field1=[CAST($0):TIMESTAMP], key=[0], this=[null:OBJECT])
    LogicalTableScan(table=[[hazelcast, public, src[projects=[0]]]])

00:03:26,780 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [JetSqlBackend] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] After logical opt:
InsertLogicalRel(table=[[hazelcast, public, target[projects=[0, 1, 2, 3]]]], operation=[INSERT], flattened=[false])
  ProjectLogicalRel(__key=[0], field1=[CAST($0):TIMESTAMP], key=[0], this=[null:OBJECT])
    FullScanLogicalRel(table=[[hazelcast, public, src[projects=[0]]]])

00:03:26,780 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [JetSqlBackend] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] After physical opt:
InsertPhysicalRel(table=[[hazelcast, public, target[projects=[0, 1, 2, 3]]]], operation=[INSERT], flattened=[false])
  ProjectPhysicalRel(__key=[0], field1=[CAST($0):TIMESTAMP], key=[0], this=[null:OBJECT])
    FullScanPhysicalRel(table=[[hazelcast, public, src[projects=[0]]]])

00:03:26,782 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [LightMasterContext] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing light job 0661-ca4c-ef40-0001, execution graph in DOT format:
digraph DAG {
	"TestBatch[public.src]" [localParallelism=1];
	"Project" [localParallelism=default];
	"Project(IMap[public.target])" [localParallelism=default];
	"IMap[public.target]" [localParallelism=1];
	"TestBatch[public.src]" -> "Project" [queueSize=1024];
	"Project" -> "Project(IMap[public.target])" [queueSize=1024];
	"Project(IMap[public.target])" -> "IMap[public.target]" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
00:03:26,782 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [LightMasterContext] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for 0661-ca4c-ef40-0001
00:03:26,782 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [LightMasterContext] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for 0661-ca4c-ef40-0001
00:03:26,782 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [InitExecutionOperation] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 0661-ca4c-ef40-0001, execution 0661-ca4c-ef40-0001 from [127.0.0.1]:5701
00:03:26,783 DEBUG |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [JobExecutionService] test_insertSelect - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for light job ID=0661-ca4c-ef40-0001, jobName='0661-ca4c-ef40-0001', executionId=0661-ca4c-ef40-0001 initialized, will start the execution
00:03:26,784 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '0661-ca4c-ef40-0001', execution 0661-ca4c-ef40-0001
00:03:26,784 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '0661-ca4c-ef40-0001', execution 0661-ca4c-ef40-0001 completed
00:03:26,953  INFO |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
00:03:26,954  INFO |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
00:03:26,954  INFO |test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog, hz:impl:mapService/target]
00:03:26,954 ERROR || - [EventServiceImpl] hz.dazzling_gates.event-1441 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] hz.dazzling_gates.event-1441 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@db451e7
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 7e7e5be1-d7f2-4104-a1b5-b4a109c62d74 this, name='__sql.catalog', numberOfEntriesAffected=2}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:159) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
BuildInfo right after test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}](com.hazelcast.jet.sql.impl.validate.RowAssignmentTypeCoercionTest): BuildInfo{version='5.0-SNAPSHOT', build='20210622', buildNumber=20210622, revision=2cc059b, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='5.0-SNAPSHOT', build='20210622', revision='2cc059b'}}
Hiccups measured while running test 'test_insertSelect[TestParams{id=2012, srcType=TIME, targetType=TIMESTAMP, value=01:42:00, targetValue=2021-06-22T01:42, expectedFailureRegex=null}](com.hazelcast.jet.sql.impl.validate.RowAssignmentTypeCoercionTest):'
00:03:25, accumulated pauses: 173 ms, max pause: 161 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by gierlachg**
Fixes #18962

### CODE REVIEW

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/validate/RowAssignmentTypeCoercionTest.java [hunk 1]
```diff
@@ -76,20 +81,20 @@
...
-                TestParams.passingCase(1006, NULL, BIGINT, "null", null, null),
-                TestParams.passingCase(1007, NULL, DECIMAL, "null", null, null),
-                TestParams.passingCase(1008, NULL, REAL, "null", null, null),
-                TestParams.passingCase(1009, NULL, DOUBLE, "null", null, null),
-                TestParams.passingCase(1010, NULL, TIME, "null", null, null),
-                TestParams.passingCase(1011, NULL, DATE, "null", null, null),
-                TestParams.passingCase(1012, NULL, TIMESTAMP, "null", null, null),
-                TestParams.passingCase(1013, NULL, TIMESTAMP_WITH_TIME_ZONE, null, null, null),
-                TestParams.passingCase(1014, NULL, OBJECT, "null", null, null),
+                TestParams.passingCase(1001, NULL, VARCHAR, "null", null, new Object[]{null}),
```
Comment (viliam-durina) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/validate/RowAssignmentTypeCoercionTest.java:84]: This looks simpler:
```suggestion
TestParams.passingCase(1001, NULL, VARCHAR, "null", null, (Object) null),
```

**Review by viliam-durina — APPROVED** [review]
