### PR TITLE
Fixed an intermittent failure in SqlNoDeserializationTest (#18135)

### LINKED ISSUE #18135: SqlNoDeserializationTest failures
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3636/

**server**
```
Error Message
Failed to resolve key metadata: java.io.IOException: KEY FAILURE
Stacktrace
com.hazelcast.sql.HazelcastSqlException: Failed to resolve key metadata: java.io.IOException: KEY FAILURE
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:76)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:241)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:207)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:203)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:144)
	at com.hazelcast.sql.misc.SqlNoDeserializationTest.testMember(SqlNoDeserializationTest.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.hazelcast.sql.impl.QueryException: Failed to resolve key metadata: java.io.IOException: KEY FAILURE
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:59)
	at com.hazelcast.sql.impl.calcite.parse.QueryParser.parse(QueryParser.java:78)
	at com.hazelcast.sql.impl.calcite.OptimizerContext.parse(OptimizerContext.java:135)
	at com.hazelcast.sql.impl.calcite.CalciteSqlOptimizer.prepare(CalciteSqlOptimizer.java:126)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:295)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:276)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:228)
	... 16 more
Caused by: com.hazelcast.sql.impl.QueryException: Failed to resolve key metadata: java.io.IOException: KEY FAILURE
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:67)
	at com.hazelcast.sql.impl.QueryException.error(QueryException.java:51)
	at com.hazelcast.sql.impl.schema.map.sample.MapSampleMetadataResolver.resolve(MapSampleMetadataResolver.java:81)
	at com.hazelcast.sql.impl.schema.map.PartitionedMapTableResolver.getFieldMetadata(PartitionedMapTableResolver.java:235)
	at com.hazelcast.sql.impl.schema.map.PartitionedMapTableResolver.getHeapMapFields(PartitionedMapTableResolver.java:180)
	at com.hazelcast.sql.impl.schema.map.PartitionedMapTableResolver.createTable(PartitionedMapTableResolver.java:120)
	at com.hazelcast.sql.impl.schema.map.PartitionedMapTableResolver.getTables(PartitionedMapTableResolver.java:73)
	at com.hazelcast.sql.impl.schema.SqlCatalog.<init>(SqlCatalog.java:42)
	at com.hazelcast.sql.impl.SqlServiceImpl.prepare(SqlServiceImpl.java:293)
	... 18 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: java.io.IOException: KEY FAILURE
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleException(SerializationUtil.java:103)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:214)
	at com.hazelcast.sql.impl.schema.map.sample.MapSampleMetadataResolver.resolve(MapSampleMetadataResolver.java:75)
	... 24 more
Caused by: java.io.IOException: KEY FAILURE
	at com.hazelcast.sql.misc.SqlNoDeserializationTest$PersonKey.readData(SqlNoDeserializationTest.java:240)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.readInternal(DataSerializableSerializer.java:160)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:106)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.read(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:44)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:208)
	... 25 more
```
**client**

```
Error Message
Failed to resolve key metadata: java.io.IOException: KEY FAILURE
Stacktrace
java.lang.AssertionError: Failed to resolve key metadata: java.io.IOException: KEY FAILURE
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.sql.misc.SqlNoDeserializationTest.testClient(SqlNoDeserializationTest.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by devozerov**
This PR fixes a flaky failure in the SqlNoDeserializationTest described in #18135

The test itself is pretty complicated - it forcefully fails the deserialization of the object, to ensure that we do not deserialize user classes during the query execution (see #18056). The problem is that our schema resolution routine still needs to deserialize user objects to derive the schema. To mitigate this, test attempts to cache the plan, so that we do not need to deserialize during the prepare phase on subsequent execution. Somehow, this caching didn't work. 

Probably, the reason was a race between an `IMap` population in the test, when we have a small period of time when it is empty, and the plan checker thread, that attempts to invalidate outdated plans. The fix is to ensure that we never have an empty `IMap` after we cached the plan.

Closes #18135.

### CODE REVIEW

File: hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java [hunk 1]
```diff
@@ -99,7 +100,7 @@ public void after() {
     private static Config config() {
         Config config = smallInstanceConfig();
 
-        config.addMapConfig(new MapConfig(MAP_NAME).setInMemoryFormat(InMemoryFormat.BINARY));
+        config.addMapConfig(new MapConfig(MAP_NAME).setInMemoryFormat(InMemoryFormat.BINARY).setBackupCount(0));
```
Comment (ahmetmircik) [inline hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java:103]: Why do we set backup count to zero here?

File: hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java [hunk 2]
```diff
@@ -207,8 +208,17 @@ private void populate(boolean fail) {
             localMap.put(new PersonKey(i, fail), new Person(fail));
         }
```
Comment (ahmetmircik) [inline hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java:210]: could you please add a short explanatory doc to this `populate` method?

File: hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java [hunk 3]
```diff
@@ -207,8 +208,17 @@ private void populate(boolean fail) {
...
-        member1.getMap(MAP_NAME).clear();
-        member1.getMap(MAP_NAME).putAll(localMap);
+        IMap<PersonKey, Person> map = member1.getMap(MAP_NAME);
+
+        map.putAll(localMap);
+
+        if (fail) {
+            for (int i = 0; i < KEY_COUNT; i++) {
+                map.remove(new PersonKey(i, false));
+            }
```
Comment (ahmetmircik) [inline hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java:218]: Test seems timing sensitive, if i insert, for instance 300 millis here, it fails.
 
```suggestion
            }
  sleepAtLeastMillis(300);

```

File: hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java (hunk 1 above)
Comment (devozerov) [reply hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java]: A leftover. Removed.

File: hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java (hunk 2 above)
Comment (devozerov) [reply hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java]: The method is simplified as explained in the next comment.

File: hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java (hunk 3 above)
Comment (devozerov) [reply hazelcast-sql-core/src/test/java/com/hazelcast/sql/misc/SqlNoDeserializationTest.java]: The timing problem could be caused by a periodic plan checker that attempts to invalidate suspicious plans. 
To make the test more reliable, I decided to rework it in favor of `Portable` objects. In SQL, we may need to deserialize the object in two cases: when building the schema, and when reading values from the user cursor. The goal of this test is to ensure that we do not do deserailziations in any other case, such as when transferring data between processes. If the object is `Portable`, we do not deserialize it when building the schema, because in this case, we extract fields directly from `Data`. Therefore, the change to the portable, removes exceptions during schema build, making the tests stable.

**Review by ahmetmircik — APPROVED** [review]

**Comment by viliam-durina** [comment]
@devozerov doesn't the change to Portable defuse the test? We never deserialized portables, even before #17591.

**Comment by devozerov** [comment]
@viliam-durina no, we deserialized them multiple times during the processing - when sending from member to member, and when sending from member to client. Now we do not do that. The only difference between portable and non-portable is that we do not deserialize them to build the schema, and to extract fields. But before the original fix, we deserialized them when doing `SELECT __key, this FROM map`, and one every transition between processes.

**Review by viliam-durina — APPROVED** [review]
