### PR TITLE
Ensure coherent state in DataConnectionConfig

### LINKED ISSUE #24533: NPE when 'type' is omitted from dynamic DataConnectionConfig [HZ-2425]
**Describe the bug**
When attempting to add a `DataConnectionConfig` dynamically via [Config.addDataConnectionConfig()](https://docs.hazelcast.org/docs/latest-dev/javadoc/com/hazelcast/config/Config.html#addDataConnectionConfig-com.hazelcast.config.DataConnectionConfig-), if the `type` isn't set, then calling the method will throw a `NullPointerException` either from the client or member (depending on the topology).

**Expected behavior**
The config should be validated, and an exception should be thrown with a message that explains that the Data Connection 'type' is required.

**To Reproduce**

The following unit test can be added to [DynamicConfigTest](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/internal/dynamicconfig/DynamicConfigTest.java) to demonstrate the issue:

```
    @Test
    public void testDataConnectionConfig_missingType() {
        Properties properties = new Properties();
        properties.setProperty("prop1", "val1");
        properties.setProperty("prop2", "val2");
        DataConnectionConfig dataConnectionConfig = new DataConnectionConfig()
                .setName("some-name")
                .setProperties(properties);

        try {
            driver.getConfig().addDataConnectionConfig(dataConnectionConfig);
        } catch (NullPointerException npe) {
            npe.printStackTrace();
            fail("Should not throw NPE");
        } catch (Throwable t) {   // Exception should have message with explanation
            assertTrue(true);
        }
    }
```

Member side:

```
java.lang.NullPointerException
	at com.hazelcast.dataconnection.impl.DataConnectionServiceImpl.createDataConnectionInstance(DataConnectionServiceImpl.java:138)
	at com.hazelcast.dataconnection.impl.DataConnectionServiceImpl.lambda$put$2(DataConnectionServiceImpl.java:103)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.hazelcast.dataconnection.impl.DataConnectionServiceImpl.put(DataConnectionServiceImpl.java:83)
	at com.hazelcast.dataconnection.impl.DataConnectionServiceImpl.createConfigDataConnection(DataConnectionServiceImpl.java:79)
	at com.hazelcast.internal.dynamicconfig.ClusterWideConfigurationService.registerConfigLocally(ClusterWideConfigurationService.java:335)
	at com.hazelcast.internal.dynamicconfig.AddDynamicConfigOperation.run(AddDynamicConfigOperation.java:48)
...
```

Client-side (when running the above test with [ClientDynamicClusterConfigTest](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/client/impl/clientside/ClientDynamicClusterConfigTest.java):

```
java.lang.NullPointerException
	at com.hazelcast.client.impl.protocol.codec.builtin.StringCodec.encode(StringCodec.java:29)
	at com.hazelcast.client.impl.protocol.codec.DynamicConfigAddDataConnectionConfigCodec.encodeRequest(DynamicConfigAddDataConnectionConfigCodec.java:93)
	at com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig.addDataConnectionConfig(ClientDynamicClusterConfig.java:1134)
	at com.hazelcast.internal.dynamicconfig.DynamicConfigTest.testDataConnectionConfig_missingType(DynamicConfigTest.java:704)
...
```

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Fixes #24533

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java [hunk 1]
```diff
@@ -181,6 +183,25 @@ public DataConnectionConfig setProperties(Properties properties) {
         return this;
     }
 
+    /**
+     * Checks if this configuration object is in coherent state - has all required properties set.
+     */
+    public void checkValidity() {
```
Comment (ldziedziul) [inline hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java:189]: why not simply `public void validate() {` ? ;)

**Review by ldziedziul — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java (hunk 1 above)
Comment (mdumandag) [reply hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java:189]: And, do we need to have this in the public API? Maybe we can also put `@PrivateApi` annotation here

**Review by mdumandag — APPROVED** [review]

**Review by k-jamroz — CHANGES_REQUESTED** [review]
all these checks can be enforced in constructor and setters - much safer solution. There are no cross-attribute checks

**Comment by TomaszGaweda** [comment]
@k-jamroz That would be awesome to have, but bare in mind how we allow users to create configuration objects:
```java
DataConnectionConfig dataConnectionConfig = new DataConnectionConfig()
                .setName("some-name")
                .setType("dummy")
                .setProperties(properties);
```
So it's impossible to use constructor and if user don't call a setter, then the issue is not discovered in early stage.

**Comment by k-jamroz** [comment]
Do you want to protect against clients sending manually prepared garbage data? If so, there are many places where such checks should be implemented consistently for security. CC: @kwart

**Comment by k-jamroz** [comment]
> @k-jamroz That would be awesome to have, but bare in mind how we allow users to create configuration objects:
> 
> ```java
> DataConnectionConfig dataConnectionConfig = new DataConnectionConfig()
>                 .setName("some-name")
>                 .setType("dummy")
>                 .setProperties(properties);
> ```
> 
> So it's impossible to use constructor and if user don't call a setter, then the issue is not discovered in early stage.

If we use object also as its builder then there is nothing we can do. We should have builder for such case, and builder would invoke all-args constructor. No-arg constructor is only for serialization and ideally should be private.

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
It's mostly for the UX - we want to inform user as quickly as possible with meaningful message (previously it was just NPE without a message).

I 100% agree that builders would be better - it's maybe something good to think about for 6.0

**Comment by k-jamroz** [comment]
> It's mostly for the UX - we want to inform user as quickly as possible with meaningful message (previously it was just NPE without a message).

Builder will improve UX and is easy to add even now. It it not a breaking change either - hiding public no-arg constructor will be.

> I 100% agree that builders would be better - it's maybe something good to think about for 6.0

6.0 is too late. And in the mean time we will have inconsistent invocations of `validate` and of course there will be places were we forget about it.

File: hazelcast/src/main/java/com/hazelcast/config/Config.java [hunk 2]
```diff
@@ -3152,6 +3152,7 @@ public Config setDataConnectionConfigs(Map<String, DataConnectionConfig> dataCon
      */
     @Beta
     public Config addDataConnectionConfig(DataConnectionConfig dataConnectionConfig) {
+        dataConnectionConfig.validate();
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/config/Config.java:3155]: you miss the validation in `setDataConnectionConfigs`

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java [hunk 3]
```diff
@@ -181,6 +184,26 @@ public DataConnectionConfig setProperties(Properties properties) {
         return this;
     }
 
+    /**
+     * Checks if this configuration object is in coherent state - has all required properties set.
+     */
+    @PrivateApi
+    public void validate() {
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java:191]: if we really what to do the validation post-creation, then it would be better to have a dedicated validator util class similar to `TieredStoreConfigValidator`, so we do not pollute the API.

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java [hunk 4]
```diff
@@ -181,6 +184,26 @@ public DataConnectionConfig setProperties(Properties properties) {
...
+        List<String> errors = new ArrayList<>();
+        if (name == null || name.isEmpty()) {
+            errors.add("Data connection name must be non-null and contain text");
+        }
+        if (type == null || type.isEmpty()) {
+            errors.add("Data connection type must be non-null and contain text");
+        }
+        if (properties == null) {
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java:199]: `properties == null` can't happen

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java [hunk 5]
```diff
@@ -181,6 +184,26 @@ public DataConnectionConfig setProperties(Properties properties) {
         return this;
     }
 
+    /**
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java:187]: not caused by this PR: `setProperty` is not overridden in `DataConnectionConfigReadOnly`

Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java]: Nice catch!

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java (hunk 4 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java]: A bit paranoic check ;) If someone edited via reflection for whatever reason (e.g. serialization framework)

File: hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java (hunk 3 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/config/DataConnectionConfig.java]: Done 864528a727a29a37e9d99fe1353876bef2b806ce and later

File: hazelcast/src/main/java/com/hazelcast/config/Config.java (hunk 2 above)
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/config/Config.java]: 864528a727a29a37e9d99fe1353876bef2b806ce

File: hazelcast/src/main/java/com/hazelcast/dataconnection/impl/DataConnectionServiceImpl.java [hunk 6]
```diff
@@ -80,6 +80,7 @@ public void createConfigDataConnection(DataConnectionConfig config) {
     }
 
     private void put(DataConnectionConfig config, DataConnectionSource source) {
+        config.validate();
```
[the remark this answers is not in the document]
Comment (TomaszGaweda) [reply hazelcast/src/main/java/com/hazelcast/dataconnection/impl/DataConnectionServiceImpl.java]: a51b8a29fc5cd16b3f18f7498a956f29cefb1e22 - checking in XML/YAML

**Review by k-jamroz — APPROVED** [review]

**Comment by TomaszGaweda** [comment]
run-lab-run
