### PR TITLE
Fix limit-offset extraction for sorts with projections

### LINKED ISSUE #19096: Once I add the TO_TIMESTAMP_TZ time function to the SQL query, the LIMIT doesn't work any more.
**Describe the bug**

Once I add the TO_TIMESTAMP_TZ time function to the SQL query, the LIMIT doesn't work any more.

This query returns 10 rows, as per the limit clause:
`select trades.symbol, trades.price, trades."timestamp", symbols.this from trades JOIN symbols ON symbols.__key = trades.symbol WHERE symbol = 'ELECU' AND price > 2500 ORDER BY "timestamp" DESC LIMIT 10;`

This query returns all rows, ignoring the limit:
`select trades.symbol, trades.price, TO_TIMESTAMP_TZ(trades."timestamp"), symbols.this from trades JOIN symbols ON symbols.__key = trades.symbol WHERE symbol = 'ELECU' AND price > 2500 ORDER BY "timestamp" DESC LIMIT 10;`

**Expected behavior**

LIMIT should kick in and reduce the output to 10 rows in both cases.

**To Reproduce**

1. Get the the [realtime-trade-monitor](https://github.com/hazelcast/hazelcast-demos/tree/master/realtime-trade-monitor) 
2. Upgrade the Hazelcast dependency in the demo from 5.0-SNAPSHOT to 5.0-BETA-1
3. Add the hazelcast-sql dependency to the jet-server module
4. Follow the instructions to load symbols and ingest trades. 
5. Start an SQL console (`hz-cli sql`).
6. Try both queries

**Additional context**

- I've used the hz-cli from 5.0-BETA-1 ZIP distribution

### PR DESCRIPTION
**Pull request by ivanthescientist**
Fixes #19096

### CODE REVIEW

**Comment by ivanthescientist** [comment]
run-lab-run

**Comment by ivanthescientist** [comment]
run-lab-run

**Review by hakanmemisoglu — APPROVED** [review]
LGTM.

Just minor comment. There are 2 test examples using JOIN to produce Project node on top of Sort node. However, we do not need JOIN to do it, you can additionally run a query like:
`SELECT a FROM t ORDER BY f(a) OFFSET 1 LIMIT 1;`. You can add it to test this simpler query too.

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlOrderByWithProjectionTest.java [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+                + "ORDER BY t0.this DESC "
+                + "LIMIT 5 OFFSET 2");
+
+        final List<Object> c1s = results.stream().map(m -> m.get("c1")).collect(Collectors.toList());
+
+        assertEquals(5, results.size());
+        assertEquals(Arrays.asList(8L, 7L, 6L, 5L, 4L), c1s);
+    }
+
+    private List<Map<String, Object>> execute(String sql) {
```
Comment (gierlachg) [inline hazelcast-sql/src/test/java/com/hazelcast/sql/SqlOrderByWithProjectionTest.java:79]: `SqlTestSupport.assertRowsEventuallyInAnyOrder()` could be adapted to handle both (ordered and unordered) cases.

**Comment by ivanthescientist** [comment]
Unfortunately at the moment it would be challenging to find another way to trigger use of Jet Engine specifically without a JOIN, I'm not sure if there are any functions that are supported by Jet only. Thus the presence of JOINs in the tests.

**Comment by gierlachg** [comment]
You could use file, kafka or generator to trigger usage of Jet engine. Also, such test could be simple part of existing `SqlLimitTest`.

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlLimitTest.java [hunk 2]
```diff
@@ -195,6 +197,25 @@ public void limitWithNegativeDynamicParameter() {
                 .hasMessageContaining("LIMIT value cannot be negative");
     }
 
+    @Test
+    public void limitWithProjection() {
+        final String sql = "SELECT ABS(v) "
```
Comment (gierlachg) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlLimitTest.java:202]: I would use a projection that alters the output, `ABS` actually leaves it _untouched_.

Comment (ivanthescientist) [reply hazelcast-sql/src/test/java/com/hazelcast/jet/sql/SqlLimitTest.java:202]: Don't think it matters at all in this case though. Optimizer can't get rid of it because we don't have any rules that would simplify calls in case the input is fixed and as long as projection is there, the test verifies exactly what it should - that limit works with projections present.

**Review by gierlachg — APPROVED** [review]
