### PR TITLE
Throw descriptive Exception when field is missing

### LINKED ISSUE #17404: Improve PortableGenericRecordBuilder missing fields handling
Using `PortableGenericRecordBuilder` all the fields from the `ClassDefinition` must be written. In case they are not, an exception is thrown, however it does not help the user to spot the exact cause of the problem.

```
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.internal.serialization.impl.portable.PortableGenericRecord'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:115) ~[hazelcast-4.1-SNAPSHOT.jar:4.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:175) ~[hazelcast-4.1-SNAPSHOT.jar:4.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:151) ~[hazelcast-4.1-SNAPSHOT.jar:4.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:136) ~[hazelcast-4.1-SNAPSHOT.jar:4.1-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:124)
        ...
Caused by: java.lang.NullPointerException
	at com.hazelcast.internal.serialization.impl.portable.PortableGenericRecord.readInt(PortableGenericRecord.java:101) ~[hazelcast-4.1-SNAPSHOT.jar:4.1-SNAPSHOT]
```

An exception with proper name and/or description should be used.

### PR DESCRIPTION
**Pull request by sancar**
Make GenericRecord.Builder#build method throw
a HazelcastSerializaitonException with missing field info
instead of NullPointerException

fixes #17404

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2067/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2067/Hazelcast-pr-builder-2067.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   QueueSplitBrainTest>SplitBrainTestSupport.testSplitBrain:195->SplitBrainTestSupport.doIteration:207->onAfterSplitBrainHealed:157 ? ConcurrentModification
[INFO] 
[ERROR] Tests run: 31209, Failures: 0, Errors: 1, Skipped: 976
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by sancar** [comment]
test failure is unrelated and reported here https://github.com/hazelcast/hazelcast/issues/17412

File: hazelcast/src/test/java/com/hazelcast/genericrecord/GenericRecordBuilderTest.java [hunk 1]
```diff
@@ -101,4 +101,20 @@ public void run() {
...
+
+    @Test
+    public void testUnwrittenFieldsThrowException() {
+        ClassDefinition classDefinition =
+                new ClassDefinitionBuilder(TestSerializationConstants.PORTABLE_FACTORY_ID, TestSerializationConstants.NAMED_PORTABLE)
+                        .addUTFField("name").addIntField("myint").build();
+
+        GenericRecord.Builder builder = GenericRecord.Builder.portable(classDefinition);
+        builder.writeInt("myint", 1);
+        assertThrows(HazelcastSerializationException.class, new Runnable() {
```
Comment (puzpuzpuz) [inline hazelcast/src/test/java/com/hazelcast/genericrecord/GenericRecordBuilderTest.java:113]: nit this assertion (and other similar ones in this test) can be simplified to `assertThrows(HazelcastSerializationException.class, builder::build);`

**Review by puzpuzpuz — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/portable/PortableGenericRecordBuilder.java [hunk 2]
```diff
@@ -29,25 +29,39 @@
...
+     * @return newly created GenericRecord
+     * @throws HazelcastSerializationException if a field is not written when building with builder from
+     *                                         {@link GenericRecord.Builder#portable(ClassDefinition)} and
+     *                                         {@link GenericRecord#newBuilder()}
+     */
     @Override
     public GenericRecord build() {
+        if (!isClone) {
+            for (int i = 0; i < isWritten.length; i++) {
+                if (!isWritten[i]) {
```
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/portable/PortableGenericRecordBuilder.java:59]: if i do cloneWithBuilder (all isWritten fields are false) and i only overwrite one field, some fields of isWritten will be left as false, right? and this check would fail? am i missing something here?

Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/portable/PortableGenericRecordBuilder.java:59]: If you do clone with the builder this check will not be done. see ` if (!isClone) {` at the beginning. 
I have a test that verifies the behavior.

**Review by ihsandemir — APPROVED** [review]
