### PR TITLE
Prevent division by zero for fast repeat operations

### LINKED ISSUE #11605: ConsoleApp throws division by zero ArithmeticException for repeat operations which are fast enough
The `ConsoleApp` has a division by zero issue for repeat operations (starts with `"#"`) which are quick enough.

```
hazelcast[default] > #5 m.put $i $i
null
null
null
null
null
java.lang.ArithmeticException: / by zero
	at com.hazelcast.console.ConsoleApp.handleCommand(ConsoleApp.java:222)
	at com.hazelcast.console.ConsoleApp.start(ConsoleApp.java:171)
	at com.hazelcast.console.ConsoleApp.main(ConsoleApp.java:1539)
```

### PR DESCRIPTION
**Pull request by kwart**
Fixes #11605.

@mmedenjak Should I send a PR with the commit to 3.9 branch too?

### CODE REVIEW

**Comment by mmedenjak** [comment]
@kwart there's no need to send to 3.9 as I don't see this as a critical issue. It's fine having it in 3.9.1

File: hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java [hunk 1]
```diff
@@ -218,8 +218,12 @@ protected void handleCommand(String inputCommand) {
             for (int i = 0; i < repeat; i++) {
                 handleCommand(command.substring(first.length()).replaceAll("\\$i", "" + i));
             }
-            long elapsedSeconds = MILLISECONDS.toSeconds(Clock.currentTimeMillis() - started);
-            println("ops/s = " + repeat / elapsedSeconds);
+            long elapsedMilliSeconds = Clock.currentTimeMillis() - started;
+            if (elapsedMilliSeconds > 0) {
+                println(String.format("ops/s = %.2f", (double) repeat * 1000 / elapsedMilliSeconds));
+            } else {
+                println("Bingo, all the operations finished in no time!");
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/console/ConsoleApp.java]: I really like this comment!
