### PR TITLE
Fix number interpretation for memcache protocol implementation 

### LINKED ISSUE #19644: Memcache client's `incr` command does not work correctly
**Describe the bug**
The `incr` command in the [memcached protocol implementation](https://docs.hazelcast.com/hazelcast/5.0/clients/memcache.html) doesn't behave as the real memcached server.

**Expected behavior**
Below is  how a regular memcached server behaves when you call `incr` on a key with the value "5":
```bash
$ printf "set mykey 0 0 1\r\n5\r\nincr mykey 1\r\n" | tee commands.txt
set mykey 0 0 1
5
incr mykey 1
$ cat commands.txt | nc localhost 11211
STORED
6
```
`mykey` is initially assigned to 5, and when incremented, becomes 6.

**To Reproduce**
Running the same commands on a Hazelcast server with memcached protocol enabled:

```
$ JAVA_OPTS="-Dhz.network.memcache-protocol.enabled=true" ./bin/hz-start -d
$ printf "set mykey 0 0 1\r\n5\r\nincr mykey 1\r\n"  | nc localhost 5701
STORED
54
```
It returns the ASCII code of the character '6', which is 54.

**Additional context**

I think the problem is with how IncrementCommandProcessor interprets values. The [memcached protocol states](https://github.com/memcached/memcached/blob/ddee3e27a031be22f5f28c160be18fd3cb9bc63d/doc/protocol.txt#L350-L357) that the value should be treated as the decimal representation of a 64-bit unsigned integer. However, Hazelcast's implementation treats each byte of the data as if they were the digits of a base-256 number (see [this line](https://github.com/hazelcast/hazelcast/blob/400f6b07a1c1d0281a53831b5768dedf612ee84d/hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java#L89) and [byteArrayToLong](https://github.com/hazelcast/hazelcast/blob/400f6b07a1c1d0281a53831b5768dedf612ee84d/hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/MemcacheCommandProcessor.java#L46)) and therefore returns the ASCII code of the digit. The situation becomes even weirder when multi-digit numbers are used.

### PR DESCRIPTION
**Pull request by yemreinci**
<PR description here>

Fixes #19644.

The way in which the number values and parameters were interpreted for the `incr` and `decr` commands was incorrect. It was due to a fallacy with the spymemcached client, which was used to test the implementation. Consider the snippet below.
```java
spyClient.set("key", /*expiration=*/0, /*value=*/10);
spyClient.incr("key", 1);
```
If a regular Memcached server is used to run this example, the `incr` call will fail. (see related [SO question](https://stackoverflow.com/questions/13077324/using-incr-with-spymemcached-client)) This is because when a value of integer type is passed to spymemcached's `MemcacheClient.set()`, it will convert the number into a byte array using [this method](https://github.com/couchbase/spymemcached/blob/eb5d6eeaf5b3b6f74eda3e3cf709e70f7bb4c4ad/src/main/java/net/spy/memcached/transcoders/TranscoderUtils.java#L42-L61). However, the Memcached server expects the value to be a decimal number when the `incr` command is called on it. 

Hazelcast's memcached implementation allowed the above incorrect example to work by using the same encoding mechanism for numbers, which didn't conform with the standard. 

This PR changes the implementation of `incr` and `decr` commands to strictly follow [the memcached protocol specification](https://github.com/memcached/memcached/blob/56dc81db316a0b957415e371d20c683fea9d7d2f/doc/protocol.txt#L347-L390). The changes are:
1. The parameter for `incr` and `decr` commands are changed to be a `long` and read using `Long.readUnsignedLong`.
2. The value to be incremented is interpreted using `Long.readUnsignedLong` and the result is written using `Long.toUnsignedString`.
3. A new test class is added that uses a raw TCP socket instead of a memcached client library. It includes most of the previous tests and adds extra edge case tests for increment and decrement commands. I can include more edge cases if suggested.
4. The old increment/decrement tests that fail on a regular Memcached server are modified to follow the standard.

To make sure the behavior defined by the tests was correct, I ran them against a regular Memcached server too.

This PR will break code that depend on the previous incorrect behavior.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [x] Request reviewers if possible
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Comment by yemreinci** [comment]
What should be the `Module:` label for this PR? 
I see there is `Module: REST` but nothing about Memcached.

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java [hunk 1]
```diff
@@ -0,0 +1,614 @@
...
+        writer.write(line + CRLF);
+        writer.flush();
+    }
+
+    /**
+     * Tries to receive a response line from the server,
+     * calls Assert.fail() if nothing was received in 1 second.
+     * @return received line
+     */
+    private String receiveLine() throws Exception {
```
Comment (sancar) [inline hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:556]: @yemreinci Why did you need a a timeout ? 
Can't we just make this a blocking call ?

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java [hunk 2]
```diff
@@ -68,31 +71,23 @@ public void handle(IncrementCommand incrementCommand) {
...
+            MemcacheEntry entry = entryConverter.toEntry(incrementCommand.getKey(), value);
 
-            final byte[] value1 = entry.getValue();
-            final long current = (value1 == null || value1.length == 0) ? 0 : byteArrayToLong(value1);
-            long result = -1;
-            result = incrementCommandTypeCheck(incrementCommand, result, current);
+            String currentCachedValue = bytesToString(entry.getValue());
 
-            incrementCommand.setResponse(concatenate(stringToBytes(String.valueOf(result)), RETURN));
-            MemcacheEntry newValue = new MemcacheEntry(key, longToByteArray(result), entry.getFlag());
```
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:94]: Can we delete `longToByteArray` methods? It looks like there are no usage left.

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java [hunk 3]
```diff
@@ -0,0 +1,614 @@
...
+                lineFuture.complete(null);
+            }
+        });
+        t.start();
+
+        String line = null;
+        try {
+            line = lineFuture.get(1000, TimeUnit.MILLISECONDS);
+        } catch (TimeoutException e) {
+            t.interrupt();
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:572]: I am not sure if the `hasNextLine` is interruptable but I assume the thread we have created will be ended after the input stream of the socket is closed in the tearDown

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 1 above)
Comment (yemreinci) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:556]: We can, and it would work. But if somehow, in the future, the implementation gets broken and starts to return an error for, say, a get call, the test will expect 2 lines but the server will send only one. And the test will hang indefinitely on CI or sth and that would be hard to debug.

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java (hunk 2 above)
Comment (yemreinci) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:94]: Yes, we can. I'll do that.

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 3 above)
Comment (yemreinci) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:572]: How do we know whether sth is interruptable in Java? The documentation says it can block, so I assume it does some sort of I/O call at some point (poll, select etc.).
If you can think of a better way to implement this method, I can do that. This was the best I could come up with.

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 1 above)
Comment (yemreinci) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:556]: Also, while implementing it I didn't get it right in the first time, of course, and hit this timeout. So it was better to have tests that failed instead of ones that hang indefinitely. 
If you have a better suggestion on how to implement a receiveLine() with timeout, please say. This was the best I could do with my Java knowledge.

Comment (yemreinci) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:556]: Hmm, actually, there is `@Time(timeout = x)`. Would it be better if I get rid of the timeout logic from this method and put timeout on tests individually? I would have to put different timeouts for each each test though, because some of them take more time than the others. (the one that tests expiration, for example).

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java [hunk 4]
```diff
@@ -111,18 +106,34 @@ public void handleRejection(IncrementCommand incrementCommand) {
...
+            if (Long.compareUnsigned(current, incrementAmount) < 0) {
+                // underflow
+                return "0";
+            } else {
+                return Long.toUnsignedString(current - incrementAmount);
+            }
+        } else {
+            assert false;
+            return "";
+        }
```
[the remark this answers is not in the document]
Comment (yemreinci) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:129]: What would be better I thought was using inheritance. I thought of moving common parts to a parent abstract CounterCommand class, and implementing IncrementCommand and DecrementCommand as childs that override doIncrement. I couldn't be bothered to implement that and wasn't sure would worth it but what do you think about the idea?

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 1 above)
Comment (sancar) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:556]: I think we don't need any timeout on the tests. Think of this similar to any operation on the API. For example, we are not putting a timeout to tests because `IMap.get()` might hang forever. 
The worst case is that, a test build will timeout and we will find the problem.

**Review by sancar — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (mdumandag) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:129]: I think we can leave it as it is, without introducing the inheritance logic you described. 

Regarding this code, I feel like switch would be a better fit, but I don't have a strong opinion about it. I think we just need to get rid of the `assert false; return "";` part with something like an `IllegalStateException`, as we don't expect to hit that line

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 3 above)
Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:572]: I don't know a way either. I just started a `nc` server that just listens and wrote a similar code to yours and saw that `hasNextLine` is not interrupted. It returns when in fact there is a next line or the input stream is closed, which happens in the tearDown method anyway.

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (yemreinci) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:129]: I don't have a strong opinion about if/switch too, the previous code was using if and I modified it. I'll change it to throw illegal state for the impossible case.

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java (hunk 2 above)
Comment (yemreinci) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:94]: [Done](https://github.com/hazelcast/hazelcast/pull/19653/commits/60dfe60edede117803f35dec5c117e151e101b35#diff-f994c6ca2d7177aa4fda391bba69665b94aa22b206aa38db6e0fd695edc09a1c).

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java [hunk 5]
```diff
@@ -68,31 +71,23 @@ public void handle(IncrementCommand incrementCommand) {
...
-                    throw ExceptionUtil.rethrow(e);
-                }
-            }
+            MemcacheEntry entry = entryConverter.toEntry(incrementCommand.getKey(), value);
 
-            final byte[] value1 = entry.getValue();
-            final long current = (value1 == null || value1.length == 0) ? 0 : byteArrayToLong(value1);
-            long result = -1;
-            result = incrementCommandTypeCheck(incrementCommand, result, current);
+            String currentCachedValue = bytesToString(entry.getValue());
```
[the remark this answers is not in the document]
Comment (yemreinci) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java:78]: If value1 (`entry.getValue()`) is of size 0, then `currentCachedValue` will be an empty string. And `Long.parseUnsignedLong("")` will throw a `NumberFormatException`. This is no different than trying to increment a value "foo", for example. I added a new test `testIncrement_onEmptyValue_shouldFail` for this case, just to be safe though. Note that the previous implementation treated empty strings as 0, and that was incorrect.

About `value1 == null`, I don't think it's possible. `entry` comes either from an IMap or constructed in `EntryConverter.toEntry`. If it came from an IMap, then it is deserialized using its `readData` method, which sets the `value` variable to a nonnull value. If it was constructed in `toEntry`, then again, it can't be null.

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (yemreinci) [reply hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/IncrementCommandProcessor.java]: Done.

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 1 above)
Comment (yemreinci) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java:563]: OK, removed the timeout logic in https://github.com/hazelcast/hazelcast/pull/19653/commits/d5de9ed6f98dc3ad3eb91f9f95cf641803660bf3

File: hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java (hunk 3 above)
Comment (yemreinci) [reply hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcachedRawTcpTest.java]: Thanks for checking. Anyways, I removed the timeout logic, it will simply block forever if no there is no data to read.

**Comment by yemreinci** [comment]
run-lab-run

**Review by mdumandag — APPROVED** [review]
