### PR TITLE
Public API for SQL (#17042)

### LINKED ISSUE #17042: SQL: Introduce public API
We should introduce a public API for the SQL engine. General considerations:

1. **Service** - SQL should be accessed through a new service interface exposed from `HazelcastInstance`. Old predicate API was exposed from the `IMap` interface. This approach doesn't work for us because SQL could access multiple `IMap`-s and other data sources, such as `ReplicatedMap` or Jet connectors.

2. **Do not use JDBC interfaces** - it might be tempting to re-use JDBC `Connection/Statement/ResultSet` interfaces. They are well-known to users and part of JDK. The problem is that these interfaces are much more complex than most users need: you need to instantiate a lot of intermediate objects, remember to close them properly, handle checked exceptions, etc. Our API will be much simpler, while still reusing some ideas from JDBC.

3. **SqlQuery** object - when running a query user may need to pass various configuration properties in addition to the query itself. This includes parameters, timeout, page size, schema name, etc. Trying to expose them in a flat form will lead to a combinatorial explosion of a number of methods. Therefore, we will introduce `SqlQuery` class to encapsulate the state. Simple shortcut method for the most common case - query string and parameters - will be exposed as well:
```java
class SqlQuery {
    String schema;
    String sql;
    Object[] params;
    long timeout;
    ...
}

interface SqlService {
    SqlResult execute(SqlQuery query);
  
    default SqlResult execute(String sql, Object... params) {
        return execute(new SqlQuery(sql, params));
    }
}
```

4. **Result types** - SQL may return different types of results: rows for `SELECT` and some other commands (such as `SHOW`), update count for other DML statements, void for DDL. We will expose the result type through an enum:
```java
enum SqlResultType {
    ROWS,
    UPDATE_COUNT,
    VOID
}
```

5. **Result** - will encapsulate the result. For `ROWS` we will expose an `Iterator` as opposed to `Set` in the old predicate API. The result will be `AutoCloseable` to allow users to stop query execution before all rows are consumed. Also, it will implement `Iterable` interface to allow for convenient consumption of rows. Last, it will expose row metadata so that the user knows type of values within a row:
```java
interface SqlResult extends Iterable<SqlRow>, AutoCloseable  {
    SqlResultType resultType();
    long updateCount();
    SqlRowMetadata rowMetadata();
    Iterator<SqlRow> iterator(); // Inherited from Iterable
    void close();                // Inherited from AutoCloseable
}
```

6. **Row** - provides access to row data. At the moment we will only expose a generic accessor. In future we may want to add specialized versions, such as `getInt`, `getLong`, etc. Row will also expose own metadata, so that it could be introspected without the parent `SqlResult`:
```java
interface SqlRow {
    Object getObject(int index);
    SqlRowMetadata rowMetadata();
}
```

7. **No support for multi-result queries** - consider the query string `SELECT ... FROM r; SELECT ... FROM s`. This query string consists of two actual queries, and hence two results should be returned. We will not support such use cases at the moment, even though JDBC interfaces support it. The reason is that they are not used widely, but adds considerable complexity to both API and implementation. Many JDBC implementations don't support them as well. If needed, we will add support for such queries later like this:
```java
interface SqlService {
    ...
    List<SqlResult> executeMultiple(...);
}
```

8. **No support for sessions** - we will not support any kind of sessions in the first release. If we understand that there are important use cases in 4.1 where they are absolutely needed, we will add them separately. Sessions should not affect already described API much.

### PR DESCRIPTION
**Pull request by devozerov**
This PR introduces a public API for the SQL engine.

The PR mostly follow what was discussed in #17042. Major highlights:
1. SQL API is exposed as a new service: `HazelcastInstance.getSqlService()`
1. Major API parts: `SqlService`, `SqlQuery`, `SqlResult`, `SqlRow`
1. There are no result types yet, the only possible result is a set of rows. Other result types will be added as we progress with DDL/DML
1. Query parameters are exposed to the public API but are not supported internally. The proper parameter support requires the Calcite-related type inference part, which is not ready yet

Closes #17042

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1205/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1205/Hazelcast-pr-builder-1205.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientDynamicConfigurationAwareConfigTest>DynamicConfigurationAwareConfigTest.testDecorateAllPublicMethodsFromTest:61 Method public com.hazelcast.config.SqlConfig com.hazelcast.config.Config.getSqlConfig() is declared by class com.hazelcast.config.Config whilst it should be declared by class com.hazelcast.client.impl.clientside.ClientDynamicClusterConfig
[INFO] 
[ERROR] Tests run: 27784, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+ */
+
+package com.hazelcast.sql;
+
+/**
+ * Service to execute SQL queries.
+ */
+public interface SqlService {
+    /** Unique service name. */
+    String SERVICE_NAME = "hz:impl:sqlService";
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:24]: I think these are not meant to be public - seems we're conflating the public "SQL service" with the internal "Hazelcast SQL Service Implementation"

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+    /**
+     * Execute query.
+     *
+     * @param sql SQL.
+     * @param params Parameters.
+     * @return Cursor.
+     */
+    default SqlResult query(String sql, Object... params) {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:33]: in Jet we have `@Nonnull` and `@Nullable` annotations for all public method return types and parameters, I think this is done in IMDG as well, seems to be missing here perhaps?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+
+/**
+ * Service to execute SQL queries.
+ */
+public interface SqlService {
+    /** Unique service name. */
+    String SERVICE_NAME = "hz:impl:sqlService";
+
+    /**
+     * Execute query.
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:27]: how about some examples here, the javadoc seems too barren?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 4]
```diff
@@ -0,0 +1,274 @@
...
+import java.util.List;
+import java.util.Objects;
+
+/**
+ * Definition of the SQL query.
+ * <p>
+ * This object is mutable. Properties are read once before the execution is started.
+ * Changes to properties do not affect the behavior of already running queries.
+ */
+public class SqlQuery implements Serializable {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:33]: is it a good idea to use Java serialization here? Given this can be sent between different minor versions

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+     * <p>
+     * The class of the returned value depends on the SQL type of the column.
+     *
+     * @see #getRowMetadata()
+     * @see SqlColumnMetadata#getType()
+     * @param columnIndex Column index, 0-based.
+     * @return Value of the column.
+     * @throws IndexOutOfBoundsException If column index is out of bounds.
+     */
+    Object getObject(int columnIndex);
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java:34]: would it make sense to provide getter for primitive types? or a method that supports generics so you don't need explicit casting? i.e  `<T> T get(int index)`

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+import java.util.ArrayList;
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+import java.util.stream.Collectors;
+
+/**
+ * SQL row metadata.
+ */
+public class SqlRowMetadata implements Serializable {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:30]: See same concern about `SqlQuery`

**Comment by jerrinot** [comment]
It would be nice to have a proper `toString` in the `SqlRow` implementations. 
That would improve the "first 3 minutes experience"

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+    public SqlColumnMetadata getColumn(int index) {
+        if (index < 0) {
+            throw new IndexOutOfBoundsException("Column index cannot be negative: " + index);
+        }
+
+        if (index >= columns.size()) {
+            throw new IndexOutOfBoundsException("Column index is out of bounds: " + index);
+        }
+
+        return columns.get(index);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:76]: These checks are perfectly handled by the list implementation, throw the same type of exception. 
```suggestion
        return columns.get(index);
```
We should also document that we throw in case of and out-of-bounds index, some other methods return null.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+     * from {@link SqlRow}.
+     *
+     * @see SqlRow
+     * @param name Column name (case sensitive).
+     * @return Column index or {@link #COLUMN_NOT_FOUND} if a column with the given name is not found.
+     */
+    public int findColumn(String name) {
+        Integer index = nameToIndex.get(name);
+
+        return index != null ? index : COLUMN_NOT_FOUND;
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:90]: This can be simplified to:
```suggestion
        return nameToIndex.getOrDefault(name, COLUMN_NOT_FOUND);
```

But I'm not sure this is a good design. If one refers to a column by name, it's a programming error to use a name not present in the query. I don't expect people to use this method to probe for the existence of a column.

The `SqlRow` class only has index-based access to values, if one uses:
```java
int fooIndex = metadata.findColumn('foo_column');
Object value = row.getObject(fooIndex);
```
he will get "column index out of range: -1" instead of "column 'foo_column' doesn't exist".

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+        if (index >= columns.size()) {
+            throw new IndexOutOfBoundsException("Column index is out of bounds: " + index);
+        }
+
+        return columns.get(index);
+    }
+
+    /**
+     * Find index of the column with the given name. Returned index can be used to get column value
+     * from {@link SqlRow}.
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:81]: We should specify here whether the name is case sensitive.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+        int result = name.hashCode();
+
+        result = 31 * result + type.hashCode();
+
+        return result;
+    }
+
+    @Override
+    public String toString() {
+        return '[' + name + ':' + type + ']';
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java:90]: We could use the sql syntax `name + ' ' + type`. Also the `[]` suggest a collection, but it's a tuple, i'd just use none.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java [hunk 11]
```diff
@@ -0,0 +1,55 @@
...
+    }
+
+    @Override
+    public SqlRowMetadata getRowMetadata() {
+        return rowMetadata;
+    }
+
+    private void checkIndex(int index) {
+        if (index < 0 || index >= rowMetadata.getColumnCount()) {
+            throw new IllegalArgumentException("Column index is out of range: " + index);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java]: The `getObject` method declares to throw IIOBE in this case.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java (hunk 1 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlService.java]: Removed. This service name is only required by a client implementation (which is not ready yet). It will be located in a private class.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 4 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java]: Agree. This was not part of the original proposal. I added it to provide some convenience to users but didn't think about compatibility. 
Removed now.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 6 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java]: Removed.

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1216/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1216/Hazelcast-pr-builder-1216.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DataSerializableConventionsTest.test_serializableClasses_areIdentifiedDataSerializable:161 There are 3 classes which are Serializable, not @BinaryInterface-annotated and are not IdentifiedDataSerializable.
[INFO] 
[ERROR] Tests run: 3856, Failures: 1, Errors: 0, Skipped: 14
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java (hunk 2 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlService.java]: Added annotations to public API. Please double-check that it looks good now.

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1217/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1217/Hazelcast-pr-builder-1217.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClientReliableTopicOnClusterRestartTest.shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant:185->lambda$shouldFail_OnClusterRestart_whenDataLoss_notLossTolerant$5:187
[INFO] 
[ERROR] Tests run: 27820, Failures: 1, Errors: 0, Skipped: 1001
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

File: hazelcast-sql/src/main/java/com/hazelcast/sql/impl/calcite/SqlToQueryType.java [hunk 12]
```diff
@@ -66,6 +66,9 @@
         CALCITE_TO_HZ.put(SqlTypeName.DATE, QueryDataType.DATE);
         CALCITE_TO_HZ.put(SqlTypeName.TIMESTAMP, QueryDataType.TIMESTAMP);
         CALCITE_TO_HZ.put(SqlTypeName.TIMESTAMP_WITH_LOCAL_TIME_ZONE, QueryDataType.TIMESTAMP_WITH_TZ_OFFSET_DATE_TIME);
+
+        HZ_TO_CALCITE.put(QueryDataTypeFamily.OBJECT, SqlTypeName.ANY);
+        CALCITE_TO_HZ.put(SqlTypeName.ANY, QueryDataType.OBJECT);
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast-sql/src/main/java/com/hazelcast/sql/impl/calcite/SqlToQueryType.java:71]: This will be clarified as a part of the expressions PR. There are no expressions of support in the current PR.

File: hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java [hunk 13]
```diff
@@ -0,0 +1,154 @@
...
+
+        return this;
+    }
+
+    /**
+     * Gets the timeout in milliseconds that is applied to queries without an explicit timeout.
+     *
+     * @return Timeout in milliseconds.
+     */
+    public long getQueryTimeout() {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java:120]: I think it's a good convention to use something like `queryTimeoutMillis` because if you're editing the config file, the unit is not  always obvious. I think this convention is followed in rest of the config.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java [hunk 14]
```diff
@@ -0,0 +1,89 @@
...
+ */
+
+package com.hazelcast.sql;
+
+import javax.annotation.Nonnull;
+
+/**
+ * SQL column metadata.
+ */
+public class SqlColumnMetadata {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java:24]: should make the class `final` as it's public

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java [hunk 15]
```diff
@@ -0,0 +1,89 @@
...
+
+    private final String name;
+    private final SqlColumnType type;
+
+    public SqlColumnMetadata(String name, SqlColumnType type) {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java:29]: missing annotations (it's public class).

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java [hunk 16]
```diff
@@ -0,0 +1,87 @@
...
+import java.time.LocalDate;
+import java.time.LocalDateTime;
+import java.time.LocalTime;
+import java.time.OffsetDateTime;
+
+/**
+ * SQL column type.
+ */
+public enum SqlColumnType {
+    /** VARCHAR type, represented by {@link java.lang.String} */
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java:30]: does this qualify as standard Javadoc format so it's picked up by the generator?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlException.java [hunk 17]
```diff
@@ -0,0 +1,53 @@
...
+
+/**
+ * An exception occurred during SQL query execution.
+ */
+public class SqlException extends HazelcastException {
+
+    private final UUID originatingMemberId;
+    private final int code;
+
+    public SqlException(UUID originatingMemberId, int code, String message, Throwable cause) {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlException.java:32]: missing annotations

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 18]
```diff
@@ -0,0 +1,286 @@
...
+
+    /** Default page size. */
+    public static final int DEFAULT_CURSOR_BUFFER_SIZE = 4096;
+
+    private String sql;
+    private List<Object> parameters;
+    private long timeout = DEFAULT_TIMEOUT;
+    private int cursorBufferSize = DEFAULT_CURSOR_BUFFER_SIZE;
+
+    public SqlQuery(String sql) {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:49]: missing annotation

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 19]
```diff
@@ -0,0 +1,119 @@
...
+import java.util.ArrayList;
+import java.util.HashMap;
+import java.util.List;
+import java.util.Map;
+import java.util.stream.Collectors;
+
+/**
+ * SQL row metadata.
+ */
+public class SqlRowMetadata {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:31]: should also consider making this final

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 20]
```diff
@@ -0,0 +1,119 @@
...
+    /** Constant indicating that the column is not found. */
+    public static final int COLUMN_NOT_FOUND = -1;
+
+    private final List<SqlColumnMetadata> columns;
+    private final Map<String, Integer> nameToIndex;
+
+    public SqlRowMetadata(List<SqlColumnMetadata> columns) {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:38]: missing annotation

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlResultImpl.java [hunk 21]
```diff
@@ -0,0 +1,106 @@
...
+import com.hazelcast.sql.impl.state.QueryState;
+
+import javax.annotation.Nonnull;
+import java.util.Iterator;
+import java.util.NoSuchElementException;
+
+/**
+ * Cursor implementation.
+ */
+public class SqlResultImpl implements SqlResult {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/SqlResultImpl.java:33]: no `toString` implementation for this class, is that intentional?

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java [hunk 22]
```diff
@@ -0,0 +1,98 @@
...
+    }
+
+    private void checkIndex(int index) {
+        if (index < 0 || index >= rowMetadata.getColumnCount()) {
+            throw new IndexOutOfBoundsException("Column index is out of range: " + index);
+        }
+    }
+
+    @Override
+    public String toString() {
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java:86]: might be nice to document this in the interface

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 23]
```diff
@@ -0,0 +1,119 @@
...
+     * @return The number of columns in the row.
+     */
+    public int getColumnCount() {
+        return columns.size();
+    }
+
+    /**
+     * Get column metadata.
+     *
+     * @param index Column index, 0-based.
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:62]: veery minor but typically the javadoc for `@param` statements start in lower case everywhere else

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 24]
```diff
@@ -0,0 +1,286 @@
...
+    public long getTimeout() {
+        return timeout;
+    }
+
+    /**
+     * Sets the query timeout in milliseconds.
+     * <p>
+     * If the timeout is reached for a running query, it will be cancelled forcefully.
+     * <p>
+     * Zero value means no timeout. {@value #TIMEOUT_NOT_SET} means that the value from {@link SqlConfig#getQueryTimeout()} will
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:178]: We should also create a constant for the value of 0.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 18 above)
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:49]: We should also mark this argument as nonnull. Also elsewhere.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlResultImpl.java (hunk 21 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/SqlResultImpl.java:33]: You mean to produce some string view of the whole result? We can't iterate the iterator here because it's a mutating operation. Years ago I had an issue that displaying a variable in the debugger called the `toString` and it lazy-loaded the value and then I couldn't reproduce my issue. If we want to format the results somehow, it should be a special method where we could document it, not `toString`.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java (hunk 15 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java:29]: Maybe we can mark this as `@PrivateApi`, it's not meant to be use by the users.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java (hunk 16 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java:30]: Of course...

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 9 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:76]: It is specified in the parameter JavaDoc.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java (hunk 10 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 8 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java]: This is a common practice in Java. See `String.indexOf` or `ResultSet.findColumn`. 
Access by column name has been added: `SqlRow#getObject(String)`

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 7 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java]: As discussed, these checks are intentional to make the API behavior stable irrespective of the underlying implementation.

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlErrorTest.java [hunk 25]
```diff
@@ -0,0 +1,369 @@
...
+    public void testTimeout() {
+        // Start two instances and fill them with data
+        HazelcastInstance instance1 = factory.newHazelcastInstance();
+        HazelcastInstance instance2 = factory.newHazelcastInstance();
+
+        IMap<Long, Long> map = instance1.getMap(MAP_NAME);
+
+        for (long i = 0; i < DATA_SET_SIZE; i++) {
+            map.put(i, i);
+        }
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast-sql/src/test/java/com/hazelcast/sql/SqlErrorTest.java]: Applied batched putAll as suggested.

File: hazelcast-sql/src/main/java/com/hazelcast/sql/impl/calcite/parse/QueryConverter.java [hunk 26]
```diff
@@ -85,7 +89,14 @@ public RelNode convert(SqlNode node) {
...
 
-        return relTrimmed;
+        // 5. Collect original field names.
+        List<String> fieldNames = new ArrayList<>(root.fields.size());
+
+        for (Pair<Integer, String> field : root.fields) {
+            fieldNames.add(field.right);
+        }
+
+        return new QueryConvertResult(relTrimmed, fieldNames);
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast-sql/src/main/java/com/hazelcast/sql/impl/calcite/parse/QueryConverter.java]: Applied.

File: hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd [hunk 27]
```diff
@@ -4937,6 +4938,54 @@
...
+        </xs:annotation>
+        <xs:all>
+            <xs:element name="executor-pool-size" type="xs:unsignedInt" minOccurs="0" maxOccurs="1">
+                <xs:annotation>
+                    <xs:documentation>
+                        Sets the number of threads responsible for query execution.
+                        Normally the value of this parameter should be equal to the number of CPU cores.
+                        Setting the value to less than the number of CPU cores will limit the degree of parallelism of the SQL
+                        subsystem. This may be beneficial if you would like to prioritize other CPU-intensive workloads on the
+                        same machine.
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd:4956]: Applied the same approach as in Jet. Now, -1 is used as a default. Thanks for the suggestion.

File: hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd [hunk 28]
```diff
@@ -4937,6 +4938,54 @@
...
+            </xs:element>
+            <xs:element name="operation-pool-size" type="xs:unsignedInt" minOccurs="0" maxOccurs="1">
+                <xs:annotation>
+                    <xs:documentation>
+                        Sets the number of threads responsible for network operations processing.
+                        When Hazelcast members execute a query, they send commands to each other over the network to coordinate
+                        the execution. This includes requests to start or stop query execution, or a request to process a batch
+                        of data. These commands are processed in a separate operation thread pool, to avoid frequent interruption
+                        of running query fragments.
+                        The default value should be good enough for the most workloads. You may want to increase the default
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd]: Added the default value (-1)

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java (hunk 5 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java]: Reverted back to `<T> T getObject(...)` approach, as it seems that the community is in agreement that it is more user-friendly. 
Also, added `<T> T getObject(String columnName)` overload for convenience.
There will be no specialized methods in the first release (e.g. `getInt(...)`) because it requires additional considerations on the desired behavior (e.g. how to deal with nullability, whether to perform implicit conversions, etc).

**Comment by devozerov** [comment]
@jerrinot `SqlRowImpl.toString()` the method has been added:
1. It outputs the row in the following format `[age INT=40, name VARCHAR=John]`
1. The relevant `SqlRowMetadata` will be shown as `[age INT, name VARCHAR]`
1. The relevant `SqlColumnMetadata` will be shown as `age INT` and `name VARCHAR`

Let me know if you have any comments on this.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java [hunk 29]
```diff
@@ -0,0 +1,66 @@
...
+     * The class of the returned value depends on the SQL type of the column. No implicit conversions are performed on the value.
+     *
+     * @see #getMetadata()
+     * @see SqlRowMetadata#findColumn(String)
+     * @see SqlColumnMetadata#getName()
+     * @see SqlColumnMetadata#getType()
+     * @param columnName Column name.
+     * @return Value of the column
+     * @throws NullPointerException If column name is null
+     * @throws IllegalArgumentException If a column with the given name is not found
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java:55]: What about adding this?
```
@throws ClassCastException If the type of the column type isn't assignable to the type {@code T}.
```
It's not strictly correct because the CCE is not thrown by this method but when the result of this method is assigned, but it might help to understand the issue.

It also might help to put a blank line between the blocks of `@see`, `@param` and `@throws` lines, the javadoc renderer also groups it.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlServiceImpl.java [hunk 30]
```diff
@@ -16,52 +16,79 @@
...
+        int operationPoolSize = config.getOperationPoolSize();
+        long queryTimeout = config.getQueryTimeoutMillis();
 
-        NodeServiceProviderImpl nodeServiceProvider = new NodeServiceProviderImpl(nodeEngine);
+        if (executorPoolSize == SqlConfig.DEFAULT_EXECUTOR_POOL_SIZE) {
+            executorPoolSize = Runtime.getRuntime().availableProcessors();
+        }
+
+        if (operationPoolSize == SqlConfig.DEFAULT_OPERATION_POOL_SIZE) {
+            operationPoolSize = Runtime.getRuntime().availableProcessors();
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/SqlServiceImpl.java:82]: This used to be `Math.min(8, Runtime.getRuntime().availableProcessors())`, was the change intentional?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java (hunk 3 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlService.java]: Added example and general overview to the `SqlService` JavaDoc. Please let me know if you have ant comments.

File: hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java (hunk 13 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java]: Applied the suggestion.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java (hunk 16 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java:30]: From the Oracle docs [1]:
> This tag is valid in all documentation comments: overview, package, class, interface, constructor, method and **field**

[1] https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDDIECH

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlResultImpl.java (hunk 21 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/SqlResultImpl.java:33]: There is nothing to expose here. Row and row metadata do have `toString` implementations.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlException.java [hunk 31]
```diff
@@ -0,0 +1,51 @@
...
+ */
+
+package com.hazelcast.sql;
+
+import com.hazelcast.core.HazelcastException;
+
+import java.util.UUID;
+
+/**
+ * An exception occurred during SQL query execution.
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlException.java:25]: But parsing is a part of query execution, isn't it?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java [hunk 32]
```diff
@@ -0,0 +1,71 @@
...
+     * @return Iterator.
+     * @throws IllegalStateException If the method is invoked more than once.
+     * @throws SqlException In case of an SQL-related error condition.
+     */
+    @Override
+    @Nonnull
+    Iterator<SqlRow> iterator();
+
+    /**
+     * Release the resources associated with the query result.
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java:64]: Not really. Cancellation is not common use case. The aim of this docs is to stress out that the query result is stateful, and the state must be released via a call to `close`. That is, it is used to avoid resource leaks in the first place, no to do a cancellation. Moreover, a call to close may or may not trigger a cancellation. Therefore, the proposed change is not accurate.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/extract/GenericFieldExtractor.java [hunk 33]
```diff
@@ -44,10 +45,14 @@ public GenericFieldExtractor(
...
+            return type.normalize(extractors.extract(getTarget(), path, null));
+        } catch (QueryDataTypeMismatchException e) {
+            throw QueryException.dataException("Failed to extract map entry " + (key ? "key" : "value") + " field \""
+                + path + "\" because of type mismatch [expectedClass=" + e.getExpectedClass().getName()
+                + ", actualClass=" + e.getActualClass().getName() + ']');
         } catch (Exception e) {
-            throw QueryException.dataException("Cannot extract " + (key ? "key" : "value") + " field \"" + path
-                + "\" of type " + type + ": " + e.getMessage(), e);
+            throw QueryException.dataException("Failed to extract map entry " + (key ? "key" : "value") + " field \""
+                + path + "\": " + e.getMessage(), e);
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/extract/GenericFieldExtractor.java:55]: The exception class is accessible from `getCause()`.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlException.java (hunk 31 above)
[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlException.java:25]: Well, depends on how you look at it, but you can say so. I leave it up to you, this comment is very minor.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 24 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java]: Added a constant.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 18 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 20 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 19 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java]: Done.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 18 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java]: Done

File: hazelcast/src/main/java/com/hazelcast/sql/SqlException.java (hunk 17 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlException.java]: Fixed

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java (hunk 15 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java (hunk 14 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlServiceImpl.java (hunk 30 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/SqlServiceImpl.java:82]: Math.min was very old heuristics with no proven value. It is simplified now.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java (hunk 29 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRow.java:55]: Fixed

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java [hunk 34]
```diff
@@ -0,0 +1,90 @@
...
+/**
+ * SQL column metadata.
+ */
+public final class SqlColumnMetadata {
+
+    private final String name;
+    private final SqlColumnType type;
+
+    @SuppressWarnings("ConstantConditions")
+    public SqlColumnMetadata(@Nonnull String name, @Nonnull SqlColumnType type) {
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java:30]: What about marking this constructor a `@PrivateApi`? It's not supposed to be used by the users, we might add more metadata to it.
Also `SqlRowMetadata`, maybe also `SqlException`.

Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnMetadata.java:33]: Agreed, fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlException.java [hunk 35]
```diff
@@ -0,0 +1,51 @@
...
+
+    /**
+     * @return ID of the member where the error occurred.
+     */
+    public UUID getOriginatingMemberId() {
+        return originatingMemberId;
+    }
+
+    /**
+     * @return Error code from {@link SqlErrorCode}.
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlException.java:50]: Removed OK.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java (hunk 22 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/SqlRowImpl.java:86]: Could you please clarify what do you mean by this?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java (hunk 16 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlColumnType.java:30]: Resolving for now. Please re-open the conversation if you foresee any problems with these JavaDocs.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 23 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java]: Applied to `@param`, `@return`, `@throws`.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 36]
```diff
@@ -0,0 +1,280 @@
...
+    }
+
+    /**
+     * Gets query parameters.
+     *
+     * @return Query parameters.
+     */
+    @Nonnull
+    public List<Object> getParameters() {
+        return parameters != null ? parameters : Collections.emptyList();
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java]: Agree, fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 37]
```diff
@@ -0,0 +1,271 @@
...
+    public SqlQuery(String sql) {
+        setSql(sql);
+    }
+
+    /**
+     * Copying constructor.
+     */
+    private SqlQuery(String sql, List<Object> parameters, long timeout, int cursorBufferSize) {
+        this.sql = sql;
+        this.parameters = parameters;
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:60]: Fixed, thanks for spotting this.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlException.java (hunk 31 above)
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlException.java:26]: I propose to leave it as is since most users will not even aware of the parsing step as a separate internal execution stage.

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java [hunk 38]
```diff
@@ -452,6 +453,13 @@
      */
     @Nonnull CPSubsystem getCPSubsystem();
 
+    /**
+     * Returns SQL service.
+     *
+     * @return SQL service.
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:459]: I agree that these comments do not add any value. At the same time, JavaDoc without body or return tag may look aesthetically inconsistent in both IDE, or when converted to HTML. E.g. JDK chooses the approach with repetition. When you look at missing part of JavaDoc the question is whether this is a bug or an intentional omission. With explicit docs it is clear - there is just no more useful information to add.

Therefore I'd prefer to keep it as is, given that we do not have any hard project-wide rules for one or the other approach, and both formatting options could be found in different parts of the API.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/NodeEngine.java [hunk 39]
```diff
@@ -114,6 +115,13 @@
      */
     SplitBrainProtectionService getSplitBrainProtectionService();
 
+    /**
+     * Gets SQL service.
+     *
+     * @return the SQL service
+     */
+    SqlServiceImpl getSqlService();
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/NodeEngine.java:123]: Resolving this to keep the discussion in a single place (see the comment above).

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java (hunk 38 above)
[the remark this answers is not in the document]
Comment (cangencer) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:459]: given that this is the entry point to the API, I think it warrants more than a trivial comment? Perhaps a sentence or two about it wouldn't hurt.

[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:459]: Rendered in IntelliJ, how _aesthetically consistent_ is this?
image

Maybe we could replace the `@return` with `@see SqlService`. That's also duplicate, one can click on the return type, but it suggests that there's something interesting and related in there.

[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:459]: Also, should be marked with `@NonNull`.

[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java]: We do not go into details in `HazelcastInstance`, because extended JavaDocs are provided in the returned objects. I added a reference to `SqlService` in the method's JavaDoc.

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java [hunk 40]
```diff
@@ -452,6 +453,15 @@
...
     @Nonnull CPSubsystem getCPSubsystem();
 
+    /**
+     * Returns a service to execute distributed SQL queries.
+     *
+     * @return SQL service
+     *
+     * @see SqlService
+     */
+    @Nonnull SqlService getSql();
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:463]: Shouldn't we also mark this method as `@Beta`?

Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:463]: I think it is sufficient to mark the service itself as `@Beta`. The method `HazelcastInstance.getSql` is not in the beta state on its own. It is the service that it provides is in the beta status. We used this pattern for all other `@Beta` usages.

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:463]: I agree it's technically sufficient, but we're trying to make it as clear as possible for the users. All APIs available through this method are beta, so even though if this method itself is not, there's nothing you can do with it if you want to avoid beta.

I would even document the state of the development here or in the `SqlService` class docs. It will set expectations and reduce disillusionment.

File: hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd [hunk 41]
```diff
@@ -4937,6 +4938,57 @@
...
+                        The default value -1 sets the pool size equal to the number of CPU cores, and should be good enough
+                        for the most workloads.
+                        Setting the value to less than the number of CPU cores may improve the overall performance on machines
+                        with large CPU count, because it will decrease the number of context switches.
+                        It is not recommended to set the value of this parameter greater than the number of CPU cores because it
+                        may decrease the system's overall performance due to excessive context switches.
+                    </xs:documentation>
+                </xs:annotation>
+            </xs:element>
+            <xs:element name="query-timeout-millis" type="xs:unsignedLong" minOccurs="0" maxOccurs="1">
```
Comment (petrpleshachkov) [inline hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd:4979]: What is the default value of this parameter? Shall we add it to the schema definition?

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java [hunk 42]
```diff
@@ -0,0 +1,961 @@
...
+    public InMemoryFormat inMemoryFormat;
+
+    @Parameters(name = "cursorBufferSize:{0}, dataSetSize:{1}, serializationMode:{2}, inMemoryFormat:{3}")
+    public static Collection<Object[]> parameters() {
+        List<Object[]> res = new ArrayList<>();
+
+        for (int pageSize : PAGE_SIZES) {
+            for (int dataSetSize : DATA_SET_SIZES) {
+                for (SerializationMode serializationMode : SerializationMode.values()) {
+                    for (InMemoryFormat format : new InMemoryFormat[] { InMemoryFormat.OBJECT, InMemoryFormat.BINARY }) {
```
Comment (petrpleshachkov) [inline hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java:120]: Shall we create a similar run for HD?

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java [hunk 43]
```diff
@@ -0,0 +1,961 @@
...
+
+            Iterator<SqlRow> rowIterator = res.iterator();
+
+            while (rowIterator.hasNext()) {
+                SqlRow row = rowIterator.next();
+
+                assertEquals(rowMetadata, res.getRowMetadata());
+
+                Long key0 = row.getObject(rowMetadata.findColumn(adjustFieldName("key")));
+                assert key0 != null;
```
Comment (petrpleshachkov) [inline hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java:188]: Maybe use` assertNotNull()` instead?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 44]
```diff
@@ -0,0 +1,289 @@
...
+import java.util.List;
+import java.util.Objects;
+
+/**
+ * Definition of a SQL query.
+ * <p>
+ * This object is mutable. Properties are read once before the execution is started.
+ * Changes to properties do not affect the behavior of already running queries.
+ */
+public class SqlQuery {
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:33]: AFAIU, this is a public class, shall we make it `final` ?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 45]
```diff
@@ -0,0 +1,289 @@
...
+    /** Value for the timeout that is not set. */
+    public static final long TIMEOUT_NOT_SET = -1;
+
+    /** Value for the timeout that is disabled. */
+    public static final long TIMEOUT_DISABLED = 0;
+
+    /** Default timeout. */
+    public static final long DEFAULT_TIMEOUT = TIMEOUT_NOT_SET;
+
+    /** Default page size. */
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:43]: Not sure that I understand which page we are talking about? Maybe use "portion" instead?

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java (hunk 40 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:465]: Ok, agree. Added `@Beta` annotation to `HazelcastInstance.getSql`. Regarding concrete capabilities - it is nearly impossible to list and maintain the list of supported features. In SQL this is the goal of documentation.

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java (hunk 42 above)
Comment (devozerov) [reply hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java:120]: HD is not supported in the scope of this PR

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java [hunk 46]
```diff
@@ -0,0 +1,289 @@
...
+     */
+    @Nonnull
+    public SqlQuery addParameter(Object parameter) {
+        parameters.add(parameter);
+
+        return this;
+    }
+
+    /**
+     * Clear query parameters.
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:151]: Minor: "Clears query parameters" to be consistent with the rest of the JavaDoc

File: hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd (hunk 41 above)
Comment (devozerov) [reply hazelcast-spring/src/main/resources/hazelcast-spring-4.1.xsd]: Fixed in both XSD files.

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java (hunk 43 above)
Comment (devozerov) [reply hazelcast-sql/src/test/java/com/hazelcast/sql/SqlBasicTest.java]: Fixed

File: hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java [hunk 47]
```diff
@@ -0,0 +1,72 @@
...
+    @Nonnull
+    SqlRowMetadata getRowMetadata();
+
+    /**
+     * Returns the iterator over the result rows.
+     * <p>
+     * The iterator may be requested only once.
+     *
+     * @return iterator
+     * @throws IllegalStateException ff the method is invoked more than once
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java:56]: Typo: ff -> if

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java [hunk 48]
```diff
@@ -0,0 +1,120 @@
...
+     * Gets the number of columns in the row.
+     *
+     * @return the number of columns in the row
+     */
+    public int getColumnCount() {
+        return columns.size();
+    }
+
+    /**
+     * Get column metadata.
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:63]: Minor Get -> Gets

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java [hunk 49]
```diff
@@ -0,0 +1,147 @@
...
+ *     <li>this OBJECT (hidden)
+ * </ul>
+ * <h2>Consistency</h2>
+ * Results returned from IMap query are weakly consistent:
+ * <ul>
+ *     <li>If an entry was not updated during iteration, it is guaranteed to be returned exactly once
+ *     <li>If an entry was modified during iteration, it might be returned zero, one or several times
+ * </ul>
+ * <h1>Usage</h1>
+ * When a query is executed, an {@link SqlResult} is returned. You may get row iterator from the result. The result must be closed
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:90]: What if a user constantly not closing the SqlResult? Will this cause OOM on the member eventually?

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java [hunk 50]
```diff
@@ -0,0 +1,147 @@
...
+ */
+@Beta
+public interface SqlService {
+    /**
+     * Convenient method to execute a distributed query with the given parameters.
+     * <p>
+     * Converts passed SQL string and parameters into an {@link SqlQuery} object and invokes {@link #query(SqlQuery)}.
+     *
+     * @param sql SQL string
+     * @param params parameters
```
Comment (petrpleshachkov) [inline hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:112]: I'd add a few words to explain - parameters for what?

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java (hunk 40 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:465]: I would add a statement like this:
>The SQL module in the 4.1 release is in beta state. We might change details of the behavior in future releases or even change the API. The functionality is also limited, for example we don't yet support joins or aggregations or DML statements. We also don't support IMaps with NATIVE in-memory format (enterprise feature). However, the features that are implemented are of production quality and are safe to be used in production settings.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java (hunk 49 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:90]: Yes, it will cause OOME on many members.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java (hunk 47 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlResult.java:56]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java (hunk 48 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlRowMetadata.java:63]: Fixed

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 46 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:151]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 45 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:43]: This is about "cursorBufferSize". Fixed.

File: hazelcast-sql/src/test/java/com/hazelcast/sql/SqlErrorTest.java [hunk 51]
```diff
@@ -0,0 +1,358 @@
...
+import static junit.framework.TestCase.assertEquals;
+import static junit.framework.TestCase.assertTrue;
+import static junit.framework.TestCase.fail;
+
+/**
+ * Test for different error conditions.
+ */
+@RunWith(HazelcastParallelClassRunner.class)
+@Category({QuickTest.class, ParallelJVMTest.class})
+public class SqlErrorTest extends SqlTestSupport {
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast-sql/src/test/java/com/hazelcast/sql/SqlErrorTest.java:48]: Same as in the comment above.

File: hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java [hunk 52]
```diff
@@ -0,0 +1,161 @@
...
+     * It is not recommended to set the value of this parameter greater than the number of CPU cores because it may decrease
+     * the system's overall performance due to excessive context switches.
+     * <p>
+     * Defaults to {@code -1}.
+     *
+     * @param executorPoolSize Number of threads responsible for query execution.
+     * @return This instance for chaining.
+     */
+    public SqlConfig setExecutorPoolSize(int executorPoolSize) {
+        if (executorPoolSize < DEFAULT_EXECUTOR_POOL_SIZE || executorPoolSize == 0) {
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java:73]: This will not work for positive values. We need to exclude all negative values and zero, but leave positive values and -1.

File: hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java [hunk 53]
```diff
@@ -0,0 +1,161 @@
...
+     * It is not recommended to set the value of this parameter greater than the number of CPU cores because it
+     * may decrease the system's overall performance due to excessive context switches.
+     * <p>
+     * Defaults to {@code -1}.
+     *
+     * @param operationPoolSize Number of threads responsible for network operations processing.
+     * @return This instance for chaining.
+     */
+    public SqlConfig setOperationPoolSize(int operationPoolSize) {
+        if (operationPoolSize < DEFAULT_OPERATION_POOL_SIZE || operationPoolSize == 0) {
```
[the remark this answers is not in the document]
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/config/SqlConfig.java:113]: Explained in the comment above.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java (hunk 44 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlQuery.java:33]: Agree. Marked as `final`.

File: hazelcast/src/main/java/com/hazelcast/sql/SqlService.java (hunk 50 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/sql/SqlService.java:112]: Added explanation.

**Comment by devozerov** [comment]
> Not all of the steps from here are done, for example `hazelcast-default`, `YamlMemberDomConfigProcessor`, maybe more:
> https://github.com/hazelcast/hazelcast/wiki/Checklist-for-Hazelcast-config-changes

Looks like this document is outdated. There is no clear need to add anything to `hazelcas-default`. Also no changes are needed to `YamlMemberDomConfigProcessor` in this specific case.

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java (hunk 40 above)
Comment (devozerov) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java:468]: Added a note about beta state. 
As mentioned before, I am not keen to add a description of specific features to JavaDoc. This is a goal of documentation, not JavaDoc, to inform users about supported SQL features. Whatever we write in JavaDoc will be outdated almost immediately. Even the list of unsupported feature in the sample snippet is not accurate already.

**Comment by devozerov** [comment]
run-lab-run
