### PR TITLE
Do not fire MERGE events when merging MultiMap entries

### LINKED ISSUE #13559: MultiMapValue can not be serialized
I'm using vertx with the latest version of hazelcast 3.10.4. Vertx use hazelcast as default implementation for its cluster manager service. However i am getting a few errors when running vertx+hazelcast in a distributed cluster.

After a couple of hours of research i found that vertx cluster goes into an inconsistent state because it use a MultiMap to hold some internal information. However when split brain happens and this multimap should be merged, hazelcast fail with

```
SEVERE: [10.0.14.7]:5701 [dev] [3.10.4] Failed to serialize 'com.hazelcast.multimap.impl.MultiMapValue'
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.multimap.impl.MultiMapValue'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:157)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:133)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:118)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:106)
	at com.hazelcast.spi.impl.NodeEngineImpl.toData(NodeEngineImpl.java:317)
	at com.hazelcast.multimap.impl.MultiMapEventsPublisher.publishEntryEvent(MultiMapEventsPublisher.java:60)
	at com.hazelcast.multimap.impl.MultiMapService.publishEntryEvent(MultiMapService.java:241)
	at com.hazelcast.multimap.impl.operations.AbstractMultiMapOperation.publishEvent(AbstractMultiMapOperation.java:71)
	at com.hazelcast.multimap.impl.operations.MergeOperation.run(MergeOperation.java:78)
	at com.hazelcast.spi.Operation.call(Operation.java:148)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:202)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:191)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:120)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.hazelcast.multimap.impl.MultiMapValue
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:487)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:146)
	... 13 more
```

I think MultiMapValue should implement IdentifiedDataSerializable. I made a quick implementation and it works, but i 'm not sure if my code is good enough
```java
    @Override
    public int getFactoryId() {
        return MultiMapDataSerializerHook.F_ID;
    }

    @Override
    public int getId() {
        return MultiMapDataSerializerHook.MULTIMAP_VALUE;
    }

    @Override
    public void writeData(ObjectDataOutput out) throws IOException {
        out.writeLong(hits);

        for (MultiMapRecord record : collection)
            out.writeObject(record);
    }

    @Override
    public void readData(ObjectDataInput in) throws IOException {
        this.hits = in.readLong();
        for (int i = 0; i < this.hits; i++)
            this.collection.add(in.readObject(MultiMapRecord.class));
    }
```

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #13559

Multimap does not have MERGE listener anyway hence it's pointless
to fire MERGE events.

I also added additional parameters to the MultiMap split-brain test
to test every merge policy for both BINARY and OBJECT formats.

Backport will follow.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/multimap/MultiMapSplitBrainTest.java [hunk 1]
```diff
@@ -133,6 +142,11 @@ protected void onAfterSplitBrainCreated(HazelcastInstance[] firstBrain, Hazelcas
         multiMapA2 = secondBrain[0].getMultiMap(multiMapNameA);
         multiMapB2 = secondBrain[0].getMultiMap(multiMapNameB);
 
+        EntryListener<Object, Object> listener = new EmptyEntryListener<Object, Object>();
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/multimap/MultiMapSplitBrainTest.java]: this is the important bit for the test
