### PR TITLE
Fix cluster state transaction process

### LINKED ISSUE #6383: AdvancedClusterStateTest failures
**changeClusterState_shouldFail_whenInitiatorDies_beforePrepare**
**changeClusterState_shouldFail_withoutBackup_whenInitiatorDies_afterPrepare**
**changeClusterState_shouldFail_withoutBackup_whenInitiatorDies_beforePrepare**

```
com.hazelcast.transaction.TransactionException: Transaction is timed-out!
    at com.hazelcast.transaction.impl.TransactionImpl.checkTimeout(TransactionImpl.java:287)
    at com.hazelcast.transaction.impl.TransactionImpl.prepare(TransactionImpl.java:211)
    at com.hazelcast.cluster.AdvancedClusterStateTest$DelegatingTransaction.prepare(AdvancedClusterStateTest.java:584)
    at com.hazelcast.cluster.AdvancedClusterStateTest$TransactionAnswer$1.prepare(AdvancedClusterStateTest.java:505)
    at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:210)
    at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:794)
    at com.hazelcast.cluster.AdvancedClusterStateTest.changeClusterState_shouldFail_whenInitiatorDies_beforePrepare(AdvancedClusterStateTest.java:160)
```

**invocationShouldComplete_whenMemberReJoins_inFrozenState**
**partitionTable_shouldBeFrozen_whenMemberLeaves_inFrozenState**

```
ava.lang.IllegalStateException: Still have pending migration/replication tasks, cannot lock cluster state! New state: FROZEN, current state: ACTIVE
    at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:124)
    at com.hazelcast.cluster.impl.operations.LockClusterStateOperation.run(LockClusterStateOperation.java:68)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/685/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/681/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/684/

### PR DESCRIPTION
**Pull request by mdogan**
Fixed cluster state transaction process. There were two issues:

- Transaction logs should be appended before acquiring initial locks,
not after. Otherwise during rollback, successfully acquired locks will
remain locked until expiration time.

- To provide initial lock and rollback/commit ordering, locking block
should wait for all futures. Throwing error on the first lock failure
will break order and may cause rollback executed before other lock operations.
That will cause again hanging locks (until expiration).

Fixes #6383

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

**Comment by metanet** [comment]
:+1

**Comment by mdogan** [comment]
Client test failures:

```
testUpdate(com.hazelcast.client.map.MapNearCacheInvalidationFromClientTest)  Time elapsed: 1.372 sec  <<< FAILURE!
22:44:24 java.lang.AssertionError: expected:<DefaultData{type=-7, hashCode=768969306, partitionHash=768969306, totalSize=9, dataSize=4, heapCost=29}> but was:<null>
22:44:24 	at org.junit.Assert.fail(Assert.java:88)
22:44:24 	at org.junit.Assert.failNotEquals(Assert.java:834)
22:44:24 	at org.junit.Assert.assertEquals(Assert.java:118)
22:44:24 	at org.junit.Assert.assertEquals(Assert.java:144)
22:44:24 	at com.hazelcast.client.map.MapNearCacheInvalidationFromClientTest.testUpdate(MapNearCacheInvalidationFromClientTest.java:184)
```

```
testMapReduceJobSubmissionWithNoDataNode(com.hazelcast.client.mapreduce.MapReduceLiteMemberTest)  Time elapsed: 154.011 sec  <<< ERROR!
22:40:01 org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
22:40:01 	at java.lang.Thread.sleep(Native Method)
22:40:01 	at com.hazelcast.client.spi.ProxyManager.sleepForProxyInitRetry(ProxyManager.java:264)
22:40:01 	at com.hazelcast.client.spi.ProxyManager.initializeWithRetry(ProxyManager.java:241)
22:40:01 	at com.hazelcast.client.spi.ProxyManager.getOrCreateProxy(ProxyManager.java:212)
22:40:01 	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getDistributedObject(HazelcastClientInstanceImpl.java:492)
22:40:01 	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.getJobTracker(HazelcastClientInstanceImpl.java:355)
22:40:01 	at com.hazelcast.client.impl.HazelcastClientProxy.getJobTracker(HazelcastClientProxy.java:128)
22:40:01 	at com.hazelcast.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:247)
22:40:01 	at com.hazelcast.client.mapreduce.MapReduceLiteMemberTest.testMapReduceJobSubmissionWithNoDataNode(MapReduceLiteMemberTest.java:99)
```

**Comment by mdogan** [comment]
verify

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java [hunk 1]
```diff
@@ -284,4 +285,38 @@ public String toString() {
         sb.append('}');
         return sb.toString();
     }
+
+    private static final class StateManagerExceptionHandler implements FutureUtil.ExceptionHandler {
+        private final ILogger logger;
+        private Throwable error;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java]: I would make this field volatile. Afaik it is set by one thread and the rethrowIfFailed is called by another. Perhaps it lifts on top of an existing happens before relation, but it isn't obvious. So I would place it in a volatile variable to prevent any confusion.

File: hazelcast/src/test/java/com/hazelcast/cluster/AdvancedClusterStateTest.java [hunk 2]
```diff
@@ -422,7 +422,7 @@ private void changeClusterStateEventually(HazelcastInstance hz, ClusterState new
         final Cluster cluster = hz.getCluster();
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cluster/AdvancedClusterStateTest.java]: Is there a test which can reproduce the original issue? So that we know your fix really solves this issue.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java [hunk 3]
```diff
@@ -68,6 +71,7 @@
     ClusterStateManager(Node node, Lock clusterServiceLock) {
         this.node = node;
         this.clusterServiceLock = clusterServiceLock;
+        logger = node.getLogger(getClass());
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java]: I would use this.logger

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java (hunk 1 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java]: What about adding a comment about it's usage instead of making it `volatile`? Since, it's written and read by the same thread.

File: hazelcast/src/test/java/com/hazelcast/cluster/AdvancedClusterStateTest.java (hunk 2 above)
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/cluster/AdvancedClusterStateTest.java]: See fixed issue.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java (hunk 3 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java]: why?

**Comment by pveentjer** [comment]
I had a very superficial scan on this PR. My knowledge about cluster and the recent changes is not sufficient to say this pr is good or not.

File: hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java (hunk 1 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/cluster/impl/ClusterStateManager.java]: see 1aff2796bdf684c3e3674041107b640be9aa90e5
