### PR TITLE
AwsCloudDiscoveryTest.testAwsAddressProvider test fails

### LINKED ISSUE #11571: AwsCloudDiscoveryTest
**com.hazelcast.client.discovery.AwsCloudDiscoveryTest.testAwsAddressProvider**
```java
java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [[172.30.0.181]:5701, [172.30.0.181]:5702, [172.30.0.181]:5703]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:864)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1500(ClientConnectionManagerImpl.java:101)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:874)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:870)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/view/Sonar/job/Hazelcast-3.x-sonar/lastCompletedBuild/com.hazelcast$hazelcast-client/testReport/com.hazelcast.client.discovery/AwsCloudDiscoveryTest/testAwsAddressProvider/

### PR DESCRIPTION
**Pull request by ihsandemir**
Fixed testAwsAddressProvider test so that it only tests for retrieved aws addresses. It can not connect to the discovered instance since it is started at a custome port different from 5701-5704 and AwsAddressProvider does not have the custom port setting capability but the AwsCloudDiscovery has this option.

fixes #11571

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java [hunk 1]
```diff
@@ -119,16 +123,25 @@ public void testAwsAddressProvider() {
                 .setTagKey(AWS_TEST_TAG)
                 .setTagValue(AWS_TEST_TAG_VALUE);
 
+
         ClientConfig clientConfig = new ClientConfig();
-        clientConfig.getNetworkConfig().setAwsConfig(clientAwsConfig);
+        String instanceName = null;
```
Comment (Donnerbart) [inline hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: This should be `String instanceName;`, otherwise a warning is created.

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java [hunk 2]
```diff
@@ -119,16 +123,25 @@ public void testAwsAddressProvider() {
                 .setTagKey(AWS_TEST_TAG)
                 .setTagValue(AWS_TEST_TAG_VALUE);
 
+
```
Comment (Donnerbart) [inline hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: Superfluous newline.

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java [hunk 3]
```diff
@@ -119,16 +123,25 @@ public void testAwsAddressProvider() {
...
-        assertEquals(5, map.get(1));
+        GroupConfig groupConfig = clientConfig.getGroupConfig();
+        String loggingType = clientConfig.getProperty(GroupProperty.LOGGING_TYPE.getName());
+        LoggingService loggingService = new ClientLoggingService(groupConfig.getName(),
+                loggingType, BuildInfoProvider.getBuildInfo(), instanceName);
 
-        AwsAddressProvider awsAddressProvider = new AwsAddressProvider(clientAwsConfig, client.getLoggingService());
+        AwsAddressProvider awsAddressProvider = new AwsAddressProvider(clientAwsConfig, loggingService);
         Collection<Address> addresses = awsAddressProvider.loadAddresses();
         assertTrue(isNotEmpty(addresses));
```
Comment (Donnerbart) [inline hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: A failure on `assertTrue()` gives a quite meaningless error. We could improve this, maybe like this
```java
assertTrue("Expected non-empty addresses from AwsAddressProvider.loadAddresses()", isNotEmpty(addresses));
```

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java [hunk 4]
```diff
@@ -119,16 +123,25 @@ public void testAwsAddressProvider() {
...
+        String instancePrivateIp = System.getenv("HZ_TEST_AWS_INSTANCE_PRIVATE_IP");
+        assumeThat("HZ_TEST_AWS_INSTANCE_PRIVATE_IP is not set", instancePrivateIp, Matchers.<String>notNullValue());
```
Comment (Donnerbart) [inline hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: I'm not sure about this `assumeThat()`. The test passes fine until here, if just `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set. But if `HZ_TEST_AWS_INSTANCE_PRIVATE_IP` is not set, the whole test will nevertheless be skipped/ignored, although the addresses have been successfully loaded and checked.

This works fine on my machine:
```java
        if (instancePrivateIp != null) {
            assertEquals(instancePrivateIp, addresses.iterator().next().getHost());
        }
```

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java (hunk 1 above)
Comment (ihsandemir) [reply hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: done.

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java (hunk 3 above)
Comment (ihsandemir) [reply hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: done.

File: hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java (hunk 4 above)
Comment (ihsandemir) [reply hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: added this check to the beginning similar to the other env. variable checks.

Comment (Donnerbart) [reply hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: Looks good to me. But how do I know what to set for `HZ_TEST_AWS_INSTANCE_PRIVATE_IP`? Setting an env variable looks like it's always the same IP address. Where does this come from?

Comment (Donnerbart) [reply hazelcast-client/src/test/java/com/hazelcast/client/discovery/AwsCloudDiscoveryTest.java]: Ah, I found the instance via the `aws-test-tag`. Question is answered.
