### PR TITLE
Fix K8s service port [CN-894]

### LINKED ISSUE #24688: Embedded Hazelcast in Kubernetes environment won't detect members anymore after latest release
**Describe the bug**
Hi,

we do get Hazelcast in embedded mode as part of a Spring Boot transitive dependency, and after performing the last update (Hazelcast from 5.1.5 to 5.1.6), we noticed that the pods failed to detect each other. The only difference seems to be the version change. Since I didn't see any hint regarding this in the release notes (apart from maybe #24044 or maybe #23932), I wonder, if there needs to be something configured differently now. 

Failing log output - see this blacklist entry at the end:
```
2023-05-30T16:24:57.506Z  WARN 1 --- [           main] c.h.i.impl.HazelcastInstanceFactory      : Hazelcast is starting in a Java modular environment (Java 9 and newer) but without proper access to required Java packages. Use additional Java arguments to provide Hazelcast access to Java internal API. The internal API access is used to get the best performance results. Arguments to be used:
 --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
2023-05-30T16:24:57.716Z  INFO 1 --- [           main] com.hazelcast.system.logo                : [10.4.0.31]:5701 [dev] [5.1.6] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
2023-05-30T16:24:57.716Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.31]:5701 [dev] [5.1.6] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
2023-05-30T16:24:57.716Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.31]:5701 [dev] [5.1.6] Hazelcast Platform 5.1.6 (20230510 - 029cff5) starting at [10.4.0.31]:5701
2023-05-30T16:24:57.716Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.31]:5701 [dev] [5.1.6] Cluster name: dev
2023-05-30T16:24:57.716Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.31]:5701 [dev] [5.1.6] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2023-05-30T16:24:57.719Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.31]:5701 [dev] [5.1.6] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2023-05-30T16:24:58.714Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.31]:5701 [dev] [5.1.6] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: dxf-webapp-cache-pool, service-port: 0, service-label: null, service-label-value: true, namespace: dc-ofd-qa, pod-label: null, pod-label-value: null, resolve-not-ready-addresses: true, expose-externally-mode: AUTO, use-node-name-as-external-address: false, service-per-pod-label: null, service-per-pod-label-value: null, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
2023-05-30T16:24:59.400Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.31]:5701 [dev] [5.1.6] Kubernetes Discovery activated with mode: KUBERNETES_API
2023-05-30T16:24:59.402Z  INFO 1 --- [           main] com.hazelcast.system.security            : [10.4.0.31]:5701 [dev] [5.1.6] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2023-05-30T16:24:59.600Z  INFO 1 --- [           main] com.hazelcast.instance.impl.Node         : [10.4.0.31]:5701 [dev] [5.1.6] Using Discovery SPI
2023-05-30T16:24:59.606Z  WARN 1 --- [           main] com.hazelcast.cp.CPSubsystem             : [10.4.0.31]:5701 [dev] [5.1.6] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2023-05-30T16:25:00.310Z  INFO 1 --- [           main] c.h.internal.diagnostics.Diagnostics     : [10.4.0.31]:5701 [dev] [5.1.6] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2023-05-30T16:25:00.315Z  INFO 1 --- [           main] com.hazelcast.core.LifecycleService      : [10.4.0.31]:5701 [dev] [5.1.6] [10.4.0.31]:5701 is STARTING
2023-05-30T16:25:00.600Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.31]:5701 [dev] [5.1.6] Kubernetes plugin discovered availability zone: 0
2023-05-30T16:25:00.635Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.31]:5701 [dev] [5.1.6] Kubernetes plugin discovered node name: aks-agentpool-20404461-vmss00002y
2023-05-30T16:25:00.743Z  WARN 1 --- [           main] c.hazelcast.kubernetes.KubernetesClient  : Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
2023-05-30T16:25:00.763Z  INFO 1 --- [cached.thread-3] c.h.i.cluster.impl.DiscoveryJoiner       : [10.4.0.31]:5701 [dev] [5.1.6] [10.4.0.31]:5702 is added to the blacklist.
2023-05-30T16:25:00.798Z  INFO 1 --- [cached.thread-2] c.h.i.cluster.impl.DiscoveryJoiner       : [10.4.0.31]:5701 [dev] [5.1.6] [10.4.0.51]:5702 is added to the blacklist.
```

Working log output:
```
2023-05-30T16:26:54.524Z  INFO 1 --- [           main] com.hazelcast.system.logo                : [10.4.0.14]:5701 [dev] [5.1.5] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
2023-05-30T16:26:54.525Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.14]:5701 [dev] [5.1.5] Copyright (c) 2008-2022, Hazelcast, Inc. All Rights Reserved.
2023-05-30T16:26:54.525Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.14]:5701 [dev] [5.1.5] Hazelcast Platform 5.1.5 (20221114 - c52d6ff) starting at [10.4.0.14]:5701
2023-05-30T16:26:54.525Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.14]:5701 [dev] [5.1.5] Cluster name: dev
2023-05-30T16:26:54.525Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.14]:5701 [dev] [5.1.5] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed.
To enable integrity checker do one of the following: 
  - Change member config using Java API: config.setIntegrityCheckerEnabled(true);
  - Change XML/YAML configuration property: Set hazelcast.integrity-checker.enabled to true
  - Add system property: -Dhz.integritychecker.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_INTEGRITYCHECKER_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2023-05-30T16:26:54.528Z  INFO 1 --- [           main] com.hazelcast.system                     : [10.4.0.14]:5701 [dev] [5.1.5] The Jet engine is disabled.
To enable the Jet engine on the members, do one of the following:
  - Change member config using Java API: config.getJetConfig().setEnabled(true)
  - Change XML/YAML configuration property: Set hazelcast.jet.enabled to true
  - Add system property: -Dhz.jet.enabled=true (for Hazelcast embedded, works only when loading config via Config.load)
  - Add environment variable: HZ_JET_ENABLED=true (recommended when running container image. For Hazelcast embedded, works only when loading config via Config.load)
2023-05-30T16:26:55.599Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.14]:5701 [dev] [5.1.5] Kubernetes Discovery properties: { service-dns: null, service-dns-timeout: 5, service-name: dxf-webapp-cache-pool, service-port: 0, service-label: null, service-label-value: true, namespace: dc-ofd-qa, pod-label: null, pod-label-value: null, resolve-not-ready-addresses: true, expose-externally-mode: AUTO, use-node-name-as-external-address: false, service-per-pod-label: null, service-per-pod-label-value: null, kubernetes-api-retries: 3, kubernetes-master: https://kubernetes.default.svc}
2023-05-30T16:26:56.205Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.14]:5701 [dev] [5.1.5] Kubernetes Discovery activated with mode: KUBERNETES_API
2023-05-30T16:26:56.207Z  INFO 1 --- [           main] com.hazelcast.system.security            : [10.4.0.14]:5701 [dev] [5.1.5] Enable DEBUG/FINE log level for log category com.hazelcast.system.security  or use -Dhazelcast.security.recommendations system property to see 🔒 security recommendations and the status of current config.
2023-05-30T16:26:56.419Z  INFO 1 --- [           main] com.hazelcast.instance.impl.Node         : [10.4.0.14]:5701 [dev] [5.1.5] Using Discovery SPI
2023-05-30T16:26:56.425Z  WARN 1 --- [           main] com.hazelcast.cp.CPSubsystem             : [10.4.0.14]:5701 [dev] [5.1.5] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
2023-05-30T16:26:57.131Z  INFO 1 --- [           main] c.h.internal.diagnostics.Diagnostics     : [10.4.0.14]:5701 [dev] [5.1.5] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
2023-05-30T16:26:57.198Z  INFO 1 --- [           main] com.hazelcast.core.LifecycleService      : [10.4.0.14]:5701 [dev] [5.1.5] [10.4.0.14]:5701 is STARTING
2023-05-30T16:26:57.400Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.14]:5701 [dev] [5.1.5] Kubernetes plugin discovered availability zone: 0
2023-05-30T16:26:57.438Z  INFO 1 --- [           main] c.h.s.d.integration.DiscoveryService     : [10.4.0.14]:5701 [dev] [5.1.5] Kubernetes plugin discovered node name: aks-agentpool-20404461-vmss00002y
2023-05-30T16:26:57.597Z  WARN 1 --- [           main] c.hazelcast.kubernetes.KubernetesClient  : Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
2023-05-30T16:26:57.698Z  INFO 1 --- [.IO.thread-in-0] c.h.i.server.tcp.TcpServerConnection     : [10.4.0.14]:5701 [dev] [5.1.5] Initialized new cluster connection between /10.4.0.14:48785 and /10.4.0.44:5701
2023-05-30T16:26:58.643Z  INFO 1 --- [.IO.thread-in-1] c.h.i.server.tcp.TcpServerConnection     : [10.4.0.14]:5701 [dev] [5.1.5] Initialized new cluster connection between /10.4.0.14:56901 and /10.4.0.62:5701
```

Both logs were produced on the very same kubernetes cluster...  Maybe, it is something related to the ports, as the failing one mentions 5702 while the succeeding one (with the older version) mentions 5701 as the target...

**Expected behavior**
5.1.5 and 5.1.6 should behave the same, when configured the same
**To Reproduce**

1. Configure Hazelcast as mentioned in the Logs?

**Additional context**
Spring Boot 3.0.6->3.0.7 update
JDK 17

### LINKED ISSUE #24705: Embedded Hazelcast Kubernetes auto-discovery fails on 5.3.0
**Describe the bug**
Embedded Hazelcast with Kubernetes autodiscovery fails on 5.3.0 if the hazelcast port is not the first port found in the list.  HZ tries to connect repetitively on the first port found, and fails to initialize the cluster.  Most of the time, the service fails to start entirely, sometimes it starts but with single member clusters consisting of itself on all nodes.

**Expected behavior**
The cluster should start up as expected.

### To Reproduce

- Using a kubernetes service with multiple ports, where the HZ port _is not the first one in the list_, try to start up a cluster of two or more nodes with Kubernetes auto-discovery.  The logic in KubernetesApiProvider.extractPort (https://github.com/hazelcast/hazelcast/blob/f5984a1e6ffc821789c7616b17d897d1c42b08cb/hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesApiProvider.java#LL50C26-L50C26) looks for a port named `hazelcast-service-port`, if it does not find it, it returns the first port in the list.  Hazelcast will fail to form a cluster because it tries to connect with the first port only.
- A successful workaround was to configure the `service-port` value in the configuration, so be sure that is not specified.

### Additional context
The port name `hazelcast-service-port` is 22 characters long, which exceeds the Kubernetes port name limit of 15 characters.  The check in the code will never succeed.

There's no stack trace even at finest level for when the cluster fails to start, the node just attempts to connect, and then shuts down.

### Running in the following configuration:
- HZ 5.3.0
- Java 17.0.7+7-LTS
- Azure Kubernetes Service, K8s version v1.25.4
- Upgrade of two node service instance

### Workarounds tried:
- Giving all K8s permissions to the hazelcast service account (no change in behavior from endpoint slice or legacy endpoint apis)
- Renaming the port (failed due to K8s limitation)
- Reordering the ports (failed due to the helm chart driving the service, outside of our control)
- Override the `service-port` in the K8s networking configuration, which appears to flow through to the connection logic, overriding the auto-discovered port. - **this did work and allow the nodes to join into a cluster.**

### Additional details:

K8s ports for the service:
```yaml
    ports:
    - containerPort: 8443
      name: http
      protocol: TCP
    - containerPort: 8444
      name: admin
      protocol: TCP
    - containerPort: 5701
      name: hazelcast
      protocol: TCP
```

Log snippet (sanitized) - note that it is trying to connect to 8443 on all nodes, not 5701.
```
2023-06-01 23:47:30,199  INFO rid="" tid= eid= com.hazelcast.core.LifecycleService - [<my ip>]:5701 [<cluster name>] [5.3.0] [<my ip>]:5701 is STARTING
2023-06-01 23:47:30,249  INFO rid="" tid= eid= c.h.s.d.integration.DiscoveryService - [<my ip>]:5701 [<cluster name>] [5.3.0] Cannot fetch the current zone, ZONE_AWARE feature is disabled
2023-06-01 23:47:30,282  WARN rid="" tid= eid= c.h.s.d.integration.DiscoveryService - [<my ip>]:5701 [<cluster name>] [5.3.0] Cannot fetch name of the node, NODE_AWARE feature is disabled
2023-06-01 23:47:30,282 TRACE rid="" tid= eid= com.hazelcast.instance.impl.Node - [<my ip>]:5701 [<cluster name>] [5.3.0] Adding ShutdownHook
2023-06-01 23:47:30,351  WARN rid="" tid= eid= c.hazelcast.kubernetes.KubernetesClient - Cannot fetch public IPs of Hazelcast Member PODs, you won't be able to use Hazelcast Smart Client from outside of the Kubernetes network
2023-06-01 23:47:30,365  INFO rid="" tid= eid= c.h.i.cluster.impl.DiscoveryJoiner - [<my ip>]:5701 [<cluster name>] [5.3.0] [<my ip>]:8443 is added to the blacklist.
2023-06-01 23:48:00,370  INFO rid="" tid= eid= c.h.i.server.tcp.TcpServerConnection - [<my ip>]:5701 [<cluster name>] [5.3.0] Connection[id=1, /<my ip>:55593->/<other ip1>:8443, qualifier=null, endpoint=[<other ip1>]:8443, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2023-06-01 23:48:00,370  INFO rid="" tid= eid= c.h.i.server.tcp.TcpServerConnection - [<my ip>]:5701 [<cluster name>] [5.3.0] Connection[id=2, /<my ip>:48263->/<other ip2>:8443, qualifier=null, endpoint=[<other ip2>]:8443, remoteUuid=null, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
2023-06-01 23:48:00,376  INFO rid="" tid= eid= c.h.i.cluster.impl.DiscoveryJoiner - [<my ip>]:5701 [<cluster name>] [5.3.0] [<other ip2>]:8443 is added to the blacklist.
2023-06-01 23:48:00,376  INFO rid="" tid= eid= c.h.i.cluster.impl.DiscoveryJoiner - [<my ip>]:5701 [<cluster name>] [5.3.0] [<other ip1>]:8443 is added to the blacklist.
2023-06-01 23:48:00,476  INFO rid="" tid= eid= c.h.i.cluster.impl.DiscoveryJoiner - [<my ip>]:5701 [<cluster name>] [5.3.0] [<other ip1>]:8443 is removed from the blacklist.
2023-06-01 23:48:00,476  INFO rid="" tid= eid= c.h.i.cluster.impl.DiscoveryJoiner - [<my ip>]:5701 [<cluster name>] [5.3.0] [<other ip2>]:8443 is removed from the blacklist.
2023-06-01 23:48:06,356  INFO rid="" tid= eid= com.hazelcast.instance.impl.Node - [<my ip>]:5701 [<cluster name>] [5.3.0] Running shutdown hook... Current node state: ACTIVE
2023-06-01 23:48:06,360  INFO rid="" tid= eid= com.hazelcast.core.LifecycleService - [<my ip>]:5701 [<cluster name>] [5.3.0] [<my ip>]:5701 is SHUTTING_DOWN
2023-06-01 23:48:06,369 TRACE rid="" tid= eid= com.hazelcast.instance.impl.Node - [<my ip>]:5701 [<cluster name>] [5.3.0] We are being asked to shutdown when state = ACTIVE
2023-06-01 23:48:06,369  WARN rid="" tid= eid= com.hazelcast.instance.impl.Node - [<my ip>]:5701 [<cluster name>] [5.3.0] Terminating forcefully...
2023-06-01 23:48:06,369  INFO rid="" tid= eid= com.hazelcast.instance.impl.Node - [<my ip>]:5701 [<cluster name>] [5.3.0] Shutting down connection manager...
```

### PR DESCRIPTION
**Pull request by SeriyBg**
Change the port name from `hazelcast-service-port` that is longer than 15 characters to `hazelcast`.

Fixes #24688
Fixes #24705 

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [+] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [+] Label `Add to Release Notes` or `Not Release Notes content` set
- [+] Request reviewers if possible
- [+] Send backports/forwardports if fix needs to be applied to past/future releases
- [+] New public APIs have `@Nonnull/@Nullable` annotations
- [+] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesApiProvider.java [hunk 1]
```diff
@@ -51,14 +51,14 @@ default Integer extractPort(JsonValue subsetJson) {
...
-            if (hazelcastServicePort != null && hazelcastServicePort.asString().equals("hazelcast-service-port")) {
+            if (hazelcastServicePort != null && hazelcastServicePort.asString().equals("hazelcast")) {
                 JsonValue servicePort = port.asObject().get("port");
                 if (servicePort != null && servicePort.isNumber()) {
                     return servicePort.asInt();
                 }
             }
         }
-        if (ports.size() > 0) {
+        if (ports.size() == 1) {
```
Comment (semihbkgr) [inline hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesApiProvider.java:61]: Why changed in this way `equals to 1`

Comment (semihbkgr) [reply hazelcast/src/main/java/com/hazelcast/kubernetes/KubernetesApiProvider.java:61]: Anyway, It is not a big deal. In the best practice, we assume to have a port named as `hazelcast`.

**Review by semihbkgr — APPROVED** [review]

**Review by hasancelik — APPROVED** [review]
