### PR TITLE
Disallow parallel SimpleTestInClusterSupport tests creating objects [HZ-3667]

### LINKED ISSUE #24680: com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest
_master_ (commit 02e4cbb450e037bd8946f1498293ea3b375da93e)

Failed on zing-17: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZingJDK17-nightly/27/testReport/com.hazelcast.jet.sql_slow/SqlSlowIndexResolutionTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.NullPointerException: Cannot invoke "com.hazelcast.client.test.TestHazelcastFactory.newHazelcastInstance(com.hazelcast.config.Config)" because "com.hazelcast.jet.SimpleTestInClusterSupport.factory" is null
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:73)
	at com.hazelcast.jet.sql_slow.SqlSlowIndexResolutionTest.beforeClass(SqlSlowIndexResolutionTest.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:891)

```
</details>

<details><summary>Standard output:</summary>

```
22:56:56,181  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
22:56:56,181  WARN || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Terminating forcefully...
22:56:56,181  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down connection manager...
22:56:56,181  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Shutting down node engine...
22:56:56,183  INFO || - [HealthMonitor] hz.SqlSlowIndexResolutionTest_gracious_wilson.HealthMonitor - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] processors=8, physical.memory.total=377.8G, physical.memory.free=138.0G, swap.space.total=8.0G, swap.space.free=4.7G, heap.memory.used=4.8G, heap.memory.free=3.2G, heap.memory.total=8.0G, heap.memory.max=8.0G, heap.memory.used/total=59.42%, heap.memory.used/max=59.42%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=182, unknown.gc.time=30590ms, load.process=69.58%, load.system=84.78%, load.systemAverage=7.30, thread.count=34, thread.peakCount=563, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
22:56:56,185  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
22:56:56,185  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230526 - 02e4cbb) starting at [127.0.0.1]:5701
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
22:56:56,185  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
22:56:56,187  INFO || - [NodeExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Destroying node NodeExtension.
22:56:56,187  INFO || - [Node] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Shutdown is completed in 6 ms.
22:56:56,187  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
22:56:56,190  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
Exception in thread "hz.SqlSlowIndexResolutionTest_gracious_wilson.cached.thread-6" 22:56:56,192  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@f34705c[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@f347050[Wrapped task = DelegateDecorator{executor=com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate@7983f215, runnable=com.hazelcast.jet.impl.JobCoordinationService$$Lambda$scanJobs$636937061/0x0000000000003761@f3470b0}]] rejected from com.hazelcast.internal.util.executor.LoggingScheduledExecutor@7983f3bb[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 6]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
	at com.hazelcast.spi.impl.executionservice.impl.DelegatingTaskScheduler.schedule(DelegatingTaskScheduler.java:49)
	at com.hazelcast.spi.impl.executionservice.impl.ExecutionServiceImpl.schedule(ExecutionServiceImpl.java:273)
	at com.hazelcast.jet.impl.JobCoordinationService.scanJobs(JobCoordinationService.java:1402)
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:891)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:111)
22:56:56,200  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
22:56:56,203  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
22:56:56,204  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
22:56:56,204  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
22:56:56,205  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - b45f9ebe-54cc-4652-839d-9466dace4af4 this
]

22:56:56,205  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
22:56:56,205  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
Started Running Test: testCompare_LocalDateTime_with_LocalDateTime[mode:EQ]

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-ZingJDK17-nightly/27/

### LINKED ISSUE #24713: com.hazelcast.jet.sql_slow.SqlBasicClientSlowTest.(?)
_master_ (commit f5984a1e6ffc821789c7616b17d897d1c42b08cb)

Failed on oracle-11 (force-offload): https://jenkins.hazelcast.com/job/Hazelcast-master-nightly-force-offload/50/testReport/com.hazelcast.jet.sql_slow/SqlBasicClientSlowTest/___/
<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: already initialized
	at com.hazelcast.jet.SimpleTestInClusterSupport.initialize(SimpleTestInClusterSupport.java:64)
	at com.hazelcast.jet.SimpleTestInClusterSupport.initializeWithClient(SimpleTestInClusterSupport.java:86)
	at com.hazelcast.jet.sql.SqlBasicTest.beforeClass(SqlBasicTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:41)
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)

```
</details>

<details><summary>Standard output:</summary>

```
16:57:16,676  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
16:57:16,676  INFO || - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
16:57:16,676  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
16:57:16,676  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230604 - f5984a1) starting at [127.0.0.1]:5701
16:57:16,677  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
16:57:16,677  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
16:57:16,677  INFO || - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet is enabled
16:57:16,682  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
16:57:16,682  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] TPC: disabled
16:57:16,686  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
16:57:16,689  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
16:57:16,696  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
16:57:16,696  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
16:57:16,696  INFO || - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - dffdc17e-38c3-477c-8492-f7f5234fcac3 this
]

16:57:16,696  INFO || - [JobCoordinationService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Jet started scanning for jobs
16:57:16,696 DEBUG || - [JobCoordinationService] hz.SqlBasicSlowTest_inspiring_ardinghelli.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
16:57:16,696  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
16:57:16,697  INFO || - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.4.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
16:57:16,697  INFO || - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Copyright (c) 2008-2023, Hazelcast, Inc. All Rights Reserved.
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Hazelcast Platform 5.4.0-SNAPSHOT (20230604 - f5984a1) starting at [127.0.0.1]:5702
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Cluster name: dev
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Integrity Checker is disabled. Fail-fast on corrupted executables will not be performed. For more information, see the documentation for Integrity Checker.
16:57:16,698  INFO || - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Jet is enabled
16:57:16,700  INFO || - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
16:57:16,701  INFO || - [TpcServerBootstrap] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] TPC: disabled
16:57:16,704  WARN || - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
16:57:16,706  INFO || - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 2
16:57:16,708  INFO || - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
16:57:16,708  INFO || - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
16:57:16,708  INFO || - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.4.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701-dffdc17e-38c3-477c-8492-f7f5234fcac3, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=17e28fff-e6f9-4454-b036-ebca87d50f8e], remoteEndpoint=[address=[127.0.0.1]:5701, uuid=dffdc17e-38c3-477c-8492-f7f5234fcac3], alive=true}
16:57:16,709  INFO || - [MockServer] hz.SqlBasicSlowTest_inspiring_ardinghelli.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702-17e28fff-e6f9-4454-b036-ebca87d50f8e, connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5701, uuid=dffdc17e-38c3-477c-8492-f7f5234fcac3], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=17e28fff-e6f9-4454-b036-ebca87d50f8e], alive=true}
16:57:16,709  INFO || - [ClusterService] hz.SqlBasicSlowTest_inspiring_ardinghelli.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - dffdc17e-38c3-477c-8492-f7f5234fcac3 this
	Member [127.0.0.1]:5702 - 17e28fff-e6f9-4454-b036-ebca87d50f8e
]

16:57:16,796 DEBUG || - [JobCoordinationService] hz.SqlBasicSlowTest_inspiring_ardinghelli.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.4.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
16:57:16,798  WARN |stressTest[processingGuarantee:atLeastOnce, restartGraceful:false]| - [SqlSTSInnerNonEquiJoinFaultToleranceStressTest] Thread-205 - null
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:558) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:230) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:217) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:202) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.toDataWithStrategy(MapProxySupport.java:1334) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:410) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:122) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.impl.JobRepository.getJobExecutionRecord(JobRepository.java:615) ~[hazelcast-5.4.0-SNAPSHOT.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.core.JetTestSupport.lambda$waitForNextSnapshot$4(JetTestSupport.java:393) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1285) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1304) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.core.JetTestSupport.waitForNextSnapshot(JetTestSupport.java:392) ~[hazelcast-5.4.0-SNAPSHOT-tests.jar:5.4.0-SNAPSHOT]
	at com.hazelcast.jet.sql_nightly.SqlSTSInnerEquiJoinFaultToleranceStressTest$JobRestarter.run(SqlSTSInnerEquiJoinFaultToleranceStressTest.java:247) [test-classes/:?]
16:57:16,799  INFO |stressTest[processingGuarantee:atLeastOnce, restartGraceful:false]| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
BuildInfo right after stressTest[processingGuarantee:atLeastOnce, restartGraceful:false](com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20230604', buildNumber=20230604, revision=f5984a1, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'stressTest[processingGuarantee:atLeastOnce, restartGraceful:false](com.hazelcast.jet.sql_nightly.SqlSTSInnerNonEquiJoinFaultToleranceStressTest):'
16:57:00, accumulated pauses: 538 ms, max pause: 222 ms, pauses over 1000 ms: 0
16:57:05, accumulated pauses: 973 ms, max pause: 209 ms, pauses over 1000 ms: 0
16:57:10, accumulated pauses: 978 ms, max pause: 171 ms, pauses over 1000 ms: 0
16:57:15, accumulated pauses: 1489 ms, max pause: 1482 ms, pauses over 1000 ms: 1


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-force-offload/50/

### LINKED ISSUE #26063: com.hazelcast.jet.sql.impl.connector.infoschema.MappingsTableTest.test_rows_security_enabled
_master_ (commit 02a156be4151ff173c81676fc444c2059bbedf21)

Failed on oracle-17: https://jenkins.hazelcast.com/job/Hazelcast-master-sonar/322/testReport/com.hazelcast.jet.sql.impl.connector.infoschema/MappingsTableTest/test_rows_security_enabled/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.DistributedObjectDestroyedException: Proxy [hz:impl:mapService:__jet.executionRecords] was destroyed while being created. This may result in incomplete cleanup of resources.
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.destroyProxy(ProxyRegistry.java:320)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:189)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: test_rows_dataconnection in 0.005 seconds.
BuildInfo right after test_rows_security_enabled(com.hazelcast.jet.sql.impl.connector.infoschema.MappingsTableTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231123', buildNumber=20231123, revision=02a156b, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'test_rows_security_enabled(com.hazelcast.jet.sql.impl.connector.infoschema.MappingsTableTest):'
03:52:20, accumulated pauses: 7 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-sonar/322/

### LINKED ISSUE #26071: com.hazelcast.jet.sql.impl.parse.ParserOperationsTest.testSelectAs
_master_ (commit cae25cf53c3847ea2c3387651a66da08f78c1853)

Failed on MacOS: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-MacOS-ZuluJDK11/298/testReport/com.hazelcast.jet.sql.impl.parse/ParserOperationsTest/testSelectAs/
<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.DistributedObjectDestroyedException: Proxy [hz:impl:mapService:__jet.records] was destroyed while being created. This may result in incomplete cleanup of resources.
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.destroyProxy(ProxyRegistry.java:320)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:189)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at ------ submitted from ------.()
	at com.hazelcast.internal.util.ExceptionUtil.cloneExceptionWithFixedAsyncStackTrace(ExceptionUtil.java:348)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.returnOrThrowWithGetConventions(InvocationFuture.java:112)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:100)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:618)
	at com.hazelcast.jet.impl.JetInstanceImpl.filterNonLightJobs(JetInstanceImpl.java:130)
	at com.hazelcast.jet.impl.JetInstanceImpl.getJobsInt(JetInstanceImpl.java:123)
	at com.hazelcast.jet.impl.AbstractJetInstance.getJobs(AbstractJetInstance.java:245)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:150)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testOrderBy in 0.010 seconds.

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-MacOS-ZuluJDK11/298/

### LINKED ISSUE #26091: com.hazelcast.jet.sql.impl.opt.WatermarkThrottlingFrameSizeCalculatorTest.when_onlySlidingWindowInTree_then_returnWindowSize
_pr/26087/merge_ (commit c03bb54d6d544885e2986061a00a9a6b5e3db04d)
Failed on oracle-11 (pr builder): https://jenkins.hazelcast.com/job/Hazelcast-pr-builder/22029/testReport/junit/com.hazelcast.jet.sql.impl.opt/WatermarkThrottlingFrameSizeCalculatorTest/when_onlySlidingWindowInTree_then_returnWindowSize/

<details><summary>Stacktrace:</summary>

```
com.hazelcast.spi.exception.DistributedObjectDestroyedException: Proxy [hz:impl:mapService:__jet.executionRecords] was destroyed while being created. This may result in incomplete cleanup of resources.
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.destroyProxy(ProxyRegistry.java:320)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyLocalDistributedObject(ProxyServiceImpl.java:189)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.destroyDistributedObject(ProxyServiceImpl.java:177)
	at com.hazelcast.spi.impl.AbstractDistributedObject.destroy(AbstractDistributedObject.java:76)
	at com.hazelcast.jet.SimpleTestInClusterSupport.lambda$supportAfter$6(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:210)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381)
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37)
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104)
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:63)
	at com.hazelcast.test.HazelcastParallelClassRunner.access$101(HazelcastParallelClassRunner.java:52)
	at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:165)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_twoConsecutiveSlidingWindowsAgg_then_returnGcdOfWindowsSize in 3.707 seconds.
17:04:33,659  INFO |when_onlySlidingWindowInTree_then_returnWindowSize| - [HazelcastTestSupport] Thread-7 - Shutting down node factory as @After action
Started Running Test: when_noSlidingWindowInTree_then_returnDefault
BuildInfo right after when_onlySlidingWindowInTree_then_returnWindowSize(com.hazelcast.jet.sql.impl.opt.WatermarkThrottlingFrameSizeCalculatorTest): BuildInfo{version='5.4.0-SNAPSHOT', build='20231129', buildNumber=20231129, revision=c03bb54, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_onlySlidingWindowInTree_then_returnWindowSize(com.hazelcast.jet.sql.impl.opt.WatermarkThrottlingFrameSizeCalculatorTest):'
17:04:30, accumulated pauses: 292 ms, max pause: 58 ms, pauses over 1000 ms: 0


No metrics recorded during the test
17:04:33,706  INFO |when_shouldNotExecutePlan_then_returnDefault| - [HazelcastTestSupport] Thread-3 - Shutting down node factory as @After action
17:04:33,706  INFO |when_streamToStreamJoin_then_returnMinPostponeTime| - [HazelcastTestSupport] Thread-2 - Shutting down node factory as @After action

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-pr-builder/22029/

### PR DESCRIPTION
**Pull request by k-jamroz**
`SimpleTestInClusterSupport` cannot be used in parallel tests if they create any objects: data structures (IMaps etc), Jet (Jet jobs, even light jobs) or SQL objects (MAPPINGS etc). The parallel cleanup process might lead to removal of such objects during the test. Check is added to explicitly fail in such situation instead of waiting for race condition to break the test.

As part of this change, some tests that do not require Hazelcast instance were converted to pure unit tests.

The following ArchUnit test can be used to find all potentially problematic tests:

```java
    @Test
    public void reportParallelSimpleTestInClusterSupport() {
        JavaClasses testClasses = new ClassFileImporter()
                .withImportOption(ImportOption.Predefined.ONLY_INCLUDE_TESTS)
                .importPackages("com.hazelcast");
        ArchRuleDefinition.classes().that()
                .areAssignableTo(SimpleTestInClusterSupport.class).and()
                .areAnnotatedWith(Parameterized.UseParametersRunnerFactory.class)
                .should(new ArchCondition<>("ser") {
                    @Override
                    public void check(JavaClass item, ConditionEvents events) {
                        if (HazelcastParallelParametersRunnerFactory.class.isAssignableFrom(
                                item.getAnnotationOfType(Parameterized.UseParametersRunnerFactory.class).value())) {
                            System.out.println(item.getFullName());
                        }
                    }
                })
                .check(testClasses);

        ArchRuleDefinition.classes().that()
                .areAssignableTo(SimpleTestInClusterSupport.class).and()
                .areAnnotatedWith(RunWith.class)
                .should(new ArchCondition<>("ser") {
                    @Override
                    public void check(JavaClass item, ConditionEvents events) {
                        if (HazelcastParallelClassRunner.class.isAssignableFrom(
                                item.getAnnotationOfType(RunWith.class).value())) {
                            System.out.println(item.getFullName());
                        }
                    }
                })
                .check(testClasses);
    }
```

Improves #26007

Fixes #26091
Fixes #26071
Fixes #26063
Fixes #24680
Fixes #24713

### CODE REVIEW

**Review by TomaszGaweda — APPROVED** [review]

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql_slow/SqlBasicSlowTest.java [hunk 1]
```diff
@@ -18,23 +18,12 @@
...
 
 import java.util.ArrayList;
 import java.util.Collection;
 import java.util.List;
 
-import static org.junit.runners.Parameterized.UseParametersRunnerFactory;
-
-@RunWith(HazelcastParametrizedRunner.class)
-@UseParametersRunnerFactory(HazelcastParallelParametersRunnerFactory.class)
-@Category({SlowTest.class, ParallelJVMTest.class})
```
Comment (Fly-Style) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql_slow/SqlBasicSlowTest.java:37]: Is it fast enough be be a `QuickTest`?

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql_slow/SqlBasicClientSlowTest.java [hunk 2]
```diff
@@ -17,18 +17,7 @@
...
-import com.hazelcast.test.annotation.ParallelJVMTest;
-import com.hazelcast.test.annotation.SlowTest;
-import org.junit.experimental.categories.Category;
-import org.junit.runner.RunWith;
 
-import static org.junit.runners.Parameterized.UseParametersRunnerFactory;
-
-@RunWith(HazelcastParametrizedRunner.class)
-@UseParametersRunnerFactory(HazelcastParallelParametersRunnerFactory.class)
-@Category({SlowTest.class, ParallelJVMTest.class})
```
Comment (Fly-Style) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql_slow/SqlBasicClientSlowTest.java:31]: Is it fast enough be be a QuickTest?

**Review by Fly-Style — APPROVED** [review]
LGTM!

**Review by TomaszGaweda — APPROVED** [review]
