### PR TITLE
Fixed wakeup bug in NioOutboundPipeline

### LINKED ISSUE #14830: Outbound pipeline is not wake-up properly after merging the write-through changes
The TLS handshakes got stuck in Hazelcast EE after merging #14696 .

### PR DESCRIPTION
**Pull request by pveentjer**
Fixes #14830.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java [hunk 1]
```diff
@@ -52,6 +52,12 @@
         extends NioPipeline
         implements Supplier<OutboundFrame>, OutboundPipeline {
 
+    private enum State {
+        SCHEDULED,
+        UNSCHEDULED,
```
Comment (kwart) [inline hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java]: Shouldn't we place the `UNSCHEDULE` as the first item in the enum? It would keep the `isScheduled`/`scheduled` probes more compatible.

Comment (pveentjer) [reply hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java]: You are right.

**Comment by pveentjer** [comment]
I have addressed your comment @kwart . Can you have another look?

File: hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java [hunk 2]
```diff
@@ -137,8 +143,8 @@ private long idleTimeMs() {
     }
 
     @Probe(level = DEBUG)
-    private long isScheduled() {
-        return scheduled.get() ? 1 : 0;
+    private long scheduled() {
+        return scheduled.get().ordinal();
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java]: This is rather unconventional. Any reason we can't use something like `return scheduled.get() == State.SCHEDULED ? 1 : 0`?
I'm thinking if someone changes the order. The value of this method returns as well.
