### PR TITLE
Fixes memory leak in client listeners

### LINKED ISSUE #5893: Possible memory leak when client adds/removes EntryListeners
Below is a minimal working example which demonstrates the issue.
```java
import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;

public class ListenerMember
{
    public static void main(String[] args) {
        new ListenerMember().run();
    }

    public void run() {
        Config cfg = new Config();
        Hazelcast.newHazelcastInstance(cfg);
    }
}
```
```java
import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.config.ClientNetworkConfig;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import com.hazelcast.map.listener.MapListener;


public class ListenerClient implements MapListener
{
    public static void main(String[] args) {
        new ListenerClient().run();
    }

    public void run() {
        ClientNetworkConfig networkConfig = new ClientNetworkConfig();
        networkConfig.addAddress("127.0.0.1:5701");
        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setNetworkConfig(networkConfig);
        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);

        IMap<Integer, String> map = client.getMap("testmap");

        while (true) {
            final String listenerId = map.addEntryListener(this, false);
            map.removeEntryListener(listenerId);
        }
    }
}
```
 `ListenerMember` was run for 1 minute before starting `ListenerClient`. The image below shows the heap usage of `ListenerMember` over the course of approximately 30 minutes, as reported by Java VisualVM.
cluster_member_heap

The test was run using versions 3.4.2, 3.5.1, and 3.6 snapshot (20150807.171323-259), and all version exhibited the same behavior. When using version 3.4, `ListenerClient` implemented `EntryListener` instead of `MapListener` (which was not available in 3.4)

The above image was produced using 3.6 snapshot, using Java 7 on a Windows 7 machine using the following JVM arguments: -server -Xms1G -Xmx1G. Similar behavior is exhibited when running a similar test using Hazelcast Simulator 0.5 across multiple CentOS 6.6 virtual machines.

### PR DESCRIPTION
**Pull request by sancar**
Memory leak occurs when a listener added and removed from client.
A remove runnable in the collection that is stored in ClientEndpointImpl
is the leftover. This remove runnable collection was used to cleanup the
listeners when client is disconnected. With this change, listener removal
is always done via this remove runnables and runnable itself removed.

fixes #5893

### CODE REVIEW

**Comment by mdogan** [comment]
Can you verify the fix with tests please? Tests should verify that when a listener (map, queue etc) is registered and then deregistered, `ClientEndpointImpl.removeListenerActions` should be empty.

**Comment by gurbuzali** [comment]
needs rebase

**Comment by sancar** [comment]
Tests are added 
https://github.com/hazelcast/hazelcast/pull/6097/files#diff-aaa1dacf7c91fef1510077360199a164
https://github.com/hazelcast/hazelcast/pull/6097/files#diff-9d65b88b15d9707de1dff8762fa8449f

File: hazelcast-client-new/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java [hunk 1]
```diff
@@ -0,0 +1,224 @@
...
+        });
+    }
+
+    @Test
+    public void testDistributedObjectListeners() {
+        testListenerLeak(new IFunction() {
+            @Override
+            public Object apply(Object input) {
+                HazelcastInstance client = (HazelcastInstance) input;
+                String id = client.addDistributedObjectListener(new DistributedObjectListener() {
```
Comment (pveentjer) [inline hazelcast-client-new/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java]: I would use a mock here since you don't care about its content. 

String id = client.addDistributedObjectListener(mock(DistributedObjectListener.class));

This increased the readability of the code.

File: hazelcast-client-new/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java [hunk 2]
```diff
@@ -0,0 +1,224 @@
...
+
+
+    @Test
+    public void testTopicMessageListener() {
+        testListenerLeak(new IFunction() {
+            @Override
+            public Object apply(Object input) {
+                HazelcastInstance client = (HazelcastInstance) input;
+                ITopic<Object> topic = client.getTopic(randomString());
+                String id = topic.addMessageListener(new MessageListener<Object>() {
```
Comment (pveentjer) [inline hazelcast-client-new/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java]: Also a mock here.

File: hazelcast-client-new/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java [hunk 3]
```diff
@@ -0,0 +1,224 @@
...
+    }
+
+    @Test
+    public void testMapPartitionLostListeners() {
+        testListenerLeak(new IFunction() {
+            @Override
+            public Object apply(Object input) {
+                HazelcastInstance client = (HazelcastInstance) input;
+                IMap map = client.getMap(randomString());
+                String id = map.addPartitionLostListener(new MapPartitionLostListener() {
```
Comment (pveentjer) [inline hazelcast-client-new/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java]: Use a mock

 String id = map.addPartitionLostListener(mock(MapPartitionLostListener.class));

Easier to read

File: hazelcast-client/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java [hunk 4]
```diff
@@ -0,0 +1,232 @@
...
+    public void testMapPartitionLostListeners() {
+        testListenerLeak(new IFunction() {
+            @Override
+            public Object apply(Object input) {
+                HazelcastInstance client = (HazelcastInstance) input;
+                IMap map = client.getMap(randomString());
+                String id = map.addPartitionLostListener(new MapPartitionLostListener() {
+                    @Override
+                    public void partitionLost(MapPartitionLostEvent event) {
+
```
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java]: Also a mock

File: hazelcast-client/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java [hunk 5]
```diff
@@ -0,0 +1,232 @@
...
+        });
+    }
+
+    @Test
+    public void testDistributedObjectListeners() {
+        testListenerLeak(new IFunction() {
+            @Override
+            public Object apply(Object input) {
+                HazelcastInstance client = (HazelcastInstance) input;
+                String id = client.addDistributedObjectListener(new DistributedObjectListener() {
```
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java]: A mock.

File: hazelcast-client/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java [hunk 6]
```diff
@@ -0,0 +1,232 @@
...
+
+
+    @Test
+    public void testTopicMessageListener() {
+        testListenerLeak(new IFunction() {
+            @Override
+            public Object apply(Object input) {
+                HazelcastInstance client = (HazelcastInstance) input;
+                ITopic<Object> topic = client.getTopic(randomString());
+                String id = topic.addMessageListener(new MessageListener<Object>() {
```
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/listeners/ListenerLeakTest.java]: A mock.

File: hazelcast/src/main/java/com/hazelcast/client/ClientEndpoint.java [hunk 7]
```diff
@@ -44,6 +45,10 @@
 
     void setListenerRegistration(String service, String topic, String id);
 
+    void setListenerRemoveAction(String registrationId, Callable<Boolean> removeAction);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/ClientEndpoint.java]: What is this method supposed to do? From the naming it isn't clear to me and there is no javadoc.

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
@pveentjer @mdogan I updated the pr according to reviews.

**Comment by gurbuzali** [comment]
:+1:
