### PR TITLE
Fix ClientInvocation Retry

### LINKED ISSUE #18062: 5G of repeated warning logged:   com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1208)
this exact WARNING message was repeated for 5Gigs in the clients logs,   printing the warning just once would suffice 

```

WARNING: hz.client_1 [HZ] [4.2-SNAPSHOT] Future.complete(Object) on completed future. Request: ClientMessage{connection=null, length=88, operation=Map.Set, isRetryable=false, correlationId=27603811, messa
geType=10f00, isEvent=false, isfragmented=false}, current value: ExceptionalResult{cause=java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.map.impl.operation.SetOperat
ion{serviceName='hz:impl:mapService', identityHash=1498203592, partitionId=178, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=60000, tenantControl=com.
hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, name=mapBak1}}, offered value: ClientMessage{connection=ClientConnection{alive=true, connectionId=231, channel=NioChannel{/10.0.0.183:33879->/10.0.0.2
0:5701}, remoteAddress=[10.0.0.20]:5701, lastReadTime=2021-01-13 14:25:18.699, lastWriteTime=2021-01-13 14:25:18.699, closedTime=never, connected server version=4.2-SNAPSHOT}, length=19, operation=null, i
sRetryable=false, correlationId=27614360, messageType=10f01, isEvent=false, isfragmented=false}
java.lang.Exception
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1208)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1185)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1174)
	at com.hazelcast.client.impl.spi.impl.ClientInvocation.complete(ClientInvocation.java:242)
	at com.hazelcast.spi.impl.operationservice.impl.BaseInvocation.completeWithPendingResponse(BaseInvocation.java:153)
	at com.hazelcast.spi.impl.operationservice.impl.BaseInvocation.detectAndHandleBackupTimeout(BaseInvocation.java:142)
	at com.hazelcast.client.impl.spi.impl.ClientInvocationServiceImpl$CleanResourcesTask.run(ClientInvocationServiceImpl.java:305)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)

```

### PR DESCRIPTION
**Pull request by sancar**
Bug Description:
There seems to be multiple problems which is caused by single problem
we allow multiple threads to retry/change state of single invocation.
Example:
A connection is closed. CleanResourcesTask checks periodically and
handles invocation with connection closed.
   https://github.com/hazelcast/hazelcast/blob/04e9df4c2f406238267a8d45fbc9ae476b40c7d5/hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java#L290-L301

This continues and schedules a retry here
    https://github.com/hazelcast/hazelcast/blob/04e9df4c2f406238267a8d45fbc9ae476b40c7d5/hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocation.java#L305-L315

Before this task gets a chance to run, CleanResoursTask can wakeup
check the same connection and schedule a new retry.

As a solution I first, try to sync them on `deRegisterInvocation(callid)`
,but this does not work. The idea was to only one that can
deRegisterInvocation will retry. Also a response/exception from
remote will notify if they can deregister the invocation.
One problem is correlation id is changed by the retried task, and
other threads are trying to deregister by reading that correlationId.
In response path, we have correlation id coming from remote but in
connection closed case, we don't have one to use(instead of reading
from invocation itself)

Another problem is how we handle connection close. Lets say a member
is about the close and we send an invocation to it. It can send,
ClusterPassive, InstanceNotActive like exceptions. And it closes the
connection after that. We have two cases to handle on the client side.
Lets say we have detected that connection is closed again in
CleanResoursesTask, and we are about to notify the invocation.
In the mean time we got InstanceNotActiveException as well, and we
retried it on another connection/with new call id.
Notify for connection close deregisters the new retry which should
not happen.

I have noticed we had similar problems on the core side.
#7270

I have investigate the solutions and core codebase
#9296
#9303

They are not suitable for the client. Especially connection close
case is different. On the member, we have MemberLeftException
which is guarded by `MemberListVersion` which are not applicable
to the client. So for the client, solution grew around `connection`
naturally.

Solution:
We coordinate all threads that wants to notify the invocation.
We achieve synchronization of different threads via `sentConnection`
field sentConnection starts as null.
It is set to a non-null when `connection` to be sent is determined.
It is set to null when a response/exception is going to be notified.
It is trying to be compared and set to null on connection close case
with dead connection, to prevent invocation to be notified which is
already retried on another connection.
Only one thread that can set this to null can be actively notify
a response/exception.

This way we make sure that only one thread changes the states
(changing correlation id/deregistration of invication).

fixes #18062

### CODE REVIEW

**Review by ihsandemir — COMMENTED** [review]
Did you consider this alternative solution?: keeping another unique `invocation-id` independent of the `correlation-id` which could be used for register/deregister? You can de-register with this final constant invocation id.

**Comment by sancar** [comment]
@ihsandemir I did consider a couple of alternatives but this was not one of them. 
Putting one other shared map on the hot path could be problematic. 
Also note that the deregistration is only a small part of the problem. We need to coordinate connection close/retries. 
Please read the description in more detail especially around `connection close`. I don't see how I can use this idea to solve all the problems mentioned.

**Comment by sancar** [comment]
Test failure is not related and reported here https://github.com/hazelcast/hazelcast/issues/18310

**Comment by sancar** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java [hunk 1]
```diff
@@ -287,29 +294,29 @@ public boolean isSmartRoutingEnabled() {
...
-            }
         }
 
-        private void notifyException(ClientInvocation invocation, ClientConnection connection) {
-            Exception ex = new TargetDisconnectedException(connection.getCloseReason(), connection.getCloseCause());
-            invocation.notifyException(ex);
+        @Override
+        public void connectionRemoved(ClientConnection connection) {
+            for (ClientInvocation invocation : invocations.values()) {
+                if (invocation.getPermissionToNotifyForDeadConnection(connection)) {
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java:315]: Shouldn't we first check if the invocations sent connection is actually the connection that is closed before trying the acquire permission to notify? If the sentConnection of the invocation is something else, then CAS will fail and we will spin until the sentConnection for the invocation becomes null

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java [hunk 2]
```diff
@@ -287,29 +294,29 @@ public boolean isSmartRoutingEnabled() {
...
-                }
-            }
         }
 
-        private void notifyException(ClientInvocation invocation, ClientConnection connection) {
-            Exception ex = new TargetDisconnectedException(connection.getCloseReason(), connection.getCloseCause());
-            invocation.notifyException(ex);
+        @Override
+        public void connectionRemoved(ClientConnection connection) {
+            for (ClientInvocation invocation : invocations.values()) {
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java:314]: Can this and the 
```
       if (!connection.write(clientMessage)) {
            if (invocation.getPermissionToNotifyForDeadConnection(connection)) {
                IOException exception = new IOException("Packet not sent to " + connection.getRemoteAddress() + " "
                        + clientMessage);
                invocation.notifyExceptionWithOwnedPermission(exception);
            }	            }
            return false;	        
       }
``` 

race?

I mean, lets say we registered the invocation and set the `sentConnection`, then the connection is closed, and we came here, acquire the permission, and retry the invocation and set the `sentConnection` to something alive. Then the code I posted above will not be able to do `SENT_CONNECTION.compareAndSet(this, deadConnection, null)` in `getPermissionToNotifyForDeadConnection` and spin

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java (hunk 1 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java:316]: The code is simplified, we don't have the while loop anymore.

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java (hunk 2 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java:315]: The code is simplified, we don't have the while loop anymore.

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocation.java [hunk 3]
```diff
@@ -221,15 +241,44 @@ public void setInvocationTimeoutMillis(long invocationTimeoutMillis) {
...
+     *
      * @param clientMessage return true if invocation completed
      */
     void notify(ClientMessage clientMessage) {
         assert clientMessage != null : "response can't be null";
         int expectedBackups = clientMessage.getNumberOfBackupAcks();
 
-        notifyResponse(clientMessage, expectedBackups);
+        if (getPermissionToNotify(clientMessage.getCorrelationId())) {
+            assert sentConnection == null;
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocation.java:255]: Minor: It is just a micro-optimization but we can move `int expectedBackups = clientMessage.getNumberOfBackupAcks();`
to the if block so that we are not reading it when we don't need it

**Review by mdumandag — APPROVED** [review]

**Review by yuce — CHANGES_REQUESTED** [review]
LGTM, except minor things.

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocation.java [hunk 4]
```diff
@@ -168,7 +183,7 @@ private void invokeOnSelection() {
             if (isBindToSingleConnection()) {
                 boolean invoked = invocationService.invokeOnConnection(this, (ClientConnection) connection);
                 if (!invoked) {
-                    notifyException(new IOException("Could not invoke on connection " + connection));
+                    notifyExceptionWithOwnedPermission(new IOException("Could not invoke on connection " + connection));
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocation.java:186]: IOException is used a lot of places. It is our choice when we know that this message is not written to socket and safe to retry.

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java [hunk 5]
```diff
@@ -158,10 +159,13 @@ public void addBackupListener() {
 
     public void start() {
         responseHandlerSupplier.start();
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java:161]: No it is not possible for `start` to be called more than once. User can not call `start`, we don't have such an API.

File: hazelcast/src/main/java/com/hazelcast/client/impl/proxy/IExecutorDelegatingFuture.java [hunk 6]
```diff
@@ -111,9 +110,7 @@ private boolean invokeCancelRequest(boolean mayInterruptIfRunning) throws Interr
     }
 
     private void waitForRequestToBeSend() throws InterruptedException {
-        InternalCompletableFuture future = getFuture();
-        ClientInvocationFuture clientCallFuture = (ClientInvocationFuture) future;
-        clientCallFuture.getInvocation().getSendConnectionOrWait();
+        ClientInvocationFuture future = getFuture();
+        future.getInvocation().waitInvoked();
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/proxy/IExecutorDelegatingFuture.java:114]: I prefer this way.

File: hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java [hunk 7]
```diff
@@ -221,28 +225,31 @@ private boolean send(ClientInvocation invocation, ClientConnection connection) {
             throw new HazelcastClientNotActiveException();
         }
 
+        ClientMessage clientMessage = invocation.getClientMessage();
         if (isBackupAckToClientEnabled) {
-            invocation.getClientMessage().getStartFrame().flags |= ClientMessage.BACKUP_AWARE_FLAG;
+            clientMessage.getStartFrame().flags |= ClientMessage.BACKUP_AWARE_FLAG;
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/spi/impl/ClientInvocationServiceImpl.java:230]: Matter of taste. May be we can discuss later, and create a separate pr if we see it necessary.

**Comment by Danny-Hazelcast** [comment]
looks to fix the issue https://github.com/hazelcast/hazelcast/issues/18062

**Review by yuce — APPROVED** [review]

**Review by ihsandemir — APPROVED** [review]
