### PR TITLE
Fix NPE and AIOB exceptions while getting address aliases

### LINKED ISSUE #19152: NPE from TcpServerConnectionChannelErrorHandler
5.0-SNAPSHOT (`20210722 - 97e59fa`) is throwing NPEs that 5.0-BETA-1 doesn't

```
09:08:00.569 ERROR hz.practical_khorana.IO.thread-in-0 c.h.i.s.t.TcpServerConnectionChannelErrorHandler - [10.104.3.7]:5701 [grid] [5.0-SNAPSHOT] null 
java.lang.NullPointerException: null
	at com.hazelcast.internal.util.AddressUtil.getAliases(AddressUtil.java:368)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.addressAliases(TcpServerConnection.java:273)
	at com.hazelcast.internal.server.tcp.TcpServerConnection.close(TcpServerConnection.java:255)
	at com.hazelcast.internal.server.tcp.TcpServerConnectionChannelErrorHandler.onError(TcpServerConnectionChannelErrorHandler.java:51)
	at com.hazelcast.internal.networking.nio.NioPipeline.onError(NioPipeline.java:277)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:385)
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:368)
	at com.hazelcast.internal.networking.nio.NioThread.selectLoop(NioThread.java:294)
	at com.hazelcast.internal.networking.nio.NioThread.executeRun(NioThread.java:249)
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102)
```

### PR DESCRIPTION
**Pull request by ufukyilmaz**
This PR fixes the `NPE` and `ArrayIndexOutBound` exceptions thrown while
fetching address aliases.

Note: This [TcpServerConnectionManager_MemoryLeakTest#test_connectionCleanedUpWhenClosed_withoutPlaneIndexSet](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager_MemoryLeakTest.java#L67-L90)
is written when the handshake processing is performed before the
planeIndex is set. After that, this processing order is changed to
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerControl.java#L84-L85.
For now, this is testing a bit artificial scenario. But, I think it is better to have
this since it can show up some errors like this.

I was also thinking about remove this block because I think that the connection registration should not be
performed when `planeIndex` is not set:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java#L298-L324.
But, I didn't understand how this `onConnectionClose` method is
synchronized with the connection registration and then I hesitated to
remove this cleanup logic. 

Apart from that, I didn't do any null handling in the
[TcpServerControl#process](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerControl.java#L115-L125).
Since the else block is added a long ago and it didn't do any handling
(I thought that it should be thrown there).  
  
Fixes #19152,  #19177

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Request reviewers if possible

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/util/AddressUtil.java [hunk 1]
```diff
@@ -364,7 +365,7 @@ public static AddressMatcher getAddressMatcher(String address) {
         return selectedPorts;
     }
 
-    public static Collection<Address> getAliases(InetSocketAddress inetSocketAddress) {
+    public static Collection<Address> getAliases(@Nonnull InetSocketAddress inetSocketAddress) {
```
Comment (kwart) [inline hazelcast/src/main/java/com/hazelcast/internal/util/AddressUtil.java:368]: I'm curious if there is a reason to require non `null`s. Maybe we could allow it and return an empty collection instead. WDYT?

Comment (ufukyilmaz) [reply hazelcast/src/main/java/com/hazelcast/internal/util/AddressUtil.java:368]: There is not any specific reason, I just want to handle it in this way. I can change it.

**Comment by vbekiaris** [comment]
@ufukyilmaz the cleanup block [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManagerBase.java#L298-L324) and related test are still relevant. Consider this scenario:

- memberA open connection to memberB
- memberA sends handshake packet to memberB
- memberB crashes -> no handshake response is received on memberA side
- memberA handles connection-closed event -> `planeIndex` is still `-1` (because it would be set on memberA while processing the handshake response from memberB, which was never received).

related https://github.com/hazelcast/hazelcast/issues/17238#issuecomment-694241589

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager.java [hunk 2]
```diff
@@ -112,8 +113,19 @@ public ServerConnection get(Address address, int streamId) {
...
-        return plane.getAddresses(connection);
+        Plane plane;
+        if (connection.getPlaneIndex() == -1) {
+            // It could be the case that planeIndex of the connection may not
+            // be set. In this case, we return only the remote address of
+            // connection. Since the plane index is set before the connection
+            // registration (handshake processing), we don't expect this
+            // connection exist in connectionMaps of the planes and don't
+            // search on them.
+            return Collections.singleton(connection.getRemoteAddress());
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager.java:124]: Can this be a singleton with `null` as single element? Will it be handled gracefully by consumers of `getKnownAliases`?

Comment (ufukyilmaz) [reply hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager.java:124]: This address is not set in its initialization and I think I should behave it as it can be null. Thanks for pointing this out

**Comment by ufukyilmaz** [comment]
https://github.com/hazelcast/hazelcast/pull/19228#issuecomment-890943300
AFAIU, the connection registration to the plane is performed after this plane index is set. (error handler registration vs. is also performed after this planeIndex is set.). 
In your described scenario:
MemberA cannot handle connection-closed event while planeIndex is still -1 (because the error handler won't registered before this planeIndex is set.) 

See: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerControl.java#L84-L85 and https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerControl.java#L179.

**Comment by vbekiaris** [comment]
> AFAIU, the connection registration to the plane is performed after this plane index is set.

Depends from which point of view you see it, connection initiator or target. Let me be more specific with the example above:

- `memberA` opens connection to `memberB` using `getOrConnect`. At this point, `memberA`'s connection manager adds `memberB`'s address to its `connectionsInProgress` Set (so it won't attempt creating another connection until that one is either established or fails). A `Connection` object is created on `memberA` and its `planeIndex` is yet unset.
- `memberB` accepts the connection in `TcpServerAcceptor` and creates a new `Connection` object on its own side.
- `memberA` sends `MemberHandshake` packet to `memberB`.
- `memberB` crashes -> it does not send a `MemberHandshake` response to `memberA` -> the `Connection` object on `memberA` still has its `planeIndex` unset.
- `memberA` handles a [selection key error](https://github.com/hazelcast/hazelcast/blob/40d555dc1110da9f63fd66f504c83d4382d0384b/hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioThread.java#L385) as the socket is closed -> `NioPipeline#errorHandler` is invoked  -> ... -> `ConnectionLifecycleListenerImpl.onConnectionClose` is invoked with `planeIndex` still being `-1`.

I hope this makes sense.

File: hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager.java [hunk 3]
```diff
@@ -112,8 +113,26 @@ public ServerConnection get(Address address, int streamId) {
...
+            // be set. In this case, we return only the remote address of
+            // connection, if it is not null. We return an empty set if it's
+            // null.
+            // Since the plane index is set before the connection
+            // registration (handshake processing), we don't expect this
+            // connection exist in connectionMaps of the planes and don't
+            // search for it on them.
+            Address remoteAddress = connection.getRemoteAddress();
+            if (remoteAddress != null) {
+                return Collections.singleton(connection.getRemoteAddress());
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/server/tcp/TcpServerConnectionManager.java:128]: nit
```suggestion
                return Collections.singleton(remoteAddress);
```

**Review by vbekiaris — APPROVED** [review]

**Review by leszko — APPROVED** [review]
I checked and It fixes the issue in Kubernetes. Thanks @ufukyilmaz

**Review by ramizdundar — APPROVED** [review]
