### PR TITLE
Catch test failures in `LocalStatsDelegateTest`

### LINKED ISSUE #25411: `LocalStatsDelegateTest.testMapStats_Created_OnlyOnce_InGivenInternal()` failures not being caught
Assertion failures in `com.hazelcast.internal.jmx.LocalStatsDelegateTest.MapStatsThread.run()` are happening in a different thread, which means if they fail, the test suite still passes.

These tests appear to consistently fail for me.

This was also flagged in Sonar.

### PR DESCRIPTION
**Pull request by JackPGreen**
- Ensure assertion failures fail the build
- Consolidate duplicate code between tests
- Use existing `assertGreaterThanOrEqualTo` method
- Annotate existing failing test as `NightlyTest` - fixing the test failure is out of scope for this issue, so this way can fold into the regular test-failure process

Fixes #25411

### CODE REVIEW

**Comment by JackPGreen** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/internal/jmx/LocalStatsDelegateTest.java [hunk 1]
```diff
@@ -16,168 +16,133 @@
...
+            final int mapStatsThread2SleepMs, final int sleepSeconds) throws Exception {
+        final IMap<Object, Object> trial = createHazelcastInstance().getMap("trial");
 
         final StatsSupplier<LocalMapStats> statsSupplier = new LocalMapStatsSupplier(trial);
-        final LocalStatsDelegate localStatsDelegate = new LocalStatsDelegate<LocalMapStats>(statsSupplier, 5);
+        final LocalStatsDelegate<LocalMapStats> localStatsDelegate = new LocalStatsDelegate<>(statsSupplier, intervalSec);
 
-        Thread mapStatsThread1 = new Thread(new MapStatsThread(localStatsDelegate, done, true, 100));
-        Thread mapStatsThread2 = new Thread(new MapStatsThread(localStatsDelegate, done, true, 80));
+        final ExecutorService executor = Executors.newFixedThreadPool(3);
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/internal/jmx/LocalStatsDelegateTest.java:77]: The `executor` is not shutdown after the test so resources will leak. If you use the executor, make it a field in the test class so you can shut it down in `@AfterClass`. Alternatively, you can use `HazelcastTestSupport#spawn` to conveniently spawn threads.

File: hazelcast/src/test/java/com/hazelcast/internal/jmx/LocalStatsDelegateTest.java [hunk 2]
```diff
@@ -16,168 +16,133 @@
...
         mapPutThread.start();
 
-        sleepSeconds(60);
+        sleepSeconds(sleepSeconds);
 
         done.set(true);
 
-        mapStatsThread1.join();
-        mapStatsThread2.join();
+        mapStatsThread1.get();
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/internal/jmx/LocalStatsDelegateTest.java:91]: alternative for waiting on both futures could be `FutureUtil#waitWithDeadline` utility method

**Review by vbekiaris — COMMENTED** [review]
good catch!

File: hazelcast/src/test/java/com/hazelcast/internal/jmx/LocalStatsDelegateTest.java (hunk 2 above)
Comment (JackPGreen) [reply hazelcast/src/test/java/com/hazelcast/internal/jmx/LocalStatsDelegateTest.java]: 155f1eb8f8759485d056c3ca2867da7617dc073d

**Review by vbekiaris — APPROVED** [review]

**Comment by JackPGreen** [comment]
run-lab-run

**Comment by JackPGreen** [comment]
run-lab-run
