### PR TITLE
Fix MemberToMemberDiscoveryTest

### LINKED ISSUE #13942: MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest
_master_ (commit 124c1da596a0559159d64c6afd34ed95b015ff71)

Failed on Sonar build: https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/248/testReport/com.hazelcast.spi.discovery.multicast/MemberToMemberDiscoveryTest/formClusterWithTwoMembersTest/

Stacktrace:
```
java.lang.AssertionError: Cluster size is not correct. Expected: 2, actual: 1, instance index: 0
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:1083)
	at com.hazelcast.test.HazelcastTestSupport$14.run(HazelcastTestSupport.java:1111)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1294)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1311)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1108)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:1096)
	at com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest(MemberToMemberDiscoveryTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Standard output:
```
Hiccups measured while running test 'formClusterWithTwoMembersTest(com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest):'
13:10:45, accumulated pauses: 1724 ms, max pause: 216 ms, pauses over 1000 ms: 0
13:10:50, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:10:55, accumulated pauses: 30 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:11:00, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:11:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:11:10, accumulated pauses: 27 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:11:15, accumulated pauses: 28 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:11:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:11:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:11:30, accumulated pauses: 31 ms, max pause: 3 ms, pauses over 1000 ms: 0
13:11:35, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:11:40, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:11:45, accumulated pauses: 29 ms, max pause: 2 ms, pauses over 1000 ms: 0
13:11:50, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:11:55, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:00, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:10, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:15, accumulated pauses: 31 ms, max pause: 4 ms, pauses over 1000 ms: 0
13:12:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:25, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:30, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:35, accumulated pauses: 28 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:12:40, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:12:45, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:12:50, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:12:55, accumulated pauses: 238 ms, max pause: 231 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by blazember**
If the two nodes configured in this test can't form a cluster initially due to hiccups or any multicasting problem the two nodes form two single-member cluster, then the test waits for the configured eventual timeout and then it fails, because no merging attempt is made. This is because default `hazelcast.merge.first.run.delay.seconds` is 300 seconds, which is greater then the timeout 120 seconds. This commit decreases this setting to 5 seconds and also decreases `hazelcast.merge.next.run.delay.seconds` to 5 seconds from 120 seconds giving the two nodes a chance to discover each other even if there is a hiccup during the initial join.

Fixes #13942

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java [hunk 1]
```diff
@@ -44,6 +44,10 @@
     @Rule
     public final OverridePropertyRule overrideJoinWaitSecondsRule = set("hazelcast.wait.seconds.before.join", "10");
     @Rule
+    public final OverridePropertyRule overrideMergeFirstRunDelayRule = set("hazelcast.merge.first.run.delay.seconds", "30");
```
Comment (mmedenjak) [inline hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java]: You can lower it even further. See our [split brain tests](https://github.com/hazelcast/hazelcast/blob/92ca85687ad1f9cc2057a7cd3b7a27f22bad8019/hazelcast/src/test/java/com/hazelcast/test/SplitBrainTestSupport.java#L156-L160).

Comment (blazember) [reply hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java]: :+1:  
Done
