### PR TITLE
fixing MC-838 by using lenient scalar/primitive validation

### LINKED ISSUE #18939: Unable to use digits-only String values in the YAML config
YAML schema validation doesn't handle properly String values containing only digits (in `5.0-SNAPSHOT`).

Reproducer:
```yaml
hazelcast:
  cluster-name: '1234'
```

**Fails with the following stacktrace:**
```expected type: String, found: Integer
  instance location: #/hazelcast/cluster-name
  keyword location: #/properties/hazelcast/properties/cluster-name

	at com.hazelcast.internal.config.YamlConfigSchemaValidator.wrap(YamlConfigSchemaValidator.java:55)
	at com.hazelcast.internal.config.YamlConfigSchemaValidator.validate(YamlConfigSchemaValidator.java:82)
	at com.hazelcast.config.YamlConfigBuilder.parseAndBuildConfig(YamlConfigBuilder.java:163)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:134)
	at com.hazelcast.config.YamlConfigBuilder.build(YamlConfigBuilder.java:127)
	at com.hazelcast.config.YamlConfigBuilderTest.buildConfig(YamlConfigBuilderTest.java:1825)
	at com.hazelcast.config.YamlConfigBuilderTest.testClusterName(YamlConfigBuilderTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by erosb**
## Removing automatic conversion of string values and using lenient validation for scalars

Fixes #18939 (MC-838)

### The original problem

While working on #18441 , there was a problem related to config replacers: the replacers (correctly) were running before the yaml schema validation, and the config replacers always put string values into the yaml DOM, regardless if the string values actually presented other scalar values. This problem was highlighted by `YamlConfigImportVariableReplacementTest#readVariables()` failing.

### The first workaround

In #18441 it was worked around [by converting all string scalars to corresponding Booleans / Numbers](https://github.com/hazelcast/hazelcast/pull/18441/files?file-filters%5B%5D=.java&file-filters%5B%5D=.xml&file-filters%5B%5D=.yaml#diff-aaec45fad254a40b71de573974c556e1812c8229f147a92c7e0dd455280a9a9aR56), whenever the string was parse-able. This conversion was performed after the config replacers, but before the schema validation invocation, and it seemingly solved the problem.

### The regression

As reported by @kwart in #18939 , the workaround introduced a new problem: the automatic string-to-other-scalar conversion was performed in cases when it was unnecessary, moreover, it actually broke the subsequent schema validation, because a yaml like `cluster-name: '1234'` failed to validate, because the `'1234'` string literal got converted into an integer, but the schema expects a string as the `cluster-name`, therefore it resulted in a schema validation exception.

### The second workaround

This PR removes the first workaround (automatic string-to-other-scalar conversion). Instead, a lenient validation mode was introduced for primitives, in which mode the validator accepts strings as numbers or booleans, if they are parseable. This was done in https://github.com/everit-org/json-schema/pull/429 and is included in version `1.13.0` of the library. The documentation of the lenient validation is [here](https://github.com/everit-org/json-schema#lenient-mode).

This current PR upgrades to version 1.13.0 of the validator library, uses the lenient validation, and adds a test making sure that this regression doesn't happen again.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java [hunk 1]
```diff
@@ -77,8 +79,12 @@ public void validate(YamlMapping rootNode) {
                                 + " root schema document, " + definedRootNodeCount + " are present",
                         "#", "#", emptyList());
             }
-            SCHEMA.validate(YamlToJsonConverter.convert(rootNode));
+            Validator.builder()
+                    .primitiveValidationStrategy(PrimitiveValidationStrategy.LENIENT)
+                    .build()
+                    .performValidation(SCHEMA, YamlToJsonConverter.convert(rootNode));
         } catch (ValidationException e) {
+            e.printStackTrace();
```
Comment (kwart) [inline hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java:87]: Probably a leftover. If you want to print the stacktrace, use the Logger instead.

**Review by kwart — CHANGES_REQUESTED** [review]
Just one exception handling needs improvement, otherwise LGTM.

File: hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java (hunk 1 above)
Comment (erosb) [reply hazelcast/src/main/java/com/hazelcast/internal/config/YamlConfigSchemaValidator.java:87]: Thanks, removed.

**Review by kwart — APPROVED** [review]
