### PR TITLE
Fixes DelegatingCompletableFuture

### LINKED ISSUE #18053: DelegatingCompletableFuture does not complete if the callback throws an exception
From the javadocs for `CompletionStage.whenComplete()`:

```
Unlike method handle, this method is not designed to translate completion outcomes, so the supplied action 
should not throw an exception. However, if it does, the following rules apply: if this stage completed normally 
but the supplied action throws an exception, then the returned stage completes exceptionally with the supplied 
action's exception. Or, if this stage completed exceptionally and the supplied action throws an exception, then 
the returned stage completes exceptionally with this stage's exception.
```

`DelegatingCompletableFuture` does not implement this contract. In particular the `DeserializingBiConsumer` is prone to throwing `HazelcastSerializationException` which then causes downstream consumers of the future to hang because there is no completion signal.

### PR DESCRIPTION
**Pull request by vbekiaris**
and subclass `ClientDelegatingFuture` behaviour
when `HazelcastSerializationException` is thrown:

- serialization exception is now properly wrapped
in (Execution|Completion)Exception when thrown
from get, getNow or join methods.
- `whenComplete`, `handle` and `exceptionally`
can act on the HazelcastSerializationException

fixes #18053 

Backports will be prepared once this PR is reviewed and merged

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DelegatingCompletableFutureTest.test_actionsTrigger_whenAlreadyCompletedFuture:128 CountDownLatch failed to complete within 120 seconds, count left: 1
[INFO] 
[ERROR] Tests run: 35436, Failures: 1, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PartitionAssignmentsCorrectnessTest>AbstractPartitionAssignmentsCorrectnessTest.testPartitionAssignments_whenNodesStartedTerminated:48->AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually:76->AbstractPartitionAssignmentsCorrectnessTest.assertPartitionAssignmentsEventually:80->HazelcastTestSupport.assertTrueEventually:1350->HazelcastTestSupport.assertTrueEventually:1248->PartitionCorrectnessTestSupport.assertPartitionAssignments:210 On Member [127.0.0.1]:5702 - 6ea7f62a-b21a-48f0-8e93-340cef5f50aa this, Replica 1 is not found in Partition {ID: 0, Version: 1} [
	0:[127.0.0.1]:5701 - 58582161-ffca-4319-96d3-271bc83928ad
]
[INFO] 
[ERROR] Tests run: 35459, Failures: 1, Errors: 0, Skipped: 979
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/client/impl/ClientDelegatingFuture_SerializationExceptionTest.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+import com.hazelcast.internal.serialization.SerializationService;
+import com.hazelcast.internal.serialization.impl.DefaultSerializationServiceBuilder;
+import com.hazelcast.logging.ILogger;
+import com.hazelcast.spi.impl.DelegatingCompletableFuture_SerializationExceptionTest;
+import com.hazelcast.spi.impl.InternalCompletableFuture;
+import com.hazelcast.spi.impl.sequence.CallIdSequence;
+import org.junit.Before;
+
+import static org.mockito.Mockito.mock;
+
```
Comment (sancar) [inline hazelcast/src/test/java/com/hazelcast/client/impl/ClientDelegatingFuture_SerializationExceptionTest.java:33]: Don't we need test annotations ?

@RunWith(HazelcastParallelClassRunner.class)
@Category({QuickTest.class, ParallelJVMTest.class})

**Review by sancar — APPROVED** [review]
Looks good. Left single comment about missing annotations on client tests

**Review by taburet — APPROVED** [review]
Looks good.

**Comment by vbekiaris** [comment]
@sancar @taburet thanks for the reviews!
