### PR TITLE
Problem in MapEvictionPolicy.compare javadoc

### LINKED ISSUE #11074: MapEvictionPolicy.compare error in javadoc
hazelcast 3.8.4

The javadoc for MapEvictionPolicy.compare says:
> If you prefer to evict the 1st entry then return positive number, if the 2nd entry is a better candidate then return a negative number or return 0 if both entries are equally good candidates for eviction

which seems to be incorrect as the implementations (LRUEvictionPolicy and LFUEvictionPolicy) behave the opposite way i.e. return -1 if the first entry needs to be evicted and +1 if the second.

### PR DESCRIPTION
**Pull request by pveentjer**
Fix #11074

Problem in te MapEvictionPolicy.compare. Wrong order.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/map/eviction/MapEvictionPolicy.java [hunk 1]
```diff
@@ -48,8 +48,8 @@
      * {@inheritDoc}
      *
      * <p>
-     *     If you prefer to evict the 1st entry then return positive number, if the 2nd entry is a better candidate
-     * then return a negative number or return 0 if both entries are equally good candidates for eviction
+     * If you prefer to evict the 1st entry then return positive number, if the 2nd entry is a better candidate
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/map/eviction/MapEvictionPolicy.java]: `If you prefer to evict the 1st entry then return positive number` should be `If you prefer to evict the 1st entry then return a negative number`
