### PR TITLE
Increase hazelcast.wait.seconds.before.join in a test

### LINKED ISSUE #11085: MemberToMemberDiscoveryTest
**com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest**
```java
java.lang.AssertionError: Cluster size is not correct. Expected: 2 Actual: 1
	at org.junit.Assert.fail(Assert.java:88)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSize(HazelcastTestSupport.java:915)
	at com.hazelcast.test.HazelcastTestSupport$13.run(HazelcastTestSupport.java:937)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1086)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:933)
	at com.hazelcast.test.HazelcastTestSupport.assertClusterSizeEventually(HazelcastTestSupport.java:927)
	at com.hazelcast.spi.discovery.multicast.MemberToMemberDiscoveryTest.formClusterWithTwoMembersTest(MemberToMemberDiscoveryTest.java:58)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/10127/testReport/junit/com.hazelcast.spi.discovery.multicast/MemberToMemberDiscoveryTest/formClusterWithTwoMembersTest/

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #11085

The hazelcast.wait.seconds.before.join is set to 1s in our tests by default.
This is insufficient to the MulticastDiscovery strategy as the 2nd member may
start before receiving the multicast message from the 1st member.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+                try {
+                    base.evaluate();
+                } finally {
+                    if (oldValue == null) {
+                        System.clearProperty(propertyName);
+                    } else {
+                        System.setProperty(propertyName, oldValue);
+                    }
+                }
+            }
```
Comment (mesutcelik) [inline hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java]: That complexity in `evaluate` might be a sign that we should create `ClearPropertyRule` and `SetPropertyRule`

File: hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java [hunk 2]
```diff
@@ -23,21 +23,28 @@
...
+import static com.hazelcast.test.OverridePropertyRule.set;
+
 @RunWith(HazelcastSerialClassRunner.class)
 @Category(QuickTest.class)
 public class MemberToMemberDiscoveryTest extends HazelcastTestSupport {
 
     private Config config;
 
+    @Rule
+    public final OverridePropertyRule overridePropertyRule = set("hazelcast.wait.seconds.before.join", "10");
```
Comment (mesutcelik) [inline hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java]: There are other places where we can use that Rule throughout code base i.e. `hazelcast.local.localAddress` but that can be done in another PR

Comment (jerrinot) [reply hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java]: hopefully it's simpler now

File: hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+import org.junit.rules.TestRule;
+import org.junit.runner.Description;
+import org.junit.runners.model.Statement;
+
+
+/**
+ * Set or clear a property before running a test. The property will be restored once the test is finished.
+ *
+ */
+public final class OverridePropertyRule implements TestRule {
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java]: What does this Rule do what our `Hazelcast*Runners` don't do? They already store and restore all system properties. So I think I'm missing something here :)

**Comment by Donnerbart** [comment]
The issue is on milestone 3.9, this PR on 3.10. We should align this and suppress the test if it will be fixed in 3.10 :)

File: hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java (hunk 3 above)
Comment (jerrinot) [reply hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java]: I see the properties cleanup in runners as sort-of last resort. 

a test should not make assumptions about runners. it should not taint global environment and rely on someone else to clean it.

Comment (Donnerbart) [reply hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java]: I like the idea of a clean setup, but this is the only test using it, so it's more code style fragmentation. We should make a checklist for new tests and refactorings, with hints for the code parts, which are "silently" introduced over time:
* using mocked network? -> extend `HazelcastTestSupport` and its factory methods
* dealing with System properties? -> use `OverridePropertyRule`
* need to check for the root cause of a nested exception? -> use `RootCauseMatcher` with an `ExpectedException` rule
* is it a Near Cache test? -> use one of the unified abstract Near Cache test classes with a `NearCacheTestContext`
* ...

File: hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+
+
+    /**
+     * Set the property to a newValue
+     *
+     * @param propertyName system property to set
+     * @param newValue value to set
+     * @return instance of the rule
+     */
+    public static OverridePropertyRule set(String propertyName, String newValue) {
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java]: Could we have a `set(HazelcastProperty property, String newValue)` method? Then you could use it like this in the test (with a static import):
```java
@Rule
public final OverridePropertyRule overridePropertyRule = set(MAX_JOIN_SECONDS, "10");
```

Comment (jerrinot) [reply hazelcast/src/test/java/com/hazelcast/test/OverridePropertyRule.java]: I don't really like introducing a dependency on Hazelcast in this rule. you can always use 
`public final OverridePropertyRule overridePropertyRule = set(MAX_JOIN_SECONDS.getName(), "10");
 Write`
