### PR TITLE
Fix `GET_DDL` windows-specific line separator [HZ-2283]

### LINKED ISSUE #24183: com.hazelcast.jet.sql.impl.schema.GetDdlTest [HZ-2283]
_master_ (commit 1dd1657bdba1a227fe7b43777f0adf5b2f37c316)

Failed on Windows - OracleJDK8: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Windows-OracleJDK8/441/testReport/com.hazelcast.jet.sql.impl.schema/GetDdlTest/

Following tests failed with various exceptions:
- `com.hazelcast.jet.sql.impl.schema.GetDdlTest.when_queryDataLinkFromDatalinkNamespace_then_success`
- `com.hazelcast.jet.sql.impl.schema.GetDdlTest.when_queryTypeFromRelationNamespace_then_success`
- `com.hazelcast.jet.sql.impl.schema.GetDdlTest.when_queryDdlWithInput_then_success`
- `com.hazelcast.jet.sql.impl.schema.GetDdlTest.when_queryViewFromRelationNamespace_then_success`
- `com.hazelcast.jet.sql.impl.schema.GetDdlTest.when_queryMappingFromRelationNamespace_then_success`

<details><summary>Stacktrace for when_queryDataLinkFromDatalinkNamespace_then_success as an example:</summary>

```
java.lang.AssertionError: 

Expecting actual:
  [Row{[CREATE OR REPLACE DATA LINK "hazelcast"."public"."dl"
TYPE "DUMMY"
SHARED]}]
to contain exactly in any order:
  [Row{[CREATE OR REPLACE DATA LINK "hazelcast"."public"."dl"
TYPE "DUMMY"
SHARED]}]
elements not found:
  [Row{[CREATE OR REPLACE DATA LINK "hazelcast"."public"."dl"
TYPE "DUMMY"
SHARED]}]
and elements not expected:
  [Row{[CREATE OR REPLACE DATA LINK "hazelcast"."public"."dl"
TYPE "DUMMY"
SHARED]}]

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:424)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:401)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:361)
	at com.hazelcast.jet.sql.impl.schema.GetDdlTest.when_queryDataLinkFromDatalinkNamespace_then_success(GetDdlTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

```
</details>

<details><summary>Standard output for when_queryDataLinkFromDatalinkNamespace_then_success as an example:</summary>

```
21:23:53,674  INFO |when_queryDataLinkFromDatalinkNamespace_then_success| - [PartitionStateManager] when_queryDataLinkFromDatalinkNamespace_then_success - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing cluster partition table arrangement...
21:23:53,681 DEBUG || - [JobRepository] hz.GetDdlTest_jovial_newton.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
21:23:53,701 DEBUG |when_queryDataLinkFromDatalinkNamespace_then_success| - [CalciteSqlOptimizer] when_queryDataLinkFromDatalinkNamespace_then_success - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Before logical opt:
LogicalCalc(expr#0=[{inputs}], expr#1=[_UTF-16LE'datalink':VARCHAR CHARACTER SET "UTF-16LE"], expr#2=[_UTF-16LE'dl':VARCHAR CHARACTER SET "UTF-16LE"], expr#3=[GET_DDL($t1, $t2)], EXPR$0=[$t3])
  LogicalValues(tuples=[[{ 0 }]])

21:23:53,714 DEBUG |when_queryDataLinkFromDatalinkNamespace_then_success| - [CalciteSqlOptimizer] when_queryDataLinkFromDatalinkNamespace_then_success - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After logical opt:
ValuesLogicalRel(values=[{projection=[com.hazelcast.sql.impl.expression.service.GetDdlFunction@7ac4efdc], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}])

21:23:53,715 DEBUG |when_queryDataLinkFromDatalinkNamespace_then_success| - [CalciteSqlOptimizer] when_queryDataLinkFromDatalinkNamespace_then_success - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] After physical opt:
ValuesPhysicalRel(values=[{projection=[com.hazelcast.sql.impl.expression.service.GetDdlFunction@7ac4efdc], values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}]]}]}])

21:23:53,722 DEBUG |when_queryDataLinkFromDatalinkNamespace_then_success| - [LightMasterContext] when_queryDataLinkFromDatalinkNamespace_then_success - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Start executing light job 09a6-7f2e-3e40-0001, execution graph in DOT format:
digraph DAG {
	"Values" [localParallelism=1];
	"ClientSink" [localParallelism=1];
	"Values" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
21:23:53,722 DEBUG |when_queryDataLinkFromDatalinkNamespace_then_success| - [LightMasterContext] when_queryDataLinkFromDatalinkNamespace_then_success - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Building execution plan for 09a6-7f2e-3e40-0001
21:23:53,723 DEBUG || - [LightMasterContext] hz.GetDdlTest_jovial_newton.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Built execution plans for 09a6-7f2e-3e40-0001
21:23:53,723 DEBUG || - [InitExecutionOperation] hz.GetDdlTest_jovial_newton.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 09a6-7f2e-3e40-0001, execution 09a6-7f2e-3e40-0001 from [127.0.0.1]:5701
21:23:53,727 DEBUG || - [JobExecutionService] hz.GetDdlTest_jovial_newton.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=09a6-7f2e-3e40-0001, jobName='09a6-7f2e-3e40-0001', executionId=09a6-7f2e-3e40-0001 initialized, will start the execution
21:23:53,731 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Completed execution of job '09a6-7f2e-3e40-0001', execution 09a6-7f2e-3e40-0001
21:23:53,731 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-2 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution of job '09a6-7f2e-3e40-0001', execution 09a6-7f2e-3e40-0001 completed
21:23:54,002  INFO |when_queryDataLinkFromDatalinkNamespace_then_success| - [SqlTestSupport] Time-limited test - Removing 1 cached plans in SqlTestSupport.@After
21:23:54,002  INFO |when_queryDataLinkFromDatalinkNamespace_then_success| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
21:23:54,002  INFO |when_queryDataLinkFromDatalinkNamespace_then_success| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog, hz:impl:flakeIdGeneratorService/__jet.ids]
BuildInfo right after when_queryDataLinkFromDatalinkNamespace_then_success(com.hazelcast.jet.sql.impl.schema.GetDdlTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230403', buildNumber=20230403, revision=1dd1657, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_queryDataLinkFromDatalinkNamespace_then_success(com.hazelcast.jet.sql.impl.schema.GetDdlTest):'
21:23:50, accumulated pauses: 1802 ms, max pause: 683 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-Windows-OracleJDK8/441/

### PR DESCRIPTION
**Pull request by Fly-Style**
Closes #24183

### CODE REVIEW

**Comment by Fly-Style** [comment]
run-windows

**Comment by Fly-Style** [comment]
run-sql-only

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/GetDdlTest.java [hunk 1]
```diff
@@ -44,16 +45,16 @@ public void when_queryMappingFromRelationNamespace_then_success() {
...
-                        "  \"__key\" INTEGER EXTERNAL NAME \"__key\",\n" +
-                        "  \"this\" INTEGER EXTERNAL NAME \"this\"\n" +
-                        ")\n" +
-                        "TYPE \"IMap\"\n" +
-                        "OPTIONS (\n" +
-                        "  'keyFormat'='java',\n" +
-                        "  'keyJavaClass'='int',\n" +
-                        "  'valueFormat'='java',\n" +
-                        "  'valueJavaClass'='int'\n" +
+                new Row("CREATE OR REPLACE EXTERNAL MAPPING \"hazelcast\".\"public\".\"a\" EXTERNAL NAME \"a\" (" + LE +
```
Comment (k-jamroz) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/GetDdlTest.java:48]: AssertJ has `isEqualToNormalizingNewlines`. It would simplify such tests. In addition we could have `scalar(SqlResult)` helper method. Can be static or even as a default method in `SqlResult`. I created it once for convenience: https://github.com/hazelcast/hazelcast/pull/23140/files#diff-ae948b2b986ea1c9536e8266a88d84a2c31535f5eca06ff372520046b62b4df4R101

Comment (Fly-Style) [reply hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/schema/GetDdlTest.java:48]: I'd keep it as a separate issue and introduced later. I guess, just fixing test failure is enough.

**Comment by Fly-Style** [comment]
run-windows

**Comment by k-jamroz** [comment]
@ivanthescientist could you resolve conflicts and review this PR?

**Comment by k-jamroz** [comment]
run-windows

**Comment by k-jamroz** [comment]
Merging, as there are only unrelated failures in windows build.
