### PR TITLE
Fixes #5662 - InvocationNestedRemoteTest failure

### LINKED ISSUE #5662: [TEST-FAILURE] InvocationNestedRemoteTest.whenPartition_callsIncorrectPartition
```
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationNestedRemoteTest.whenPartition_callsIncorrectPartition(InvocationNestedRemoteTest.java:105)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.7/com.hazelcast$hazelcast/166/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/InvocationNestedRemoteTest/whenPartition_callsIncorrectPartition/

### PR DESCRIPTION
**Pull request by tombujok**
Fix for #5662 - InvocationNestedRemoteTest failure

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java [hunk 1]
```diff
@@ -8,115 +8,120 @@
...
-        HazelcastInstance hz = createHazelcastInstance();
-        OperationService operationService = getOperationService(hz);
+    public void invokeOnPartition_outerGeneric_innerGeneric_forbidden() {
+        HazelcastInstance local = createHazelcastInstance();
+        OperationService operationService = getOperationService(local);
+
+        InnerOperation innerOperation = new InnerOperation(RESPONSE, GENERIC_OPERATION);
+        OuterOperation outerOperation = new OuterOperation(innerOperation, GENERIC_OPERATION);
+
+        expected.expect(Exception.class);
```
Comment (bilalyasar) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: just friendly advice :)
in general, in hazelcast we use (expected = SomeExceptionClassName) pattern.
You can see an example here: https://github.com/hazelcast/hazelcast/blob/08857da91e497365437700243db026fda4c5c31a/hazelcast/src/test/java/com/hazelcast/config/QueryCacheConfigTest.java#L15

Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: Thx. I know this one - but it's not specific enough IMHO in many cases. 
You don't really know which line threw the exception. 
It's also impossible to match what the message was which is useful in some cases, where the same type of exception may be thrown twice from the same method, like it's matched here:
https://github.com/hazelcast/hazelcast/pull/6240/files#diff-efd38b559d7c6a3cc584ef18e630e672R79

There are cases where notation proposed by you is OK, but I don't see a reason why we should be dogmatic about it ;)

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java [hunk 2]
```diff
@@ -248,18 +248,25 @@ public boolean isInvocationAllowedFromCurrentThread(Operation op, boolean isAsyn
...
+        // if already running an operation for a partition (id >= 0) it means that it's a nested invocation
+        // in this case partitionId of both nested operations has to match
         PartitionOperationThread partitionThread = (PartitionOperationThread) currentThread;
+        OperationRunner runner = partitionThread.getCurrentOperationRunner();
+        if (runner != null) {
+            return runner.getPartitionId() == op.getPartitionId();
+        }
+
+        // TODO: this is racy... what if the partition is being migrated at the same time?
         return toPartitionThreadIndex(op.getPartitionId()) == partitionThread.threadId;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: being local or not is currently not the question.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java [hunk 3]
```diff
@@ -248,18 +248,25 @@ public boolean isInvocationAllowedFromCurrentThread(Operation op, boolean isAsyn
...
         }
 
-        // we are only allowed to invoke from a PartitionOperationThread if the operation belongs to that
-        // PartitionOperationThread.
+        // if already running an operation for a partition (id >= 0) it means that it's a nested invocation
+        // in this case partitionId of both nested operations has to match
         PartitionOperationThread partitionThread = (PartitionOperationThread) currentThread;
+        OperationRunner runner = partitionThread.getCurrentOperationRunner();
+        if (runner != null) {
+            return runner.getPartitionId() == op.getPartitionId();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: Can you add a line of comment explaining that a nested call is happening here.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: Can you add a line of comment that this is the first call (so not nested).

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: Do you suggest removing the TODO?

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java (hunk 3 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: There's one just above the line you quoted
```
// if already running an operation for a partition (id >= 0) it means that it's a nested invocation
// in this case partitionId of both nested operations has to match
```
Would like to have another comment here?

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java [hunk 4]
```diff
@@ -36,91 +36,52 @@ public void setup() {
...
-    // ================= isDone ==========================================
-
     @Test
     public void isDone_whenNullResponse() throws ExecutionException, InterruptedException {
         DummyOperation op = new DummyOperation(null);
 
         InternalCompletableFuture future = operationService.invokeOnTarget(null, op, getAddress(local));
-        // first we wait for the future to complete.
-        future.get();
+        future.get(); // first we wait for the future to complete.
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Checkstyle doesn't like trailing comments; so we don't do them in our regular code. Personally I have no problem with it; perhaps we should make checkstyle lenient towards trailing comments.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java [hunk 5]
```diff
@@ -36,91 +36,52 @@ public void setup() {
...
-                // we need to set the call-id to prevent running the operation on the calling-thread.
-                setPartitionId(1);
-            }
-
-            @Override
-            public void run() throws Exception {
-                Thread.sleep(5000);
-            }
-        };
+        DummyOperation op = new DummySleepingNullReturningOperation();
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Now it becomes a bit more difficult to understand the operation. From the name it isn't clear that it is a partition specific operation.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 4 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: It's a test - so no checkstyle.
In a test I personally prefer this notation to make the test smaller in terms of LOC.
I have no problems in moving it up again.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java [hunk 6]
```diff
@@ -129,22 +90,19 @@ public void isDone_whenObjectResponse() {
...
     }
 
-    // ========================= andThen ==================================
-
     // There is a bug: https://github.com/hazelcast/hazelcast/issues/5001
     @Test
     public void andThen_whenNullResponse_thenCallbackExecuted() throws ExecutionException, InterruptedException {
         DummyOperation op = new DummyOperation(null);
-
+        final ExecutionCallback callback = mock(ExecutionCallback.class);
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Does this field need to be final?

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java (hunk 1 above)
Comment (bilalyasar) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: yes you are right, it is not obligation as you said :+1:

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 5 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: For me the test is much more unreadable with the inner class. I have to analyse its code reading every single unit-test.
What name do you suggest?

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 6 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Unfortunately yes since it's used in the inner class. 
If we used some proxying mechanism that e.g. Awaitility provides we could remove most of the inner classes from our tests...

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java [hunk 7]
```diff
@@ -8,115 +8,120 @@
...
+        OuterOperation outerOperation = new OuterOperation(innerOperation, outerPartitionId);
         InternalCompletableFuture f = operationService.invokeOnPartition(null, outerOperation, outerOperation.getPartitionId());
 
-        try {
-            f.getSafely();
-            fail();
-        } catch (IllegalThreadStateException e) {
-        }
+        expected.expect(IllegalThreadStateException.class);
+        expected.expectMessage("cannot make remote call");
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: I would not test for the message.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java [hunk 8]
```diff
@@ -8,115 +8,120 @@
...
+        f.getSafely();
     }
 
     @Test
-    public void whenPartition_callsDifferentPartition_butMappedToSameThread() throws ExecutionException, InterruptedException {
+    public void invokeOnPartition_outerLocal_innerSameInstance_callsDifferentPartition_mappedToSameThread() throws ExecutionException, InterruptedException {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: Maybe it is an idea to split up this test into 2 files: one testing partition specific outer call.. and the other testing non partition specific outer call. Otherwise you get such long names.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: I think we should. We should also update the documentation to clearly explain what this method is doing.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java (hunk 3 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: Only when you have received the runner, you know you are in a nested call.  

So this conclusion:
```
 // if already running an operation for a partition (id >= 0) it means that it's a nested invocation
        // in this case partitionId of both nested operations has to match
```

I'm not following.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java (hunk 7 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: I know there are various opinions about it - I wouldn't like to have another dogmatic discussion about it and would prefer to stay pragmatic.
We don't have any error codes, thus it's difficult to assert precisely what you want to assert. 
Checking exception type only is in many cases very imprecise, you can also get:
`cannot make invocation on multiple partitions`
`cannot be run in current thread`

I prefer to be sure what I'm asserting and where the exception is thrown - otherwise the test may not be testing what you are willing to test. I've seen many of them already...

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 4 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Perhaps we should update checkstyle. I have little problems with a trailing comment. Can you suggest it on the dev channel?

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java (hunk 8 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: There's already `InvocationNestedLocalTest` and `InvocationNestedRemoteTest`
Wouldn't like to split a test to two files because of a name that's descriptive and tells me everything about it. The name can be shorter actually since `callsDifferentPartition` is redundant.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 5 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: For me it isn't clear because this DummySleepingNullReturningOperation doesn't explain the intent to me.

Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Let me have a look at the whole source. Judging changes based on fragements sucks.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 4 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Actually I'll remove the comment since it's obvious that the future has completed when get returns.
Feel free to discuss on dev channel whether we should have checkstyle in tests.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java (hunk 2 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: Done

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java (hunk 3 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/classic/ClassicOperationExecutor.java]: Done. Thx

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 5 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: The main purpose of the DummySleeping one is to not be bother with the actual result of the operation. I need to have an invocation and this is the way how to get one. 

So perhaps name it to GetLostOperation :) Something that clearly explains the intent that we don't want to be bother with the actual operation.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 6 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Sure.. Again.. judging code based on fragments sucks

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java (hunk 1 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: Thx!

Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationNestedLocalTest.java]: I think this is a relatively new unit feature. I recently discovered it while reading 

https://pragprog.com/book/utj2/pragmatic-unit-testing-in-java-8-with-junit

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 5 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: I love the GetLostOperation :)
How about `DummyPartitionOperation`? or `TestPartitionOperation`?

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 6 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Oki doki

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 5 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: The problem with DummyPartitionOperation/TestPartitionOperation names is that they all give the impression that they matter. In our case, the GetLostOperation is meant to create an invocation and to shoot it so much into the future that it won't bother the actual test. So I don't care about its results.. I just want to get access to an Invocation instance I can test.

Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: OK, so I'll change it to `GetLostPartitionOperation` since you asked once if it's partition operation or not.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java [hunk 9]
```diff
@@ -154,4 +112,17 @@ public void run() throws Exception {
             }
         });
     }
+
+    private static class GetLostPartitionOperation extends DummyOperation {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Can you add a few lines of comment explaining the intend of this operation?

**Comment by metanet** [comment]
:+1:

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java (hunk 9 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFutureTest.java]: Done

**Comment by tombujok** [comment]
We've got two thumbs-up already. 
@pveentjer Are you also ok with it? I'm asking since you deliver significant input here.
