### PR TITLE
TestFix: RepartitioningStressTest waits for the RestartThread on exit

### LINKED ISSUE #9575: OperationServiceImpl Failures
**whenNonExistingTarget**
```
com.hazelcast.core.HazelcastException: com.hazelcast.core.MemberLeftException: Member [127.0.0.1]:6553 - 2caec777-71dd-49c4-ab05-8f20be223b81 has left cluster!
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$OnMemberLeftTask.run0(InvocationMonitor.java:346)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationMonitor$MonitorTask.run(InvocationMonitor.java:229)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.join(AbstractInvocationFuture.java:136)
	at com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnTargetTest.whenNonExistingTarget(OperationServiceImpl_invokeOnTargetTest.java:76)
```
https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1190/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_invokeOnTargetTest/whenNonExistingTarget/

**invokeOnTargetTest.com.hazelcast.spi.impl.operationservice.impl.OperationServiceImpl_invokeOnTargetTest**
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_2016_uzhpczcwum', node=[127.0.0.1]:6819}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$1.evaluate(AbstractHazelcastClassRunner.java:254)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:78)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:54)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/1189/testReport/junit/com.hazelcast.spi.impl.operationservice.impl/OperationServiceImpl_invokeOnTargetTest/com_hazelcast_spi_impl_operationservice_impl_OperationServiceImpl_invokeOnTargetTest/

### PR DESCRIPTION
**Pull request by jerrinot**
Otherwise there is a race between test finish and Hazelcast.shutdownAll();
It could happened that  Hazelcast.shutdownAll(); is executed in the tearDown(()
and then the RestartThread creates another instance.

Fixes #9575

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/RepartitioningStressTest.java [hunk 1]
```diff
@@ -78,10 +80,15 @@ public void setUp() {
...
             queue.add(createHazelcastInstance());
         }
+
+        restartThread = new RestartThread();
     }
 
     @After
-    public void tearDown() {
+    public void tearDown() throws InterruptedException {
+        if (restartThread.isAlive()) {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationservice/impl/RepartitioningStressTest.java]: Is the guard needed for stopAndJoin?
