### PR TITLE
Fix infinite waiting on ICondition when waiting deadline is in the past

### LINKED ISSUE #4372: [TEST-FIX] ConditionTest.testAwaitUntil_whenFail
```
java.lang.Exception: test timed out after 60000 milliseconds
	at java.lang.Object.wait(Native Method)
	at com.hazelcast.spi.impl.BasicInvocationFuture.pollResponse(BasicInvocationFuture.java:265)
	at com.hazelcast.spi.impl.BasicInvocationFuture.waitForResponse(BasicInvocationFuture.java:216)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:193)
	at com.hazelcast.spi.impl.BasicInvocationFuture.get(BasicInvocationFuture.java:173)
	at com.hazelcast.concurrent.lock.ConditionImpl.doAwait(ConditionImpl.java:89)
	at com.hazelcast.concurrent.lock.ConditionImpl.await(ConditionImpl.java:80)
	at com.hazelcast.concurrent.lock.ConditionImpl.awaitUntil(ConditionImpl.java:110)
	at com.hazelcast.concurrent.lock.ConditionTest.testAwaitUntil_whenFail(ConditionTest.java:539)
```
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/418/testReport/junit/com.hazelcast.concurrent.lock/ConditionTest/testAwaitUntil_whenFail/

### PR DESCRIPTION
**Pull request by jerrinot**
See [commit message](https://github.com/hazelcast/hazelcast/commit/768b06e52b35f4e20f04434b8154389877bc9713) for details.

There are also 2 additional changes:
- Client lock proxy fails fast on `newCondition()` when name is `null`. This makes it consistent with member proxy impl. This behaviour is specified in `ILock` contract since at least Hazelcast 3.2, but it wasn't enforced on a client-side. See https://github.com/jerrinot/hazelcast/commit/57941a237ea4f3701089ee96c8a8ba9405511152#diff-05672139fa6d01518bb60ac3ffc60a4fR97

- Re-use `ConditionAbstractTest` on a client side. 

Fixes #4372

### CODE REVIEW

**Comment by tombujok** [comment]
👍 once green

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientConditionProxy.java [hunk 1]
```diff
@@ -91,8 +91,11 @@ private boolean doAwait(long time, TimeUnit unit, long threadId) throws Interrup
     @Override
     public boolean awaitUntil(Date deadline) throws InterruptedException {
         long until = deadline.getTime();
-        final long timeToDeadline = until - Clock.currentTimeMillis();
-        return await(timeToDeadline, TimeUnit.MILLISECONDS);
+        final long durationMs = until - Clock.currentTimeMillis();
+        if (durationMs <= 0) {
```
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientConditionProxy.java]: What about the other methods taking "long time" as a parameter (e.g. public boolean await(long time, TimeUnit unit))? Is it better to do this check at the method taking long time as a parameter?

File: hazelcast-client/src/test/java/com/hazelcast/client/lock/LegacyClientConditionTest.java [hunk 2]
```diff
@@ -0,0 +1,189 @@
...
+import java.util.concurrent.CountDownLatch;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicInteger;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertTrue;
+
+@RunWith(HazelcastParallelClassRunner.class)
+@Category({QuickTest.class, ParallelTest.class})
+public class LegacyClientConditionTest extends HazelcastTestSupport {
```
Comment (ihsandemir) [inline hazelcast-client/src/test/java/com/hazelcast/client/lock/LegacyClientConditionTest.java]: Is there a specific reason for making the test name start with "Legacy"?

Comment (jerrinot) [inline hazelcast-client/src/test/java/com/hazelcast/client/lock/LegacyClientConditionTest.java]: I just renamed the original `ClientConditionTest`, because I wanted to use the name for the test inheriting from `ConditionAbstractTest`. 

In theory `LegacyClientConditionTest` could be removed as it appears all(?) cases are already covered by `ConditionAbstractTest`. However it feels funny to remove tests - there is always a risk there is case not covered in the `ConditionAbstractTest` <- maybe some subtle difference.

File: hazelcast-client/src/test/java/com/hazelcast/client/lock/ClientConditionTest.java [hunk 3]
```diff
@@ -1,189 +1,31 @@
...
-import java.util.concurrent.TimeUnit;
-import java.util.concurrent.atomic.AtomicInteger;
-
-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertTrue;
-
 @RunWith(HazelcastParallelClassRunner.class)
 @Category({QuickTest.class, ParallelTest.class})
-public class ClientConditionTest extends HazelcastTestSupport {
+public class ClientConditionTest extends ConditionAbstractTest {
```
Comment (jerrinot) [inline hazelcast-client/src/test/java/com/hazelcast/client/lock/ClientConditionTest.java]: this tests now re-uses all tests implemented in `ConditionAbstractTest`

**Comment by asimarslan** [comment]
👍 
Client behavior fixes are quite well documented in API doc.

**Comment by ihsandemir** [comment]
👍

**Comment by jerrinot** [comment]
@tombujok, @asimarslan, @ihsandemir: thanks for a quick review!
