### PR TITLE
Fix fired events when initialMembersipListener is used on client

### LINKED ISSUE #7430: Callback order and content of InitialMembershipEvent
For clients, `InitialMembershipListener.init` is called _after_ all `MembershipListener.memberAdded`, which contradicts the docs: 
> The InitializingMembershipListener is a `MembershipListener` that first receives a `InitialMembershipEvent` when it is registered so it immediately knows which members are available. After that event has been received, it will receive the normal MembershipEvents

For members, `InitialMembershipListener.init` is called immediately, but `getMembers` only contains itself, which also seems to contradict the intent described in the docs.

### PR DESCRIPTION
**Pull request by sancar**
When initial membership event added before client is started,
it was firing individual ADDED events for current memberlist,
along with InitialMembershipEvent. Only latter is preserved,
other events are removed.

Related tests are added.
Membershiplistener related tests in ClientRegressionWithMockNetworkTest
are moved to MembershipListenerTest.

fixes #7430

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/MembershipListenerTest.java [hunk 1]
```diff
@@ -124,20 +163,83 @@ public void addNullListener_thenException() throws Exception {
         return result;
     }
 
+    /**
+     * related to issue #1181
+     */
+    @Test
+    public void testAddInitialMembership_whenListenerAddedViaClientConfig() throws InterruptedException {
```
Comment (ihsandemir) [inline hazelcast-client/src/test/java/com/hazelcast/client/MembershipListenerTest.java]: why is there no assert? What is being tested?

Comment (sancar) [inline hazelcast-client/src/test/java/com/hazelcast/client/MembershipListenerTest.java]: Before the fix, It was throwing NullPointer exception according to issue mentioned in #1181 . It is testing that it does not throw any exception.

**Comment by sancar** [comment]
clientRelated

**Comment by sancar** [comment]
clientRelated

**Comment by ihsandemir** [comment]
:+1:

**Comment by asimarslan** [comment]
:+1:
