### PR TITLE
Ensure the ordering between transaction prepare and rollback operations

### LINKED ISSUE #6383: AdvancedClusterStateTest failures
**changeClusterState_shouldFail_whenInitiatorDies_beforePrepare**
**changeClusterState_shouldFail_withoutBackup_whenInitiatorDies_afterPrepare**
**changeClusterState_shouldFail_withoutBackup_whenInitiatorDies_beforePrepare**

```
com.hazelcast.transaction.TransactionException: Transaction is timed-out!
    at com.hazelcast.transaction.impl.TransactionImpl.checkTimeout(TransactionImpl.java:287)
    at com.hazelcast.transaction.impl.TransactionImpl.prepare(TransactionImpl.java:211)
    at com.hazelcast.cluster.AdvancedClusterStateTest$DelegatingTransaction.prepare(AdvancedClusterStateTest.java:584)
    at com.hazelcast.cluster.AdvancedClusterStateTest$TransactionAnswer$1.prepare(AdvancedClusterStateTest.java:505)
    at com.hazelcast.cluster.impl.ClusterStateManager.changeClusterState(ClusterStateManager.java:210)
    at com.hazelcast.cluster.impl.ClusterServiceImpl.changeClusterState(ClusterServiceImpl.java:794)
    at com.hazelcast.cluster.AdvancedClusterStateTest.changeClusterState_shouldFail_whenInitiatorDies_beforePrepare(AdvancedClusterStateTest.java:160)
```

**invocationShouldComplete_whenMemberReJoins_inFrozenState**
**partitionTable_shouldBeFrozen_whenMemberLeaves_inFrozenState**

```
ava.lang.IllegalStateException: Still have pending migration/replication tasks, cannot lock cluster state! New state: FROZEN, current state: ACTIVE
    at com.hazelcast.cluster.impl.ClusterStateManager.lockClusterState(ClusterStateManager.java:124)
    at com.hazelcast.cluster.impl.operations.LockClusterStateOperation.run(LockClusterStateOperation.java:68)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OracleJDK1.6/685/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK7/681/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/684/

### PR DESCRIPTION
**Pull request by metanet**
Transaction prepare step sends prepare operations simultaneously and triggers rollback on first failure. Since other nodes may not receive the prepare operation yet, it is possible that a rollback operation hits a node before prepare. We must ensure that a rollback operation happens after the prepare operation.

Fixes #6383

Pair-investigated with @mdogan

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/util/FutureUtil.java [hunk 1]
```diff
@@ -246,6 +264,19 @@ public static void waitWithDeadline(Collection<Future> futures, long timeout, Ti
     }
 
     @PrivateApi
+    public static void waitUntilAllRespondedWithDeadline(Collection<Future> futures, long timeout, TimeUnit timeUnit,
+                                                         ExceptionHandler exceptionHandler) {
+        CollectAllExceptionHandler collector = new CollectAllExceptionHandler(futures.size());
+        waitWithDeadline(futures, timeout, timeUnit, collector);
+        final List<Throwable> throwables = collector.getThrowables();
+        synchronized (throwables) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/util/FutureUtil.java]: Why is there a sync block on throwables?

Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/util/FutureUtil.java]: Ok. Learned something new. Apparently it is part of the synchronizedList to give a guarantee on the underlying lock being used. Ans synchronized(list) is a recommended approach.

Comment (metanet) [inline hazelcast/src/main/java/com/hazelcast/util/FutureUtil.java]: Yep. Synchronized list doesnt provide thread safety guarantee for iteration

Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/util/FutureUtil.java]: @metanet: can you add a short comment over sync block explaining its reason? You can even add it via direct push after merge. It seems people can be confused here.

**Comment by mdogan** [comment]
:+1:

**Comment by metanet** [comment]
Sure, i will do it after merge

**Comment by gurbuzali** [comment]
👍
