### PR TITLE
Tenant control moved to TenantControlService, fix cache replication with unavailable applications / classes

### LINKED ISSUE #10875: [cache] Need a way to remove all user classes from cache configuration for existing cache
This is all related to #8972 and PR #10874 #14633 and https://github.com/hazelcast/hazelcast/pull/13702

What happens is when a Payara application gets redeployed, all of it's classes are changed, so when accessing JCache, you get ClassCast exceptions.
On the other hand, if you remove the cache completely, another clustered instance of the application will get all sorts of weird errors such as:
```
com.hazelcast.cache.CacheNotExistsException: Cache /hz/comments is already destroyed or not created yet, on Member [10.0.1.7]:5900 - 21d05a8c-1cb8-4fd2-a258-5fb7c15a1fe0 this
	at com.hazelcast.cache.impl.AbstractCacheRecordStore.<init>(AbstractCacheRecordStore.java:116)
	at com.hazelcast.cache.impl.CacheRecordStore.<init>(CacheRecordStore.java:69)
	at com.hazelcast.cache.impl.CacheService.createNewRecordStore(CacheService.java:68)
	at com.hazelcast.cache.impl.CachePartitionSegment.createNew(CachePartitionSegment.java:51)
	at com.hazelcast.cache.impl.CachePartitionSegment.createNew(CachePartitionSegment.java:37)
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:73)
	at com.hazelcast.cache.impl.CachePartitionSegment.getOrCreateRecordStore(CachePartitionSegment.java:67)
	at com.hazelcast.cache.impl.AbstractCacheService.getOrCreateRecordStore(AbstractCacheService.java:282)
	at com.hazelcast.cache.impl.operation.AbstractCacheOperation.beforeRun(AbstractCacheOperation.java:80)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:188)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:409)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:115)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100)
```
I believe the best solution to this is to have a way to remove the configuration and cache from the local node only, but leaving the cache alone in all the other instances.  If the local instance is the only instance, the cache should be removed, but the removal wouldn't be replicated to other instances.
If the other instance modifies the cache while it's absent on the local node,
it could be replicated but not deserialized in any way, because the classes would not be loaded at that point and ClassNotFound exception will result:

```
Warning:   StandardWrapperValve[bg.jug.guestbook.admin.RestApplication]: Servlet.service() for servlet bg.jug.guestbook.admin.RestApplication threw exception
java.lang.ClassCastException: Incompatible cache value types specified, expected class bg.jug.guestbook.entities.User but class bg.jug.guestbook.entities.User was specified
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:195)
	at com.hazelcast.cache.impl.AbstractHazelcastCacheManager.getCache(AbstractHazelcastCacheManager.java:68)
	at bg.jug.guestbook.users.UserCacheProducer.getUsersCache(UserCacheProducer.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.producer.ProducerMethodProducer.produce(ProducerMethodProducer.java:103)
	at org.jboss.weld.injection.producer.AbstractMemberProducer.produce(AbstractMemberProducer.java:161)
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:180)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)
	at org.jboss.weldx.cache.AutoCloseable$Cache$Closeable$Iterable$1431046378$Proxy$_$$_WeldClientProxy.get(Unknown Source)
	at bg.jug.guestbook.users.JCacheUserManager.getUser(JCacheUserManager.java:23)
	at bg.jug.guestbook.users.JCacheUserManager$Proxy$_$$_WeldClientProxy.getUser(Unknown Source)
	at bg.jug.guestbook.users.LoginController.login(LoginController.java:37)
	at bg.jug.guestbook.users.LoginController$Proxy$_$$_WeldClientProxy.login(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1622)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:258)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:654)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:593)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:483)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:180)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:242)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:539)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by lprimak**
Fixes #10875

Old PR (for 3.12) #17129

### CODE REVIEW

**Comment by lprimak** [comment]
Works correctly on most cases, some things are not tested yet and some things yet to do below:

To test:
- Near cache
- Different InMemory object modes (OBJECT)
- Maps / Entry processors on different nodes, including nodes without application code deployed

TO be implemented:
- Migrations with unavailable tenants / applications

**Comment by lprimak** [comment]
@mmedenjak @vbekiaris this is the 4.x master PR

**Comment by lprimak** [comment]
Payara tenant classes, as a usage example: https://github.com/payara/Payara/pull/4762

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+
+    /**
+     *
+     * @return underlying object, initialize within Tenant Control when necessary
+     */
+    public T get() {
+        boolean localInitialized = this.initialized;
+        if (!localInitialized) {
+            try {
+                lock.lock();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:53]: Calling allien code while holding a lock is a source or problems.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+import java.util.concurrent.locks.ReentrantLock;
+import java.util.function.Supplier;
+
+/**
+ * Represents a value that requires tenant control context to be accessed
+ *
+ * @author lprimak
+ * @param <T> object type
+ */
+public class TenantContextual<T> {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:31]: Every problem in computer science can be added by adding an extra layer of indirection; apart from having too many layers of indirection. I have the feeling that we are adding an unwanted layer of indirection here.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:53]: A lock always needs to be acquired outside the try block.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 3]
```diff
@@ -33,8 +31,7 @@
  * @author lprimak
  */
 @Beta
-public interface TenantControl extends Serializable {
-
+public interface TenantControl extends DataSerializable {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:34]: This will break any implementation of TenantControl. In theory it is allowed because it is @Beta, but something that needs to be considered since there is already a release with this interface.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/DestroyEventContext.java [hunk 4]
```diff
@@ -16,27 +16,21 @@
...
+import com.hazelcast.core.HazelcastInstance;
 import com.hazelcast.spi.annotation.Beta;
 
 /**
  * Hook to decouple Hazelcast object from the tenant
- * @param <T> context type
  */
 @Beta
-public interface DestroyEventContext<T> {
+public interface DestroyEventContext {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/DestroyEventContext.java:26]: Breaking beta interface..

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:53]: I don't believe any alien code is called from here. This class is really private API (perhaps I should annotate it as such) but the way it's used only "non-alien" code is used here

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 2 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:31]: I am not sure what is the alternative here is, do you have a suggestion?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:53]: good comment. done.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 3 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:34]: TenantControl was created by me for Payara. I doubt very much it'll break anyone else. Besides, many, many things were changed in more of an incompatible way from Hazelcast 3.x to 4.x

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/DestroyEventContext.java (hunk 4 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/DestroyEventContext.java:26]: Same comment as above

**Comment by lprimak** [comment]
@pveentjer thank you for the review. Looks like most of things you don't like is TenantContextual. Perhaps you are right, but for now, I don't see the alternative. Can you suggest one to me?

**Comment by lprimak** [comment]
I am working on delaying migration until the tenant becomes available right now, perhaps most of the things that are in this PR right now no longer be necessary when it's complete... will see

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (pveentjer) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java]: Alien code -> Code that isn't owned by this class.  The problem with any interface injected into this class and called whole holding a lock, it is very easy to run into severe problems (contention, deadlocks etc). And perhaps it is fine now, but I have seen on quite a few occasions that eventually you end up with some nasty locking problem.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 3 above)
Comment (pveentjer) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:34]: Hazelcast 4.0 is a major release and hence allowed to break API.

**Comment by pveentjer** [comment]
My primary issue with this PR is not the above code comments. But that we add a feature to one of our API's because of one particular use-case. It makes a lot of sense for that particular use-case, but it adds to the complexity of the system. So code and feature complexity, but also unexpected asymmetric behavior. E.g. the JCache has this feature, but the IMap has not. 

IMHO this should be done on a system wide level, or it should not be done at all.

**Comment by lprimak** [comment]
@pveentjer You are correct. The overall goal is to introduce tenant control to any client code that's run from Hazelcast Operation thread.
Obviously that includes Maps, and other objects that let users run code out of Hazelcast threads.

In fact, all the issues arose because of these calls have no context and need to be set, leading to all sorts of issues when using Hazelcast integration with Payara (or any other app server)

This issue is indeed complex, but I believe it needs to be solved because
I see more and more people using Payara with Hazelcast and reporting these kinds of issues.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 3 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:34]: Generally since it's beta and since it's a rather obscure feature, I'm ok with changing it in a minor release.

**Comment by pveentjer** [comment]
Would it not make sense to integrate it deeper into the system so that it applies to all data-structures and not only to JCache. Example:

```
 @Override
    public void run(Operation op) {
        executedOperationsCounter.inc();

        boolean publishCurrentTask = publishCurrentTask();

        if (publishCurrentTask) {
            currentTask = op;
        }

        try {
            checkNodeState(op);

            if (timeout(op)) {
                return;
            }

            ensureNoPartitionProblems(op);

            ensureNoSplitBrain(op);

            ensureTenantControl(op); <----

            op.beforeRun();

            call(op);
        } catch (Throwable e) {
            handleOperationError(op, e);
        } finally {
            if (publishCurrentTask) {
                currentTask = null;
            }
        }
    }
```

This tenant functionality seems something that should not be ad hoc integrated in a specific data-structure but is more of a general infrastructure level concern.

**Comment by lprimak** [comment]
@pveentjer I agree with you.
The use case came up in JCache because it's an API that's supported by Payara and backed by Hazelcast, so as soon as people started using JCache, things started failing.

Using Hazelcast data structures is not "Java EE compliant" and therefore was not a "first priority" at first. However, I agree that this should be implemented on global level, and is my next step.

**Comment by lprimak** [comment]
I have started work to migrate tenant control into Operations.
The issue I am facing is that any Hazelcast object (maps, queues, cache, etc.) needs tenant control in configuration. Not ```Config``` classes but 'internal' configuration to keep state. What do you think is the best for this?
Is it DistributedObject? Proxy? Something else?
Thanks!

**Comment by lprimak** [comment]
preliminary work done with putting TenantControl into DistributedObject and proxy

**Comment by lprimak** [comment]
All tenant control code is now in Operations and moved out of the cache.
I am now looking for other threaded executions that need tenant control added.
One is the topic listener service

**Comment by lprimak** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/DistributedObjectEventPacket.java [hunk 5]
```diff
@@ -60,12 +64,17 @@ public UUID getSource() {
...
+        return tenantControl;
+    }
+
     @Override
     public void writeData(ObjectDataOutput out) throws IOException {
         out.writeBoolean(eventType == EventType.CREATED);
         out.writeUTF(serviceName);
         out.writeUTF(name);
         UUIDSerializationUtil.writeUUID(out, source);
+        out.writeObject(tenantControl);
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/DistributedObjectEventPacket.java:77]: rolling upgrades: make this class implement `Versioned` and guard for cluster version being greater or equal than current one

(also in `readData` below)

**Comment by lprimak** [comment]
@vbekiaris thanks for your review! I'll get on it shortly

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 6]
```diff
@@ -43,18 +42,18 @@
...
-    Closeable setTenant(boolean createRequestScope);
+    Closeable setTenant();
+
+    /**
+     * To be called when Hazelcast object is created
+     * @param destroyEventContext hook to decouple any Hazelcast object when the tenant is destroyed,
+     * This is used, for example, to delete all associated caches from the application when
+     * it gets undeployed, so there are no ClassCastExceptions afterwards
+     */
+    void objectCreated(Optional<DestroyEventContext> destroyEventContext);
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:56]: As far as `Optional`, I like it but I really don't care either way. So if you want me to do `@Nullable` I will

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java [hunk 7]
```diff
@@ -132,20 +132,27 @@ public final void executeRun() {
 
     private void process(Object task) {
         try {
+            SwCounter counter;
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: You are right that it conflates the return value. However your proposal will lead to a lot of code duplication and opportunity for errors. I think my solution is elegant, even though a bit confusing. I wish we had tuples :) however they do bring some issues as well

[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: I will put in a comment to un-confuse

**Comment by lprimak** [comment]
@vbekiaris posted updates

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: However, if you look at the implementation, the ```orElse``` thing works really well and really descriptive on optionals. I suppose another ```if()``` statement will work just as well however I think this looks eligant

[the remark this answers is not in the document]
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: I still think `Optional` will pollute the caller side. See also Brian Goetz's https://stackoverflow.com/questions/26327957/should-java-8-getters-return-optional-type/26328555#26328555 : "You should almost never use it as a field of something or a method parameter."

**Comment by lprimak** [comment]
@vbekiaris removed Optionals

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: done

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java [hunk 8]
```diff
@@ -194,9 +197,11 @@ public DistributedObjectFuture getOrCreateProxyFuture(String name, UUID source,
      * @param local        {@code true} if the proxy should be only created on the local member,
      *                     otherwise fires {@code DistributedObjectEvent} to trigger cluster-wide
      *                     proxy creation.
+     * @param tenantControl optional, if it was transferred via PostOp
      * @return The DistributedObject instance if it is created by this method, null otherwise.
      */
-    public DistributedObjectFuture createProxy(String name, UUID source, boolean initialize, boolean local) {
+    public DistributedObjectFuture createProxy(String name, UUID source, boolean initialize, boolean local,
+            Optional<TenantControl> tenantControl) {
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java]: done

**Comment by emre-aydin** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 9]
```diff
@@ -43,18 +41,19 @@
...
      */
-    Closeable setTenant(boolean createRequestScope);
+    Closeable setTenant();
+
+    /**
+     * To be called when Hazelcast object is created
+     * @param destroyEventContext hook to decouple any Hazelcast object when the tenant is destroyed,
+     * This is used, for example, to delete all associated caches from the application when
+     * it gets undeployed, so there are no ClassCastExceptions afterwards
+     * cannot be null. This is a functional interface, no-op lambda can be used
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:54]: fixed

File: hazelcast/src/main/java/com/hazelcast/internal/nio/ClassLoaderUtil.java [hunk 10]
```diff
@@ -39,6 +39,13 @@
  */
 @SuppressWarnings({"checkstyle:magicnumber", "checkstyle:npathcomplexity"})
 public final class ClassLoaderUtil {
+    /**
+     * Marker interface.
+     * do not cache constructors if an instance of this interface,
+     * Used by systems with complicated class loader schemes
+     * that may interfere with caching
+     */
+    public interface BypassClassCaching { };
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/internal/nio/ClassLoaderUtil.java:48]: Yes, this is correct. I added this because Hazelcast's class caching was causing issues in Payara's class loading.
I will move it into SPI

File: hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java [hunk 11]
```diff
@@ -64,6 +62,7 @@
     private final List<CacheConfig> configs = new ArrayList<CacheConfig>();
     private final Map<String, Map<Data, CacheRecord>> data = new HashMap<String, Map<Data, CacheRecord>>();
     private CacheNearCacheStateHolder nearCacheStateHolder;
+    private boolean classesAlwaysAvailable = true;
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java:65]: fixed

File: hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java [hunk 12]
```diff
@@ -157,7 +146,11 @@ protected void writeInternal(ObjectDataOutput out)
         int confSize = configs.size();
         out.writeInt(confSize);
         for (CacheConfig config : configs) {
-            out.writeObject(config);
+            if (!classesAlwaysAvailable) {
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/operation/CacheReplicationOperation.java:149]: fixed

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheDataSerializerHook.java [hunk 13]
```diff
@@ -236,7 +234,6 @@ public DataSerializableFactory createFactory() {
         constructors[SET_EXPIRY_POLICY] = arg -> new CacheSetExpiryPolicyOperation();
         constructors[SET_EXPIRY_POLICY_BACKUP] = arg -> new CacheSetExpiryPolicyBackupOperation();
         constructors[EXPIRE_BATCH_BACKUP] = arg -> new CacheExpireBatchBackupOperation();
-        constructors[CACHE_DESTROY_EVENT_CONTEXT] = arg -> new CacheDestroyEventContext();
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheDataSerializerHook.java:239]: fixed

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java [hunk 14]
```diff
@@ -132,20 +132,33 @@ public final void executeRun() {
...
             } else {
                 throw new IllegalStateException("Unhandled task:" + task);
             }
-            completedTotalCount.inc();
+            if (counter != null) {
+                counter.inc();
+                completedTotalCount.inc();
+            } else {
+                // retry later if not ready
+                queue.add(task, false);
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:160]: fixed

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java [hunk 15]
```diff
@@ -0,0 +1,97 @@
...
+
+import com.hazelcast.spi.annotation.PrivateApi;
+import com.hazelcast.spi.tenantcontrol.TenantControl;
+import com.hazelcast.spi.tenantcontrol.TenantControl.Closeable;
+import java.util.concurrent.locks.Lock;
+import java.util.concurrent.locks.ReentrantLock;
+import java.util.function.Supplier;
+
+/**
+ * Represents a value that requires tenant control context to be accessed
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java:27]: fixed

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/OperationRunner.java [hunk 16]
```diff
@@ -49,11 +49,11 @@ public OperationRunner(int partitionId) {
 
     public abstract long executedOperationsCount();
 
-    public abstract void run(Packet packet) throws Exception;
+    public abstract boolean run(Packet packet) throws Exception;
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/OperationRunner.java:52]: fixed

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/OperationRunner.java [hunk 17]
```diff
@@ -49,11 +49,11 @@ public OperationRunner(int partitionId) {
...
 
     public abstract void run(Runnable task);
 
-    public abstract void run(Operation task);
+    public abstract boolean run(Operation task);
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/OperationRunner.java:56]: fixed

**Comment by lprimak** [comment]
@vbekiaris fixed according to all your comments

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java [hunk 18]
```diff
@@ -204,23 +204,29 @@ public void run(Operation op) {
...
 
             ensureNoSplitBrain(op);
 
-            op.beforeRun();
-
-            call(op);
+            if (op.isOperationReady()) {
+                op.pushThreadContext();
+                op.beforeRun();
+                call(op);
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java:238]: done

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by lprimak** [comment]
@vbekiaris I removed BypassClassCache interface. I found the 'true' cause of it and this functionality is not necessary, thus simplifying PR even further

**Comment by gurbuzali** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 19]
```diff
@@ -43,18 +41,19 @@
...
+    Closeable setTenant();
+
+    /**
+     * To be called when Hazelcast object is created
+     * @param destroyEventContext hook to decouple any Hazelcast object when the tenant is destroyed,
+     * This is used, for example, to delete all associated caches from the application when
+     * it gets undeployed, so there are no ClassCastExceptions afterwards.
+     * Cannot be null. This is a functional interface, so no-op lambda can be used instead.
+     */
+    void distributedObjectCreated(DestroyEventContext destroyEventContext);
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:56]: You can also add `Nonnull` annotation here then, also add `Nonnull` or `Nullable` for other methods, parameters and return values.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 20]
```diff
@@ -43,18 +41,19 @@
     /**
      * Establish this tenant's thread-local context
      * Particular TenantControl implementation will control the details of how
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:43]: Minor - "Particular TenantControl implementation will control the details of how" can probably be rephrased as it sounds strange.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 21]
```diff
@@ -43,18 +41,19 @@
...
      * @return handle to be able to close the tenant's scope.
      */
-    Closeable setTenant(boolean createRequestScope);
+    Closeable setTenant();
+
+    /**
+     * To be called when Hazelcast object is created
+     * @param destroyEventContext hook to decouple any Hazelcast object when the tenant is destroyed,
+     * This is used, for example, to delete all associated caches from the application when
+     * it gets undeployed, so there are no ClassCastExceptions afterwards.
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:53]: Minor: `{@code null}` and `{@link ClassCastException}`

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 22]
```diff
@@ -65,5 +64,29 @@
      * Hazelcast object from the tenant
      * This is so the TenantControl itself can be garbage collected
      */
-    void unregister();
+    void distributedObjectDestroyed();
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:67]: Minor: maybe we can change the method names `distributedObjectCreated` and `distributedObjectDestroyed`. I understand they should be called when the object is created and destroyed but this tells more about _when_ they will be called rather than _what_ the implementation should do. In some other case, maybe we might call these methods when the object hasn't yet been created or destroyed.

Maybe something like `registerContext` or `unregisterContext` is better?

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 23]
```diff
@@ -65,5 +64,29 @@
...
+
+    /**
+     * Checks if tenant app is loaded at the current time and classes are available
+     *
+     * @param op passed so the tenant can filter on who is calling
+     * @return true if tenant is loaded and classes are available
+     */
+    boolean isAvailable(Operation op);
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:75]: Umph. We are leaking private API here and this is a big problem in terms of compatibility. `Operation` is very private API and it's class name, package, methods and implementation may change heavily between releases or even get deleted completely. Can you provide less context here?

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java [hunk 24]
```diff
@@ -65,5 +64,29 @@
...
+
+    /**
+     * clean up the thread to avoid potential class loader leaks
+     */
+    void clearThreadContext();
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:80]: What's the difference between this method and close? I would expect close to clear the context.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java [hunk 25]
```diff
@@ -503,35 +489,18 @@ public CacheConfig findCacheConfig(String simpleName) {
...
-                logger.finest("Could not load service provider for TenantControl", e);
-            }
-        }
-        if (tenantControlFactory == null) {
-            tenantControlFactory = NOOP_TENANT_CONTROL_FACTORY;
-        }
-        CacheConfigAccessor.setTenantControl(cacheConfig, tenantControlFactory.saveCurrentTenant(
-                new CacheDestroyEventContext(cacheConfig.getName())));
+    public void reSerializeCacheConfig(CacheConfig cacheConfig) {
+        CompletableFuture<CacheConfig> future = new CompletableFuture<>();
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499]: Why do we need to reserialise on cache destroy? Keep in mind this is concurrent with cache partition operations.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java [hunk 26]
```diff
@@ -71,8 +71,12 @@ public Data getSerializedValue(SerializationService serializationService) {
         return serializedValue;
     }
 
-    // returns a new DeferredValue representing the same value as this
     public DeferredValue<V> shallowCopy() {
+        return shallowCopy(true, null);
+    }
+
+    // returns a new DeferredValue representing the same value as this
+    public DeferredValue<V> shallowCopy(boolean resolved, SerializationService serializationService) {
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java:79]: Can you add javadoc explaining what `resolved` is about?

File: hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java [hunk 27]
```diff
@@ -708,11 +688,11 @@ protected void readListenerConfigurations(ObjectDataInput in) throws IOException
      *                 or will be resolved to loaded classes and the actual {@code keyType} and {@code valueType} will be copied.
      *                 Otherwise, this configuration's {@code keyClassName} and {@code valueClassName} will be copied to the
      *                 target config, to be resolved at a later time.
+     * @param backupSerializationService in case serialization service isn't initialized
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java:691]: Can you initialise the serialisation service on the config before calling this method instead of providing it as an argument?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java [hunk 28]
```diff
@@ -81,7 +85,12 @@ public Data getSerializedValue(SerializationService serializationService) {
             copy.serializedValueExists = true;
             copy.serializedValue = serializedValue;
         }
-        if (valueExists) {
+        if (!resolved && serializationService != null) {
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java:88]: It's a bit hard reasoning about the states of `DeferredValue`. Isn't it the case that either `serializedValueExists` is `true` or `valueExists` is `true` and that we can simply use the previous code? Which scenario does this new case cover?

File: hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/atomiclong/proxy/AtomicLongProxy.java [hunk 29]
```diff
@@ -251,5 +251,4 @@ public void destroy() {
     public CPGroupId getGroupId() {
         return groupId;
     }
-
 }
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/atomiclong/proxy/AtomicLongProxy.java:254]: Can you revert this and `ClassLoaderUtil`?

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: Is there an example how much code duplication it actually introduces? I don't think it'll be too much and I must agree this approach is suprising to say the least. It also requires you to do code like this, which might not be necessary if you were passing around boolean:
`return currentRunner.run(operation) ? null : completedOperationCount;`

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java [hunk 30]
```diff
@@ -125,7 +132,8 @@ public int getClassId() {
         @Override
         public void run() {
             try {
-                registry.createProxy(proxyInfo.getObjectName(), proxyInfo.getSource(), true, true);
+                registry.createProxy(proxyInfo.getObjectName(), proxyInfo.getSource(), true, true,
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: What if the proxies were propagated while the cluster version is 4.0 and then we switched to cluster version 4.1? Where do we react to this cluster version change to update the tenant control?

File: hazelcast/src/test/java/com/hazelcast/cache/CacheTenantControlTest.java [hunk 31]
```diff
@@ -137,69 +167,120 @@ public void testTenantControl_executionBeforeAfterOps() {
...
         }
     }
 
     public static class CountingTenantControl implements TenantControl {
-
         @Override
-        public Closeable setTenant(boolean createRequestScope) {
-            new Exception().printStackTrace();
+        public Closeable setTenant() {
+//            new Exception().printStackTrace();
```
Comment (mmedenjak) [inline hazelcast/src/test/java/com/hazelcast/cache/CacheTenantControlTest.java:224]: Leftover

**Review by mmedenjak — COMMENTED** [review]
Overall, I don't see major blockers for this PR and I think it'll make it into 4.1, but there's definitely room for improvement.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: It saves at least 12 redundant lines of code in hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java, you can see the changes right in this PR.

The issue here isn't only the therwise-would-be 12 lines of code, the alternative would require creating an if() statement for every one of those counter instances to check if the operation is available, and only then increment the counter, leading to another 20+ line of code duplication, which is very error-prone and would require another 50+ lines of unit tests.

In reality it may not be that complex, but just thinking about it makes this solution much more elegant

File: hazelcast/src/main/java/com/hazelcast/cache/impl/tenantcontrol/CacheDestroyEventContext.java [hunk 32]
```diff
@@ -42,21 +42,6 @@ public CacheDestroyEventContext(String cacheName) {
         this.cacheName = cacheName;
     }
 
-    @Override
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/tenantcontrol/CacheDestroyEventContext.java:45]: old logic didn't work correctly under any circumstances anyway, it actually created more problems, so it brings no value here, actually fixes a previous problem.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java [hunk 33]
```diff
@@ -164,64 +162,72 @@ public AbstractCacheRecordStore(String cacheNameWithPrefix, int partitionId, Nod
...
-            cacheLoader = injectDependencies(cacheLoader);
-        }
-        if (cacheConfig.getCacheWriterFactory() != null) {
-            Factory<CacheWriter> cacheWriterFactory = cacheConfig.getCacheWriterFactory();
-            cacheWriterFactory = injectDependencies(cacheWriterFactory);
-            cacheWriter = cacheWriterFactory.create();
-            cacheWriter = injectDependencies(cacheWriter);
-        }
+        injectDependencies(evictionPolicyEvaluator.getEvictionPolicyComparator());
+        TenantControl tenantControl = nodeEngine.getProxyService()
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: Doesn't this undo the part of the effort of moving out tenant control out of the cache service? I thought the idea was to make it generic and not linked to cache.
I agree with you that it looks awkward however I don't know enough to see where it would be a better, generic place to put it that's accessible to all

[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: I basically need something 'global' where I can retrieve tenant control by service and distributed object names. Is there any generic place like that?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java [hunk 34]
```diff
@@ -164,64 +162,72 @@ public AbstractCacheRecordStore(String cacheNameWithPrefix, int partitionId, Nod
...
+                .getTenantControl(ICacheService.SERVICE_NAME, cacheNameWithPrefix);
+        cacheLoader = new TenantContextual<>(this::initCacheLoader,
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:192]: this turned out to be quite the task :)

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 19 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:56]: done

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 20 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:43]: done

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 21 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:53]: done

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 23 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:75]: All I could think of is class name (String) or actual class (Class<?>) objects I'll change it to Class<?> for now as it seems more type-safe

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 22 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:67]: renamed to registerObject / unregisterObject

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 24 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java:80]: added more comments. This is catch-all method that clears all of the potential context instead of just the one that was used in setTenant()

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java (hunk 25 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499]: All user classes have to be removed from the cache configuration, i.e. key types, value types, all factories, etc. when tenant is destroyed, otherwise there would be class loading issues.
This is called when tenant is undeployed so there would be no other cache operations with this configuration in this case.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java (hunk 26 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java:79]: done

File: hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java (hunk 27 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java:691]: Here I was simply trying to resolve an NPE. I was not going to refactor this class without knowing the sideffects.
Perhaps you can ask @vbekiaris as I believe he wrote that class

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java (hunk 28 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java:88]: This is a simple fix for NPE.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java (hunk 30 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: Not sure this can be resolved, or should be, since 4.0 didn't work correctly anyway

File: hazelcast/src/test/java/com/hazelcast/cache/CacheTenantControlTest.java (hunk 31 above)
Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/CacheTenantControlTest.java:224]: removed

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/tenantcontrol/CacheDestroyEventContext.java (hunk 32 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/tenantcontrol/CacheDestroyEventContext.java:45]: Ok, if that's the case...

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: It doesn't need to be just in the cache service, it can be part of any service that wishes to participate in tenant control. Some services may not need to participate in tenant control so hooking it into the proxy lifecycle might be unnecessary there (e.g. `FlakeIdGenerator`, `PNCounter`).

As for what would be the best "global" place, I guess it's just like any other helper subsystem (execution service, proxy service, ...) so to me `NodeEngine.getTenantControl` seems ok and generally `NodeEngine` is readily available almost everywhere.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java (hunk 28 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java:95]: When does NPE occur?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 34 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java]: Looks good.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 23 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: Again, operations might change class names and be deleted across minor releases so I'm not sure this will be good enough.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java (hunk 30 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: It might be the case, but here's what will happen on RU from 4.0 to 4.1. A user is running 4.0 cluster with some proxies. They start RU, shut down some 4.0 members, add some 4.1 members, and perhaps add some more proxies in the meantime. They complete RU and switch to cluster version 4.1. At this point, none of the proxies have tenant control since we had to avoid copying it because of serialization concerns.

What I'm thinking is that we should either avoid sending tenant control over the wire and rely on some tenant control on each node locally based on the configuration and the node version, or implement `ClusterVersionListener#onClusterVersionChange` and react on the cluster version change to distribute the tenant control across the cluster once the cluster has been upgraded to 4.1, which seems prone to race conditions as it would be asynchronous.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: Can you point to the commit where the alternate solution is present? I tried going through the git history for this class but could not find it. The issue being that the current codebase definitely has issues with clarity and I'm unsure if I can assess how worse the alternate solution is.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java (hunk 25 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499]: As we don't have any synchronization between the proxy lifecycle and the operation lifecycle, it is still possible there are ongoing operations using tenant control, e.g. replication operations, cache read/write operations being retried because of some network issues... On the other hand, as this would be called from some unknown thread by the SPI implementation, there's not much we can do here but document that it must be invoked once there are no more ongoing operations.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: Unfortunately when I did the alternative solution it was pretty bad and I didn't even commit it.
I think the comment makes the current solution pretty  clear on what it does.
I can roll this whole thing back and put back the "bad" solution but I need some assurances that the work will not be in vain. I need this PR done in 4.1 and if that's what it'll take I can do that (reluctantly)

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: Ok, I can move it out of proxy into NodeEngine

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java (hunk 28 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java:95]: Oh I really don't remember the details. There is a whole bunch of "other side" here in Payara that you don't see and it was quite the effort to get all of this working. I just fixed the NPE when I saw it and I unfortunately don't remember where exactly it was.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java (hunk 30 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: tenant control **absolutely has** to be sent over the wire. This is one of the basic requirements. Again, there is lots of things you don't see that are implemented in Payara and may not be obvious from just the Hazelcast part.

As discussed previously I will try to move it out of proxy and into node engine.

All of this is non-existent problem anyway because nobody is using tenant control in 4.0 because it doesn't work correctly anyway.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 23 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: The point of this is to filter by operation. service or distributed object names are useless in this case.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: Let me correct that, I need to assess the feasibility of it first

[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: Ok, the problem I am having is that tenant control needs to go over the wire when distributed object is created.
This is why I put it into proxy anyway. Do you have the alternative of how to get tenant control created correctly with the distributed object while not using the proxy as the vehicle for this?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java (hunk 25 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499]: in tenant control's case, this is only called when tenant is unavailable, and in such case all operations are not going to go through (would be put back in the queue) and will eventually time out. This is the correct behavior in this instance.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: Let me rephrase that. The 'specific' tenant control instance needs to be created when distributed object is created, and needs to go over the wire and be 'held' by the same distributed object everywhere in the cluster. This is why the code went into Proxy in the first place, because it is the 'mirror' of the distributed object on every node.

So the requirements are:
- tenant control holds state on a per-object basis, and needs to be distributed on the network
- tenant control needs to be kept with the object through all cluster nodes
- Objects, such as CacheRecordStore need object-specific tenantControl when created

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java (hunk 30 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: To answer your question directly, if tenant control is not found (null) it won't be used in which case you will get classloader errors, which would happen in 4.0 anyway since tenant control isn't working correctly.
So, the situation is improved in all cases, and breaks in none.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:135]: Ok, this is taking too much time and energy.
I'll jut revert this change, put in all the duplicate code that was here before
so we can just move on from this.

**Comment by lprimak** [comment]
@mmedenjak I think what you are missing is that when tenant is unavailable, there are no operations that can run, because they are marked by tenant control as unavailable. This is why all the issues that you are bringing up about operations vs. proxy threading do not apply in this case.

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 33 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:190]: You're right, a proxy does seem like the perfect place for it then. Alternatively, it could be placed in a service, much like the proxy service, in `NodeEngine`, and share the same lifecycle, so that we could avoid mixing concerns in the proxy service and its' classes. Still, the proxy service and all of its' classes are private API, so we may simply ignore this complexity at this point, and merge it, only to consider moving it elsewhere in a subsequent PR.

Summary - I'll think about it a bit more but we can say this is not a blocker for the merge.

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2535/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2535/Hazelcast-pr-builder-2535.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31978, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 23 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: It is very inconvenient from the standpoint of the SPI implementations as users might depend on classes, or methods, or API, which is internal and subject to change. While on this subject, I'm thinking not only what can happen in terms of when we change a class name/package, or add/remove methods but what would happen for your SPI implementation if we added a new operation like `com.hazelcast.cache.internal.SuperFastReadOperation`. How would you make sure that operation is handled properly then?

But, in an effort to proceed further with this PR, here are some questions and ideas:
• what is it that you actually use from an operation? What's important to your implementation of the SPI? The operation name? I'm thinking if we can introduce a new interface which will clearly describe the things that you require, and our private API can provide just this information. 
• alternatively, although unlikely, we can maybe think about making the tenant control part of the private API. That way, it has access to all other private API and we can change it any way we want in any release. Still, this option is rather "dirty"

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java (hunk 25 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499]: Ok, right, thanks.

File: hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java (hunk 27 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/config/CacheConfig.java:691]: It's not a blocker but I think it would be safe to set the serialisation service before calling this method. I'm more worried about the changes in the proxy and operation system than any issues that could come up as a side effect of setting the serialisation service on CacheConfig :)

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java (hunk 30 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: Ok, I'll reassess the code from the standpoint of having to migrate tenant control. I think it might be ok then, and we might further be comfortable with the incompatibility with RU, if we made this whole tenant control SPI internal. But I have to think some more about the consequences of something like that.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2541/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/2541/Hazelcast-pr-builder-2541.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MigrationInvocationsSafetyTest.migrationCommit_shouldRollback_whenTargetCrashes:324->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:221->PartitionCorrectnessTestSupport.assertSizeAndDataEventually:225->HazelcastTestSupport.assertTrueEventually:1355->HazelcastTestSupport.assertTrueEventually:1253->PartitionCorrectnessTestSupport.access$000:66->PartitionCorrectnessTestSupport.assertSizeAndData:237->PartitionCorrectnessTestSupport.assertPartitionAssignments:179->PartitionCorrectnessTestSupport.assertPartitionAssignments:216 expected:<-1669084290458575971> but was:<8917940183757797572>
[INFO] 
[ERROR] Tests run: 31978, Failures: 1, Errors: 0, Skipped: 978
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by lprimak** [comment]
@mmedenjak I have no idea what's up with that test. It's totally unrelated

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java (hunk 30 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/operations/PostJoinProxyOperation.java:135]: Either way it's fine with me

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java]: This should be called once, before the tenant context is initialised. Probably isn't going to be a problem. @lprimak is it possible to initialise the tenant control eagerly while record store is being created and not later when it's accessed?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 2 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java]: Resolving this comment as this class serves its' purpose and I asked if the tenant context can be resolved eagerly in other comment above.

File: hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java (hunk 23 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/spi/tenantcontrol/TenantControl.java]: We decided not to pursue moving this SPI into a private/internal package as it wouldn't really be owned by Hazelcast and we could not then move it, remove it, augment it when and how we would like to. Instead, it would effectively be owned by Payara.

Instead, we have managed to agree on what is actually needed from the perspective of the operation. Resolving this comment as we will soon update this part of the code to avoid leaking private API.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java]: no, as when Hazelcast migration happens, no user classes (factory classes here) are available so this will result in errors

**Comment by mmedenjak** [comment]
@lprimak Vassilis added an interface to avoid leaking private API in the other PR. Can you take a look?
https://github.com/hazelcast/hazelcast/pull/17673/commits/d2c648d5ecfef647a347cac6457cbdb82108fea2

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java (hunk 1 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/TenantContextual.java]: Resolving as it should be lazy and it will be invoked only once.

**Comment by lprimak** [comment]
https://github.com/hazelcast/hazelcast/pull/17673 is now obsolete with all changes migrated to this PR
@vbekiaris @mmedenjak since you have access to this PR and branch, please do the further work here.
thank you!

**Comment by lprimak** [comment]
As far as I can tell, there are only two problems left:
- tests not passing
- PreJoinConfig compatibility with 4.0

> Just realised this here is a problem. In 4.0, we serialised tenant control (or null) and in 4.1 we silently stop serialising or reading this object. So, this breaks the serialisation compatibility.
Seems to me that all users using cache and PreJoinCacheConfig will run into this issue, whether they use tenant control or not.

**Comment by lprimak** [comment]
Now only one problem remains
- test passing

**Comment by mmedenjak** [comment]
@lprimak can you squash the commits? Alternatively I can do it. This week I'm busy with some other things but I'd like to continue with this next week.

**Comment by lprimak** [comment]
Sure

**Comment by lprimak** [comment]
It's been a month... can we restart this issue please?
thank you!

**Comment by lprimak** [comment]
Fixed it so it passes all of the tests

**Comment by kwart** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
I did a quick run over the current PR. I see not much has changed, which is good and it leaves me with a couple of non-critical things that I wanted to do:
- double-check the logic in `Operation*` classes, to see we didn't break something. This part is extremely sensitive as ALL of hazelcast uses this code and it needs to be picture-perfect. But for now, I didn't see any red flags.
- double-check the logic in `DeferredValue`. Last we commented on that, you did some defensive code for an NPE. But it was a bit fuzzy and I want to understand it better
- add more tests. To me this is the biggest outstanding item. There are overall a few tests, which if I remember correctly, cover ICache and IMap, and mostly cover some happy-day cases. But there's much more to the changed code, not just the fact that we added tenant control to other data structures. The production code looks ready to go, more or less, but I really would like to have more tests. The good news is, I think it'll be rather straightforward to add them.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/tenantcontrol/impl/TenantControlReplicationOperation.java [hunk 35]
```diff
@@ -0,0 +1,136 @@
...
+import java.io.IOException;
+import java.util.Map.Entry;
+import java.util.concurrent.ConcurrentMap;
+
+/**
+ * Operation which exchanges tenant control between members.
+ * Can be used to exchange a single or multiple tenant controls each belonging
+ * to a different distributed object.
+ *
+ * @since 4.1
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/tenantcontrol/impl/TenantControlReplicationOperation.java:37]: nit: update to 4.2

**Comment by lprimak** [comment]
> double-check the logic in DeferredValue. Last we commented on that, you did some defensive code for an NPE. 

From what I can remember, the NPE was caused by DeferredValue getting called from reSerialize() method, which isn't part of the 'regular' serialize flow in Hazelcast, thus Serializer wasn't initialized. I felt like I would be introducing more risks by initializing it somewhere else, thus I introduced the backup serializer as a parameter.

> add more tests. To me this is the biggest outstanding item.

Is this an action item for me or Hazelcast? If it's for me, I would need quite a bit more direction than that, because
I feel like all the critical tests are there, and any others would  not add too much value (I may be wrong of course) that's why I need direction :)

> and mostly cover some happy-day cases. 

Not 'quite' true, as `TenantUnavailableTest` is all about error and edge cases

File: hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java [hunk 36]
```diff
@@ -152,10 +154,19 @@ public void cacheConfigShouldBeAddedOnJoiningMember_whenCacheLoaderFactoryNotRes
...
-                + "Package excluded explicitly"));
-        cache.invoke(key, new PersonEntryProcessor());
+        ClassLoader oldClassLoader = Thread.currentThread().getContextClassLoader();
+        try {
+            Thread.currentThread().setContextClassLoader(hz2.getConfig().getClassLoader());
+            CacheProxy cacheProxy = (CacheProxy) cache;
+            CacheService cacheService = (CacheService) cacheProxy.getService();
+            expect.expectCause(new RootCauseMatcher(ClassNotFoundException.class, "classloading.domain.PersonCacheLoaderFactory - "
+                    + "Package excluded explicitly"));
+            cacheService.getCacheConfig(cache.getPrefixedName()).getCacheLoaderFactory();
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java:164]: Why was this test changed? The second `HazelcastInstance` is anyway started with the filtering class loader and `invoke` will trigger the cache loader factory instantiation attempt. In the new version of the code, the following 2 lines will be anyway skipped because this line will throw the `ClassNotFoundException`.

**Review by vbekiaris — COMMENTED** [review]
Looks good! I added some minor comments

File: hazelcast/src/main/java/com/hazelcast/cache/impl/operation/AddCacheConfigOperation.java [hunk 37]
```diff
@@ -69,5 +68,8 @@ public int getClassId() {
         return CacheDataSerializerHook.ADD_CACHE_CONFIG_OPERATION;
     }
 
-
+    @Override
+    public boolean requiresTenantContext() {
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/operation/AddCacheConfigOperation.java:72]: done

File: hazelcast/src/main/java/com/hazelcast/spi/impl/tenantcontrol/impl/TenantControlReplicationOperation.java (hunk 35 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/tenantcontrol/impl/TenantControlReplicationOperation.java:37]: done

File: hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java (hunk 36 above)
Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java:164]: Because this test always succeeded, when it should have failed. With this change, class loading is more realistic and it makes for a better test.
I changed it because it was succeeding when I introduced it into app server (actual class loading environment) but it should have failed.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java [hunk 38]
```diff
@@ -196,6 +241,7 @@ private void process(TaskBatch batch) {
         } finally {
             queue.add(batch, false);
         }
+        return true;
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/impl/OperationThread.java:244]: fixed

**Comment by nfrankel** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java (hunk 36 above)
Comment (vbekiaris) [reply hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java:164]: > Because this test always succeeded, when it should have failed. With this change, class loading is more realistic and it makes for a better test.

The original test expects the exception to be thrown from Hazelcast partition operation threads. These threads are the ones which execute the `EntryProcessor` from `invoke` and are responsible for instantiating and invoking the `CacheLoader`. They use the config classloader (that is the `FilteringClassLoader` setup in second instance's `Config`).

The updated code changes the test-executing thread's context classloader and forces initialization of the `CacheLoader` from the test thread, triggering the exception to be thrown earlier from `getCacheLoaderFactory` call and does not exercise the partition operation thread code that should trigger the `CacheLoader` execution at all.

Can you elaborate on the setup that succeeded when it should have failed?

Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/CacheTypesConfigTest.java:185]: > Can you elaborate on the setup that succeeded when it should have failed?

This was 3 years ago, I don't remember. All I know this was failing in my tests an I fixed it.

I reverted the changes and added another test, hope that resolves this (long) discussion

**Comment by nfrankel** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java [hunk 39]
```diff
@@ -92,7 +93,7 @@
     private static final int TIMEOUT = 10;
 
     protected final ILogger logger;
-    protected final CacheConfig<K, V> cacheConfig;
+    protected CacheConfig<K, V> cacheConfig;
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: From which threads can this reassignment be called now? As I don't see safe publication of new values.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java [hunk 40]
```diff
@@ -56,7 +57,12 @@ public PreJoinCacheConfig(CacheConfig cacheConfig) {
     }
 
     public PreJoinCacheConfig(CacheConfig cacheConfig, boolean resolved) {
-        cacheConfig.copy(this, resolved);
+        this(cacheConfig, resolved, null);
+    }
+
+    public PreJoinCacheConfig(CacheConfig cacheConfig, boolean resolved,
+            SerializationService backupSerializationService) {
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: I think we can remove this whole `backupSerializationService`. The case which you seem to be referring to is when the `CacheConfig` is constructed using `public CacheConfig(CacheSimpleConfig simpleConfig)`. I believe that if we set the serialization service in that constructor, it will always be non-null. Do you have a test (either on our side or on your side) which tests for this NPE?

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/3103/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/3103/Hazelcast-pr-builder-3103.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 4 errors reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499:14: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499:31: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:499:71: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java:500:22: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
</details>
</pre>

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java [hunk 41]
```diff
@@ -353,12 +355,7 @@ protected EvictionChecker createCacheEvictionChecker(int size, MaxSizePolicy max
     protected EvictionPolicyComparator createEvictionPolicyComparator(EvictionConfig evictionConfig) {
         checkCacheEvictionConfig(evictionConfig);
 
-        Closeable tenantContext = getTenantControl(cacheConfig).setTenant(false);
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:356]: No it doesn't. At this point all data is serialized and user classes are not required

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java (hunk 39 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: I think you already changed this

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: No, this was during reSerialize() which does a copy() of the cache config, not simpleConfig

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java (hunk 39 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: this is called when the tenant is undeployed and cache config is deserialized. It doesn't have to be propagated anywhere and cannot be inconsistent.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java [hunk 42]
```diff
@@ -164,64 +162,73 @@ public AbstractCacheRecordStore(String cacheNameWithPrefix, int partitionId, Nod
...
-            cacheLoader = cacheLoaderFactory.create();
-            cacheLoader = injectDependencies(cacheLoader);
-        }
-        if (cacheConfig.getCacheWriterFactory() != null) {
-            Factory<CacheWriter> cacheWriterFactory = cacheConfig.getCacheWriterFactory();
-            cacheWriterFactory = injectDependencies(cacheWriterFactory);
-            cacheWriter = cacheWriterFactory.create();
-            cacheWriter = injectDependencies(cacheWriter);
-        }
+        injectDependencies(evictionPolicyEvaluator.getEvictionPolicyComparator());
```
[the remark this answers is not in the document]
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:189]: probably a mistake. Can you fix it since you are already working on this?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: I am sure it can be removed provided serializationService is made sure never to be null

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java (hunk 39 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: The thread-safety semantics remain the same, I only removed duplication. 

>  It doesn't have to be propagated anywhere and cannot be inconsistent.
Can you elaborate? If that is so, why do we need to update it in the first place?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: Yes, `reSerialize()` was doing a copy of a `CacheConfig` which was most probably constructed using `public CacheConfig(CacheSimpleConfig simpleConfig)` as that constructor does not ensure the serialization service is set.

Do you have a test (either on our side or on your side) which tests for this NPE?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java (hunk 42 above)
[the remark this answers is not in the document]
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheRecordStore.java:189]: Ok, I will.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java (hunk 39 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: To remove references to classes no longer available via class loader when application is I deployed from Payara

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: Maybe... this was so long ago I don't remember

Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: I'll remove it and we'll test then.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java (hunk 39 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: I don't know how else to reserialize cache config when tenant is undeployed, to remove all user classes that are no longer available on the current instance, thus the title of original issue for this PR.
#10875

Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: Also I can't prove a negative

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: > Yes, reSerialize() was doing a copy of a CacheConfig which was most probably constructed using public CacheConfig(CacheSimpleConfig simpleConfig)

I remember now. This is correct. If CacheConfig always have serializer non-null, the backup serialization code can be removed.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java (hunk 39 above)
Comment (lprimak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/CacheProxySupport.java:96]: The only other way I could see to do this is to recreate the whole proxy again with the new re-serialized cache config. I have no idea how to do that safely either.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: I started removing it which then turned out to either the serialization service needing to be added to `public CacheConfig(CacheSimpleConfig simpleConfig)` or a setter added to `CacheConfig`. @vbekiaris is that constructor public API? 

Also, is `CacheConfig#copy` public API? Because we're changing the arguments to include `SerializationService`, which is private API.

**Comment by mmedenjak** [comment]
I went through the operation code, looks ok. The deferred value is also ok, I'll just verify if we broke public API by adding `SerializationService` parameters. So the only thing I have left to double-check is the test coverage. I guess we don't have tests for all `TenantContextAwareService`, so probably at least that might be a thing to improve.

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java:64]: Pragmatically, I don't expect any end users actually use `CacheConfig(CacheSimpleConfig simpleConfig)` or `CacheConfig#copy`, however both are exposed as public. A workaround could be to add a package-private setter for `SerializationService` and access it via `CacheConfigAccessor` which is already declared as `@PrivateApi`.

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 40 above)
Comment (mmedenjak) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java]: Changed it to your suggestion and removed backup serialization service. CacheConfig should now always have the serialization service set.

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/3126/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/3126/Hazelcast-pr-builder-3126.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JCacheCacheManagerDITest.testCacheWithCacheLoaderFactory_dependenciesInjected:61 Spring bean not injected to @SpringAware object
[ERROR]   JCacheCacheManagerDITest.testCacheWithCacheWriterFactory_dependenciesInjected:82 Spring bean not injected to @SpringAware object
[ERROR]   JCacheCacheManagerDITest.testCacheWithExpiryPolicyFactory_dependenciesInjected:103 Spring bean not injected to @SpringAware object
[INFO] 
[ERROR] Tests run: 191, Failures: 3, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

File: hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java [hunk 43]
```diff
@@ -0,0 +1,181 @@
...
+
+        assertTrue("Iterator should not be empty", it2.hasNext());
+        while (it2.hasNext()) {
+            Cache.Entry<String, ValueType> entry = it2.next();
+            assertInstanceOf(ValueType.class, entry.getValue());
+        }
+        Assert.assertFalse("Class Loading Failed", classLoadingFailed);
+    }
+
+    public static class SimulateNonExistantClassLoader extends URLClassLoader {
```
Comment (mmedenjak) [inline hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java:142]: This classloader is not used. Is there a test missing?

File: hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java [hunk 44]
```diff
@@ -0,0 +1,181 @@
...
+    private static final Set<String> disallowClassNames = new HashSet<>();
+    private static final CountDownLatch latch = new CountDownLatch(1);
+    private static boolean classLoadingFailed;
+
+    @Before
+    public void setup() {
+        cacheName = randomName();
+        classLoadingFailed = false;
+        initState();
+        classesAlwaysAvailable = false;
```
Comment (mmedenjak) [inline hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java:75]: `classesAlwaysAvailable` is false in all tests. Is there a test where it is true? Should we have a test for that?

**Comment by mmedenjak** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]
👍

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/3128/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/3128/Hazelcast-pr-builder-3128.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JCacheCacheManagerDITest.testCacheWithCacheLoaderFactory_dependenciesInjected:61 Spring bean not injected to @SpringAware object
[ERROR]   JCacheCacheManagerDITest.testCacheWithCacheWriterFactory_dependenciesInjected:82 Spring bean not injected to @SpringAware object
[ERROR]   JCacheCacheManagerDITest.testCacheWithExpiryPolicyFactory_dependenciesInjected:103 Spring bean not injected to @SpringAware object
[INFO] 
[ERROR] Tests run: 191, Failures: 3, Errors: 0, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@vbekiaris @lprimak I finally managed to fix the failing spring tests. Looks like it's because of the additional logic in `DeferredValue#shallowCopy`:
```
if (!resolved && serializationService != null) {
            if (!serializedValueExists) {
                copy.serializedValueExists = true;
                copy.serializedValue = getSerializedValue(serializationService);
            }
        }
```

Basically, the tests assumed that the loader/writer and expiry factory are instantiated only once (when doing `springCacheManager.getCacheManager().getCache()`) and that the `value` is passed onto copies of cache configs (when doing `CacheConfig#copy`). But, now because of the logic above and because `resolved == false`, we serialized all factories and deserialized it, making copies.

I fixed it by making sure there will be _some_ factory instance which gets initialised by managed context, and not necessarily the one which was constructed first. Let me know if that does not sound right or if you need more info.

**Comment by vbekiaris** [comment]
`CacheLoaderFactory` and other user customizations are expected to be serialized/deserialized with the associated `CacheConfig`, so I don't think the cloning is an issue.

File: hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java (hunk 43 above)
Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: yes, probably.
need to go through history to figure out what happened
the alternative is that there was one and it's no longer applicable, I will take a look

File: hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java (hunk 44 above)
Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: there is nothing to test that isn't rested already if that is true

File: hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java (hunk 43 above)
Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: well, there is no history since commits were squashed :(

Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: I think during the refactoring of tests somehow reference to `SimulateNonExistantClassLoader ` got lost

Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: yes, this test is completely broken, I am working on restoring it to functional state

Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: ok this is now fixed

**Comment by nfrankel** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java (hunk 44 above)
Comment (mmedenjak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: Then I'll remove this field as I don't see it's point.

Comment (lprimak) [reply hazelcast/src/test/java/com/hazelcast/cache/TenantUnavailableTest.java]: Ok, I think there was some use for this beforehand (it had to be set to true at one point) but with the current state it's no longer necessary

**Comment by lprimak** [comment]
I am hoping to buy some champagne this week... should I?

**Comment by mmedenjak** [comment]
run-lab-run

**Review by mmedenjak — APPROVED** [review]
Pop the champagne

**Comment by lprimak** [comment]
> Pop the champagne

Nice! Need to have it merged first :)

**Comment by lprimak** [comment]
Got caviar ready alsoi

**Review by vbekiaris — APPROVED** [review]
