### PR TITLE
Relax Kafka producer creation check [HZ-2392]

### LINKED ISSUE #24429: Cannot use a 'SHARED' Kafka data connection to create a mapping [HZ-2392]
**Describe the bug**
After https://github.com/hazelcast/hazelcast/pull/24333, it seems it's no longer possible to use shared `SHARED` data connection for Kafka. If the user tries to provide options via `CREATE DATA CONNECTION...` only, they will get `com.hazelcast.sql.HazelcastSqlException: Missing 'valueFormat' option` when attempting to create a mapping from it. If they provide the `keyFormat` and `valueFormat` options when creating the mapping, the user will get the following error when trying to use this mapping in a query:

```
com.hazelcast.core.HazelcastException: Shared Kafka producer can be created only with data connection options
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{my_job/Kafka[public.my_topic]#0}: com.hazelcast.core.HazelcastException: Shared Kafka producer can be created only with data connection options
        at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)
        at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80)
        at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: com.hazelcast.core.HazelcastException: Shared Kafka producer can be created only with data connection options
```

**Expected behavior**
The mapping can be creating w/o providing the options (i.e. options are provided when creating the shared Kafka DC)

**To Reproduce**

The following unit test can be pasted into `KafkaDataConnectionIntegrationTest` to demonstrate the issue:

```
    @Test
    public void test_canCreateShared() {
        String dcName = randomName();
        String name = createRandomTopic(PARTITION_COUNT);
        createSqlKafkaDataConnection(dcName, true);
        createKafkaMappingUsingDataConnection(name, dcName, "");

        try (SqlResult r = sqlService.execute("INSERT INTO " + name + " VALUES (0, 'value-0')")) {
            assertEquals(0, r.updateCount());
        }

        assertTipOfStream("SELECT * FROM " + name, singletonList(new Row(0, "value-0")));
    }
```

### PR DESCRIPTION
**Pull request by Fly-Style**
Fixes #24429

### CODE REVIEW

**Review by ivanthescientist — APPROVED** [review]

File: extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaDataConnection.java [hunk 1]
```diff
@@ -189,15 +189,23 @@ public <K, V> KafkaProducer<K, V> getProducer(@Nullable String transactionalId)
     public <K, V> KafkaProducer<K, V> getProducer(
             @Nullable String transactionalId,
             @Nonnull Properties properties) {
-        if (getConfig().isShared() && !properties.isEmpty()) {
+        Properties configProperties = getConfig().getProperties();
+
+        boolean inputPropsAreSubsetOfConfigProps = inputPropsAreSubsetOfConfigProps(properties);
+        if (getConfig().isShared() && !properties.isEmpty() && !inputPropsAreSubsetOfConfigProps) {
```
Comment (sumnerib) [inline extensions/kafka/src/main/java/com/hazelcast/jet/kafka/KafkaDataConnection.java:195]: The error message is now misleading, because you still _must_ provide the `keyFormat`/`valueFormat` when creating the SQL mapping AFAICT. Also, providing only the `*.deserializer` options for the DC and key/value formats for the mapping isn't enough either (they aren't considered a subset). This is poor UX, but I think we can live with it in BETA if we improve the error messaging. Maybe something that points the user to set the `*.serializer` options when creating the DC?

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/KafkaDataConnectionIntegrationTest.java [hunk 2]
```diff
@@ -89,17 +91,32 @@ public void test_nonShared() {
...
+
+        try (SqlResult r = sqlService.execute("INSERT INTO " + name + " VALUES (0, 'value-0')")) {
+            assertThat(r.updateCount()).isZero();
+        }
+
+        assertTipOfStream("SELECT * FROM " + name, singletonList(new Row(0, "value-0")));
+    }
+
+    @Test
+    public void when_createSharedProducerWithOverriddenProperty_then_success() {
```
Comment (sumnerib) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/kafka/KafkaDataConnectionIntegrationTest.java:108]: Minor comment: shouldn't it be `when_createSharedProducerWithOverriddenProperty_then_fail()` ?

**Review by sumnerib — CHANGES_REQUESTED** [review]

**Review by sumnerib — APPROVED** [review]
