### PR TITLE
[#15346] Fix deserialization filtering for Externalizables and Deadlock in Map index

### LINKED ISSUE #15346: Leaking deserialization protection on Externalizables
The deserialization filter doesn't properly protect against vulnerable `Externalizable` classes. The filtering has to be extended.

The issue was discovered by @Mak-Sym and reported on Hazelcast google group - https://groups.google.com/forum/#!topic/hazelcast/B_RAv7gTVPU.

### PR DESCRIPTION
**Pull request by kwart**
Fixes #15346 and also leaking record lock in the `Records`  class.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/cluster/MulticastDeserializationTest.java [hunk 1]
```diff
@@ -74,23 +73,34 @@ public void tearDown() {
...
-        javaSerializationFilterConfig.getBlacklist()
-                .addClasses(TestDeserialized.class.getName());
+    @Test
+    public void testWithoutFilter() throws Exception {
+        Config config = createConfig(false);
+        Hazelcast.newHazelcastInstance(config);
+
+        sendJoinDatagram(new TestDeserialized());
+        Thread.sleep(500L);
+        assertTrueEventually(() -> assertTrue("Object was not deserializaed", TestDeserialized.isDeserialized));
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/cluster/MulticastDeserializationTest.java]: minor: typo in `deserializaed`

File: hazelcast/src/test/java/com/hazelcast/cluster/MulticastDeserializationTest.java [hunk 2]
```diff
@@ -74,23 +73,34 @@ public void tearDown() {
...
-                .setDefaultsDisabled(true);
-        javaSerializationFilterConfig.getBlacklist()
-                .addClasses(TestDeserialized.class.getName());
+    @Test
+    public void testWithoutFilter() throws Exception {
+        Config config = createConfig(false);
+        Hazelcast.newHazelcastInstance(config);
+
+        sendJoinDatagram(new TestDeserialized());
+        Thread.sleep(500L);
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/cluster/MulticastDeserializationTest.java]: no need to sleep here since we use `assertTrueEventually` next

File: hazelcast/src/main/java/com/hazelcast/map/impl/record/Records.java [hunk 3]
```diff
@@ -148,7 +148,13 @@ private static Object tryStoreIntoCache(Record record, Object valueBeforeCas, Se
 
         //we managed to lock the record for ourselves
         Object valueAfterCas = record.getValue();
-        Object object = serializationService.toObject(valueBeforeCas);
+        Object object = null;
+        try {
+            object = serializationService.toObject(valueBeforeCas);
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/map/impl/record/Records.java]: good catch!

**Comment by kwart** [comment]
Thanks for review, @vbekiaris. The findings are fixed in a new commit.

**Comment by kwart** [comment]
@chefhoobajoob Latest 3.12.z build is the 3.12.12.
You can find the released bits
* either in the Maven repo: https://repo1.maven.org/maven2/com/hazelcast/hazelcast/3.12.12/
* or in GitHub releases: https://github.com/hazelcast/hazelcast/releases/tag/v3.12.12

**Comment by chefhoobajoob** [comment]
@kwart : great! thank you, the visa tag was explicitly mentioned in security scans as the version to update to, so pretty confusing
