### PR TITLE
InvocationFuture support for Exceptions as valid response values

### LINKED ISSUE #13138: Setting an Exception in an IAtomicReference causes it to be thrown when getting it
I'm using an Hazelcast **IAtomicReference** to store a **reference to an Exception** object. When I try to get the stored **Exception**, it is **thrown** rather than returned.
Is it a **desired behaviour** (I couldn't find any mention to it in the documentation) **or** is it a **defect**?

```Java
@Test(expected=RuntimeException.class)
public void testExceptionInAtomicReference {
        Config config = new Config();
        HazelcastInstance hz = Hazelcast.newHazelcastInstance(config);

        Exception e = new RuntimeException("my exception");
        IAtomicReference<Exception> ref = hz.getAtomicReference("excRef");
        ref.set(e);
        Exception exception = ref.get(); // <--- This throws the exception stored rather than returning it
}
```

### PR DESCRIPTION
**Pull request by tkountis**
Support for allowing Exceptions to be returned or be thrown. Similar to `j.u.c.CompletableFuture.completeExceptionally`, we can now store `Exception` response values, and the user can access them, as usual, with `Future.get()`

Changes shouldn't affect the fast path, and the additional litter caused, is only on erroneous responses.

- [x] Check whether this can be RU supported

Fixes #13138

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/RetrieveAndDisposeResultOperation.java [hunk 1]
```diff
@@ -44,6 +46,10 @@ public void run() throws Exception {
 
     @Override
     public Object getResponse() {
+        if (result instanceof Throwable) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/RetrieveAndDisposeResultOperation.java]: Why is the exception not immediately raised? Why is it stored in 'result'?

**Comment by pveentjer** [comment]
The idea behind the fix is good. I like the way the exception is wrapped in a marked object so that the ambiguity between a exceptional value and exceptional response is resolved.

My worry is about the all over the place ad hoc fixes to get it working. It is just too easy to miss edge cases.

**Comment by tkountis** [comment]
@pveentjer I agree with the concern, and i had to deal partially with it, in the tests. My suggestion is that we keep this on 3.11 only, no back-ports, so we have more time to interact with it and fix any other side effects.

File: hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/RetrieveAndDisposeResultOperation.java (hunk 1 above)
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/durableexecutor/impl/operations/RetrieveAndDisposeResultOperation.java]: The task is offloaded, so the result is async. Therefore, the Exception happens on another thread.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java [hunk 2]
```diff
@@ -427,4 +430,17 @@ public String toString() {
             this.executor = executor;
         }
     }
+
+    @SuppressWarnings("checkstyle:visibilitymodifier")
+    protected static final class AltResult {
+        public final Throwable cause;
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java]: Can we please make this field private and use a getter method to access it?

If we ever need to access the cause in a compatibility test, those field accesses are super painful (only method calls are properly proxied). I've been there with `Node` and all its public fields. I already see such a field access in `AbstractInvocationFuture_AbstractTest`.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 3]
```diff
@@ -474,7 +475,7 @@ boolean detectAndHandleBackupTimeout(long timeoutMillis) {
         }
 
         if (shouldFailOnIndeterminateOperationState()) {
-            complete(new IndeterminateOperationStateException(this + " failed because backup acks missed."));
+            notifyError(new IndeterminateOperationStateException(this + " failed because backup acks missed."));
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: Here we want to complete immediately with `IndeterminateOperationStateException `, without checking for any other condition.  I think `complete(..)` shows that intention better.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 4]
```diff
@@ -654,6 +655,10 @@ private void complete(Object value) {
         }
     }
 
+    private void onComplete() {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: Nop private method.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 5]
```diff
@@ -687,7 +692,7 @@ private void completeWhenRetryRejected(RejectedExecutionException e) {
         if (context.logger.isFinestEnabled()) {
             context.logger.finest(e);
         }
-        complete(new HazelcastInstanceNotActiveException(e.getMessage()));
+        notifyError(new HazelcastInstanceNotActiveException(e.getMessage()));
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: Similar to `IndeterminateOperationStateException ` case, we want to complete immediately, without any further check.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java [hunk 6]
```diff
@@ -278,25 +280,24 @@ private void initInvocationTarget() throws Exception {
         remote = !context.thisAddress.equals(invTarget);
     }
 
-    void notifyError(Object error) {
-        assert error != null;
+    void notifyError(Throwable cause) {
+        notifyError(new ErrorResponse(cause, op.getCallId(), op.isUrgent()));
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: This seems redundant. `notifyError(ErrorResponse response)` doesn't care about `ErrorResponse` object, it just unwraps the cause. I think existing version is better, no need to wrap/unwrap.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java [hunk 7]
```diff
@@ -78,35 +79,42 @@ protected void onInterruptDetected() {
...
+                    + " was interrupted. " + invocation));
         } else if (unresolved == CALL_TIMEOUT) {
             return newOperationTimeoutException(false);
         } else if (unresolved == HEARTBEAT_TIMEOUT) {
             return newOperationTimeoutException(true);
         } else if (unresolved.getClass() == Packet.class) {
-            NormalResponse response = invocation.context.serializationService.toObject(unresolved);
-            unresolved = response.getValue();
+            unresolved = invocation.context.serializationService.toObject(unresolved);
+            if (unresolved instanceof NormalResponse) {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java]: In which case `unresolved ` is not an instance of `NormalResponse `?  What happens when this condition doesn't hold?

File: hazelcast/src/main/java/com/hazelcast/executor/impl/DistributedExecutorService.java [hunk 8]
```diff
@@ -301,9 +302,13 @@ private void logException(Exception e) {
         private boolean sendResponse(Object result) {
             if (RESPONSE_FLAG.compareAndSet(this, Boolean.FALSE, Boolean.TRUE)) {
                 try {
+                    if (result instanceof Throwable) {
```
[the remark this answers is not in the document]
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/executor/impl/DistributedExecutorService.java]: Leftover of previous solution, removed :+1:

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java (hunk 3 above)
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: :+1:

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java (hunk 5 above)
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: :+1:

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java (hunk 6 above)
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/Invocation.java]: :+1:

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java (hunk 7 above)
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java]: When it is an instance of an ErrorResponse. So once it gets deserialized, it will proceed with processing it, outside the outer IF block.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java [hunk 9]
```diff
@@ -427,4 +437,18 @@ public String toString() {
...
+    protected static final class AltResult {
+        private final Throwable cause;
+
+        public AltResult(Throwable cause) {
+            this.cause = cause;
+        }
+
+        public Throwable getCause() {
+            return cause;
+        }
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java]: Can you add a toString? Always useful when debugging.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java [hunk 10]
```diff
@@ -161,7 +179,7 @@ private Object newOperationTimeoutException(boolean heartbeatTimeout) {
 
         sb.append(invocation);
         String msg = sb.toString();
-        return new ExecutionException(msg, new OperationTimeoutException(msg));
+        return new AltResult(new ExecutionException(msg, new OperationTimeoutException(msg)));
```
[the remark this answers is not in the document]
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java]: Given that the bigger part of the logic handling this lies within the Future class, I think I am fine with this compromise. The alternative would be to re-introduce the factory method, but I think it just adds more noise at this point. If you see other benefits to it, I am happy to put it in.

[the remark this answers is not in the document]
Comment (pveentjer) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/InvocationFuture.java]: My main reason to get make the class public is that we'll be replacing the InvocationFuture by the CompletableFuture very soon.

**Comment by pveentjer** [comment]
The solution looks good. However I'm very worried about potential problems. The main cause is that in HZ there is no distinction between an Exception being thrown and an Exception as value.

I would like to see the 'completeExceptionally' functionality because eventually that is what we'll be using once the CompletableFuture is introduced.

But now we introduce a lot of complexity and ad hoc fixes for a use case that can easily be solved in a simpler way e.g. by wrapping the exception.
