### PR TITLE
Fixing multiple bugs in ResultSets; Increasing test coverage

### LINKED ISSUE #9614: size() doesn't match the actual element number of Set<QueryableEntry>
Set<QueryableEntry> set = ((IndexAwarePredicate) predicate).filter(queryContext);
int size = set.size();
    
int act_size = 0;
for(QueryableEntry queryableEntry : set) {
     act_size++;
}

assert size==act_size;    =====> **Here will throws AssertionError**
__________________________________________________________________________________
The issue is in com.hazelcast.query.impl.AndResultSet, size() will return the size of setSmallest,
but iterator will return the intersection size of setSmallest,otherIndexedResults,lsNoIndexPredicates.
So the inconsistence occurs.  

See the following code:

  ```
public int size() {
     return setSmallest.size();
  }
    
  public boolean hasNext() {
		if (currentEntry != null) {
			return true;
		}

		for (; it.hasNext();) {
			QueryableEntry entry = it.next();

			if (checkOtherIndexedResults(entry) && checkNoIndexPredicates(entry)) {
				currentEntry = entry;
				return true;
			}
		}

		return false;
}  
```

### PR DESCRIPTION
**Pull request by tombujok**
Fixes #9614 (among other things)

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 1]
```diff
@@ -161,6 +150,14 @@ public void remove() {
 
     @Override
     public int size() {
-        return setSmallest.size();
+        if (size == -1) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: this could be problematic performance-wise. as it's used during evaluation. I see you have some sort of caching, but I am not sure about possible consequences. what's the worst (performance) case you can imagine here?

File: hazelcast/src/test/java/com/hazelcast/query/impl/OrResultSetTest.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+
+        OrResultSet resultSet = new OrResultSet(indexedResults);
+
+        int sizeMethod = resultSet.size();
+        int sizeIterator = 0;
+        for (QueryableEntry queryableEntry : resultSet) {
+            sizeIterator++;
+        }
+
+        assertEquals(sizeIterator, 2 * size);
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/query/impl/OrResultSetTest.java]: I think this should be `assertEquals(2 * size, sizeIterator);`, since the order is `expected` then `actual` value. Same for the next assertion.

File: hazelcast/src/test/java/com/hazelcast/query/impl/OrResultSetTest.java [hunk 3]
```diff
@@ -0,0 +1,109 @@
...
+        public Data getKeyData() {
+            return null;
+        }
+
+        @Override
+        public Data getValueData() {
+            return null;
+        }
+    }
+
```
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/query/impl/OrResultSetTest.java]: Unnecessary newline here, but there is a newline missing at the end of the file :)

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 4]
```diff
@@ -103,7 +92,7 @@ public boolean hasNext() {
                 return true;
             }
 
-            for (; it.hasNext();) {
+            for (; it.hasNext(); ) {
```
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: True

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 5]
```diff
@@ -161,6 +150,14 @@ public void remove() {
...
+        if (size == -1) {
+            int calculatedSize = 0;
+            for (Iterator<QueryableEntry> it = iterator(); it.hasNext(); it.next()) {
+                calculatedSize++;
+            }
+            size = calculatedSize;
+        }
+        return size;
     }
+
```
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: I like it so :)

File: hazelcast/src/test/java/com/hazelcast/query/impl/OrResultSetTest.java (hunk 2 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/query/impl/OrResultSetTest.java]: True, fixed

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java (hunk 1 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: It's just iterating over the set once, then it's cached. The only place where it's used instantiated is here:
https://github.com/tombujok/hazelcast/blob/c2472d25552d6ad830858365cc142ef73b4c4a41/hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java#L99-L99

What do you mean precisely when you say that it's used during evaluation.

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: You were right. I've identified edge cases where the overhead of the size() method was significant (i.e. slowing down the query 5x times). 
Fixed.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 6]
```diff
@@ -161,6 +150,28 @@ public void remove() {
...
+            }
+            size = calculatedSize;
+        }
+        return size;
+    }
+
+    /**
+     * @return returns estimated size without calculating the full result set in full-result scan.
+     */
+    public int estimatedSize() {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: does it have to be public?

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: Yes, it unfortunately does, but the users get the result as the top-level Set interface

File: hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java [hunk 7]
```diff
@@ -99,6 +100,16 @@ public Predicate accept(Visitor visitor, Indexes indexes) {
         return new AndResultSet(smallestIndexedResult, otherIndexedResults, lsNoIndexPredicates);
     }
 
+    private int size(Set<QueryableEntry> result) {
+        // In case of AndResultSet and OrResultSet calling size() may be very expensive so quickerEstimated() size is used
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java]: `quickerEstimated()` does not exist.

File: hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java [hunk 8]
```diff
@@ -99,6 +100,16 @@ public Predicate accept(Visitor visitor, Indexes indexes) {
...
+        if (result instanceof AndResultSet) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java]: the question is whether to create an interface `WithSizeEstimator` or something. probably an overkill.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 9]
```diff
@@ -28,37 +28,26 @@
...
     private final List<Set<QueryableEntry>> otherIndexedResults;
     private final List<Predicate> lsNoIndexPredicates;
+    private int size;
 
     public AndResultSet(Set<QueryableEntry> setSmallest, List<Set<QueryableEntry>> otherIndexedResults,
                         List<Predicate> lsNoIndexPredicates) {
         this.setSmallest = isNotNull(setSmallest, "setSmallest");
         this.otherIndexedResults = otherIndexedResults;
         this.lsNoIndexPredicates = lsNoIndexPredicates;
+        this.size = -1;
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: `cachedSize` ?

File: hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java (hunk 8 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java]: I was thinking about it, but kind of it's just two classes. But thanks for the hint.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java (hunk 9 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: Fixed

File: hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java (hunk 7 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/predicates/AndPredicate.java]: Fixed.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 10]
```diff
@@ -28,37 +28,26 @@
...
     }
 
     public byte[] toByteArray(ObjectDataOutput out) throws IOException {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: I can't see where this `toByteArray()` method is used.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 11]
```diff
@@ -28,37 +28,26 @@
...
 
     public AndResultSet(Set<QueryableEntry> setSmallest, List<Set<QueryableEntry>> otherIndexedResults,
                         List<Predicate> lsNoIndexPredicates) {
         this.setSmallest = isNotNull(setSmallest, "setSmallest");
         this.otherIndexedResults = otherIndexedResults;
         this.lsNoIndexPredicates = lsNoIndexPredicates;
+        this.cachedSize = -1;
     }
 
     public byte[] toByteArray(ObjectDataOutput out) throws IOException {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: what was the need for this `toByteArray` method?

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 12]
```diff
@@ -28,37 +28,26 @@
...
     private final List<Set<QueryableEntry>> otherIndexedResults;
     private final List<Predicate> lsNoIndexPredicates;
+    private int cachedSize;
 
     public AndResultSet(Set<QueryableEntry> setSmallest, List<Set<QueryableEntry>> otherIndexedResults,
                         List<Predicate> lsNoIndexPredicates) {
         this.setSmallest = isNotNull(setSmallest, "setSmallest");
         this.otherIndexedResults = otherIndexedResults;
         this.lsNoIndexPredicates = lsNoIndexPredicates;
+        this.cachedSize = -1;
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: using a static final variable instead of `-1` can increase readability.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java (hunk 11 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: That's a good hint. First I thought it overrides a method in higher-levelled interface. Now I see it's not used.
Should we delete it? Wdyt also @jerrinot @mdogan?

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java (hunk 12 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: Thx. Fixed.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java (hunk 11 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: I reckon it was originally meant to be used for serialization? I can see the method was removed from `OrResultSet` [quite some time ago](https://github.com/jerrinot/hazelcast/commit/ee3455b2c8c256df86b2917ef8e7af0c6292df5b#diff-773b532d77d82620bf8102c731d1f76bL31).

I would just remove it from `AndResultSet` (In a PR into master only)

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java [hunk 13]
```diff
@@ -161,6 +153,28 @@ public void remove() {
...
+            }
+            cachedSize = calculatedSize;
+        }
+        return cachedSize;
     }
+
+    /**
+     * @return returns estimated size without calculating the full result set in full-result scan.
+     */
+    public int estimatedSize() {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: if `estimatedSize()` is called on this result set before `size() `,  is there a possibility that returned value from `size()` is wrong because of the _size-caching_?

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: Good question, but the answer is `no` since the `estimatedSize()` won't cache anything.
It uses the `cachedSize` if it is initialized (since it delivers the most accurate result), but if there's no `cachedSize` it will return an estimated size without caching it anywhere.

**Comment by tombujok** [comment]
@ahmetmircik toByteArray removed.

File: hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java (hunk 13 above)
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/query/impl/AndResultSet.java]: i see now, thanks
