### PR TITLE
fixes #5229. ClientDelegationFuture is implemented.

### LINKED ISSUE #5212: [TEST-FAILURE] ClientMapNearCacheTest Failures
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-sonar/changes
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3090/console
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/3091/testReport/
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/538/

### LINKED ISSUE #5229: New Client GetAsync Fails with a NegativeArraySizeException
```
        Hazelcast.newHazelcastInstance();
        IMap map = client.getMap("map");

        int size = 100;
        for (int i = 0; i < size; i++) {
            map.put(i, i);
        }
        for (int i = 0; i < size; i++) {
            Future f = map.getAsync(i);
            f.get();
        }
```

### PR DESCRIPTION
**Pull request by sancar**
fixes #5212

### CODE REVIEW

**Comment by sancar** [comment]
Also fixes #5212.

**Comment by gurbuzali** [comment]
will this also fix https://github.com/hazelcast/hazelcast/issues/5229 ?

File: hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java [hunk 1]
```diff
@@ -0,0 +1,203 @@
...
+            if (error instanceof CancellationException) {
+                throw (CancellationException) error;
+            }
+            if (error instanceof InterruptedException) {
+                throw (InterruptedException) error;
+            }
+            // should not happen!
+            throw new ExecutionException(error);
+        }
+        return getResult();
```
Comment (mdogan) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java]: Doesn't this mean, each time you call `future.get()`, value is deserialized?

**Comment by sancar** [comment]
@gurbuzali  Yes, as it is says in the title. :)

File: hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java (hunk 1 above)
Comment (sancar) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java]: Yes, it will be. I did not cache the deserialized object. I could not change this one because I need to pass data to an internal call back(one expecting data as response) . And to do that I ended up with implementing an unnecessary deserialize and serialize back to data.

Comment (sancar) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java]: @mdogan After a second look , I updated the ClientDelegatingFuture.

File: hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java [hunk 2]
```diff
@@ -0,0 +1,202 @@
...
+import com.hazelcast.nio.serialization.SerializationService;
+import com.hazelcast.util.ExceptionUtil;
+
+import java.util.concurrent.CancellationException;
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.Executor;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+
+public class ClientDelegatingFuture<FutureValue> implements ICompletableFuture<FutureValue> {
```
Comment (mdogan) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java]: Can you rename `FutureValue` to a single capital letter like `V`? It makes reading code harder..

Comment (mdogan) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java]: It looks like a class name in the code.

File: hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java [hunk 3]
```diff
@@ -0,0 +1,202 @@
...
+
+    protected void setDone() {
+        this.done = true;
+    }
+
+    protected ClientInvocationFuture getFuture() {
+        return future;
+    }
+
+    class DelegatingExecutionCallback<CallbackValue> implements ExecutionCallback<ClientMessage> {
```
Comment (mdogan) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/util/ClientDelegatingFuture.java]: same here for `CallbackValue`.
