### PR TITLE
Peel exceptions before rethrowing from ReliableTopic.publish

### LINKED ISSUE #9960: topic com.hazelcast.core.HazelcastException: Failed to publish message: wrapping com.hazelcast.core.OperationTimeoutException
using version 3.8

running multi tests in parallel, lots of thread, lots of structures, some async puts, get's,  lots of load,  so the timeOutException is expected

`com.hazelcast.core.HazelcastException`  
is wrapping 
`java.util.concurrent.ExecutionException` 
which is wrapping 
`com.hazelcast.core.OperationTimeoutException`

```
at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.publish(ReliableTopicProxy.java:172)
    at hzcmd.topic.Publisher.timeStep(Publisher.java:13)
    at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:53)
    at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:40)
    at remote.bench.BenchThread.call(BenchThread.java:38)
    at remote.bench.BenchThread.call(BenchThread.java:12)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: AddOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2017-02-22 08:56:33.975. Start time: 2017-02-22 08:54:54.936. Total elapsed time: 99039 ms. Invocation{op=com.hazelcast.ringbuffer.impl.operations.AddOperation{serviceName='hz:impl:ringbufferService', identityHash=2084149414, partitionId=54, replicaIndex=0, callId=-9838688, invocationTime=1487746494936 (2017-02-22 08:54:54.936), waitTimeout=-1, callTimeout=60000, name=_hz_rb_topicA_topic}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1487746494936, firstInvocationTime='2017-02-22 08:54:54.936', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[10.212.1.117]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.newOperationTimeoutException(InvocationFuture.java:151)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:99)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
    at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
    at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.addWithBackoff(ReliableTopicProxy.java:190)
    at com.hazelcast.topic.impl.reliable.ReliableTopicProxy.publish(ReliableTopicProxy.java:162)
    ... 11 more
Caused by: com.hazelcast.core.OperationTimeoutException: AddOperation got rejected before execution due to not starting within the operation-call-timeout of: 60000 ms. Current time: 2017-02-22 08:56:33.975. Start time: 2017-02-22 08:54:54.936. Total elapsed time: 99039 ms. Invocation{op=com.hazelcast.ringbuffer.impl.operations.AddOperation{serviceName='hz:impl:ringbufferService', identityHash=2084149414, partitionId=54, replicaIndex=0, callId=-9838688, invocationTime=1487746494936 (2017-02-22 08:54:54.936), waitTimeout=-1, callTimeout=60000, name=_hz_rb_topicA_topic}, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1487746494936, firstInvocationTime='2017-02-22 08:54:54.936', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 02:00:00.000', target=[10.212.1.117]:5701, pendingResponse={VOID}, backupsAcksExpected=0, backupsAcksReceived=0, connection=null}
    ... 17 more
```

@vbekiaris 
I see it’s deep in the invocation system; I ‘ll take a look a bit later to see if we can peel the `ExecutionException` and throw the original cause or we need to wrap it as-is

### PR DESCRIPTION
**Pull request by vbekiaris**
Also adds a `peel` method variant in `ExceptionUtil` to provide a custom message when wrapping with a `HazelcastException`.

Fixes #9960

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableTopicProxy.java [hunk 1]
```diff
@@ -114,10 +114,9 @@ public void publish(E payload) {
                 default:
                     throw new IllegalArgumentException("Unknown overloadPolicy:" + overloadPolicy);
             }
-        } catch (RuntimeException e) {
-            throw e;
         } catch (Exception e) {
```
Comment (vbekiaris) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientReliableTopicProxy.java]: The code in `try` block above may throw a `RuntimeException` or an `ExecutionException` wrapping the cause, so `peel`ing it will rethrow one of:
- the `RuntimeException` itself
- the cause of `ExecutionException`, when that is an instance of `RuntimeException`
- a `HazelcastException` wrapping a non-`RuntimeException`

With the previous `catch` block, any non-`RuntimeException` would be thrown wrapped in a `HazelcastException`, resulting in the `HazelcastException`->`ExecutionException`->actual exception wrapping observed in #9960

File: hazelcast/src/main/java/com/hazelcast/util/ExceptionUtil.java [hunk 2]
```diff
@@ -53,6 +53,31 @@ public static RuntimeException peel(final Throwable t) {
...
+    }
+
+    /**
+     * May peel {@code Throwable t} to return a {@code Throwable} that is of {@code allowedType}, according to
+     * the following rules:
+     * <ul>
+     *     <li>If {@code Throwable t} is a {@code RuntimeException}, returns {@code t}.</li>
+     *     <li>If {@code t} is an instance of {@code ExecutionException} or {@code InvocationTargetException},
+     *     then return the result of recursively peeling its non-null {@code t.getCause()}. Otherwise if
+     *     {@code t.getCause()} is null throw a new {@code HazelcastException} that wraps {@code t}.</li>
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/util/ExceptionUtil.java]: `throw a new {@code HazelcastException}` -> `return a new...`

File: hazelcast/src/main/java/com/hazelcast/util/ExceptionUtil.java [hunk 3]
```diff
@@ -53,6 +53,31 @@ public static RuntimeException peel(final Throwable t) {
     }
 
     public static <T extends Throwable> Throwable peel(final Throwable t, Class<T> allowedType) {
+        return peel(t, allowedType, null);
+    }
+
+    /**
+     * May peel {@code Throwable t} to return a {@code Throwable} that is of {@code allowedType}, according to
+     * the following rules:
+     * <ul>
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/util/ExceptionUtil.java]: When writing some javadoc for migrations I found that writing the pseudocode in the javadoc tends to be brittle :
- sometimes it makes the javadoc harder to read than the actual code
- when the code changes the javadoc always must change as well

I was trying to make the javadoc as clear as possible about the general method use but without going into the details. I'm not saying this needs to be changed but I needed to check the code to understand what the javadoc was saying. What do you think?

Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/util/ExceptionUtil.java]: Thanks, amended the description.
