### PR TITLE
Copy Nearcacheconfig when it needs to be changed

### LINKED ISSUE #17952: NearCache eviction config differs when a client is recreated with the same ClientFailoverConfig
In version 4.0.2, when a client is recreated with the same ClientFailoverConfig after creating a map that has default nearCache eviction configuration the following exception is seen;

```
Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: Alternative config with cluster name DIGITALBANK_STO03 has a different config than the initial config with cluster name DIGITALBANK_STO02 for nearCache
	at com.hazelcast.client.impl.clientside.FailoverClientConfigSupport.throwInvalidConfigurationException(FailoverClientConfigSupport.java:110)
	at com.hazelcast.client.impl.clientside.FailoverClientConfigSupport.checkValidAlternative(FailoverClientConfigSupport.java:144)
	at com.hazelcast.client.impl.clientside.FailoverClientConfigSupport.checkValidAlternative(FailoverClientConfigSupport.java:104)
	at com.hazelcast.client.impl.clientside.FailoverClientConfigSupport.resolveClientFailoverConfig(FailoverClientConfigSupport.java:65)
	at com.hazelcast.client.HazelcastClient.newHazelcastFailoverClient(HazelcastClient.java:188)
	at com.support.hazelcast.Client1.main(Client1.java:44)
```

https://github.com/hazelcast/hazelcast/blob/v4.0.2/hazelcast/src/main/java/com/hazelcast/config/NearCacheConfigAccessor.java

**To Reproduce**

1. Create a client with HazelcastClient.newHazelcastFailoverClient(clientFailoverConfig);
2. client.getMap any map that has default nearCache eviction config
3. create another client with the same clientFailoverConfig

Zendesk ticket reference; https://hazelcast.zendesk.com/agent/tickets/6862

### PR DESCRIPTION
**Pull request by sancar**
This reverts commit 8df8a6ebd1a43c42dd3ae86d223b0d3b5fd51606.

Copies NearcacheConfig and EvictionConfig when they needs
to be changed by NearcacheConfigAccessor so that the object
on ClientConfig/Config does not change when used.

fixes  #17952
fixes https://github.com/hazelcast/hazelcast-enterprise/issues/3966

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/config/NearCacheConfigAccessorTest.java [hunk 1]
```diff
@@ -24,7 +24,7 @@
 import org.junit.experimental.categories.Category;
 import org.junit.runner.RunWith;
 
-import static org.junit.Assert.assertEquals;
+import static groovy.util.GroovyTestCase.assertEquals;
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/config/NearCacheConfigAccessorTest.java:27]: It would be good to use `org.junit.Assert.assertEquals` instead of this

File: hazelcast/src/test/java/com/hazelcast/config/NearCacheConfigAccessorTest.java [hunk 2]
```diff
@@ -36,27 +36,16 @@ public void testConstructor() {
     }
 
     @Test
-    public void testInitDefaultMaxSizeForOnHeapMaps_whenNull_thenDoNothing() {
-        NearCacheConfigAccessor.initDefaultMaxSizeForOnHeapMaps(null);
+    public void testCopyInitDefaultMaxSizeForOnHeapMaps_whenNull_thenDoNothing() {
```
Comment (mdumandag) [inline hazelcast/src/test/java/com/hazelcast/config/NearCacheConfigAccessorTest.java:39]: Can you also add a test that, when the size is configured, we are not copying the near cache config?

File: hazelcast/src/main/java/com/hazelcast/config/EvictionConfig.java [hunk 3]
```diff
@@ -66,19 +66,24 @@
...
+    protected EvictionPolicy evictionPolicy = DEFAULT_EVICTION_POLICY;
+
+    protected String comparatorClassName;
+    protected EvictionPolicyComparator comparator;
+
+    /**
+     * Used by the {@link NearCacheConfigAccessor} to
+     * initialize the proper default value for on-heap maps.
+     */
+    boolean sizeConfigured;
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/config/EvictionConfig.java:80]: if `sizeConfigured` was set to `true`, after deserialization what keeps it still `true`?

File: hazelcast/src/main/java/com/hazelcast/config/NearCacheConfigAccessor.java [hunk 4]
```diff
@@ -28,14 +28,19 @@
...
 
         EvictionConfig evictionConfig = nearCacheConfig.getEvictionConfig();
-        if (nearCacheConfig.getInMemoryFormat() != InMemoryFormat.NATIVE) {
-            evictionConfig.defaultSize = MapConfig.DEFAULT_MAX_SIZE;
+        if (nearCacheConfig.getInMemoryFormat() != InMemoryFormat.NATIVE && !evictionConfig.sizeConfigured) {
+            EvictionConfig copyEvictionConfig = new EvictionConfig(evictionConfig);
+            copyEvictionConfig.setSize(MapConfig.DEFAULT_MAX_SIZE);
+            NearCacheConfig copyNearCacheConfig = new NearCacheConfig(nearCacheConfig);
+            copyNearCacheConfig.setEvictionConfig(copyEvictionConfig);
+            return copyNearCacheConfig;
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/config/NearCacheConfigAccessor.java:42]: minor: maybe a cosmetic change to increase readability:
```suggestion
        public static NearCacheConfig copyWithInitializedDefaultMaxSizeForOnHeapMaps(NearCacheConfig nearCacheConfig) {
        if (nearCacheConfig == null) {
            return null;
        }

        EvictionConfig evictionConfig = nearCacheConfig.getEvictionConfig();
        if (nearCacheConfig.getInMemoryFormat() == InMemoryFormat.NATIVE
                || evictionConfig.sizeConfigured) {
            return nearCacheConfig;
        }

        // create copy of eviction config
        EvictionConfig copyEvictionConfig = new EvictionConfig(evictionConfig)
                .setSize(MapConfig.DEFAULT_MAX_SIZE);

        // create copy of nearCache config and set eviction config
        return new NearCacheConfig(nearCacheConfig)
                .setEvictionConfig(copyEvictionConfig);
    }
```

File: hazelcast/src/main/java/com/hazelcast/config/EvictionConfig.java (hunk 3 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/config/EvictionConfig.java:80]: I have reverted the EvictionConfig behaviour. So it seems that setting sizeConfigured on deserialization was not necessary. For the sake of keeping it backward compatible, I will not touch this. Lets consider if that is necessary as a separate fix if needed.

Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/config/EvictionConfig.java:80]: thanks, i see this is an existing issue, not introduced in this PR. Created an issue for it: https://github.com/hazelcast/hazelcast/issues/18354

**Review by ahmetmircik — APPROVED** [review]

**Review by mdumandag — APPROVED** [review]
