### PR TITLE
Fixes default cache manager tests ClientCachingProviderTest

### LINKED ISSUE #12115: ClientCachingProviderTest failures
Failing [tests in recent builds](
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-freestyle/1495/#showFailuresLink):
```
com.hazelcast.client.cache.ClientCachingProviderTest.whenDefaultCacheManager_thenSharedNameHazelcastInstanceExists
com.hazelcast.client.cache.ClientCachingProviderTest.whenDefaultCacheManager_withUnnamedDefaultInstance_thenNoSharedNameHazelcastInstanceExists
```

with:

```
javax.cache.CacheException: Error opening URI [hazelcast]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:130)
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:159)
	at com.hazelcast.cache.HazelcastCachingProvider.getCacheManager(HazelcastCachingProvider.java:174)
	at com.hazelcast.cache.CachingProviderTest.whenDefaultCacheManager_thenSharedNameHazelcastInstanceExists(CachingProviderTest.java:228)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:105)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:97)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalStateException: Unable to connect to any address! The following addresses were tried: [[127.0.0.1]:5703, [127.0.0.1]:5702, [127.0.0.1]:5701]
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.connectToClusterInternal(ClientConnectionManagerImpl.java:875)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl.access$1500(ClientConnectionManagerImpl.java:102)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:885)
	at com.hazelcast.client.connection.nio.ClientConnectionManagerImpl$3.call(ClientConnectionManagerImpl.java:881)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```

### PR DESCRIPTION
**Pull request by vbekiaris**
Initial cleanup in default cache manager tests was shutting down the `HazelcastInstance` member started in `@Before` method, thus client-side default `CacheManager` tests would fail..

Fixes #12115

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientCachingProviderTest.java [hunk 1]
```diff
@@ -62,8 +65,6 @@ public void setup() {
             throw new AssertionError("Could not construct named hazelcast client instance: " +
                     e.getMessage());
         }
-        instances.add(instance1);
```
Comment (vbekiaris) [inline hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientCachingProviderTest.java]: `instance1` and `instance2` have already been added to `instances` in `createHazelcastInstance` method.

File: hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientCachingProviderTest.java [hunk 2]
```diff
@@ -91,6 +92,17 @@ protected void assertInstanceStarted(String instanceName) {
...
 
+    @Override
+    protected Collection<HazelcastInstance> getStartedInstances() {
+        return HazelcastClient.getAllHazelcastClients();
+    }
+
+    @Override
+    protected void cleanupForDefaultCacheManagerTest() {
+        clearSystemProperties();
+        clearCachingProviderRegistry();
```
Comment (vbekiaris) [inline hazelcast-client/src/test/java/com/hazelcast/client/cache/ClientCachingProviderTest.java]: For the client-side cleanup before the tests for default `CacheManager`, just cleanup the `CachingProvider` registry and system properties; do not shutdown the `HazelcastInstance` member started in `@Before`.

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run
