### PR TITLE
Eliminate ProxyService and rely on EventService [HZ-1920]

### LINKED ISSUE #18381: ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode [HZ-1920]
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4229/testReport/junit/com.hazelcast.client.map/ClientMapPartitionLostListenerTest/test_mapPartitionLostListener_invoked_fromOtherNode/

Error Message
```
There is no proxy with name 9897e763-2d64-4143-87bf-dd81ec2be5b2 created (yet)
Stacktrace
java.lang.AssertionError: There is no proxy with name 9897e763-2d64-4143-87bf-dd81ec2be5b2 created (yet)
	at org.junit.Assert.fail(Assert.java:89)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest$2.run(ClientMapPartitionLostListenerTest.java:172)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.assertProxyExistsEventually(ClientMapPartitionLostListenerTest.java:163)
	at com.hazelcast.client.map.ClientMapPartitionLostListenerTest.test_mapPartitionLostListener_invoked_fromOtherNode(ClientMapPartitionLostListenerTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

The test failure is not related to `PartitionLostListener`. 

A proxy created by the client is not propagated to the all the members within 2 minutes. 
Logs did not reveal much but this issue reminds of a similar one with event service registrations which is fixed by PreJoinOperations and invokeOnStableCluster here https://github.com/hazelcast/hazelcast/pull/11520
It might worth to investigate proxy creation and replication mechanism from the same perspective.

### PR DESCRIPTION
**Pull request by arodionov**
While registering listeners we don’t check proxy existence but rely on proxy existence during publishing.
The current fix removes this dependency and relies on `EventService`.

This PR is a separate fix for the https://github.com/hazelcast/hazelcast/issues/18381, but does not fix the problem with the "lost" proxy on another member.

Fixes #18381

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forward ports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by ahmetmircik** [comment]
Also this PR is a backportable fix.

**Review by ahmetmircik — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java [hunk 1]
```diff
@@ -36,26 +35,25 @@ class MapPartitionAwareService implements PartitionAwareService {
...
+        this.eventService = (EventServiceImpl) this.nodeEngine.getEventService();
     }
 
     @Override
     public void onPartitionLost(IPartitionLostEvent partitionLostEvent) {
         final Address thisAddress = nodeEngine.getThisAddress();
         final int partitionId = partitionLostEvent.getPartitionId();
 
-        Collection<DistributedObject> result = proxyService.getDistributedObjects(MapService.SERVICE_NAME);
+        EventServiceSegment eventServiceSegment = eventService.getSegment(MapService.SERVICE_NAME, false);
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java:51]: I see that this method can return null. Can this be a problem for us?

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java:51]: Yes, I will add a check and some logging for this case.
Thanks!

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java [hunk 2]
```diff
@@ -36,26 +36,31 @@ class MapPartitionAwareService implements PartitionAwareService {
...
         final int partitionId = partitionLostEvent.getPartitionId();
 
-        Collection<DistributedObject> result = proxyService.getDistributedObjects(MapService.SERVICE_NAME);
-
-        for (DistributedObject object : result) {
-            final MapProxyImpl mapProxy = (MapProxyImpl) object;
-            final String mapName = mapProxy.getName();
+        EventServiceSegment eventServiceSegment = eventService.getSegment(MapService.SERVICE_NAME, false);
+        if (eventServiceSegment == null) {
+            logger.warning("No service registration found for " + MapService.SERVICE_NAME);
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java:56]: Do we need this log? I assume this code will be run no matter whether a partition lost listener is added or not. (The onPartitionLost method, through the InternalPartitionLostEventPublisher). And, if the user hasn't added any listeners to any of the maps yet, or not using the map at all we will hit this line. 

I believe it can confuse the user. I am in favor of removing it, what do you think?

**Comment by ramizdundar** [comment]
Is https://github.com/hazelcast/hazelcast/pull/22942 also going to be merged, since we have this PR now?

**Review by ramizdundar — APPROVED** [review]

**Comment by arodionov** [comment]
> Is #22942 also going to be merged, since we have this PR now?

Yes, since there are other test failures with proxy replication

File: hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java (hunk 2 above)
Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/map/impl/MapPartitionAwareService.java]: Yes, you are right. Makes sense!
Thanks!

**Review by mdumandag — APPROVED** [review]

**Comment by arodionov** [comment]
Thanks, everybody for the review comments and suggestions!
