### PR TITLE
Additional information in case of thread local leak test failure

### LINKED ISSUE #14178: JavaXCacheDependencyClientTest.createHazelcastInstance
_master_ (commit ddc5d0f8df8d1d3aac02f5e3caf40be9ff0253ae)

Failed on nightly build : https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/285/testReport/junit/classloading/JavaXCacheDependencyClientTest/createHazelcastInstance/

Stacktrace : 

```
java.lang.AssertionError: Application created a ThreadLocal with key of type [com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$1] (value [com.hazelcast.client.spi.impl.ClientResponseHandlerSupplier$1@2bcb3313]) and a value of type [com.hazelcast.util.MutableInteger] (value [com.hazelcast.util.MutableInteger@2725e0bf) but failed to remove it when the application was stopped.
	at org.junit.Assert.fail(Assert.java:88)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalMapForLeaks(ThreadLocalLeakTestUtils.java:173)
	at classloading.ThreadLocalLeakTestUtils.checkThreadLocalsForLeaks(ThreadLocalLeakTestUtils.java:71)
	at classloading.AbstractJavaXCacheDependencyTest.createHazelcastInstance(AbstractJavaXCacheDependencyTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:98)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by vbekiaris**
Adds thread name & type to failure message, along with hints
for known issues.

Closes #14178 
Rationale behind this PR: https://github.com/hazelcast/hazelcast/issues/14178#issuecomment-446170840

### CODE REVIEW

File: hazelcast/src/test/java/classloading/ThreadLocalLeakTestUtils.java [hunk 1]
```diff
@@ -231,4 +236,27 @@ private static boolean loadedByThisOrChild(Object o, ClassLoader cl) {
...
+    private static String describeThread(Thread thread) {
+        return format("[%s] of type [%s]", thread.getName(), getPrettyClassName(thread.getClass()));
+    }
+
+    // enhance message with information about known thread locals issues
+    private static String checkKnownIssues(String message, Thread thread, Object key) {
+        if (thread != null && key != null) {
+            String threadClassName = getPrettyClassName(thread.getClass());
+            String keyClassName = getPrettyClassName(key.getClass());
+            if (threadClassName.equals("com.hazelcast.internal.networking.nio.NioThread")
```
Comment (vbekiaris) [inline hazelcast/src/test/java/classloading/ThreadLocalLeakTestUtils.java]: Hazelcast is started with a `FilteringClassLoader` so an `instanceof` check will fail here.
