### PR TITLE
Fix for java gzip compression

### LINKED ISSUE #12104: Java serialization compression bug
We have a bug when following configuration is applied. 
```
SerializationConfig.setEnableCompression(true);
```
Since GZipInputStream read more bytes than it needs, the fields coming after a compressed data is not able to read. 
Following reproduces the issue:
```
 @Test
    public void testCompression_withArrayList() {
        DefaultSerializationServiceBuilder defaultSerializationServiceBuilder = new DefaultSerializationServiceBuilder();
        SerializationService ss = defaultSerializationServiceBuilder.setEnableCompression(true).build();

        ArrayList<SampleSerializable> expected = new ArrayList<SampleSerializable>();
        for (int i = 0; i < 10; i++) {
            expected.add(new SampleSerializable(i));
        }
        Data data = ss.toData(expected);
        ArrayList<SampleSerializable> result = ss.toObject(data);

        assertEquals(expected, result);
    }
```

If any of our internal operations or users use `ObjectDataOutput.writeObject(x)` with a java serializable,  issue appears. 

A fix is available as follows but requires one more copy when writing the object. Also relies on an internal value( Gzip Header Size ). 
https://github.com/hazelcast/hazelcast/pull/12099

One more suggestion is that we could completely remove `compression` feature. Arguments for that:
1. We will remove the bug. 
2. `compression` is often misunderstood. We have seen that users expects that all data is compressed when it is used. But It only applies to Java Serializable's. 
3. Java Serializable is not used much by our users. They either their own serialization methods or ours (Portable/IdentifiedDataSerializable).

### PR DESCRIPTION
**Pull request by sancar**
Gzip compression reads bytes ahead. That was causing serialization
bugs when more data available after a object serialized with
compression enabled.

As fix, we are rewinding the stream to correct position so that
next data in the stream can be read correctly.
Thanks @jerrinot for the fix.

fixes hazelcast/hazelcast-enterprise#1750
fixes #12104

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java [hunk 1]
```diff
@@ -220,6 +230,9 @@ public Object read(final ObjectDataInput in) throws IOException {
                 } else {
                     result = objectInputStream.readUnshared();
                 }
+                if (gzipEnabled) {
+                    gZipInputStream.pushBackUnconsumedBytes(in);
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: do you have to pass the `in`? it's already passed in the constructor, isnt it?

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java [hunk 2]
```diff
@@ -290,4 +303,30 @@ public void destroy() {
...
+    private static class ExtendedGZipInputStream extends GZIPInputStream {
+
+        static final int GZIP_TRAILER_SIZE = 8;
+
+        ExtendedGZipInputStream(InputStream in) throws IOException {
+            super(in);
+        }
+
+        /**
+         * Gzip input stream reads more bytes in the stream than it actually needs.
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: nitpick - `s/reads/consumes`.

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java (hunk 1 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: Ohh. right. I missed that.

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java [hunk 3]
```diff
@@ -290,4 +303,30 @@ public void destroy() {
     private JavaDefaultSerializers() {
     }
 
+    /**
+     * Utility class to access internal inflater of GZIPInputStream
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: the JavaDoc is obsolete. it's not a utility class anymore.

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java [hunk 4]
```diff
@@ -67,12 +69,17 @@ public Externalizable read(final ObjectDataInput in) throws IOException {
                 final Externalizable ds = ClassLoaderUtil.newInstance(in.getClassLoader(), className);
                 final ObjectInputStream objectInputStream;
                 final InputStream inputStream = (InputStream) in;
+                ExtendedGZipInputStream gZipInputStream = null;
                 if (gzipEnabled) {
-                    objectInputStream = newObjectInputStream(in.getClassLoader(), new GZIPInputStream(inputStream));
+                    gZipInputStream = new ExtendedGZipInputStream(inputStream);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: Seems not a side effect of this PR but shouldn't we close `gZipInputStream`? Remembered this one: http://www.evanjones.ca/java-native-leak-bug.html

Comment (jerrinot) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: that would also close the inner stream and that's not what we want. but this line should prevent the leak: https://github.com/hazelcast/hazelcast/pull/12099/files#diff-47cd284d0b603ce35aad0b8ffea162d5R327

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java [hunk 5]
```diff
@@ -290,4 +303,29 @@ public void destroy() {
...
+        }
+
+        private void pushBackUnconsumedBytes() {
+            int remaining = inf.getRemaining();
+            BufferObjectDataInput baodi = (BufferObjectDataInput) in;
+            int position = baodi.position();
+            int rewindBack = max(0, remaining - ExtendedGZipInputStream.GZIP_TRAILER_SIZE);
+            int newPosition = position - rewindBack;
+            baodi.position(newPosition);
+            inf.end();
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/JavaDefaultSerializers.java]: maybe a comment here would be nice.

**Comment by sancar** [comment]
run-lab-run
