### PR TITLE
Fix ScheduledFutureProxy partition & member listener leak

### LINKED ISSUE #11221: [scheduled-executor] Registration objects causing memory leak while using ScheduledExecutor
I originally posted this question on [stackoverflow](https://stackoverflow.com/questions/45862782/hazelcast-registration-objects-causing-memory-leak-while-using-scheduledexecutor).

We are using Hazelcast (version 3.8.2) ScheduledExecutor to perform tasks in a cluster. We have a memory issue. 

[Zabbix memory graph - OLD GC Usage](https://i.stack.imgur.com/4kEkJ.png)

Profiling was done, and we realized that the leak is happening in EventServiceSegment for registration maps. It's all for .partitionLost events. Or, well, majority.

[Yourkit memory profiling](https://i.stack.imgur.com/ESs3u.png)

We know about disposing finished future, and here's our code that is performed on each instance periodically.

```
final long futureDisposed = service.getAllScheduledFutures().values().stream().flatMap(Collection::stream)
            .filter(future -> future.getStats().getTotalRuns() > 0).peek(IScheduledFuture::dispose).count();
final long futuresLeft = service.getAllScheduledFutures().values().stream().flatMap(Collection::stream).count();
```

What we get when logging those values is okay, correct number of tasks is disposed, and correct number of tasks remains scheduled. At the moment of this heap dump, futuresLeft logged ~2500 scheduled futures as left in the system. But the memory is still growing.

Our tasks get generated in batches of hundreds, then get scheduled for same delay. The tasks are implementing Runnable, Serializable and HazelcastInstanceAware. We also have transient references to some objects we pick up from userContext of HazelcastInstance.

Scheduling is done as:
```
this.scheduler = instance.getScheduledExecutorService(schedulerName);
this.scheduler.schedule(new Task(taskId), delay, TimeUnit.MILLISECONDS);
```

When tasks are executed, they might get rescheduled, and then we create a new object (previously we would schedule same objects back, but then we changed it, hoping it would help, but it didn't).

Scheduler is configured with durability 1 and poolSize of 2.

I've went through code, googled whatever keyword I could find, but nothing helped. I can see that these registrations are supposed to be cleaned when calling dispose, but they are not.

How to properly clean this registrations map when tasks are finished?

### PR DESCRIPTION
**Pull request by tkountis**
When creating a ScheduledFutureProxy it listens for partition & member loss events.
These listeners only get unregistered when the Future at hand, is disposed. However,
lots of use-cases demonstrate that the original Future is ignored. Instead, calls to
scheduler.getAllScheduled() are utilized to fetch all running tasks, and dispose the
finished ones. This, creates even more proxy objects, all following the same practise,
registering themselves as listeners, therefore they can't be garbage collected.

This patch, introduces a middle-man who acts as the sole & universal listener for those
events, the service itself, and all FutureProxy objects, are weakly referred from within
this class.

The contract of the ScheduledFutureProxy has changed to reflect j.u.c.FutureTask which
uses reference-equality. This also allows the weak reference collection to work as designed.

Fix #11221 

Heap dump shows no leaks after 10mins of continuous scheduling, after which, no leftover instances are observed. 

**Note:** This change makes the ScheduledExecutorService listener on partition & member loss
events. This is regardless if its in use or not.

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientScheduledFutureProxy.java [hunk 1]
```diff
@@ -63,7 +63,7 @@
 
     private ScheduledTaskHandler handler;
 
-    public ClientScheduledFutureProxy(ScheduledTaskHandler handler, ClientContext context) {
+    ClientScheduledFutureProxy(ScheduledTaskHandler handler, ClientContext context) {
```
Comment (mmedenjak) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientScheduledFutureProxy.java]: So the `ClientScheduledFutureProxy` does not offer this kind of best-effort mechanism for notifying of partition and member loss?

File: hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java [hunk 2]
```diff
@@ -183,4 +219,62 @@ private void resetPartitionOrMemberBinContainer(String name) {
...
+
+    private void unRegisterPartitionListenerIfExists() {
+        if (this.partitionLostRegistration == null) {
+            return;
+        }
+
+        try {
+            getNodeEngine().getPartitionService().removePartitionLostListener(this.partitionLostRegistration);
+        } catch (Exception ex) {
+            if (peel(ex, HazelcastInstanceNotActiveException.class, null)
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java]: I think you might get away with not having this hack by getting a reference to the partition service when constructing the `DistributedScheduledExecutorService`. But sometimes that's not possible as well if the partition service is not available at that moment.

File: hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java [hunk 3]
```diff
@@ -283,7 +283,7 @@ public IScheduledFuture schedule(Runnable command, long delay, TimeUnit unit) {
     public IScheduledFuture<?> getScheduledFuture(ScheduledTaskHandler handler) {
         checkNotNull(handler, "Handler is null");
 
-        ScheduledFutureProxy proxy = new ScheduledFutureProxy(handler);
+        ScheduledFutureProxy proxy = new ScheduledFutureProxy(handler, this);
```
[the remark this answers is not in the document]
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledExecutorServiceProxy.java]: 👍

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientScheduledFutureProxy.java (hunk 1 above)
Comment (tkountis) [reply hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientScheduledFutureProxy.java]: Never did. I originally added this to server side only with plans to add it to client too. However, after seeing that this might have been a bad idea, i don't want to support it there too. Lets see if this fix proves to be solid in production, and we might reconsider this decision.

File: hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java (hunk 2 above)
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/DistributedScheduledExecutorService.java]: Getting the reference isn't the problem, doing the action is. It executes some operations internally, which trigger the exception.

File: hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledFutureProxy.java [hunk 4]
```diff
@@ -179,72 +166,37 @@ public void dispose() {
...
-
-    @Override
-    public boolean equals(Object o) {
-        if (this == o) {
-            return true;
-        }
-        if (o == null || getClass() != o.getClass()) {
-            return false;
+    void notifyMemberLost(MembershipEvent event) {
+        if (handler == null) {
```
[the remark this answers is not in the document]
Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/scheduledexecutor/impl/ScheduledFutureProxy.java]: Good catch!

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by iwittenberg** [comment]
Any chance of getting this merged into a 3.8.x release?  Running into issues directly caused from this.

**Comment by tkountis** [comment]
@iwittenberg there you go https://github.com/hazelcast/hazelcast/pull/11327
