### PR TITLE
Fix NPE in ChangeRecordImpl when old or new value is null

### LINKED ISSUE #22446: [CDC] NPE in ChangeRecordImpl#hashCode for INSERT/SYNC operations
**Describe the bug**

hashCode method in ChangeRecordImpl uses .toJson() method on oldValue/newValue fields but for SYNC/INSERT operations the oldValue is nullable.
Example on screenshot:
image

Logs:
```
Caused by: java.lang.NullPointerException
	at com.hazelcast.jet.cdc.impl.ChangeRecordImpl.hashCode(ChangeRecordImpl.java:183) ~[classes/:?]
	at com.hazelcast.jet.core.Partitioner.lambda$static$7a6ef289$1(Partitioner.java:70) ~[classes/:?]
	at com.hazelcast.jet.core.Edge$KeyPartitioner.getPartition(Edge.java:818) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.OutboundCollector$Partitioned.offer(OutboundCollector.java:198) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.OutboxImpl.doOffer(OutboxImpl.java:255) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.OutboxImpl.offerInternal(OutboxImpl.java:142) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.OutboxImpl.offer(OutboxImpl.java:99) ~[classes/:?]
	at com.hazelcast.jet.core.AbstractProcessor.tryEmit(AbstractProcessor.java:309) ~[classes/:?]
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:408) ~[classes/:?]
	at com.hazelcast.jet.core.AbstractProcessor.emitFromTraverser(AbstractProcessor.java:421) ~[classes/:?]
	at com.hazelcast.jet.cdc.impl.CdcSourceP.complete(CdcSourceP.java:189) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[classes/:?]

```
**Expected behavior**
hashCode method should be null-safe (for oldValue and newValue)

**To Reproduce**

1. Go to 'com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest'
2. Replace current pipeline definition for mysyql method with:
```
           Pipeline pipeline = Pipeline.create();
            StreamSource<ChangeRecord> source = mySqlSource(container);
            pipeline.readFrom(source)
                    .withNativeTimestamps(1)
                    .setLocalParallelism(1)
                    .window(SlidingWindowDefinition.sliding(SECONDS.toMillis(2), SECONDS.toMillis(1)))
                    .distinct()
                    .writeTo(Sinks.logger(WindowResult::toString));
```
3. Above pipeline will throw NPE due to nullable "oldValue for SYNC entries"

**Additional context**
Found during testing on 5.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by TomaszGaweda**
Use NPE-proof Objects.hashCode

Fixes #22446

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] Send backports/forwardports if fix needs to be applied to past/future releases
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
run-lab-run

**Review by frant-hartm — APPROVED** [review]

**Review by ldziedziul — APPROVED** [review]

File: extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java [hunk 1]
```diff
@@ -194,10 +189,10 @@ public boolean equals(Object obj) {
...
         }
         ChangeRecordImpl that = (ChangeRecordImpl) obj;
-        return this.sequenceSource == that.sequenceSource &&
-                this.sequenceValue == that.sequenceValue &&
-                this.keyJson.equals(that.keyJson) &&
-                Objects.equals(this.oldValue, that.oldValue) &&
-                Objects.equals(this.newValue, that.newValue);
+        return this.sequenceSource == that.sequenceSource
+                && this.sequenceValue == that.sequenceValue
+                && this.keyJson.equals(that.keyJson)
```
Comment (orcunc) [inline extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java:194]: I think it is better if Objects.equals() is used for keyJson, timestamp, database etc. fields too. Basically for all fields  that are not primitive.
Objects.equals() handles reference equality and null conditions

Comment (TomaszGaweda) [reply extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/ChangeRecordImpl.java]: a3087854fd3ffbfd5737c7022e3289b8d18c5c88 + 113e5f9db076157cb010ddbac375c07498a58da1
