### PR TITLE
Mongo improvements [HZ-2237]

### LINKED ISSUE #24167: Mongo Connector improvements  [HZ-2237]
Group issue of improvements for Mongo Connector:
1.  Improve logs messages - currently from the client side error is:
```
java.lang.NullPointerException: unable to connect to Mongo
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947)
	at com.hazelcast.jet.Job.join(Job.java:80)
	at com.mycompany.simple.hz.app.Main.main(Main.java:53)
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{09a2-21ad-f1c0-0001/abc#0}: java.lang.NullPointerException: unable to connect to Mongo
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80)
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: unable to connect to Mongo
	at com.hazelcast.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
	at com.hazelcast.jet.mongodb.impl.ReadMongoP$StreamMongoReader.nextChunkTraverser(ReadMongoP.java:433)
```

but from the sever it was:
```
023-03-31 14:01:28,215 [ WARN] [hz.festive_darwin.jet.blocking.thread-1] [.h.j.m.i.ReadMongoP]: [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] [09a2-21ad-f1c0-0001/abc#1] Could not connect to MongoDB
com.mongodb.MongoCommandException: Command failed with error 40573 (Location40573): 'The $changeStream stage is only supported on replica sets' on server localhost:27017. The full response is {"ok": 0.0, "errmsg": "The $changeStream stage is only supported on replica sets", "code": 40573, "codeName": "Location40573"}
        at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:205) ~[hazelcast-jet-mongodb-5.3.0-SNAPSHOT.jar:?]
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:443) ~[hazelcast-jet-mongodb-5.3.0-SNAPSHOT.jar:?]
```

We should propagate this kind of errors from server to the client. Error `"unable to connect to Mongo"` hides real problem which can be fixed by someone who will see `"The $changeStream stage is only supported on replica sets"`.

2. There is no check if collection already exists for the source.
3. "name" param for MongoSinks is redundant - you san use pipeline API to name your sink like:
```
.writeTo(mongodb(dataLinkRef("mongoDB"), defaultDatabase(), testName.getMethodName()))
.setName(SINK_NAME)
```

### PR DESCRIPTION
**Pull request by TomaszGaweda**
1. Source and sink checks if database/collection exists
2. Exceptions will not be "eaten" by MongoConnection, but throw as a cause
3. Only transient exceptions will cause retry, not all types
4. Better back-pressure handling - waiting some configured time.
5. Name is not mandatory in sources/sinks

Fixes #24167

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

File: extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java [hunk 1]
```diff
@@ -140,4 +144,23 @@ public static LocalDateTime bsonTimestampToLocalDateTime(@Nullable BsonTimestamp
...
+    static void checkCollectionExists(MongoDatabase database, String collectionName) {
+        for (String name : database.listCollectionNames()) {
+            if (name.equals(collectionName)) {
+                return;
+            }
+        }
+        throw new JetException("Collection " + collectionName + " in database " + database.getName() + " does not exist");
+    }
+
+    static void checkDatabaseExists(MongoClient client, String databaseName) {
```
Comment (orcunc) [inline extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java:157]: database names are case insensitive. compare like that

File: extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java [hunk 2]
```diff
@@ -140,4 +144,23 @@ public static LocalDateTime bsonTimestampToLocalDateTime(@Nullable BsonTimestamp
                             .withZoneSameInstant(systemDefault())
                             .toLocalDateTime();
     }
+
+    static void checkCollectionExists(MongoDatabase database, String collectionName) {
```
Comment (orcunc) [inline extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java:148]: checkXXXOrFail kind of method names are easier to understand that it throws exception. It is up to you

File: extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/ReadMongoParams.java
Comment (orcunc) [inline extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/ReadMongoParams.java:1]: List<Bson> aggregates = new ArrayList<>(); is not serializable but ReadMongoParams is serializable. You need to mark this field as transient or remove Serializable from ReadMongoParams . Otherwise it will create serialization problems in the future

File: extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSinkResilienceTest.java
Comment (orcunc) [inline extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSinkResilienceTest.java:1]: Line# 160. Close the directClient in try block
`MongoClient directClient = MongoClients.create(connectionString);`

File: extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceResilienceTest.java
Comment (orcunc) [inline extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceResilienceTest.java:1]: Line # 88 this is not used

@Rule
 public TestName testName = new TestName();

File: extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java (hunk 2 above)
Comment (ldziedziul) [reply extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java:148]: maybe `assertCollectionExists`

Comment (ldziedziul) [reply extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java:148]: maybe `assertCollectionExists`

File: extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceTest.java
Comment (orcunc) [inline extensions/mongodb/src/test/java/com/hazelcast/jet/mongodb/MongoSourceTest.java:1]: If batchFilters method you don't need to use fluent interface. You can just change the parameter like below. Up to you
```
 if (filter) {
   sourceBuilder.filter(gte("key", FILTERED_BOUND));
 }
```

**Review by orcunc — CHANGES_REQUESTED** [review]
Please see my comments

File: extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/MongoSources.java [hunk 3]
```diff
@@ -142,13 +134,13 @@ public static MongoSourceBuilder.Batch<Document> batch(
...
     @Nonnull
     public static BatchSource<Document> batch(
-            @Nonnull String name,
             @Nonnull String connectionString,
             @Nonnull String database,
             @Nonnull String collection,
             @Nullable Bson filter,
             @Nullable Bson projection
     ) {
+        String name = "MongoSource(" + database + "/" + collection + ")";
```
Comment (ldziedziul) [inline extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/MongoSources.java:143]: Maybe extract it to a method `name(database, collection)`

**Review by ldziedziul — APPROVED** [review]
Looks good, just address things from other reviews

File: extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java (hunk 2 above)
Comment (TomaszGaweda) [reply extensions/mongodb/src/main/java/com/hazelcast/jet/mongodb/impl/MongoUtilities.java:148]: I think it's a common thing that `checkX` methods fail. `assert` is good also, but more test-related IMHO

**Comment by TomaszGaweda** [comment]
All updated @orcunc

**Review by orcunc — APPROVED** [review]
