### PR TITLE
Fixes MapListener addition issue via EntryListenerConfig 

### LINKED ISSUE #5648: Not possible to add MapClearedListener to EntryListenerConfig as an implementation

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes #5648 

Fixed two issues: first one is addition of a MapListener impl. via EntryListenerConfig object and second one is a left-over which prevents setting of instance to HazelcastInstanceAware listeners

### CODE REVIEW

**Comment by ahmetmircik** [comment]
verify

**Comment by gurbuzali** [comment]
:+1:

File: hazelcast/src/test/java/com/hazelcast/map/EntryListenerConfigTest.java [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+import org.junit.runner.RunWith;
+
+import java.util.concurrent.atomic.AtomicBoolean;
+import java.util.concurrent.atomic.AtomicInteger;
+
+import static org.junit.Assert.assertEquals;
+import static org.junit.Assert.assertTrue;
+
+/**
+ * Keep this test serial. It relays on static shared variables.
```
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/map/EntryListenerConfigTest.java]: Why don't you convert statics to instance variables and use parallel testing?

Comment (ahmetmircik) [inline hazelcast/src/test/java/com/hazelcast/map/EntryListenerConfigTest.java]: Because i am creating a new listener from the class-name and want to reference to a field of that new instance in order to count fired events.

Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/map/EntryListenerConfigTest.java]: I see. what about using some reflection magic to access internal listener instance? Is it worth it?

Comment (ahmetmircik) [inline hazelcast/src/test/java/com/hazelcast/map/EntryListenerConfigTest.java]: current approach seems simple to me.

**Comment by mdogan** [comment]
:+1:
