### PR TITLE
Do not rethrow exceptions cached in futures in ProxyRegistry.destroy()

### LINKED ISSUE #12470: ProxyManager won't remove Proxy even after original distributed object destroyed.
This seems to be a bug.

ProxyManager won't remove Proxy even after original distributed object destroyed.
This caused memory leak after long time such as 1 month.

The only removing event happens when hazelcast client instance call the getDistributedObjects function.
https://github.com/hazelcast/hazelcast/blob/e0ea8ed98b3c30d4e8a03d38fc6fd9c6bca57574/hazelcast-client/src/main/java/com/hazelcast/client/impl/HazelcastClientInstanceImpl.java#L661

To avoid memory leak we had to call getDistributedObjects function in distributedObjectDestroyed event in our program.

### LINKED ISSUE #12480: CacheBasicServerTest
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14013

com.hazelcast.cache.CacheBasicServerTest.cacheManagerOfCache_cannotBeOverwritten
```
com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
	at com.hazelcast.spi.AbstractDistributedObject.throwNotActiveException(AbstractDistributedObject.java:105)
	at com.hazelcast.spi.AbstractDistributedObject.lifecycleCheck(AbstractDistributedObject.java:100)
	at com.hazelcast.spi.AbstractDistributedObject.getNodeEngine(AbstractDistributedObject.java:94)
	at com.hazelcast.cache.impl.CacheProxy.<init>(CacheProxy.java:88)
	at com.hazelcast.cache.impl.AbstractCacheService.createDistributedObject(AbstractCacheService.java:225)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.doCreateProxy(ProxyRegistry.java:191)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyRegistry.createProxy(ProxyRegistry.java:184)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:240)
	at com.hazelcast.spi.impl.proxyservice.impl.ProxyServiceImpl.dispatchEvent(ProxyServiceImpl.java:64)
	at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:61)
	at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:43)
	at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:226)
	at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:209)
```

com.hazelcast.cache.CacheBasicServerTest.com.hazelcast.cache.CacheBasicServerTest
```
java.lang.IllegalStateException: Instances haven't been shut down: [HazelcastInstance{name='_hzInstance_39_dev', node=[127.0.0.1]:5039}, HazelcastInstance{name='_hzInstance_40_dev', node=[127.0.0.1]:5040}]
	at com.hazelcast.test.AbstractHazelcastClassRunner$3.evaluate(AbstractHazelcastClassRunner.java:342)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:108)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeLazy(JUnitCoreWrapper.java:89)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:58)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:144)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

### PR DESCRIPTION
**Pull request by blazember**
Exceptions cached in `DistributedObjectFuture`s are rethrown on the shutdown thread from `ProxyRegistry.destroy()`, which aborts shutdown procedure abruptly, potentially leading to resource leaking. These exceptions should not be rethrown to ensure proper shutdown.

Fixes #12480 #12516 https://github.com/hazelcast/hazelcast/issues/12589

### CODE REVIEW

**Comment by blazember** [comment]
run-lab-run

**Comment by blazember** [comment]
run-lab-run

**Comment by blazember** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java [hunk 1]
```diff
@@ -262,11 +263,26 @@ void destroy() {
...
+            invalidate(distributedObject);
         }
         proxies.clear();
     }
+
+    private DistributedObject extractDistributedObject(DistributedObjectFuture future) {
+        try {
+            return future.get();
+        } catch (Throwable ex) {
+            EmptyStatement.ignore(ex);
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java]: won't this eat the Interrupted flag when InterruptedException is thrown?

Comment (blazember) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java]: Good question. It won't because this future [doesn't throw InterruptedException](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/DistributedObjectFuture.java#L35) and the interrupted flag is not cleared. 

Another question though is what happens if that `future.get()` meets with an interrupt without cached result or error. I'm taking a look.

Comment (blazember) [reply hazelcast/src/main/java/com/hazelcast/spi/impl/proxyservice/impl/ProxyRegistry.java]: `future.get()` doesn't handle interrupts correctly, created #12585 for this.

**Comment by blazember** [comment]
The last commit changed the description only to fix the typo in the referenced issues.
