### PR TITLE
Prevent OperationTimeoutException for long running user codes from client

### LINKED ISSUE #5555: Operation timeout behavior is different in client and in node when calling IMap.executeOnKey()
For v3.5:
When an executeOnKey() operation reaches `hazelcast.operation.call.timeout.millis`value (an example operation is sleeping inside a simple entryProcessor() ) :
Node side, it is asked if operation is still executing:
````
Jun 22, 2015 3:55:51 PM com.hazelcast.spi.impl.operationservice.impl.Invocation
WARNING: [192.168.2.37]:5701 [sertug] [3.5] No response for 4002 ms. InvocationFuture{invocation=Invocation{ serviceName='hz:impl:mapService', op=GetOperation{numbers}, partitionId=31, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=2000, target=Address[192.168.2.37]:5701, backupsExpected=0, backupsCompleted=0}, response=null, done=false}
Jun 22, 2015 3:55:51 PM com.hazelcast.spi.impl.operationservice.impl.Invocation
WARNING: [192.168.2.37]:5701 [sertug] [3.5] Asking if operation execution has been started: Invocation{ serviceName='hz:impl:mapService', op=GetOperation{numbers}, partitionId=31, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=2000, target=Address[192.168.2.37]:5701, backupsExpected=0, backupsCompleted=0}
Jun 22, 2015 3:55:51 PM com.hazelcast.spi.impl.operationservice.impl.Invocation
WARNING: [192.168.2.37]:5701 [sertug] [3.5] 'is-executing': true -> Invocation{ serviceName='hz:impl:mapService', op=GetOperation{numbers}, partitionId=31, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=2000, target=Address[192.168.2.37]:5701, backupsExpected=0, backupsCompleted=0}
```
But on the client side, operationTimeoutException is thrown:
````
Exception in thread "main" com.hazelcast.core.OperationTimeoutException: No response for 4000 ms. Aborting invocation! Invocation{ serviceName='hz:impl:mapService', op=EntryOperation{}, partitionId=31, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=2000, target=Address[192.168.2.37]:5701, backupsExpected=0, backupsCompleted=0} No response has been received!  backups-expected:0 backups-completed: 0
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.newOperationTimeoutException(Invocation.java:491)
	at com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService$IsOperationStillRunningCallback.setOperationTimeout(IsStillRunningService.java:224)
	at com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService$IsOperationStillRunningCallback.onResponse(IsStillRunningService.java:212)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture$1.run(InvocationFuture.java:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
	at ------ End remote and begin local stack-trace ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveResponse(ClientInvocationFuture.java:147)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:114)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.get(ClientInvocationFuture.java:89)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:130)
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnKey(ClientMapProxy.java:939)
	at TimeoutClient.main(TimeoutClient.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

### PR DESCRIPTION
**Pull request by sancar**
When client runnables get into operation thread, they publish
themselves as currentTask. Then, when they do invocation on same
thread with same partition id, they were not able to update current
task with new operation. Since InvocationStillRunning is checked
by published current task, the user code looked like finished
at the moment and gets operation timeout exception.
Fix enables client runnables to change currentTask with new
invocation operation.

Fixes #5555

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java [hunk 1]
```diff
@@ -131,7 +133,9 @@ public void run(Runnable task) {
     }
 
     private boolean publishCurrentTask() {
-        return (getPartitionId() != AD_HOC_PARTITION_ID && currentTask == null);
+        boolean isClientRunnable = currentTask instanceof MessageTask
```
Comment (gurbuzali) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java]: the problem with this approach is that when we introduce a new client runnable which gets executed by operation-runner then we will silently introduce this very same bug. We can say that with the new protocol things will not change that much but I think it is still a possibility. We need a general interface here for operation/client-message but that's not the subject of this PR

**Comment by gurbuzali** [comment]
:+1:

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java (hunk 1 above)
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java]: or does anybody know why `currentTask == null` is added/required? maybe we should just get rid of that check...

**Comment by sancar** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java (hunk 1 above)
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationservice/impl/OperationRunnerImpl.java]: @gurbuzali 
All client runnables has to be MessageTask in new protocol. And all old client requests are handled by single runnable class ClientPacketProcessor(which we will get rid of in 3.7 SNAPSHOT) . So in theory, there should not be a problem because of an addition of new client runnable.

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
verify

**Comment by sancar** [comment]
run-lab-run

**Comment by eminn** [comment]
:+1:
