### PR TITLE
Partition Group API now takes members as method argument

### LINKED ISSUE #18795: No way to get cluster members within DiscoveryStrategy.getPartitionGroupStrategy()
**Describe the bug**
In order to do anything useful in ` DiscoveryStrategy.getPartitionGroupStrategy()`, the method needs access
to current cluster members. Currently, there is no way to access the cluster members.
Partition Group API is useless because of this, and this is why this is a bug and not a feature.
API bug.

### PR DESCRIPTION
**Pull request by lprimak**
<PR description here>

Fixes #18795

Introduces new method that can be overridden so that cluster members are available to the implementing code.
This makes it possible to implement useful partitioning strategies.

I have taken great care here to preserve current functionality, so hopefully this can make it into 4.2.1 or 4.2.2 as opposed to having to wait all the way until 5.0

* API
New API introduced in `DiscoveryStrategy`: `PartitionGroupStrategy getPartitionGroupStrategy(Collection<? extends Member> allMembers)`
The older one with no arguments has been marked as deprecated.
I have made effort to make sure that the old API works as previously, and if the new API method is overridden then it will take precedence over the old one.

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Add `Add to Release Notes` label if changes should be mentioned in release notes or `Not Release Notes content` if changes are not relevant for release notes
- [ ] Request reviewers if possible
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by lprimak** [comment]
4.2.1!!! yay! thanks

**Comment by mmedenjak** [comment]
We'll see about that. I've added it to the milestone to take a look, but it's definitely in the wrong branch - `master` is the 5.0 release, https://github.com/hazelcast/hazelcast/tree/4.2.z are 4.2.z patch releases.

**Comment by lprimak** [comment]
I can cherry-pick :)

File: hazelcast/src/main/java/com/hazelcast/internal/partition/membergroup/SPIAwareMemberGroupFactory.java [hunk 1]
```diff
@@ -62,10 +63,13 @@ public SPIAwareMemberGroupFactory(DiscoveryService discoveryService) {
...
-                            Iterable<MemberGroup> spiGroupsIterator =
-                                    discoveryStrategy.getPartitionGroupStrategy().getMemberGroups();
-                            for (MemberGroup group : spiGroupsIterator) {
+                            PartitionGroupStrategy deprecatedGroupStrategy = discoveryStrategy.getPartitionGroupStrategy();
+                            checkNotNull(deprecatedGroupStrategy);
+                            PartitionGroupStrategy groupStrategy = discoveryStrategy.getPartitionGroupStrategy(allMembers);
+                            if (groupStrategy == null) {
+                                groupStrategy = deprecatedGroupStrategy;
+                            }
+                            for (MemberGroup group : groupStrategy.getMemberGroups()) {
```
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/internal/partition/membergroup/SPIAwareMemberGroupFactory.java:72]:
```suggestion
                            PartitionGroupStrategy groupStrategy = discoveryStrategy.getPartitionGroupStrategy(allMembers);
                            if (groupStrategy == null) {
                                groupStrategy = discoveryStrategy.getPartitionGroupStrategy();
                            }
                            checkNotNull(groupStrategy);
                            for (MemberGroup group : groupStrategy.getMemberGroups()) {
```

**Comment by ahmetmircik** [comment]
@lprimak could you please add test?

**Comment by lprimak** [comment]
@ahmetmircik I changed half the tests to point to the new method, and left half to point to the old one.
I am not sure what kind of other tests need to be made.

**Comment by lprimak** [comment]
@ahmetmircik many tests added

**Comment by lprimak** [comment]
@ihsandemir Thanks for the fantastic suggestion. Really clears up the logic there!

**Comment by vbekiaris** [comment]
run-lab-run

**Review by ahmetmircik — APPROVED** [review]

**Comment by ahmetmircik** [comment]
run-lab-run

**Review by ihsandemir — APPROVED** [review]
