### PR TITLE
Send PreJoin ops from joining to master in JoinRequest [HZ-1733]

### LINKED ISSUE #19988: com.hazelcast.internal.cluster.impl.BasicClusterStateTest.test_eventsDispatched_whenClusterState_PASSIVE
_master_ (commit f2583ff36d582805374d8751428f2b66b455b546)

Failed on Imb, JDK 8 : [test failure](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8/158/testReport/junit/com.hazelcast.internal.cluster.impl/BasicClusterStateTest/test_eventsDispatched_whenClusterState_PASSIVE/)

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.internal.cluster.impl.BasicClusterStateTest.lambda$test_eventsDispatched_whenClusterState_PASSIVE$0(BasicClusterStateTest.java:401)
	at com.hazelcast.internal.cluster.impl.BasicClusterStateTest$$Lambda$17994/0x0000000094373a40.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1260)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1362)
	at com.hazelcast.internal.cluster.impl.BasicClusterStateTest.test_eventsDispatched_whenClusterState_PASSIVE(BasicClusterStateTest.java:401)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: joinNotAllowed_whenClusterState_isFrozen in 0.954 seconds.
23:03:48,186 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,286 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,386 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,486 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,587 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,687 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,787 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,887 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:48,987 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,087 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,187 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,288 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,388 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,488 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,588 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,688 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,788 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,889 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:49,989 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,089 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,189 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,289 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,389 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,490 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,590 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,690 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,790 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,890 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:50,990 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,090 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,191 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,291 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,392 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,492 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,592 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,692 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,792 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,892 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:51,992 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,093 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,193 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,293 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,393 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,493 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,593 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,693 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,794 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,894 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:52,994 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,094 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,194 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,294 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,395 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,495 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,595 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,695 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,795 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,895 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:53,996 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,096 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,196 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,296 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,396 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,496 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,596 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,697 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,797 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,897 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:54,997 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,097 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,197 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,297 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,398 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,498 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,598 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,698 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,798 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,898 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:55,998 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,099 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,199 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,224 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,300 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,400 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,500 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,600 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,700 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,800 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:56,900 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,001 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,101 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,201 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,301 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,401 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,501 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,602 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,702 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,802 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:57,902 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,002 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,102 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,202 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,225 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,303 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,403 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,503 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,603 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,703 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,803 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:58,903 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,004 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,104 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,204 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,304 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,404 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,504 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,604 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,705 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,805 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:03:59,905 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,005 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,105 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,205 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,225 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,306 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,406 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,506 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,606 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,706 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,806 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:00,907 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,007 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,107 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,207 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,307 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,407 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,508 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,608 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,708 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,808 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:01,908 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,008 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,108 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,209 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,225 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,309 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,409 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,509 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,609 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,709 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,809 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:02,910 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,010 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,110 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,210 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,310 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,410 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,510 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,610 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,711 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,811 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:03,911 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,011 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,111 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,211 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,225 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,311 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,411 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,512 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,612 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,712 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,812 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:04,912 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,012 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,112 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,212 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,313 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,413 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,513 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,613 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,713 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,813 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:05,913 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,014 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,114 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,214 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,225 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,314 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,414 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,514 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,614 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,714 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,815 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:06,915 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,015 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,115 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,215 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,315 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,415 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,515 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,615 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,716 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,816 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:07,916 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:08,016 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:08,116 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:08,216 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition.
23:04:08,225 DEBUG |test_eventsDispatched_whenClusterState_PASSIVE| - [JobCoordinationService] hz.upbeat_snyder.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Not starting jobs because cluster is in passive state or in transition
...[truncated 1654627 chars]...
nsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=183,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=194,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=260,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-0,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [metric=os.maxFileDescriptorCount]=120000
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-6,unit=count,metric=operation.thread.completedPacketCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.plannedMigrations]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-4,unit=count,metric=operation.thread.errorCount]=0
[upbeat_snyder] [23:05:46,178] [cooperativeWorker=4,unit=count,metric=iterationCount,module=jet]=1
[upbeat_snyder] [23:05:46,178] [partitionId=180,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=191,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-1,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=proxy.destroyedCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-5,unit=count,metric=operation.thread.completedPacketCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.operationTimeoutCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=transactions.rollbackCount]=0
[upbeat_snyder] [23:05:46,178] [metric=runtime.uptime]=3114682
[upbeat_snyder] [23:05:46,178] [unit=count,metric=raft.nodes]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-5,unit=count,metric=operation.thread.errorCount]=0
[upbeat_snyder] [23:05:46,178] [cooperativeWorker=3,unit=count,metric=iterationCount,module=jet]=1
[upbeat_snyder] [23:05:46,178] [partitionId=170,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=181,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=192,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-2,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.stateStamp]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.usedHeap]=1171281048
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-4,unit=count,metric=operation.thread.completedPacketCount]=0
[upbeat_snyder] [23:05:46,178] [metric=classloading.totalLoadedClassesCount]=105377
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-2,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=ns,metric=partitions.elapsedDestinationCommitTime]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-0,unit=count,metric=operation.thread.completedTotalCount]=2
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.genericQueueSize]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.replicaSyncSemaphore]=10
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-1,unit=count,metric=operation.thread.errorCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-3,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.genericThreadCount]=5
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.completedCount]=35
[upbeat_snyder] [23:05:46,178] [cooperativeWorker=2,unit=count,metric=iterationCount,module=jet]=1
[upbeat_snyder] [23:05:46,178] [partitionId=106,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=117,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=128,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=139,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=205,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=216,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=227,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=238,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=249,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=6,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.adhoc.executedOperationsCount]=4
[upbeat_snyder] [23:05:46,178] [metric=classloading.unloadedClassesCount]=5105
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-3,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [metric=os.committedVirtualMemorySize]=43876749312
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.migrationQueueSize]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedPacketCount]=23
[upbeat_snyder] [23:05:46,178] [unit=count,metric=event.threadCount]=5
[upbeat_snyder] [23:05:46,178] [unit=count,metric=jobs.submitted,module=jet]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-2,unit=count,metric=operation.thread.errorCount]=0
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=cluster.clock.maxClusterTimeDiff]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-2,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-7,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [cooperativeWorker=1,unit=count,metric=iterationCount,module=jet]=1
[upbeat_snyder] [23:05:46,178] [partitionId=107,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=118,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=129,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=206,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=217,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=228,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=239,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.committedHeap]=4294967296
[upbeat_snyder] [23:05:46,178] [unit=count,metric=raft.terminatedRaftNodeGroupIds]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.freeHeap]=3123686248
[upbeat_snyder] [23:05:46,178] [partitionId=5,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-4,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [metric=os.freePhysicalMemorySize]=199565647872
[upbeat_snyder] [23:05:46,178] [unit=count,metric=event.totalFailureCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-2,unit=count,metric=operation.thread.completedTotalCount]=3
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-3,unit=count,metric=operation.thread.errorCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-1,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-6,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [cooperativeWorker=0,unit=count,metric=iterationCount,module=jet]=1
[upbeat_snyder] [23:05:46,178] [partitionId=269,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=258,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=247,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=236,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=104,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=115,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=126,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=137,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=148,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=159,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=203,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=214,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=225,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=operation.invocations.invocationScanPeriodMillis]=1000
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.responses.backupCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=80,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=91,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=8,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-5,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=raft.metadata.activeMembersCommitIndex]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-1,unit=count,metric=operation.thread.completedTotalCount]=1
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.asyncOperations]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationBatchCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-5,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=259,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=248,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=105,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=116,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=127,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=138,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=149,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=204,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=215,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=226,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=237,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=90,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=7,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [service=hz:core:clusterService,unit=count,metric=event.publicationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.callTimeoutCount]=0
[upbeat_snyder] [23:05:46,178] [genericId=0,unit=count,metric=operation.generic.executedOperationsCount]=23
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-4,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=267,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=256,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=245,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=234,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=223,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=212,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=102,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=113,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=124,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=135,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=146,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=157,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=168,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=179,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=201,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=blockingWorkerCount,module=jet]=0
[upbeat_snyder] [23:05:46,178] [partitionId=2,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.responses.missingCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-3,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=raft.metadata.groups]=0
[upbeat_snyder] [23:05:46,178] [partitionId=268,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=257,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=246,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=235,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=224,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=103,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=114,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=125,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=136,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=147,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=158,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=169,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=202,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=213,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.retryCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=1,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.maxNative]=0
[upbeat_snyder] [23:05:46,178] [unit=percent,metric=operation.invocations.usedPercentage]=0.0
[upbeat_snyder] [23:05:46,178] [genericId=2,unit=count,metric=operation.generic.executedOperationsCount]=1
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-2,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-3,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [service=hz:core:proxyService,unit=count,metric=event.publicationCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=265,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=254,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=243,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=232,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=221,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=210,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=199,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=100,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=111,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=122,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=133,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=144,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=155,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=166,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=177,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=188,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=gc.unknownTime]=0
[upbeat_snyder] [23:05:46,178] [partitionId=4,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-1,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=cluster.clock.clusterUpTime]=119995
[upbeat_snyder] [23:05:46,178] [genericId=1,unit=count,metric=operation.generic.executedOperationsCount]=2
[upbeat_snyder] [23:05:46,178] [service=hz:core:clusterService,unit=count,metric=event.listenerCount]=1
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-0,unit=count,metric=operation.thread.errorCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.partitionThreadCount]=8
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-1,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [metric=thread.threadCount]=177
[upbeat_snyder] [23:05:46,178] [partitionId=266,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=255,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=244,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=233,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=222,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=211,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=200,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=101,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=112,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=123,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=134,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=145,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=156,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=167,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=178,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=189,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.partitionCount]=271
[upbeat_snyder] [23:05:46,178] [partitionId=3,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [service=hz:core:partitionService,unit=count,metric=event.publicationCount]=0
[upbeat_snyder] [23:05:46,178] [metric=thread.daemonThreadCount]=119
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.freeNative]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=cluster.size]=2
[upbeat_snyder] [23:05:46,178] [unit=count,metric=event.rejectedCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-1,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-4,unit=count,metric=operation.thread.completedRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-0,unit=count,metric=operation.thread.completedTotalCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=20,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=31,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=42,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=53,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=64,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=75,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=86,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=97,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [cooperativeWorker=0,unit=count,metric=taskletCount,module=jet]=0
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=cluster.clock.localClockTime]=1637967946175
[upbeat_snyder] [23:05:46,178] [dir=user.home,unit=bytes,metric=file.partition.freeSpace]=13935296512
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-2,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=gc.majorCount]=4
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-5,unit=count,metric=operation.thread.completedRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-1,unit=count,metric=operation.thread.completedTotalCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=30,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=41,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=52,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=63,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=74,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=85,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=96,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.priorityQueueSize]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=proxy.proxyCount]=1
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-6,unit=count,metric=operation.thread.completedRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=11,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=22,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=33,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=44,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=55,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=66,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=77,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=88,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=99,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.committedNative]=0
[upbeat_snyder] [23:05:46,178] [unit=ns,metric=partitions.elapsedMigrationOperationTime]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.genericPriorityQueueSize]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=gc.minorCount]=431
[upbeat_snyder] [23:05:46,178] [metric=os.freeSwapSpaceSize]=4294963200
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [metric=os.totalPhysicalMemorySize]=405449981952
[upbeat_snyder] [23:05:46,178] [metric=os.systemCpuLoad]=3.3649943985398174
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-7,unit=count,metric=operation.thread.completedRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [metric=runtime.availableProcessors]=8
[upbeat_snyder] [23:05:46,178] [partitionId=10,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=21,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=32,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=43,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=54,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=65,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=76,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=87,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=98,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-6,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=gc.unknownCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.responseQueueSize]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.maxMetadata]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.parker.totalParkedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.localPartitionCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=209,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-4,unit=count,metric=operation.thread.completedTotalCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=60,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=71,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=82,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=93,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.generic-operation.thread-0,unit=count,metric=operation.thread.completedRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-7,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.invocations.lastCallId]=17
[upbeat_snyder] [23:05:46,178] [unit=count,metric=transactions.commitCount]=1
[upbeat_snyder] [23:05:46,178] [unit=count,metric=raft.destroyedGroupIds]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.activePartitionCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-5,unit=count,metric=operation.thread.completedTotalCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=70,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=81,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=92,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=9,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [service=hz:core:partitionService,unit=count,metric=event.listenerCount]=6
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.invocations.pending]=0
[upbeat_snyder] [23:05:46,178] [unit=bytes,metric=memory.usedNative]=0
[upbeat_snyder] [23:05:46,178] [dir=user.home,unit=bytes,metric=file.partition.totalSpace]=21460156416
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=cluster.clock.clusterStartTime]=1637967826180
[upbeat_snyder] [23:05:46,178] [unit=ms,metric=cluster.clock.clusterTime]=1637967946176
[upbeat_snyder] [23:05:46,178] [partitionId=108,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=119,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=207,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=218,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=229,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [dir=user.home,unit=bytes,metric=file.partition.usableSpace]=13935296512
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-2,unit=count,metric=operation.thread.completedTotalCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=40,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=51,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=62,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=73,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=84,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=95,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.invocations.normalTimeouts]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=raft.metadata.activeMembers]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=operation.failedBackups]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.memberGroupsSize]=2
[upbeat_snyder] [23:05:46,178] [unit=count,metric=event.queueCapacity]=1000000
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedOperationCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=109,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=208,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=219,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [unit=count,metric=partitions.completedMigrations]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.partition-operation.thread-3,unit=count,metric=operation.thread.completedTotalCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=50,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=61,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=72,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=83,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [partitionId=94,unit=count,metric=operation.partition.executedOperationsCount]=0
[upbeat_snyder] [23:05:46,178] [thread=hz.upbeat_snyder.priority-generic-operation.thread-0,unit=count,metric=operation.thread.completedPartitionSpecificRunnableCount]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster,unit=count,metric=executor.internal.completedTasks]=26
[upbeat_snyder] [23:05:46,178] [name=hz:cluster,unit=count,metric=executor.internal.maximumPoolSize]=2
[upbeat_snyder] [23:05:46,178] [name=hz:cluster,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:event,unit=count,metric=executor.internal.completedTasks]=14
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:event,unit=count,metric=executor.internal.maximumPoolSize]=1
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:event,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:event,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:event,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled:cqc:24e80b48-23c0-481f-afc3-3851a7d0c5dd,unit=count,metric=executor.internal.completedTasks]=24
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled:cqc:24e80b48-23c0-481f-afc3-3851a7d0c5dd,unit=count,metric=executor.internal.maximumPoolSize]=1
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled:cqc:24e80b48-23c0-481f-afc3-3851a7d0c5dd,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled:cqc:24e80b48-23c0-481f-afc3-3851a7d0c5dd,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled:cqc:24e80b48-23c0-481f-afc3-3851a7d0c5dd,unit=count,metric=executor.internal.remainingQueueCapacity]=10000
[upbeat_snyder] [23:05:46,178] [name=jet:coordinator,unit=count,metric=executor.internal.completedTasks]=2
[upbeat_snyder] [23:05:46,178] [name=jet:coordinator,unit=count,metric=executor.internal.maximumPoolSize]=4
[upbeat_snyder] [23:05:46,178] [name=jet:coordinator,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=jet:coordinator,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=jet:coordinator,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:offloadable,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:offloadable,unit=count,metric=executor.internal.maximumPoolSize]=8
[upbeat_snyder] [23:05:46,178] [name=hz:offloadable,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:offloadable,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:offloadable,unit=count,metric=executor.internal.remainingQueueCapacity]=100000
[upbeat_snyder] [23:05:46,178] [name=hz:client,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client,unit=count,metric=executor.internal.maximumPoolSize]=8
[upbeat_snyder] [23:05:46,178] [name=hz:client,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:mastership,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:mastership,unit=count,metric=executor.internal.maximumPoolSize]=1
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:mastership,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:mastership,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:mastership,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:async,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:async,unit=count,metric=executor.internal.maximumPoolSize]=8
[upbeat_snyder] [23:05:46,178] [name=hz:async,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:async,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:async,unit=count,metric=executor.internal.remainingQueueCapacity]=100000
[upbeat_snyder] [23:05:46,178] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.maximumPoolSize]=160
[upbeat_snyder] [23:05:46,178] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client-blocking-tasks,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[upbeat_snyder] [23:05:46,178] [name=hz:mc,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:mc,unit=count,metric=executor.internal.maximumPoolSize]=2
[upbeat_snyder] [23:05:46,178] [name=hz:mc,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:mc,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:mc,unit=count,metric=executor.internal.remainingQueueCapacity]=2000
[upbeat_snyder] [23:05:46,178] [name=hz:client-query,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client-query,unit=count,metric=executor.internal.maximumPoolSize]=8
[upbeat_snyder] [23:05:46,178] [name=hz:client-query,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client-query,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:client-query,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled,unit=count,metric=executor.internal.completedTasks]=4767
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled,unit=count,metric=executor.internal.maximumPoolSize]=16
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled,unit=count,metric=executor.internal.poolSize]=2
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:scheduled,unit=count,metric=executor.internal.remainingQueueCapacity]=800000
[upbeat_snyder] [23:05:46,178] [name=hz:system,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:system,unit=count,metric=executor.internal.maximumPoolSize]=8
[upbeat_snyder] [23:05:46,178] [name=hz:system,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:system,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:system,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=MetricsPublisher,unit=count,metric=executor.internal.completedTasks]=119
[upbeat_snyder] [23:05:46,178] [name=MetricsPublisher,unit=count,metric=executor.internal.maximumPoolSize]=16
[upbeat_snyder] [23:05:46,178] [name=MetricsPublisher,unit=count,metric=executor.internal.poolSize]=1
[upbeat_snyder] [23:05:46,178] [name=MetricsPublisher,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=MetricsPublisher,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.maximumPoolSize]=2
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:splitbrain,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.maximumPoolSize]=1
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:cluster:version:auto:upgrade,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=jet:tasklet_initClose,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=jet:tasklet_initClose,unit=count,metric=executor.internal.maximumPoolSize]=8
[upbeat_snyder] [23:05:46,178] [name=jet:tasklet_initClose,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=jet:tasklet_initClose,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=jet:tasklet_initClose,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:query,unit=count,metric=executor.internal.completedTasks]=0
[upbeat_snyder] [23:05:46,178] [name=hz:query,unit=count,metric=executor.internal.maximumPoolSize]=16
[upbeat_snyder] [23:05:46,178] [name=hz:query,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:query,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:query,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.completedTasks]=122
[upbeat_snyder] [23:05:46,178] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.maximumPoolSize]=16
[upbeat_snyder] [23:05:46,178] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.poolSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.queueSize]=0
[upbeat_snyder] [23:05:46,178] [name=hz:CRDTReplicationMigration,unit=count,metric=executor.internal.remainingQueueCapacity]=2147483647
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalPutLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalSetLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalGetLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalRemoveLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalMaxPutLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalMaxSetLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalMaxGetLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.totalMaxRemoveLatency]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.lastAccessTime]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.lastUpdateTime]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.hits]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.numberOfOtherOperations]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.numberOfEvents]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.getCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.putCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.setCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.removeCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=ms,metric=map.creationTime]=1637964849983
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.ownedEntryCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.backupEntryCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=bytes,metric=map.ownedEntryMemoryCost]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=bytes,metric=map.backupEntryMemoryCost]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.heapCost]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.merkleTreesCost]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.lockedEntryCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.dirtyEntryCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.backupCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.queryCount]=0
[upbeat_snyder] [23:05:46,178] [name=e54c0de2-0ab7-476d-a20d-7fad1766656b,unit=count,metric=map.indexedQueryCount]=0
```

</details>

### PR DESCRIPTION
**Pull request by arodionov**
Make the PreJoin operation a part of `JoinRequest` to run it after authentication on the master, and remove it from the `FinalizeJoinOp`.

This should prevent "losing" proxy creation on secondary.
Details in the comment:  https://github.com/hazelcast/hazelcast/issues/18381#issuecomment-952843577
Based on unfinished PR https://github.com/hazelcast/hazelcast/pull/19859

Fixes #19988

Breaking changes (list specific methods/types/messages):
- Introduce a new parameter `OnJoinOp` in `JoinRequest`

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by vbekiaris** [comment]
run-ee-tests

**Comment by arodionov** [comment]
run-ee-tests

File: hazelcast/src/main/java/com/hazelcast/spi/impl/eventservice/impl/EventServiceImpl.java [hunk 1]
```diff
@@ -677,18 +676,9 @@ public void accept(Packet packet) {
 
     @Override
     public OnJoinRegistrationOperation getPreJoinOperation() {
-        // pre-join operations are only sent by master member
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/eventservice/impl/EventServiceImpl.java:680]: maybe keep this comment and add that specifically `EventService`'s pre-join op is also sent from joining member to master in `JoinRequest`?

**Review by vbekiaris — COMMENTED** [review]
looks good, added some minor comments

File: hazelcast/src/main/java/com/hazelcast/instance/impl/Node.java [hunk 2]
```diff
@@ -870,9 +872,11 @@ public JoinRequest createJoinRequest(Address remoteAddress) {
         MemberImpl localMember = getLocalMember();
         CPMemberInfo localCPMember = getLocalCPMember();
         UUID cpMemberUUID = localCPMember != null ? localCPMember.getUuid() : null;
+        Collection<Operation> preJoinOps = nodeEngine.getPreJoinOperations();
+        OnJoinOp onJoinOp = (preJoinOps != null && !preJoinOps.isEmpty()) ? new OnJoinOp(preJoinOps) : null;
```
[the remark this answers is not in the document]
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/instance/impl/Node.java]: Actually that's a leftover comment from previous review round :) 

For the record, my opinion is that we should only pick `EventService`'s pre-join op and send it to master in `JoinRequest` (as implemented in 3d71985146f597815509ab85a5cf6d7000b83e14). Gathering all pre-join ops seems wasteful: for most services a prejoin op before member is joined probably has nothing to add to master member (eg configuration service has no dynamically registered configs).

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/JoinRequest.java [hunk 3]
```diff
@@ -120,11 +128,11 @@ public void readData(ObjectDataInput in) throws IOException {
...
         this.addresses = readMap(in);
-        // RU_COMPAT 5.1
-        MemberVersion current = MemberVersion.of(VERSION_5_2_0);
+        cpMemberUUID = UUIDSerializationUtil.readUUID(in);
+        // RU_COMPAT 5.2
+        MemberVersion current = MemberVersion.of(VERSION_5_3_0);
         if (MemberVersion.MAJOR_MINOR_VERSION_COMPARATOR.compare(this.memberVersion, current) >= 0) {
-            // member is at least 5.2, we expect cpMemberUuid exists in the incoming packet
-            cpMemberUUID = UUIDSerializationUtil.readUUID(in);
+            preJoinOperation = in.readObject();
```
[the remark this answers is not in the document]
Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/JoinRequest.java:135]: Yes, I did. Also manually tested the rolling upgrade from 5.2 to 5.3 with different combinations.

File: hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/JoinRequestOp.java [hunk 4]
```diff
@@ -38,9 +42,24 @@ public JoinRequestOp(JoinRequest request) {
...
+        }
+
+        ClusterServiceImpl clusterService = getService();
+        NodeEngineImpl nodeEngine = clusterService.getNodeEngine();
+
+        preOp.setNodeEngine(nodeEngine);
+        OperationAccessor.setCallerAddress(preOp, getCallerAddress());
+        OperationAccessor.setConnection(preOp, getConnection());
+        preOp.setOperationResponseHandler(createEmptyResponseHandler());
+    }
```
Comment (ramizdundar) [inline hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/JoinRequestOp.java:61]: Is this required? There is also `OnJoinOp.beforeRun()`.

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/operations/JoinRequestOp.java:61]: Actually, the newly added test `testListenerRegistrationWhileANewMemberJoining` failed without it with:
```
java.lang.NullPointerException: null
	at com.hazelcast.internal.cluster.impl.operations.OnJoinOp.run(OnJoinOp.java:85) ~[classes/:?]
```

**Review by ramizdundar — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java [hunk 5]
```diff
@@ -735,6 +738,30 @@ public void noOperationExecuted_beforePreJoinOpIsDone() throws Exception {
...
+        Config masterConfig = getConfigWithService(new PostJoinAwareServiceImpl(latch), PostJoinAwareServiceImpl.SERVICE_NAME);
+        HazelcastInstance hz1 = factory.newHazelcastInstance(masterConfig);
+
+        Config joiningConfig = getConfigWithService(new PostJoinAwareServiceImpl(latch), PostJoinAwareServiceImpl.SERVICE_NAME);
+        EntryListenerConfig listenerConfig = new EntryListenerConfig();
+        CountDownLatch entryAddedLatch = new CountDownLatch(1);
+        listenerConfig.setImplementation((EntryAddedListener) event -> entryAddedLatch.countDown());
+        joiningConfig.getMapConfig("test").addEntryListenerConfig(listenerConfig);
+
+        factory.newHazelcastInstance(joiningConfig);
```
Comment (ahmetmircik) [inline hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java:754]: This test seems to have a wrong base because we always assume same config for all members when starting a cluster, otherwise it is possible to create such many failure cases.

**Comment by arodionov** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java (hunk 5 above)
Comment (arodionov) [reply hazelcast/src/test/java/com/hazelcast/internal/cluster/impl/MembershipUpdateTest.java]: Updated the test, thanks for the note!

File: hazelcast/src/main/java/com/hazelcast/spi/impl/eventservice/impl/EventServiceImpl.java [hunk 6]
```diff
@@ -677,18 +676,11 @@ public void accept(Packet packet) {
...
+        // EventService's pre-join operations are only sent by master member
+        // also EventService's pre-join op is sent from joining member to master in JoinRequest
         return getOnJoinRegistrationOperation();
     }
 
-    @Override
-    public Operation getPostJoinOperation() {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/eventservice/impl/EventServiceImpl.java:685]: Maybe it can be easier to see the issue if we keep this method and return null by explaining the problem as a comment inside method.

File: hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java [hunk 7]
```diff
@@ -763,8 +764,10 @@ void setMastershipClaimInProgress() {
 
     /**
      * Starts join process on master member.
+     *
+     * @param preJoinOperation
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java:768]:
```suggestion
     * @param preJoinOperation joining member's preJoinOperation, not master's
```

File: hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java [hunk 8]
```diff
@@ -788,6 +791,10 @@ private void startJoin() {
                     return;
                 }
 
+                if (preJoinOperation != null) {
+                    nodeEngine.getOperationService().run(preJoinOperation);
+                }
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterJoinManager.java:796]:
```suggestion
                OnJoinOp preJoinOp = preparePreJoinOps();

                if (preJoinOperation != null) {
                    nodeEngine.getOperationService().run(preJoinOperation);
                }
```

Seems it is possible to send joining member's listener-registrations back to it with `preparePreJoinOps`. The above calling order change suggestion is for this possibility.

**Review by ahmetmircik — APPROVED** [review]

**Comment by arodionov** [comment]
Thanks @vbekiaris, @ahmetmircik, and @ramizdundar for the review and suggestions!
