### PR TITLE
DelegatingFuture should deserialize value passed into ExecutionCallback if required

### LINKED ISSUE #5158: Value passed into ICompletableFuture.onResponse is not deserialized
Hazelcast Version: 3.4.2
If this is a feature of ICompletableFuture then perhaps the type should be changed to *Data* instead of generic?
The example below throws this exception:
```
java.lang.ClassCastException: com.hazelcast.nio.serialization.DefaultData cannot be cast to java.lang.String
	at TestCompletableFuture$1.onResponse(TestCompletableFuture.java:1)
	at com.hazelcast.spi.impl.BasicInvocationFuture$1.run(BasicInvocationFuture.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

```
		HazelcastInstance instance = Hazelcast.newHazelcastInstance();
		IMap<String, String> map = instance.getMap("map");
		map.set("key", "Some Value");
		ICompletableFuture<String> f = (ICompletableFuture<String>) map.getAsync("key");
		f.andThen(new ExecutionCallback<String>() {
			public void onResponse(String response) {
				System.out.println(response);
			}

			public void onFailure(Throwable t) {

			}
		});
		Hazelcast.shutdownAll();
```

### PR DESCRIPTION
**Pull request by mdogan**
- DelegatingFuture should deserialize value passed into ExecutionCallback if required.
- Added tests for DelegatingFuture and CompletedFuture.
- Fixes #5158

### CODE REVIEW

**Comment by gurbuzali** [comment]
:+1:

File: hazelcast/src/test/java/com/hazelcast/util/executor/CallerRunsExecutor.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.hazelcast.util.executor;
+
+import java.util.concurrent.Executor;
+
+class CallerRunsExecutor implements Executor {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/util/executor/CallerRunsExecutor.java]: Can you add a few lines of Javadoc?

**Comment by pveentjer** [comment]
Minor comments, but good to go.
