### PR TITLE
Change TaskletExecutionService Job Fail Logging Level on members

### LINKED ISSUE #19965: SQL query with LIMIT clause should not log at warn level
**Describe the bug**
Running SQL query with a limit clause results in a warning log on the member:

```
hazelcast-a_3   | 2021-11-19 10:11:57,495 [ WARN] [hz.sleepy_kepler.jet.cooperative.thread-8] [c.h.j.i.e.TaskletExecutionService]: [192.168.208.3]:5701 [hazelcast-a] [5.1-SNAPSHOT] Exception in ProcessorTasklet{0722-2a3b-25f1-0002/ClientSink#0}
hazelcast-a_3   | com.hazelcast.jet.sql.impl.QueryResultProducerImpl$ResultLimitReachedException: Done by reaching the item number in SQL LIMIT clause
```

**Expected behavior**
WARN level should be for states which are exceptional. The fact that LIMIT clause is implemented via `ResultLimitReachedException` is a detail and it should be logged at most on debug/trace level

### PR DESCRIPTION
**Pull request by yamanogluberk**
In case of a job fail, the user is already going to get the error in the job result or the sql result. By using 'FINE' level logging instead of the 'WARN' level, we can reduce the noise, because the job fail cause might not be an implementation error but an implementation detail like the `ResultLimitReachedException` used in the 'LIMIT' clause in an sql query(#19965). 

Suggested by @viliam-durina 
WDYT @hazelcast/core 

Fixes #19965 

Breaking changes (list specific methods/types/messages):

- Logging level in TaskletExecutionService when the job fails is changed from 'WARN' to 'FINE'

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [ ] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java [hunk 1]
```diff
@@ -396,7 +396,7 @@ private void runTasklet(TaskletTracker t) {
                     CancellationException ex = (CancellationException) e;
                     t.executionTracker.exception(ex);
                 } else {
-                    logger.warning("Exception in " + t.tasklet, e);
+                    logger.fine("Exception in " + t.tasklet, e);
```
Comment (frant-hartm) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:399]: If there is an exception, e.g. from `result = t.call();` do we get the whole stacktrace reported on the master? We have some issues with incomplete stacktraces, I am not sure if this is the case or it's something else.

If we have the full stacktrace, then I am fine with this change.

Alternatively we could have a special case for the `QueryResultSizeExceededException` similar to `CancellationException` above.

**Review by frant-hartm — CHANGES_REQUESTED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java (hunk 1 above)
Comment (yamanogluberk) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:399]: To me it feels a little wrong to add a special case for a specific job/implementation detail to here, because `CancellationException` is generic, a user can cancel any of the jobs, but 'QueryResultSizeExceededException' doesnt feel so generic, so if we were to add a special case I d suggest we add interfaces to exceptions that could occur in a job that denotes how they are logged, might be a little more generic. WDYT about this?

About the stack trace, I only changed the logging level, idk if that effects how the stacktrace is reported, but I will see and inform here how the stacktrace is reported.

Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:399]: Currently, there is 1 special case, we would add 2nd one. Let's wait for a 3rd before we try to create an abstraction for this.

> changed the logging level
yes, and after this change, we won't see the log on the member. This is desired for `QueryResultSizeExceededException` but for any other exception, this is interesting, so unless we are sure (I am not) that the exception is correctly propagated and logged on master I would keep it also on the member at warning level.

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:399]: Before, the default logging level was WARN and it was reduced to INFO for cancellation. Now the default is FINE, but is _increased_ for cancellation. That doesn't make sense.

But Frantisek's point is right. Users can have a plethora of causes for job failures. I think there are cases when the client doesn't receive the full stack trace, even though I was unable find such scenario. And I didn't look into non-java clients. So I think it makes sense to log on member with INFO level by default, and decrease the level to FINE for the two cases we know are normal: for cancellation and SqlLimitExc.

Comment (yamanogluberk) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:399]: @frant-hartm WDYT about the approach Viliam suggested?

Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java]: Fine with me.

**Review by frant-hartm — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java (hunk 1 above)
Comment (yamanogluberk) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java]: So I tried and on the Master node an Error message that occurred during the execution of a job is printed with a stacktrace even on INFO level. Thus, I believe it is okey to use INFO as the default level and FINE for cancellation and SqlLimitException for now.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/ResultLimitReachedException.java [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.hazelcast.sql.impl;
+
+public class ResultLimitReachedException extends Exception {
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/ResultLimitReachedException.java:19]:
```suggestion
/**
 * An exception used to cancel a job once the number of rows reaches the number
 * specified by the SQL LIMIT clause.
 */
public class ResultLimitReachedException extends Exception {
```

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java [hunk 3]
```diff
@@ -392,11 +393,15 @@ private void runTasklet(TaskletTracker t) {
...
             } catch (Throwable e) {
                 if (e instanceof CancellationException) {
-                    logger.info("Job was cancelled by the user.");
+                    logger.fine("Job was cancelled by the user.");
                     CancellationException ex = (CancellationException) e;
                     t.executionTracker.exception(ex);
+                } else if (e instanceof ResultLimitReachedException) {
+                    logger.fine("SQL LIMIT is reached. ");
+                    ResultLimitReachedException ex = (ResultLimitReachedException) e;
+                    t.executionTracker.exception(ex);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:402]:
```suggestion
                    t.executionTracker.exception(e);
```

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java [hunk 4]
```diff
@@ -392,11 +393,15 @@ private void runTasklet(TaskletTracker t) {
...
                 } else {
-                    logger.warning("Exception in " + t.tasklet, e);
+                    logger.info("Exception in " + t.tasklet, e);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:404]: We should do the same error handling for BlockingWorker. We can extract this code to a method and call it from there. Currently, the blocking worker logs in WARN level.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java (hunk 4 above)
Comment (yamanogluberk) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:404]: Do you mean we should check for the same exceptions there as well? Or just the logging level? @viliam-durina

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/execution/TaskletExecutionService.java:404]: Exceptions, same log level. In principle it should be the same, whether we're running as cooperative or blocking.

**Review by viliam-durina — APPROVED** [review]
