### PR TITLE
Assert index eventually has some data in MapIndexLifecycleTest

### LINKED ISSUE #12597: Intermittently failing MapIndexLifecycleTest
com.hazelcast.map.MapIndexLifecycleTest.whenIndexConfigured_existsOnAllMembers

**Stacktrace**
```
java.lang.AssertionError: Year index should contain records
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.map.MapIndexLifecycleTest.assertGlobalIndexesAreInitialized(MapIndexLifecycleTest.java:181)
	at com.hazelcast.map.MapIndexLifecycleTest.whenIndexConfigured_existsOnAllMembers(MapIndexLifecycleTest.java:116)
```

https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14376/testReport/junit/com.hazelcast.map/MapIndexLifecycleTest/whenIndexConfigured_existsOnAllMembers/

**Standard Output** 
[test.log](https://github.com/hazelcast/hazelcast/files/1811535/test.log)

### PR DESCRIPTION
**Pull request by vbekiaris**
Reasoning: the assertion may be executed before migrations
have been completed, so global indexes may be not yet populated
at the time they are queried.

Fixes #12597

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java [hunk 1]
```diff
@@ -71,6 +72,7 @@
 
 @RunWith(HazelcastParallelClassRunner.class)
 @Category({QuickTest.class, ParallelTest.class})
+@Repeat(1000)
```
Comment (tkountis) [inline hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java]: leftover ?

Comment (Donnerbart) [reply hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java]: I think that's the reason for the `[DO NOT MERGE]`. Although it may crash our PR builder runtime statistics :p

Comment (tkountis) [reply hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java]: Didn't see that, time to sleep then :)

Comment (vbekiaris) [reply hazelcast/src/test/java/com/hazelcast/map/MapIndexLifecycleTest.java]: Yes, it was intended to run the test several times in the PR builder in parallel with other tests. @tkountis thanks for the review and hope you had a good rest ;-)

PR is now updated without `@Repeat` and reasoning in description / see also https://github.com/hazelcast/hazelcast/issues/12597#issuecomment-373324317

**Comment by vbekiaris** [comment]
verify

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run
