### PR TITLE
Simplify eviction strategy and fix a fragile CQC test

### LINKED ISSUE #9778: [query-cache] EvictionTest.testMaxSizeEvictionWorks
```
java.lang.AssertionError: Cache size is 101, failed to complete within 120 seconds, count left: 3
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:877)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:863)
	at com.hazelcast.map.impl.querycache.EvictionTest.testMaxSizeEvictionWorks(EvictionTest.java:59)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/1167/testReport/junit/com.hazelcast.map.impl.querycache/EvictionTest/testMaxSizeEvictionWorks/

### PR DESCRIPTION
**Pull request by jerrinot**
See commit message for details
Fixes #9778
EE part : https://github.com/hazelcast/hazelcast-enterprise/pull/1709

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/eviction/impl/evaluator/EvictionPolicyEvaluator.java [hunk 1]
```diff
@@ -50,7 +48,7 @@ public EvictionPolicyComparator getEvictionPolicyComparator() {
      * @param evictionCandidates Multiple {@link com.hazelcast.internal.eviction.EvictionCandidate} to be evicted
      * @return multiple {@link com.hazelcast.internal.eviction.EvictionCandidate} these are available to be evicted
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/internal/eviction/impl/evaluator/EvictionPolicyEvaluator.java]: The javadoc needs to be fixed.

File: hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java [hunk 2]
```diff
@@ -58,18 +60,22 @@ boolean isEvictionEnabled() {
...
-        if (isEvictionEnabled()) {
-            return evictionStrategy.evict(cache, evictionPolicyEvaluator, evictionChecker, listener);
+    void evictIfRequired() {
+        if (!isEvictionEnabled()) {
+            return;
+        }
+
+        for (int i = 0; evictionChecker.isEvictionRequired() && i < MAX_EVICTION_ATTEMPTS; i++) {
+            // we already established we should evict -> we can pass EVICT_ALWAYS to the eviction strategy
+            evictionStrategy.evict(cache, evictionPolicyEvaluator, EVICT_ALWAYS, listener);
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java]: Just checking - this is a best-effort mechanism where we evict up to `MAX_EVICTION_ATTEMPTS` - even if the cache capacity has been exceeded more than that limit?

File: hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java [hunk 3]
```diff
@@ -26,12 +26,14 @@
...
 
 import static com.hazelcast.internal.config.ConfigValidator.checkEvictionConfig;
+import static com.hazelcast.internal.eviction.EvictionChecker.EVICT_ALWAYS;
 import static com.hazelcast.internal.eviction.EvictionPolicyEvaluatorProvider.getEvictionPolicyEvaluator;
 
 /**
  * Contains eviction specific functionality of a {@link QueryCacheRecordStore}.
  */
 public class EvictionOperator {
+    private static final int MAX_EVICTION_ATTEMPTS = 10;
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java]: maybe some javaDoc to shortly explain reasoning behind this limit

File: hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java (hunk 2 above)
Comment (jerrinot) [reply hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java]: yes. you want to spread the cost of cleaning it up across multiple calls. to prevent bad latency spikes.

Comment (jerrinot) [reply hazelcast/src/main/java/com/hazelcast/map/impl/querycache/subscriber/EvictionOperator.java]: I added comment to the property itself

File: hazelcast/src/main/java/com/hazelcast/internal/eviction/impl/evaluator/EvictionPolicyEvaluator.java [hunk 4]
```diff
@@ -44,13 +42,15 @@ public EvictionPolicyComparator getEvictionPolicyComparator() {
...
+     * The definition of the best depends on configured eviction policy. (LRU, LFU, custom, etc)
+     *
+     * It returns <code>null</code> when there the input is empty.
      *
      * @param evictionCandidates Multiple {@link com.hazelcast.internal.eviction.EvictionCandidate} to be evicted
-     * @return multiple {@link com.hazelcast.internal.eviction.EvictionCandidate} these are available to be evicted
+     * @return a selected candidate to be evicted or null.
      */
-    public <C extends EvictionCandidate<A, E>> Iterable<C> evaluate(Iterable<C> evictionCandidates) {
+    public <C extends EvictionCandidate<A, E>> C evaluate(Iterable<C> evictionCandidates) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/eviction/impl/evaluator/EvictionPolicyEvaluator.java]: I though this whole method could be renamed to `selectBestCandidate()` ? @ahmetmircik: WDYT?

but perhaps not in this PR.

Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/internal/eviction/impl/evaluator/EvictionPolicyEvaluator.java]: seems doable
