### PR TITLE
unresolved addresses should be retried when trying to connect.

### LINKED ISSUE #4349: Client shuts down when IP changes upon reconnects
We have been experiencing that HZ clients shutdown in case of an IP change of one or more of the configured node (DNS) addresses. 

Steps that led to the problem:

1. Cluster with two nodes
2. Clients are configured to access cluster nodes via FQDN
3. Shutdown of both cluster nodes
4. (clients try to reconnect)
5. Cluster nodes come up again
6. During startup, cluster nodes get new (private) IP addresses, which are registered at the DNS service
7. It seems that there is a small time window where the FQDN has no IP assigned/configured at the DNS service, because accessing ``InetAddress address = inetSocketAddress.getAddress();`` https://github.com/hazelcast/hazelcast/blob/3.3.4/hazelcast/src/main/java/com/hazelcast/nio/Address.java#L198 evaluates to null. Since this exception is nowhere handled, ``ClusterListenerThread.run`` shuts down the client https://github.com/hazelcast/hazelcast/blob/3.3.4/hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java#L83-L94. 

We are experiencing this issue with 3.3.1, but as far as I can see the code in the master (i.e., 3.4) is the same. 

I would suggest to handle the exception directly here https://github.com/hazelcast/hazelcast/blob/3.4/hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java#L258-L260, but this may also have an impact on initial connection attempts (where it may be desired to quit immediately).

*full stacktrace*
``` java
java.lang.IllegalArgumentException: Can't resolve address: hz0.example.com:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200) ~[hazelcast-3.3.1.jar:3.3.1]
	at com.hazelcast.nio.Address.<init>(Address.java:69) ~[hazelcast-3.3.1.jar:3.3.1]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:246) ~[hazelcast-client-3.3.1.jar:3.3.1]
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:79) ~[hazelcast-client-3.3.1.jar:3.3.1]
java.lang.IllegalArgumentException: Can't resolve address: hz0.example.com:5701
	at com.hazelcast.nio.Address.resolve(Address.java:200)
	at com.hazelcast.nio.Address.<init>(Address.java:69)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.connectToOne(ClusterListenerThread.java:246)
	at com.hazelcast.client.spi.impl.ClusterListenerThread.run(ClusterListenerThread.java:79)
```

### PR DESCRIPTION
**Pull request by sancar**
fixes #4349

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    }
+
+    @Test
+    public void testWithLegalAndIllegalAddressTogether() {
+        String illegalAddress = randomString();
+
+        Hazelcast.newHazelcastInstance();
+        ClientConfig config = new ClientConfig();
+        config.getNetworkConfig().addAddress(illegalAddress).addAddress("localhost");
+        HazelcastClient.newHazelcastClient(config);
```
Comment (jerrinot) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: shouldn't you check the client has actually connected to the member running locally?

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+import com.hazelcast.test.HazelcastSerialClassRunner;
+import com.hazelcast.test.HazelcastTestSupport;
+import com.hazelcast.test.annotation.QuickTest;
+import org.junit.After;
+import org.junit.Before;
+import org.junit.Test;
+import org.junit.experimental.categories.Category;
+import org.junit.runner.RunWith;
+
+/**
```
Comment (jerrinot) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: this shouldn't be here.

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java [hunk 3]
```diff
@@ -0,0 +1,50 @@
+package com.hazelcast.client;
```
Comment (bilalyasar) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: there must be license headers.

**Comment by sancar** [comment]
I updated the pr according to reviews.

**Comment by jerrinot** [comment]
the PR seems good to me now.
:+1:

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java (hunk 3 above)
Comment (gurbuzali) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: there is already ?

**Comment by gurbuzali** [comment]
:+1:

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java (hunk 3 above)
Comment (jerrinot) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: yes, the license was missing in the original commit.

**Comment by mdogan** [comment]
What about master branch?

**Comment by sancar** [comment]
It is on the way. There is a waiting pr on the master branch. I need to do this update on top of it, otherwise there will be conflict.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java [hunk 4]
```diff
@@ -250,22 +250,22 @@ private ClientConnection connectToOne() throws Exception {
...
         Throwable lastError = null;
-        Set<Address> triedAddresses = new HashSet<Address>();
+        Set<InetSocketAddress> triedAddresses = new HashSet<InetSocketAddress>();
         while (true) {
             final long nextTry = Clock.currentTimeMillis() + connectionAttemptPeriod;
             final Collection<InetSocketAddress> socketAddresses = getSocketAddresses();
             for (InetSocketAddress isa : socketAddresses) {
-                Address address = new Address(isa);
-                triedAddresses.add(address);
-                LOGGER.finest("Trying to connect to " + address);
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java]: Please make use of 'isFinestEnabled'. Even though it isn't code that very frequently runs, I think it is best to do.

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+        ClientConfig config = new ClientConfig();
+        config.getNetworkConfig().addAddress(illegalAddress);
+        HazelcastClient.newHazelcastClient(config);
+    }
+
+    @Test
+    public void testWithLegalAndIllegalAddressTogether() {
+        String illegalAddress = randomString();
+
+        final HazelcastInstance server = Hazelcast.newHazelcastInstance();
```
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: Please remove the 'finals'. They don't provide any value here, only noise. Also you are not consistent with your other test methods.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java [hunk 6]
```diff
@@ -250,22 +250,22 @@ private ClientConnection connectToOne() throws Exception {
...
                 try {
+                    triedAddresses.add(isa);
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java]: isa is not a human readable name. Please use address or something.

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java (hunk 5 above)
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: It could very well be that I'm wrong; but if I remember correctly, there is randomization in the client addresses. So it could very well be that 'localhost' addresses is touched first, even though it is in the list last. This would mean that this test doesn't trigger running into a non existing address.

Comment (sancar) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: Yes, this test will randomly test our failing scenario. Some tests will not test the thing we want. Statistically half of them. But there is no other way to test it, what is your suggestion?

Comment (sancar) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: About finals, they are auto generated in my IDE environment. If we don't have a clear policy about finals, I don't want to change them, because someone else might just say it is better to have them. If we can have a checkstyle rule or something, it can be better to resolve such disagreements,

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java (hunk 6 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java]: OK.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java (hunk 4 above)
Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java]: OK.

Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClusterListenerThread.java]: Our checkstyle is like a trap. I just added isFinestEnabled and it is complaining about npath complexity. :) . It is probably a sign of it was already complicated. Fixing that also.

**Comment by sancar** [comment]
@pveentjer @gurbuzali @jerrinot . Are you guys happy with this one after updates?

**Comment by gurbuzali** [comment]
I'm OK with the changes.
as for finals I think they are not necessary but as you've stated there is no consensus

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java (hunk 5 above)
Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: About final:

Be at least consistent in your own code. It doesn't make much sense to have 50% of the methods with and 50% of the methods without finals.

Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: About non deterministic tests:

Make them deterministic. One potential solution is to use a system property that prevents the randomization. It isn't a public property (so not a groupproperties), but just one we know about.

Comment (mdogan) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: I think discussing about using or not-using or half-using `final` local variables/method params is one of the most useless discussions in our group. 

We should let people do whatever they like with finals. They are at worst harmless if not useful. I don't think finals have any negative effect on code readability.

Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: It causes reading noise; it causes longer lines than needed. If it would be as simple as scala finals (just use val instead of var) I would be pushing to use finals. In java it is just noise. From a optimization point of view it is quite useless (local variables) since the jit will be able to determine it anwyay.

But most importantly: use a single style throughout the system. We have a style for brackets or spaces/tabs etc. Finals falls in the same category; it doesn't make the code go faster, but a single style is used. I don't see the reason why we should deal with final any differently.

Comment (pveentjer) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientConnectionTest.java]: I don't want to make too many words dirty about it. My main point here is that a single developer uses multiple styles for final. If you are writing some concurrent code; I have no problems at all using finals within methods (I do that all the time). But for non concurrent code; use a single style and stick with it.

**Comment by pveentjer** [comment]
My main comment regarding this pr is the non deterministic behaviour of the actual code. Which makes testing almost impossible to do. I think we should have a look at how we can make the code more deterministic for testing purposes.

**Comment by sancar** [comment]
I lost my motivation on this issue because of all this discussion. Anyone who wants to resolve the issue? @asimarslan @enesakar

**Comment by enesakar** [comment]
System property for just a single test does not sound good. 
But I talked with Ali and we think that system property that prevents shuffling addresses can be something also beneficial for users besides making test more reliable.
So Sancar can you add such a system property that prevents shuffling, then we can merge the PR.

**Comment by bwzhang2011** [comment]
@sancar, It does't matter for your motivation for such issue at least for most programmers like myself appreciated of @pveentjer attitude not only for the design but also for the coding for hz set up some good example to us for improvement continuously

**Comment by sancar** [comment]
com.hazelcast.queue.TransactionQueueTest.testIssue859And863

Failing for the past 1 build (Since Failed#11587 )
Took 2 min 4 sec.
Error Message

expected:<2000> but was:<1999>
Stacktrace

java.lang.AssertionError: expected:<2000> but was:<1999>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.queue.TransactionQueueTest$2.run(TransactionQueueTest.java:271)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:251)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:267)
	at com.hazelcast.queue.TransactionQueueTest.testIssue859And863(TransactionQueueTest.java:268)

**Comment by sancar** [comment]
verify

**Comment by enesakar** [comment]
@bwzhang2011 our developers' motivation always matters for us.

**Comment by bwzhang2011** [comment]
@enesakar, sorry for my expression for my comment. as we know @sancar also play the important role in hz team for the hz client component (or more). our project based on the hz cluster and communication rely on hz client for communication and operation so any improvement and feature is appreciated. maybe it doesn't matter just mean you don't care about and through the improvement for hz product especially the expectation for hz3.5 releasing (for performance and enhancement), we're looking forward to more robust product forthcoming.

File: hazelcast-client/src/main/java/com/hazelcast/client/config/ClientProperties.java [hunk 7]
```diff
@@ -22,6 +22,16 @@
 public class ClientProperties {
 
     /**
+     * Client shuffles the given member list to prevent all clients to connect to same node when
+     * this property is false. When set to true, client tries to connect to nodes in order as given.
+     */
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/config/ClientProperties.java]: Perhaps it would be an idea to include a few lines why this property exist; so setting it to false helps to make tests deterministic. I don't know if it has any value for a production system.

Comment (sancar) [inline hazelcast-client/src/main/java/com/hazelcast/client/config/ClientProperties.java]: Setting it to false means changing the default behaviour. I wanted to leave the behaviour as is to not to surprise users. The users probably relying on client to make balancing in the sense that clients will more or less connect to different nodes, and there will be no bottleneck in one node.

And we added this property because we thought there is added value.(see @enesakar comment) Otherwise we better don't add the property  so that we don't make the properties a mess with unused configurations.

**Comment by asimarslan** [comment]
I think we have reached a point that we should merge this PR. We should stop at some quality thresh-hold level(like level of detailed documentations ) , and we reached that level as I cannot see any comment about major problems. 

As we all know, One can continue to criticise infinitely as long as he/she wants.

I cannot see any more problem that should be fixed before merging this PR and merging it as two people already approved it.
P.S. Documentation can be fixed without PR at any time.
