### PR TITLE
Fire MERGE_FAILED when node fails to merge to discovered cluster

### LINKED ISSUE #9856: Adding `MERGE_FAILED` to LifeCycleState's
Currently there's only `MERGING, MERGED` but no event fired for a failed merge. This would be informative and further give an idea to user to understand a reason of a `SHUTTING_DOWN` event since a failed merge is followed by a shutdown.

This can be added to both 3.7.x and 3.8.x branches.

### PR DESCRIPTION
**Pull request by mdogan**
Currently there are only `MERGING`, `MERGED` events, but no event fired for a failed merge.

Fixes #9856

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/core/LifecycleEvent.java [hunk 1]
```diff
@@ -42,6 +42,7 @@
         SHUTDOWN,
         MERGING,
         MERGED,
+        MERGE_FAILED,
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/core/LifecycleEvent.java]: this change ordinal value of the `CLIENT_`. is it ok?

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/core/LifecycleEvent.java]: I guess some serialization strategies might break

Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/core/LifecycleEvent.java]: `LifecycleEvent` is not serialized. It should be completely local event. Relying ordinals unless explicitly defined should be considered as bug, I think.

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/core/LifecycleEvent.java]: mr. Bloch agrees with you:
