### PR TITLE
Small improvements for SlowOperationDetector

### LINKED ISSUE #5043: SlowOperationDetector disable logging option
There should be an option to disable the SlowOperatioDetector logging the stacktraces to the log file. It is very noisy and if you already using the management center or the performance monitor, there is no need to have the stacktraces written to the normal log file.

### PR DESCRIPTION
**Pull request by Donnerbart**
Added hint in first log of SlowOperationDetector.
Added a missing test for the property to disable the feature.
Added the stack trace config property to some tests to increase code coverage.

Fixes #5043.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetector.java [hunk 1]
```diff
@@ -43,6 +43,8 @@
     private static final long ONE_SECOND_IN_NANOS = TimeUnit.SECONDS.toNanos(1);
     private static final long SLOW_OPERATION_THREAD_MAX_WAIT_TIME_TO_FINISH = TimeUnit.SECONDS.toMillis(10);
 
+    private static boolean isFirstLog = true;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetector.java]: Perhaps better not to make this static. Let each HZ instance tell it once. Also if it is static, you have threading issues here (no happens before relation).

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java [hunk 2]
```diff
@@ -46,6 +46,21 @@ public void teardown() {
     }
 
     @Test
+    public void testDisabled() {
+        Config config = new Config();
+        config.setProperty(GroupProperties.PROP_SLOW_OPERATION_DETECTOR_ENABLED, "false");
+        config.setProperty(GroupProperties.PROP_SLOW_OPERATION_DETECTOR_THRESHOLD_MILLIS, "1000");
+
+        instance = getSingleNodeCluster(config);
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java]: Why don't you make use of the HazelcastTestSupport.createHazelcastInstance method?

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java [hunk 3]
```diff
@@ -46,6 +46,21 @@ public void teardown() {
...
+
+        getInternalOperationService(instance).execute(new SlowRunnable(3, Operation.GENERIC_PARTITION_ID));
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java]: Make use of the HazelcastTestSupport.getOperationService method which returns the InternalOperationService.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java (hunk 2 above)
Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java]: I am, you are just missing context:

```
    HazelcastInstance getSingleNodeCluster(Config config) {
        MapConfig mapConfig = new MapConfig();
        mapConfig.setName("slowOperation*");
        config.addMapConfig(mapConfig);

        TestHazelcastInstanceFactory factory = createHazelcastInstanceFactory(1);
        return factory.newHazelcastInstance(config);
    }
```

**Comment by pveentjer** [comment]
Also add @Override on your Thread.run method.

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorBasicTest.java]: Damn github reviews

File: hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorAbstractTest.java [hunk 4]
```diff
@@ -113,10 +101,6 @@ static void shutdownOperationService(HazelcastInstance instance) {
         return invocationMap.values();
     }
 
-    static InternalOperationService getInternalOperationService(HazelcastInstance instance) {
-        return TestUtil.getNode(instance).nodeEngine.getOperationService();
-    }
-
     static int getDefaultPartitionId(HazelcastInstance instance) {
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorAbstractTest.java]: I find default partition id extremely confusing. Also 'default key' is very confusing.

Comment (Donnerbart) [inline hazelcast/src/test/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetectorAbstractTest.java]: Please have a look in IDEA, that method is already in master. It may be confusing because it is not 100% easy what I have to do there. I totally don't care about keys and values in my tests. I just need the partitionId of the one entry which is in the map for a nested operation with different partitionIds.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetector.java [hunk 5]
```diff
@@ -231,22 +234,39 @@ private SlowOperationLog getOrCreate(String stackTrace, Object operation) {
...
+                logger.warning(format("Slow operation detected: %s (%d invocations)", log.operation, totalInvocations));
             }
-            logger.warning(format("Slow operation detected: %s (%d invocations)", log.operation, totalInvocations));
+        }
+
+        private void logWithConfigHint(SlowOperationLog log, int totalInvocations) {
+            // print a hint once how to enable logging of stack traces
+            logger.warning(format("Slow operation detected: %s"
+                            + "%nHint: You can enable the logging of stack traces with the following config property:"
+                            + " hazelcast.slow.operation.detector.stacktrace.logging.enabled",
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/operationexecutor/slowoperationdetector/SlowOperationDetector.java]: I would use the GroupProperty for it. This way you don't run into problems when it is renamed.

**Comment by Donnerbart** [comment]
verify
