### PR TITLE
Fix expected memory costs in tests

### LINKED ISSUE #8908: [ZING-JVM] SizeEstimatorTest.testExactHeapCostAfterUpdateWithMultipleBackupNodes & testSinglePut
**testExactHeapCostAfterUpdateWithMultipleBackupNodes**
```
java.lang.AssertionError: Heap cost calculation is wrong! expected:<156> but was:<188>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at com.hazelcast.map.SizeEstimatorTest.testExactHeapCostAfterUpdateWithMultipleBackupNodes(SizeEstimatorTest.java:69)
```
https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/34/testReport/junit/com.hazelcast.map/SizeEstimatorTest/testExactHeapCostAfterUpdateWithMultipleBackupNodes/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/55/testReport/junit/com.hazelcast.map/SizeEstimatorTest/testExactHeapCostAfterUpdateWithMultipleBackupNodes/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/56/testReport/junit/com.hazelcast.map/SizeEstimatorTest/testExactHeapCostAfterUpdateWithMultipleBackupNodes/

**testSinglePut**
```
java.lang.AssertionError: expected:<156> but was:<188>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.map.SizeEstimatorTest.testSinglePut(SizeEstimatorTest.java:55)
```
https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK6/34/testReport/junit/com.hazelcast.map/SizeEstimatorTest/testSinglePut/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK7/55/testReport/junit/com.hazelcast.map/SizeEstimatorTest/testSinglePut/

https://hazelcast-l337.ci.cloudbees.com/view/Zing/job/Hazelcast-3.x-ZingJDK8/56/testReport/junit/com.hazelcast.map/SizeEstimatorTest/testSinglePut/

### PR DESCRIPTION
**Pull request by vbekiaris**
The expected memory costs in test code were previously calculated assuming compressed oops is enabled (or a 32-bit JVM). These have now been updated to take into account the JVM reference cost in bytes as estimated by `JVMUtil`.

Fixes #8908 and #8909

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/SizeEstimatorTest.java [hunk 1]
```diff
@@ -48,7 +49,8 @@ public void smoke() throws InterruptedException {
 
     @Test
     public void testSinglePut() throws InterruptedException {
-        long expectedPerEntryHeapCost = 156L;
+        // the expected cost is 8 * reference_cost + (key + record cost)
+        long expectedPerEntryHeapCost = 124 + 8 * JVMUtil.REFERENCE_COST_IN_BYTES;
```
Comment (tkountis) [inline hazelcast/src/test/java/com/hazelcast/map/SizeEstimatorTest.java]: Not blocking, but would be nice if we had these figures defined with name, easier to read and wouldn't require comments.

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Thanks @mmedenjak @tkountis @jerrinot for the quick review!
