### PR TITLE
Fix wrong XML schema locations

### LINKED ISSUE #13504: XSD in client config default
https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/resources/hazelcast-client-default.xml#L32
specifies
http://www.hazelcast.com/schema/config/hazelcast-client-config-3.11.xsd

This should be
http://hazelcast.com/schema/client-config/hazelcast-client-config-3.11.xsd
or
https://hazelcast.com/schema/client-config/hazelcast-client-config-3.11.xsd

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #13504

Also adding a test to make sure it XMLs points to existing XSDd.

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/config/XmlConfigSchemaLocationTest.java [hunk 1]
```diff
@@ -0,0 +1,164 @@
...
+    }
+
+    private void validateSchemaLocationUrl(InputStream documentStream, String originalLocation) throws Exception {
+        String schemaAttr = extractSchemaAttribute(documentStream);
+        if (schemaAttr == null) {
+            return;
+        }
+        for (String nameSpaceUrl : schemaAttr.split(" ")) {
+            nameSpaceUrl = nameSpaceUrl.trim();
+            if (shouldSkipValidation(nameSpaceUrl)) {
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/config/XmlConfigSchemaLocationTest.java]: this is ugly. instead of parsing locations from "schemaUri location" it's just skipping everything what does not end with `.xsd`. it works in practice quite well.

File: hazelcast/src/test/java/com/hazelcast/config/XmlConfigSchemaLocationTest.java [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+import java.util.Set;
+import java.util.regex.Pattern;
+
+import static com.hazelcast.test.TestCollectionUtils.setOf;
+import static org.junit.Assert.assertEquals;
+
+@RunWith(HazelcastSerialClassRunner.class)
+@Category(SlowTest.class)
+public class XmlConfigSchemaLocationTest extends HazelcastTestSupport {
+    private static final Set<String> WHITELIST = setOf("hazelcast-sample-service.xsd");
```
Comment (mesutcelik) [inline hazelcast/src/test/java/com/hazelcast/config/XmlConfigSchemaLocationTest.java]: I didn't quite get WHITELIST?

Comment (jerrinot) [reply hazelcast/src/test/java/com/hazelcast/config/XmlConfigSchemaLocationTest.java]: see this file: https://github.com/jerrinot/hazelcast/blob/4031fca68c08a763151649ca7d41d41713deafdd/hazelcast/src/test/resources/com/hazelcast/config/hazelcast-service.xml#L22

It's an example of a custom Hazelcast service. 

The example defines own schema, but the schema is not available anywhere on the internet. It's just an example after all. So the test has to skip it.

Comment (kwart) [reply hazelcast/src/test/java/com/hazelcast/config/XmlConfigSchemaLocationTest.java]: Could you add a comment with reference to the `ServiceConfigTest` on the constant?

**Comment by kwart** [comment]
```bash
$ curl --tlsv1.0 -Lvs http://www.hazelcast.com/schema/config/hazelcast-config-3.11.xsd 2>&1
*   Trying 104.198.14.254...
* TCP_NODELAY set
* Connected to www.hazelcast.com (104.198.14.254) port 80 (#0)
> GET /schema/config/hazelcast-config-3.11.xsd HTTP/1.1
> Host: www.hazelcast.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Tue, 11 Sep 2018 11:52:32 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Keep-Alive: timeout=20
< Location: http://hazelcast.com/schema/config/hazelcast-config-3.11.xsd
< 
* Ignoring the response-body
{ [178 bytes data]
* Connection #0 to host www.hazelcast.com left intact
* Issue another request to this URL: 'http://hazelcast.com/schema/config/hazelcast-config-3.11.xsd'
*   Trying 104.198.14.254...
* TCP_NODELAY set
* Connected to hazelcast.com (104.198.14.254) port 80 (#1)
> GET /schema/config/hazelcast-config-3.11.xsd HTTP/1.1
> Host: hazelcast.com
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Date: Tue, 11 Sep 2018 11:52:32 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Keep-Alive: timeout=20
< Location: https://hazelcast.com/schema/config/hazelcast-config-3.11.xsd
< X-Type: default
< 
* Ignoring the response-body
{ [178 bytes data]
* Connection #1 to host hazelcast.com left intact
* Issue another request to this URL: 'https://hazelcast.com/schema/config/hazelcast-config-3.11.xsd'
*   Trying 104.198.14.254...
* TCP_NODELAY set
* Connected to hazelcast.com (104.198.14.254) port 443 (#2)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
} [137 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to hazelcast.com:443 
* stopped the pause stream!
* Closing connection 2
```
