### PR TITLE
CacheRecord comparator implementation is fixed to be able to differentiate

### LINKED ISSUE #4451: A bug in ClientNearCache eviction comparator
In the ClientNearCache class there is the following comparator: 

    private final Comparator<CacheRecord<K>> comparator = new Comparator<CacheRecord<K>>() {
        public int compare(CacheRecord<K> o1, CacheRecord<K> o2) {
            if (EvictionPolicy.LRU.equals(evictionPolicy)) {
                return ((Long) o1.lastAccessTime).compareTo((o2.lastAccessTime));
            } else if (EvictionPolicy.LFU.equals(evictionPolicy)) {
                return ((Integer) o1.hit.get()).compareTo((o2.hit.get()));
            }

            return 0;
        }
    };

It is later on used in a TreeSet to finde the entries that should be evicted. Problem is, if there are CacheRecords with the same hit count or lastAccessTime (depending on LFU/LRU), you'll only add one of these although most likely all of them should be evicted. 

Think it's a minor issues since this will most likely not happen that often. Maybe you should rely on the CacheRecord key as well though?

### PR DESCRIPTION
**Pull request by sancar**
unique keys. fixes #4451

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/nearcache/ClientHeapNearCache.java [hunk 1]
```diff
@@ -282,10 +271,27 @@ public long getCost() {
...
+
         boolean expired() {
             long time = Clock.currentTimeMillis();
             return (maxIdleMillis > 0 && time > lastAccessTime + maxIdleMillis)
                     || (timeToLiveMillis > 0 && time > creationTime + timeToLiveMillis);
         }
+
+        public int compareTo(CacheRecord<K> o) {
+            if (EvictionPolicy.LRU.equals(evictionPolicy)) {
+                final int result = ((Long) this.lastAccessTime).compareTo((o.lastAccessTime));
```
Comment (gurbuzali) [inline hazelcast-client/src/main/java/com/hazelcast/client/nearcache/ClientHeapNearCache.java]: isn't it better to calculate the result with `this.lastAccessTime - o.lastAccessTime` rather than casting to Long ?

**Comment by serkan-ozal** [comment]
@sancar @gurbuzali Comparing hashcodes as  `return hashCode1 - hashCode2` may cause some integer overflow problems.

Suppose that
        i1 = -500.000.000
        i2 = 2.000.000.000
     
Normally "i1 < i2", but if we use "i1 - i2" for comparison
i1 - i2 = -500.000.000 - 2.000.000.000 and we may accept result as "-2.500.000.000".
But the actual result is "1.794.967.296" because of overflow between
positive and negative integer bounds.

So, if we use "i1 - i2" for comparison, since result is greater than 0,
"i1" is accepted as bigger that "i2". But in fact "i1" is smaller than "i2".
Therefore, "i1 - i2" is not good way for comparison way between signed integers. 

So comparison must be like this
~~~~ java
...
return compareIntegers(obj1.hashCode(), obj2.hashCode());
...
private static int compareIntegers(int i1, int i2) {
        // "return i1 - i2" is not good way for comparison
        if (i1 > i2) {
            return +1;
        } else if (i2 > i1) {
            return -1;
        } else {
            return 0;
        }
}
~~~~

**Comment by sancar** [comment]
It never occurred to me this can be a problem, since I come across this kind usage in most of the code bases. But in this context real comparison does not matter as long as it always give the same answer.

For lastAccessTime it should not be that problem because they never be minus. But I am casting them to int , there is another problem. If last access times are 24(IntMax/ 1000/ 60 / 60 / 24) days apart, there will be overflow when casting.

I will update the pr with static util comparison methods for all int and longs in my methods just for the sake of standardization whether there is a problem or not. And also to remove the unnecessary casting to Objects.

**Comment by serkan-ozal** [comment]
@sancar 

`But in this context real comparison does not matter as long as it always give the same answer.`

I think, integer overflow can break the **transitivity** and may cause different sort result. 

Assume that there are three integers: x, y, z

`x > y`, `y > z` and this must be that `x > z`. But in integer overflow case, this may not be true and.
So I think sort result may differ from initial order of elements in this case.

I had faced with similar issue in this PR: https://github.com/hazelcast/hazelcast/pull/3377

**Comment by sancar** [comment]
@serkan-ozal  Of course, I know it can cause different ordering. But in this context, order does not matter when comparing hashcodes. I mean, It does not matter which key is evicted first as long as other comparisons (lastAccessTime or hit) are equal.

**Comment by sancar** [comment]
@serkan-ozal  @gurbuzali  Thanks for the detailed review.

**Comment by serkan-ozal** [comment]
@sancar Ok, I see. It doesn't matter for hash code comparison but as you said it can be problem when casting long typed time values to int and comparing them by minus (cause to selecting wrong record to evict).

**Comment by sancar** [comment]
verify

File: hazelcast/src/main/java/com/hazelcast/util/QuickMath.java [hunk 2]
```diff
@@ -204,4 +204,39 @@ public static String bytesToHex(byte[] in) {
         }
         return new String(hexChars);
     }
+
+    /**
+     * Utility method to compare integers
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/util/QuickMath.java]: You don't need to add 'utility method' because it provides no additional information. 

```
Compares 2 integers
```

What I'm missing is the explanation of the return values. So what do -1, 0 and 1 mean? Well.. 0 is easy.. but does 1 mean i1>i2 or i1<i2.

Perhaps call them first and second instead of those cryptic names?

File: hazelcast/src/main/java/com/hazelcast/util/QuickMath.java [hunk 3]
```diff
@@ -204,4 +204,39 @@ public static String bytesToHex(byte[] in) {
...
+        if (i1 > i2) {
+            return +1;
+        } else if (i2 > i1) {
+            return -1;
+        } else {
+            return 0;
+        }
+    }
+
+    /**
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/util/QuickMath.java]: Same here.

Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/util/QuickMath.java]: Is there a unit tests for these methods? I don't see any in this PR.

Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/util/QuickMath.java]: updated the javadoc

**Comment by ahmetmircik** [comment]
This PR seems mergeable to me.
