### PR TITLE
Fixes in ICondition

### LINKED ISSUE #3317: [TEST-FIX] ConditionTest.testLockConditionSignalAllShutDownKeyOwner
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-problematicTest/com.hazelcast$hazelcast/223/testReport/junit/com.hazelcast.concurrent.lock/ConditionTest/testLockConditionSignalAllShutDownKeyOwner/
```
java.lang.AssertionError: expected:<50> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at com.hazelcast.concurrent.lock.ConditionTest.testLockConditionSignalAllShutDownKeyOwner(ConditionTest.java:426)
```

### PR DESCRIPTION
**Pull request by jerrinot**
See #2272 for further discussion.

There are 2 big fixes:
- `ConditionKey` is tight to a particular Waiter.
This is needed as otherwise a thread might eat its own signal.
- BeforeAwaitOperation::getNotifiedKey returns `ConditionKey` when there
is a pending signal.

There are also additional improvements:
- Move getNotifiedKey() up to `LockStoreImpl`
- Map notifiers use this idiom for creating a notifier key:  If there is a pending signal (ConditionKey) then use it as a notifier. Otherwise use a regular LockWaitNotifyKey
- `ConditionInfo` simplification

Fixes #3317, #2272, #3789

### CODE REVIEW

**Comment by jerrinot** [comment]
run-lab-run

File: hazelcast/src/test/java/com/hazelcast/concurrent/lock/ConditionAdvancedTest.java [hunk 1]
```diff
@@ -161,7 +161,6 @@ public void run() {
 
 
     @Test
-    @Ignore // https://github.com/hazelcast/hazelcast/issues/2272
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/concurrent/lock/ConditionAdvancedTest.java]: this is passing now

File: hazelcast/src/test/java/com/hazelcast/concurrent/lock/ProducerConsumerConditionStressTest.java [hunk 2]
```diff
@@ -13,7 +13,6 @@
 
 
 @RunWith(HazelcastParallelClassRunner.class)
-@Ignore // https://github.com/hazelcast/hazelcast/issues/2272
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/concurrent/lock/ProducerConsumerConditionStressTest.java]: this is passing now

File: hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockResourceImpl.java [hunk 3]
```diff
@@ -276,8 +288,9 @@ void cancelEviction() {
 
     boolean isRemovable() {
         return !isLocked()
-                && isNullOrEmpty(conditions)
-                && isNullOrEmpty(expiredAwaitOps);
+                && isNullOrEmpty(waiters)
+                && isNullOrEmpty(expiredAwaitOps)
+                && isNullOrEmpty(conditionKeys);
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockResourceImpl.java]: we do not want to remove a lock if there are pending signals

File: hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BaseSignalOperation.java [hunk 4]
```diff
@@ -42,23 +41,11 @@ public BaseSignalOperation(ObjectNamespace namespace, Data key, long threadId, S
 
     @Override
     public void run() throws Exception {
-        LockStoreImpl lockStore = getLockStore();
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BaseSignalOperation.java]: this logic has been moved to `LockResourceImpl`

File: hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BeforeAwaitOperation.java [hunk 5]
```diff
@@ -80,7 +79,8 @@ public Operation getBackupOperation() {
 
     @Override
     public WaitNotifyKey getNotifiedKey() {
-        return new LockWaitNotifyKey(namespace, key);
+        LockStoreImpl lockStore = getLockStore();
+        return lockStore.getNotifiedKey(key);
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/concurrent/lock/operations/BeforeAwaitOperation.java]: we delegate to a lock store - if there is a pending signal then we have to use `ConditionKey` as a notifier.

**Comment by jerrinot** [comment]
run-lab-run

**Comment by mdogan** [comment]
👍 
very good work.

**Comment by mdogan** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockResourceImpl.java [hunk 6]
```diff
@@ -160,71 +162,74 @@ boolean canAcquireLock(String caller, long threadId) {
...
+        Iterator<WaitersInfo.ConditionWaiter> iterator = waiters.iterator();
+        for (int i = 0; iterator.hasNext() && i < maxSignalCount; i++) {
+            WaitersInfo.ConditionWaiter waiter = iterator.next();
+            ConditionKey signalKey = new ConditionKey(objectName,
+                    key, conditionId, waiter.getCaller(), waiter.getThreadId());
+            registerSignalKey(signalKey);
+            iterator.remove();
         }
+        if (!condition.hasWaiter()) {
+            this.waiters.remove(condition);
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockResourceImpl.java]: Should this be `this.waiters.remove(conditionId)`?

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/concurrent/lock/LockResourceImpl.java]: great finding!

**Comment by vbekiaris** [comment]
👍 just a minor oversight. Great job!

**Comment by jerrinot** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run
