### PR TITLE
Fixes entry listener backward binary-compatibility issue

### LINKED ISSUE #4705: NoSuchMethodError com.hazelcast.core.IMap.addEntryListener(Lcom/hazelcast/core/EntryListener;Z)Ljava/lang/String;
Binary / source-level incompatibility  3.4 VS 3.5

```   Failure[
   message='Worked ran into an unhandled exception'
   type='Worker exception'
   agentAddress=10.168.112.55
   time=Sun Mar 01 02:27:01 EET 2015
   workerAddress=client:10.168.112.55
   workerId=worker-10.168.112.55-4-client
   test=TestCase{
          id=MapEntryListenerTest
        , class=com.hazelcast.stabilizer.tests.map.MapEntryListenerTest
        , basename=MapEntryListenerTest
        , deleteProb=0.2
        , evictProb=0.2
        , keyCount=1000
        , maxEntryListenerDelayMs=0
        , minEntryListenerDelayMs=0
        , randomDistributionUniform=true
        , removeProb=0.2
        , replaceProb=0.25
        , threadCount=3
        , valueCount=1000
        , valueLength=100
        , writeProb=0.4
        , writeUsingPutIfAbsent=0.25
        , writeUsingPutProb=0.5
    }
   cause=java.lang.NoSuchMethodError: com.hazelcast.core.IMap.addEntryListener(Lcom/hazelcast/core/EntryListener;Z)Ljava/lang/String;
	at com.hazelcast.stabilizer.tests.map.MapEntryListenerTest.setup(MapEntryListenerTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.stabilizer.utils.ReflectionUtils.invokeMethod(ReflectionUtils.java:29)
	at com.hazelcast.stabilizer.worker.TestContainer.setup(TestContainer.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.hazelcast.stabilizer.worker.WorkerCommandRequestProcessor$WorkerCommandRequestProcessorThread$2.doRun(WorkerCommandRequestProcessor.java:267)
	at com.hazelcast.stabilizer.worker.WorkerCommandRequestProcessor$CommandThread.run(WorkerCommandRequestProcessor.java:333)

]   ```

### PR DESCRIPTION
**Pull request by ahmetmircik**
closes #4705

- Contains addition of previously removed listener adder method signatures as deprecated.
- Tests for newly added  code.

### CODE REVIEW

**Comment by jerrinot** [comment]
:+1:

File: hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java [hunk 1]
```diff
@@ -527,6 +543,13 @@ public String addEntryListener(MapListener listener, boolean includeValue) {
     }
 
     @Override
+    public String addEntryListener(EntryListener listener, boolean includeValue) {
```
Comment (Danny-Hazelcast) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java]: https://hazelcast-l337.sonar.cloudbees.com/drilldown/measures/10815?metric=coverage&rids%5B%5D=10817&rids%5B%5D=13439#   sonar seems to show this function is not covered by any tests ?

File: hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java [hunk 2]
```diff
@@ -549,6 +580,14 @@ public String addEntryListener(MapListener listener, Predicate<K, V> predicate,
     }
 
     @Override
+    public String addEntryListener(EntryListener listener, Predicate<K, V> predicate, K key, boolean includeValue) {
```
Comment (Danny-Hazelcast) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java]: sonar show this method is not covered by any tests

File: hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java (hunk 1 above)
Comment (ahmetmircik) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/proxy/ClientMapProxy.java]: @Danny-Hazelcast can you please create an issue for it?
