### PR TITLE
Make 'MetadataRaftGroupSnapshot' class immutable since it is stored in the RaftLog snapshot [HZ-1398]

### LINKED ISSUE #21438: com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot [HZ-1398]
_master_ (commit 504ac9f2f3e2a561087708436085d9fb83b3ace5)

Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/420/testReport/com.hazelcast.cp.internal/CPMemberAddRemoveTest/when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<[CPMember{uuid=d594f66e-5397-4d70-8030-741f2c444a27, address=[127.0.0.1]:5702}, CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703}, CPMember{uuid=e6275a2d-ffd3-4320-9381-a1dfecbd8adf, address=[127.0.0.1]:5704}]> but was:<[CPMember{uuid=d594f66e-5397-4d70-8030-741f2c444a27, address=[127.0.0.1]:5702}, CPMember{uuid=191f010e-ad74-4e4e-b7eb-6aab64c10df5, address=[127.0.0.1]:5701}, CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703}]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.lambda$when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot$18(CPMemberAddRemoveTest.java:812)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest$$Lambda$11339/00000000244441E0.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1226)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1328)
	at com.hazelcast.cp.internal.CPMemberAddRemoveTest.when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot(CPMemberAddRemoveTest.java:809)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

<details><summary>Standard output:</summary>

```
05:34:21,382  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftGroupMembershipManager] hz.serene_spence.cached.thread-11 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Current leadership claims:
	CPMember{uuid=d594f66e-5397-4d70-8030-741f2c444a27, address=[127.0.0.1]:5702} has 0,
	CPMember{uuid=e6275a2d-ffd3-4320-9381-a1dfecbd8adf, address=[127.0.0.1]:5704} has 0,
	CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703} has 0 leaderships.
05:34:21,382  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftGroupMembershipManager] hz.serene_spence.cached.thread-11 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] CPGroup leadership balance is fine, cannot rebalance further...
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
05:34:32,591  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Terminating forcefully...
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MockServer] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5], alive=false}
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MockServer] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27], alive=false}
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MockServer] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5703, uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2], remoteEndpoint=[address=[127.0.0.1]:5703, uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5], alive=false}
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MockServer] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5703, uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5], remoteEndpoint=[address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2], alive=false}
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MembershipManager] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removing Member [127.0.0.1]:5703 - 2311a9e1-3881-4749-8314-1934e8cf0aa5
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [PartitionStateManager] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 2311a9e1-3881-4749-8314-1934e8cf0aa5
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [PartitionStateManager] hz.recursing_bardeen.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID 2311a9e1-3881-4749-8314-1934e8cf0aa5
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [ClusterService] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:6} [
	Member [127.0.0.1]:5702 - d594f66e-5397-4d70-8030-741f2c444a27 this
	Member [127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2
]

05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [TransactionManagerService] hz.pensive_spence.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 2311a9e1-3881-4749-8314-1934e8cf0aa5
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Shutting down node engine...
05:34:32,591  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [ClusterService] hz.recursing_bardeen.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] 

Members {size:2, ver:6} [
	Member [127.0.0.1]:5702 - d594f66e-5397-4d70-8030-741f2c444a27
	Member [127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2 this
]

05:34:32,591  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftService] hz.pensive_spence.cached.thread-7 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703} is not present in the cluster. It will be auto-removed after 14400 seconds.
05:34:32,592  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [TransactionManagerService] hz.recursing_bardeen.cached.thread-6 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 2311a9e1-3881-4749-8314-1934e8cf0aa5
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [NodeExtension] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5703 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
05:34:32,594  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Terminating forcefully...
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MockServer] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2], remoteEndpoint=[address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27], alive=false}
05:34:32,594  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MockServer] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Removed connection to endpoint: [address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2], connection: MockConnection{localEndpoint=[address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27], remoteEndpoint=[address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2], alive=false}
05:34:32,595  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MembershipManager] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Member [127.0.0.1]:5702 - d594f66e-5397-4d70-8030-741f2c444a27 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5702 - d594f66e-5397-4d70-8030-741f2c444a27 this
05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MembershipManager] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Starting mastership claim process...
05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MembershipManager] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Local MembersView{version=6, members=[MemberInfo{address=[127.0.0.1]:5702, uuid=d594f66e-5397-4d70-8030-741f2c444a27, liteMember=false, memberListJoinVersion=2}, MemberInfo{address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, liteMember=false, memberListJoinVersion=5}]} with suspected members: [Member [127.0.0.1]:5702 - d594f66e-5397-4d70-8030-741f2c444a27] and initial addresses to ask: []
05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Shutting down node engine...
05:34:32,595  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [InternalPartitionService] hz.pensive_spence.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Ignoring received partition table, startup is not completed yet. Sender: [127.0.0.1]:5702
05:34:32,595 ERROR |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [PromotionCommitOperation] hz.pensive_spence.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Promotion of 50 partitions failed. . Promotion partition state stamp: 2538535148351109352, current partition state stamp: -3954767352384688262
05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [PartitionStateManager] hz.recursing_bardeen.cached.thread-3 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Storing snapshot of partition assignments while removing UUID d594f66e-5397-4d70-8030-741f2c444a27
05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [ClusterService] hz.recursing_bardeen.cached.thread-3 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] 

Members {size:1, ver:7} [
	Member [127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2 this
]

05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MembershipManager] hz.recursing_bardeen.cached.thread-3 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Mastership is claimed with: MembersView{version=7, members=[MemberInfo{address=[127.0.0.1]:5704, uuid=8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, liteMember=false, memberListJoinVersion=5}]}
05:34:32,595  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [TransactionManagerService] hz.recursing_bardeen.cached.thread-2 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: d594f66e-5397-4d70-8030-741f2c444a27
05:34:32,595  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Invocation] hz.pensive_spence.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Future.complete(Object) on completed future. Request: Invocation{op=com.hazelcast.internal.partition.operation.PromotionCommitOperation{serviceName='hz:core:partitionService', identityHash=-996065916, partitionId=-1, replicaIndex=0, callId=-1143, invocationTime=1652679272594 (2022-05-16 05:34:32.594), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0}, tryCount=2147483647, tryPauseMillis=500, invokeCount=1, callTimeoutMillis=60000, firstInvocationTimeMs=1652679272594, firstInvocationTime='2022-05-16 05:34:32.594', lastHeartbeatMillis=0, lastHeartbeatTime='1970-01-01 00:00:00.000', target=[127.0.0.1]:5702, pendingResponse={VOID}, backupsAcksExpected=-1, backupsAcksReceived=0, connection=null}, current value: ExceptionalResult{cause=com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!}, offered value: false
java.lang.Exception: null
	at com.hazelcast.spi.impl.AbstractInvocationFuture.warnIfSuspiciousDoubleCompletion(AbstractInvocationFuture.java:1253) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete0(AbstractInvocationFuture.java:1230) [classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.complete(AbstractInvocationFuture.java:1219) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.complete(Invocation.java:673) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.sendResponse(Invocation.java:236) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.sendResponse(Operation.java:483) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:283) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:175) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:139) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
05:34:32,596  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MigrationManager] hz.pensive_spence.migration - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Promotion commit failed for [MigrationInfo{uuid=b56fb116-cfa0-4cba-9cc3-80b15d6589eb, partitionId=94, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=95c31aa4-20c0-4512-bbde-02d93271a0e0, partitionId=96, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=76c6b089-030c-4893-861c-3f460617a971, partitionId=97, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=afb647ce-5c7c-4600-b858-074de57c6c51, partitionId=98, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=0aa8996b-e0ae-4278-b08b-13ea94d28a3f, partitionId=101, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=69499b26-3351-45ea-b43d-9138a7989d59, partitionId=103, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=7c63e28b-e46f-4c62-a096-d2a00aa54a71, partitionId=104, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=fd0d3437-9804-4630-8c22-eff6aa223743, partitionId=105, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=12f99d0f-dcf3-408b-90b0-d555af3c7d83, partitionId=106, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=8f211fee-24a0-43e6-be96-b2e85d4f5a20, partitionId=107, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=349387ca-87c4-46df-8152-bcff06f98f64, partitionId=109, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=52c3433e-267c-4271-ae1d-2831f1022662, partitionId=112, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=76eeaa49-31a7-4ede-a04b-1eea21ebe99e, partitionId=115, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=37653280-6c00-4bf8-90b9-90696b38c715, partitionId=119, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=3ea08366-f1c5-4506-b249-c1e582ad04ca, partitionId=120, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=12c30d08-2d09-4048-ba58-9a23a1798e27, partitionId=121, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=2066b52a-577e-4186-97e7-beda8ab902d1, partitionId=122, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=b9fed7bc-43ec-481a-8163-8743f60d38d3, partitionId=126, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=2f9c5325-1738-4c1b-afab-aab2f0308f7c, partitionId=127, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=e7c91fd3-f9c1-4d38-a056-075a69a491b1, partitionId=128, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=778dd926-6e98-4241-ba72-8c34b7c62000, partitionId=130, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=fca75d8d-dca6-4d29-86aa-07e10de86517, partitionId=132, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=c0acbb57-1bac-4a61-b82d-fcccd0d1bd7b, partitionId=133, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=8de20517-a27a-4d3f-aaee-519b17bb3aaf, partitionId=135, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=35d533ee-1497-454a-b80b-703febc81fdd, partitionId=138, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=faf25d75-bda2-427d-9c8b-ca5cc5b8ed7f, partitionId=139, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=ad1743c8-c659-4d8f-b83e-8302e625958f, partitionId=144, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=5a920c1d-7835-4839-844a-45219b844ddd, partitionId=148, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=2a22427e-8ec7-4a49-a769-5ef2dc53f1f7, partitionId=149, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=6e2827b5-36ba-43ed-a4ed-e321639b895c, partitionId=150, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=5a47e4f1-5971-422f-ad70-764ff9315ad5, partitionId=152, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=7a46f25c-3050-4ee7-84c2-2446904270f0, partitionId=153, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=54ac03bc-933e-4853-93fb-97889bdff05a, partitionId=155, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=deca814f-0608-480f-9414-66f8a452eaa7, partitionId=157, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=fd2b5a3b-0821-4a7d-8753-74365e6e6f23, partitionId=158, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=ac6c3f5b-9980-418a-8775-0f0b6c88d643, partitionId=159, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=7fdf50e0-00e5-4b2e-9b1d-c16d7c04f060, partitionId=163, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=66db912d-11d3-4a92-a5f5-aa3abb22b616, partitionId=164, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=a1937a6c-662d-4330-96d4-5c7e13dc0c17, partitionId=170, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=a6e25088-252c-42ca-bd6e-943210c92147, partitionId=171, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5702, initialPartitionVersion=8, partitionVersionIncrement=2, status=SUCCESS}] since destination [127.0.0.1]:5704 - 8c19428a-bf0a-4e65-bb3b-cd768e49d1c2 left the cluster
05:34:32,845  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [InternalPartitionService] hz.recursing_bardeen.migration - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Fetching partition tables from cluster to determine the most recent one... Local stamp: -3271556229799755952
05:34:32,845  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [InternalPartitionService] hz.recursing_bardeen.migration - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Most recent partition table is determined.
05:34:32,845  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [InternalPartitionService] hz.recursing_bardeen.migration - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Applying the most recent of partition state...
05:34:32,845  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [InternalPartitionService] hz.recursing_bardeen.migration - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Following unknown addresses are found in partition table sent from master[[127.0.0.1]:5704]. (Probably they have recently joined or left the cluster.) {
	[127.0.0.1]:5702 - d594f66e-5397-4d70-8030-741f2c444a27
	[127.0.0.1]:5703 - 2311a9e1-3881-4749-8314-1934e8cf0aa5
}
05:34:32,865  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [MigrationManager] hz.recursing_bardeen.migration - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Partition balance is ok, no need to repartition.
05:34:33,306  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftNodeImpl$LeaderFailureDetectionTask(METADATA)] hz.recursing_bardeen.partition-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Current leader RaftEndpoint{uuid='2311a9e1-3881-4749-8314-1934e8cf0aa5'} is not reachable. Will start new election round...
05:34:33,306  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftNode(METADATA)] hz.recursing_bardeen.partition-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] 

CP Group Members {groupId: METADATA(0), size:3, term:2, logIndex:56} [
	CPMember{uuid=d594f66e-5397-4d70-8030-741f2c444a27, address=[127.0.0.1]:5702}
	CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703}
	CPMember{uuid=e6275a2d-ffd3-4320-9381-a1dfecbd8adf, address=[127.0.0.1]:5704} - FOLLOWER this
]

05:34:33,306  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [PreVoteTask(METADATA)] hz.recursing_bardeen.partition-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Pre-vote started for next term: 3, last log index: 57, last log term: 2
05:34:33,306  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftNode(METADATA)] hz.recursing_bardeen.partition-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] 

CP Group Members {groupId: METADATA(0), size:3, term:2, logIndex:56} [
	CPMember{uuid=d594f66e-5397-4d70-8030-741f2c444a27, address=[127.0.0.1]:5702}
	CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703}
	CPMember{uuid=e6275a2d-ffd3-4320-9381-a1dfecbd8adf, address=[127.0.0.1]:5704} - FOLLOWER this
]

05:34:35,584  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [PreVoteTask(METADATA)] hz.recursing_bardeen.partition-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Pre-vote started for next term: 3, last log index: 57, last log term: 2
05:34:35,584  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [RaftNode(METADATA)] hz.recursing_bardeen.partition-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] 

CP Group Members {groupId: METADATA(0), size:3, term:2, logIndex:56} [
	CPMember{uuid=d594f66e-5397-4d70-8030-741f2c444a27, address=[127.0.0.1]:5702}
	CPMember{uuid=2311a9e1-3881-4749-8314-1934e8cf0aa5, address=[127.0.0.1]:5703}
	CPMember{uuid=e6275a2d-ffd3-4320-9381-a1dfecbd8adf, address=[127.0.0.1]:5704} - FOLLOWER this
]

05:34:35,597  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [NodeExtension] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
05:34:35,597  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 3003 ms.
05:34:35,597  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5702 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
05:34:35,597  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5704 is SHUTTING_DOWN
05:34:35,597  WARN |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Terminating forcefully...
05:34:35,597  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Shutting down connection manager...
05:34:35,597  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Shutting down node engine...
05:34:35,599  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [NodeExtension] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Destroying node NodeExtension.
05:34:35,599  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
05:34:35,599  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5704 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5704 is SHUTDOWN
05:34:35,599  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
05:34:35,599  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [Node] Thread-13485 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
05:34:35,599  INFO |when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot| - [LifecycleService] Thread-13485 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot(com.hazelcast.cp.internal.CPMemberAddRemoveTest): BuildInfo{version='5.2-SNAPSHOT', build='20220516', buildNumber=20220516, revision=504ac9f, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_snapshotIsTakenWhileRemovingCPLeader_newMemberInstallsSnapshot(com.hazelcast.cp.internal.CPMemberAddRemoveTest):'
05:32:15, accumulated pauses: 82 ms, max pause: 30 ms, pauses over 1000 ms: 0
05:32:20, accumulated pauses: 222 ms, max pause: 79 ms, pauses over 1000 ms: 0
05:32:25, accumulated pauses: 161 ms, max pause: 62 ms, pauses over 1000 ms: 0
05:32:30, accumulated pauses: 96 ms, max pause: 64 ms, pauses over 1000 ms: 0
05:32:35, accumulated pauses: 134 ms, max pause: 55 ms, pauses over 1000 ms: 0
05:32:40, accumulated pauses: 83 ms, max pause: 45 ms, pauses over 1000 ms: 0
05:32:45, accumulated pauses: 68 ms, max pause: 41 ms, pauses over 1000 ms: 0
05:32:50, accumulated pauses: 68 ms, max pause: 41 ms, pauses over 1000 ms: 0
05:32:55, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:00, accumulated pauses: 105 ms, max pause: 50 ms, pauses over 1000 ms: 0
05:33:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:10, accumulated pauses: 46 ms, max pause: 20 ms, pauses over 1000 ms: 0
05:33:15, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:25, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:30, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:35, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:40, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:45, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:50, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:33:55, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:34:00, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:34:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:34:10, accumulated pauses: 36 ms, max pause: 9 ms, pauses over 1000 ms: 0
05:34:15, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:34:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:34:25, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
05:34:30, accumulated pauses: 70 ms, max pause: 43 ms, pauses over 1000 ms: 0
05:34:35, accumulated pauses: 3 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

</details>

### PR DESCRIPTION
**Pull request by arodionov**
When the RaftNode state is restored from the `RaftLog`'s `SnapshotEntry`, further node's state updates also mutate the snapshot of the Metadata Raft group state (`MetadataRaftGroupSnapshot` class). If another RaftNode is restored from this mutated snapshot, it will not be in the expected state.

So, the `MetadataRaftGroupSnapshot` class should be immutable.

Fixes #21438
fixes https://github.com/hazelcast/hazelcast/issues/16574

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/cp/internal/MetadataRaftGroupSnapshot.java [hunk 1]
```diff
@@ -27,9 +27,15 @@
...
 import java.util.Set;
+import java.util.stream.Collectors;
+
+import static java.util.Collections.unmodifiableCollection;
+import static java.util.Collections.unmodifiableList;
+import static java.util.Collections.unmodifiableSet;
 
 /**
  * Snapshot of the Metadata Raft group state
+ * This class should be IMMUTABLE since it is stored in the RaftLog's SnapshotEntry
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/cp/internal/MetadataRaftGroupSnapshot.java:38]: what about making the class truly immutable? Set everything in `final` fields in the constructor, no setters at all.

**Review by vbekiaris — COMMENTED** [review]
that's a good catch, thanks for the fix.

File: hazelcast/src/main/java/com/hazelcast/cp/internal/MetadataRaftGroupSnapshot.java (hunk 1 above)
Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/MetadataRaftGroupSnapshot.java:38]: This class is serialisable, so we should rewrite their de-serialisation.
The current issue comes from the getter.

I'll take a look if it is possible to use only the constructor and deep copy the parameters.

Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/MetadataRaftGroupSnapshot.java:38]: ah right, 🤦 Let's just get rid of public setters to avoid accidental usage and use a constructor with all values as arguments in `MetadataRaftGroupManager#takeSnapshot`(like we do for other IDS classes - init via constructors with arguments at the point where it is created, use no-arg constructor just in IDS factory).

**Comment by vbekiaris** [comment]
run-lab-run

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/cp/internal/MembershipChangeSchedule.java [hunk 2]
```diff
@@ -163,11 +165,12 @@ public void readData(ObjectDataInput in) throws IOException {
             groupId = in.readObject();
             membersCommitIndex = in.readLong();
             int len = in.readInt();
-            members = new HashSet<>(len);
+            Set<RaftEndpoint> membersSet = new LinkedHashSet<>(len);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/cp/internal/MembershipChangeSchedule.java:168]: can you please add a simple note in the code for preference of LinkedHashSet over HashSet?

**Review by ahmetmircik — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/cp/internal/MembershipChangeSchedule.java (hunk 2 above)
Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/MembershipChangeSchedule.java:168]: Thanks, Ahmet, for the comment!
Have changed the implementation from `HashSet` to `LinkedHashSet`, because the actual type of `members` in the `CPGroupMembershipChange` constructor is `LinkedHashSet`. 
So when we restore the serialized `CPGroupMembershipChange` object with `HashSet`, the order of `members` has changed.
I will add this note to the code.

**Comment by arodionov** [comment]
run-lab-run

**Comment by arodionov** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
build failed with known test failure #21156, merging.
thanks for the fix @arodionov

**Comment by vbekiaris** [comment]
@arodionov do we need to backport this?

**Comment by arodionov** [comment]
> @arodionov do we need to backport this?

Yes, I think we need. They are planned by me.
