### PR TITLE
Revision on logic of choosing new address for owner connection

### LINKED ISSUE #12082: SHUFFLE_MEMBER_LIST javaDoc is wrong
[JavaDoc](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/spi/properties/ClientProperty.java#L30) should be fixed as shuffling is done when property is set to `true`.

- [x] Is this only wrong for java client? What about other clients?

### PR DESCRIPTION
**Pull request by sancar**
1. Duplicates in member list is removed.
2. The previously failed member will be last to be retried.

fixes #12082

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java [hunk 1]
```diff
@@ -901,32 +904,48 @@ public void run() {
...
 
+    private static <T> Set<T> shuffle(Set<T> set) {
+        List<T> shuffleMe = new ArrayList<T>(set);
+        Collections.shuffle(shuffleMe);
+        Set<T> shuffledSet = new LinkedHashSet<T>();
+        shuffledSet.addAll(shuffleMe);
+        return shuffledSet;
+    }
+
+    private void putPreviousOwnerAddressToLast(Set<Address> addresses) {
```
Comment (tkountis) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: I would add a small comment here, to make the reasoning visible to future refactorings

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java [hunk 2]
```diff
@@ -901,32 +904,53 @@ public void run() {
...
+        shuffledSet.addAll(shuffleMe);
+        return shuffledSet;
+    }
+
+    /**
+     * Previous owner address is moved to last item in set so that client will not try to connect to same one immediately.
+     * It could be the case that address is removed because it is healthy(it not responding to heartbeat/pings)
+     * In that case, trying other addresses first to upgrade make more sense.
+     */
+    private void putPreviousOwnerAddressToLast(Set<Address> addresses) {
```
Comment (ahmetmircik) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: changing method signature to accept `LinkedHashSet` instead of `Set` seems more appropriate if order is important. `Set` contract doesn't have an ordering guarantee per se.

Comment (sancar) [reply hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: It was `LinkedHashSet`, but checkstyle complained. :(

Comment (ahmetmircik) [reply hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: then maybe something like this: `assert addresses instanceOf LinkedHashSet`

Comment (Donnerbart) [reply hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: It's just a private method, so I think it's okay to enforce a `LinkedHashSet` if it's needed. We should not have this in "public" APIs though.

Maybe in this case a suppression via `@SuppressWarnings("checkstyle:...")` is better, since the `assert` will just be checked at runtime (and will decrease the code coverage, if not tested).

Comment (sancar) [reply hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnectionManagerImpl.java]: I would probably remove the method completely instead. It is just two lines anyway.
