### PR TITLE
Various fixes for updating job configuration [HZ-2253] [HZ-2264] [HZ-2271]

### LINKED ISSUE #24196: Provide more precise error when updating suspended JobConfig w/ unsupported option [HZ-2253]
**Describe the bug**
Given a suspended job, when updating the `JobConfig` via `ALTER JOB job_name OPTIONS ('optionKey'='value') RESUME`, if a valid `JobConfig` option is used that isn't supported by `DeltaJobConfig`, then a misleading error will occur (i.e.): 

`From line 1, column 33 to line 1, column 53: Unknown job option: processingGuarantee`

However the same option can be used in the `CREATE JOB ...` statement. IMO this behavior is misleading, because one will get the same message for a truly unknown job option (i.e.):

`From line 1, column 33 to line 1, column 40: Unknown job option: badOpt`

**Expected behavior**
Perhaps the message can be updated to distinguish known but unsupported options from those that are completely unknown. This will give the user a better idea that maybe the way they're trying to amend the `JobConfig` doesn't make sense.

**To Reproduce**

Attempt to `ALTER` a suspended job to run with an option defined in [JobConfig](https://docs.hazelcast.org/docs/5.3.0-SNAPSHOT/javadoc/com/hazelcast/jet/config/JobConfig.html) but not in [DeltaJobConfig](https://docs.hazelcast.org/docs/5.3.0-SNAPSHOT/javadoc/com/hazelcast/jet/config/DeltaJobConfig.html).

### LINKED ISSUE #24209: Updating Job 'timeoutMillis' via 'Job.updateConfig()' not working [HZ-2264]
**Describe the bug**
Given a cluster with a suspended job, using `job.updateConfig(deltaJobConfig)` and then resuming the job seems to have no effect.

**Expected behavior**
Job will be forcefully cancelled if the `timeoutMillis` specified in the `DeltaJobConfig` instance has elapsed since job submission.

**To Reproduce**
The following reproducer class demonstrates the issue. 

```
public class Main {
    public static void main(String[] args) throws InterruptedException {
        HazelcastInstance hz1 = Hazelcast.newHazelcastInstance();

        // Default JobConfig
        JobConfig jobConfig = new JobConfig();
        jobConfig.setName("my_job");

        Pipeline p = Pipeline.create();
        p.readFrom(TestSources.itemStream(1))
                .withoutTimestamps()
                .writeTo(Sinks.list("my_list"));

        Job job = hz1.getJet().newJob(p, jobConfig);
        waitForStatus(job, JobStatus.RUNNING);

        // Create DeltaJobConfig w/ 5 second timeout
        DeltaJobConfig djc = new DeltaJobConfig();
        djc.setTimeoutMillis(5000);

        // Suspend and apply the change
        job.suspend();
        waitForStatus(job, JobStatus.SUSPENDED);
        job.updateConfig(djc);

        // Resume and wait for job to fail (force-cancellation from timeout)
        job.resume();
        waitForStatus(job, JobStatus.FAILED);

        System.exit(0);
    }

    private static void waitForStatus(Job job, JobStatus expectedStatus) throws InterruptedException {
        for (JobStatus status; (status = job.getStatus()) != expectedStatus;) {
            Thread.sleep(10);
        }
    }
}
```

### LINKED ISSUE #24229: Updating Job 'splitBrainProtection' via 'Job.updateConfig()' not working [HZ-2271]
Describe the bug
Given a cluster with a suspended job, using job.updateConfig(deltaJobConfig) to update the `splitBrainProtection` setting and then resuming the job seems to have no effect.

Expected behavior
Job will run/not run based on the corresponding changes to `splitBrainProtection` in the updated config if the quorum is lost.

To Reproduce
The following reproducer class demonstrates the issue.

```
public static void main(String[] args) throws InterruptedException {
        HazelcastInstance hz1 = Hazelcast.newHazelcastInstance();
        HazelcastInstance hz2 = Hazelcast.newHazelcastInstance();

        JobConfig jobConfig = new JobConfig();
        jobConfig.setName("my_job");
        jobConfig.setSplitBrainProtection(true);


        Pipeline p = Pipeline.create();
        p.readFrom(TestSources.itemStream(1))
                .withoutTimestamps()
                .writeTo(Sinks.list("my_list"));

        Job job = hz1.getJet().newJob(p, jobConfig);
        waitForStatus(job, JobStatus.RUNNING);

        DeltaJobConfig djc = new DeltaJobConfig();
        djc.setSplitBrainProtection(false);

        // Suspend and apply the change
        job.suspend();
        waitForStatus(job, JobStatus.SUSPENDED);
        job.updateConfig(djc);

        job.resume();
        hz2.getLifecycleService().terminate();
        waitForStatus(job, JobStatus.NOT_RUNNING);
        waitForStatus(job, JobStatus.RUNNING);

        System.exit(0);
    }

    private static void waitForStatus(Job job, JobStatus expectedStatus) throws InterruptedException {
        for (JobStatus status; (status = job.getStatus()) != expectedStatus;) {
            Thread.sleep(10);
        }
    }
```

### PR DESCRIPTION
**Pull request by burakgok**
Provide more precise error for unsupported options in ALTER JOB [[HZ-2253]]
Add support for updating job timeout [[HZ-2264]]
Add support for updating split brain protection [[HZ-2271]]

Fixes #24196
Fixes #24209
Fixes #24229

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

[HZ-2253]: https://hazelcast.atlassian.net/browse/HZ-2253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HZ-2264]: https://hazelcast.atlassian.net/browse/HZ-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HZ-2271]: https://hazelcast.atlassian.net/browse/HZ-2271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ivanthescientist — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 1]
```diff
@@ -570,6 +570,10 @@ private void invokeStartExecution() {
                         responses);
 
         mc.setJobStatus(RUNNING);
+        if (mc.hasTimeout()) {
+            long remainingTime = mc.remainingTime(Clock.currentTimeMillis());
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:574]: why do you schedule timeout that late (after `InitExecutionOperation` completed on all nodes)?

Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:574]: btw, if the timeout is exceeded when the job is resumed, it should be not resumed at all instead of starting it and killing it 1ms later

Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:574]: also, in previous implemenation, timeout could terminate also a suspended job. Now it does not, if I see correctly.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 2]
```diff
@@ -772,6 +776,7 @@ void finalizeExecution(@Nullable Throwable failure) {
                 ) {
                     mc.setJobStatus(SUSPENDED, description, userRequested);
                     mc.jobExecutionRecord().setSuspended(null);
+                    mc.coordinationService().unscheduleJobTimeout(mc.jobId());
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:779]: in previous implementaion, timeout could terminate also a suspended job. Now it does not, if I see correctly. We should not change this behavior.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java [hunk 3]
```diff
@@ -1488,15 +1478,15 @@ public long[] findUnknownExecutions(long[] executionIds) {
         }).toArray();
     }
 
-    private void scheduleJobTimeout(final long jobId, final long timeout) {
+    void scheduleJobTimeout(final long jobId, final long timeout) {
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java:1481]: timeout could be ignored if it was very short and the job took long to start (for example there are a few IMap operation in between). we could fix this as well

Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java:1481]: in such case job should fail/be cancelled immediately

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (burakgok) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:574]: > why do you schedule timeout that late (after InitExecutionOperation completed on all nodes)?

1. The interval from the job submission to the job being reported as `RUNNING` is negligible for any reasonable timeout.
2. Starting the timeout just after setting the `RUNNING` status makes it more consistent. And there is a reason why we report `RUNNING` status so late: initializing the execution may fail on some nodes or the job termination may be requested just after initializing the execution. They are both addressed in the current implementation and we try to avoid glitchy status updates.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 2 above)
Comment (burakgok) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:779]: The original behavior doesn't make sense to me. We have the suspend-on-failure flag, which is used to re-run jobs by adding more resources or altering the configuration. Should the timeout continue during the maintenance? If this is the desired behavior, the suspend-on-failure shouldn't be used at all. Manually suspending a job implies even greater control and responsibility, in which we shouldn't interfere.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java (hunk 3 above)
Comment (burakgok) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java:1481]: Yes, theoretically, it can be "fixed," but specifying a timeout which is less than a second is a misuse.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:574]: Ad.1. If the job starts too slowly, it should be possible to abort it using timeout. If the job hangs in the initiliazation (eg. due to some network glitches), it will never be cancelled due to the timeout. So initialization time may not always be that short. As part of initialization we connect to Kafka or JDBC etc. 
Ad.2. Do you mean statuses like `NOT_RUNNING->STARTING->FAILED`? I think this is perfectly fine, some jobs may not start running or partially start, not only due to the timeout but also other errors (like connection errors). Job can be also manually cancelled when it is still STARTING. Jet handles such cases. 

I still do not like the idea of scheduling 1 ms timeout, if the remaining time is <=0. Canceling immediately is more explicit, but maybe more complicated.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 2 above)
Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: I can see that you restored original behavior. For the record: reliable tracking of remaining time is hard, we would have to store it somewhere and update it regularly so it can survive node crash. This is bigger topic: job resource consumption monitoring and limiting, and it can be not only run time, but also CPU usage, memory usage, io usage etc. Maybe we will implement something like that in future version.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:574]: I see we used the "hack" with 1ms timeout before, so for now we can leave it to not complicate the code now.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java (hunk 3 above)
Comment (k-jamroz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobCoordinationService.java:1481]: It was a problem because in previous PR version you passed negative timeout here, but that is no more possible.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (burakgok) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java]: You are right, timeout should cover the initialization as well. I restored the original behavior by scheduling the timeout at the of `MasterJobContext.tryStartJob()`.

**Review by k-jamroz — APPROVED** [review]
