### PR TITLE
CacheConfig propagation fixes

### LINKED ISSUE #11905: [cache] Implement delayed resolution for other types in CacheConfig
In addition to key and value types, the following need to be deferred:
```cacheLoaderFactory, cacheWriterFactory, expiryPolicyFactory and listenerConfigurations```
The above also rely for their classes to exist in current Class Loader and may not,
causing the node initialization failures.

There should be a similar fix for these as in key and value types.
Suggestion would be to transfer an array of bytes rather than objects for these values,
and actually de-serialize them only when needed.

Base issue: #8972 and PR https://github.com/hazelcast/hazelcast/pull/10874

Related Issue #10728
Related Pull Request https://github.com/hazelcast/hazelcast/pull/11513

### PR DESCRIPTION
**Pull request by vbekiaris**
- Deprecates CacheCreateConfigOperation due to unclear semantics; replaced by `AddCacheConfigOperation`, invoked cluster-wide with `invokeOnStableClusterSerial` to ensure all members become aware of new cache config's.
- Removes unused return value from `AbstractHazelcastCacheManager#createCacheConfig`
- Incorporates #12225 so that deferred resolution of classes is extended to cache loader/writer factories, expiry policy factory and cache entry listener configurations (previously it only applied to cache's KV types).

Supersedes #12225 
Fixes #11905 
EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/2016

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java [hunk 1]
```diff
@@ -69,6 +70,40 @@ protected void readKeyValueTypes(ObjectDataInput in)
         setValueClassName(in.readUTF());
     }
 
+    @Override
+    protected void writeFactories(ObjectDataOutput out) throws IOException {
+        SerializationService serializationService = out.getSerializationService();
+        out.writeData(lazyCacheLoaderFactory.getSerializedValue(serializationService));
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java]: I'm guessing previously the EE code serialised factories with :
```
out.writeObject(cacheLoaderFactory);
        out.writeObject(cacheWriterFactory);
        out.writeObject(expiryPolicyFactory);
```
This might be a problem. As I've detected in `com.hazelcast.enterprise.wan.operation.EWRPutOperation#writeInternal`, there is a difference in format between that and:
```
out.writeData(lazyCacheLoaderFactory.getSerializedValue(serializationService));
        out.writeData(cacheWriterFactory.getSerializedValue(serializationService));
        out.writeData(expiryPolicyFactory.getSerializedValue(serializationService));
```
The difference being that the serialization service additionally writes the partition hash. So some 3.9 member might now start getting this data with additionally the partition hash.
Actually I'm not 100% sure here so it may be best if you confirm this.

File: hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java [hunk 2]
```diff
@@ -46,25 +48,20 @@
...
      * The {@link javax.cache.configuration.Factory} for the {@link javax.cache.integration.CacheLoader}.
      */
-    protected Factory<CacheLoader<K, V>> cacheLoaderFactory;
+    protected DeferredValue<Factory<CacheLoader<K, V>>> lazyCacheLoaderFactory;
 
     /**
      * The {@link Factory} for the {@link javax.cache.integration.CacheWriter}.
      */
-    protected Factory<CacheWriter<? super K, ? super V>> cacheWriterFactory;
+    protected DeferredValue<Factory<CacheWriter<? super K, ? super V>>> cacheWriterFactory;
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java]: Minor: You can also rename the other `DeferredValue`s to lazy or revert the lazy one for consistency

File: hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java [hunk 3]
```diff
@@ -423,14 +430,23 @@ public boolean isStoreByValue() {
...
+    }
+
+    protected boolean hasListenerConfiguration() {
+        return listenerConfigurations != null && !listenerConfigurations.isEmpty();
+    }
+
     @Override
     public int hashCode() {
-        int result = cacheLoaderFactory != null ? cacheLoaderFactory.hashCode() : 0;
-        result = 31 * result + listenerConfigurations.hashCode();
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java]: Can we return some kind of hash codes from the deferred values? So we keep these fields in the hashCode/equals?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java [hunk 4]
```diff
@@ -0,0 +1,286 @@
...
+        DeferredValue<?> deferredValue = (DeferredValue<?>) o;
+
+        if (valueExists && deferredValue.valueExists) {
+            return value != null ? value.equals(deferredValue.value) : deferredValue.value == null;
+        }
+        if (serializedValueExists && deferredValue.serializedValueExists) {
+            return serializedValue != null ? serializedValue.equals(deferredValue.serializedValue)
+                    : deferredValue.serializedValue == null;
+        }
+        throw new IllegalArgumentException("Cannot compare serialized vs deserialized value");
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java]: Can this create an issue if we add a new listener configuration to the cache config which was deserialised (thus containing only serialised listener configurations)?

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/ByteArrayObjectDataOutput.java [hunk 5]
```diff
@@ -386,6 +386,12 @@ public void writeData(Data data) throws IOException {
         }
     }
 
+    @Override
+    public void writeObjectAsData(Object object) throws IOException {
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/ByteArrayObjectDataOutput.java]: Is this only used in tests?

File: hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java [hunk 6]
```diff
@@ -345,17 +356,19 @@ public void deleteCache(String cacheNameWithPrefix, String callerUuid, boolean d
 
     @Override
     public CacheConfig putCacheConfigIfAbsent(CacheConfig config) {
-        CacheConfig localConfig = configs.putIfAbsent(config.getNameWithPrefix(), config);
+        // ensure all configs registered in CacheService are not PreJoinCacheConfig's
+        CacheConfig cacheConfig = asCacheConfig(config);
```
[the remark this answers is not in the document]
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/AbstractCacheService.java]: Right

File: hazelcast/src/main/java/com/hazelcast/cache/impl/HazelcastServerCacheManager.java [hunk 7]
```diff
@@ -147,24 +155,32 @@ private void enableStatisticManagementOnOtherNodes(String cacheName, boolean sta
...
-        // In that case, scheduled thread is used, not operation thread.
-        InternalCompletableFuture future =
-                operationService.invokeOnTarget(CacheService.SERVICE_NAME, op, nodeEngine.getThisAddress());
-        if (syncCreate) {
-            return (CacheConfig<K, V>) future.join();
+    protected <K, V> void createCacheConfig(String cacheName,
+                                            CacheConfig<K, V> config,
+                                            boolean createAlsoOnOthers,
+                                            boolean syncCreate) {
+        Version clusterVersion = nodeEngine.getClusterService().getClusterVersion();
```
[the remark this answers is not in the document]
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/HazelcastServerCacheManager.java]: The `syncCreate` parameter here dictates whether we should wait for the operation to complete or not before returning, otherwise it would be a good deduplication opportunity.
edit: did a quick check, seems that `syncCreate` argument is effectively always `true`. I will double check and if confirmed, replace with the call to `cacheService`.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/JCacheDetector.java [hunk 8]
```diff
@@ -55,6 +57,18 @@ public static boolean isJCacheAvailable(ClassLoader classLoader) {
...
     public static boolean isJCacheAvailable(ClassLoader classLoader, ILogger logger) {
+        ClassLoader backupClassLoader = AccessController.doPrivileged(new PrivilegedAction<ClassLoader>() {
+            @Override
+            public ClassLoader run() {
+                return JCacheDetector.class.getClassLoader();
+            }
+        });
+        // try the class loader that loaded Hazelcast/JCacheDetector class
+        // if the thread-context class loader is too narrowly defined and doesn't contain JCache
+        return isJCacheAvailableInternal(classLoader, null) || isJCacheAvailableInternal(backupClassLoader, null);
```
[the remark this answers is not in the document]
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/JCacheDetector.java]: Good catch, need to pass the `logger` here instead of `null`.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java (hunk 1 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/PreJoinCacheConfig.java]: Good one, indeed this serialization block needs to be guarded with version checks to ensure compatibility during RU from 3.9.

File: hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java (hunk 3 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/config/AbstractCacheConfig.java]: Yes, `DeferredValue` implements `hashCode`, so I will restore those fields in the `hashCode` calculation

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/ByteArrayObjectDataOutput.java (hunk 5 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/ByteArrayObjectDataOutput.java]: Hm.. that was meant as the equivalent of `input.readDataAsObject` but after introduction of `DeferredValue` this is no longer needed so will be removed.

File: hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java (hunk 4 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/cache/impl/DeferredValue.java]: `CacheConfig.getListenerConfigurations().add(...)` is safe to use, however `CacheConfig.addCacheEntryListenerConfiguration` may hit this issue, as it adds the value directly in the set of `DeferredValue`s.

**Comment by vbekiaris** [comment]
thanks for the reviews @taburet @mmedenjak
