### PR TITLE
Fix errors when schema change enabled [5.2.z]

### LINKED ISSUE #22438: CDC "op is not a valid field name" during creation of ChangeRecord when "include.schema.changes" is set to true
**Describe the bug**
_com.hazelcast.jet.cdc.impl.ChangeRecordCdcSourceP#map_ expects that in _SourceRecord.value().values()_ will be "**op**" String to map operation.
For MySqlConnector and DebeziumCdcSources with property "include.schema.changes" set to true, the above code returns exception and job is in failed state as first command cannot be mapped.
Example operation which throws exception:
image 

Logs:
```
14:13:28,919 ERROR |someTest| - [JoinSubmittedJobOperation] hz.friendly_banzai.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.2.0-SNAPSHOT] Exception in ProcessorTasklet{08c4-b2db-9200-0001/mysql#0}: com.hazelcast.jet.JetException: Failed to connect to database
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{08c4-b2db-9200-0001/mysql#0}: com.hazelcast.jet.JetException: Failed to connect to database
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_345]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_345]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_345]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_345]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_345]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
Caused by: com.hazelcast.jet.JetException: Failed to connect to database
	at com.hazelcast.jet.cdc.impl.CdcSourceP.reconnect(CdcSourceP.java:214) ~[classes/:?]
	at com.hazelcast.jet.cdc.impl.CdcSourceP.complete(CdcSourceP.java:194) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[classes/:?]
	... 6 more
Caused by: org.apache.kafka.connect.errors.DataException: op is not a valid field name
	at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254) ~[connect-api-2.8.2.jar:?]
	at org.apache.kafka.connect.data.Struct.getCheckType(Struct.java:261) ~[connect-api-2.8.2.jar:?]
	at org.apache.kafka.connect.data.Struct.getString(Struct.java:158) ~[connect-api-2.8.2.jar:?]
	at com.hazelcast.jet.cdc.impl.ChangeRecordCdcSourceP.map(ChangeRecordCdcSourceP.java:67) ~[classes/:?]
```

**Expected behavior**
Above change can be mapped to _Operation.UNSPECIFIED_ (this status already exist)

**To Reproduce**

1. Go to 'com.hazelcast.jet.cdc.DebeziumCdcIntegrationTest'
2. Change _'include.schema.changes'_ from _'false'_ to _'true'_ in _DebeziumCdcIntegrationTest#mySqlSource_  method
3. Run _DebeziumCdcIntegrationTest#mysql_ test

**Additional context**
Found during testing on 5.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by TomaszGaweda**
By default, we disable this option in MySQL/PostgreSQL connector, but user still may use generic connector or other connector class. In that cases, our code was producing errors, because change schema connect records don't have before and after.

Backport of #22444
Fixes #22438

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [x] Send backports/forwardports if fix needs to be applied to past/future releases
- [x] New public APIs have `@Nonnull/@Nullable` annotations
- [x] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by TomaszGaweda** [comment]
run-lab-run

**Review by ldziedziul — APPROVED** [review]
LGTM

File: extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSourceP.java [hunk 1]
```diff
@@ -412,11 +414,20 @@ private static void log(ILogger logger, String name, String property, Object val
...
-    private static long extractTimestamp(SourceRecord record) {
-        if (record.valueSchema().field("ts_ms") == null) {
+    private static long extractTimestamp(SourceRecord sourceRecord) {
+        Schema valueSchema = sourceRecord.valueSchema();
+        boolean noValueTsMs = valueSchema.field(TIMESTAMP_MS_FIELD_NAME) == null;
+        boolean noSourceTsMs = valueSchema.field("source").schema().field(TIMESTAMP_MS_FIELD_NAME) == null;
+        if (noValueTsMs && noSourceTsMs) {
             return NO_NATIVE_TIME;
         }
-        Long timestamp = ((Struct) record.value()).getInt64("ts_ms");
```
Comment (orcunc) [inline extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/impl/CdcSourceP.java:419]: There is already a constant defined as TIMESTAMP_MS_FIELD_NAME. Maybe we can use it ?
