### PR TITLE
Inject HazelcastInstance in HazelcastInstanceAware commands

### LINKED ISSUE #9675: IScheduledExecutorService appears not to use HazelcastInstanceAware on local operations
Version: 3.8 EA

I've been using the IScheduledExecutorService which was added in Hazelcast 3.8. It appears that when operations are scheduled and executed on a single local node, that the HazelcastInstance does not get injected. An instance is injected if the task is submitted and executed on a remote node.

Sample reproduction case; console contains:

```
Testing via ExecutorService
Injected state: true
Testing via ScheduledExecutorService
Injected state: false
```

Expected:

```
Testing via ExecutorService
Injected state: true
Testing via ScheduledExecutorService
Injected state: true
```

Test case:

```java
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.HazelcastInstanceAware;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.Serializable;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;

import static org.junit.Assert.assertTrue;

public class HazelcastInstanceAwareTest {
    HazelcastInstance instance;

    @Before
    public void setup() {
        instance = Hazelcast.newHazelcastInstance();
    }

    @After
    public void teardown() throws Exception {
        instance.shutdown();
    }

    @Test
    public void test() throws ExecutionException, InterruptedException {
        System.err.println("Testing via ExecutorService");
        assertTrue(instance.getExecutorService("foo").submit((Callable<Boolean>) new AwareRunnable()).get());

        System.err.println("Testing via ScheduledExecutorService");
        instance.getScheduledExecutorService("bar").scheduleAtFixedRate(new AwareRunnable(), 0, 5, TimeUnit.SECONDS);

        Thread.sleep(TimeUnit.SECONDS.toMillis(10));
    }

    static class AwareRunnable implements Runnable, Callable<Boolean>, HazelcastInstanceAware, Serializable {
        private volatile HazelcastInstance instance;

        @Override
        public void setHazelcastInstance(final HazelcastInstance instance) {
            this.instance = instance;
        }

        @Override
        public void run() {
            call();
        }

        @Override
        public Boolean call() {
            final boolean injected = (instance != null);
            System.err.println("Injected state: " + injected);
            return injected;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by vbekiaris**
When a `HazelcastInstanceAware` command is passed as argument to one of the `schedule*` methods in `IScheduledExecutorService`, inject the `HazelcastInstance`.

In case the command is deserialized on another member, `HazelcastInstance` is already injected by https://github.com/vbekiaris/hazelcast/blob/d2694664aaf0d0e4bc9a8b792e300672cb0e48a2/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java#L268-L268 . However when the command is scheduled on the local member, `HazelcastInstance` was not injected at all.

Fixes #9675

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientScheduledFutureProxy.java [hunk 1]
```diff
@@ -186,7 +186,7 @@ public boolean isDone() {
     @Override
     public V get()
             throws InterruptedException, ExecutionException {
-        return this.get0().join();
+        return this.get0().get();
```
Comment (vbekiaris) [inline hazelcast-client/src/main/java/com/hazelcast/client/proxy/ClientScheduledFutureProxy.java]: `join` peels exceptions wrapped in `ExecutionException`s, so it would unwrap the exception in the received `ExecutionException`.

**Comment by vbekiaris** [comment]
Pushed an additional commit that:
* Splits `ScheduledExecutorServiceTest` to separate quick & slow tests. Quick test finishes (on my machine) in 20seconds. (fixes #9386)
* Removes `HazelcastInstance` constructor argument from `Callable`s/`Runnable`s that implement `HazelcastInstanceAware`
* Uses `InvocationFuture.get` instead of `join` to avoid peeling `ExecutionException`s in `IScheduledFuture.get` (fixes #9685)
* Enables two client-side ignored tests & introduces some minor clean ups in tests.
