### PR TITLE
Disables write-through and selection key wakeup with SELECT_WITH_FIX

### LINKED ISSUE #15628: SelectWithSelectorFix_TcpIpConnection_BasicTest.lastWriteTime_whenNothingWritten
_master_ (commit 05fb45237db1fff1e3212f8d56016f89dc2f4935)

Failed on CorrettoJDK11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-CorrettoJDK11/30/testReport/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/lastWriteTime_whenNothingWritten/

**Stacktrace**

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest$2.run(TcpIpConnection_AbstractTest.java:166)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1308)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1410)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest.connect(TcpIpConnection_AbstractTest.java:162)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractBasicTest.lastWriteTime_whenNothingWritten(TcpIpConnection_AbstractBasicTest.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
Hiccups measured while running test 'lastWriteTime_whenNothingWritten(com.hazelcast.internal.networking.nio.SelectWithSelectorFix_TcpIpConnection_BasicTest):'
06:46:50, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:46:55, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:00, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
06:47:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:10, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:15, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:20, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:25, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:30, accumulated pauses: 37 ms, max pause: 1 ms, pauses over 1000 ms: 0
06:47:35, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:40, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:45, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:50, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:47:55, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:00, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:05, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:10, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:15, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:20, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:25, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:30, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:35, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:40, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:45, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
06:48:50, accumulated pauses: 1225 ms, max pause: 1196 ms, pauses over 1000 ms: 1
06:48:55, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

### LINKED ISSUE #15706: SelectWithSelectorFix_TcpIpConnection_BasicTest.test_equals
_master_ (commit 4a6825bb471cedfd692ee970412fda34ab66c0d3)

Failed on ZingJDK8 : http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-ZingJDK8/94/testReport/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/test_equals/

**Stacktrace**
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest.lambda$connect$1(TcpIpConnection_AbstractTest.java:156)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1316)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1418)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTest.connect(TcpIpConnection_AbstractTest.java:154)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractBasicTest.test_equals(TcpIpConnection_AbstractBasicTest.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

### LINKED ISSUE #15840: SelectWithSelectorFix_TcpIpConnection_BasicTest.write_whenNonUrgent
```
Stacktrace
java.lang.AssertionError
```
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3951/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/write_whenNonUrgent/

### LINKED ISSUE #15941: SelectWithSelectorFix_TcpIpConnection_BasicTest. getRemoteSocketAddress
http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/4158/testReport/junit/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_BasicTest/getRemoteSocketAddress/

```
Stacktrace
java.lang.AssertionError
Standard Output
07:14:30,304  WARN |test_equals| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [4.0-SNAPSHOT] Disconnected address: [127.0.0.1]:5701
java.io.EOFException: Remote socket closed!
	at com.hazelcast.internal.networking.nio.NioInboundPipeline.process(NioInboundPipeline.java:116) ~[classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKey(NioThread.java:368) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.processSelectionKeys(NioThread.java:353) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.selectLoopWithFix(NioThread.java:293) [classes/:?]
	at com.hazelcast.internal.networking.nio.NioThread.run(NioThread.java:228) [classes/:?]
Finished Running Test: test_equals in 0.407 seconds.
07:14:30,304  WARN |test_equals| - [TcpIpConnectionErrorHandler] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [4.0-SNAPSHOT] Removing connection to endpoint [127.0.0.1]:5701 Cause => java.io.EOFException {Remote socket closed!}, Error-Count: 2
07:14:30,304  INFO |test_equals| - [MockIOService] hz.hz.IO.thread-in-0 - [LOCAL] [somegroup] [4.0-SNAPSHOT] Removing endpoint: [127.0.0.1]:5701
```

### LINKED ISSUE #15983: SelectWithSelectorFix_TcpIpConnection_TransferStressTest.testTinyPackets
master (commit a32c26cc24130659320a1aa8aa4940b53062ec35)

http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-nightly/288/testReport/com.hazelcast.internal.networking.nio/SelectWithSelectorFix_TcpIpConnection_TransferStressTest/testTinyPackets/

**Stacktrace**
```

java.lang.AssertionError: expected:<155083074> but was:<155074074>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTransferStressTest$1.run(TcpIpConnection_AbstractTransferStressTest.java:130)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1325)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1342)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTransferStressTest.testPackets(TcpIpConnection_AbstractTransferStressTest.java:120)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTransferStressTest.testPackets(TcpIpConnection_AbstractTransferStressTest.java:91)
	at com.hazelcast.internal.nio.tcp.TcpIpConnection_AbstractTransferStressTest.testTinyPackets(TcpIpConnection_AbstractTransferStressTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by vbekiaris**
Selector mode `SELECT_WITH_FIX` requires that a single thread accesses
the selector and its selection keys. This does not hold true when
write-through or selection key wake up optimizations are enabled, so
when `SELECT_WITH_FIX` selector mode is used, above optimizations are
disabled and a warning is logged.

Fixes #15706 
Fixes #15628 
Fixes #15840
Fixes #15983
Fixes #15941

### CODE REVIEW

**Comment by mmedenjak** [comment]
Nice work, do we need a backport?

**Comment by vbekiaris** [comment]
@mmedenjak thanks, backport is not needed. In 3.x [`NioOutboundPipeline#schedule`](https://github.com/hazelcast/hazelcast/blob/58295179f2be53f4d032aae6499cb4dc7c3f7c5c/hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioOutboundPipeline.java#L182) always adds a task to the `NioThread`'s queue and wakes up the selector; the shortcut was added in 4.0 with #15552.

**Comment by mmedenjak** [comment]
Does this also cover https://github.com/hazelcast/hazelcast/issues/15840?

**Comment by vbekiaris** [comment]
Yes, looks like the test failed due to the same reason

**Comment by tkountis** [comment]
Nice!

**Comment by pveentjer** [comment]
With the write through, a thread can also access the SelectionKey. So I believe also with write through this special selector mode could  lead to problems.

**Comment by pveentjer** [comment]
Oops..wrong button.

**Comment by mmedenjak** [comment]
I assume this also covers https://github.com/hazelcast/hazelcast/issues/15983

**Comment by sancar** [comment]
Might  be related https://github.com/hazelcast/hazelcast/issues/15941 ?

**Comment by vbekiaris** [comment]
@sancar  in `master` branch `SELECT_WITH_FIX` selector mode may fail to write some data, that's the reason why `SelectorWithFix` tests are failing. These will be addressed by this PR.

File: hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioNetworking.java [hunk 1]
```diff
@@ -465,8 +487,9 @@ public Context() {
             }
         }
 
-        public void setSelectionKeyWakeupEnabled(boolean selectionKeyWakeupEnabled) {
+        public Context selectionKeyWakeupEnabled(boolean selectionKeyWakeupEnabled) {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/internal/networking/nio/NioNetworking.java]: updated so it is suitable for chaining and renamed according to this class' method naming convention

**Comment by vbekiaris** [comment]
@tkountis @pveentjer could you review again?

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Merging as build failed with unrelated, expiration-related test failure  https://github.com/hazelcast/hazelcast/issues/15877 with several pauses.
