### PR TITLE
Various fixes for job status listeners [HZ-2162] [HZ-2182] [HZ-2195]

### LINKED ISSUE #23976: JobStatusListener continuously fires when quorum is lost [HZ-2162]
**Describe the bug**
Given a cluster with a running Jet job with `splitBrainProtection` enabled and a `JobStatusListener` registered for the job, if a member leaves the cluster, the listener will continuously receive events with status `NOT_RUNNING` even though no status change has occurred.

**Expected behavior**
When the member leaves, only a single event should fire for `STARTING -> NOT_RUNNING`.

**To Reproduce**

1. Run the attached [Member.java](https://github.com/hazelcast/hazelcast/files/10983053/Member.txt) (change from `.txt`)
2. Observe that the following will continuously print while the member is missing:
```
JobStatus changed: NOT_RUNNING -> NOT_RUNNING
JobStatus changed: NOT_RUNNING -> NOT_RUNNING
JobStatus changed: NOT_RUNNING -> NOT_RUNNING
JobStatus changed: NOT_RUNNING -> NOT_RUNNING
...
```

### LINKED ISSUE #24020: com.hazelcast.jet.JobStatusListenerTest.testLightListener_jobFails[onClient] [HZ-2195]
_master_ (commit fa2866756a08191e8fffc39f5755470236722652)

Failed on oracle-8 (little-endian): https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-nightly-little-endian/18/testReport/com.hazelcast.jet/JobStatusListenerTest/testLightListener_jobFails_onClient_/
<details><summary>Stacktrace:</summary>

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at com.hazelcast.test.HazelcastTestSupport.assertIterableEquals(HazelcastTestSupport.java:1001)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$assertIterableEqualsEventually$16(JobStatusListenerTest.java:325)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1277)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1381)
	at com.hazelcast.jet.JobStatusListenerTest.assertIterableEqualsEventually(JobStatusListenerTest.java:325)
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testLightListener_jobFails$10(JobStatusListenerTest.java:241)
	at com.hazelcast.jet.JobStatusListenerTest.testLightListener(JobStatusListenerTest.java:314)
	at com.hazelcast.jet.JobStatusListenerTest.testLightListener_jobFails(JobStatusListenerTest.java:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

```
</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: testListener_restartOnException[onClient] in 4.259 seconds.
Started Running Test: testLightListener_jobFails[onClient]
23:47:41,976 TRACE || - [ClientListenerService] hz.client_1918.eventRegistration- - hz.client_1918 [dev] [5.3.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.jet.impl.ClientJobProxy$1@63ff6050, handler=com.hazelcast.jet.impl.ClientJobProxy$ClientJobStatusEventHandler@571affa4} to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-03-17 23:47:41.972, lastWriteTime=2023-03-17 23:47:41.976, closedTime=never}}
23:47:41,977 TRACE || - [ClientListenerService] hz.client_1918.eventRegistration- - hz.client_1918 [dev] [5.3.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.jet.impl.ClientJobProxy$1@63ff6050, handler=com.hazelcast.jet.impl.ClientJobProxy$ClientJobStatusEventHandler@571affa4} to MockedClientConnection{localAddress=[127.0.0.1]:40001, super=ClientConnection{alive=true, connectionId=1, channel=null, remoteAddress=[127.0.0.1]:5701, lastReadTime=2023-03-17 23:47:41.977, lastWriteTime=2023-03-17 23:47:41.976, closedTime=never}}
23:47:41,977 TRACE || - [ClientListenerService] hz.client_1918.eventRegistration- - hz.client_1918 [dev] [5.3.0-SNAPSHOT] Register attempt of ClientListenerRegistration{codec=com.hazelcast.jet.impl.ClientJobProxy$1@63ff6050, handler=com.hazelcast.jet.impl.ClientJobProxy$ClientJobStatusEventHandler@571affa4} to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2023-03-17 23:47:41.974, lastWriteTime=2023-03-17 23:47:41.972, closedTime=never}}
23:47:41,977 DEBUG || - [Planner] hz.JobStatusListenerTest_pensive_curie.client.thread-1 - Watermarks in the pipeline will be throttled to 1000
23:47:41,977 TRACE || - [ClientListenerService] hz.client_1918.eventRegistration- - hz.client_1918 [dev] [5.3.0-SNAPSHOT] Registered ClientListenerRegistration{codec=com.hazelcast.jet.impl.ClientJobProxy$1@63ff6050, handler=com.hazelcast.jet.impl.ClientJobProxy$ClientJobStatusEventHandler@571affa4} to MockedClientConnection{localAddress=[127.0.0.1]:40002, super=ClientConnection{alive=true, connectionId=2, channel=null, remoteAddress=[127.0.0.1]:5702, lastReadTime=2023-03-17 23:47:41.977, lastWriteTime=2023-03-17 23:47:41.977, closedTime=never}}
23:47:41,979 DEBUG || - [LightMasterContext] hz.JobStatusListenerTest_pensive_curie.client.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Start executing light job 0990-bd07-4108-0002, execution graph in DOT format:
digraph DAG {
	"itemStream" [localParallelism=1];
	"noop" [localParallelism=1];
	"itemStream" -> "noop" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
23:47:41,979 DEBUG || - [LightMasterContext] hz.JobStatusListenerTest_pensive_curie.client.thread-1 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Building execution plan for 0990-bd07-4108-0002
23:47:41,979 DEBUG || - [LightMasterContext] hz.JobStatusListenerTest_pensive_curie.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Built execution plans for 0990-bd07-4108-0002
23:47:41,979 DEBUG || - [InitExecutionOperation] hz.JobStatusListenerTest_pensive_curie.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 0990-bd07-4108-0002, execution 0990-bd07-4108-0002 from [127.0.0.1]:5701
23:47:41,980 DEBUG || - [JobExecutionService] hz.JobStatusListenerTest_pensive_curie.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=0990-bd07-4108-0002, jobName='0990-bd07-4108-0002', executionId=0990-bd07-4108-0002 initialized, will start the execution
23:47:41,981 DEBUG || - [InitExecutionOperation] hz.JobStatusListenerTest_eloquent_curie.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Initializing execution plan for job 0990-bd07-4108-0002, execution 0990-bd07-4108-0002 from [127.0.0.1]:5701
23:47:41,982 DEBUG || - [JobExecutionService] hz.JobStatusListenerTest_eloquent_curie.cached.thread-12 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Execution plan for light job ID=0990-bd07-4108-0002, jobName='0990-bd07-4108-0002', executionId=0990-bd07-4108-0002 initialized, will start the execution
23:47:41,982 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Completed execution of job '0990-bd07-4108-0002', execution 0990-bd07-4108-0002
23:47:41,982 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5702 [dev] [5.3.0-SNAPSHOT] Execution of job '0990-bd07-4108-0002', execution 0990-bd07-4108-0002 completed
23:47:42,019 DEBUG || - [JobRepository] hz.JobStatusListenerTest_pensive_curie.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Job cleanup took 0ms
23:47:43,985  INFO || - [TaskletExecutionService] hz.JobStatusListenerTest_pensive_curie.jet.blocking.thread-0 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}
java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testLightListener_jobFails$648ca993$1(JobStatusListenerTest.java:232) ~[test-classes/:?]
	at com.hazelcast.jet.pipeline.test.TestSources$ItemStreamSource.fillBuffer(TestSources.java:236) ~[classes/:?]
	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:119) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_351]
23:47:43,988 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Completed execution of job '0990-bd07-4108-0002', execution 0990-bd07-4108-0002
23:47:43,988 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution of job '0990-bd07-4108-0002', execution 0990-bd07-4108-0002 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:783) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) ~[?:1.8.0_351]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:498) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:429) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:415) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:895) ~[?:1.8.0_351]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:369) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	... 1 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testLightListener_jobFails$648ca993$1(JobStatusListenerTest.java:232) ~[test-classes/:?]
	at com.hazelcast.jet.pipeline.test.TestSources$ItemStreamSource.fillBuffer(TestSources.java:236) ~[classes/:?]
	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:119) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	... 1 more
23:47:43,993 ERROR || - [InitExecutionOperation] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testLightListener_jobFails$648ca993$1(JobStatusListenerTest.java:232) ~[test-classes/:?]
	at com.hazelcast.jet.pipeline.test.TestSources$ItemStreamSource.fillBuffer(TestSources.java:236) ~[classes/:?]
	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:119) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[classes/:?]
	... 5 more
23:47:43,995 ERROR || - [SubmitJobOperation] hz.JobStatusListenerTest_pensive_curie.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.3.0-SNAPSHOT] Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
com.hazelcast.jet.JetException: Execution on a member failed: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.impl.LightMasterContext.findError(LightMasterContext.java:326) ~[classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.lambda$null$2(LightMasterContext.java:171) ~[classes/:?]
	at com.hazelcast.jet.impl.LightMasterContext.lambda$invokeOnParticipant$8(LightMasterContext.java:297) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode.lambda$execute$0(AbstractInvocationFuture.java:1570) ~[classes/:?]
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104) ~[test-classes/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_351]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_351]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_351]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_351]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_351]
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{0990-bd07-4108-0002/itemStream#0}: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.handleTaskletExecutionError(TaskletExecutionService.java:286) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService.access$600(TaskletExecutionService.java:80) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:325) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
Caused by: java.lang.ArithmeticException: / by zero
	at com.hazelcast.jet.JobStatusListenerTest.lambda$testLightListener_jobFails$648ca993$1(JobStatusListenerTest.java:232) ~[test-classes/:?]
	at com.hazelcast.jet.pipeline.test.TestSources$ItemStreamSource.fillBuffer(TestSources.java:236) ~[classes/:?]
	at com.hazelcast.function.BiConsumerEx.accept(BiConsumerEx.java:47) ~[classes/:?]
	at com.hazelcast.jet.impl.connector.ConvenientSourceP.complete(ConvenientSourceP.java:119) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.complete(ProcessorTasklet.java:541) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:421) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:291) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:315) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_351]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_351]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_351]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
23:47:45,320  INFO |testLightListener_jobFails[onClient]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 17 jobs in SimpleTestInClusterSupport.@After: [0990-bcfb-3bc9-0002, 0990-bcfb-3bc1-0002, 0990-bcfb-3bc0-0002, 0990-bcfb-3bc3-0002, 0990-bcfb-3bc4-0002, 0990-bcfb-3bc6-0002, 0990-bd07-4104-0002, 0990-bd07-4107-0002, 0990-bd07-4106-0002, 0990-bd07-4101-0002, 0990-bd07-4100-0002, 0990-bd07-4103-0002, 0990-bcef-10c9-0001, 0990-bcef-10c7-0001, 0990-bcef-10c4-0001, 0990-bcef-10c5-0001, 0990-bcef-10c2-0001]
23:47:45,340  INFO |testLightListener_jobFails[onClient]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 0 distributed objects in SimpleTestInClusterSupport.@After: []
BuildInfo right after testLightListener_jobFails[onClient](com.hazelcast.jet.JobStatusListenerTest): BuildInfo{version='5.3.0-SNAPSHOT', build='20230317', buildNumber=20230317, revision=fa28667, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testLightListener_jobFails[onClient](com.hazelcast.jet.JobStatusListenerTest):'
23:47:40, accumulated pauses: 1330 ms, max pause: 1287 ms, pauses over 1000 ms: 1
23:47:45, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test

```
</details>

Standard output can be found here - https://s3.console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-nightly-little-endian/18/

### PR DESCRIPTION
**Pull request by burakgok**
Eliminate unnecessary job status transitions [[HZ-2162]]
Avoid concurrent modification in log assertion [[HZ-2195]]
Wait for listener registration before tests [[HZ-2182]] [EE PR: hazelcast/hazelcast-enterprise#5879]

Fixes #23976
Fixes #24020
Fixes hazelcast/hazelcast-enterprise#5833

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

[HZ-2162]: https://hazelcast.atlassian.net/browse/HZ-2162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HZ-2182]: https://hazelcast.atlassian.net/browse/HZ-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HZ-2195]: https://hazelcast.atlassian.net/browse/HZ-2195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by k-jamroz — APPROVED** [review]

**Comment by k-jamroz** [comment]
> Fixes https://github.com/hazelcast/hazelcast-enterprise/issues/5833

After these changes you would get different exception, but the test still can fail.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java [hunk 1]
```diff
@@ -294,6 +296,33 @@ private void terminate(TerminationMode mode) {
...
+     * orderKey as job status events, and restoring Registration#listener during deserialization.
+     * The fastest and simplest solution is to assume optimistically that the job is still
+     * running and remove the listener if it turns out be completed.
+     */
+    @Override
+    public UUID addStatusListener(@Nonnull JobStatusListener listener) {
+        UUID registrationId = doAddStatusListener(listener);
+        String error;
+        try {
+            JobStatus status = getStatus();
```
Comment (k-jamroz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/AbstractJobProxy.java:315]: a race is still possible if the job terminates after `doAddStatusListener()` and before  `getStatus()`. Listener will be notified about the event (they may be not only terminal events) even though `addStatusListener` will throw `IllegalStateException`. Or do I miss something and `removeStatusListener` will be executed on the same thread where events for this job are processed?

anyway, this race does not seem so important

File: hazelcast/src/test/java/com/hazelcast/jet/JobStatusListenerTest.java [hunk 2]
```diff
@@ -263,8 +290,9 @@ protected static void assertHasNoListenerEventually(String jobIdString, UUID reg
         assertTrueEventually(() -> {
             assertTrue(Arrays.stream(instances()).allMatch(hz ->
                     getEventService(hz).getRegistrations(JobEventService.SERVICE_NAME, jobIdString).isEmpty()));
-            assertFalse(((ClientListenerServiceImpl) getHazelcastClientInstanceImpl(client()).getListenerService())
-                    .getRegistrations().containsKey(registrationId));
+            assertTrue(registrationId == null
+                    || !((ClientListenerServiceImpl) getHazelcastClientInstanceImpl(client()).getListenerService())
```
Comment (k-jamroz) [inline hazelcast/src/test/java/com/hazelcast/jet/JobStatusListenerTest.java:294]: this may fix error in `@After` but the tests still will fail if the job ends before listener is registered (it will not get any event or too few or listener registration will throw). Is it possible in heavily loaded CI server.

**Review by k-jamroz — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/jet/JobStatusListenerTest.java [hunk 3]
```diff
@@ -301,30 +282,40 @@ protected void testListener(Object source, Consumer<Job> test, String... log) {
...
+            assertEquals("length", actualCopy.size(), expected.length);
+            assertEquals(actualCopy, asList(expected));
         });
     }
 
-    protected static void assertIterableEqualsEventually(Iterable<?> actual, Object... expected) {
-        assertTrueEventually(() -> assertIterableEquals(actual, expected));
-    }
-
     @SafeVarargs
```
Comment (k-jamroz) [inline hazelcast/src/test/java/com/hazelcast/jet/JobStatusListenerTest.java:319]: `assertTailEqualsEventually` seems not to be needed anymore, can be removed (also from EE)

Comment (burakgok) [reply hazelcast/src/test/java/com/hazelcast/jet/JobStatusListenerTest.java:319]: It was added because `NOT_RUNNING` → `STARTING` and `STARTING` → `RUNNING` transitions might be missed. I confirmed that this is still the case by trying to remove it.

**Review by Fly-Style — APPROVED** [review]
