### PR TITLE
Quorum clean up

### LINKED ISSUE #12401: Quorum exceptions during rolling upgrade, when `IMap` quorum protection implementation has changed
Initial Cluster information
```
Size: 3
Version: Hazelcast 3.9.2
Client Count: 1
Client Docker : FROM openjdk:8-slim (debian)
Member Docker: FROM openjdk:8-jre (debian)
Client log level: DEBUG [slf4j]
Member log level: ALL [jdk]
```
Steps:
1. Sanity check, wait for initial cluster size to be 3 and all members `active`
2. Start client to generate traffic to 3.9.2 cluster
3. Drain 3.9.2 members 1 by 1, for each drain period, cluster is verified to have 3 members and all members are `active`
4. Collect Statistics

Sample statistics given below
```
Statistics QuorumStatistics(success=1172, failures=0, exceptions=0, quorumExceptions=20)
```
During RU, `Quorum exceptions` are not expected.
Logs and configs are attached
[Archive.zip](https://github.com/hazelcast/hazelcast/files/1741726/Archive.zip)
Logs for members are also follow RU pattern, which means member `1` is upgraded with `4`.
```
1->4
2->5
3->6
```

As can be seen `map` config changes between versions as below
```
3.9.2
 <map name="default">
        <statistics-enabled>false</statistics-enabled>
        <backup-count>1</backup-count>
        <quorum-ref>q3</quorum-ref>
    </map>
    <quorum enabled="true" name="q3">
        <quorum-size>2</quorum-size>
        <quorum-type>READ_WRITE</quorum-type>
    </quorum>
```
```
3.10-SNAPSHOT
<map name="default">
        <statistics-enabled>false</statistics-enabled>
        <backup-count>1</backup-count>
        <quorum-ref>q3</quorum-ref>
</map>
<quorum enabled="true" name="q3">
        <quorum-size>2</quorum-size>
        <quorum-type>READ_WRITE</quorum-type>
        <probabilistic-quorum heartbeat-interval-millis="100" acceptable-heartbeat-pause-millis="1250" max-sample-size="20" suspicion-threshold="20"/>
    </quorum>
```
Test flow code can be found [here](https://github.com/lazerion/hazelcast-qe/blob/master/it/shorten-split-brain-detection/runner/src/test/java/com/hazelcast/shorten/split/brain/it/runner/ShortenSplitBrainDetectionTest.java#L131-L181)

You can execute locally if you follow [this documentation](https://github.com/lazerion/hazelcast-qe/blob/master/it/shorten-split-brain-detection/README.md)

### PR DESCRIPTION
**Pull request by metanet**
* Custom quorum functions should consider the local member
* Minor clean up in QuorumService
* Ensure thread-safety of QuorumService internal state
* Minor refactoring in custom quorum impls

Fixes #12401

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/quorum/impl/AbstractPingAwareQuorumFunction.java [hunk 1]
```diff
@@ -76,13 +81,40 @@ public void onPingRestored(Member member) {
...
+
+    @Override
+    public void memberRemoved(MembershipEvent membershipEvent) {
+        if (pingFDEnabled) {
+            pingFailureDetector.remove(membershipEvent.getMember());
+        }
+    }
+
+    protected boolean isAlivePerIcmp(Member member) {
+        if (!pingFDEnabled || cluster.getLocalMember().equals(member)) {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/quorum/impl/AbstractPingAwareQuorumFunction.java]: even better is: `!pingFDEnabled || member.localMember()`

File: hazelcast/src/main/java/com/hazelcast/quorum/impl/AbstractPingAwareQuorumFunction.java [hunk 2]
```diff
@@ -76,13 +81,40 @@ public void onPingRestored(Member member) {
...
         return pingFailureDetector.isAlive(member);
     }
+
+    protected boolean isLocalDataMember(Member member) {
+        if (cluster == null) {
+            return false;
+        }
+
+        Member localMember = cluster.getLocalMember();
+        return !localMember.isLiteMember() && localMember.equals(member);
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/quorum/impl/AbstractPingAwareQuorumFunction.java]: `return !member.isLiteMember() && member.localMember();`

File: hazelcast/src/main/java/com/hazelcast/quorum/impl/ProbabilisticQuorumFunction.java [hunk 3]
```diff
@@ -66,34 +65,20 @@ public boolean apply(Collection<Member> members) {
             if (!isAlivePerIcmp(member)) {
                 continue;
             }
-            if (failureDetector.isAlive(member, timestamp)) {
+
+            if (isLocalDataMember(member) || failureDetector.isAlive(member, timestamp)) {
```
Comment (mdogan) [inline hazelcast/src/main/java/com/hazelcast/quorum/impl/ProbabilisticQuorumFunction.java]: We always call `apply(members)` with data members only. Only local-member check should be sufficient.
