### PR TITLE
[API-1526] Increase test timeout in the CompactSchemaReplicationStressTest

### LINKED ISSUE #22044: com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationStressTest.testSchemaReplication [API-1526]
_master_ (commit 111323fed8ce48bf807eeaad28dda838b4ff9346)

Failed on IbmJDK8: 
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/67/testReport/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationStressTest/testSchemaReplication_driverType_CLIENT_/
- https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-nightly/67/testReport/com.hazelcast.internal.serialization.impl.compact.schema/CompactSchemaReplicationStressTest/testSchemaReplication_driverType_MEMBER_/

Failed in variants `[driverType:CLIENT]` and `[driverType:MEMBER]`.

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:218)
	at java.lang.Thread.join(Thread.java:705)
	at com.hazelcast.internal.serialization.impl.compact.schema.CompactSchemaReplicationStressTest.testSchemaReplication(CompactSchemaReplicationStressTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:825)
```

</details>

Standard output can be found here https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-master-IbmJDK8-nightly/67/

### PR DESCRIPTION
**Pull request by mdumandag**
The test was failing regularly due to timeout errors. In the failing
runs, there were no kind of exceptions etc, and the test logic is
pretty simple. So, the test is probably failing due to timeout.

On my laptop, the test takes around 2 minutes to complete, and in
some nightly builds that I have examined, it was taking around
4 minutes. So, I think it is reasonable to think that test could
take more than 5 minutes in some nightly builds.

Therefore, in this PR, I increase the test timeout to 10 minutes,
and added logging to the drivers so that we can see the progress
in the logs, to make sure that the failures were indeed related
to timeouts.

Closes #22044

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/schema/CompactSchemaReplicationStressTest.java [hunk 1]
```diff
@@ -153,7 +157,11 @@ public void run() {
         }
 
         private void replicateSchemas() {
-            for (int i = 0; i < SCHEMA_COUNT ; i++) {
+            for (int i = 1; i <= SCHEMA_COUNT; i++) {
+                if (i % 10_000 == 0) {
```
Comment (ihsandemir) [inline hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/schema/CompactSchemaReplicationStressTest.java:161]: is 10000 too high? Total is 42000 and hence only 4 logs. May be you change to 2000 to see more  granular progress.

**Review by ihsandemir — APPROVED** [review]

**Review by srknzl — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/schema/CompactSchemaReplicationStressTest.java (hunk 1 above)
Comment (mdumandag) [reply hazelcast/src/test/java/com/hazelcast/internal/serialization/impl/compact/schema/CompactSchemaReplicationStressTest.java:161]: There are 30 drivers, so I didn't want to fill the logs with frequent updates.

I believe this is enough to see the progress
