### PR TITLE
Avoid NPE for mapContainer request during CREATE INDEX

### LINKED ISSUE #20171: NullPointerException when creating an index on an empty Map [SQL]
http://jenkins.hazelcast.com/view/stable/job/stable-x1/191/console

/disk1/workspace/stable-x1/5.1-SNAPSHOT/2021_12_13-10_09_09/sql-service

 CREATE INDEX mapBak1HD1ageIdx  ON mapBak1HD1 (age) TYPE SORTED
gives

com.hazelcast.sql.HazelcastSqlException
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:74)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:211)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:162)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:158)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:154)
	at com.hazelcast.sql.SqlService.execute(SqlService.java:89)
	at hzcmd.map.sql.service.CreateIndex.timeStep(CreateIndex.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at com.hazelcast.jet.sql.impl.PlanExecutor.execute(PlanExecutor.java:133)
	at com.hazelcast.jet.sql.impl.SqlPlanImpl$CreateIndexPlan.execute(SqlPlanImpl.java:269)
	at com.hazelcast.sql.impl.SqlServiceImpl.query0(SqlServiceImpl.java:248)
	at com.hazelcast.sql.impl.SqlServiceImpl.execute(SqlServiceImpl.java:198)

### PR DESCRIPTION
**Pull request by Fly-Style**
Fixes #20171.

### CODE REVIEW

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java [hunk 1]
```diff
@@ -130,6 +130,12 @@ SqlResult execute(CreateIndexPlan plan) {
             // common case. There's no atomic operation to create an index in IMDG, so it's not easy to
             // implement.
             MapContainer mapContainer = getMapContainer(hazelcastInstance.getMap(plan.mapName()));
+
+            // Very rare case, but still may happens...
+            if (mapContainer == null) {
+                throw QueryException.error("Can't create index: mapping '" + plan.mapName() + "' not initialized yet");
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/PlanExecutor.java:136]: We must create the index also in this case. The fix might be using `MapServiceContext.getMapContainer(mapName)` instead of `MapServiceContext.getMapContainers().get(mapName)`, as we're doing currently.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

**Review by viliam-durina — APPROVED** [review]
