### PR TITLE
Await MapStore initialization before tests [HZ-1695]

### LINKED ISSUE #21993: com.hazelcast.mapstore.mysql.MySQLGenericMapStoreTest.whenMapStoreDestroy_thenDropMapping [HZ-1695]
_master_ (commit 5bcb6c0fa7d5f3ea4b5f8ad912d87a6be8fb60f8)

Failed on IbmJDK8 in FIPS mode: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-IbmJDK8-fips-nightly/451/testReport/com.hazelcast.mapstore.mysql/MySQLGenericMapStoreTest/whenMapStoreDestroy_thenDropMapping/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: 

Expecting:
  <[Row{[__map-store.people_o_9fc9eee5_5097_46f0_8f2d_5277831d7749]},
    Row{[__map-store.people_o_e8977381_2561_41fc_ba89_e908002aa76c]}]>
to contain exactly in any order:
  <[Row{[__map-store.people_o_9fc9eee5_5097_46f0_8f2d_5277831d7749]}]>
but the following elements were unexpected:
  <[Row{[__map-store.people_o_e8977381_2561_41fc_ba89_e908002aa76c]}]>

	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:321)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsAnyOrder(SqlTestSupport.java:283)
	at com.hazelcast.mapstore.GenericMapStoreTest.lambda$awaitMappingCreated$6(GenericMapStoreTest.java:627)
	at com.hazelcast.mapstore.GenericMapStoreTest$$Lambda$2532/0000000018014930.run(Unknown Source)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1236)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1253)
	at com.hazelcast.mapstore.GenericMapStoreTest.awaitMappingCreated(GenericMapStoreTest.java:626)
	at com.hazelcast.mapstore.GenericMapStoreTest.whenMapStoreDestroy_thenDropMapping(GenericMapStoreTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.lang.Thread.run(Thread.java:822)
```

</details>

<details><summary>Standard output:</summary>

```
07:43:17,166 DEBUG || - [GenericMapStore] hz.friendly_jang.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.2-SNAPSHOT] Initializing for map people_o_9fc9eee5_5097_46f0_8f2d_5277831d7749
07:43:22,264  INFO |whenMapStoreDestroy_thenDropMapping| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
07:43:22,264  INFO |whenMapStoreDestroy_thenDropMapping| - [SqlTestSupport] Time-limited test - Removing 0 cached plans in SqlTestSupport.@After
07:43:22,265  INFO |whenMapStoreDestroy_thenDropMapping| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
07:43:22,266  INFO |whenMapStoreDestroy_thenDropMapping| - [SimpleTestInClusterSupport] Time-limited test - Destroying 1 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:mapService/__sql.catalog]
BuildInfo right after whenMapStoreDestroy_thenDropMapping(com.hazelcast.mapstore.mysql.MySQLGenericMapStoreTest): BuildInfo{version='5.2-SNAPSHOT', build='20220816', buildNumber=20220816, revision=5bcb6c0, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'whenMapStoreDestroy_thenDropMapping(com.hazelcast.mapstore.mysql.MySQLGenericMapStoreTest):'
07:43:15, accumulated pauses: 57 ms, max pause: 11 ms, pauses over 1000 ms: 0
07:43:20, accumulated pauses: 7 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

</details>

### PR DESCRIPTION
**Pull request by burakgok**
Some tests in `GenericMapStoreTest` seemingly end before MapStore is initialized, which prevents the mapping from being destroyed by `SimpleTestInClusterSupport#supportAfter`.

Additionally, some refactoring is done.

Fixes #21993

### CODE REVIEW

File: extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java [hunk 1]
```diff
@@ -611,6 +604,7 @@ private <K> GenericMapStore<K> createMapStore(Properties properties, HazelcastIn
 
         GenericMapStore<K> mapStore = new GenericMapStore<>();
         mapStore.init(instance, properties, mapName);
+        mapStore.awaitInitFinished();
```
Comment (frant-hartm) [inline extensions/mapstore/src/test/java/com/hazelcast/mapstore/GenericMapStoreTest.java:607]: Some tests intentionally fail to create the mapping, so the `awaitInitFinished` throws an exception. See the failed tests.

**Review by frant-hartm — CHANGES_REQUESTED** [review]

**Comment by krzysztofslusarski** [comment]
run-lab-run

**Review by frant-hartm — APPROVED** [review]

**Review by krzysztofslusarski — APPROVED** [review]

**Comment by frant-hartm** [comment]
run-lab-run
