### PR TITLE
Fix small issues with FlakeIdGenerator

### LINKED ISSUE #14397: small flake id generator issues
I have found some small issues regarding to flake id generator.

- `FlakeIdGenerator` documentation [states that ](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/flakeidgen/FlakeIdGenerator.java#L67) `NodeIdOutOfRangeException` is thrown if node ID for all members in the cluster is out of valid range. However, when the client requests a new flake id in this case, `HazelcastException` is thrown instead from [this](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/flakeidgen/impl/FlakeIdGeneratorProxy.java#L260) line. See this [test](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/flakeidgen/impl/FlakeIdGenerator_NodeIdOverflowIntegrationTest.java#L72). Either the documentation or the behavior should change.

- Clients can assign negative values for `prefetchValidityMillis` but the members can't. See [client](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/config/ClientFlakeIdGeneratorConfig.java#L108) and [member](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java#L162) sides.

- There is no need for the maximum operation done [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java#L120) and [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/config/ClientFlakeIdGeneratorConfig.java#L73) since one cannot assign a `prefetchCount` out of the `0 < prefetchCount <= MAXIMUM_PREFETCH_COUNT` range. (See [this](https://github.com/hazelcast/hazelcast/blob/master/hazelcast-client/src/main/java/com/hazelcast/client/config/ClientFlakeIdGeneratorConfig.java#L84) and [this](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/config/FlakeIdGeneratorConfig.java#L135))

### PR DESCRIPTION
**Pull request by viliam-durina**
- fix javadoc that HazelcastException is thrown and not
NodeIdOutOfRangeException. Reason: NodeIdOutOfRangeException is in
`impl` package, we don't want users to catch it, it's internal. Also
there's no specific action the user code could take to fix the problem,
other than logging it and failing

- allov negative `prefetchValidityMillis` in client config to make it
equivalent to the member config

- remove redundant `Math.max`

Fixes #14397

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java [hunk 1]
```diff
@@ -328,6 +328,11 @@
 
     /**
      * Returns all {@link DistributedObject}'s such as; queue, map, set, list, topic, lock, multimap.
+     * <p>
+     * The results are returned on a best-effort basis. The result might miss
+     * just-created objects and contain just-deleted objects. An existing
+     * object can also be missing from the list occasionally. One cluster
+     * member is queried to obtain the list.
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java]: Should "one cluster member is queried" be really part of the method's contract? I am not expecting this to change anytime soon, but it feels like an implementation detail.

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/core/HazelcastInstance.java]: It's a performance hint. If you want to use this method frequently, you'd like to know this.
