### PR TITLE
client tests mock network internal address list leak fixed

### LINKED ISSUE #6991: ClientRegressionWithMockNetworkTest.*
This is a failure from my local runs, so no CloudBees link is available.

```
java.lang.AssertionError
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:582)
    at com.hazelcast.client.ClientRegressionWithMockNetworkTest.testLock_WhenDummyClientAndOwnerNodeDiesTogether(ClientRegressionWithMockNetworkTest.java:563)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:132)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at com.hazelcast.test.HazelcastParallelClassRunner.access$301(HazelcastParallelClassRunner.java:46)
    at com.hazelcast.test.HazelcastParallelClassRunner$TestRunner.run(HazelcastParallelClassRunner.java:139)
    at java.lang.Thread.run(Thread.java:745)
```

https://gist.github.com/Donnerbart/aaed8a5ed47ea92d327f

The failing assert is this one:

```
assertTrue(lock.tryLock(1, TimeUnit.MINUTES));
```

### PR DESCRIPTION
**Pull request by asimarslan**
fixes #6991

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java [hunk 1]
```diff
@@ -49,6 +49,7 @@
 import com.hazelcast.test.annotation.NightlyTest;
 import com.hazelcast.test.annotation.ParallelTest;
 import com.hazelcast.test.annotation.QuickTest;
+import com.hazelcast.test.annotation.Repeat;
```
Comment (Donnerbart) [inline hazelcast-client/src/test/java/com/hazelcast/client/ClientRegressionWithMockNetworkTest.java]: Left-over?

**Comment by Donnerbart** [comment]
:+1: (once green)

**Comment by Donnerbart** [comment]
run-lab-run
