### PR TITLE
invalidate near client cache after execute on keys operation

### LINKED ISSUE #15468: Client near cache is not invalidated after IMap.executeOnKeys
This test fails:

```java
    @Test
    public void executeOnKeysInvalidation() {
        HazelcastInstance server = hazelcastFactory.newHazelcastInstance();
        ClientConfig clientConfig = new ClientConfig().addNearCacheConfig(new NearCacheConfig("map"));
        HazelcastInstance client = hazelcastFactory.newHazelcastClient(clientConfig);
        IMap<String, String> map = client.getMap("map");
        map.put("key", "value1");
        map.get("key"); // put the key to near cache
        map.executeOnKeys(singleton("key"), entry -> {
            entry.setValue("value2");
            return null;
        });
        assertEquals("value2", map.get("key"));
    }
```

```
org.junit.ComparisonFailure: 
Expected :value2
Actual   :value1
```

### PR DESCRIPTION
**Pull request by alex-dukhno**
This PR is the fix for #15468. Due to the fact that result of computation was the `null` hazelcast hasn't send updated value to a client.

I included tests with `null` result and with not-`null` result different from new cache value

closes #15468

### CODE REVIEW

**Comment by alex-dukhno** [comment]
Hi @viliam-durina, can you please take a look?
Thanks

**Comment by viliam-durina** [comment]
Someone from IMDG team should have a look.

File: hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperator.java [hunk 1]
```diff
@@ -204,6 +204,9 @@ public Object getOldValue() {
     }
 
     public Data getResult() {
+        if (result == null) {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperator.java]: Caller should do invalidations on its own end. Returning a not null result from server hides actual issue (also will cause unexpected serialization costs). Do you mind to investigate `NearCachedMapProxyImpl` and apply same logic to `NearCachedClientMapProxy`?

Comment (alex-dukhno) [reply hazelcast/src/main/java/com/hazelcast/map/impl/operation/EntryOperator.java]: Thanks for advice! I updated the code accordingly.

**Comment by sancar** [comment]
@alex-dukhno On the `NearCachedMapProxyImpl` ,  `serializeKeys` is also used. 
```
 @Override
    public <R> InternalCompletableFuture<Map<K, R>> submitToKeysInternal(Set<K> keys,
                                                                         Set<Data> dataKeys,
                                                                         EntryProcessor<K, V, R> entryProcessor) {
        if (serializeKeys) {
            toDataCollectionWithNonNullKeyValidation(keys, dataKeys);
        }
        try {
            return super.submitToKeysInternal(keys, dataKeys, entryProcessor);
        } finally {
            Set<?> ncKeys = serializeKeys ? dataKeys : keys;
            for (Object key : ncKeys) {
                invalidateNearCache(key);
            }
        }
    }
```

Same config also available on the client side. To have a consistent behaviour, you are gonna need to use it also. And can you also add a related test to see the failure. When `NearCacheConfig.setSerializeKeys` is set, we store the near cached keys as data locally. If I am not mistaken, When it is set, this submitToKey implementation will not validate the keys since keys will not match the ones in the nearcache.

**Comment by alex-dukhno** [comment]
@sancar added test case with the fix for `serializeKeys`

**Comment by sancar** [comment]
Thanks @alex-dukhno

File: hazelcast/src/main/java/com/hazelcast/client/impl/proxy/NearCachedClientMapProxy.java [hunk 2]
```diff
@@ -481,6 +482,26 @@ public LocalMapStats getLocalMapStats() {
...
+                                                                 @Nonnull EntryProcessor<K, V, R> entryProcessor) {
+        checkNotNull(keys, NULL_KEY_IS_NOT_ALLOWED);
+
+        Set<?> nearCacheKeys = serializeKeys
+            ? keys.stream().map(this::toNearCacheKey).collect(Collectors.toSet())
+            : keys;
+
+        InternalCompletableFuture<Map<K, R>> response;
+        try {
+            response = super.submitToKeys(keys, entryProcessor);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/client/impl/proxy/NearCachedClientMapProxy.java]: if `serializeKeys` is true, we serialize all keys to convert them to near-cache keys. But here, in `super.submitToKeys`, we also do an extra serialization for all passed `keys` before sending them to server. This means we do same thing twice. This could have been done as in this commit: https://github.com/hazelcast/hazelcast/commit/57f09edf8015099eeefb1a98eb9efbbfaf30f060

Can you please also address this double serialization problem?

Comment (alex-dukhno) [reply hazelcast/src/main/java/com/hazelcast/client/impl/proxy/NearCachedClientMapProxy.java]: patch is applied. Thanks

**Comment by sancar** [comment]
run-lab-run

**Comment by ahmetmircik** [comment]
@alex-dukhno thanks for the fix.
