### PR TITLE
Check the taken session id and ignore its invalidation if it is already invalidated inside Hazelcast's session inside `WebFilter::readSessionFromLocal`

### LINKED ISSUE #6335: Session already invalidated in JBOOS - WILDFLY
Hello, my problem is in server jboos - wildlfy9, I'm using hazelcast version 3.5.2

I'm try session  session-fixation-protection all options how : "none", migratedSession, "changeSessionId","newSession" not working any.

This error is using the example spring-security 

https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/spring-security

2015-10-01 00:06:08,614 ERROR [io.undertow.request] (default task-7) UT005023: Exception handling request to /spring-security/j_spring_security_check: java.lang.IllegalStateException: UT000021: Session already invalidated
	at io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:484)
	at io.undertow.server.session.InMemorySessionManager$SessionImpl.invalidate(InMemorySessionManager.java:473)
	at io.undertow.servlet.spec.HttpSessionImpl.invalidate(HttpSessionImpl.java:199)
	at com.hazelcast.web.WebFilter$RequestWrapper.readSessionFromLocal(WebFilter.java:492)
	at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:461)
	at com.hazelcast.web.WebFilter$RequestWrapper.getSession(WebFilter.java:392)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)
	at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:270)
at org.springframework.security.web.authentication.session.SessionFixationProtectionStrategy.applySessionFixation(SessionFixationProtectionStrategy.java:94)
	at org.springframework.security.web.authentication.session.AbstractSessionFixationProtectionStrategy.onAuthentication(AbstractSessionFixationProtectionStrategy.java:82)
	at org.springframework.security.web.authentication.session.SessionFixationProtectionStrategy.onAuthentication(SessionFixationProtectionStrategy.java:55)
	at org.springframework.security.web.authentication.session.CompositeSessionAuthenticationStrategy.onAuthentication(CompositeSessionAuthenticationStrategy.java:83)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:216)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at com.hazelcast.web.WebFilter.doFilter(WebFilter.java:353)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by serkan-ozal**
Even though session can be taken from request, it might be already invalidated.

For example, in Wildfly (uses Undertow), taken wrapper session might be valid but its underlying real session might be already invalidated after redirection due to its request/url based wrapper session (points to same original session) design. Therefore, we check the taken session id and ignore its invalidation if it is already invalidated inside Hazelcast's session.

Fixes #6335

### CODE REVIEW

File: hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java [hunk 1]
```diff
@@ -475,14 +476,21 @@ private HazelcastHttpSession readSessionFromLocal() {
...
-                originalSession.invalidate();
+                // Even though session can be taken from request, it might be already invalidated.
+                // For example, in Wildfly (uses Undertow), taken wrapper session might be valid
+                // but its underlying real session might be already invalidated after redirection
+                // due to its request/url based wrapper session (points to same original session) design.
+                // Therefore, we check the taken session id and
+                // ignore its invalidation if it is already invalidated inside Hazelcast's session.
+                // See issue on Wildfly https://github.com/hazelcast/hazelcast/issues/6335
+                if (!originalSession.getId().equals(invalidatedOriginalSessionId)) {
+                    originalSession.invalidate();
```
Comment (bilalyasar) [inline hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java]: why we don't have `originalSessions.remove(originalSession.getId());` here?

Comment (serkan-ozal) [inline hazelcast-wm/src/main/java/com/hazelcast/web/WebFilter.java]: when code reached here it is obvious that `originalSession.getId()` is not in `originalSessions` so it was redundant and removed it.
Check this code snippet before here:
``` java
String hazelcastSessionId = originalSessions.get(originalSession.getId());
if (hazelcastSessionId != null) {
    ...
    return
}
```

**Comment by mesutcelik** [comment]
:+1:

**Comment by kobalski** [comment]
:+1:  We should also have back port of this fix.

**Comment by serkan-ozal** [comment]
ok, will send also backport
