### PR TITLE
Memcache: BulkGet implemented as a single command

### LINKED ISSUE #9637: MemcacheTest.testBulkSetGet_withManyKeys
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/6683/testReport/junit/com.hazelcast.internal.ascii/MemcacheTest/testBulkSetGet_withManyKeys/

Regression

Timeout waiting for bulk values: waited 216,000 ms. Node status: Connection Status { /127.0.0.1:5703 active: true, authed: true, last read: 215,997 ms ago }
Stacktrace

net.spy.memcached.OperationTimeoutException: Timeout waiting for bulk values: waited 216,000 ms. Node status: Connection Status { /127.0.0.1:5703 active: true, authed: true, last read: 215,997 ms ago }
	at net.spy.memcached.internal.BulkGetFuture.get(BulkGetFuture.java:126)
	at net.spy.memcached.internal.BulkGetFuture.get(BulkGetFuture.java:51)
	at net.spy.memcached.MemcachedClient.getBulk(MemcachedClient.java:1465)
	at net.spy.memcached.MemcachedClient.getBulk(MemcachedClient.java:1509)
	at net.spy.memcached.MemcachedClient.getBulk(MemcachedClient.java:1523)

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #9637

The old implementation generated PartialGetCommand per each key
and EndCommand. Commands are executed on a multi-threaded
executor service: PartialGetCommand can be re-ordered with EndCommand.

The new implementation has 2 advantages
1. Uses map.getAll() <- it gives better performance than calling get() per each key
2. Having a single command eliminates races.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/EntryConverter.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        }
+
+        MemcacheEntry entry = null;
+        if (value instanceof MemcacheEntry) {
+            entry = (MemcacheEntry) value;
+        } else if (value instanceof byte[]) {
+            entry = new MemcacheEntry(key, ((byte[]) value), 0);
+        } else if (value instanceof String) {
+            entry = new MemcacheEntry(key, stringToBytes((String) value), 0);
+        } else {
```
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/EntryConverter.java]: Can't the value be Data?

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/internal/ascii/memcache/EntryConverter.java]: it should not. it uses a regular IMap proxy and proxy never exposes Data to users.

File: hazelcast/src/test/java/com/hazelcast/util/collection/InternalSetMultiMapTest.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+        assertThat(results, hasSize(1));
+        assertThat(results, contains("value"));
+    }
+
+    @Test
+    public void entrySet_whenEmpty_thenReturnEmptySet() {
+        Set<?> entries = multiMap.entrySet();
+        assertThat(entries, hasSize(0));
+    }
+}
```
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/util/collection/InternalSetMultiMapTest.java]: Maybe a separate integration test doing a round-trip from a client wouldn't be a bad idea? :)

Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/util/collection/InternalSetMultiMapTest.java]: we already have an [integration test](https://github.com/jerrinot/hazelcast/blob/f87f2b5989350fd466fd5818f6d6619ae4166324/hazelcast/src/test/java/com/hazelcast/internal/ascii/MemcacheTest.java#L58-L58) - that's how this all started - @mdogan had added new tests and they failed occasional.

Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/util/collection/InternalSetMultiMapTest.java]: ok 👍
