### PR TITLE
Fix OS process & system load metrics display issues

### LINKED ISSUE #12190: HealthMonitor reports load statistics incorrectly
```
HealthMonitor||[xxx]:5704 [dev] [3.9.2] ...
, load.process=0.02%, load.system=0.70%, load.systemAverage=2435.00%
...
```

Here the process cpu was 2% not 0.02%, and overall machine/server cpu 70% not 0.7%.

The values the JVM reports are between 0.0 and 1.0 - not 0 and 100 percent.

https://github.com/hazelcast/hazelcast/blob/8c4f4859c24d944361cb0100323d48590d856281/hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java#L59

https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad--

### PR DESCRIPTION
**Pull request by mdogan**
- os.systemLoadAverage is not a percentage, removed `%` sign.
- os.processCpuLoad & os.systemCpuLoad are reported between [0, 1] range.
Multiplied their results with 100.

Fixes #12190

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java [hunk 1]
```diff
@@ -72,6 +72,11 @@ public double get(OperatingSystemMXBean bean) {
     // This method doesn't depend on the OperatingSystemMXBean so it can be tested. Due to not knowing
     // the exact OperatingSystemMXBean class it is very difficult to get this class tested.
     static void registerMethod(MetricsRegistry metricsRegistry, Object osBean, String methodName, String name) {
+        registerMethod(metricsRegistry, osBean, methodName, name, 1);
+    }
+
+    private static void registerMethod(MetricsRegistry metricsRegistry, Object osBean, String methodName,
+            String name, final long multiplier) {
```
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java]: Do we need this `final` here?

Comment (mdogan) [reply hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java]: Yes, unless you use Java 8 compiler.

Comment (Donnerbart) [reply hazelcast/src/main/java/com/hazelcast/internal/metrics/metricsets/OperatingSystemMetricSet.java]: Ah, now I see it. Was just a bit difficult to spot on GitHub :)
