### PR TITLE
Wildcard usage for query cache configuration at the client does not work as expected

### LINKED ISSUE #9990: [query-cache] Client side query cache xml configuration no supporting * in query-cache mapName="*"
version 3.8

Client size xml config
```
<query-caches>
        <query-cache mapName="queryCacheMapBak1HD*"  name="queryCacheMapBak1HD_query-cache">
            <in-memory-format>OBJECT</in-memory-format>
            <buffer-size>50</buffer-size>
            <batch-size>5</batch-size>
            <delay-seconds>0</delay-seconds>
            <coalesce>true</coalesce>
            <include-value>true</include-value>
            <populate>true</populate>
            <predicate type="class-name">hzcmd.map.cqc.PersonIdPredicate</predicate>
        </query-cache>
    </query-caches>
```

member size config
```
<map name="queryCacheMapBak1HD*">
        <backup-count>1</backup-count>
        <in-memory-format>NATIVE</in-memory-format>
        <eviction-policy>LRU</eviction-policy>
        <max-size policy="FREE_NATIVE_MEMORY_PERCENTAGE">15</max-size>
        <hot-restart enabled="false">
            <fsync>false</fsync>
        </hot-restart>

        <query-caches>
            <query-cache name="queryCacheMapBak1HD*">
                <in-memory-format>OBJECT</in-memory-format>
                <buffer-size>50</buffer-size>
                <batch-size>5</batch-size>
                <delay-seconds>0</delay-seconds>
                <coalesce>true</coalesce>
                <include-value>true</include-value>
                <populate>true</populate>
                <predicate type="class-name">hzcmd.map.cqc.PersonIdPredicate</predicate>
            </query-cache>
        </query-caches>
    </map>
```

member size is ok, but on the client size 

queryCache = map.getQueryCache(name);

returns null.

as 
<query-cache mapName="queryCacheMapBak1HD*"  name="queryCacheMapBak1HD_query-cache">

* is not support for  mapName on the client side.  but it is support on the member size

### PR DESCRIPTION
**Pull request by ihsandemir**
Fixes the wildcard usage for query cache configuration at the ClientConfig. Adds two methods to ClientConfig.

fixes #9990

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheXmlConfigWildcardTest.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+
+import static org.junit.Assert.assertNotNull;
+
+@RunWith(HazelcastParallelClassRunner.class)
+@Category({QuickTest.class, ParallelTest.class})
+public class QueryCacheXmlConfigWildcardTest extends HazelcastTestSupport {
+
+    @Before
+    public void setUp() throws Exception {
+        System.setProperty("hazelcast.config", "classpath:hazelcast-querycache-xml-config-wildcard-test.xml");
```
Comment (mdogan) [inline hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheXmlConfigWildcardTest.java]: Better to use `new ClasspathXmlConfig("hazelcast-querycache-xml-config-wildcard-test.xml")`

Comment (ihsandemir) [inline hazelcast/src/test/java/com/hazelcast/map/impl/querycache/QueryCacheXmlConfigWildcardTest.java]: OK, changed. Unfortunately only for member side.

**Comment by ihsandemir** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
run-lab-run

File: hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java [hunk 2]
```diff
@@ -759,4 +760,47 @@ public ClientConfig setUserCodeDeploymentConfig(ClientUserCodeDeploymentConfig u
...
     }
+
+    /**
+     *
+     * @param mapName The name of the map for which the query cache config is to be returned.
+     * @param cacheName The name of the query cache config.
+     * @return The query cache config. If the config does not exist, it is created.
+     */
+    public QueryCacheConfig getOrCreateQueryCacheConfig(String mapName, String cacheName) {
+        Map<String, Map<String, QueryCacheConfig>> allQueryCacheConfig = getQueryCacheConfigs();
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java]: the first key: what does it represent?
the second key: what does it represent?

File: hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java [hunk 3]
```diff
@@ -759,4 +760,47 @@ public ClientConfig setUserCodeDeploymentConfig(ClientUserCodeDeploymentConfig u
...
+
+        Map<String, QueryCacheConfig> mapQueryCacheConfig = lookupByPattern(allQueryCacheConfig, mapName);
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java]: I'm confused with this name.

It isn't a single config, but a map of configurations.

Is represents all the query cache configs for a map. It will help if the variable would be named to 'queryCacheConfigsForMap' so that the name explains what is happening.

File: hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/DynamicConfigurationAwareConfig.java [hunk 4]
```diff
@@ -174,6 +174,30 @@ public MapConfig getMapConfig(String name) {
...
+    @Override
+    public MapConfig getMapConfigOrNull(String name) {
+        return getMapConfigOrNullInternal(name);
+    }
+
+    private MapConfig getMapConfigOrNullInternal(String name) {
+        return getMapConfigOrNullInternal(name, name);
+    }
+
+    private MapConfig getMapConfigOrNullInternal(String name, String fallbackName) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/internal/dynamicconfig/DynamicConfigurationAwareConfig.java]: Flavor warning. In case of such internal methods, I often add a 0 postfix. 

So instead of 

getMapConfigOrNullInternal

I call them

getMapConfigOrNull0

This is done frequently in the JDK.

File: hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java (hunk 2 above)
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java]: Yes, this is continous query caches. it can be defined multiple on a map. The first is the map name and the second is the query cache name.

File: hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java (hunk 3 above)
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/config/ClientConfig.java]: Changed to queryCacheConfigsForMap.
