### PR TITLE
Catch and log exceptions from dynamic metrics providers

### LINKED ISSUE #15932: Exception thrown from a dynamic metric provider stops the collector task
If the dynamic metrics collection encounters an exception it bubbles the exception up to the caller triggered the collection. This is a periodically scheduled task that is getting stopped once it is hit by an exception. Therefore, the exceptions should be caught and logged, but not propagated.

This is found by throwing an NPE from `TcpIpNetworkingService` in advanced networking mode, in which case its field `unifiedEndpointManager` is `null`.

### PR DESCRIPTION
**Pull request by blazember**
If the dynamic metrics collection encounters an exception it bubbles the
exception up to the caller triggered the periodic task that triggered
the collection. It is fixed by catching and logging the exception
without bubbling it up.

Throwing an NPE from
`TcpIpNetworkingService.MetricsProvider#provideDynamicMetrics` in
advanced networking mode is fixed by adding a null check around
`unifiedEndpointManager`.

Fixes #15932

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/DynamicMetricsCollectionTest.java [hunk 1]
```diff
@@ -133,6 +133,19 @@ public void testDirectDoubleProveLevelFilters() {
         verify(collectorMock, never()).collectDouble("[unit=bytes,metric=test.someMetric]", 42.42D, emptySet());
     }
 
+    @Test
+    public void testDynamicProviderExceptionsAreNotPropagated() {
+        MetricsCollector collectorMock = mock(MetricsCollector.class);
+        MetricsRegistry metricsRegistry = new MetricsRegistryImpl(Logger.getLogger(MetricsRegistryImpl.class), MANDATORY);
+        metricsRegistry.registerDynamicMetricsProvider((taggerSupplier, context) -> {
+            throw new RuntimeException("Intentionally failing metrics collection");
+
```
Comment (puzpuzpuz) [inline hazelcast/src/test/java/com/hazelcast/internal/metrics/impl/DynamicMetricsCollectionTest.java]: A redundant empty line

**Comment by blazember** [comment]
Thanks for the review guys :+1:
