### PR TITLE
Fix NPE during aggregation

### LINKED ISSUE #9852: query.QueryOperation Failed to serialize NormalResponse
```
Feb 10, 2017 6:56:29 AM com.hazelcast.map.impl.query.QueryOperation
SEVERE: [10.212.1.117]:5701 [HZ] [3.8-SNAPSHOT] Failed to serialize 'com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse'
com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse'
    at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:73)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:125)
    at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.send(OutboundResponseHandler.java:88)
    at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:64)
    at com.hazelcast.spi.Operation.sendResponse(Operation.java:338)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponse(OperationRunnerImpl.java:279)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:270)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:187)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.query.AggregationResult'
    at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:73)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:251)
    at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
    at com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.writeData(NormalResponse.java:91)
    at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:215)
    at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:56)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:151)
    ... 10 more
Caused by: java.lang.NullPointerException
```

```
Feb 10, 2017 6:56:30 AM com.hazelcast.map.impl.query.MapQueryEngineImpl
WARNING: [10.212.1.117]:5701 [HZ] [3.8-SNAPSHOT] Could not get results
java.util.concurrent.ExecutionException: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.spi.impl.operationservice.impl.responses
.NormalResponse'
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:88)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.addResultsOfPredicate(MapQueryEngineImpl.java:177)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.dispatchQueryOnQueryThreads(MapQueryEngineImpl.java:153)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.doRunQueryOnQueryThreads(MapQueryEngineImpl.java:146)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.runQueryOnAllPartitions(MapQueryEngineImpl.java:125)
	at com.hazelcast.map.impl.query.MapQueryEngineImpl.execute(MapQueryEngineImpl.java:86)
	at com.hazelcast.map.impl.proxy.MapProxyImpl.aggregate(MapProxyImpl.java:783)
	at hzcmd.map.aggregate.Count.timeStep(Count.java:15)
	at remote.bench.marker.MetricsMarker.flatOut(MetricsMarker.java:52)
	at remote.bench.marker.MetricsMarker.bench(MetricsMarker.java:39)
	at remote.bench.BenchThread.call(BenchThread.java:38)
	at remote.bench.BenchThread.call(BenchThread.java:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:73)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:125)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.send(OutboundResponseHandler.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:64)
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:338)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponse(OperationRunnerImpl.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:270)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:187)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:401)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveAndThrowIfException(InvocationFuture.java:75)
	... 18 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.map.impl.query.AggregationResult'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:73)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:251)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:370)
	at com.hazelcast.spi.impl.operationservice.impl.responses.NormalResponse.writeData(NormalResponse.java:91)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:215)
	at com.hazelcast.internal.serialization.impl.EnterpriseDataSerializableSerializer.write(EnterpriseDataSerializableSerializer.java:56)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:151)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:125)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.send(OutboundResponseHandler.java:88)
	at com.hazelcast.spi.impl.operationservice.impl.OutboundResponseHandler.sendResponse(OutboundResponseHandler.java:64)
	at com.hazelcast.spi.Operation.sendResponse(Operation.java:338)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.sendResponse(OperationRunnerImpl.java:279)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.handleResponse(OperationRunnerImpl.java:270)
	at com.hazelcast.spi.impl.operationservice.impl.Ope
```

https://github.com/hazelcast/hzCmd-bench/blob/zeta/src/main/java/hz/map/aggregate/Count.java

### PR DESCRIPTION
**Pull request by jerrinot**
Fixes #9852

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/aggregation/impl/MaxAggregator.java [hunk 1]
```diff
@@ -45,6 +45,9 @@ public void accumulate(I entry) {
     }
 
     private boolean isCurrentlyLessThan(R extractedValue) {
+        if (extractedValue == null) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/aggregation/impl/MaxAggregator.java]: not related to the #9852
this is another issue discovered by the bouncing test

File: hazelcast/src/main/java/com/hazelcast/aggregation/impl/MinAggregator.java [hunk 2]
```diff
@@ -45,6 +45,9 @@ public void accumulate(I entry) {
     }
 
     private boolean isCurrentlyGreaterThan(R otherValue) {
+        if (otherValue == null) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/aggregation/impl/MinAggregator.java]: not related to the #9852
this is another issue discovered by the bouncing test

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/AggregationResult.java [hunk 3]
```diff
@@ -55,10 +55,14 @@ public AggregationResult(Aggregator aggregator) {
 
     @Override
     public void combine(AggregationResult result) {
+        Collection<Integer> otherPartitionIds = result.getPartitionIds();
+        if (otherPartitionIds == null) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/AggregationResult.java]: this is possible when the other result was created while partitions were in motion

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java [hunk 4]
```diff
@@ -155,7 +156,7 @@ private void dispatchQueryOnQueryThreads(Query query, Target target, Collection<
             if (t.getCause() instanceof QueryResultSizeExceededException) {
                 throw rethrow(t);
             }
-            logger.warning("Could not get results", t);
+            logger.log(Level.FINE, "Could not get results", t);
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java]: reduced to keep it consistent with client task. exception here is a not a big deal as it will be retried per-partition. 
it's actually expected when members are bouncing.

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/AggregationResult.java [hunk 5]
```diff
@@ -55,10 +55,14 @@ public AggregationResult(Aggregator aggregator) {
 
     @Override
     public void combine(AggregationResult result) {
+        Collection<Integer> otherPartitionIds = result.getPartitionIds();
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/AggregationResult.java]: maybe in `AggregationResult` class,  we can assign `partitionIds` to `emptyList()` to get rid of null checks.

File: hazelcast/src/main/java/com/hazelcast/aggregation/impl/MaxAggregator.java (hunk 1 above)
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/aggregation/impl/MaxAggregator.java]: isn't this `null` check needed by all other aggregators? i mean in `accumulate` methods of them. Because `AbstractAggregator#extract` can return `null` anytime ?

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/AggregationResult.java (hunk 5 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/AggregationResult.java]: I was thinking about this. but then I saw there were already checks in place and I was worried about side-effects. it's probably something Tom should deal with in 3.9 with this Query engine re-work.

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java (hunk 4 above)
Comment (Donnerbart) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java]: You might like this PR :) https://github.com/hazelcast/hazelcast/pull/9855

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java]: in 3.9 for sure :)

File: hazelcast/src/main/java/com/hazelcast/aggregation/impl/MaxAggregator.java (hunk 1 above)
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/aggregation/impl/MaxAggregator.java]: good question. I created https://github.com/hazelcast/hazelcast/issues/9858
