### PR TITLE
Fix dangling endpoints when connection closed before authentication

### LINKED ISSUE #12674: ClientServiceTest.testClientListenerDisconnected fails randomly
*master*

Failed in the PR builder for master branch: https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/14581/testReport/junit/com.hazelcast.client/ClientServiceTest/testClientListenerDisconnected/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 120000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.hazelcast.test.HazelcastTestSupport.sleepMillis(HazelcastTestSupport.java:349)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1208)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1217)
	at com.hazelcast.client.ClientServiceTest.testClientListenerDisconnected(ClientServiceTest.java:337)
```

Standard output (interesting part):
```
12:41:51,703  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_6_dev.cached.thread-6 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: 2dae38da-71df-46a9-abbb-29c4c655f3d1
12:41:51,705  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_5_dev.cached.thread-6 - [127.0.0.1]:5005 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: e89c62d9-107e-4f60-8217-aef45a740822
12:41:51,705  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_5_dev.cached.thread-6 - [127.0.0.1]:5005 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: 1a67a2f9-5e03-46eb-b832-ae377cda0bb1
12:41:51,706  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_6_dev.cached.thread-6 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: 1a67a2f9-5e03-46eb-b832-ae377cda0bb1
12:41:51,707  INFO |testClientListenerDisconnected| - [TransactionManagerService] hz._hzInstance_6_dev.cached.thread-6 - [127.0.0.1]:5006 [dev] [3.10-SNAPSHOT] Committing/rolling-back alive transactions of client, UUID: e89c62d9-107e-4f60-8217-aef45a740822

Hiccups measured while running test 'testClientListenerDisconnected(com.hazelcast.client.ClientServiceTest):'
12:40:55, accumulated pauses: 1004 ms, max pause: 406 ms, pauses over 1000 ms: 0
12:41:00, accumulated pauses: 1879 ms, max pause: 298 ms, pauses over 1000 ms: 0
12:41:05, accumulated pauses: 939 ms, max pause: 264 ms, pauses over 1000 ms: 0
12:41:10, accumulated pauses: 1600 ms, max pause: 280 ms, pauses over 1000 ms: 0
12:41:15, accumulated pauses: 1944 ms, max pause: 696 ms, pauses over 1000 ms: 0
12:41:20, accumulated pauses: 1357 ms, max pause: 157 ms, pauses over 1000 ms: 0
12:41:25, accumulated pauses: 2245 ms, max pause: 631 ms, pauses over 1000 ms: 0
12:41:30, accumulated pauses: 1359 ms, max pause: 128 ms, pauses over 1000 ms: 0
12:41:35, accumulated pauses: 1574 ms, max pause: 240 ms, pauses over 1000 ms: 0
12:41:40, accumulated pauses: 2390 ms, max pause: 326 ms, pauses over 1000 ms: 0
12:41:45, accumulated pauses: 776 ms, max pause: 34 ms, pauses over 1000 ms: 0
12:41:50, accumulated pauses: 752 ms, max pause: 16 ms, pauses over 1000 ms: 0
12:41:55, accumulated pauses: 724 ms, max pause: 24 ms, pauses over 1000 ms: 0
12:42:00, accumulated pauses: 768 ms, max pause: 40 ms, pauses over 1000 ms: 0
12:42:05, accumulated pauses: 692 ms, max pause: 23 ms, pauses over 1000 ms: 0
12:42:10, accumulated pauses: 665 ms, max pause: 21 ms, pauses over 1000 ms: 0
12:42:15, accumulated pauses: 387 ms, max pause: 18 ms, pauses over 1000 ms: 0
12:42:20, accumulated pauses: 143 ms, max pause: 49 ms, pauses over 1000 ms: 0
12:42:25, accumulated pauses: 28 ms, max pause: 4 ms, pauses over 1000 ms: 0
12:42:30, accumulated pauses: 35 ms, max pause: 6 ms, pauses over 1000 ms: 0
12:42:35, accumulated pauses: 41 ms, max pause: 6 ms, pauses over 1000 ms: 0
12:42:40, accumulated pauses: 38 ms, max pause: 5 ms, pauses over 1000 ms: 0
12:42:45, accumulated pauses: 37 ms, max pause: 2 ms, pauses over 1000 ms: 0
12:42:50, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
12:42:55, accumulated pauses: 51 ms, max pause: 21 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by sancar**
If client closes a connection, right after the authentication task
is started at a member, we were ending up with dangling endpoints.

For fix, job of cleaning up these dangling endpoints are given to
ClientHeartBeatMonitor.

fixes #12674

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java [hunk 1]
```diff
@@ -68,13 +73,41 @@ public void start() {
...
+
         String memberUuid = clientEngine.getThisUuid();
         for (ClientEndpoint ce : clientEndpointManager.getEndpoints()) {
             ClientEndpointImpl clientEndpoint = (ClientEndpointImpl) ce;
             monitor(memberUuid, clientEndpoint);
         }
     }
 
+    private void cleanupEndpointsWithDeathConnections() {
+        ArrayList<ClientEndpoint> endpointsWithDeadConnections = new ArrayList<ClientEndpoint>();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java]: Normally you don't specificity ArrayList for the variable, just list.

File: hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java [hunk 2]
```diff
@@ -68,13 +73,41 @@ public void start() {
...
+        for (ClientEndpoint ce : clientEndpointManager.getEndpoints()) {
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java]: Don't use abbreviations. If you want to write something short, just use endpoint or so. Abbreviations make the code harder to read.

File: hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java [hunk 3]
```diff
@@ -68,13 +73,41 @@ public void start() {
...
+        }
+
+        int size = endpointsWithDeadConnections.size();
+        if (size != 0) {
+            //if connection is not alive, it means we come across an edge case.
+            //normally connection close should remove endpoint from client endpoint manager
+            //this means that connection.close happened before, authentication complete(endpoint registered to manager)
+            //therefore connection.close could not remove the endpoint.
+            //we will remove the endpoint here when detected.
+            logger.info("Cleaning up endpoints with dead connections, size:" + size
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java]: Does this need to be info? Isn't this a debug message?

File: hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java (hunk 1 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java]: You are going to create litter every time you do a check. There is no need for that. You can iterate over the set of endpoints and remove the dead endpoint as soon as you see it.

Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/ClientHeartbeatMonitor.java]: I can't use the iterate approach since map could be modified when I am iterating over. 
That is why I avoid iterators. 

I can avoid litter by creating the list only if there is a closed connection.

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run

**Comment by sancar** [comment]
run-lab-run
