### PR TITLE
Do not log business exceptions

### LINKED ISSUE #9051: DurableExecutorService exceptions
If `DurableExecutorService.retrieveResult(long)` is run from a client for a task that doesn't exist, two exceptions appear on 3.7.1.

In the server logs `StaleTaskIdException`. This shouldn't be logged to the server if re-thrown to the client.

On the client, `ExecutionException`. This should be a `StaleTaskIdException`

### PR DESCRIPTION
**Pull request by jerrinot**
Exceptions such as StaleSequenceException are part of a normal
flow. They are propagated to user code and there is no reason
why Hazelcast should log them by default.

Fixes #9051, #9781

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/Operation.java [hunk 1]
```diff
@@ -486,7 +487,9 @@ public void onExecutionFailure(Throwable e) {
      */
     public void logError(Throwable e) {
         final ILogger logger = getLogger();
-        if (e instanceof RetryableException) {
+        if (e instanceof SilentException) {
+            logger.finest(e.getMessage(), e);
+        } else if (e instanceof RetryableException) {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/Operation.java]: One could mark an `Exception` with both `SilentException` & `RetryableException`; in this case it will not be retried at all, just silently ignored. I cannot think why one would want a silent & retryable exception, but should we add a related warning in `SilentException`'s javadoc?
Also, since `QuorumException` becomes a `SilentException` with this PR, the `instanceof QuorumException` else-if branch below can be removed.

Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/Operation.java]: Please ignore the remark about `RetryableException`, I now see it's just the logging that is being done here.
