### PR TITLE
Fix SuspendExecutionOnFailureTest assertions

### LINKED ISSUE #19836: com.hazelcast.jet.core.SuspendExecutionOnFailureTest.when_jobSuspendedDueToFailure_then_canBeResumed
5.0.z (rev. f8d5893f13590e24b767096d565c19e71c03a82a)

Failed on Zing, JDK8: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-ZingJDK8/8/testReport/junit/com.hazelcast.jet.core/SuspendExecutionOnFailureTest/when_jobSuspendedDueToFailure_then_canBeResumed_1__mode_client_/

<details><summary>Stacktrace:</summary>

```
java.lang.AssertionError: expected:<50> but was:<47>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.core.SuspendExecutionOnFailureTest.lambda$when_jobSuspendedDueToFailure_then_canBeResumed$1(SuspendExecutionOnFailureTest.java:192)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1260)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1362)
	at com.hazelcast.jet.core.SuspendExecutionOnFailureTest.when_jobSuspendedDueToFailure_then_canBeResumed(SuspendExecutionOnFailureTest.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

<details><summary>Standard output:</summary>

```
Finished Running Test: when_jobFailed_then_suspensionCauseThrows[1: mode=client] in 0.218 seconds.
Started Running Test: when_jobSuspendedDueToFailure_then_canBeResumed[1: mode=client]
19:25:28,584 DEBUG || - [JobClassLoaderService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Creating job classLoader for job 06fc-0975-2e82-0001
19:25:28,584 DEBUG || - [JobClassLoaderService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Create processor classloader map for job 06fc-0975-2e82-0001
19:25:28,586 DEBUG || - [Planner] hz.nervous_haibt.cached.thread-3 - Watermarks in the pipeline will be throttled to 1000
19:25:28,588  INFO || - [JobCoordinationService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting job 06fc-0975-2e82-0001 based on submit request
19:25:28,591  INFO || - [MasterJobContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Didn't find any snapshot to restore for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001
19:25:28,591  INFO || - [MasterJobContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Start executing job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001, execution graph in DOT format:
digraph DAG {
	"src" [localParallelism=1];
	"mapUsingIMap" [localParallelism=1];
	"mapSink(SuspendExecutionOnFailureTest_sinkMap)" [localParallelism=1];
	"src" -> "mapUsingIMap" [queueSize=1024];
	"mapUsingIMap" -> "mapSink(SuspendExecutionOnFailureTest_sinkMap)" [label="partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
19:25:28,591 DEBUG || - [MasterJobContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Building execution plan for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001
19:25:28,592 DEBUG || - [MasterJobContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Built execution plans for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001
19:25:28,593 DEBUG || - [InitExecutionOperation] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Initializing execution plan for job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 from [127.0.0.1]:5701
19:25:28,593 DEBUG || - [InitExecutionOperation] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Initializing execution plan for job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 from [127.0.0.1]:5701
19:25:28,595  INFO || - [JobExecutionService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Execution plan for jobId=06fc-0975-2e82-0001, jobName='06fc-0975-2e82-0001', executionId=06fc-0972-facf-0001 initialized
19:25:28,596 DEBUG || - [JobClassLoaderService] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Creating job classLoader for job 06fc-0975-2e82-0001
19:25:28,596 DEBUG || - [JobClassLoaderService] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Create processor classloader map for job 06fc-0975-2e82-0001
19:25:28,598  INFO || - [JobExecutionService] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Execution plan for jobId=06fc-0975-2e82-0001, jobName='06fc-0975-2e82-0001', executionId=06fc-0972-facf-0001 initialized
19:25:28,599 DEBUG || - [MasterJobContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Init of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 was successful
19:25:28,599 DEBUG || - [MasterJobContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Executing job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001
19:25:28,599  INFO || - [JobExecutionService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Start execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 from coordinator [127.0.0.1]:5701
19:25:28,599  INFO || - [JobExecutionService] hz.magical_haibt.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Start execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 from coordinator [127.0.0.1]:5701
19:25:28,602 DEBUG || - [JobClassLoaderService] ForkJoinPool.commonPool-worker-28 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=06fc-0975-2e82-0001
19:25:28,602 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-28 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Completed execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001
19:25:28,602 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-28 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] Execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 completed
19:25:28,603 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-28 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: null
19:25:28,604 DEBUG || - [JobCoordinationService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 snapshot is scheduled in 50ms
19:25:28,671 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 0 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001, flags: terminal=no,export=no, writing to: null
19:25:28,671 DEBUG || - [ExecutionContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 0 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 on member
19:25:28,671 ERROR || - [SnapshotPhase1Operation] hz.magical_haibt.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase1Operation.doRun(SnapshotPhase1Operation.java:65) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,673 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for src: keys=1, chunks=1, bytes=37
19:25:28,674 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for mapUsingIMap: keys=0, chunks=0, bytes=0
19:25:28,675 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for mapSink(SuspendExecutionOnFailureTest_sinkMap): keys=0, chunks=0, bytes=0
19:25:28,681 DEBUG || - [SnapshotPhase1Operation] hz.nervous_haibt.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 0 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 finished successfully on member
19:25:28,691 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 will wait for 1 responses to StartExecutionOperation in onSnapshotPhase1Complete()
19:25:28,691 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 all awaited responses to StartExecutionOperation received or were already received
19:25:28,701 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 0 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 completed with status SUCCESS in 32ms, 37 bytes, 1 keys in 1 chunks, stored in '__jet.snapshot.06fc-0975-2e82-0001.0', proceeding to phase 2
19:25:28,711 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Cleared snapshot data map __jet.snapshot.06fc-0975-2e82-0001.1
19:25:28,711 DEBUG || - [ExecutionContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 0 phase 2 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 on member
19:25:28,711 ERROR || - [SnapshotPhase2Operation] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,714 DEBUG || - [SnapshotPhase2Operation] hz.nervous_haibt.jet.blocking.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 0 phase 2 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 finished successfully on member
19:25:28,721  WARN || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 0 in job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 failed on member: MemberInfo{address=[127.0.0.1]:5702, uuid=8c42b5c3-52d6-435d-889a-e2c1d69d5b57, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,721 DEBUG || - [JobCoordinationService] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 snapshot is scheduled in 50ms
19:25:28,721 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 0 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 completed in 62ms, status=success
19:25:28,783 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001, flags: terminal=no,export=no, writing to: null
19:25:28,783 DEBUG || - [ExecutionContext] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 1 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 on member
19:25:28,783 ERROR || - [SnapshotPhase1Operation] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase1Operation.doRun(SnapshotPhase1Operation.java:65) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,788 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for src: keys=1, chunks=1, bytes=37
19:25:28,790 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for mapUsingIMap: keys=0, chunks=0, bytes=0
19:25:28,790 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for mapSink(SuspendExecutionOnFailureTest_sinkMap): keys=0, chunks=0, bytes=0
19:25:28,795 DEBUG || - [SnapshotPhase1Operation] hz.nervous_haibt.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 1 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 finished successfully on member
19:25:28,796 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 will wait for 1 responses to StartExecutionOperation in onSnapshotPhase1Complete()
19:25:28,796 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 all awaited responses to StartExecutionOperation received or were already received
19:25:28,797 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 1 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 completed with status SUCCESS in 24ms, 37 bytes, 1 keys in 1 chunks, stored in '__jet.snapshot.06fc-0975-2e82-0001.1', proceeding to phase 2
19:25:28,807 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Cleared snapshot data map __jet.snapshot.06fc-0975-2e82-0001.0
19:25:28,808 DEBUG || - [ExecutionContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 1 phase 2 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 on member
19:25:28,812 DEBUG || - [SnapshotPhase2Operation] hz.nervous_haibt.jet.blocking.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 1 phase 2 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 finished successfully on member
19:25:28,816 ERROR || - [SnapshotPhase2Operation] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,817  WARN || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] SnapshotPhase2Operation for snapshot 1 in job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 failed on member: MemberInfo{address=[127.0.0.1]:5702, uuid=8c42b5c3-52d6-435d-889a-e2c1d69d5b57, liteMember=false, memberListJoinVersion=2}=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase2Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase2Operation.doRun(SnapshotPhase2Operation.java:54) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,817 DEBUG || - [JobCoordinationService] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 snapshot is scheduled in 50ms
19:25:28,817 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Snapshot 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 completed in 45ms, status=success
19:25:28,882 DEBUG || - [MasterSnapshotContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 2 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001, flags: terminal=no,export=no, writing to: null
19:25:28,882 DEBUG || - [ExecutionContext] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Starting snapshot 2 phase 1 for job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 on member
19:25:28,882 ERROR || - [SnapshotPhase1Operation] hz.magical_haibt.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 06fc-0975-2e82-0001, execution 06fc-0972-facf-0001 not found for coordinator [127.0.0.1]:5701 for 'SnapshotPhase1Operation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:441) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.SnapshotPhase1Operation.doRun(SnapshotPhase1Operation.java:65) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
19:25:28,887 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for src: keys=1, chunks=1, bytes=37
19:25:28,903 DEBUG || - [AsyncSnapshotWriterImpl] hz.nervous_haibt.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Stats for mapUsingIMap: keys=0, chunks=0, bytes=0
19:25:28,907  WARN || - [TaskletExecutionService] hz.nervous_haibt.jet.cooperative.thread-0 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Exception in ProcessorTasklet{06fc-0975-2e82-0001/mapUsingIMap#1}
com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryFlushQueue(AsyncTransformUsingServiceOrderedP.java:191) ~[classes/:?]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryProcess(AsyncTransformUsingServiceOrderedP.java:130) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:297) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:531) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:297) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) [?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356) [classes/:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0-zing_18.06.0.0]
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryFlushQueue(AsyncTransformUsingServiceOrderedP.java:186) ~[classes/:?]
	... 10 more
Caused by: java.lang.RuntimeException: Fail deliberately
	at com.hazelcast.jet.core.SuspendExecutionOnFailureTest.lambda$when_jobSuspendedDueToFailure_then_canBeResumed$d88c3f54$1(SuspendExecutionOnFailureTest.java:176) ~[test-classes/:?]
	at com.hazelcast.function.BiFunctionEx.apply(BiFunctionEx.java:49) ~[classes/:?]
	at com.hazelcast.jet.pipeline.GeneralStage.lambda$null$0(GeneralStage.java:694) ~[classes/:?]
	at com.hazelcast.spi.impl.DelegatingCompletableFuture$DeserializingFunction.apply(DelegatingCompletableFuture.java:518) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ApplyNode.lambda$execute$0(AbstractInvocationFuture.java:1484) ~[classes/:?]
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104) ~[test-classes/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0-zing_18.06.0.0]
19:25:28,912 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-469 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Completed execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001
19:25:28,912 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-469 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06fc-0975-2e82-0001/mapUsingIMap#1}: com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:769) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:489) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:317) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0-zing_18.06.0.0]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0-zing_18.06.0.0]
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06fc-0975-2e82-0001/mapUsingIMap#1}: com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:400) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356) ~[classes/:?]
	... 1 more
Caused by: com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryFlushQueue(AsyncTransformUsingServiceOrderedP.java:191) ~[classes/:?]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryProcess(AsyncTransformUsingServiceOrderedP.java:130) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:297) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:531) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:297) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356) ~[classes/:?]
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryFlushQueue(AsyncTransformUsingServiceOrderedP.java:186) ~[classes/:?]
	at com.hazelcast.jet.impl.processor.AsyncTransformUsingServiceOrderedP.tryProcess(AsyncTransformUsingServiceOrderedP.java:130) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.lambda$stateMachineStep$2(ProcessorTasklet.java:297) ~[classes/:?]
	at com.hazelcast.jet.impl.util.Util.doWithClassLoader(Util.java:531) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:297) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.stateMachineStep(ProcessorTasklet.java:281) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.ProcessorTasklet.call(ProcessorTasklet.java:255) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:388) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0-zing_18.06.0.0]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:356) ~[classes/:?]
	... 1 more
Caused by: java.lang.RuntimeException: Fail deliberately
	at com.hazelcast.jet.core.SuspendExecutionOnFailureTest.lambda$when_jobSuspendedDueToFailure_then_canBeResumed$d88c3f54$1(SuspendExecutionOnFailureTest.java:176) ~[test-classes/:?]
	at com.hazelcast.function.BiFunctionEx.apply(BiFunctionEx.java:49) ~[classes/:?]
	at com.hazelcast.jet.pipeline.GeneralStage.lambda$null$0(GeneralStage.java:694) ~[classes/:?]
	at com.hazelcast.spi.impl.DelegatingCompletableFuture$DeserializingFunction.apply(DelegatingCompletableFuture.java:518) ~[classes/:?]
	at com.hazelcast.spi.impl.AbstractInvocationFuture$ApplyNode.lambda$execute$0(AbstractInvocationFuture.java:1484) ~[classes/:?]
	at com.hazelcast.test.TestLoggingUtils$CustomTestNameAwareForkJoinPool$TestNameAwareRunnable.run(TestLoggingUtils.java:104) ~[test-classes/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0-zing_18.06.0.0]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0-zing_18.06.0.0]
19:25:28,912 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-469 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06fc-0975-2e82-0001/mapUsingIMap#1}: com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately
19:25:28,912 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-469 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Execution of job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 has failures: [[127.0.0.1]:5701=com.hazelcast.jet.JetException: Exception in ProcessorTasklet{06fc-0975-2e82-0001/mapUsingIMap#1}: com.hazelcast.jet.JetException: Async operation completed exceptionally: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Fail deliberately]
19:25:28,913 DEBUG || - [JobClassLoaderService] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Finish JobClassLoaders phaseCount = 0, removing classloaders for jobId=06fc-0975-2e82-0001
19:25:30,939 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 1ms
19:25:33,774 DEBUG || - [MasterJobContext] hz.nervous_haibt.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Not scaling up job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001: not running or already running on all members
19:25:35,941 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:25:40,944 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:25:43,746  INFO || - [HealthMonitor] hz.nervous_haibt.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.8G, heap.memory.free=1.5G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=55.14%, heap.memory.used/max=55.14%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=100.00%, load.systemAverage=6.40, thread.count=162, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=930, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:25:44,286  INFO || - [HealthMonitor] hz.magical_haibt.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.8G, heap.memory.free=1.5G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=55.20%, heap.memory.used/max=55.20%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=6.12, thread.count=162, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1069, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:25:45,949 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:25:50,963 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:25:55,983 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 15ms
19:26:00,997 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:03,747  INFO || - [HealthMonitor] hz.nervous_haibt.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.8G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=55.80%, heap.memory.used/max=55.80%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=100.00%, load.system=100.00%, load.systemAverage=6.01, thread.count=163, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1302, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:26:04,289  INFO || - [HealthMonitor] hz.magical_haibt.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.8G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=55.80%, heap.memory.used/max=55.80%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=100.00%, load.systemAverage=5.93, thread.count=163, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1442, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:26:06,023 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:11,027 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 2ms
19:26:16,030 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:21,033 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:23,753  INFO || - [HealthMonitor] hz.nervous_haibt.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.8G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=56.46%, heap.memory.used/max=56.46%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=6.02, thread.count=164, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1674, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:26:24,290  INFO || - [HealthMonitor] hz.magical_haibt.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.8G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=56.52%, heap.memory.used/max=56.52%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=5.86, thread.count=165, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1817, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:26:26,036 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:31,043 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:36,051 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:41,080 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 9ms
19:26:43,754  INFO || - [HealthMonitor] hz.nervous_haibt.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.9G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=57.30%, heap.memory.used/max=57.30%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=5.43, thread.count=153, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2049, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:26:44,292  INFO || - [HealthMonitor] hz.magical_haibt.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.9G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=57.30%, heap.memory.used/max=57.30%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=100.00%, load.systemAverage=5.79, thread.count=153, thread.peakCount=1490, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2193, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:26:46,082 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:51,087 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:26:56,103 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:27:01,115 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:27:03,755  INFO || - [HealthMonitor] hz.nervous_haibt.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.9G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=58.08%, heap.memory.used/max=58.08%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=5.69, thread.count=154, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2424, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:27:04,301  INFO || - [HealthMonitor] hz.magical_haibt.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.9G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=58.08%, heap.memory.used/max=58.08%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=5.48, thread.count=154, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=1, executor.q.priorityOperation.size=0, operations.completed.count=2568, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:27:06,118 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:27:11,122 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 1ms
19:27:16,134 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:27:21,150 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:27:23,756  INFO || - [HealthMonitor] hz.nervous_haibt.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.9G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=58.44%, heap.memory.used/max=58.44%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=5.21, thread.count=154, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2796, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:27:24,303  INFO || - [HealthMonitor] hz.magical_haibt.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0.1-SNAPSHOT] processors=4, physical.memory.total=29.8G, physical.memory.free=16.1G, swap.space.total=0, swap.space.free=0, heap.memory.used=1.9G, heap.memory.free=1.4G, heap.memory.total=3.3G, heap.memory.max=3.3G, heap.memory.used/total=58.44%, heap.memory.used/max=58.44%, minor.gc.count=0, minor.gc.time=0ms, major.gc.count=0, major.gc.time=0ms, unknown.gc.count=621, unknown.gc.time=519720ms, load.process=0.00%, load.system=0.00%, load.systemAverage=5.03, thread.count=154, thread.peakCount=1490, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=2944, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=1, connection.active.count=0, client.connection.count=0, connection.count=0
19:27:26,161 DEBUG || - [JobRepository] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Job cleanup took 0ms
19:27:29,133 DEBUG |when_jobSuspendedDueToFailure_then_canBeResumed[1: mode=client]| - [AbstractJobProxy] Thread-30019 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] Sending CANCEL_FORCEFUL request for job 06fc-0975-2e82-0001 (name ??)
19:27:29,134 DEBUG || - [JobCoordinationService] hz.nervous_haibt.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0.1-SNAPSHOT] job '06fc-0975-2e82-0001', execution 06fc-0972-facf-0001 is completed
BuildInfo right after when_jobSuspendedDueToFailure_then_canBeResumed[1: mode=client](com.hazelcast.jet.core.SuspendExecutionOnFailureTest): BuildInfo{version='5.0.1-SNAPSHOT', build='20211020', buildNumber=20211020, revision=f8d5893, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_jobSuspendedDueToFailure_then_canBeResumed[1: mode=client](com.hazelcast.jet.core.SuspendExecutionOnFailureTest):'
19:25:25, accumulated pauses: 4941 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:25:30, accumulated pauses: 4932 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:25:35, accumulated pauses: 4931 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:25:40, accumulated pauses: 4929 ms, max pause: 18 ms, pauses over 1000 ms: 0
19:25:45, accumulated pauses: 4943 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:25:50, accumulated pauses: 4937 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:25:55, accumulated pauses: 4928 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:00, accumulated pauses: 4931 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:05, accumulated pauses: 4943 ms, max pause: 21 ms, pauses over 1000 ms: 0
19:26:10, accumulated pauses: 4935 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:15, accumulated pauses: 4935 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:20, accumulated pauses: 4937 ms, max pause: 19 ms, pauses over 1000 ms: 0
19:26:25, accumulated pauses: 4937 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:30, accumulated pauses: 4928 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:35, accumulated pauses: 4936 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:40, accumulated pauses: 4932 ms, max pause: 22 ms, pauses over 1000 ms: 0
19:26:45, accumulated pauses: 4937 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:50, accumulated pauses: 4934 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:26:55, accumulated pauses: 4932 ms, max pause: 19 ms, pauses over 1000 ms: 0
19:27:00, accumulated pauses: 4935 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:27:05, accumulated pauses: 4938 ms, max pause: 23 ms, pauses over 1000 ms: 0
19:27:10, accumulated pauses: 4929 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:27:15, accumulated pauses: 4933 ms, max pause: 20 ms, pauses over 1000 ms: 0
19:27:20, accumulated pauses: 4941 ms, max pause: 19 ms, pauses over 1000 ms: 0
19:27:25, accumulated pauses: 4070 ms, max pause: 20 ms, pauses over 1000 ms: 0

```

</details>

### PR DESCRIPTION
**Pull request by viliam-durina**
I think the assertion on line 192 was wrong. If a vertex fails after a
certain item, there's no guarantee that a downstream vertex already
processed all previous items. The test failed rarely because the source
emits items one by one with 5ms delay, so it was very likely that all
items were sunk, but if there was some hiccup, it could fail.

Fixes #19836

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/jet/core/SuspendExecutionOnFailureTest.java [hunk 1]
```diff
@@ -189,10 +189,11 @@ public void when_jobSuspendedDueToFailure_then_canBeResumed() {
         assertJobStatusEventually(job, SUSPENDED);
 
         IMap<Integer, Integer> sinkMap = hz().getMap("SuspendExecutionOnFailureTest_sinkMap");
-        assertTrueEventually(() -> assertEquals(interuptItem, sinkMap.size()));
 
         counterMap.put("key", false);
         job.resume();
+        // sinkMap is an idempotent sink, so even we're using at-least-once, no key will be duplicated, so the
+        // must contain expected number of items.
```
Comment (ramizdundar) [inline hazelcast/src/test/java/com/hazelcast/jet/core/SuspendExecutionOnFailureTest.java:196]:
```suggestion
        // sink must contain expected number of items.
```

**Review by ramizdundar — APPROVED** [review]
LGTM

**Review by ufukyilmaz — APPROVED** [review]
It looks good to me. I was thinking about guaranteeing that the next steps process the items that are previous to the error item and it seems to be possible but this kind of guarantee doesn't make sense in terms of fault tolerance (anyway we don't have a chance to take a snapshot after the error since previous steps may already progress, and we have to go back to the previous snapshot).

**Comment by mmedenjak** [comment]
@viliam-durina can this be merged?
