### PR TITLE
Propagate bitmap index statistics

### LINKED ISSUE #17047: BITMAP index statisctics is not propagated to the LocalMapStats
**Describe the bug**
The statistics of a BITMAP index is not reflected into the LocalMapStats. This behavior seems to be occurring due to the implementation difference between getRecords() and evaluate() methods on AbstractIndex.java. While getRecord() invokes stats.onIndexHit(), evaluate() method does not have any calls to the stats.onIndexHit().

**Expected behavior**
The operations on Map are expected to be reflected into BITMAP index statistics as reflected into the standard index stats. 

**To Reproduce**

1. Add an index to a Map.
```java 
        IMap<String, MapEntryIndexed> map = hz.getMap("indexedMap");
        map.addIndex("label", false);
```
2. Perform some operations on Map
3. Print LocalMapStats, observe indexStats
```java
        System.out.println(map.getLocalMapStats());
```
4. Repeat step 1,2 and 3. Add BITMAP index instead of standard index
```java
        map.addIndex("BITMAP(label)", false);
```
        
**Additional context**
Tested on Hazelcast v3.12.6

### PR DESCRIPTION
**Pull request by Fly-Style**
This PR adds bitmap index stat hits.
Closes #17047.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java [hunk 1]
```diff
@@ -403,6 +416,64 @@ Comparable canonicalizeScalarForStorage(Comparable value) {
...
+     * @param operationStats current index stats
+     * @param values         iterator which points on first value should be inserted
+     */
+    private void accountEntryInsert(IndexOperationStats operationStats, Iterator values) {
+        if (values instanceof MultiValueIterator) {
+            while (values.hasNext()) {
+                operationStats.onEntryAdded(null, values.next());
+            }
+        } else {
+            operationStats.onEntryAdded(null, values);
```
Comment (taburet) [inline hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java:431]: `values.next()`?

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java [hunk 2]
```diff
@@ -403,6 +416,64 @@ Comparable canonicalizeScalarForStorage(Comparable value) {
...
+     * @param oldValues      iterator which points on first old value should be removed
+     * @param newValues      iterator which points on first old value should be inserted
+     */
+    private void accountEntryUpdate(IndexOperationStats operationStats, Iterator oldValues, Iterator newValues) {
+        if (newValues instanceof MultiValueIterator) {
+            while (newValues.hasNext()) {
+                operationStats.onEntryAdded(null, newValues.next());
+            }
+        } else {
+            operationStats.onEntryAdded(null, newValues);
```
Comment (taburet) [inline hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java:448]: `newValues.next()`?

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java [hunk 3]
```diff
@@ -125,6 +125,8 @@ public void insert(Object value, QueryableEntry entry, IndexOperationStats opera
             return;
         }
 
+        Iterator statValues = makeIterator(value);
```
Comment (taburet) [inline hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java:128]: Probably passing the `IndexOperationStats` instance to `Bitmap` methods might be a better alternative. Yes, it kind of breaks the separation of responsibilities between `BitmapIndexStore` and `Bitmap`, but we would not need extra iterators allocation and we would iterate the entries only once.

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java [hunk 4]
```diff
@@ -145,6 +147,7 @@ public void insert(Object value, QueryableEntry entry, IndexOperationStats opera
                 }
 
                 bitmap.insert(values, key, entry);
+                accountEntryInsert(operationStats, statValues);
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java:150]: can we account stats after releasing lock? If yes, we can put `accountEntryInsert` in the end of the method after releasing write locks.

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java [hunk 5]
```diff
@@ -403,6 +416,64 @@ Comparable canonicalizeScalarForStorage(Comparable value) {
         return value;
     }
 
+    /**
+     * Accounts insert operations
+     *
+     * @param operationStats current index stats
+     * @param values         iterator which points on first value should be inserted
+     */
+    private void accountEntryInsert(IndexOperationStats operationStats, Iterator values) {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java:425]: Can we rewrite this method like this? So there will be no case to create meta object like iterator. 
```suggestion
private void accountEntryInsert(IndexOperationStats operationStats, Object value) {
        if (value instanceof MultiResult) {
            List results = ((MultiResult) value).getResults();
            for (int i = 0; i < results.size(); i++) {
                operationStats.onEntryAdded(null, results.get(i));
            }
        } else {
            operationStats.onEntryAdded(null, value);
        }
    }
```

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java (hunk 4 above)
Comment (Fly-Style) [reply hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java:150]: @taburet proposed to pass `operationStats` instance to `Bitmap` methods. 
I reviewed my approach and agreed, that Sergey's proposition makes sense and would be cheaper.

Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java]: it will also work, my concern was to do minimum work inside critical section(if it is valid to calculate stats after lock-release)

**Review by ahmetmircik — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java (hunk 4 above)
Comment (Fly-Style) [reply hazelcast/src/main/java/com/hazelcast/query/impl/BitmapIndexStore.java]: Sure, got you.

**Review by taburet — APPROVED** [review]
