### PR TITLE
Map stats fixes

### LINKED ISSUE #4321: [map] IMap jmx statistics evicted together with the map entry
Hazelcast 3.3.3 I have the following map config:

```xml
<hz:map name="xdm-xml" async-backup-count="1" backup-count="0" in-memory-format="OBJECT"
     eviction-policy="LRU" time-to-live-seconds="0" max-size-policy="USED_HEAP_PERCENTAGE" 
     max-size="25" eviction-percentage="10" max-idle-seconds="3600">
/hz:map>
```
When system starts and caches populated and get hits the stats present relevant values for localHits and localGetOperationCount attributes. But after 1 hour of idle some entries evicted and localHits/localGetOperationCount attributes became less and less.. till 0. Looks like you store get/hits statistics together with the entry itself and it gets evicted together with entry.

One more issue with stats: the map contains > 12M of values. Getting statistics for this map takes several minutes - looks like they're aggregated from the map entries too!

### LINKED ISSUE #6406: Provide LocalMapStats: TotalHits, TotalMisses, TotalGets
It would be very helpful if we could get total hits/misses/gets for an IMap on a per node basis (so we can see the effectiveness of the cache).  These should be counted and not reset as entries are evicted.  An additional method "resetTotalCounts()" could be added to allow the end user to reset these statistics.  If the internal data structure stored a DateTime when initialized or reset, then ManCenter could pull these statistics periodically (or they could be posted to ManCenter) which would allow ManCenter to report total hits/misses over time regardless of expiration of entries.

### PR DESCRIPTION
**Pull request by vbekiaris**
* Fixes hits count so it reflects the entire history per record store (not just entries currently in the record store).
* Introduces test & fixes in `MultiMap` statistics

Fixes #4321

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapService.java [hunk 1]
```diff
@@ -428,4 +429,20 @@ public void dispatchEvent(EventData event, EntryListener listener) {
         }
         return multiMapStats;
     }
+
+    private Address getReplicaAddress(IPartition partition, int backupCount, int replicaIndex) {
+        Address replicaAddress = partition.getReplicaAddress(replicaIndex);
+        int tryCount = REPLICA_ADDRESS_TRY_COUNT;
+        int memberSize = nodeEngine.getClusterService().getSize();
+
+        while (memberSize > backupCount && replicaAddress == null && tryCount-- > 0) {
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/multimap/impl/MultiMapService.java]: Unrelated to your PR, but the check `memberSize > backupCount` could lead to unnecessary waiting. You can have more members than the configured backup count and still not have as many replicas as you have backup count. This is because of partition groups. For instance, you have 4 members in 2 partition groups. Even though the map is configured with 3 backups and there are 4 members, there will be only 1 backup replica.
That's why `IPartitionService#getMaxAllowedBackupCount` should be used. A similar use case is [here](https://github.com/hazelcast/hazelcast-enterprise/blob/a734e8cf920ecc0a925f34e9ffa6f878d1629a60/hazelcast-enterprise/src/main/java/com/hazelcast/enterprise/wan/replication/AbstractWanPublisher.java#L244).

**Comment by ahmetmircik** [comment]
Do we really need `misses` field?  Can't we calculate aggregated `misses` all over the cluster like this : `totalMissCount = totalGetCount - totalHitCount` (since with this PR we started to keep all hits from the start of cluster)?

One potential issue is on node addition and removal, hits will be lost and re-calculated from per-entry-hits. This implies that keeping the hit count from the start of cluster will be possible under some restricted conditions.

Maybe an issue for later versions but what about calculating `hits` from over the local map proxy like what we have for get-count now? This way calculating hits can be simpler and can become more powerful to node addition/removal. Also client-side map-proxy can benefit from this new calculation style.

File: hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java [hunk 2]
```diff
@@ -268,11 +284,12 @@ protected void updateStatsOnGet(long now) {
     }
 
     protected void updateStatsOnRemove(long hits) {
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java]: do we need this method any more?

**Comment by vbekiaris** [comment]
>Do we really need misses field? Can't we calculate aggregated misses all over the cluster like this : totalMissCount = totalGetCount - totalHitCount (since with this PR we started to keep all hits from the start of cluster)?

You are right, we should be able to track just 2 quantities and derive the value of the third one. However there are minor inconsistencies in the way these are tracked (eg hits and misses may be incremented when reading a backup, get operation count is only incremented on primary replicas) and resolving all of these is way beyond the scope of this PR.

> One potential issue is on node addition and removal, hits will be lost and re-calculated from per-entry-hits. This implies that keeping the hit count from the start of cluster will be possible under some restricted conditions.

Good point, I realized and documented this limitation for `misses` statistics but hadn't realized that a similar condition applies for the `hits` also. I will push an update to `LocalMapStats.getHits()` javadoc.

> Maybe an issue for later versions but what about calculating hits from over the local map proxy like what we have for get-count now?

Definitely, and at that point we should be able to design a proper way to migrate record-store level statistics.

File: hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java (hunk 2 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/map/impl/recordstore/AbstractRecordStore.java]: I left it there as a placeholder, similarly to `updateStatsOnPut/Get` methods, so that when we need to update stats on remove we won't have to look all over the codebase (I see 6 usages).

**Comment by rruxandra** [comment]
Hello @vbekiaris,

Should this fix also work for the situation when the entries are removed from the distributed map?
I still see the hits counter decreased when an entry is removed or evicted from the distributed map.

Here is a simple test that reproduces the issue in Hazelcast 3.10-BETA-2:

```
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.core.IMap;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class TestHits {

	private HazelcastInstance hcInstance;

	@Before
	public void setUp() {
		hcInstance = Hazelcast.newHazelcastInstance();
	}

	@After
	public void tearDown() {
		hcInstance.shutdown();
	}

	@Test
	public void testHits() {

		IMap<Object, Object> iMap = hcInstance.getMap("test");
		iMap.put("k", "v");
		iMap.get("k");

		assertEquals(1, iMap.getLocalMapStats().getGetOperationCount());
		assertEquals(1, iMap.getLocalMapStats().getHits());

		iMap.remove("k");

		assertEquals(1, iMap.getLocalMapStats().getGetOperationCount());
		assertEquals(1, iMap.getLocalMapStats().getHits());
	}

}
```

Thank you!
