### PR TITLE
[BACKPORT] Client side cache statistics implementation

### LINKED ISSUE #6262: Support cache stats at client side also
Currently, cache stats are only supported at server side and exposed by `CacheProxy`. But at client side cache stats are not calculated and supported so `UnsupportedOperationException` is thrown at `ClientCacheProxy`.

### PR DESCRIPTION
**Pull request by serkan-ozal**
This PR handles client side cache statistics.

Closes #6262

### CODE REVIEW

**Comment by serkan-ozal** [comment]
verify

File: hazelcast-client-new/src/test/java/com/hazelcast/client/cache/stats/ClientCacheStatsTest.java [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+        return HazelcastClientCachingProvider.createCachingProvider(client);
+    }
+
+    protected ClientConfig createClientConfig() {
+        return new ClientConfig();
+    }
+
+    @Test
+    public void testStatisticsDisabled() {
+        _testStatisticsDisabled();
```
Comment (pveentjer) [inline hazelcast-client-new/src/test/java/com/hazelcast/client/cache/stats/ClientCacheStatsTest.java]: what is the purpose of this strange naming convention?

File: hazelcast-client-new/src/test/java/com/hazelcast/client/cache/stats/ClientCacheStatsTest.java [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+    public void testNearCacheStatsWhenNearCacheEnabled() {
+        String cacheName = randomName();
+        CacheConfig cacheConfig = createCacheConfig();
+        cacheConfig.setName(cacheName);
+        ClientConfig clientConfig = ((HazelcastClientProxy) client).getClientConfig();
+        clientConfig.addNearCacheConfig(new NearCacheConfig().setName(cacheName));
+        ICache<Integer, String> cache = createCache(cacheName, cacheConfig);
+        CacheStatistics stats = cache.getLocalCacheStatistics();
+
+        assertNotNull(stats);
```
Comment (pveentjer) [inline hazelcast-client-new/src/test/java/com/hazelcast/client/cache/stats/ClientCacheStatsTest.java]: I see in this test and in the tests above that you are testing if statistics is not null. Please create a dedicated test for that and remove this assert from all the other tests. A test that does:

do
assert
do 
assert

Is probably a broken test since it contains multiple situations.

File: hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheStatisticsImpl.java [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+
+    @Override
+    public long getOwnedEntryCount() {
+        throw new UnsupportedOperationException("This statistic is not supported for client.");
+    }
+
+    @Override
+    public NearCacheStats getNearCacheStatistics() {
+        if (nearCacheStats != null) {
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/cache/impl/ClientCacheStatisticsImpl.java]: I would flip the 2 statements. Normally you first check for the unhappy situation and then you continue to the real logic. For example argument validation.

File: hazelcast/src/test/java/com/hazelcast/cache/stats/CacheStatsTestSupport.java [hunk 4]
```diff
@@ -33,19 +29,63 @@ protected HazelcastInstance getHazelcastInstance() {
...
-    public void testCreationTime() {
+    protected void _testStatisticsDisabled() {
+        long now = System.currentTimeMillis();
+
+        CacheConfig cacheConfig = createCacheConfig();
+        cacheConfig.setStatisticsEnabled(false);
+        ICache<Integer, String> cache = createCache(cacheConfig);
+        CacheStatistics stats = cache.getLocalCacheStatistics();
+
+        assertNotNull(stats);
```
Comment (pveentjer) [inline hazelcast/src/test/java/com/hazelcast/cache/stats/CacheStatsTestSupport.java]: Again an example of do assert do assert.

Split it up in 2 different tests.

File: hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java [hunk 5]
```diff
@@ -409,11 +556,35 @@ protected ClientInvocationFuture invoke(ClientMessage req, Data keyData, int com
         } catch (Exception e) {
             throw ExceptionUtil.rethrow(e);
         }
-        return new ClientDelegatingFuture<Boolean>(future, clientContext.getSerializationService(),
-                putIfAbsentResponseDecoder);
+        ClientDelegatingFuture delegatingFuture =
+                new ClientDelegatingFuture<Boolean>(future, clientContext.getSerializationService(),
+                                                    putIfAbsentResponseDecoder);
+        if (async && statisticsEnabled) {
+            delegatingFuture.andThen(new ExecutionCallback<Object>() {
```
Comment (sancar) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java]: Can't we add this callback after `putIfAbsentAsyncInternal ` returned ?  They are also returning completable future. 
Async methods with isAsync boolean looks odd. I am basically trying to get rid of that boolean .
And my comment applies to all other async methods with async boolean.

**Comment by sancar** [comment]
I had one comment. Other than that, pr looks good.

File: hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java (hunk 5 above)
Comment (serkan-ozal) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java]: @sancar at first version if this PR, I had implemented as you mentioned. But then I thought that it is not good idea using thread pools (executor) for sync operations for just statistics since its overhead to overall system may be more that making it as sync.

**Comment by serkan-ozal** [comment]
Please do not merge it yet. I will override `getCacheEvictions` method at client cache statistics as unsupported operation.

**Comment by serkan-ozal** [comment]
done!

File: hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java (hunk 5 above)
Comment (sancar) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java]: @serkan-ozal  I did not understand. As far as I know, they are running on same executor, aren't they ? I mean, where is it running on when we choose to make the call inside the `putIfAbsentAsyncInternal ` method?

Comment (serkan-ozal) [inline hazelcast-client-new/src/main/java/com/hazelcast/client/cache/impl/AbstractClientInternalCacheProxy.java]: I don't mean there are different executors, I say that this statistics are just simple calculation and no need to handle them by creating an extra object (ExecutionCallback) and processing it on another executor thread.

**Comment by serkan-ozal** [comment]
verify

**Comment by serkan-ozal** [comment]
verify

**Comment by enesakar** [comment]
verify

**Comment by ihsandemir** [comment]
:+1:

**Comment by serkan-ozal** [comment]
verify
