### PR TITLE
Items not to be added to Ringbuffer on store error

### LINKED ISSUE #11209: [ringbuffer] Keep primary and backups consistent in case of a store failure
#### Current behavior
Backups' view of the Ringbuffer differs from the primary's in case of an exception is thrown by the store underlying the Ringbuffer.

##### Example
Add 5 items.
A client adds a 6th.
The primary will add it to its ringbuffer. It will then call store. If the store throws an exception the primary leaves the 6th item in its primary ring buffer but does not add it to the backup ring buffer and it is also missing from the store.

#### Desired behavior
Neither primary nor backups add item(s) in case of a store exception is thrown. Store is responsible for not adding the item(s) in case it throws exceptions. 

Also the contracts between the Ringbuffer and the RingbufferStore needs to be documented in the javadoc.

### PR DESCRIPTION
**Pull request by blazember**
- Fail Ringbuffer add operations (add, addAsync, addAllAsync) in case the underlying store throws an exception
- Define contracts and interactions between Ringbuffer and RingbufferStore
- Format Ringbuffer javadoc
- Bring terms and spelling to a common ground (ringbuffer -> Ringbuffer, entries -> items etc)
- Resolves contradiction between reference manual and javadoc:
	manual: "Hazelcast Ringbuffer is a distributed data structure..."
	javadoc: "Ringbuffer currently is not a distributed data-structure..."

Fixes #11209

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/core/RingbufferStore.java [hunk 1]
```diff
@@ -26,31 +26,48 @@
...
+     * @see com.hazelcast.ringbuffer.Ringbuffer#add(Object)
+     * @see com.hazelcast.ringbuffer.Ringbuffer#addAsync(Object, com.hazelcast.ringbuffer.OverflowPolicy)
      */
     void store(long sequence, T data);
 
     /**
-     * Stores multiple entries. Implementation of this method can optimize the store operation.
+     * Stores multiple items. Implementation of this method can optimize the store operation.
+     *
+     * Exceptions thrown by this method causes the primary and the backups of the
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/core/RingbufferStore.java]: I took a look at the map store and it seems the map operations first call the map store before changing the in-memory state. Can you change the order with the ringbuffer so we avoid this issue instead? So first call the store, then add it to the in-memory ringbuffer.

File: hazelcast/src/main/java/com/hazelcast/ringbuffer/Ringbuffer.java [hunk 2]
```diff
@@ -67,41 +77,44 @@
     long capacity();
 
     /**
-     * Returns number of items in the ringbuffer.
-     *
-     * If no ttl is set, the size will always be equal to capacity after the head completed the first loop
-     * around the ring. This is because no items are getting retired.
+     * Returns number of items in the Ringbuffer.
+     * <p>
+     * If no ttl is set, the size will always be equal to capacity after the head completed the first loop around the ring.
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/ringbuffer/Ringbuffer.java]: Keep it for now, but prefer javadoc up to (around) 72 characters per line in the future. It possibly makes it more readable. I know a lot of the current javadoc is not adhering to this rule.

File: hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java [hunk 3]
```diff
@@ -331,6 +340,9 @@ public Data readAsData(long sequence) {
     }
 
     /**
+     * Reads multiple items from the ring buffer and returns the stored format without serialisation.
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: Doesn't this method return a `long`? What do you mean by `without serialisation`?

File: hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java [hunk 4]
```diff
@@ -234,15 +242,22 @@ public long remainingCapacity() {
      *                                         deserialized
      */
     public long add(T item) {
-        final long sequence = addInternal(item);
+        final long nextSequence = ringbuffer.tailSequence() + 1;
```
Comment (tkountis) [inline hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: Would rather have this inside the `Ringbuffer` implementation. Something like `ringbuffer.peekNextTailSequence()` to adhere to common concepts, and keep this hidden as an implementation detail.

Comment (blazember) [reply hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: Makes sense, changing accordingly.

File: hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java [hunk 5]
```diff
@@ -257,22 +272,20 @@ public long add(T item) {
...
 
-        for (int i = 0; i < items.length; i++) {
-            lastSequence = addInternal(items[i]);
-            if (i == 0) {
-                firstSequence = lastSequence;
-            }
-        }
         if (store.isEnabled() && items.length != 0) {
             try {
                 store.storeAll(firstSequence, convertToData(items));
```
Comment (tkountis) [inline hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: I think this also relies on a specific implementation ie. the sequence being incremental by one as seen in `ArrayRingbuffer`. However, if we had a different implementation of the `Ringbuffer` interface, which worked on a fixed number or sequences that we visit circularly (stupid example I know), then this would break. I think a better approach would have been to have a SequenceIterator exposed when we do `peek` on the ringbuffer, which we could use to get the next sequence in a loop (read only mode). Please don't change sth, this is a bigger change and it was always like that. I guess we will never have another implementation anyway :)

Comment (blazember) [reply hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: Isn't it part of the Ringbuffer's contract that each added item receives a unique sequence so that no collision may happen? The javadoc at least advertises that on add and addAsync. Reference is also bringing an example of using the Ringbuffer as a unique ID generator.

Comment (tkountis) [reply hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: Yep, the example was a bad one. What I am trying to say here is that we are exposing the internals of the implementation, which is `current_seq + 1`. If that changes to be `current_seq + 10`, which is still unique, but with different step, this would break. This is only theoretical of course, that's why I wouldn't change it, I just used this opportunity to discuss it from a design point of view.

Comment (blazember) [reply hazelcast/src/main/java/com/hazelcast/ringbuffer/impl/RingbufferContainer.java]: Alright, got it. Then adding the other change you proposed (peekNextTailSequence, on its way) internalize this logic into the Ringbuffer and hides from the external world. It is cleaner that way anyways.

File: hazelcast/src/main/java/com/hazelcast/ringbuffer/Ringbuffer.java [hunk 6]
```diff
@@ -112,16 +125,20 @@
...
      * publishing items on this Ringbuffer. However you need to take care of correctly determining an initial ID when any node
-     * uses the ringbuffer for the first time. The most reliable way to do that is to write a dummy item into the ringbuffer and
+     * uses the Ringbuffer for the first time. The most reliable way to do that is to write a dummy item into the Ringbuffer and
      * use the returned sequence as initial ID. On the reading side, this dummy item should be discard. Please keep in mind that
      * this ID is not the sequence of the item you are about to publish but from a previously published item. So it can't be used
      * to find that item.
+     * <p>
+     * If the Ringbuffer is backed by a {@link com.hazelcast.core.RingbufferStore}, the item gets persisted by the underlying
+     * store via {@link com.hazelcast.core.RingbufferStore#store(long, Object)}. Note that in case an exception is thrown by the
+     * store, it makes the Ringbuffer not adding the item, keeping the store, primary and the backups consistent.
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/ringbuffer/Ringbuffer.java]: ... `it prevents the item from being added to the Ringbuffer...`, same below

File: hazelcast/src/main/java/com/hazelcast/core/RingbufferStore.java [hunk 7]
```diff
@@ -26,31 +26,52 @@
     /**
      * Stores one item with it's corresponding sequence.
      *
+     * Exceptions thrown by this method prevents {@link com.hazelcast.ringbuffer.Ringbuffer}
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/core/RingbufferStore.java]: `Exceptions thrown by this method prevent the ...`
