### PR TITLE
Filter out unwanted network interfaces in DefaultAddressPicker

### LINKED ISSUE #11795: The default network interface selection chooses wrong interface in some cases
*This issue is based on existing PR: #11504*

Hazelcast binds to a wrong network interface in some cases. The problem is with network interfaces which are not `UP` (e.g. Docker uses such interface for in-host communication).  

The problem is in  `DefaultAddressPicker` class which doesn't check network interface status. The   `DefaultAddressPicker` is responsible for selecting a network interface for Hazelcast. It picks the first available non-loopback IP address.

**Suggested fix**
Change the `DefaultAddressPicker` implementation so it filters out network interfaces which are:
* `DOWN`
* or `loopback`
* or `virtual`

### PR DESCRIPTION
**Pull request by kwart**
Fixes #11795

This commit improves selection of bind addresses in `DefaultAddressPicker`.
When `InterfaceDefinition`s are not provided, only the non-loopback && non-virtual network interfaces which are UP are used as candidates for picking address.

The original implementation picks the first available non-loopback address of any interface. After the change the flags of the network interface are checked too.

Users can hit the issue when they have Docker installed. The Docker creates new interface and host binds usually to `172.17.0.1`. 
The Enumeration of NetworkInterfaces can look like:
```
'docker0': isUp=false, isVirtual=false, isLoopback=false
'virbr0': isUp=false, isVirtual=false, isLoopback=false
'virbr1': isUp=false, isVirtual=false, isLoopback=false
'enp0s25': isUp=true, isVirtual=false, isLoopback=false
'lo': isUp=true, isVirtual=false, isLoopback=true
```
So the first available IP address is the `172.17.0.1`.

When the second instance is started, the members are not able to create cluster
```
Connection[id=14, /172.17.0.1:5701->/192.168.1.4:43447, endpoint=null, alive=false, type=MEMBER] closed. Reason: Wrong bind request from /192.168.1.4, identified as /172.17.0.1
```

I saw the issue reported also in OKAPI JIRA [OKAPI-104](https://issues.folio.org/browse/OKAPI-104)

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java [hunk 1]
```diff
@@ -0,0 +1,429 @@
...
+    private final Config config = new Config();
+    private final HazelcastProperties hazelcastProperties = new HazelcastProperties(config);
+
+    /**
+     * Test class setup: Prefer IPv4, but only by standard Java property.
+     */
+    @BeforeClass
+    public static void beforeClass() {
+        origPreferIpv4 = setSystemProperty(SYS_PROP_PREFER_IPV4, "true");
+        origPreferIpv4Hazelcast = setSystemProperty("hazelcast.prefer.ipv4.stack", "false");
```
Comment (mmedenjak) [inline hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: You can use `GroupProperty.PREFER_IPv4_STACK.getName()` instead of `hazelcast.prefer.ipv4.stack` here

File: hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java [hunk 2]
```diff
@@ -334,15 +334,19 @@ private static AddressDefinition pickLoopbackAddress(String host, int defaultPor
     private AddressDefinition pickMatchingAddress(Collection<InterfaceDefinition> interfaces) throws SocketException {
         Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
         boolean preferIPv4Stack = preferIPv4Stack();
+        boolean matchInterfaceDefinition = interfaces != null && !interfaces.isEmpty();
```
Comment (mmedenjak) [inline hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java]: You can use `CollectionUtil.isNotEmpty(interfaces)` as well

File: hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java (hunk 1 above)
Comment (kwart) [reply hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: I tend to use the string directly in the test. It can catch backward compatibility issues when the GroupProperty is refactored.

File: hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java (hunk 2 above)
Comment (kwart) [reply hazelcast/src/main/java/com/hazelcast/instance/DefaultAddressPicker.java]: Thanks, I will update it.

File: hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java [hunk 3]
```diff
@@ -0,0 +1,429 @@
...
+    public void testComplexScenario() throws Exception {
+        List<NetworkInterface> networkInterfaces = new ArrayList<NetworkInterface>();
+        networkInterfaces.add(
+                createNetworkConfig(builder().withName("lo").withLoopback(true).withAddresses("127.0.0.1", "::1").build()));
+        networkInterfaces
+                .add(createNetworkConfig(builder().withName("docker0").withUp(false).withAddresses("172.17.0.1").build()));
+        networkInterfaces.add(createNetworkConfig(builder().withName("wlp3s0").withUp(false).build()));
+        networkInterfaces.add(createNetworkConfig(
+                builder().withName("enp0s25").withAddresses("fe80::9711:82f4:383a:e254", "192.168.1.4").build()));
+        networkInterfaces
```
Comment (mmedenjak) [inline hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: I'm going to guess you wanted to make this interface virtual. Otherwise, I don't see any virtual interfaces being created.

Comment (kwart) [reply hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: Good catch. I'm going to add 2 test methods with virtual Network Interfaces.

**Comment by kwart** [comment]
Thanks for the reviews.

Changes are implemented and tests extended.

File: hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java (hunk 1 above)
Comment (mmedenjak) [reply hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: Right, seems reasonable.

Comment (jerrinot) [reply hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: there is convenience for this. see it in [action](https://github.com/jerrinot/hazelcast/blob/0862c483877c7ba750cda91700b3d4e47bf941b9/hazelcast/src/test/java/com/hazelcast/spi/discovery/multicast/MemberToMemberDiscoveryTest.java) It does auto-cleaning and hopefully makes the test somewhat cleaner.

Comment (kwart) [reply hazelcast/src/test/java/com/hazelcast/instance/DefaultAddressPickerInterfacesTest.java]: :+1: will fix
