### PR TITLE
NullPointerException on cluster properties #18102

### LINKED ISSUE #18102: NullPointerException on cluster properties
Cluster properties accept a null, but then throw a NPE when retrieved. Neither is good.

Reproducer, tested on 4.1.1

```
import com.hazelcast.config.Config;
import com.hazelcast.spi.properties.ClusterProperty;

public class Application {

    public static void main(String[] args) throws Exception {
        Config config = new Config();
        System.out.println("BEFORE " + config.getProperty(ClusterProperty.PARTITION_COUNT.getName()));
        config.setProperty(ClusterProperty.PARTITION_COUNT.getName(), null);
        System.out.println("AFTER: " + config.getProperty(ClusterProperty.PARTITION_COUNT.getName()));
    }

}
```

### PR DESCRIPTION
**Pull request by fkardashov**
NullPointerException on cluster properties
Fix NPE if try set key or value as null

Fixes #18102

### CODE REVIEW

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/config/Config.java [hunk 1]
```diff
@@ -530,7 +530,10 @@ public String getProperty(String name) {
      * Hazelcast System Properties</a>
      */
     public Config setProperty(String name, String value) {
-        properties.put(name, value);
+        if (!isNullOrEmptyAfterTrim(name) && !isNullOrEmptyAfterTrim(value)) {
```
Comment (blazember) [inline hazelcast/src/main/java/com/hazelcast/config/Config.java:533]: Since we don't want to let the user setting the property if either the `key` or the `value` is `null`, maybe throwing an `IllegalArgumentException` would be more appropriate than silently ignoring the call. WDYT?

Comment (fkardashov) [reply hazelcast/src/main/java/com/hazelcast/config/Config.java]: fixed.
throw IllegalArgumentExeption
and added two tests.

**Comment by mmedenjak** [comment]
run-lab-run

**Review by blazember — APPROVED** [review]
LGTM :+1: 
BTW, on current master I get NPE if trying to set either key or value as `null`. But throwing `IllegalArgumentException` is more meaningful.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
Thank you for the contribution @fkardashov !
