### PR TITLE
Fix SqlRollingUpgradeTest

### LINKED ISSUE #19035: com.hazelcast.jet.sql.impl.SqlRollingUpgradeTest.when_clientSql_then_usesEitherVersion
Failed on http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/6012/testReport/com.hazelcast.jet.sql.impl/SqlRollingUpgradeTest/when_clientSql_then_usesEitherVersion/

Stacktrace:
```
java.lang.AssertionError: expected:<1> but was:<0>
	at com.hazelcast.jet.sql.impl.SqlRollingUpgradeTest.lambda$when_clientSql_then_usesEitherVersion$2(SqlRollingUpgradeTest.java:70)
	at com.hazelcast.jet.sql.impl.SqlRollingUpgradeTest.when_clientSql_then_usesEitherVersion(SqlRollingUpgradeTest.java:69)
```

Standard output:
```
Finished Running Test: when_lightJob_then_usesTheSubmitterVersion in 0.106 seconds.
Started Running Test: when_clientSql_then_usesEitherVersion
13:56:54,071 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,107 DEBUG || - [JetSqlBackend] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Before logical opt:
LogicalProject(v=[$0], __key=[$1], this=[$2])
  LogicalJoin(condition=[=($3, $0)], joinType=[inner])
    LogicalTableFunctionScan(invocation=[GENERATE_STREAM(1)], rowType=[RecordType:peek(BIGINT v)])
    LogicalProject(__key=[$0], this=[$1], __key0=[CAST($0):BIGINT(63)])
      LogicalTableScan(table=[[hazelcast, public, m[projects=[0, 1]]]])

13:56:54,171 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,255 DEBUG || - [JetSqlBackend] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] After logical opt:
JoinLogicalRel(condition=[=(CAST($1):BIGINT(63), $0)], joinType=[inner])
  FullScanLogicalRel(table=[[hazelcast, stream, stream_6cb474e0_093e_41cb_9db7_5eb1c09e2283[projects=[0]]]])
  FullScanLogicalRel(table=[[hazelcast, public, m[projects=[0, 1]]]])

13:56:54,272 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,331 DEBUG || - [JetSqlBackend] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] After physical opt:
JoinNestedLoopPhysicalRel(condition=[=(CAST($1):BIGINT(63), $0)], joinType=[inner])
  FullScanPhysicalRel(table=[[hazelcast, stream, stream_6cb474e0_093e_41cb_9db7_5eb1c09e2283[projects=[0]]]])
  FullScanPhysicalRel(table=[[hazelcast, public, m[projects=[0, 1]]]])

13:56:54,372 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,379 DEBUG || - [LightMasterContext] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Light job 0677-2280-1f81-0002 will run on a subset of members: 1 out of 2 members with version 5.1
13:56:54,381 DEBUG || - [LightMasterContext] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start executing light job 0677-2280-1f81-0002, execution graph in DOT format:
digraph DAG {
	"Stream[stream.stream_6cb474e0_093e_41cb_9db7_5eb1c09e2283]" [localParallelism=1];
	"Join(Scan-IMap[public.m])" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"Stream[stream.stream_6cb474e0_093e_41cb_9db7_5eb1c09e2283]" -> "Join(Scan-IMap[public.m])" [queueSize=1024];
	"Join(Scan-IMap[public.m])" -> "ClientSink" [label="distributed to [127.0.0.1]:5702-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
13:56:54,381 DEBUG || - [LightMasterContext] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Building execution plan for 0677-2280-1f81-0002
13:56:54,382 DEBUG || - [LightMasterContext] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Built execution plans for 0677-2280-1f81-0002
13:56:54,384 DEBUG || - [InitExecutionOperation] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 0677-2280-1f81-0002, execution 0677-2280-1f81-0002 from [127.0.0.1]:5702
13:56:54,396 DEBUG || - [JobExecutionService] hz.brave_proskuriakova.client-query.thread-2 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for light job ID=0677-2280-1f81-0002, jobName='0677-2280-1f81-0002', executionId=0677-2280-1f81-0002 initialized, will start the execution
13:56:54,400 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '0677-2280-1f81-0002', execution 0677-2280-1f81-0002
13:56:54,400 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-4 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '0677-2280-1f81-0002', execution 0677-2280-1f81-0002 completed
13:56:54,472 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,572 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,673 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,773 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,873 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress
13:56:54,974 DEBUG || - [JobCoordinationService] hz.nifty_proskuriakova.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting non-light jobs because rolling upgrade is in progress

... Trimmed these `Not starting non-light jobs because rolling upgrade is in progress` logs

13:58:54,720  INFO |when_clientSql_then_usesEitherVersion| - [SimpleTestInClusterSupport] Time-limited test - Ditching 0 jobs in SimpleTestInClusterSupport.@After: []
13:58:54,720  INFO |when_clientSql_then_usesEitherVersion| - [SimpleTestInClusterSupport] Time-limited test - Destroying 2 distributed objects in SimpleTestInClusterSupport.@After: [hz:impl:replicatedMapService/__sql.catalog, hz:impl:mapService/m]
13:58:54,720 ERROR || - [EventServiceImpl] hz.nifty_proskuriakova.event-41 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] hz.nifty_proskuriakova.event-41 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@7d652b50
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 1217744d-0484-4c40-a2f1-4190e4b1ce5e this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.0-SNAPSHOT.jar:5.0-SNAPSHOT]
BuildInfo right after when_clientSql_then_usesEitherVersion(com.hazelcast.jet.sql.impl.SqlRollingUpgradeTest): BuildInfo{version='5.0-SNAPSHOT', build='20210709', buildNumber=20210709, revision=cd331bd, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_clientSql_then_usesEitherVersion(com.hazelcast.jet.sql.impl.SqlRollingUpgradeTest):'
13:56:50, accumulated pauses: 43 ms, max pause: 13 ms, pauses over 1000 ms: 0
13:56:55, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:00, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:05, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:10, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:15, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:20, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:25, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:30, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:35, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:40, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:45, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:50, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:57:55, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:00, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:05, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:10, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:15, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:20, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:25, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:30, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:35, accumulated pauses: 29 ms, max pause: 0 ms, pauses over 1000 ms: 0
13:58:40, accumulated pauses: 31 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:58:45, accumulated pauses: 34 ms, max pause: 1 ms, pauses over 1000 ms: 0
13:58:50, accumulated pauses: 243 ms, max pause: 213 ms, pauses over 1000 ms: 0


No metrics recorded during the test


```

### PR DESCRIPTION
**Pull request by viliam-durina**
`ProcessorMetaSupplier.forceTotalParallelismOne` used to pick the member
that will run the processor by examining the current partition table. A
light job, during a rolling upgrade, doesn't use all the members. It
could happen that a member that is not a participant, will be chosen, in
which case the total parallelism would be 0 (i.e. the processor will not
run at all).

This was an issue even before the rolling upgrade support - if a member
was added after the job was started, but before the PMS ran, it could
also happen that the processor won't be run at all.

Fixes #19035

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java [hunk 1]
```diff
@@ -391,8 +394,13 @@ public void init(@Nonnull Context context) {
...
                 }
-                ownerAddress = context.hazelcastInstance().getPartitionService().getPartition(
-                        StringPartitioningStrategy.getPartitionKey(partitionKey)).getOwner().getAddress();
+                String key = StringPartitioningStrategy.getPartitionKey(partitionKey);
+                int partitionId = context.hazelcastInstance().getPartitionService().getPartition(key).getPartitionId();
+                ownerAddress = context.partitionAssignment().entrySet().stream()
+                        .filter(en -> arrayIndexOf(partitionId, en.getValue()) >= 0)
+                        .findAny()
+                        .map(Entry::getKey)
+                        .orElseThrow(() -> new RuntimeException("Owner partition not assigned to any participating member"));
```
Comment (ufukyilmaz) [inline hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java:403]: We don't expect to enter the exception throwing case here, right? Or I wonder when the program goes into the exception case here

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/core/ProcessorMetaSupplier.java:403]: No, it should never happen. Every partition should be owned by some processor. If you're curious where will it go look here: https://github.com/hazelcast/hazelcast/blob/0057d5c4c2174ef7bc9aee7ca75b542e4edcf152/hazelcast/src/test/java/com/hazelcast/jet/core/ExecutionLifecycleTest.java#L166

**Review by ufukyilmaz — APPROVED** [review]

**Review by gurbuzali — APPROVED** [review]
