### PR TITLE
Handle undefined cleanup order for PS and PMS

### LINKED ISSUE #19001: com.hazelcast.jet.core.TopologyChangeTest.when_coordinatorLeavesDuringExecution_then_jobCompletes
_master_ (commit https://github.com/hazelcast/hazelcast/commit/635391f382bd290648544b91b0b2ee106738d0e4)

Failed on Zulu JDK 16 - http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/6/testReport/com.hazelcast.jet.core/TopologyChangeTest/when_coordinatorLeavesDuringExecution_then_jobCompletes_liteMemberFlags_1__/

Stacktrace:
```
java.lang.AssertionError: expected:<2> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.core.TopologyChangeTest.lambda$when_coordinatorLeavesDuringExecution_then_jobCompletes$4(TopologyChangeTest.java:299)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1260)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1362)
	at com.hazelcast.jet.core.TopologyChangeTest.when_coordinatorLeavesDuringExecution_then_jobCompletes(TopologyChangeTest.java:297)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:831)```
```

Standard output:
```
Finished Running Test: when_nodeIsNotJobParticipant_then_initFails[liteMemberFlags(1)] in 1.037 seconds.
Started Running Test: when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]
02:31:14,656  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:31:14,657  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [logo] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:31:14,657  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:31:14,658  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210625 - 949deba) starting at [127.0.0.1]:5701
02:31:14,658  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [system] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:31:14,660  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:31:14,663  WARN |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [CPSubsystem] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:31:14,665  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JetServiceBackend] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:31:14,666  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [Diagnostics] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:31:14,666  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
02:31:14,666  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [ClusterService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 5c1594a2-7911-4b39-9f48-3f9dfd08e435 this lite
]

02:31:14,666  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JetExtension] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Jet is enabled
02:31:14,666 DEBUG |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JobCoordinationService] hz.fervent_euler.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:31:14,667  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [LifecycleService] Time-limited test - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
02:31:14,667  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [MetricsConfigHelper] Time-limited test - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:31:14,667  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [logo] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:31:14,667  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:31:14,667  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210625 - 949deba) starting at [127.0.0.1]:5702
02:31:14,667  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [system] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:31:14,668  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [HealthMonitor] hz.fervent_euler.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=185.5G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=2.6G, heap.memory.free=1.4G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=64.31%, heap.memory.used/max=64.31%, minor.gc.count=1326, minor.gc.time=13120ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=2.96, thread.count=65, thread.peakCount=2132, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:31:14,668  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [MetricsConfigHelper] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:31:14,670  WARN |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [CPSubsystem] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:31:14,672  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JetServiceBackend] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:31:14,673  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [Diagnostics] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:31:14,673  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
02:31:14,674  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [MockServer] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}
02:31:14,674  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [MockServer] hz.fervent_euler.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}
02:31:14,674  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [ClusterService] hz.fervent_euler.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 5c1594a2-7911-4b39-9f48-3f9dfd08e435 this lite
	Member [127.0.0.1]:5702 - 11b28e93-2a10-4eb2-992f-86d370186ffd
]

02:31:14,767 DEBUG |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JobCoordinationService] hz.fervent_euler.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:31:14,774  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [ClusterService] hz.peaceful_euler.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 5c1594a2-7911-4b39-9f48-3f9dfd08e435 lite
	Member [127.0.0.1]:5702 - 11b28e93-2a10-4eb2-992f-86d370186ffd this
]

02:31:14,867 DEBUG |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JobCoordinationService] hz.fervent_euler.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:31:14,967 DEBUG |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JobCoordinationService] hz.fervent_euler.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:31:15,067 DEBUG |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JobCoordinationService] hz.fervent_euler.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:31:15,167 DEBUG |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JobCoordinationService] hz.fervent_euler.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:31:15,174  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [JetExtension] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Jet is enabled
02:31:15,174  INFO |when_coordinatorLeavesDuringExecution_then_jobCompletes[liteMemberFlags(1)]| - [LifecycleService] Time-limited test - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED```
```

### LINKED ISSUE #19381: com.hazelcast.jet.core.SplitBrainTest.when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge
_master_ (commit 9ce0da2756b4ab15df48e9af18991e893a435dc0)

Failed on Zulu JDK 16: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK16-nightly/14/testReport/com.hazelcast.jet.core/SplitBrainTest/when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge/

Stacktrace:
```
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at com.hazelcast.jet.core.SplitBrainTest.lambda$when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge$23(SplitBrainTest.java:245)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1262)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1279)
	at com.hazelcast.jet.core.SplitBrainTest.lambda$when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge$25(SplitBrainTest.java:245)
	at com.hazelcast.jet.core.JetSplitBrainTestSupport.testSplitBrain(JetSplitBrainTestSupport.java:128)
	at com.hazelcast.jet.core.SplitBrainTest.when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge(SplitBrainTest.java:257)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Standard output:
```
02:32:29,075  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:32:29,076  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [logo] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:32:29,076  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:32:29,076  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210820 - 9ce0da2) starting at [127.0.0.1]:5701
02:32:29,076  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:32:29,080  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:32:29,088  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [CPSubsystem] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:32:29,091  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetServiceBackend] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:32:29,092  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Diagnostics] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:32:29,092  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTING
02:32:29,092  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetExtension] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Jet is enabled
02:32:29,092  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:1, ver:1} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
]

02:32:29,092  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is STARTED
02:32:29,092 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,092  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:32:29,093  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [logo] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:32:29,093  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:32:29,093  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210820 - 9ce0da2) starting at [127.0.0.1]:5702
02:32:29,093  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:32:29,095  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.optimistic_ptolemy.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=158.2G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.5G, heap.memory.free=1.5G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=61.70%, heap.memory.used/max=61.70%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.25, thread.count=67, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=0, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:29,095  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:32:29,099  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [CPSubsystem] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:32:29,102  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetServiceBackend] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:32:29,103  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Diagnostics] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:32:29,104  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is STARTING
02:32:29,104  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=true}
02:32:29,104  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.optimistic_ptolemy.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=true}
02:32:29,104  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.optimistic_ptolemy.generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
]

02:32:29,192 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,204  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetExtension] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Jet is enabled
02:32:29,205  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:2} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
]

02:32:29,293 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,394 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,496 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,597 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,608  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is STARTED
02:32:29,610  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:32:29,615  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [logo] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:32:29,615  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:32:29,615  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210820 - 9ce0da2) starting at [127.0.0.1]:5703
02:32:29,615  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:32:29,615  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.unruffled_ptolemy.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=158.1G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.5G, heap.memory.free=1.5G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=61.93%, heap.memory.used/max=61.93%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=2.86%, load.system=100.00%, load.systemAverage=33.25, thread.count=93, thread.peakCount=2121, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=11, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:29,645  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:32:29,675  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [CPSubsystem] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:32:29,692  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetServiceBackend] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:32:29,699 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,705  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Diagnostics] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:32:29,706  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5703 is STARTING
02:32:29,707  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5701, alive=true}
02:32:29,712  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.optimistic_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5703, alive=true}
02:32:29,719  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.optimistic_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
]

02:32:29,722  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5703, alive=true}
02:32:29,724  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
]

02:32:29,800 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:29,810  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetExtension] hz.lucid_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Jet is enabled
02:32:29,812  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.lucid_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] 

Members {size:3, ver:3} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 this
]

02:32:29,901 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,001 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,101 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,202 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,210  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5702, alive=true}
02:32:30,210  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5703 is STARTED
02:32:30,210  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:32:30,211  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [logo] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:32:30,211  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:32:30,211  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210820 - 9ce0da2) starting at [127.0.0.1]:5704
02:32:30,211  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:32:30,212  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.lucid_ptolemy.HealthMonitor - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=158.1G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.5G, heap.memory.free=1.5G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=62.32%, heap.memory.used/max=62.32%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.25, thread.count=130, thread.peakCount=2121, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=12, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:30,213  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:32:30,217  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [CPSubsystem] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:32:30,220  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetServiceBackend] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:32:30,221  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Diagnostics] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:32:30,221  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5704 is STARTING
02:32:30,221  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5701, alive=true}
02:32:30,222  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.optimistic_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5704, alive=true}
02:32:30,222  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.optimistic_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:4} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
]

02:32:30,223  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.lucid_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5704, alive=true}
02:32:30,223  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5704, alive=true}
02:32:30,223  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:4} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
]

02:32:30,223  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.lucid_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:4} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 this
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
]

02:32:30,302 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,322  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetExtension] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Jet is enabled
02:32:30,323  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:4} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68 this
]

02:32:30,402 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,502 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,603 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,703 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,722  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5702, alive=true}
02:32:30,722  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5703, alive=true}
02:32:30,722  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5704 is STARTED
02:32:30,722  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [LOCAL] [dev] [5.0-SNAPSHOT] Overridden metrics configuration with system property 'hazelcast.metrics.collection.frequency'='1' -> 'MetricsConfig.collectionFrequencySeconds'='1'
02:32:30,723  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [logo] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] 
	+       +  o    o     o     o---o o----o o      o---o     o     o----o o--o--o
	+ +   + +  |    |    / \       /  |      |     /         / \    |         |   
	+ + + + +  o----o   o   o     o   o----o |    o         o   o   o----o    |   
	+ +   + +  |    |  /     \   /    |      |     \       /     \       |    |   
	+       +  o    o o       o o---o o----o o----o o---o o       o o----o    o   
02:32:30,723  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Copyright (c) 2008-2021, Hazelcast, Inc. All Rights Reserved.
02:32:30,723  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Hazelcast Platform 5.0-SNAPSHOT (20210820 - 9ce0da2) starting at [127.0.0.1]:5705
02:32:30,723  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [system] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Cluster name: dev
02:32:30,724  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.affectionate_ptolemy.HealthMonitor - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=158.0G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.5G, heap.memory.free=1.5G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=62.62%, heap.memory.used/max=62.62%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.25, thread.count=162, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=15, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:30,726  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MetricsConfigHelper] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Collecting debug metrics and sending to diagnostics is enabled
02:32:30,730  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [CPSubsystem] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] CP Subsystem is not enabled. CP data structures will operate in UNSAFE mode! Please note that UNSAFE mode will not provide strong consistency guarantees.
02:32:30,733  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetServiceBackend] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Setting number of cooperative threads and default parallelism to 4
02:32:30,734  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Diagnostics] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
02:32:30,734  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5705 is STARTING
02:32:30,734  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5701, alive=true}
02:32:30,735  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.optimistic_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5705, alive=true}
02:32:30,735  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.optimistic_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:5, ver:5} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
	Member [127.0.0.1]:5705 - 462bbd0d-953b-44a8-94df-924f70631b34
]

02:32:30,736  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.lucid_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5705, alive=true}
02:32:30,736  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5705, alive=true}
02:32:30,736  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5705, alive=true}
02:32:30,736  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.unruffled_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:5, ver:5} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
	Member [127.0.0.1]:5705 - 462bbd0d-953b-44a8-94df-924f70631b34
]

02:32:30,736  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.lucid_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] 

Members {size:5, ver:5} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 this
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
	Member [127.0.0.1]:5705 - 462bbd0d-953b-44a8-94df-924f70631b34
]

02:32:30,736  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] 

Members {size:5, ver:5} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68 this
	Member [127.0.0.1]:5705 - 462bbd0d-953b-44a8-94df-924f70631b34
]

02:32:30,803 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:30,835  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetExtension] hz.blissful_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Jet is enabled
02:32:30,836  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.blissful_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] 

Members {size:5, ver:5} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
	Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
	Member [127.0.0.1]:5705 - 462bbd0d-953b-44a8-94df-924f70631b34 this
]

02:32:30,903 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:31,003 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:31,104 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:31,204 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5702, alive=true}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5703, alive=true}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Created connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5704, alive=true}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5705 is STARTED
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetSplitBrainTestSupport] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - Going to create split-brain...
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5703, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5703, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:31,235  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removing Member [127.0.0.1]:5704 - b8be6c96-ba23-4ddb-a469-d24ccc520f68
02:32:31,235  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [OutboundResponseHandler] hz.blissful_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Cannot send response: null to [127.0.0.1]:5701. com.hazelcast.internal.cluster.impl.operations.FinalizeJoinOp{serviceName='hz:core:clusterService', identityHash=321299039, partitionId=-1, replicaIndex=0, callId=30, invocationTime=1629426751235 (2021-08-20 02:32:31.235), waitTimeout=-1, callTimeout=60000, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, targetUuid=462bbd0d-953b-44a8-94df-924f70631b34, members=MemberInfo{address=[127.0.0.1]:5701, uuid=58c37c17-68e3-471e-84e3-e0e6b12b3338, liteMember=false, memberListJoinVersion=1} MemberInfo{address=[127.0.0.1]:5702, uuid=394ff09f-fb1c-4664-a115-dd0741e2fd23, liteMember=false, memberListJoinVersion=2} MemberInfo{address=[127.0.0.1]:5703, uuid=36e002fb-dd9d-47a5-8ca7-f4b5b9da0743, liteMember=false, memberListJoinVersion=3} MemberInfo{address=[127.0.0.1]:5704, uuid=b8be6c96-ba23-4ddb-a469-d24ccc520f68, liteMember=false, memberListJoinVersion=4} MemberInfo{address=[127.0.0.1]:5705, uuid=462bbd0d-953b-44a8-94df-924f70631b34, liteMember=false, memberListJoinVersion=5} , postJoinOp=com.hazelcast.internal.cluster.impl.operations.OnJoinOp{serviceName='hz:core:clusterService', identityHash=387523811, partitionId=-1, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, tenantControl=com.hazelcast.spi.impl.tenantcontrol.NoopTenantControl@0, operations=[com.hazelcast.map.impl.operation.PostJoinMapOpera
...[truncated 104384 chars]...
0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:48,488 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:48,588 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:48,688 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:48,789 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:48,889 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:48,989 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,089 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,097  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.optimistic_ptolemy.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=157.9G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.6G, heap.memory.free=1.4G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=64.67%, heap.memory.used/max=64.67%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.06, thread.count=222, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=63, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:49,189 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,290 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,390 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,490 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,590 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,618  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.unruffled_ptolemy.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=157.9G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.6G, heap.memory.free=1.4G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=64.72%, heap.memory.used/max=64.72%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.06, thread.count=222, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=47, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:49,690 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,791 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,891 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:49,991 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,091 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,191 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,214  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.lucid_ptolemy.HealthMonitor - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=157.9G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.6G, heap.memory.free=1.4G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=64.79%, heap.memory.used/max=64.79%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.06, thread.count=222, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=46, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:50,291 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,388 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,391 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,492 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,592 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,693 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,755  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.affectionate_ptolemy.HealthMonitor - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=157.9G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.6G, heap.memory.free=1.4G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=64.84%, heap.memory.used/max=64.84%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=3.08%, load.system=100.00%, load.systemAverage=33.06, thread.count=222, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=80, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:50,793 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,894 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:50,995 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,095 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,195 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,239  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [HealthMonitor] hz.blissful_ptolemy.HealthMonitor - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=157.9G, swap.space.total=4.0G, swap.space.free=3.8G, heap.memory.used=2.6G, heap.memory.free=1.4G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=64.93%, heap.memory.used/max=64.93%, minor.gc.count=990, minor.gc.time=12252ms, major.gc.count=0, major.gc.time=0ms, load.process=0.00%, load.system=100.00%, load.systemAverage=33.06, thread.count=222, thread.peakCount=2121, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=109, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=4, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
02:32:51,295 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,395 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,495 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,596 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,696 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,796 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,896 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:51,996 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,096 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,196 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,297 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,388 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,397 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,497 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,597 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,697 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,798 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,898 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:52,998 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,098 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,198 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,298 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,399 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,499 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,600 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,701 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,802 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:53,902 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,003 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,103 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,203 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,303 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,388 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,403 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,503 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,604 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,704 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,804 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:54,904 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:55,004 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:55,105 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:55,205 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:55,305 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:55,405 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:55,505 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:58,087 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:58,089 DEBUG |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JobCoordinationService] hz.optimistic_ptolemy.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Not starting jobs because partitions are not yet initialized.
02:32:58,107  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [JetTestSupport] Time-limited test - Terminating instanceFactory in JetTestSupport.@After
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
02:32:58,108  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Terminating forcefully...
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5703, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5703, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5703, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5703, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5703, alive=false}
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5703, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:32:58,108  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 this
02:32:58,108  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 this
02:32:58,108  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743 this
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removing Member [127.0.0.1]:5703 - 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:10} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
]

02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.optimistic_ptolemy.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.affectionate_ptolemy.cached.thread-7 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.unruffled_ptolemy.cached.thread-19 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:10} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655 this
]

02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Shutting down node engine...
02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.unruffled_ptolemy.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:10} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
]

02:32:58,108  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.blissful_ptolemy.cached.thread-7 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5703, UUID: 36e002fb-dd9d-47a5-8ca7-f4b5b9da0743
02:32:58,109  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.blissful_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] 

Members {size:4, ver:10} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0 this
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
]

02:32:58,110  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [NodeExtension] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
02:32:58,110  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
02:32:58,110  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5703 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
02:32:58,110  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
02:32:58,110  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Terminating forcefully...
02:32:58,110  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5702, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5702, alive=false}
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5702, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:32:58,111  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
02:32:58,111  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23 this
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removing Member [127.0.0.1]:5702 - 394ff09f-fb1c-4664-a115-dd0741e2fd23
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.optimistic_ptolemy.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 394ff09f-fb1c-4664-a115-dd0741e2fd23
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.blissful_ptolemy.cached.thread-7 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 394ff09f-fb1c-4664-a115-dd0741e2fd23
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:3, ver:11} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
]

02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.affectionate_ptolemy.cached.thread-7 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5702, UUID: 394ff09f-fb1c-4664-a115-dd0741e2fd23
02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.blissful_ptolemy.generic-operation.thread-1 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] 

Members {size:3, ver:11} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0 this
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
]

02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] 

Members {size:3, ver:11} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655 this
]

02:32:58,111  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Shutting down node engine...
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [NodeExtension] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5705 is SHUTTING_DOWN
02:32:58,113  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Terminating forcefully...
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5705, alive=false}
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:32:58,113  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0 is suspected to be dead for reason: Connection manager is stopped on Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0 this
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removing Member [127.0.0.1]:5705 - eff110c4-1838-4b24-9b04-a747abbe8cb0
02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:12} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
]

02:32:58,113  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.optimistic_ptolemy.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5705, UUID: eff110c4-1838-4b24-9b04-a747abbe8cb0
02:32:58,114  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.affectionate_ptolemy.cached.thread-7 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5705, UUID: eff110c4-1838-4b24-9b04-a747abbe8cb0
02:32:58,114  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] hz.affectionate_ptolemy.priority-generic-operation.thread-0 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] 

Members {size:2, ver:12} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338
	Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655 this
]

02:32:58,114  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Shutting down node engine...
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [NodeExtension] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 3 ms.
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5705 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5705 is SHUTDOWN
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5704 is SHUTTING_DOWN
02:32:58,116  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Terminating forcefully...
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5704, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5704, alive=false}
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MockServer] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5704, remoteEndpoint=[127.0.0.1]:5701, alive=false}
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [MembershipManager] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Removing Member [127.0.0.1]:5704 - e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [ClusterService] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] 

Members {size:1, ver:13} [
	Member [127.0.0.1]:5701 - 58c37c17-68e3-471e-84e3-e0e6b12b3338 this
]

02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [TransactionManagerService] hz.optimistic_ptolemy.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5704, UUID: e0d8bdc7-fce1-4bf1-b839-42f75b2ab655
02:32:58,116  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Shutting down node engine...
02:32:58,118  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [NodeExtension] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
02:32:58,118  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
02:32:58,118  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5704 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5704 is SHUTDOWN
02:32:58,118  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
02:32:58,118  WARN |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Terminating forcefully...
02:32:58,118  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down connection manager...
02:32:58,118  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Shutting down node engine...
02:32:58,120  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [NodeExtension] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Destroying node NodeExtension.
02:32:58,120  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [Node] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Hazelcast Shutdown is completed in 2 ms.
02:32:58,120  INFO |when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge| - [LifecycleService] Thread-5065 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge(com.hazelcast.jet.core.SplitBrainTest): BuildInfo{version='5.0-SNAPSHOT', build='20210820', buildNumber=20210820, revision=9ce0da2, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'when_jobIsSubmittedToMinoritySide_then_jobIsCancelledDuringMerge(com.hazelcast.jet.core.SplitBrainTest):'
02:32:25, accumulated pauses: 91 ms, max pause: 3 ms, pauses over 1000 ms: 0
02:32:30, accumulated pauses: 55 ms, max pause: 4 ms, pauses over 1000 ms: 0
02:32:35, accumulated pauses: 46 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:32:40, accumulated pauses: 106 ms, max pause: 4 ms, pauses over 1000 ms: 0
02:32:45, accumulated pauses: 69 ms, max pause: 1 ms, pauses over 1000 ms: 0
02:32:50, accumulated pauses: 91 ms, max pause: 19 ms, pauses over 1000 ms: 0
02:32:55, accumulated pauses: 2529 ms, max pause: 2525 ms, pauses over 1000 ms: 1
```

### PR DESCRIPTION
**Pull request by frant-hartm**
The execution completion is done asynchronously so it might happen that
MasterJobContext#finalizeJob, which closes PMS and removes the job class
loader, is done before JobExecutionService#completeExecution, which then
tries to access already removed classloader.

This introduces a reference counter when removing job classloaders.

Also refactored the classloader handling to a separate service.

Fixes #19381
Fixes #19001 (the second occurrences related to this)

### CODE REVIEW

**Review by ufukyilmaz — APPROVED** [review]
It looks very good to me overall, just add a few minor comments

**Review by gurbuzali — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+    /**
+     * Prepare processor classloaders for given job for current thread
+     *
+     * @param jobId id of the job
+     */
+    public void prepareProcessorClassLoaders(long jobId) {
+        ProcessorClassLoaderTLHolder.putAll(getProcessorClassLoaders(jobId));
+    }
+
+    public ClassLoader getProcessorClassLoader(long jobId, String name) {
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java]: :+1:

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+                                jobClassLoader = new JetDelegatingClassLoader(parent);
+                            } else {
+                                jobClassLoader = new JetClassLoader(nodeEngine, parent, config.getName(), jobId,
+                                        jobRepository);
+                            }
+
+                            Map<String, ClassLoader> processorCls = createProcessorClassLoaders(
+                                    jobId, config, jobClassLoader
+                            );
+                            int refCount = nodeEngine.getClusterService().isMaster() ? 2 : 1;
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java]: Good idea. I have added javadocs for all public methods in this class plus some comments about the counts.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+
+    public Map<String, ClassLoader> getProcessorClassLoaders(long jobId) {
+        return classLoaders.get(jobId).processorCls();
+    }
+
+    public void clearProcessorClassLoaders() {
+        ProcessorClassLoaderTLHolder.remove();
+    }
+
+    public void removeClassloadersForJob(long jobId) {
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java]: Yeah why not. I like it.

[the remark this answers is not in the document]
Comment (ufukyilmaz) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java]: Thanks for addressing the comments

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java [hunk 4]
```diff
@@ -49,6 +49,14 @@
 
 public class JobClassLoaderService {
 
+    /*
+     * On master node there is a race between closing PMS and PS.
+     * We need to close the classloader only after both have been called.
+     * The reference counting is done in removeClassloadersForJob()
```
Comment (ufukyilmaz) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java:55]: minor: `removeClassloadersForJob()` reference is stale after renaming.
also, it would be better to have it linked as `{@link #tryRemoveClassloadersForJob(long)}`

**Comment by viliam-durina** [comment]
The implementation seems too fragile to me. We start with a fixed `refCount` and decrement it at specific places. However, is it guaranteed that we'll enter both these phases? What if there's some error in the master's code so that the member's code doesn't even run? We'll still start with refCount=2, but we'll decrement only once and leak the CL.

Also there can be some races when we think we're master and when we're not - the master status is mutable. For example, we receive `InitJobOperation` from master, but the master died just after that and we became master. We'll proceed handling the InitOp and we'll use refCount=2, because we're master now. However, there will be only one removal and the CL will leak again.

A more robust code would be to have two places where we initially get the CL and two where we release it. These should be strictly paired. The former will increment the refCount, the latter will decrement it. And the execution must guarantee that whenever we get the CL, we'll also release it, ideally using `try-finally`, if possible. There are ~5 places in total where we get the CL, but only 2 should be designated as initializations, others should assume that the CL is initialized, get it and not increment the CL.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java [hunk 5]
```diff
@@ -0,0 +1,311 @@
...
+                    + " requested, but it does not exists");
+        }
+    }
+
+    /**
+     * Try to remove and close/shutdown job classloader and any processor classloaders for given job
+     *
+     * If there are some
+     */
+    public void tryRemoveClassloadersForJob(long jobId, JobPhase phase) {
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java:190]: I would reconsider the logging levels in this method. 
- On line 191 and 200 and 220 it should be FINEST - it's used only to evaluate issues in the implementation. 
- On line 194 it should be a WARN, i guess this is not possible unless there's some problem. 
- On line 207 it should be WARN too - it's not normal if the `close()` fails. Also, on line 206 we should catch `Throwable`, we're calling user code I think.


Also, all logs on FINE or FINEST levels should use `LoggingUtil`.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java [hunk 6]
```diff
@@ -140,16 +141,16 @@ private ExecutionPlan deserializePlan(Data planBlob) {
...
         } else {
             JetServiceBackend service = getJetServiceBackend();
-            JobExecutionService jobExecutionService = service.getJobExecutionService();
+            JobConfig jobConfig = service.getJobConfig(jobId());
+            JobClassLoaderService jobClassloaderService = service.getJobClassLoaderService();
 
             try {
-                ClassLoader cl = service.getClassLoader(jobId());
-                JobConfig jobConfig = service.getJobConfig(this.jobId());
+                ClassLoader cl = jobClassloaderService.getOrCreateClassLoader(jobConfig, jobId(), EXECUTION);
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/operation/InitExecutionOperation.java:148]: Not a big difference, but this line should come before the `try` statement. Then it better shows what the code in `finally` cleans up.

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 7]
```diff
@@ -87,10 +100,61 @@
...
+        Map<Long, String> leakedClassloaders = new HashMap<>();
+        Collection<HazelcastInstance> instances = instanceFactory.getAllHazelcastInstances();
+        for (HazelcastInstance instance : instances) {
+            if (instance.getConfig().getJetConfig().isEnabled()) {
+                // Some tests leave jobs running, which keeps job classloader, shut down all running/starting jobs
+                JetService jet = instance.getJet();
+                List<Job> jobs = jet.getJobs();
+                for (Job job : jobs) {
+                    if (job.getStatus() == RUNNING || job.getStatus() == STARTING) {
+                        job.cancel();
```
Comment (viliam-durina) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:132]: You can use `ditchJob()` defined in this class.

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 8]
```diff
@@ -87,10 +100,61 @@
...
+                        assertJobStatusEventually(job, FAILED); // Failed = cancelled
+                    }
+                }
+
+                JobClassLoaderService jobClassLoaderService = ((HazelcastInstanceImpl) instance).node
+                        .getNodeEngine()
+                        .<JetServiceBackend>getService(SERVICE_NAME)
+                        .getJobClassLoaderService();
+
+                ConcurrentHashMap<Long, ?> classLoaders = readFieldOrNull(jobClassLoaderService, "classLoaders");
```
Comment (viliam-durina) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:142]: Why don't we expose the field publicly? You're accessing it anyway and at least it's visible in code navigation.

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 9]
```diff
@@ -87,10 +100,61 @@
...
+                // The classloader cleanup is done asynchronously in some cases, wait up to 10s
+                for (int i = 0; i < 100; i++) {
+                    if (classLoaders.isEmpty()) {
+                        break;
+                    }
```
Comment (viliam-durina) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:147]:
```suggestion
                for (int i = 0; i < 100 && !classLoaders.isEmpty(); i++) {
```

File: hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java [hunk 10]
```diff
@@ -87,10 +100,61 @@
...
+                    sleepMillis(100);
+                }
+                if (!classLoaders.isEmpty()) {
```
Comment (viliam-durina) [inline hazelcast/src/test/java/com/hazelcast/jet/core/JetTestSupport.java:150]: This `if` is unnecessary - the loop inside will do zero iterations.

File: hazelcast/src/test/java/com/hazelcast/jet/core/Processors_slidingWindowingIntegrationTest.java [hunk 11]
```diff
@@ -185,14 +185,17 @@ public boolean complete() {
...
+//            if (!complete) {
+//                return false;
+//                try {
+//                    Thread.sleep(Long.MAX_VALUE);
+//                } catch (InterruptedException e) {
+//                     proceed to returning true
+//                }
+//            } else {
+//                return true;
+//            }
```
Comment (viliam-durina) [inline hazelcast/src/test/java/com/hazelcast/jet/core/Processors_slidingWindowingIntegrationTest.java:198]: Did we remove it because it blocked the job cancellation? If so, we can remove the commented-out code.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java [hunk 12]
```diff
@@ -0,0 +1,323 @@
...
+                phases.remove(phase);
+                return phases.size();
+            }
+        }
+
+        @Override
+        public String toString() {
+            synchronized (this) {
+                return "JobClassLoaders{" +
+                        "phases=" + phases +
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java:318]: I'd rather remove `phases` from the text and avoided synchronization.

**Review by viliam-durina — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java (hunk 12 above)
Comment (frant-hartm) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/JobClassLoaderService.java:318]: When the check in the JetTestSupport detects a leaked classloader it is really useful to know which phase wasn't cleaned properly.
