### PR TITLE
Retry in KinesisSinkP#saveToSnapshot [HZ-2545]

### LINKED ISSUE #23692: com.hazelcast.jet.kinesis.KinesisIntegrationTest failures on updated docker image of localstack
For `localstack/localstack:0.13` which have arm64 support we have 3 test  failures on standard pr-builder and  on arm64 (with different number of actual messages in the assertion)
<details><summary>KinesisIntegrationTest.dynamicStream_2Shards_mergeDuringData:278</summary>

```
[ERROR]   ->dynamicStream_mergesDuringData:311->assertMessages:651->AbstractKinesisTest.assertMessages:162->HazelcastTestSupport.assertTrueEventually:1381->HazelcastTestSupport.assertTrueEventually:1277->AbstractKinesisTest.lambda$assertMessages$3:179 Messages for key 230 differ!
	expected: 100
	  actual: 2 expected:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980, 230: msg 000006230, 230: msg 000006480, 230: msg 000006730, 230: msg 000006980, 230: msg 000007230, 230: msg 000007480, 230: msg 000007730, 230: msg 000007980, 230: msg 000008230, 230: msg 000008480, 230: msg 000008730, 230: msg 000008980, 230: msg 000009230, 230: msg 000009480, 230: msg 000009730, 230: msg 000009980, 230: msg 000010230, 230: msg 000010480, 230: msg 000010730, 230: msg 000010980, 230: msg 000011230, 230: msg 000011480, 230: msg 000011730, 230: msg 000011980, 230: msg 000012230, 230: msg 000012480, 230: msg 000012730, 230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980, 230: msg 000016230, 230: msg 000016480, 230: msg 000016730, 230: msg 000016980, 230: msg 000017230, 230: msg 000017480, 230: msg 000017730, 230: msg 000017980, 230: msg 000018230, 230: msg 000018480, 230: msg 000018730, 230: msg 000018980, 230: msg 000019230, 230: msg 000019480, 230: msg 000019730, 230: msg 000019980, 230: msg 000020230, 230: msg 000020480, 230: msg 000020730, 230: msg 000020980, 230: msg 000021230, 230: msg 000021480, 230: msg 000021730, 230: msg 000021980, 230: msg 000022230, 230: msg 000022480, 230: msg 000022730, 230: msg 000022980, 230: msg 000023230, 230: msg 000023480, 230: msg 000023730, 230: msg 000023980, 230: msg 000024230, 230: msg 000024480, 230: msg 000024730, 230: msg 000024980]> but was:<[230: msg 000000230, 230: msg 000000480]>
```
</details>
<details><summary>KinesisIntegrationTest.restart_dynamicStream_graceful:400</summary>

```
[ERROR]   KinesisIntegrationTest.restart_dynamicStream_graceful:400->restart_dynamicStream:438->assertMessages:651->AbstractKinesisTest.assertMessages:162->HazelcastTestSupport.assertTrueEventually:1381->HazelcastTestSupport.assertTrueEventually:1277->AbstractKinesisTest.lambda$assertMessages$3:179 Messages for key 230 differ!
	expected: 100
	  actual: 2 expected:<[230: msg 000000230, 230: msg 000000480, 230: msg 000000730, 230: msg 000000980, 230: msg 000001230, 230: msg 000001480, 230: msg 000001730, 230: msg 000001980, 230: msg 000002230, 230: msg 000002480, 230: msg 000002730, 230: msg 000002980, 230: msg 000003230, 230: msg 000003480, 230: msg 000003730, 230: msg 000003980, 230: msg 000004230, 230: msg 000004480, 230: msg 000004730, 230: msg 000004980, 230: msg 000005230, 230: msg 000005480, 230: msg 000005730, 230: msg 000005980, 230: msg 000006230, 230: msg 000006480, 230: msg 000006730, 230: msg 000006980, 230: msg 000007230, 230: msg 000007480, 230: msg 000007730, 230: msg 000007980, 230: msg 000008230, 230: msg 000008480, 230: msg 000008730, 230: msg 000008980, 230: msg 000009230, 230: msg 000009480, 230: msg 000009730, 230: msg 000009980, 230: msg 000010230, 230: msg 000010480, 230: msg 000010730, 230: msg 000010980, 230: msg 000011230, 230: msg 000011480, 230: msg 000011730, 230: msg 000011980, 230: msg 000012230, 230: msg 000012480, 230: msg 000012730, 230: msg 000012980, 230: msg 000013230, 230: msg 000013480, 230: msg 000013730, 230: msg 000013980, 230: msg 000014230, 230: msg 000014480, 230: msg 000014730, 230: msg 000014980, 230: msg 000015230, 230: msg 000015480, 230: msg 000015730, 230: msg 000015980, 230: msg 000016230, 230: msg 000016480, 230: msg 000016730, 230: msg 000016980, 230: msg 000017230, 230: msg 000017480, 230: msg 000017730, 230: msg 000017980, 230: msg 000018230, 230: msg 000018480, 230: msg 000018730, 230: msg 000018980, 230: msg 000019230, 230: msg 000019480, 230: msg 000019730, 230: msg 000019980, 230: msg 000020230, 230: msg 000020480, 230: msg 000020730, 230: msg 000020980, 230: msg 000021230, 230: msg 000021480, 230: msg 000021730, 230: msg 000021980, 230: msg 000022230, 230: msg 000022480, 230: msg 000022730, 230: msg 000022980, 230: msg 000023230, 230: msg 000023480, 230: msg 000023730, 230: msg 000023980, 230: msg 000024230, 230: msg 000024480, 230: msg 000024730, 230: msg 000024980]> but was:<[230: msg 000000230, 230: msg 000000480]>
```
</details>

<details><summary>KinesisIntegrationTest.dynamicStream_1Shard_splitsDuringData:334</summary>

```
[ERROR]   KinesisIntegrationTest.dynamicStream_1Shard_splitsDuringData:334->dynamicStream_splitsDuringData:359->AbstractKinesisTest.splitShard:215 ? IllegalArgument Partition end can't be smaller or equal to partition start
```
</details>

Logs can be found here:
https://s3.console.aws.amazon.com/s3/object/j-artifacts?region=eu-north-1&prefix=Hazelcast-pr-builder/16009/Hazelcast-pr-builder-16009.zip

To reproduce, adjust localstack initialization:
```
localStack = new LocalStackContainer(parse("localstack/localstack")
                .withTag("0.13"))
```

### LINKED ISSUE #24774: Kinesis sink can lose data when retry happens during terminal snapshot [HZ-2545]
When Kinesis sink writes the data to Kinesis stream and if writing of any item fails for some reason (for example due to the limit on Kinesis side) the sink retries. However this retry doesn't happen for terminal snapshot. In that case the item is lost.

### PR DESCRIPTION
**Pull request by frant-hartm**
When `saveToSnapshot()` is called while `sendResult` is non-null then the result might contain failed records that are retained in the buffer.

However, the buffer is not checked if it is empty, which leads to losing the items in the buffer.

The behavior of `saveToSnapshot` should be the same as `complete()` - it needs to flush all records and retry on any failures. The change simply delegates to `complete()`.

Also updated Localstack to 2.1.0, which supports arm. The previous issues with never image seem to be fixed.

Fixes #24774
Fixes #23692

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

Backports needed for 5.0-5.3
Will send them after the review.

### CODE REVIEW

**Review by Patras3 — APPROVED** [review]
Approved, just one small remark about moving docker assumption in the same way like in other file.

File: extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,173 @@
...
+    private static KinesisTestHelper HELPER;
+    private static boolean useRealKinesis;
+
+    public KinesisLimitExceededIntegrationTest() {
+        super(AWS_CONFIG, KINESIS, HELPER);
+    }
+
+    @BeforeClass
+    public static void beforeClass() {
+        assumeDockerEnabled();
```
[the remark this answers is not in the document]
Comment (frant-hartm) [reply extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java]: Yes of course, thanks.

77ebfaef35e

File: extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/sink/KinesisSinkP.java [hunk 2]
```diff
@@ -170,10 +170,7 @@ public boolean complete() {
 
     @Override
     public boolean saveToSnapshot() {
-        if (sendResult != null) {
-            checkIfSendingFinished();
-        }
-        return sendResult == null;
+        return complete();
```
Comment (orcunc) [inline extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/sink/KinesisSinkP.java:173]: In the complete() method 
```
 if (sendResult != null) {
   ...
 }
 if (sendResult == null) {
  ...
}
````
can be changed to if/else. Because if (sendResult == null) will always be true

File: extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java [hunk 3]
```diff
@@ -0,0 +1,173 @@
...
+
+@Category(SlowTest.class)
+public class KinesisLimitExceededIntegrationTest extends AbstractKinesisTest {
+
+    public static LocalStackContainer localStack;
+
+    private static AwsConfig AWS_CONFIG;
+    private static AmazonKinesisAsync KINESIS;
+    private static KinesisTestHelper HELPER;
+    private static boolean useRealKinesis;
```
Comment (orcunc) [inline extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java:57]: useRealKinesis can be a local variable

File: extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/sink/KinesisSinkP.java (hunk 2 above)
Comment (frant-hartm) [reply extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/sink/KinesisSinkP.java:173]: No, because the `checkIfSendingFinished` can nullify the `sendResult`

File: extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java (hunk 3 above)
Comment (frant-hartm) [reply extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java:57]: 2fe058695b3

File: extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java [hunk 4]
```diff
@@ -0,0 +1,173 @@
...
+        Job writeJob = hz().getJet().newJob(write,
+                new JobConfig().setProcessingGuarantee(ProcessingGuarantee.AT_LEAST_ONCE));
+
+        Pipeline p = Pipeline.create();
+        p.readFrom(kinesisSource().build())
+         .withNativeTimestamps(0)
+         .map(Entry::getKey)
+         .peek()
+         .writeTo(Sinks.list("result"));
+        Job readJob = hz().getJet().newJob(p,
```
Comment (orcunc) [inline extensions/kinesis/src/test/java/com/hazelcast/jet/kinesis/KinesisLimitExceededIntegrationTest.java:138]: Does it make sense to assert that the read job is also running ?

**Review by orcunc — APPROVED** [review]

File: extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/sink/KinesisSinkP.java (hunk 2 above)
Comment (orcunc) [reply extensions/kinesis/src/main/java/com/hazelcast/jet/kinesis/impl/sink/KinesisSinkP.java:173]: Then maybe add a comment ? . Because it is difficult to see it

**Review by olukas — APPROVED** [review]

**Comment by frant-hartm** [comment]
Backport done to 5.3 and 5.2. 

5.1 and earlier don't backport cleanly, would take more time.
