### PR TITLE
testMapLockAndUnlockAndTryLock improved

### LINKED ISSUE #9156: BasicMapTest.testMapLockAndUnlockAndTryLock
```
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.hazelcast.map.BasicMapTest.testMapLockAndUnlockAndTryLock(BasicMapTest.java:595)
```

https://hazelcast-l337.ci.cloudbees.com/view/Hazelcast/job/Hazelcast-3.x-ZuluJDK7/com.hazelcast$hazelcast/367/testReport/junit/com.hazelcast.map/BasicMapTest/testMapLockAndUnlockAndTryLock/

### PR DESCRIPTION
**Pull request by jerrinot**
Added a latch & increased timeout to decrease reliance on timing
Fixes #9156

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java [hunk 1]
```diff
@@ -565,41 +568,45 @@ public void testMapLockAndUnlockAndTryLock() throws Exception {
...
+
         Thread thread = new Thread(new Runnable() {
             public void run() {
                 try {
                     check1.set(map.tryLock("key0"));
-                    check2.set(map.tryLock("key0", 3000, TimeUnit.MILLISECONDS));
                     latch0.countDown();
 
-                    map.put("key1", "value1");
+                    check2.set(map.tryLock("key0", timeout, SECONDS));
```
Comment (jerrinot) [inline hazelcast/src/test/java/com/hazelcast/map/BasicMapTest.java]: the diff view is quite confusing here. the change is actually quite simple. 
I added a new latch -  `latch0`. this shifted all existing latches. so the old `latch0` become `latch1`, the old `latch1` become `latch2`, etc..
