### PR TITLE
Fix split-brain test failures of Replicated Map

### LINKED ISSUE #6489: [TEST-FAILURE] ReplicatedMapMergePolicyTest.testLatestUpdateMapMergePolicy FAILURES
**testLatestUpdateMapMergePolicy**
**testHigherHitsMapMergePolicy**
```
org.junit.ComparisonFailure: expected:<[LatestUpdatedV]alue> but was:<[v]alue>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.replicatedmap.ReplicatedMapMergePolicyTest.testLatestUpdateMapMergePolicy(ReplicatedMapMergePolicyTest.java:93)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-nightly/com.hazelcast$hazelcast/744/

### PR DESCRIPTION
**Pull request by eminn**
Carry record metadata (hits, lastAccessTime, creationTime, lastUpdateTime) with the record on migration. Fixes #6489

### CODE REVIEW

**Comment by metanet** [comment]
:+1:

File: hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ReplicationOperation.java [hunk 1]
```diff
@@ -57,7 +57,9 @@ public ReplicationOperation(SerializationService serializationService, Partition
 
     @Override
     public void run() throws Exception {
-        logger.finest("Moving partition -> " + getPartitionId() + " to the new owner -> " + getNodeEngine().getThisAddress());
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ReplicationOperation.java]: Can you add a if(logger.isDebugEnabled()).. around it to prevent String litter?

File: hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/RecordMigrationInfo.java [hunk 2]
```diff
@@ -27,6 +27,14 @@
     private Data key;
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/RecordMigrationInfo.java]: I don't know how often the RecordMigrationInfo is send; but it is often I would consider implements IdentifiedDataSerializable.

File: hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ReplicationOperation.java (hunk 1 above)
Comment (eminn) [inline hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/operation/ReplicationOperation.java]: done.

**Comment by pveentjer** [comment]
verify

**Comment by sancar** [comment]
:+1:

File: hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/RecordMigrationInfo.java (hunk 2 above)
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/replicatedmap/impl/record/RecordMigrationInfo.java]: After short discussion with Emin I came to the understanding it isn't needed. The class name is not being send over the wire.

**Comment by pveentjer** [comment]
:+1:
