### PR TITLE
Decrement owned entry count with proper condition [HZ-1182]

### LINKED ISSUE #21394: NearCacheStats reports negative values after concurrent near cache remove [HZ-1182]
Run code to see the issue:
```
package com.hazelcast.map.impl.nearcache;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.map.impl.nearcache.NearCachedClientMapProxy;
import com.hazelcast.config.EvictionConfig;
import com.hazelcast.config.EvictionPolicy;
import com.hazelcast.config.MaxSizePolicy;
import com.hazelcast.config.NearCacheConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.internal.util.RandomPicker;
import com.hazelcast.map.IMap;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

public class NearCacheEviction {

    public static void main(String[] args) throws InterruptedException {
        HazelcastInstance node = Hazelcast.newHazelcastInstance();
        IMap<Object, Object> nodeMap = node.getMap("test");
        for (int i = 0; i < 100_000; i++) {
            nodeMap.set(i, i);
        }

        ClientConfig clientConfig = new ClientConfig();
        NearCacheConfig nearCacheConfig = new NearCacheConfig("test");
        EvictionConfig evictionConfig = nearCacheConfig.getEvictionConfig();
        evictionConfig.setEvictionPolicy(EvictionPolicy.LFU);
        evictionConfig.setMaxSizePolicy(MaxSizePolicy.ENTRY_COUNT);
        evictionConfig.setSize(1000);

        AtomicBoolean running = new AtomicBoolean(true);
        clientConfig.addNearCacheConfig(nearCacheConfig);
        HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);
        IMap<Object, Object> map = client.getMap("test");

        ExecutorService pool = Executors.newFixedThreadPool(8);
        Runnable get = new Runnable() {
            @Override
            public void run() {
                while (running.get()) {
                    map.get(RandomPicker.getInt(0, 100_000));
                }
            }
        };
        for (int i = 0; i < 4; i++) {
            pool.execute(get);
        }

        Runnable remove = new Runnable() {
            @Override
            public void run() {
                while (running.get()) {
                    map.remove(RandomPicker.getInt(0, 100_000));
                }
            }
        };

        for (int i = 0; i < 4; i++) {
            pool.execute(remove);
        }

        TimeUnit.SECONDS.sleep(10);
        running.set(false);

        pool.shutdown();
        pool.awaitTermination(10, TimeUnit.SECONDS);


        System.err.println(map.getLocalMapStats().getNearCacheStats());
        int real = ((NearCachedClientMapProxy) map).getNearCache().size();
        System.err.println("real size=" + real);
    }
}
```

### PR DESCRIPTION
**Pull request by vbekiaris**
A record existing in the NearCacheRecordMap does not necessarily represent an actual value present in the near cache. It can be a reservation placeholder, placed by a concurrent get operation. If that is the case, then the owned entry count should not be decremented because the entry does not yet exist.

Fixes #21394

EE PR: https://github.com/hazelcast/hazelcast-enterprise/pull/5913

Checklist:
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/HeapNearCacheRecordMap.java [hunk 1]
```diff
@@ -96,7 +96,9 @@ public <C extends EvictionCandidate<K, V>> boolean tryEvict(C evictionCandidate,
         if (evictionCandidate == null) {
             return false;
         }
-        if (remove(evictionCandidate.getAccessor()) == null) {
+        V record = remove(evictionCandidate.getAccessor());
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/HeapNearCacheRecordMap.java:99]: Can we put this check inside `onEvict` and `onExpire` methods? Because normal stats updates are happening inside them and this condition check can also go there to have them in one place.

Additionally we have  a `AbstractNearCacheRecordStore#canUpdateStats` method which is doing desired condition check, it can also be used.

**Review by ahmetmircik — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java [hunk 2]
```diff
@@ -205,11 +205,17 @@ protected void onRemoveError(K key, R record, boolean removed, Throwable error)
 
     @SuppressWarnings("unused")
     protected void onExpire(K key, R record) {
+        if (!canUpdateStats(record)) {
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java:208]: Right now, we have the same check here and in `HeapNearCacheRecordMap`. Do we need to have both of them?

File: hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java [hunk 3]
```diff
@@ -205,11 +205,17 @@ protected void onRemoveError(K key, R record, boolean removed, Throwable error)
...
+            return;
+        }
         nearCacheStats.incrementExpirations();
     }
 
     @Override
     public void onEvict(KS key, R record, boolean wasExpired) {
+        if (!canUpdateStats(record)) {
```
Comment (mdumandag) [inline hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java:216]: If we want to put these checks into both of the places, maybe we can add a check to overridden `onEvict` method in `HDNearCacheRecordStoreImpl` as well.

Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/internal/nearcache/impl/store/AbstractNearCacheRecordStore.java:216]: EE side PR https://github.com/hazelcast/hazelcast-enterprise/pull/5913

**Comment by ahmetmircik** [comment]
@vbekiaris any backport are you planning?

**Comment by vbekiaris** [comment]
@ahmetmircik yes I 'll backport the fix to supported versions
