### PR TITLE
Fixes race in AbstractInvocationFuture#exceptionally

### LINKED ISSUE #17566: DelegatingCompletableFuture_WrappingInvocationFutureTest
```
java.lang.AssertionError: expected:<java.lang.Object@7a5b4ab2> but was:<com.hazelcast.spi.impl.AbstractInvocationFuture$WhenCompleteNode@3f59cb9d>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.hazelcast.spi.impl.CompletableFutureAbstractTest.exceptionally_whenAsync(CompletableFutureAbstractTest.java:812)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/2389/testReport/junit/com.hazelcast.spi.impl/DelegatingCompletableFuture_WrappingInvocationFutureTest/exceptionally_whenAsync/

### PR DESCRIPTION
**Pull request by vbekiaris**
Registration of any dependent action on a
non-complete `AbstractInvocationFuture` will result in
field `state` being an instance of an inner class like
`AbstractInvocationFuture$WhenCompleteNode`. When calling
exceptionally, it is possible that this non-complete
state is observed and then the `AbstractInvocationFuture`
will erroneously be considered as completed because
the condition checks a previously observed value of
`state` along with its current `isDone()` status.

Fixes #17566

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java [hunk 1]
```diff
@@ -864,33 +879,19 @@ protected void unblockWhenComplete(@Nonnull final BiConsumer<? super V, ? super
         }
     }
 
-    @Override
-    public InternalCompletableFuture<V> exceptionally(@Nonnull Function<Throwable, ? extends V> fn) {
-        requireNonNull(fn);
+    private void unblockExceptionally(@Nonnull Function<Throwable, ? extends V> fn,
+                                      InternalCompletableFuture<V> future) {
         Object result = resolve(state);
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java:884]: It is wrong to resolve the `state` at this point and then use its value in a further condition. Instead, we should first check if `AbstractInvocationFuture#isDone`, similarly to all other `CompletionStage` API implementations.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java [hunk 2]
```diff
@@ -864,33 +879,19 @@ protected void unblockWhenComplete(@Nonnull final BiConsumer<? super V, ? super
...
-        final InternalCompletableFuture<V> future = newCompletableFuture();
-        for (; ; ) {
-            if (result != UNRESOLVED && isDone()) {
```
Comment (vbekiaris) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractInvocationFuture.java:873]: Here `result` may be not `UNRESOLVED` but another valid value of a non-complete future like `Thread`, `AbstractInvocationFuture$WhenCompleteNode` etc. The problem is that `isDone()` operates on field `state` but `result` reflects a potentially stale value -> it is possible that `result != UNRESOLVED` and `isDone()` are both true and yet `result` is not the actual completion value.

**Review by mmedenjak — APPROVED** [review]

**Review by mdogan — APPROVED** [review]
