### PR TITLE
17954 allow override of default serializers

### LINKED ISSUE #17954: Allow overriding default serializers with a property
We have added default serializers to the 4.2 series here:
https://github.com/hazelcast/hazelcast/pull/17934

There is a problem with backward compatibility. If a user had CustomSerializer for optional in 4.1, in 4.2 there is no way to use their serializers, and Hazelcast will throw `java.lang.IllegalArgumentException: [class java.util.Optional] serializer cannot be overridden`

Users can basically remove the Optional serializer and continue but this does not play well with Rolling Upgrade. For Rolling Upgrade to work, the user should be able to continue to use the same serializer that is used in the old version.

The proposal is to add a way to override default serializers to cover this scenario. 

1. It should be enabled with a property explicitly. Something like `hazelcast.serialization.allowOverrideDefaultSerializers` in ClusterProperty with default value `false`. 
2. When the instance does not start and throws the `IllegalArgumentException`, we should mention the new property and the implications on a log. 
3. This new property should be documented in release notes and reference manual.

### PR DESCRIPTION
**Pull request by sgflt**
Fixes #17954 

Implemented loading of configuration from xml/yaml.

Config can be overridden by system property.

### CODE REVIEW

**Comment by sancar** [comment]
@sgflt Is your work finished? Can you please move your pr from draft when you think it is ready? 
Not sure if I should start reviewing or not. 
Note that we will be preparing a design document for this internally to track this change and document it for future reference. 
It could lead the review process to take a little bit longer than usual.

**Comment by sgflt** [comment]
Not yet. I have to fix a small bug and improve tests. But I think I will be done today.

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by mmedenjak** [comment]
@sgflt thank you for providing the config option as XML/YAML config, I consider it the right approach, even though the `ClusterProperty` is much easier to implement. Here is a checklist for adding new configuration - https://github.com/hazelcast/hazelcast/wiki/Checklist-for-Hazelcast-config-changes. Not all items might apply in your case, but feel free to check it out anyway to see if you've missed something.

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java:432:67: '+' should be on a new line. [OperatorWrap]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/DefaultSerializationServiceBuilder.java:55:1: Total number of methods is 32 (max allowed is 30). [MethodCount]
--------------------------
</pre>
</details>

**Comment by mmedenjak** [comment]
@sgflt can you run checkstyle locally and fix the related issues? `mvn clean install -DskipTests -Pcheckstyle,spotbugs`

**Comment by sgflt** [comment]
- [ ] hazelcast-config-4.y.xsd
- [ ] MemberDomConfigProcessor, YamlMemberDomConfigProcessor (only if YAML needs to derive)
- [ ] XML & YAML tests: AbstractConfigBuilderTest -> [XML&Yaml]ConfigBuilderTest
- [ ] ConfigXmlGenerator, ConfigXmlGeneratorTest
- [ ] ConfigCompatibilityChecker (used by ConfigDefaultsTest, XmlOnlyConfigBuilderTest#testConfig2Xml2FullConfig and XmlOnlyConfigBuilderTest#testConfig2Xml2FullConfig_withAdvancedNetworkConfig and XmlOnlyConfigBuilderTest#testConfig2Xml2DefaultConfig)
- [ ] hazelcast-fullconfig-advanced-network-config.[xml&yaml]
- [ ] hazelcast-fullconfig.[xml&yaml]
- [ ] equality of xml and yaml files: XmlYamlConfigBuilderEqualsTest
- [ ] ClientConfig
- [ ] hazelcast-client-config-4.y.xsd
- [ ] hazelcast-client-full.[xml&yaml]
- [ ] hazelcast-client-full-example.[xml&yaml]
- [ ] ClientDomConfigProcessor, YamlClientDomConfigProcessor (only if YAML needs to derive)
- [ ] AbstractClientConfigBuilderTest
- [ ] ClientConfigXmlGenerator and its test ClientConfigXmlGeneratorTest
- [ ] hazelcast-spring-4.y.xsd
- [ ] SpringXmlConfigBuilder, fullConfig-applicationContext-hazelcast.xml and TestFullApplicationContext

**Comment by mmedenjak** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/DefaultSerializationServiceBuilder.java:55:1: Total number of methods is 32 (max allowed is 30). [MethodCount]
--------------------------
</pre>
</details>

**Comment by sgflt** [comment]
@mmedenjak now it should be complete

**Comment by mmedenjak** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java [hunk 1]
```diff
@@ -1546,6 +1546,18 @@ private int getWhenNoSSLDetected() {
...
+    /**
+     * Property allows override of default Java serializers for backward compatibility.
+     *
+     * For example application using older version of Hazelcast provides custom java.util.Optional serializer.
+     * Since version 4.2 of Hazelcast registration of any serializer for an embedded type is not possible
+     * until this flag is set to true.
+     *
+     * @since 4.2
+     */
+    public static final HazelcastProperty SERIALIZATION_ALLOW_OVERRIDE_DEFAULT_SERIALIZERS
```
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java:1558]: Hi @sgflt,
since we have decided to give full config support for this the property support is needed. Can we remove this back? Sorry for the inconvenience.

File: hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java [hunk 2]
```diff
@@ -454,6 +455,20 @@ public SerializationConfig setAllowUnsafe(boolean allowUnsafe) {
...
+    /**
+     * @return true if embedded serializers may be overridden by custom serializers
+     *
+     * @since 4.2
+     */
+    public boolean isAllowOverrideDefaultSerializers() {
+        return allowOverrideDefaultSerializers;
+    }
+
+    public SerializationConfig setAllowOverrideDefaultSerializers(final boolean allowOverrideDefaultSerializers) {
```
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java:467]: Can we add something like following into Javadoc of the set method?
```
This configuration should be used cautiously. Default serializers are used heavily by the hazelcast internally. 
If any of the instance in the same cluster overrides a default serializer, all the members and clients in the same cluster must override it with the same serializer. 
This configuration is introduced specifically to support the following case:
1. There was a custom configuration by the user for a type 
2. Hazelcast decided to add a default serializer for the same type in a future release.
To be able to support Rolling Upgrade from an old version to the new version, one needs to make sure of the backward compatibility of the serialization. As a solution, the user will set this property on the new version so that new instances will be able to override new default serializers with their existing custom serializers. 
```

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java [hunk 3]
```diff
@@ -425,8 +427,11 @@ protected final boolean safeRegister(final Class type, final Serializer serializ
     }
 
     protected final boolean safeRegister(final Class type, final SerializerAdapter serializer) {
-        if (constantTypesMap.containsKey(type)) {
-            throw new IllegalArgumentException("[" + type + "] serializer cannot be overridden");
+        if (constantTypesMap.containsKey(type) && !allowOverrideDefaultSerializers) {
+            throw new IllegalArgumentException(
+                "[" + type + "] serializer cannot be overridden."
+                + " See hazelcast.serialization.allowOverrideDefaultSerializers"
```
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java:433]: Since we will be removing the property, please do not forget to update this part as `SerializationConfig. setAllowOverrideDefaultSerializers`

File: hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java (hunk 1 above)
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java:1558]: Hi @sancar, I followed widely used way of configuration:
1) system property - useful for debug or fine tuning, overrides config file
2) standard config file as persistent configuration

So the final decision is to drop the system property support? It simplifies some code paths, but removes duality of configuration, which may be useful in some use cases.

File: hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java [hunk 4]
```diff
@@ -51,6 +51,7 @@
     private boolean allowUnsafe;
     private final Set<ClassDefinition> classDefinitions;
     private JavaSerializationFilterConfig javaSerializationFilterConfig;
+    private boolean allowOverrideDefaultSerializers;
```
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java:54]: Can we put field to equals and hashcode of SerializationConfig?

**Comment by sancar** [comment]
The changes seem to cover the client side as well but can we add a test to
 `TestClientApplicationContext` to make sure it is working for the client?
Note that in case of failure, you may need to update the following classes (from https://github.com/hazelcast/hazelcast/wiki/Checklist-for-Hazelcast-config-changes):
 ```
Hazelcast Spring client config
- TestClientApplicationContext
- HazelcastClientBeanDefinitionParser
- node-client-applicationContext-hazelcast.xml
- hazelcast-spring-4.y.xsd
```

File: hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java (hunk 1 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java:1558]: We are not putting configuration to both properties and config unless we have to. 
And I have just learned that we applied a feature that allows you to override Config via properties anyway. 
https://docs.hazelcast.org/docs/latest/manual/html-single/#overriding-configuration
So when you add it to Config, the property support is added automagically :)

**Comment by sancar** [comment]
I have completed the review. Keep in mind that we still need a second reviewer also the internal design is not completely approved yet. And most of the people are at Christmas and New Year vacation. So this will take a little more to be merged. 
@sgflt Happy Christmas and New Year.

File: hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java (hunk 1 above)
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java:1558]: Oh nice :) I am going to investigate this feature.

File: hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java (hunk 2 above)
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java:467]: Javadoc added

File: hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java (hunk 1 above)
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/spi/properties/ClusterProperty.java:1558]: Property removed

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java (hunk 3 above)
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java]: Message updated

File: hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java (hunk 4 above)
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/config/SerializationConfig.java:54]: fixed

**Comment by sgflt** [comment]
> The changes seem to cover the client side as well but can we add a test to
> `TestClientApplicationContext` to make sure it is working for the client?
> Note that in case of failure, you may need to update the following classes (from https://github.com/hazelcast/hazelcast/wiki/Checklist-for-Hazelcast-config-changes):
> 
> ```
> Hazelcast Spring client config
> - TestClientApplicationContext
> - HazelcastClientBeanDefinitionParser
> - node-client-applicationContext-hazelcast.xml
> - hazelcast-spring-4.y.xsd
> ```

Good catch. I missed this path.

**Comment by sgflt** [comment]
Shouldn't we include also OptionalLong, OptionalInt... into default serializers? (In different PR)

**Comment by sgflt** [comment]
Also I wish Happy New Year :)

**Comment by Holmistr** [comment]
Hey @sgflt , thanks a lot for your contribution! :tada: 

@sancar Have you finished your review?

I'll start looking for a second reviewer.

**Comment by mmedenjak** [comment]
run-lab-run

**Review by mdumandag — COMMENTED** [review]
@sgflt Overall it looks good to me. Left generally minor comments. I went over the config checklist and saw that the following items must be updated.

- ConfigCompatibilityChecker
- hazelcast-fullconfig-without-network.[xml&yaml]

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/SerializationServiceBuilder.java [hunk 5]
```diff
@@ -59,6 +59,8 @@
 
     SerializationServiceBuilder setAllowUnsafe(boolean allowUnsafe);
 
+    SerializationServiceBuilder setAllowOverrideDefaultSerializers(boolean allowOverrideDefaultSerializers);
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/SerializationServiceBuilder.java:62]: Yes, seems it is not needed. It is a leftover from the first commit I assume when we had property based configuration as well. 
@sgflt Can we clean this up and its implementation please?

**Comment by sancar** [comment]
@sgflt Our internal design review is complete. 
It seems everyone is ok with the design we have started with. 

As soon as you have addressed the latest comments from @mdumandag, we should be able to merge the pr. 

Thanks for your patience.

File: hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java [hunk 6]
```diff
@@ -90,6 +90,7 @@
     private volatile boolean active = true;
     private final byte version;
     private final ILogger logger = Logger.getLogger(InternalSerializationService.class);
+    private boolean allowOverrideDefaultSerializers;
```
[the remark this answers is not in the document]
Comment (sgflt) [reply hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java:93]: Final revelaed small bug in Second constructor :)

**Comment by sancar** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed.
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (default) on project hazelcast: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There is 1 error reported by Checkstyle 8.38 with /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/main/java/com/hazelcast/internal/serialization/impl/AbstractSerializationService.java:434:82: '+' should be on a new line. [OperatorWrap]
--------------------------
</pre>
</details>

**Comment by mdumandag** [comment]
Thanks for the changes @sgflt, I have resolved most of my review comments. Only 3 of them are left. Could you check them and the checkstyle error reported above https://github.com/hazelcast/hazelcast/pull/17958#issuecomment-763886164 when you have the time?

File: hazelcast/src/main/resources/hazelcast-full-example.yaml [hunk 7]
```diff
@@ -2023,6 +2023,8 @@ hazelcast:
   #     Set as true to enable shared object when default Java serialization is used. Its default value is false.
   # * "allow-unsafe":
   #     Set as true to allow the usage of unsafe. Its default value is false.
+  # * "allow-override-default-serializers":
+  #     Set as true to allow override of embedded serializers.
```
[the remark this answers is not in the document]
Comment (sgflt) [reply hazelcast/src/main/resources/hazelcast-full-example.yaml]: I have to Apologize, I have missed it.

**Comment by sgflt** [comment]
> @sgflt Overall it looks good to me. Left generally minor comments. I went over the config checklist and saw that the following items must be updated.
> 
> * ConfigCompatibilityChecker
> * hazelcast-fullconfig-without-network.[xml&yaml]

@mdumandag  Do that points count as two? I have already updated both in https://github.com/hazelcast/hazelcast/pull/17958/commits/d0ba83528247a514b34b7f6871a35840b490a95f and https://github.com/hazelcast/hazelcast/pull/17958/commits/097aedfe3d7d9dc6a4266a36e23d8379948facfa.

**Comment by mdumandag** [comment]
@sgflt I meant https://github.com/hazelcast/hazelcast/pull/17958#discussion_r560241816 and https://github.com/hazelcast/hazelcast/pull/17958#discussion_r560242438

File: hazelcast/src/main/resources/hazelcast-full-example.xml [hunk 8]
```diff
@@ -2045,6 +2045,8 @@
             Set as true to enable shared object when default Java serialization is used. Its default value is false.
         * <allow-unsafe>:
             Set as true to allow the usage of unsafe. Its default value is false.
+        * <allow-override-default-serializers>:
+            Set as true to allow override of embedded serializers.
```
[the remark this answers is not in the document]
Comment (sgflt) [reply hazelcast/src/main/resources/hazelcast-full-example.xml]: fixed

File: hazelcast/src/main/resources/hazelcast-config-4.2.xsd [hunk 9]
```diff
@@ -2959,6 +2959,14 @@
                     </xs:documentation>
                 </xs:annotation>
             </xs:element>
+            <xs:element name="allow-override-default-serializers" type="xs:boolean" minOccurs="0" maxOccurs="1" default="false">
+                <xs:annotation>
+                    <xs:documentation>
+                        True to allow override of embedded serializers.
```
[the remark this answers is not in the document]
Comment (sgflt) [reply hazelcast/src/main/resources/hazelcast-config-4.2.xsd]: fixed

**Comment by sgflt** [comment]
Now it should be complete. Mentioned comments were well hidden by GitHub's "load more" :)

**Review by mdumandag — APPROVED** [review]

**Comment by mdumandag** [comment]
Thanks a lot for the changes @sgflt, approved the PR. Let me run the tests

**Comment by mdumandag** [comment]
run-lab-run

**Review by sancar — APPROVED** [review]

**Comment by sancar** [comment]
Thanks for the contribution. @sgflt I have merged the pr 🚀
