### PR TITLE
Fixes #6020. 

### LINKED ISSUE #6020: [TEST-FAILURE] executor.CompletableFutureTest.postregisterCallback
```
java.lang.AssertionError: CountDownLatch failed to complete within 120 seconds , count left: 1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:718)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:711)
	at com.hazelcast.test.HazelcastTestSupport.assertOpenEventually(HazelcastTestSupport.java:703)
	at com.hazelcast.executor.CompletableFutureTest.postregisterCallback(CompletableFutureTest.java:104)
```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x/com.hazelcast$hazelcast/3630/testReport/junit/com.hazelcast.executor/CompletableFutureTest/postregisterCallback/

### PR DESCRIPTION
**Pull request by tombujok**
Fix for #6020 

* As suggested by Peter the AbstractCompletableFuture class has been extended so that it may be a base class for all CompletableFuture classes - in this way we omit duplication in the execution of callbacks, which was a root cause of #6020. Some classes executed the callbacks correctly - some, like the CompletableFutureTask did not - now it's unified.
* Currently, AbstractCompletableFuture class handles the cancellation and get(timeout). It enables us to remove the `extends FutureTask` in the ComputableFutureTask. As a result we create less litter and do not track the state of the task in two classes at once. Earlier it was done by the  ComputableFutureTask and the base FutureTask; what is more it was not fully in sync either.
* This change was supposed to be minimalistic so no other changes has been done in the logic of the AbstractCompletableFuture class - apart from the things mentioned above. It may be a topic for future improvements. 
* There's some more classes that encompass the logic of callbacks' execution in the codebase (listed below). They could be refactored now, so that they extend the AbstractCompletableFuture - in this way we would omit even more duplication.
   * InvocationFuture
   * ClientInvocationFuture
   * CompletedFuture

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java [hunk 1]
```diff
@@ -110,6 +167,32 @@ public V get() throws InterruptedException, ExecutionException {
...
+            if (Thread.interrupted()) {
+                throw new InterruptedException();
+            }
+
+            nanosToWait = deadlineNanoTime - System.nanoTime();
+            if (nanosToWait < 0) {
+                throw new TimeoutException();
+            }
+
+            synchronized (this) {
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: scope of this synchronized block is suspiciously small. the smells like a race-condition to me. usually you want to check your condition while owning the mutex.

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: Imagine 2 threads: 

- Thread1 - Waiter
- Thread2 - Producer

Waiter calls `get()`. Result is still not set so the Waiter will fall through up to line 190. But before Waiter enters the synchronized block the Producer thread will set the result. The Producer will call `notifyThreadsWaitingOnGet()`, but there is no thread waiting! (as the Waiter is right *before* the synchronized block)

Eventually Waiter reaches the synchronized block and calls `wait()`, but there is no one to call notify! (as the Producer is already gone). Did I miss something?

**Comment by mtopolnik** [comment]
:+1:

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java (hunk 1 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: Thanks @jerrinot  I fixed it!

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: resolved

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java [hunk 2]
```diff
@@ -110,25 +165,71 @@ public V get() throws InterruptedException, ExecutionException {
         }
     }
 
+    @Override
+    public V get(long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException {
+        final long deadlineNanoTime = System.nanoTime() + unit.toNanos(timeout);
```
Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: just a small one: It's easier to work in ms rather then ns. `Object.wait()` will convert it to ms anyway -> you can save potentially expensive modulo operation, but more importantly - it will simplify the code.

**Comment by jerrinot** [comment]
verify

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java (hunk 2 above)
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: Thx. Fixed as suggested.

**Comment by jerrinot** [comment]
:+1: from me. 

Normally having two :+1: would be enough to merge it. However this is a very core part of the system and I believe one more pair of eyes would be great. I'm nominating @metanet as he has a good knowledge in this area.

File: hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java [hunk 3]
```diff
@@ -110,25 +163,71 @@ public V get() throws InterruptedException, ExecutionException {
...
+                throw new InterruptedException();
+            }
+
+            millisToWait = deadlineTimeMillis - System.currentTimeMillis();
+            if (millisToWait <= 0) {
+                throw new TimeoutException();
+            }
+
+            synchronized (this) {
+                if (!isDoneState(this.state)) {
```
Comment (gurbuzali) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: I think we may have still race here for cancellation

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: I believe it's fine. As a cancelled future is "done". @tombujok: Perhaps you should rename the method to `isFinishedOrCancelled`? or something like this. I made the same mistake while reviewing it.

Comment (gurbuzali) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: I see

Comment (mtopolnik) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: @jerrinot My suggestion was `isFinalState` to imply that no more state changes can occur, but avoid the implications of having completed successfully. But I must say I also argued for the removal of comments explaining what "done" means for a Future because it is already documented in the official Oracle docs for `Future`. OTOH I do suggest writing a short Javadoc comment on top of `isDoneState` which reinforces the meaning.

Comment (jerrinot) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: +1 to `isFinalState()`

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: The idea was to have an analogous naming convention to the Future's `isDone()` and `isCancelled()` one, thus we named it `isDoneState()` and `isCancelledState()`.

Introducing another word like `final` doesn't help much here IMHO, because somebody still has to know if `finalState` encompasses `cancelled` or not.
I would call the method `isDoneOrCancelled()` - then it's obvious what it means.

WDYT?

Comment (mtopolnik) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: I just hate admitting in a method name that we don't know the semantics of a "done" future :) Keeping the current name and adding a Javadoc which reminds of the meaning of "done" would sit nicer with me.

Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/spi/impl/AbstractCompletableFuture.java]: OK, I've added a javadoc to the isDoneState()

File: hazelcast/src/test/java/com/hazelcast/executor/CompletableFutureTest.java [hunk 4]
```diff
@@ -23,158 +23,350 @@
...
+        f.andThen(storeTaskResponseToReference(reference2));
+
+        releaseAwaitingTask();
+
+        assertCallbacksExecutedEventually();
+        assertTestExceptionThrown(reference1, reference2);
     }
 
     @Test
+    @Repeat(10)
```
Comment (metanet) [inline hazelcast/src/test/java/com/hazelcast/executor/CompletableFutureTest.java]: I suppose there is a @Repeat left-over here.

**Comment by metanet** [comment]
:+1:  with a minor comment

File: hazelcast/src/test/java/com/hazelcast/executor/CompletableFutureTest.java (hunk 4 above)
Comment (tombujok) [inline hazelcast/src/test/java/com/hazelcast/executor/CompletableFutureTest.java]: Thx for spotting - I left it intentionally there just increase to chance of a failing test should there be any hidden bug. Would you prefer to have all the `@Repeat`s deleted? These tests are rather fast, so it's not a huge bottleneck

**Comment by gurbuzali** [comment]
I would like `Repeat`s removed, after all our CI is repeating the tests daily.
I'll merge this one, @tombujok can you please remove the `Repeat`s with a direct commit, no need a PR for that.

**Comment by tombujok** [comment]
Thx for the merge. `@Repeat`s removed with a direct commit:
https://github.com/hazelcast/hazelcast/commit/11ababded2d01fccf0b5f0ab4f26ac122429c291
