### PR TITLE
Fix ConfiguredBehaviourTests

### LINKED ISSUE #10810: ConfiguredBehaviourTest
**com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeONSingleMember**
```java
com.hazelcast.client.HazelcastClientNotActiveException: Partition does not have an owner. partitionId: 31
	at com.hazelcast.client.spi.impl.ClientInvocation.notifyException(ClientInvocation.java:186)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:153)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:171)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:96)
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:33)
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155)
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:188)
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:182)
	at com.hazelcast.client.proxy.ClientMapProxy.putInternal(ClientMapProxy.java:516)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:508)
	at com.hazelcast.client.proxy.ClientMapProxy.put(ClientMapProxy.java:311)
	at com.hazelcast.client.connectionstrategy.ConfiguredBehaviourTest.testReconnectModeONSingleMember(ConfiguredBehaviourTest.java:157)
Caused by: java.io.IOException: Partition does not have an owner. partitionId: 31
	at com.hazelcast.client.spi.impl.ClientSmartInvocationServiceImpl.invokeOnPartitionOwner(ClientSmartInvocationServiceImpl.java:42)
	at com.hazelcast.client.spi.impl.ClientInvocation.invokeOnSelection(ClientInvocation.java:143)
	at com.hazelcast.client.spi.impl.ClientInvocation.retry(ClientInvocation.java:171)
	at com.hazelcast.client.spi.impl.ClientInvocation.run(ClientInvocation.java:159)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
	at com.hazelcast.util.executor.LoggingScheduledExecutor$LoggingDelegatingFuture.run(LoggingScheduledExecutor.java:128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
```
https://hazelcast-l337.ci.cloudbees.com/job/new-lab-fast-pr/9592/testReport/junit/com.hazelcast.client.connectionstrategy/ConfiguredBehaviourTest/testReconnectModeONSingleMember/

### PR DESCRIPTION
**Pull request by sancar**
Tests were not waiting for clients to disconnect. It could be the
case that, client did not get disconnections when servers are closed.
In that case tests can fail.

When I add the waits for shutdown/disconnect, I realized that the thread
doing the shutdown (cluster executor thread), waiting itself to shutdown
and timing out with warning. We had an external thread spawn for these
cases before, it  seems that in new development of ClientConnectionStrategy
it is missed. I added that back.

fixes #10810

### CODE REVIEW

File: hazelcast-client/src/test/java/com/hazelcast/client/connectionstrategy/ConfiguredBehaviourTest.java [hunk 1]
```diff
@@ -104,12 +104,22 @@ public void testReconnectModeOFFSingleMember() {
         ClientConfig clientConfig = new ClientConfig();
         clientConfig.getConnectionStrategyConfig().setReconnectMode(OFF);
         HazelcastInstance client = hazelcastFactory.newHazelcastClient(clientConfig);
+        final CountDownLatch disconnectedLatch = new CountDownLatch(1);
+        client.getLifecycleService().addLifecycleListener(new LifecycleListener() {
+            @Override
+            public void stateChanged(LifecycleEvent event) {
+                if (LifecycleEvent.LifecycleState.SHUTDOWN.equals(event.getState())) {
```
Comment (ihsandemir) [inline hazelcast-client/src/test/java/com/hazelcast/client/connectionstrategy/ConfiguredBehaviourTest.java]: It should be enough to wait for CLIENT_DISCONNECTED, right? why use SHUTDOWN state?
