### PR TITLE
Provide CREATE MAPPING suggestion on existing but not mapped IMap exception

### LINKED ISSUE #19464: CREATE MAPPING auto-suggestion
**User paths**
* In MC in SQL browser, user should see an indication that the map doesn't have a mapping created. So it says "Do you want to create mapping? Here's a suggestion based on your sampled data:". Clicks run, boom, can query map now.
* If a user runs a SQL query (e.g. via clients) against a map that doesn't have mapping already, it adds the suggstion in the error message of the returned exception.

From the SQL engine point of view that means providing an API (e.g. via the private API for MC on client) for the suggestion. Technical details to be figured out with the MC team.

### PR DESCRIPTION
**Pull request by gierlachg**
`HazelcastSqlException` gains `suggestion` (suggested SQL statement to remediate experienced error).
In a situation when an `IMap` exists but is not mapped, `suggestion` contains `CREATE MAPPING` statement for this particular `IMap`.

Added SqlMappingDdl client operation - one can pass a name of an `IMap` and get `CREATE MAPPING` statement for it.

Depends upon [#391](https://github.com/hazelcast/hazelcast-client-protocol/pull/391)

Fixes #19464

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/sql/HazelcastSqlException.java [hunk 1]
```diff
@@ -57,4 +65,14 @@ public UUID getOriginatingMemberId() {
     public int getCode() {
         return code;
     }
+
+    /**
+     * Gets the suggested SQL statement to remediate experienced error
+     *
+     * @return Suggested SQL statement to remediate experienced error.
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/HazelcastSqlException.java:72]: Duplicate comment

File: hazelcast/src/main/java/com/hazelcast/sql/impl/SqlErrorCode.java [hunk 2]
```diff
@@ -50,6 +47,9 @@
     /** An error with data conversion or transformation. */
     public static final int DATA_EXCEPTION = 2000;
 
+    /** Object (mapping/table) not found. */
+    public static final int OBJECT_NOT_FOUND = 3000;
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/SqlErrorCode.java:51]: I'd use 1010...

File: hazelcast/src/main/java/com/hazelcast/sql/impl/schema/MappingResolver.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+/**
+ * Generic interface that resolves mappings based on object name.
+ */
+@FunctionalInterface
+public interface MappingResolver {
+
+    @Nullable
+    Mapping resolve(String name);
+
+    final class CompositeMappingResolver implements MappingResolver {
```
Comment (viliam-durina) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/schema/MappingResolver.java:33]: This class is only used in test.

**Review by viliam-durina — CHANGES_REQUESTED** [review]

**Comment by viliam-durina** [comment]
Also this needs to be updated: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/sql/SqlService.java#L52-L54

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/Metadata.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+        return fields;
+    }
+
+    Map<String, String> options() {
+        return options;
+    }
+
+    Metadata merge(Metadata other) {
+        List<MappingField> fields = new ArrayList<>(concat(this.fields.stream(), other.fields.stream())
+                .collect(toCollection(() -> new TreeSet<>(Comparator.comparing(MappingField::name)))));
```
[the remark this answers is not in the document]
Comment (gierlachg) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/Metadata.java:56]: Using `distinct` would mean using `equals` and comparing entire `MappingField`s while we want to compare just names.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java [hunk 5]
```diff
@@ -163,7 +170,61 @@ public void unparse(SqlWriter writer, int leftPrec, int rightPrec) {
...
+        writer.print(escape(mapping.name()));
+
+        if (mapping.externalName() != null) {
+            writer.print(" ");
+            writer.keyword("EXTERNAL NAME");
+            writer.print(escape(mapping.externalName()));
+        }
+
+        List<MappingField> fields = mapping.fields();
+        if (fields.size() > 0) {
```
[the remark this answers is not in the document]
Comment (gierlachg) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java:186]: Generating empty list would result in syntax error. Not including any fields means exactly that fields should be resolved.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/schema/MappingResolver.java (hunk 3 above)
Comment (gierlachg) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/schema/MappingResolver.java:33]: And in `CalciteSqlOptimizer`.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlError.java [hunk 6]
```diff
@@ -26,11 +27,24 @@
...
 
     public SqlError(int code, String message, UUID originatingMemberId) {
+        this(code, message, originatingMemberId, false, null);
+    }
+
+    public SqlError(
+            int code,
+            String message,
+            UUID originatingMemberId,
+            boolean suggestionExists, String suggestion
```
Comment (ivanthescientist) [inline hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlError.java:41]: Just curious, but is there any reason (aside from style/simplifying `equals` checks) not to just use a `suggestion != null` instead of `suggestionExists`?

**Review by ivanthescientist — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlError.java (hunk 6 above)
Comment (gierlachg) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/client/SqlError.java:41]: We have to support `v1.equals(v2)` as well as `v2.eauals(v1)`.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMapping.java:185]: That's the point, the empty field list must only come from an error. So in case of erroneous input we'll produce erroneous output, not an output that means something else.

File: hazelcast/src/main/java/com/hazelcast/sql/impl/schema/MappingResolver.java (hunk 3 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/sql/impl/schema/MappingResolver.java:33]: yeah, but there it is used needlessly - a composite resolver composed of a single resolver

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMappingTest.java [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+import com.hazelcast.sql.impl.schema.Mapping;
+import com.hazelcast.sql.impl.schema.MappingField;
+import com.hazelcast.sql.impl.type.QueryDataType;
+import org.junit.Test;
+
+import static java.util.Arrays.asList;
+import static java.util.Collections.singletonList;
+import static org.assertj.core.api.Assertions.assertThat;
+
+public class SqlCreateMappingTest {
```
[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/parse/SqlCreateMappingTest.java:29]: Maybe it would be better if the line endings didn't depend on which OS the cluster runs. But I couldn't find an option in calcite's SqlWriter to configure this, it always uses the system separator. Anyway, it's not a big issue I think.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataResolver.java [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+import com.hazelcast.sql.impl.schema.Mapping;
+import com.hazelcast.sql.impl.schema.MappingResolver;
+
+import javax.annotation.Nullable;
+import java.util.Iterator;
+import java.util.Map.Entry;
+
+import static com.hazelcast.jet.sql.impl.connector.map.IMapSqlConnector.TYPE_NAME;
+
+public class MetadataResolver implements MappingResolver {
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/connector/map/MetadataResolver.java:41]: A better name would be `IMapMappingResolver`

**Review by viliam-durina — APPROVED** [review]

**Review by promanenko — APPROVED** [review]

**Review by mdumandag — APPROVED** [review]
Looks good to me
