### PR TITLE
Fix for issue #8261

### LINKED ISSUE #8261: Cluster is in PASSIVE state! vs TargetDisconnectedException 3.7-SNAP
while testing  hzInstance.getCluster().shutdown();   on  3.6.3  and 3.7-SANPSHOT

using a 4 node cluster,  with 4 clients making putAll ops.

during which we call, hzInstance.getCluster().shutdown();  from one member of the cluster

with 3.6.3 clients get
```
java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.map.impl.operation.PutAllOperation{identityHash=993079332, serviceName='hz:impl:mapService', partitionId=64, replicaIndex=0, callId=741874, invocationTime=1464269130111 (Thu May 26 13:25:30 UTC 2016), waitTimeout=-1, callTimeout=60000, name=mapBak1}
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:200)
```

with 3.7-SANPSHOT clients get
```
com.hazelcast.spi.exception.TargetDisconnectedException: Disconnecting from member [10.0.0.189]:5701 due to heartbeat problems. Current time: 2016-05-26 13:37:11.896. Last heartbeat: never
    at com.hazelcast.spi.exception.TargetDisconnectedException.newTargetDisconnectedExceptionCausedByHeartBeat(TargetDisconnectedException.java:48)
```

so me it seem 3.6.3,  is correct,  and exception given in 3.7-SANPSHOT  is misleading

3.6.3 member log example
```
May 26, 2016 1:25:30 PM com.hazelcast.cluster.impl.operations.ChangeClusterStateOperation
INFO: [10.0.0.188]:5701 [HZ] [3.6.3] Changing cluster state state to PASSIVE, Initiator: Address[10.0.0.186]:5701
May 26, 2016 1:25:30 PM com.hazelcast.map.impl.operation.PutAllOperation
SEVERE: [10.0.0.188]:5701 [HZ] [3.6.3] Cluster is in PASSIVE state! Operation: com.hazelcast.map.impl.operation.PutAllOperation{identityHash=954986353, serviceName='hz:impl:mapService', partitionId=184, replicaIndex=0, callId=757747, invocationTime=1464269130111 (Thu May 26 13:25:30 UTC 2016), waitTimeout=-1, callTimeout=60000, name=mapBak1}
java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.map.impl.operation.PutAllOperation{identityHash=954986353, serviceName='hz:impl:mapService', partitionId=184, replicaIndex=0, callId=757747, invocationTime=1464269130111 (Thu May 26 13:25:30 UTC 2016), waitTimeout=-1, callTimeout=60000, name=mapBak1}
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:200)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:156)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThread(ClassicOperationExecutor.java:392)
    at com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor.runOnCallingThreadIfPossible(ClassicOperationExecutor.java:345)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:259)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:243)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invokeInternal(Invocation.java:210)
    at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:180)
    at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:46)
    at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:65)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:118)
    at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:98)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:127)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processPartitionSpecificRunnable(OperationThread.java:159)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:142)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124)
    at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99)
```

and 3.7-SANPSHOT member log example
```
May 26, 2016 1:37:11 PM com.hazelcast.internal.cluster.impl.operations.ChangeClusterStateOperation
INFO: [10.0.0.188]:5701 [HZ] [3.7-SNAPSHOT] Changing cluster state state to PASSIVE, Initiator: [10.0.0.186]:5701
May 26, 2016 1:37:11 PM com.hazelcast.map.impl.operation.PutAllBackupOperation
SEVERE: [10.0.0.188]:5701 [HZ] [3.7-SNAPSHOT] Cluster is in PASSIVE state! Operation: com.hazelcast.spi.impl.operationservice.impl.operations.Backup{serviceName='null', identityHash=1313662299, partitionId=149, replicaIndex=1, callId=741874, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, backupOp=com.hazelcast.map.impl.operation.PutAllBackupOperation{serviceName='hz:impl:mapService', identityHash=591857971, partitionId=-1, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, name=mapBak1}, backupOpData=null, originalCaller=[10.0.0.189]:5701, version=[11167, 0, 0, 0, 0, 0], sync=true}
java.lang.IllegalStateException: Cluster is in PASSIVE state! Operation: com.hazelcast.spi.impl.operationservice.impl.operations.Backup{serviceName='null', identityHash=1313662299, partitionId=149, replicaIndex=1, callId=741874, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, backupOp=com.hazelcast.map.impl.operation.PutAllBackupOperation{serviceName='hz:impl:mapService', identityHash=591857971, partitionId=-1, replicaIndex=0, callId=0, invocationTime=-1 (1969-12-31 23:59:59.999), waitTimeout=-1, callTimeout=9223372036854775807, name=mapBak1}, backupOpData=null, originalCaller=[10.0.0.189]:5701, version=[11167, 0, 0, 0, 0, 0], sync=true}
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.checkNodeState(OperationRunnerImpl.java:211)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:167)
    at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:397)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:117)
    at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:102)

### PR DESCRIPTION
**Pull request by ihsandemir**
Fixes #8261 . Makes sure that the CleanupResourcesTask only sets the future value after the connection is closed.

### CODE REVIEW

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java [hunk 1]
```diff
@@ -60,6 +60,7 @@
     @Probe
     protected final int connectionId;
     private final AtomicBoolean alive = new AtomicBoolean(true);
+    private final AtomicBoolean closeCompeleted = new AtomicBoolean(false);
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java]: Perhaps call it 'closed' ? Also the false initial value isn't needed, since it will be false be default.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java [hunk 2]
```diff
@@ -203,7 +204,11 @@ public void run() {
                 if (connection == null) {
                     continue;
                 }
-                if (connection.isHeartBeating()) {
+
+                boolean isAlive = connection.isAlive();
+                boolean isHeartbeating = connection.isHeartBeating();
+
+                if (isHeartbeating || (!isAlive && !connection.isCloseCompleted())) {
```
Comment (pveentjer) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java]: Why not simplify it to

if(!connection.isClosed()) continue;

**Comment by pveentjer** [comment]
Looks good. Minor comments

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java (hunk 1 above)
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java]: OK, changed.

File: hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java [hunk 3]
```diff
@@ -281,6 +282,12 @@ public void close(String reason, Throwable cause) {
         connectionManager.onClose(this);
 
         client.getMetricsRegistry().discardMetrics(this);
+
+        closeCompeleted.set(true);
+    }
+
+    public boolean isCloseCompleted() {
```
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/connection/nio/ClientConnection.java]: OK, renamed.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java (hunk 2 above)
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java]: Because, there is this case: heartbeating=false, live=true, for non-owner connection. If you look at heartbeatStopped method, it does not close the connection for non-owner connection. What is the correct thing to do for this case? Should we fail the outstanding invocations for such a connection? What happens if the connection temporarily goes to heartbeat failed and then recovers? 

Changed to: if (isHeartbeating || !connection.isClosed())  but we can still discuss what would be the best.

File: hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java [hunk 4]
```diff
@@ -235,6 +242,28 @@ public void run() {
             }
         }
 
+        private void notifyException(ClientInvocation invocation, ClientConnection connection, boolean isAlive) {
+            Exception ex = null;
```
Comment (ihsandemir) [inline hazelcast-client/src/main/java/com/hazelcast/client/spi/impl/ClientInvocationServiceSupport.java]: OK, removed null assignment.

**Comment by ihsandemir** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
run-lab-run

**Comment by ihsandemir** [comment]
run-lab-run
