### PR TITLE
Change the MulticastConfig.DEFAULT_LOOPBACK_MODE_ENABLED value to false

### LINKED ISSUE #19192: Hazelcast 5.0-BETA-1 fails to start on MacOS
**Describe the bug**
1. Downloaded the hazelcast 5.0-BETA-1 zip file.
2. start a member using bin/hz-start using the default XML files in /config

Error is thrown to the console...

```
java.net.SocketException: Can't assign requested address
	at java.net.PlainDatagramSocketImpl.join(Native Method) ~[?:1.8.0_162]
	at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178) ~[?:1.8.0_162]
	at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323) ~[?:1.8.0_162]
	at com.hazelcast.internal.cluster.impl.MulticastService.configureMulticastSocket(MulticastService.java:169) ~[hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:114) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.Node.<init>(Node.java:265) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:95) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
	at com.hazelcast.core.server.HazelcastMemberStarter.main(HazelcastMemberStarter.java:47) [hazelcast-5.0-BETA-1.jar:5.0-BETA-1]
```

[logs.txt](https://github.com/hazelcast/hazelcast/files/6886259/logs.txt)

I am using

Java 8 on MacOS Catalina v 10.15.7

I downloaded the latest 4.2.1 and used `start.sh` and it works fine.

### PR DESCRIPTION
**Pull request by kwart**
Fixes #19192.

This PR changes the `MulticastConfig.loopbackModeEnabled` default to `false`. (i.e. it has to be explicitly enabled when required). The change also gets the default aligned with the value defined in the `hazelcast-config` XSD.

This change is related to #18669 which says the `MulticastSocket.setInterface()` must not be called when we bind to a loopback address or the `loopbackModeEnabled` is `true`. But we had the  `loopbackModeEnabled` set to `true` by default. And if `setInterface()` is not called, then some Java versions on Mac OS are not able to join the multicast group (as described in #19192).

We have to retest the change on all our supported platforms.

### CODE REVIEW

**Comment by kwart** [comment]
Oh, my holy code. This will be tough. The fix resolves the issue on Mac OS, but prevents forming clusters on my Linux box. Explicitly setting the `loopbackModeEnabled="true"` helps, but we need a fix working OOTB everywhere (or as close to everywhere as possible).

**Comment by ahmetmircik** [comment]
what about keeping everything as is and only setting interface if OS is Mac OS?
`boolean callSetInterface = isOsx() || loopbackBind || !multicastConfig.isLoopbackModeEnabled();`

**Comment by kwart** [comment]
This is a result table of my MulticastSocket behavior investigation.

The first column in the table says if the address used was a loopback one.
Next 3 columns shows parameters:
* was loopbackMode requested?
* was `setInterface()` called?
* was a host used in `MultiSocket.bind()`?

The last 4 columns show when the multicast socket was able to receive a datagram sent from the same host.

| address              | loopbackModeEnabled | setInterface called | bind to explicit InetAddress | Solaris | Mac OS | Linux | Windows |
|--------------|---------------------|---------------------|------------------------------|---------|--------|-------|---------|
| non-loopback | FALSE               | FALSE               | FALSE                        | FALSE   | FALSE  | FALSE | FALSE   |
| non-loopback | FALSE               | FALSE               | TRUE                         | FALSE   | FALSE  | FALSE | FALSE   |
| non-loopback | FALSE               | TRUE                | FALSE                        | FALSE   | **TRUE**   | FALSE | FALSE   |
| non-loopback | FALSE               | TRUE                | TRUE                         | FALSE   | FALSE  | FALSE | FALSE   |
| non-loopback | TRUE                | FALSE               | FALSE                        | **TRUE**    | FALSE  | **TRUE**  | **TRUE**    |
| non-loopback | TRUE                | FALSE               | TRUE                         | FALSE   | FALSE  | FALSE | TRUE    |
| non-loopback | TRUE                | TRUE                | FALSE                        | **TRUE**    | **TRUE**   | **TRUE**  | **TRUE**    |
| non-loopback | TRUE                | TRUE                | TRUE                         | FALSE   | FALSE  | FALSE | FALSE   |
| loopback     | FALSE               | FALSE               | FALSE                        | FALSE   | FALSE  | FALSE | FALSE   |
| loopback     | FALSE               | FALSE               | TRUE                         | FALSE   | FALSE  | FALSE | FALSE   |
| loopback     | FALSE               | TRUE                | FALSE                        | FALSE   | FALSE  | FALSE | FALSE   |
| loopback     | FALSE               | TRUE                | TRUE                         | FALSE   | FALSE  | FALSE | FALSE   |
| loopback     | TRUE                | FALSE               | FALSE                        | **TRUE**    | FALSE  | **TRUE**  | **TRUE**    |
| loopback     | TRUE                | FALSE               | TRUE                         | FALSE   | FALSE  | FALSE | FALSE   |
| loopback     | TRUE                | TRUE                | FALSE                        | FALSE   | FALSE  | FALSE | **TRUE**    |
| loopback     | TRUE                | TRUE                | TRUE                         | FALSE   | FALSE  | FALSE | **TRUE**    |

So, in my tests, Solaris and Linux behaved in the same way. Mac OS and WIndows required different parameters to be configured.

*I used just 1 machine for each tested OS, so there may be other environmental effects I didn't notice.*

**Comment by kwart** [comment]
> what about keeping everything as is and only setting interface if OS is Mac OS? Something like this:
> `boolean callSetInterface = isOsx() || loopbackBind || !multicastConfig.isLoopbackModeEnabled();`

I wanted to avoid these OS dependent changes, but you're right. After trying the behavior, this seems as the only correct way.
The condition in the new commit was simplified to:
`callSetInterface = isOsx() || !loopbackBInd;`

*So long, "write once, run everywhere".*

File: hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java [hunk 1]
```diff
@@ -46,4 +46,13 @@ public static boolean isLinux() {
...
         return (OS.contains("nix") || OS.contains("nux") || OS.contains("aix"));
     }
+
+    /**
+     * Returns {@code true} if the system is a Mac OS.
+     *
+     * @return {@code true} if the current system is Mac.
+     */
+    public static boolean isMac() {
+        return (OS.contains("mac") || OS.contains("darwin"));
```
Comment (ahmetmircik) [inline hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java:56]: maybe we should also search for string "osx" for some macOS versions: https://support.apple.com/en-us/HT201260 (see the table)

**Review by gurbuzali — APPROVED** [review]

**Comment by gurbuzali** [comment]
I can confirm it fixes the issue for me, macOs Catalina 10.15.5

File: hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java (hunk 1 above)
Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java:56]: tested `os.name` property on macos 11.4 & 10.13 and both return `Mac OS X`

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java (hunk 1 above)
Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java:56]: >In 2012, with the release of OS X 10.8 Mountain Lion, the name of the system was shortened from Mac OS X to OS X

>In 2016, with the release of macOS 10.12 Sierra, the name was changed from OS X to macOS

Based on this [wikipedia](https://en.wikipedia.org/wiki/MacOS#OS_X) entry, only checking for "mac" is not sufficient.

Comment (vbekiaris) [reply hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java:56]: I think Apple's OS names don't have much to do with what the JDK returns for `os.name` property. The [JDK 8 sources since 2013](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/1a3de3cdc684/src/solaris/native/java/lang/java_props_macosx.c#l132) hard-code the os name to `Mac OS X`. This seems to be the same as [current JDK status](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/java.base/macosx/native/libjava/java_props_macosx.c#L233-L235). Also, JDK sources themselves rely on matching `Mac OS X` like [here](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/test/jdk/java/lang/ProcessBuilder/DestroyTest.java#L115) and [here](https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/test/jdk/java/lang/ProcessBuilder/DestroyTest.java#L115).

Comment (ahmetmircik) [reply hazelcast/src/main/java/com/hazelcast/internal/util/OsHelper.java:56]: Thanks then it seems there is no missing case.

**Review by ahmetmircik — APPROVED** [review]

**Comment by vbekiaris** [comment]
thanks @kwart for the PR & @gurbuzali @ahmetmircik for the reviews!
