### PR TITLE
Compatibility test related fixes and improvements

### LINKED ISSUE #16624: Multiple `AnswerTest` failures
- Fails on `Hazelcast-3.x-IbmJDK8-fips-nightly`, `Hazelcast-4.master-nightly`
- Fails on [Build #126 (Feb 7, 2020 9:12:44 AM)](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK8-fips-nightly/126/#showFailuresLink)
- Sample Error 
```
java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/hazelcast/hazelcast-client/4.0/hazelcast-client-4.0.jar
```
- Stack trace
```
com.hazelcast.test.starter.GuardianException: java.io.FileNotFoundException: https://repo1.maven.org/maven2/com/hazelcast/hazelcast-client/4.0/hazelcast-client-4.0.jar
	at com.hazelcast.test.starter.HazelcastStarterUtils.rethrowGuardianException(HazelcastStarterUtils.java:53)
	at com.hazelcast.test.starter.HazelcastVersionLocator.downloadFile(HazelcastVersionLocator.java:141)
....
```
- List of failing cases
```
com.hazelcast.test.starter.answer.test.AnswerTest.testMapService
com.hazelcast.test.starter.answer.test.AnswerTest.testCacheService
com.hazelcast.test.starter.answer.test.AnswerTest.testHazelcastInstanceImpl
com.hazelcast.test.starter.answer.test.AnswerTest.testNode
com.hazelcast.test.starter.answer.test.AnswerTest.testMultiMapService
com.hazelcast.test.starter.answer.test.AnswerTest.testPartitionService
com.hazelcast.test.starter.answer.test.AnswerTest.testSerializationService
com.hazelcast.test.starter.answer.test.AnswerTest.testClusterService
com.hazelcast.test.starter.answer.test.AnswerTest.testSetService
com.hazelcast.test.starter.answer.test.AnswerTest.testQueueService
com.hazelcast.test.starter.answer.test.AnswerTest.testNodeEngine
```

- Since we do not deploy `hazelcast-client-4.0.jar` anymore it looks these tests need to be updated 
kindly check
```
proper dependency could be https://repo1.maven.org/maven2/com/hazelcast/hazelcast/4.0/hazelcast-4.0.jar
```

### PR DESCRIPTION
**Pull request by vbekiaris**
- Cleaned up `Versions` constants for 4.x
- Updated & improved `HazelcastVersionLocator`: removed
lookup for obsolete `hazelcast-client` artifact, minor cleanups
- Updated dynamically attached agent for final class
modifier removal
- `AnswerTest` is removed for OS repository; it is
moved to EE repository, to be executed properly as a
compatibility test
- Removes irrelevant compatibility test `DeleteOperationWanFlagSerializationTest`
and `-XX:MaxPermSize` options from maven executions

Requires an EE counterpart
Fixes #16624

### CODE REVIEW

File: hazelcast/src/test/java/com/hazelcast/test/compatibility/CompatibilityTestUtils.java [hunk 1]
```diff
@@ -32,25 +28,18 @@
...
-                                                            ClassLoader classLoader, JavaModule module) {
-                        int actualModifiers = typeDescription.getActualModifiers(false);
-                        // unset final modifier
-                        int nonFinalModifiers = actualModifiers & ~Opcodes.ACC_FINAL;
-                        return builder.modifiers(nonFinalModifiers);
-                    }
-                })
-                .installOn(instrumentation);
+        new AgentBuilder.Default().with(AgentBuilder.TypeStrategy.Default.REDEFINE)
+                                  .with(AgentBuilder.InitializationStrategy.NoOp.INSTANCE)
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/test/compatibility/CompatibilityTestUtils.java]: Previously used `disableClassFormatChanges()` was actually disallowing removal of `final` modifier, silently disregarding the transformer. We configure the agent with `REDEFINE` type strategy and `NoOp` initialization strategy; this allows for the redefinition of the type (instead of default `REBASE` strategy) without adding any methods (which result in modifying `Serializable` classes' `serialVersionUid`). For more details see [`ByteBuddy#rebase`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/ByteBuddy.java#L775) vs [`ByteBuddy#redefine`](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-dep/src/main/java/net/bytebuddy/ByteBuddy.java#L697).

File: hazelcast/src/test/java/com/hazelcast/test/starter/test/HazelcastVersionLocatorTest.java [hunk 2]
```diff
@@ -45,19 +46,15 @@
...
 
-        assertHash(files[2], "fd6022e35908b42d24fe10a9c9fdaad5", "OS client");
+        assertHash(files[2], "765816e628ca4ca57d5bd7387e761eaa", "EE");
 
-        assertHash(files[3], "c5718ba5c280339fff9b54ecb5e61549", "EE member");
-
-        assertHash(files[4], "c5df750fdab71a650fb56c41742806ff", "EE member tests");
-
-        assertHash(files[5], "b1cf93ec4bb9bcda8809b81349f48cb3", "EE client");
+        assertHash(files[3], "162bcb2412570845e6fd91ee61b54f94", "EE tests");
```
Comment (vojtechtoman) [inline hazelcast/src/test/java/com/hazelcast/test/starter/test/HazelcastVersionLocatorTest.java]: `HAZELCAST_EE_TESTS_JAR_INDEX`?

File: hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastVersionLocator.java [hunk 3]
```diff
@@ -56,21 +59,19 @@
...
+            files[HAZELCAST_EE_JAR_INDEX] = locateMainArtifact(version, target, true);
+            files[HAZELCAST_EE_TESTS_JAR_INDEX] = locateTestsArtifact(version, target, true);
         }
         return files;
     }
 
     // attempts to locate member artifact in local maven repository, then downloads
-    private static File locateMember(String version, File target, boolean enterprise) {
-        File artifact = new File(LOCAL_M2_REPOSITORY_PREFIX + constructPathForMember(version, enterprise));
+    private static File locateMainArtifact(String version, File target, boolean enterprise) {
```
Comment (vojtechtoman) [inline hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastVersionLocator.java]: Minor: since `locateMember` has been renamed to `locateMainArtifact`, maybe `downloadMember` should be renamed, too?

File: hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastVersionLocator.java [hunk 4]
```diff
@@ -79,41 +80,24 @@ private static File locateMember(String version, File target, boolean enterprise
     }
 
     // attempts to locate member tests artifact in local maven repository, then downloads
-    private static File locateMemberTests(String version, File target, boolean enterprise) {
-        File artifact = new File(LOCAL_M2_REPOSITORY_PREFIX + constructPathForMemberTests(version, enterprise));
+    private static File locateTestsArtifact(String version, File target, boolean enterprise) {
```
Comment (vojtechtoman) [inline hazelcast/src/test/java/com/hazelcast/test/starter/HazelcastVersionLocator.java]: Minor: since `locateMemberTests` has been renamed to `locateTestsArtifact`, maybe `downloadMemberTests` should be renamed, too?

File: pom.xml [hunk 5]
```diff
@@ -119,7 +119,7 @@
         <atomikos.version>3.9.3</atomikos.version>
         <!-- Additional JVM system arguments -->
         <extraVmArgs/>
-        <vmHeapSettings>-Xms512m -Xmx2G -XX:MaxPermSize=1024M</vmHeapSettings>
+        <vmHeapSettings>-Xms512m -Xmx2G</vmHeapSettings>
```
Comment (vojtechtoman) [inline pom.xml]: Nice catch. Better late than never :)

File: hazelcast/src/test/java/com/hazelcast/test/compatibility/CompatibilityTestUtils.java (hunk 1 above)
Comment (vojtechtoman) [reply hazelcast/src/test/java/com/hazelcast/test/compatibility/CompatibilityTestUtils.java]: +1 for the `REDEFINE`/`REBASE` background info, what about adding it as a code comment for posterity?

File: hazelcast/src/test/java/com/hazelcast/test/starter/test/HazelcastVersionLocatorTest.java [hunk 6]
```diff
@@ -45,19 +46,15 @@
...
     @Test
     public void testDownloadVersion() throws Exception {
-        File[] files = HazelcastVersionLocator.locateVersion("3.6", folder.getRoot(), true);
+        File[] files = HazelcastVersionLocator.locateVersion("4.0", folder.getRoot(), true);
 
-        assertHash(files[0], "89563f7dab02bd5f592082697c24d167", "OS member");
+        assertHash(files[HAZELCAST_JAR_INDEX], "bc409b12b96ece6d05c3bd1e99b202bb", "OS");
 
-        assertHash(files[1], "66615c68c2708036a6030114a1b87f2b", "OS member tests");
+        assertHash(files[1], "220509ece9fc152525c91ba7c75ce600", "OS tests");
```
[the remark this answers is not in the document]
Comment (vbekiaris) [reply hazelcast/src/test/java/com/hazelcast/test/starter/test/HazelcastVersionLocatorTest.java]: 🤦‍♂ I thought I did that...

**Comment by vbekiaris** [comment]
@vojtechtoman @Holmistr thanks for the reviews
