### PR TITLE
Avoid wrong results when querying with full table scan during migrations

### LINKED ISSUE #6471: QueryIndexMigrationTest.testIndexCleanupOnMigration
```
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:182)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:822)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:980)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1292)
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:229)
	at java.util.concurrent.FutureTask.get(FutureTask.java:94)
	at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testIndexCleanupOnMigration(QueryIndexMigrationTest.java:185)

```

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.6/com.hazelcast$hazelcast/712/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-OpenJDK6/com.hazelcast$hazelcast/693/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testIndexCleanupOnMigration/

### LINKED ISSUE #8046: QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating
```
java.lang.AssertionError: expected:<30> but was:<29>
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:631)
    at com.hazelcast.map.impl.query.QueryIndexMigrationTest.testQueryWithIndexesWhileMigrating(QueryIndexMigrationTest.java:157)
```

https://hazelcast-l337.ci.cloudbees.com/view/Official%20Builds/job/Hazelcast-3.x-IbmJDK1.7/com.hazelcast$hazelcast/892/testReport/junit/com.hazelcast.map.impl.query/QueryIndexMigrationTest/testQueryWithIndexesWhileMigrating/

### PR DESCRIPTION
**Pull request by vbekiaris**
Applies validation of no owner migrations in flight and partition state version at beginning & end of `querySequential` to avoid query correctness issues. Also, added the no owner migrations in flight condition at end of `tryQueryUsingIndexes`.
Fixes #6471 
Fixes #8046

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java [hunk 1]
```diff
@@ -158,9 +165,12 @@ protected QueryResult tryQueryUsingIndexes(Predicate predicate, Collection<Integ
...
 
         QueryResult result = newQueryResult(partitions.size(), iterationType);
-        // if partition state version has changed in the meanwhile, this means migrations were executed and we may
+        // If partition state version has changed in the meanwhile, this means migrations were executed and we may
         // return stale data, so we should rather return null and let the query run with a full table scan
-        if (initialPartitionStateVersion != partitionService.getPartitionStateVersion()) {
+        // Also make sure there are no long migrations in flight which may have started after starting the query
+        // but not completed yet.
+        if (mapServiceContext.getService().getOwnerMigrationsInFlight() > 0
+                || initialPartitionStateVersion != partitionService.getPartitionStateVersion()) {
```
Comment (tombujok) [inline hazelcast/src/main/java/com/hazelcast/map/impl/query/MapQueryEngineImpl.java]: Could we maybe have a helper method for `mapServiceContext.getService().getOwnerMigrationsInFlight() > 0` and for the full condition check with or? It's being repeated in a couple of places. For example?

`mapServiceContext.getService().getOwnerMigrationsInFlight() > 0` -> `areThereMigrationsInFlight()`

`initialPartitionStateVersion != partitionService.getPartitionStateVersion())` -> `hasThePartitionStateChanged(initialPartitionStateVersion)`

Both: `isResultNonAmbigous()`?

**Comment by tombujok** [comment]
The changes look good. I was wondering if we don't have to add similar check to methods using the PagingPredicate (but I didn't really look into them)

**Comment by vbekiaris** [comment]
Both `queryParallel` & `queryParallelForPaging` are only invoked within `queryUsingFullTableScan` which is wrapped with safety checks in `querySafelyUsingFullTableScan` so there is no need to add further explicit checks in those methods.

**Comment by tombujok** [comment]
thx for the clarification 👍 good job!

**Comment by vbekiaris** [comment]
run-lab-run

**Comment by jerrinot** [comment]
run-lab-run

**Comment by vbekiaris** [comment]
Build failed after successful completion with `16:44:27 Build step 'Publish artifacts to S3 Bucket' marked build as failure`

**Comment by ahmetmircik** [comment]
👍

**Comment by vbekiaris** [comment]
run-lab-run
