### PR TITLE
[HZ-707] HOP window function support

### LINKED ISSUE #19943: com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest.test
_master_ (commit d05be9ecf18da725ac8ccfc96fe1385977cadd13)

Failed on Openj9-11: [test result](http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-Openj9-11/52/testReport/com.hazelcast.jet.sql.impl.connector.kafka/SqlKafkaAggregateTest/test/)

<details><summary>Stacktrace:</summary>

```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:221)
	at java.base/java.lang.Thread.join(Thread.java:746)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:181)
	at com.hazelcast.jet.sql.SqlTestSupport.assertRowsEventuallyInAnyOrder(SqlTestSupport.java:141)
	at com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest.test(SqlKafkaAggregateTest.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

</details>

<details><summary>Standard output:</summary>

```
09:22:34,804  INFO |test| - [PartitionStateManager] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing cluster partition table arrangement...
09:22:34,807 DEBUG |test| - [CalciteSqlOptimizer] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalTableInsert(table=[[hazelcast, public, o_05e834da_c0b8_4b55_b148_e7ae5a1667cc[projects=[0, 1]]]], operation=[INSERT], flattened=[false])
  LogicalValues(tuples=[[{ 0, _UTF-16LE'value-0' }, { 1, _UTF-16LE'value-1' }, { 2, _UTF-16LE'value-2' }, { 10, _UTF-16LE'value-10' }]])

09:22:34,807 DEBUG |test| - [CalciteSqlOptimizer] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
InsertLogicalRel(table=[[hazelcast, public, o_05e834da_c0b8_4b55_b148_e7ae5a1667cc[projects=[0, 1]]]], operation=[INSERT], flattened=[false])
  ValuesLogicalRel(values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-0}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-1}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=2}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-2}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=10}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-10}]]}])

09:22:34,808 DEBUG |test| - [CalciteSqlOptimizer] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
InsertPhysicalRel(table=[[hazelcast, public, o_05e834da_c0b8_4b55_b148_e7ae5a1667cc[projects=[0, 1]]]], operation=[INSERT], flattened=[false])
  ValuesPhysicalRel(values=[{expressions=[[ConstantExpression{type=QueryDataType {family=INTEGER}, value=0}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-0}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=1}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-1}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=2}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-2}], [ConstantExpression{type=QueryDataType {family=INTEGER}, value=10}, ConstantExpression{type=QueryDataType {family=VARCHAR}, value=value-10}]]}])

09:22:34,809 DEBUG |test| - [LightMasterContext] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 071a-659f-ae00-0001, execution graph in DOT format:
digraph DAG {
	"Values" [localParallelism=1];
	"Project(Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc])" [localParallelism=default];
	"Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]" [localParallelism=1];
	"Values" -> "Project(Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc])" [queueSize=1024];
	"Project(Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc])" -> "Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]" [queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
09:22:34,809 DEBUG |test| - [LightMasterContext] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 071a-659f-ae00-0001
09:22:34,809 DEBUG |test| - [LightMasterContext] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 071a-659f-ae00-0001
09:22:34,809 DEBUG |test| - [InitExecutionOperation] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 071a-659f-ae00-0001, execution 071a-659f-ae00-0001 from [127.0.0.1]:5701
09:22:34,810 DEBUG |test| - [JobExecutionService] test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=071a-659f-ae00-0001, jobName='071a-659f-ae00-0001', executionId=071a-659f-ae00-0001 initialized, will start the execution
09:22:34,811 DEBUG |test| - [WriteKafkaP] hz.awesome_torvalds.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [071a-659f-ae00-0001/Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]#0] Actual pool size used: 1
09:22:34,819 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:22:34,927 DEBUG |test| - [WriteKafkaP] hz.awesome_torvalds.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [071a-659f-ae00-0001/Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]#0] release null
09:22:34,928 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '071a-659f-ae00-0001', execution 071a-659f-ae00-0001
09:22:34,928 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '071a-659f-ae00-0001', execution 071a-659f-ae00-0001 completed
09:22:34,932 DEBUG |test| - [CalciteSqlOptimizer] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Before logical opt:
LogicalAggregate(group=[{0, 1}], EXPR$2=[COUNT()])
  LogicalProject(window_start=[$2], window_end=[$3])
    LogicalTableFunctionScan(invocation=[TUMBLE($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this, INTEGER window_start, INTEGER window_end)])
      LogicalProject(__key=[$0], this=[$1])
        LogicalTableFunctionScan(invocation=[IMPOSE_ORDER($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this)])
          LogicalProject(__key=[$0], this=[$1])
            LogicalTableScan(table=[[hazelcast, public, o_05e834da_c0b8_4b55_b148_e7ae5a1667cc[projects=[0, 1]]]])

09:22:34,934 DEBUG |test| - [CalciteSqlOptimizer] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After logical opt:
AggregateLogicalRel(group=[{0, 1}], EXPR$2=[COUNT()])
  ProjectLogicalRel(window_start=[$2], window_end=[$3])
    SlidingWindowLogicalRel(invocation=[TUMBLE($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this, INTEGER window_start, INTEGER window_end)])
      FullScanLogicalRel(table=[[hazelcast, public, o_05e834da_c0b8_4b55_b148_e7ae5a1667cc[projects=[0, 1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$2037/0x00000000c4512b80@517a55e2])

09:22:34,949 DEBUG |test| - [CalciteSqlOptimizer] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] After physical opt:
SlidingWindowAggregateCombineByKeyPhysicalRel(group=[{0, 1}], EXPR$2=[COUNT()])
  SlidingWindowAggregateAccumulateByKeyPhysicalRel(group=[{0, 1}])
    ProjectPhysicalRel(window_start=[$2], window_end=[$3])
      SlidingWindowPhysicalRel(invocation=[TUMBLE($1, DESCRIPTOR($0), 2:TINYINT(2))], rowType=[RecordType(INTEGER __key, VARCHAR this, INTEGER window_start, INTEGER window_end)])
        FullScanPhysicalRel(table=[[hazelcast, public, o_05e834da_c0b8_4b55_b148_e7ae5a1667cc[projects=[0, 1]]]], eventTimePolicyProvider=[com.hazelcast.jet.sql.impl.opt.logical.WatermarkRules$1$$Lambda$2037/0x00000000c4512b80@517a55e2])

09:22:34,959 DEBUG |test| - [LightMasterContext] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Start executing light job 071a-659f-ae01-0001, execution graph in DOT format:
digraph DAG {
	"Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]" [localParallelism=4];
	"Sliding-Window" [localParallelism=default];
	"Project" [localParallelism=default];
	"Sliding-Window-AccumulateByKey" [localParallelism=default];
	"Sliding-Window-CombineByKey" [localParallelism=default];
	"ClientSink" [localParallelism=1];
	"Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]" -> "Sliding-Window" [queueSize=1024];
	"Sliding-Window" -> "Project" [queueSize=1024];
	"Project" -> "Sliding-Window-AccumulateByKey" [label="partitioned", queueSize=1024];
	"Sliding-Window-AccumulateByKey" -> "Sliding-Window-CombineByKey" [label="distributed-partitioned", queueSize=1024];
	"Sliding-Window-CombineByKey" -> "ClientSink" [label="distributed to [127.0.0.1]:5701-partitioned", queueSize=1024];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
09:22:34,959 DEBUG |test| - [LightMasterContext] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Building execution plan for 071a-659f-ae01-0001
09:22:34,959 DEBUG |test| - [LightMasterContext] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Built execution plans for 071a-659f-ae01-0001
09:22:34,963 DEBUG |test| - [InitExecutionOperation] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Initializing execution plan for job 071a-659f-ae01-0001, execution 071a-659f-ae01-0001 from [127.0.0.1]:5701
09:22:34,968 DEBUG |test| - [JobExecutionService] Thread-379 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution plan for light job ID=071a-659f-ae01-0001, jobName='071a-659f-ae01-0001', executionId=071a-659f-ae01-0001 initialized, will start the execution
09:22:34,975  INFO |test| - [StreamKafkaP] hz.awesome_torvalds.jet.blocking.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [071a-659f-ae01-0001/Kafka[public.o_05e834da_c0b8_4b55_b148_e7ae5a1667cc]#0] New partition(s) assigned: [o_05e834da_c0b8_4b55_b148_e7ae5a1667cc-0]
09:22:35,008  INFO || - [SlidingWindowP] hz.awesome_torvalds.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [071a-659f-ae01-0001/Sliding-Window-AccumulateByKey#1] Late event dropped. currentWatermark=Watermark{ts=00:00:00.010}, event=[Ljava.lang.Object;@56c2bd4c
09:22:35,008  INFO || - [SlidingWindowP] hz.awesome_torvalds.jet.cooperative.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] [071a-659f-ae01-0001/Sliding-Window-AccumulateByKey#1] Late event dropped. currentWatermark=Watermark{ts=00:00:00.010}, event=[Ljava.lang.Object;@d9101150
09:22:39,820 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:22:44,820 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:22:49,821 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:22:54,821 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:22:59,822 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:04,822 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:09,822 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:14,822 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:19,823 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:24,823 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:29,823 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:34,823 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:39,824 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:44,824 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:49,824 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:54,824 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:23:59,825 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:04,825 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:09,825 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:14,826 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:19,826 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:24,826 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:29,826 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:34,827 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:39,827 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:44,827 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:49,828 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:54,828 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:24:59,828 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:04,828 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:09,829 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:14,829 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:19,829 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:24,829 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:29,830 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:34,830 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:39,830 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:44,831 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:49,831 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:54,831 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:25:59,831 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:04,832 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:09,832 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:14,832 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:19,833 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:24,833 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:29,834 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:34,834 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:39,834 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:44,835 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:49,835 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:54,835 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:26:59,835 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:04,836 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:09,836 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:14,837 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:19,838 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:24,838 DEBUG |test| - [JobRepository] hz.awesome_torvalds.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:29,838 DEBUG || - [JobRepository] hz.awesome_torvalds.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Job cleanup took 0ms
09:27:34,819 DEBUG |test| - [AbstractJobProxy] Time-limited test - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Sending CANCEL_FORCEFUL request for job 071a-659f-ae01-0001 (name ??)
09:27:34,823 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Completed execution of job '071a-659f-ae01-0001', execution 071a-659f-ae01-0001
09:27:34,823 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-13 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] Execution of job '071a-659f-ae01-0001', execution 071a-659f-ae01-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:489) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:317) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:866) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: CANCEL_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:293) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:650) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:646) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.LightMasterContext.cancelInvocations(LightMasterContext.java:181) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.LightMasterContext.requestTermination(LightMasterContext.java:273) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.JobCoordinationService.terminateLightJob(JobCoordinationService.java:500) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.TerminateJobOperation.doRun(TerminateJobOperation.java:52) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:54) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.JobProxy.invokeOp(JobProxy.java:192) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.JobProxy.invokeTerminateJob(JobProxy.java:120) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.AbstractJobProxy.terminate(AbstractJobProxy.java:219) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.impl.AbstractJobProxy.cancel(AbstractJobProxy.java:193) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.core.JetTestSupport.ditchJob(JetTestSupport.java:413) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.jet.SimpleTestInClusterSupport.supportAfter(SimpleTestInClusterSupport.java:97) ~[hazelcast-5.1-SNAPSHOT-tests.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.AbstractHazelcastClassRunner$ThreadDumpAwareRunAfters.evaluate(AbstractHazelcastClassRunner.java:381) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.DumpBuildInfoOnFailureRule$1.evaluate(DumpBuildInfoOnFailureRule.java:37) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.jitter.JitterRule$1.evaluate(JitterRule.java:104) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.metrics.MetricsRule$1.evaluate(MetricsRule.java:62) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:50) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.HazelcastSerialClassRunner.runChild(HazelcastSerialClassRunner.java:29) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.2.jar:4.13.2]
	at com.hazelcast.test.AfterClassesStatement.evaluate(AfterClassesStatement.java:39) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at com.hazelcast.test.OverridePropertyRule$1.evaluate(OverridePropertyRule.java:66) ~[hazelcast-5.1-SNAPSHOT-tests.jar:5.1-SNAPSHOT]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299) ~[junit-4.13.2.jar:4.13.2]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293) ~[junit-4.13.2.jar:4.13.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	... 1 more
BuildInfo right after test(com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest): BuildInfo{version='5.1-SNAPSHOT', build='20211113', buildNumber=20211113, revision=d05be9e, enterprise=false, serializationVersion=1}
09:27:34,825 ERROR || - [EventServiceImpl] hz.awesome_torvalds.event-229 - [127.0.0.1]:5701 [dev] [5.1-SNAPSHOT] hz.awesome_torvalds.event-229 caught an exception while processing:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@bff2e53a
java.lang.UnsupportedOperationException: SQL catalog must never be cleared - MapEvent{entryEventType=CLEAR_ALL, member=Member [127.0.0.1]:5701 - 9a9ec652-10a9-4818-abb8-f17a3b9f8c7e this, name='__sql.catalog', numberOfEntriesAffected=1}
	at com.hazelcast.jet.sql.impl.schema.MappingStorage$EntryListenerAdapter.mapCleared(MappingStorage.java:160) ~[classes/:?]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapEventPublishingService.dispatchEvent(ReplicatedMapEventPublishingService.java:132) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.replicatedmap.impl.ReplicatedMapService.dispatchEvent(ReplicatedMapService.java:232) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:64) ~[hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:245) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
	at com.hazelcast.internal.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:228) [hazelcast-5.1-SNAPSHOT.jar:5.1-SNAPSHOT]
Hiccups measured while running test 'test(com.hazelcast.jet.sql.impl.connector.kafka.SqlKafkaAggregateTest):'
09:22:30, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:22:35, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:22:40, accumulated pauses: 38 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:22:45, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:22:50, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:22:55, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:00, accumulated pauses: 38 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:23:05, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:10, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:15, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:20, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:25, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:30, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:35, accumulated pauses: 47 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:23:40, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:45, accumulated pauses: 42 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:23:50, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:23:55, accumulated pauses: 132 ms, max pause: 94 ms, pauses over 1000 ms: 0
09:24:00, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:05, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:10, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:15, accumulated pauses: 40 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:20, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:25, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:30, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:35, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:40, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:45, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:50, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:24:55, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:00, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:05, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:10, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:15, accumulated pauses: 38 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:20, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:25, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:30, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:35, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:40, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:45, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:25:50, accumulated pauses: 44 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:25:55, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:00, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:05, accumulated pauses: 41 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:10, accumulated pauses: 47 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:26:15, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:20, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:25, accumulated pauses: 45 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:26:30, accumulated pauses: 62 ms, max pause: 3 ms, pauses over 1000 ms: 0
09:26:35, accumulated pauses: 49 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:40, accumulated pauses: 39 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:45, accumulated pauses: 42 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:50, accumulated pauses: 37 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:26:55, accumulated pauses: 44 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:27:00, accumulated pauses: 43 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:27:05, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:27:10, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:27:15, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
09:27:20, accumulated pauses: 36 ms, max pause: 2 ms, pauses over 1000 ms: 0
09:27:25, accumulated pauses: 38 ms, max pause: 1 ms, pauses over 1000 ms: 0
09:27:30, accumulated pauses: 46 ms, max pause: 0 ms, pauses over 1000 ms: 0


No metrics recorded during the test
```

</details>

### PR DESCRIPTION
**Pull request by Fly-Style**
Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

Also, fixes #19943

### CODE REVIEW

File: hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/generator/SqlStreamGeneratorTest.java [hunk 1]
```diff
@@ -38,35 +38,40 @@ public static void setUpClass() {
     @Test
     public void test_generateStream() {
         assertRowsEventuallyInAnyOrder(
```
Comment (viliam-durina) [inline hazelcast-sql/src/test/java/com/hazelcast/jet/sql/impl/connector/generator/SqlStreamGeneratorTest.java:40]: This is likely to fail intermittently if there's some hiccup. We could add a method that will ignore unexpected rows.

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java [hunk 2]
```diff
@@ -321,7 +331,6 @@ public Void visit(SqlIdentifier id) {
                             OrderedWindowFinder finder = new OrderedWindowFinder(validator, windowingFunctionFound);
                             SqlNode sqlNode = parseResult.getNode();
                             sqlNode.accept(finder);
-                            // TODO: [sasha] did it as quick idea impl late night, need more thinking about correctness
```
Comment (viliam-durina) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/validate/HazelcastSqlValidator.java:324]: I'd say we should remove this whole method. We can't do it correctly, so why bother... The query parsing here is frightening...

**Review by viliam-durina — APPROVED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/OptUtils.java [hunk 3]
```diff
@@ -446,4 +448,22 @@ private static int findKeyIndex(Table table) {
...
+     * Return true if the `expression` contains any input reference to a field
+     * with index in `indexes`.
+     */
+    public static boolean hasInputRef(RexNode expression, int... indexes) {
+        boolean[] res = {false};
+        expression.accept(new RexVisitorImpl<Void>(true) {
+            @Override
+            public Void visitInputRef(RexInputRef inputRef) {
+                if (arrayIndexOf(inputRef.getIndex(), indexes) >= 0) {
+                    res[0] = true;
```
Comment (ivanthescientist) [inline hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/OptUtils.java:462]: Any reason this has to be an array? Just checking.

**Review by ivanthescientist — APPROVED** [review]

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/OptUtils.java (hunk 3 above)
Comment (Fly-Style) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/opt/OptUtils.java:462]: @ivanthescientist outer variable should be effective final to be accessible within the anonymous class/lambda context

File: hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/aggregate/function/ImposeOrderFunction.java [hunk 4]
```diff
@@ -42,7 +42,7 @@
     };
 
     public ImposeOrderFunction() {
-        super("IMPOSE_ORDER", new WindowOperandMetadata(PARAMETERS), RETURN_TYPE_INFERENCE);
+        super("IMPOSE_ORDER", new WindowOperandMetadata(PARAMETERS, new int[]{2}), RETURN_TYPE_INFERENCE);
```
[the remark this answers is not in the document]
Comment (viliam-durina) [reply hazelcast-sql/src/main/java/com/hazelcast/jet/sql/impl/aggregate/function/ImposeOrderFunction.java:45]: The argument taking this value is documented...
