### PR TITLE
Set log level trace for MigrationCorrectnessTest

### LINKED ISSUE #18147: com.hazelcast.internal.partition.MigrationCorrectnessTest.testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]
Failed on http://jenkins.hazelcast.com/job/Hazelcast-pr-builder/3669/testReport/junit/com.hazelcast.internal.partition/MigrationCorrectnessTest/testPartitionData_whenBackupNodesTerminated_backups_3_nodes_4_fragmented_false_/

**Error Message**
```
On Member [127.0.0.1]:5705 - 96dc0d36-6762-40cb-a065-4ac30a11595e this, Partition 0 versions don't match: Partition {ID: 0, Version: 5} [
 0:[127.0.0.1]:5705 - 96dc0d36-6762-40cb-a065-4ac30a11595e
 1:[127.0.0.1]:5702 - f950a942-cca9-444d-bcc2-c5e3d18f4619
 2:[127.0.0.1]:5703 - e0b44608-7d69-47ac-bcf1-c3a32dd35ae3
 3:[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e
 4:[127.0.0.1]:5701 - 631baf0c-d96b-44c6-bc83-9a683c852bbd
] expected:<7> but was:<5>
```

**Stacktrace**
```
java.lang.AssertionError: 
On Member [127.0.0.1]:5705 - 96dc0d36-6762-40cb-a065-4ac30a11595e this, Partition 0 versions don't match: Partition {ID: 0, Version: 5} [
	0:[127.0.0.1]:5705 - 96dc0d36-6762-40cb-a065-4ac30a11595e
	1:[127.0.0.1]:5702 - f950a942-cca9-444d-bcc2-c5e3d18f4619
	2:[127.0.0.1]:5703 - e0b44608-7d69-47ac-bcf1-c3a32dd35ae3
	3:[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e
	4:[127.0.0.1]:5701 - 631baf0c-d96b-44c6-bc83-9a683c852bbd
] expected:<7> but was:<5>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionAssignments(PartitionCorrectnessTestSupport.java:205)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertPartitionAssignments(PartitionCorrectnessTestSupport.java:179)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndData(PartitionCorrectnessTestSupport.java:237)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.access$000(PartitionCorrectnessTestSupport.java:66)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport$AssertSizeAndDataTask.run(PartitionCorrectnessTestSupport.java:408)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1248)
	at com.hazelcast.test.HazelcastTestSupport.assertTrueEventually(HazelcastTestSupport.java:1350)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:225)
	at com.hazelcast.internal.partition.PartitionCorrectnessTestSupport.assertSizeAndDataEventually(PartitionCorrectnessTestSupport.java:221)
	at com.hazelcast.internal.partition.AbstractMigrationCorrectnessTest.testPartitionData_whenBackupNodesTerminated(AbstractMigrationCorrectnessTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:114)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:106)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```
**Standard Output**
```
Finished Running Test: testPartitionData_whenBackupNodesStartedTerminated[backups:3,nodes:4,fragmented:false] in 21.257 seconds.
07:17:34,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-2 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:17:49,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-8 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:18:04,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-7 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:18:19,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-3 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:18:34,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-11 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:18:49,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-10 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:19:04,644  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [InternalPartitionService] hz.suspicious_solomon.cached.thread-11 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Remaining migration tasks: 2. (repartitionTime=Thu Jan 01 00:00:00 UTC 1970, plannedMigrations=0, completedMigrations=0, remainingMigrations=0, totalCompletedMigrations=0, elapsedMigrationOperationTime=0ms, totalElapsedMigrationOperationTime=0ms, elapsedDestinationCommitTime=0ms, totalElapsedDestinationCommitTime=0ms, elapsedMigrationTime=0ms, totalElapsedMigrationTime=0ms)
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5703 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTTING_DOWN
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5703 [dev] [4.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5703 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5703 is SHUTDOWN
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5702 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTTING_DOWN
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5702 [dev] [4.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5702 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5702 is SHUTDOWN
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5705 is SHUTTING_DOWN
07:19:07,221  WARN |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] Terminating forcefully...
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] Shutting down connection manager...
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [MockServer] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5705, connection: MockConnection{localEndpoint=[127.0.0.1]:5701, remoteEndpoint=[127.0.0.1]:5705, alive=false}
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [MockServer] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] Removed connection to endpoint: [127.0.0.1]:5701, connection: MockConnection{localEndpoint=[127.0.0.1]:5705, remoteEndpoint=[127.0.0.1]:5701, alive=false}
07:19:07,221  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [MembershipManager] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Removing Member [127.0.0.1]:5705 - 96dc0d36-6762-40cb-a065-4ac30a11595e
07:19:07,222  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [ClusterService] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] 

Members {size:1, ver:9} [
	Member [127.0.0.1]:5701 - 631baf0c-d96b-44c6-bc83-9a683c852bbd this
]

07:19:07,222  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [TransactionManagerService] hz.suspicious_solomon.cached.thread-5 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Committing/rolling-back live transactions of [127.0.0.1]:5705, UUID: 96dc0d36-6762-40cb-a065-4ac30a11595e
07:19:07,222  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] Shutting down node engine...
07:19:07,225  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [NodeExtension] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] Destroying node NodeExtension.
07:19:07,225  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5705 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5705 is SHUTDOWN
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5704 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5704 is SHUTTING_DOWN
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5704 [dev] [4.2-SNAPSHOT] Node is already shutting down... Waiting for shutdown process to complete...
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5704 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5704 is SHUTDOWN
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTTING_DOWN
07:19:07,226  WARN |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Terminating forcefully...
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Shutting down connection manager...
07:19:07,226  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Shutting down node engine...
07:19:07,228  WARN |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [MigrationManager] hz.suspicious_solomon.migration - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Promotion commit failed for [MigrationInfo{uuid=36f2f489-fa66-4ba8-98ad-ec0055b3b4d6, partitionId=2, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=843ae05f-0878-41cc-b757-a08d3d8ef09c, partitionId=6, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=ae0daa60-468b-4921-b68a-abc92caffdfc, partitionId=16, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=9b55be92-bb85-471e-84c8-58bd95b7e818, partitionId=18, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=2, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=e1aa0ff7-972a-4271-acb6-303d6f04cbbd, partitionId=34, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=048ea3e0-db3e-40f3-b152-7c0c1e593283, partitionId=69, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=2, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=9cf06be1-15c3-44b8-b1e2-c7422f847560, partitionId=75, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=13c75f19-7015-4a7b-8501-259dc50f3169, partitionId=81, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=ec2d3f8e-d7e4-432c-b49b-ff65e81f423b, partitionId=85, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=131bd100-a9b3-414f-9a4f-17532cdfbe66, partitionId=89, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=2, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=4cbbf829-f187-4c61-ab2f-2bcb1276c911, partitionId=102, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}, MigrationInfo{uuid=03063dd7-0217-4e82-854e-de2dc8a13c88, partitionId=105, source=null, sourceCurrentReplicaIndex=-1, sourceNewReplicaIndex=-1, destination=[127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e, destinationCurrentReplicaIndex=1, destinationNewReplicaIndex=0, master=[127.0.0.1]:5701, initialPartitionVersion=7, partitionVersionIncrement=2, status=SUCCESS}] since destination [127.0.0.1]:5704 - 5752e916-a663-48a0-a37c-122d935e565e left the cluster
07:19:07,229  WARN |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [MigrationManager] hz.suspicious_solomon.migration - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Cannot commit promotions. Destination [127.0.0.1]:5705 - 96dc0d36-6762-40cb-a065-4ac30a11595e is not a member anymore
07:19:07,230  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [NodeExtension] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Destroying node NodeExtension.
07:19:07,230  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [Node] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] Hazelcast Shutdown is completed in 4 ms.
07:19:07,230  INFO |testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false]| - [LifecycleService] Thread-486 - [127.0.0.1]:5701 [dev] [4.2-SNAPSHOT] [127.0.0.1]:5701 is SHUTDOWN
BuildInfo right after testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false](com.hazelcast.internal.partition.MigrationCorrectnessTest): BuildInfo{version='4.2-SNAPSHOT', build='20210204', buildNumber=20210204, revision=400db9e, enterprise=false, serializationVersion=1}
Hiccups measured while running test 'testPartitionData_whenBackupNodesTerminated[backups:3,nodes:4,fragmented:false](com.hazelcast.internal.partition.MigrationCorrectnessTest):'
07:17:00, accumulated pauses: 511 ms, max pause: 38 ms, pauses over 1000 ms: 0
07:17:05, accumulated pauses: 58 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:17:10, accumulated pauses: 69 ms, max pause: 8 ms, pauses over 1000 ms: 0
07:17:15, accumulated pauses: 401 ms, max pause: 49 ms, pauses over 1000 ms: 0
07:17:20, accumulated pauses: 250 ms, max pause: 39 ms, pauses over 1000 ms: 0
07:17:25, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:17:30, accumulated pauses: 190 ms, max pause: 39 ms, pauses over 1000 ms: 0
07:17:35, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:17:40, accumulated pauses: 58 ms, max pause: 15 ms, pauses over 1000 ms: 0
07:17:45, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
07:17:50, accumulated pauses: 70 ms, max pause: 14 ms, pauses over 1000 ms: 0
07:17:55, accumulated pauses: 29 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:18:00, accumulated pauses: 35 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:18:05, accumulated pauses: 57 ms, max pause: 15 ms, pauses over 1000 ms: 0
07:18:10, accumulated pauses: 45 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:18:15, accumulated pauses: 47 ms, max pause: 17 ms, pauses over 1000 ms: 0
07:18:20, accumulated pauses: 172 ms, max pause: 32 ms, pauses over 1000 ms: 0
07:18:25, accumulated pauses: 238 ms, max pause: 36 ms, pauses over 1000 ms: 0
07:18:30, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
07:18:35, accumulated pauses: 45 ms, max pause: 6 ms, pauses over 1000 ms: 0
07:18:40, accumulated pauses: 45 ms, max pause: 9 ms, pauses over 1000 ms: 0
07:18:45, accumulated pauses: 1386 ms, max pause: 61 ms, pauses over 1000 ms: 0
07:18:50, accumulated pauses: 2785 ms, max pause: 64 ms, pauses over 1000 ms: 0
07:18:55, accumulated pauses: 1361 ms, max pause: 66 ms, pauses over 1000 ms: 0
07:19:00, accumulated pauses: 83 ms, max pause: 10 ms, pauses over 1000 ms: 0
07:19:05, accumulated pauses: 152 ms, max pause: 135 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by alex-dukhno**
Related to #18147

This PR:
* set log level TRACE for MigrationCorrectnessTest
* removes `partitionId` field from `InternalPartitionImpl` as the same field exists in `AbstractInternalPartition` super class
* use diamond operator
* replace anonymous classes with lambdas in tests

### CODE REVIEW

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/test/java/com/hazelcast/internal/partition/MigrationCorrectnessTest.java [hunk 1]
```diff
@@ -36,6 +38,9 @@
 // related issue https://github.com/hazelcast/hazelcast/issues/5444
 public class MigrationCorrectnessTest extends AbstractMigrationCorrectnessTest {
 
+    @ClassRule
+    public static ChangeLoggingRule changeLoggingRule = new ChangeLoggingRule("log4j2-debug-migrations.xml");
```
Comment (ufukyilmaz) [inline hazelcast/src/test/java/com/hazelcast/internal/partition/MigrationCorrectnessTest.java:42]: You can change the name of this file from `log4j2-debug-migrations.xml` to `log4j2-trace-migrations.xml`

**Review by ufukyilmaz — APPROVED** [review]
I only have a minor comment on the xml filename. Everything looks good to me except that.
