### PR TITLE
Fix job restart before StartExecutionOp

### LINKED ISSUE #18860: com.hazelcast.jet.core.ExecutionLifecycleTest.test_jobStatusCompleting[useLightJob=false]
_master_ (commit e4a88ac86dc2172763fc8691b0501f426df2a791)

Failed on ZuluJDK11: http://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-master-ZuluJDK11/137/testReport/com.hazelcast.jet.core/ExecutionLifecycleTest/test_jobStatusCompleting_useLightJob_false_/

Stacktrace:
```
org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.base@11.0.8/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@11.0.8/java.util.concurrent.locks.LockSupport.park(LockSupport.java:323)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.manageParking(AbstractInvocationFuture.java:693)
	at app//com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:615)
	at app//com.hazelcast.jet.impl.JobProxy.getStatus0(JobProxy.java:69)
	at app//com.hazelcast.jet.impl.AbstractJobProxy.getStatus(AbstractJobProxy.java:181)
	at app//com.hazelcast.jet.core.ExecutionLifecycleTest.test_jobStatusCompleting(ExecutionLifecycleTest.java:671)
	at java.base@11.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.8/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at app//com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base@11.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.8/java.lang.Thread.run(Thread.java:834)
```

Standard output:
```
22:39:54,676  INFO || - [JobCoordinationService] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Starting job 064f-b0e5-809f-0001 based on submit request
22:39:54,677  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001
22:39:54,677  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,677 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001
22:39:54,677 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001
22:39:54,678 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccb-0001 from [127.0.0.1]:5701
22:39:54,678 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccb-0001 from [127.0.0.1]:5701
22:39:54,678  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccb-0001 initialized
22:39:54,678  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccb-0001 initialized
22:39:54,678 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Init of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 was successful
22:39:54,678 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001
22:39:54,678 DEBUG |test_jobStatusCompleting[useLightJob=false]| - [Job] test_jobStatusCompleting - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 064f-b0e5-809f-0001 (name ??)
22:39:54,678  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 from coordinator [127.0.0.1]:5701
22:39:54,678  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 from coordinator [127.0.0.1]:5701
22:39:54,679 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001
22:39:54,679 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-15 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001
22:39:54,679 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-15 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,679 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:284) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:267) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$16(MasterJobContext.java:591) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,679 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,679 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,680 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccb-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
22:39:54,680  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001
22:39:54,680  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,680 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001
22:39:54,680 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001
22:39:54,680 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccc-0001 from [127.0.0.1]:5701
22:39:54,680 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccc-0001 from [127.0.0.1]:5701
22:39:54,681  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccc-0001 initialized
22:39:54,681  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccc-0001 initialized
22:39:54,681 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Init of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 was successful
22:39:54,681 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001
22:39:54,681  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 from coordinator [127.0.0.1]:5701
22:39:54,681  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 from coordinator [127.0.0.1]:5701
22:39:54,681 DEBUG |test_jobStatusCompleting[useLightJob=false]| - [Job] test_jobStatusCompleting - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 064f-b0e5-809f-0001 (name ??)
22:39:54,682 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001
22:39:54,682 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001
22:39:54,682 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,682 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:284) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:267) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$16(MasterJobContext.java:591) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,682 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,682 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,682 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccc-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
22:39:54,683  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001
22:39:54,683  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,683 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001
22:39:54,683 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001
22:39:54,683 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccd-0001 from [127.0.0.1]:5701
22:39:54,683 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccd-0001 from [127.0.0.1]:5701
22:39:54,684  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccd-0001 initialized
22:39:54,684  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccd-0001 initialized
22:39:54,684 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Init of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 was successful
22:39:54,684 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001
22:39:54,684 DEBUG |test_jobStatusCompleting[useLightJob=false]| - [Job] test_jobStatusCompleting - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 064f-b0e5-809f-0001 (name ??)
22:39:54,684  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 from coordinator [127.0.0.1]:5701
22:39:54,684  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 from coordinator [127.0.0.1]:5701
22:39:54,685 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001
22:39:54,685 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001
22:39:54,685 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,685 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:284) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:267) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$16(MasterJobContext.java:591) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,685 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,685 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,685 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bccd-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
22:39:54,686  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001
22:39:54,686  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,686 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001
22:39:54,686 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001
22:39:54,686 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bcce-0001 from [127.0.0.1]:5701
22:39:54,686 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bcce-0001 from [127.0.0.1]:5701
22:39:54,687  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bcce-0001 initialized
22:39:54,687  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bcce-0001 initialized
22:39:54,687 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Init of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 was successful
22:39:54,687 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001
22:39:54,687 DEBUG |test_jobStatusCompleting[useLightJob=false]| - [Job] test_jobStatusCompleting - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 064f-b0e5-809f-0001 (name ??)
22:39:54,687  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 from coordinator [127.0.0.1]:5701
22:39:54,687  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 from coordinator [127.0.0.1]:5701
22:39:54,687 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001
22:39:54,687 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001
22:39:54,687 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,687 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:284) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:267) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$16(MasterJobContext.java:591) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,688 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-25 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,688 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,688 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0e8-bcce-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
22:39:54,689  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccf-0001
22:39:54,689  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0e8-bccf-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,689 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccf-0001
22:39:54,689 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0e8-bccf-0001
22:39:54,689 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccf-0001 from [127.0.0.1]:5701
22:39:54,689 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0e8-bccf-0001 from [127.0.0.1]:5701
22:39:54,689  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccf-0001 initialized
22:39:54,689  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0e8-bccf-0001 initialized
22:39:54,690 DE
...[truncated 1320151 chars]...
~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,966 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85d9-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,966 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-21 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85d9-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,966 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-21 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85d9-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
22:39:54,967  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001
22:39:54,967  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,967 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001
22:39:54,967 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001
22:39:54,967 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0ec-85da-0001 from [127.0.0.1]:5701
22:39:54,967 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0ec-85da-0001 from [127.0.0.1]:5701
22:39:54,967  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0ec-85da-0001 initialized
22:39:54,967  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0ec-85da-0001 initialized
22:39:54,967 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Init of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 was successful
22:39:54,967 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Executing job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001
22:39:54,967  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 from coordinator [127.0.0.1]:5701
22:39:54,967  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Start execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 from coordinator [127.0.0.1]:5701
22:39:54,967 DEBUG |test_jobStatusCompleting[useLightJob=false]| - [Job] test_jobStatusCompleting - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 064f-b0e5-809f-0001 (name ??)
22:39:54,968 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-21 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001
22:39:54,968 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001
22:39:54,968 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-21 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,968 DEBUG || - [JobExecutionService] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 completed with failure
java.util.concurrent.CompletionException: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at com.hazelcast.jet.impl.util.NonCompletableFuture.internalCompleteExceptionally(NonCompletableFuture.java:72) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$ExecutionTracker.taskletDone(TaskletExecutionService.java:486) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.dismissTasklet(TaskletExecutionService.java:417) ~[classes/:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.runTasklet(TaskletExecutionService.java:403) ~[classes/:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$CooperativeWorker.run(TaskletExecutionService.java:353) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
	at com.hazelcast.jet.impl.execution.ExecutionContext.terminateExecution(ExecutionContext.java:283) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution0(JobExecutionService.java:623) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.terminateExecution(JobExecutionService.java:619) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.TerminateExecutionOperation.run(TerminateExecutionOperation.java:58) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:284) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:267) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$cancelExecutionInvocations$16(MasterJobContext.java:591) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[classes/:?]
22:39:54,968 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,968 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL
22:39:54,968 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85da-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL, [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.JobTerminateRequestedException: RESTART_FORCEFUL]
22:39:54,969  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Didn't find any snapshot to restore for job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001
22:39:54,969  INFO || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Start executing job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001, execution graph in DOT format:
digraph DAG {
	"v" [localParallelism=2];
}
HINT: You can use graphviz or http://viz-js.com to visualize the printed graph.
22:39:54,969 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Building execution plan for job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001
22:39:54,969 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Built execution plans for job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001
22:39:54,969 DEBUG || - [InitExecutionOperation] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 from [127.0.0.1]:5701
22:39:54,969 DEBUG || - [InitExecutionOperation] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Initializing execution plan for job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 from [127.0.0.1]:5701
22:39:54,970  INFO || - [JobExecutionService] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0ec-85db-0001 initialized
22:39:54,970  INFO || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Execution plan for jobId=064f-b0e5-809f-0001, jobName='064f-b0e5-809f-0001', executionId=064f-b0ec-85db-0001 initialized
22:39:54,970 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Init of job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 was successful
22:39:54,970 DEBUG || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Executing job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001
22:39:54,970 DEBUG |test_jobStatusCompleting[useLightJob=false]| - [Job] test_jobStatusCompleting - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Sending RESTART_GRACEFUL request for job 064f-b0e5-809f-0001 (name ??)
22:39:54,970 DEBUG || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 calling completeExecution because execution terminated before it started
22:39:54,970 DEBUG || - [JobExecutionService] hz.sweet_wozniak.async.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 calling completeExecution because execution terminated before it started
22:39:54,970 DEBUG || - [JobExecutionService] hz.clever_wozniak.generic-operation.thread-1 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001
22:39:54,970 DEBUG || - [JobExecutionService] hz.sweet_wozniak.async.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Completed execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001
22:39:54,970 ERROR || - [StartExecutionOperation] hz.clever_wozniak.generic-operation.thread-0 - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:438) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:483) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:50) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:53) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) [classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) [classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
22:39:54,970 ERROR || - [StartExecutionOperation] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:438) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:483) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:50) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:53) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:213) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.run(OperationExecutorImpl.java:411) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl.runOrExecute(OperationExecutorImpl.java:438) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvokeLocal(Invocation.java:600) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.doInvoke(Invocation.java:579) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke0(Invocation.java:540) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.Invocation.invoke(Invocation.java:240) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.InvocationBuilderImpl.invoke(InvocationBuilderImpl.java:59) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipant(MasterContext.java:284) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterContext.invokeOnParticipants(MasterContext.java:267) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.invokeStartExecution(MasterJobContext.java:464) ~[classes/:?]
	at com.hazelcast.jet.impl.MasterJobContext.lambda$onInitStepCompleted$4(MasterJobContext.java:433) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$49(JobCoordinationService.java:1137) ~[classes/:?]
	at com.hazelcast.jet.impl.JobCoordinationService.lambda$submitToCoordinatorThread$50(JobCoordinationService.java:1158) ~[classes/:?]
	at com.hazelcast.internal.util.executor.CompletableFutureTask.run(CompletableFutureTask.java:64) [classes/:?]
	at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217) [classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
22:39:54,970 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 received response to StartExecutionOperation from [127.0.0.1]:5701: com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
22:39:54,971 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 received response to StartExecutionOperation from [127.0.0.1]:5702: com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
22:39:54,971 DEBUG || - [MasterJobContext] ForkJoinPool.commonPool-worker-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 has failures: [[127.0.0.1]:5702=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation', [127.0.0.1]:5701=com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation']
22:39:54,971 ERROR || - [MasterJobContext] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Execution of job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 failed
	Start time: 2021-06-08T22:39:54.969
	Duration: 00:00:00.002
	To see additional job metrics enable JobConfig.storeMetricsAfterJobCompletion
com.hazelcast.jet.impl.exception.ExecutionNotFoundException: job 064f-b0e5-809f-0001, execution 064f-b0ec-85db-0001 not found for coordinator [127.0.0.1]:5701 for 'StartExecutionOperation'
	at com.hazelcast.jet.impl.JobExecutionService.assertExecutionContext(JobExecutionService.java:438) ~[classes/:?]
	at com.hazelcast.jet.impl.JobExecutionService.beginExecution(JobExecutionService.java:483) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.StartExecutionOperation.doRun(StartExecutionOperation.java:50) ~[classes/:?]
	at com.hazelcast.jet.impl.operation.AsyncOperation.run(AsyncOperation.java:53) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:272) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[classes/:?]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:469) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[classes/:?]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[classes/:?]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) [classes/:?]
22:39:54,972 DEBUG || - [JobCoordinationService] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] job '064f-b0e5-809f-0001', execution 064f-b0ec-85db-0001 is completed
22:39:57,796 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:39:57,796 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:02,797 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:02,797 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:07,799 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:07,799 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:12,800 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:12,800 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:17,801 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:17,801 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:22,802 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:22,802 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:27,599  INFO || - [HealthMonitor] hz.sweet_wozniak.HealthMonitor - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=97.1G, swap.space.total=4.0G, swap.space.free=2.9G, heap.memory.used=544.4M, heap.memory.free=3.5G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=13.29%, heap.memory.used/max=13.29%, minor.gc.count=142, minor.gc.time=3442ms, major.gc.count=2, major.gc.time=597ms, load.process=0.00%, load.system=81.25%, load.systemAverage=21.35, thread.count=208, thread.peakCount=1806, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=1, executor.q.priorityOperation.size=1, operations.completed.count=527597, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=1, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=2, connection.active.count=0, client.connection.count=0, connection.count=0
22:40:27,707  INFO || - [HealthMonitor] hz.clever_wozniak.HealthMonitor - [127.0.0.1]:5702 [dev] [5.0-SNAPSHOT] processors=8, physical.memory.total=377.6G, physical.memory.free=97.1G, swap.space.total=4.0G, swap.space.free=2.9G, heap.memory.used=560.4M, heap.memory.free=3.5G, heap.memory.total=4.0G, heap.memory.max=4.0G, heap.memory.used/total=13.67%, heap.memory.used/max=13.67%, minor.gc.count=142, minor.gc.time=3442ms, major.gc.count=2, major.gc.time=597ms, load.process=4.76%, load.system=85.71%, load.systemAverage=21.35, thread.count=208, thread.peakCount=1806, cluster.timeDiff=-1, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.client.query.size=0, executor.q.client.blocking.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=516477, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=2, connection.active.count=0, client.connection.count=0, connection.count=0
22:40:27,803 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:27,803 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:32,804 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:32,804 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:37,806 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:37,806 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:42,806 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:42,806 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:47,808 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:47,808 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:52,808 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:52,808 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:57,809 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:40:57,809 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:02,811 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:02,811 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:07,811 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:07,811 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:12,812 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:12,812 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:17,813 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:17,813 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:22,814 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:22,814 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:27,815 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:27,815 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:32,816 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:32,816 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:37,817 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:37,817 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:42,818 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:42,818 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:47,819 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:47,819 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:52,820 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:52,820 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:57,821 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:41:57,821 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:02,822 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-4 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:02,822 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:07,823 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:07,823 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:12,825 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 1ms
22:42:12,827 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 1ms
22:42:17,826 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:17,827 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:22,827 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:22,828 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:27,828 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:27,828 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:32,829 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:32,829 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:37,830 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:37,830 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:42,831 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:42,831 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:47,832 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:47,832 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:52,833 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:52,833 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:42:57,837 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 1ms
22:42:57,837 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-14 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 1ms
22:43:02,838 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:02,838 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:07,838 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:07,838 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:12,840 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:12,840 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-18 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:17,841 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:17,841 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:22,841 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-8 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:22,841 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:27,843 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:27,843 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:32,843 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:32,843 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:37,844 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:37,844 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-13 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:42,845 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:42,845 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:47,846 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:47,846 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:52,847 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:52,847 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-2 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:57,848 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:43:57,848 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-12 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:02,849 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:02,849 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:07,850 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-11 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:07,850 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:12,851 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:12,851 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-10 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:17,851 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:17,851 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:22,852 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:22,852 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-1 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:27,853 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-17 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:27,853 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:32,855 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:32,855 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-15 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:37,856 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-3 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:37,856 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-9 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:42,857 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-6 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:42,857 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-7 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:47,858 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-16 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:47,858 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-19 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:52,859 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-5 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:52,859 DEBUG || - [JobRepository] hz.sweet_wozniak.cached.thread-19 - [127.0.0.1]:5701 [dev] [5.0-SNAPSHOT] Job cleanup took 0ms
22:44:55,061  INFO |test_jobStatusCompleting[useLightJob=false]| - [SimpleTestInClusterSupport] Time-limited test - Ditching 10 jobs in SimpleTestInClusterSupport.@After: [064f-b0e5-809b-0001, 064f-b0e5-809a-0001, 064f-b0e5-8099-0001, 064f-b0e5-8098-0001, 064f-b0e5-809f-0001, 064f-b0e5-809e-0001, 064f-b0e5-809d-0001, 064f-b0e5-809c-0001, 064f-b0e5-8402-0002, 064f-b0e5-8097-0001]
22:44:55,062  INFO |test_jobStatusCompleting[useLightJob=false]| - [SimpleTestInClusterSupport] Time-limited test - Destroying 0 distributed objects in SimpleTestInClusterSupport.@After: []
BuildInfo right after test_jobStatusCompleting[useLightJob=false](com.hazelcast.jet.core.ExecutionLifecycleTest): BuildInfo{version='5.0-SNAPSHOT', build='20210608', buildNumber=20210608, revision=e4a88ac, enterprise=false, serializationVersion=1, jet=JetBuildInfo{version='5.0-SNAPSHOT', build='20210608', revision='e4a88ac'}}
Hiccups measured while running test 'test_jobStatusCompleting[useLightJob=false](com.hazelcast.jet.core.ExecutionLifecycleTest):'
22:39:50, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:39:55, accumulated pauses: 56 ms, max pause: 27 ms, pauses over 1000 ms: 0
22:40:00, accumulated pauses: 30 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:40:05, accumulated pauses: 48 ms, max pause: 22 ms, pauses over 1000 ms: 0
22:40:10, accumulated pauses: 48 ms, max pause: 16 ms, pauses over 1000 ms: 0
22:40:15, accumulated pauses: 25 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:40:20, accumulated pauses: 47 ms, max pause: 23 ms, pauses over 1000 ms: 0
22:40:25, accumulated pauses: 49 ms, max pause: 24 ms, pauses over 1000 ms: 0
22:40:30, accumulated pauses: 47 ms, max pause: 22 ms, pauses over 1000 ms: 0
22:40:35, accumulated pauses: 28 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:40:40, accumulated pauses: 58 ms, max pause: 22 ms, pauses over 1000 ms: 0
22:40:45, accumulated pauses: 47 ms, max pause: 20 ms, pauses over 1000 ms: 0
22:40:50, accumulated pauses: 43 ms, max pause: 15 ms, pauses over 1000 ms: 0
22:40:55, accumulated pauses: 44 ms, max pause: 14 ms, pauses over 1000 ms: 0
22:41:00, accumulated pauses: 58 ms, max pause: 28 ms, pauses over 1000 ms: 0
22:41:05, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:10, accumulated pauses: 48 ms, max pause: 20 ms, pauses over 1000 ms: 0
22:41:15, accumulated pauses: 45 ms, max pause: 16 ms, pauses over 1000 ms: 0
22:41:20, accumulated pauses: 43 ms, max pause: 15 ms, pauses over 1000 ms: 0
22:41:25, accumulated pauses: 34 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:41:30, accumulated pauses: 38 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:41:35, accumulated pauses: 37 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:41:40, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:45, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:41:50, accumulated pauses: 30 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:41:55, accumulated pauses: 39 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:42:00, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:10, accumulated pauses: 38 ms, max pause: 9 ms, pauses over 1000 ms: 0
22:42:15, accumulated pauses: 33 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:42:20, accumulated pauses: 32 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:42:25, accumulated pauses: 33 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:42:30, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:35, accumulated pauses: 26 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:42:40, accumulated pauses: 30 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:42:45, accumulated pauses: 33 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:42:50, accumulated pauses: 32 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:42:55, accumulated pauses: 30 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:00, accumulated pauses: 30 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:43:05, accumulated pauses: 27 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:10, accumulated pauses: 38 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:43:15, accumulated pauses: 39 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:43:20, accumulated pauses: 43 ms, max pause: 8 ms, pauses over 1000 ms: 0
22:43:25, accumulated pauses: 33 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:30, accumulated pauses: 38 ms, max pause: 5 ms, pauses over 1000 ms: 0
22:43:35, accumulated pauses: 34 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:43:40, accumulated pauses: 35 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:43:45, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:43:50, accumulated pauses: 35 ms, max pause: 1 ms, pauses over 1000 ms: 0
22:43:55, accumulated pauses: 32 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:44:00, accumulated pauses: 39 ms, max pause: 7 ms, pauses over 1000 ms: 0
22:44:05, accumulated pauses: 35 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:44:10, accumulated pauses: 36 ms, max pause: 3 ms, pauses over 1000 ms: 0
22:44:15, accumulated pauses: 34 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:44:20, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:44:25, accumulated pauses: 36 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:44:30, accumulated pauses: 37 ms, max pause: 4 ms, pauses over 1000 ms: 0
22:44:35, accumulated pauses: 31 ms, max pause: 0 ms, pauses over 1000 ms: 0
22:44:40, accumulated pauses: 38 ms, max pause: 2 ms, pauses over 1000 ms: 0
22:44:45, accumulated pauses: 41 ms, max pause: 8 ms, pauses over 1000 ms: 0
22:44:50, accumulated pauses: 406 ms, max pause: 373 ms, pauses over 1000 ms: 0
22:44:55, accumulated pauses: 0 ms, max pause: 0 ms, pauses over 1000 ms: 0
```

### PR DESCRIPTION
**Pull request by viliam-durina**
Fixes this scenario:
- master assigns jobStatus=RUNNING and sends the StartExecutionOp
- job restart is requested. Master sends the TerminateExecutionOp to
  members.
- the TerminateExecutionOp on member is handled before the
  StartExecutionOp. The execution is removed from the member
- now the StartExecutionOp is handled and (correctly) throws
  ExecutionNotFoundException
- the master receives the ExecutionNotFoundException and handled it as
  an unspecific exception and fails the job

The fix is to handle this exception as if JobTerminateRequestedException
was received.

The issue can be easily reproduced by inserting a 100ms sleep at the
beginning of `StartExecutionOperation.doRun()`.

Fixes #18860

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java [hunk 1]
```diff
@@ -582,6 +582,12 @@ private void onStartExecutionComplete(Throwable error, Collection<Entry<MemberIn
                     // have to use Async version, the future is completed inside a synchronized block
                     .whenCompleteAsync(withTryCatch(logger, (r, e) -> finalizeJob(finalError)));
         } else {
+            if (error instanceof ExecutionNotFoundException) {
+                // If the StartExecutionOperation didn't find the execution, it means that we must have cancelled it.
```
Comment (gurbuzali) [inline hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:586]: we rely on assertions to check if the job is cancelled

Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:586]: because I assume that every time this happens, the the termination of execution without a snapshot must have happened.

**Review by ufukyilmaz — APPROVED** [review]
It looks good to me.

File: hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java (hunk 1 above)
Comment (viliam-durina) [reply hazelcast/src/main/java/com/hazelcast/jet/impl/MasterJobContext.java:586]: I merged this PR without resolving this comment because the test failed another time in my PR. We can still discuss this when you're back.
