### PR TITLE
Fail fast when using IndexType#BITMAP on HD

### LINKED ISSUE #17032: IMap#addIndex should fail fast for IndexType#BITMAP on HD
seen during investigation of https://github.com/hazelcast/hazelcast-enterprise/issues/2937

### PR DESCRIPTION
**Pull request by ramizdundar**
Usage of bitmap index in HD memory fast fails now. Tests are here https://github.com/hazelcast/hazelcast-enterprise/pull/3922.

Fixes #17032

### CODE REVIEW

**Comment by vbekiaris** [comment]
@ramizdundar good job. One more thing to cover is to make sure that fail fast also applies when using a client-side `HazelcastInstance`.

**Comment by ramizdundar** [comment]
Ok, I will start this tomorrow (as soon as we open pr about IMap#iterable)

**Review by vbekiaris — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapAddIndexMessageTask.java [hunk 1]
```diff
@@ -77,6 +79,14 @@ public String getMethodName() {
 
     @Override
     public Object[] getParameters() {
-        return new Object[]{parameters.indexConfig};
+        return new Object[] {parameters.indexConfig};
+    }
+
+    @Override
+    protected void beforeProcess() {
+        if (nodeEngine.getConfig().getMapConfig(parameters.name).getInMemoryFormat() == InMemoryFormat.NATIVE
```
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapAddIndexMessageTask.java:87]: Should this check be placed at the operation (`AddIndexOperationFactory`) so that it also works for server side test?

Comment (ramizdundar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapAddIndexMessageTask.java:87]: Only client side uses `AddIndexOperationFactory`. Member side directly creates a new `AddIndexOperation`. So this check should be implemented inside `AddIndexOperation` if there will be only one. However overwriting `innerBeforeRun()` inside `AddIndexOperation` results in multiple exceptions(more than 500) in different threads. So it's not fast failing anymore.

Comment (ihsandemir) [reply hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapAddIndexMessageTask.java:87]: There is a check at constructor: https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/operation/AddIndexOperation.java#L52  And you may be able put this check into https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/query/impl/IndexUtils.java#L62 method.

Comment (ramizdundar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/protocol/task/map/MapAddIndexMessageTask.java:87]: Inside https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/query/impl/IndexUtils.java#L62 method, only accessible variables are mapName, IndexConfig and some unrelated static variables, hence it's not possible to get memory format. I need something like nodeEngine or recordStore or HazelcastInstance etc. Also inside the constructor only map name is initialized. Other variables are initialized in this https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/map/impl/operation/MapOperation.java#L80-L105 method. However this method is called for each partition so it's throwing exceptions for each partition even if we do the check immediately after we can access the memory type.

**Review by ihsandemir — APPROVED** [review]
