### PR TITLE
fixes #4516. Unhandled socket exception causes one of the ioselectors to...

### LINKED ISSUE #4516: [TEST-FAILURE] client.ClientRegressionTest timeout
```
Running com.hazelcast.client.ClientRegressionTest
Build timed out (after 90 minutes). Marking the build as aborted.
```

our 3.x-IbmJDK1.7 build timed out due to this test.
https://hazelcast-l337.ci.cloudbees.com/job/Hazelcast-3.x-IbmJDK1.7/450/console

### PR DESCRIPTION
**Pull request by sancar**
Unhandled socket exception causes one of the ioselectors to be closed eventough node is still running. Fixed with catching and logging the exception in WriteHandler.

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/AbstractIOSelector.java [hunk 1]
```diff
@@ -163,7 +163,7 @@ private void handleSelectionKeys() {
         }
     }
 
-    private void handleSelectionKeyFailure(final Throwable e) {
+    public void handleSelectionKeyFailure(final Throwable e) {
         String msg = "Selector exception at  " + getName() + ", cause= " + e.toString();
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/AbstractIOSelector.java]: Why don't you call getMessage?

**Comment by pveentjer** [comment]
Do you know which exception was thrown? I had a quick peek at your code and it seems to make sense.

File: hazelcast/src/main/java/com/hazelcast/nio/tcp/AbstractIOSelector.java (hunk 1 above)
Comment (sancar) [inline hazelcast/src/main/java/com/hazelcast/nio/tcp/AbstractIOSelector.java]: I did not write this line so I dont know.

**Comment by sancar** [comment]
This was the exception before fix. 

05:55:42,916  WARN [OutSelectorImpl] hz._hzInstance_58_dev.IO.thread-out-1 - [127.0.0.1]:5701 [dev] [3.5-SNAPSHOT] Unhandled exception in hz._hzInstance_58_dev.IO.thread-out-1
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:85)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:89)
	at com.hazelcast.nio.tcp.WriteHandler.unschedule(WriteHandler.java:169)
	at com.hazelcast.nio.tcp.WriteHandler.handle(WriteHandler.java:215)
	at com.hazelcast.nio.tcp.WriteHandler.run(WriteHandler.java:288)
	at com.hazelcast.nio.tcp.AbstractIOSelector.processSelectionQueue(AbstractIOSelector.java:105)
	at com.hazelcast.nio.tcp.AbstractIOSelector.run(AbstractIOSelector.java:114)

**Comment by sancar** [comment]
I added testIssue859And863 related failure report to #3796. And other failure seems to be recently fixed in here #4527.

**Comment by sancar** [comment]
verify

**Comment by mdogan** [comment]
seems good.
