### PR TITLE
Fix(Memory Leak): Remove FencedLockProxy upon FencedLock#destroy [HZ-3039]

### LINKED ISSUE #25344: Client and server memory leaks while destroying FencedLocks [HZ-3039]
The local `FencedLock` proxy object is not removed from `LockService#proxies` [map](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java#L57) while the `Lock#destroy()` called
 
Steps to reproduce:
```
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
        Hazelcast.newHazelcastInstance(config);
        Hazelcast.newHazelcastInstance(config);
        CPSubsystem cpSubsystem = instance.getCPSubsystem();

        for (int i = 0; i < 100; i++) {
            FencedLock lock = cpSubsystem.getLock("iLock_" + i);
            lock.lock();
            lock.unlock();
            lock.destroy();
        }
```
The `LockService#proxies` map contains 100 FencedLockProxy objects:

image

This behaviour causes memory leaks.

The same behaviour is also on the client side: the `ClientRaftProxyFactory#lockProxies` tracks all created `FencedLockProxy` and not remove from the map.

The same client-side `_lock_proxies` map can be found in the Python client https://github.com/hazelcast/hazelcast-python-client/blob/master/hazelcast/cp.py#L198

### PR DESCRIPTION
**Pull request by gbarnett-hz**
Removes the `FencedLockProxy` from `LockService.proxies` _after_ calling legacy semantics of `AbstractBlockingService#destroyRaftObject`. Previously the `FencedLockProxy` would be resident in `LockService.proxies` until the CP system was reset. 

Fixes #25344

Backport of: INSERT_LINK_TO_THE_ORIGINAL_PR_HERE

EE PR: INSERT_LINK_TO_THE_EE_PR_HERE

Breaking changes (list specific methods/types/messages):
* API
* client protocol format
* serialized form
* snapshot format

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible
- [ ] Send backports/forwardports if fix needs to be applied to past/future releases
- [ ] New public APIs have `@Nonnull/@Nullable` annotations
- [ ] New public APIs have `@since` tags in Javadoc

### CODE REVIEW

**Comment by gbarnett-hz** [comment]
@arodionov if you can take a look -- if it seems reasonable I will add some testing post-comments.

**Comment by arodionov** [comment]
Thanks for the PR, Granville.
But, I wonder if it makes sense to even try to remove destroyed proxy objects from the map.

Map with lock proxies created on the server side (if using Hazecast in an embedded mode) or on the client side.
I assume we have such maps only for Lock proxies because: the Lock and a proxy themselves are heavy objects, and the Lock best practice use case, is to try to reuse an existing Lock object.

When the same lock is used from several Hazelcast clients or embedded instances, it means that every client/instance will have a such proxy and this proxy will be added to the maps on each instance:
```
HazelcastInstance instance1 = Hazelcast.newHazelcastInstance(config);
HazelcastInstance instance2 = Hazelcast.newHazelcastInstance(config);
FencedLock lockInstance1 = instance.getCPSubsystem().getLock("iLock"); // iLock proxy added to proxies Map on lockInstance1
FencedLock lockInstance2 = instance.getCPSubsystem().getLock("iLock"); // iLock proxy added to proxies Map on lockInstance2
```

Therefore, if we decide to remove the destroyed lock from the proxy's map, it means that it can be removed only from the instance from which the "destroy" method was called. 
```
lockInstance1.destroy(); // iLock proxy removed only from proxies Map on lockInstance1
```
Other clients/instances will be unaware that the lock has been destroyed.

So, I am wondering, does it make sense to provide a "partial" cleaning at all?

**Comment by gbarnett-hz** [comment]
@arodionov I agree -- even with client changes you only ever cleanup the client that called the `destroy`. On the server though this will clean up the mapping that is maintained across all instances, so perhaps that's the only place it makes sense? 

I had a look at removing the lock proxy in the Python client -- it looks simple but I also had same thought w.r.t. only fixing the client that actually called the `destroy`.

**Comment by arodionov** [comment]
Yes, for the embedded mode (server-side) proxies, I think we can proceed with removing the proxy from the `proxies` map.
In that case, we have a `DestroyRaftObjectOp` that will be executed at all instances. So we can wipe the `proxies` map in a consistent way.

Please try to add some tests for the current PR.

**Comment by gbarnett-hz** [comment]
Cheers @arodionov  -- will take a look

File: hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java [hunk 1]
```diff
@@ -244,4 +244,12 @@ public void provideDynamicMetrics(MetricDescriptor descriptor, MetricsCollection
         }
     }
 
+    @Override
+    public boolean destroyRaftObject(CPGroupId groupId, String name) {
+        boolean result = super.destroyRaftObject(groupId, name);
+        name = withoutDefaultGroupName(name + "@" + groupId.getName());
+        FencedLockProxy proxy = proxies.get(name);
+        proxies.remove(name, proxy);
```
Comment (arodionov) [inline hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java:252]: Can we simply use `proxies.remove(name);`?

Comment (gbarnett-hz) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java:252]: I don't think so because `name` is not fully qualified, i.e. `myLock@myGroup`, so in that case (other than `default`) `name=myLock` but the key in `proxies` is actually `myLock@myGroup` hence the ugliness there.

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java:252]: Seems, that after
`name = withoutDefaultGroupName(name + "@" + groupId.getName());`
it becomes fully qualified.
Also `proxies` map is used for `proxies.get(name)` and for `proxies.remove(name, proxy)`.
So if you find the `FencedLockProxy` value by the key, it will be removed. And if you don't find the value, it means that there is no such key, and is nothing to remove.

Comment (gbarnett-hz) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java:252]: Hi @arodionov , I think I misunderstood the initial comment you made. What you just wrote echoes the current logic. 

The `name` passed as argument needs to be fully qualified, hence the bit you quoted -- the `...withoutDefaultGroupName(...)...`

> Also proxies map is used for proxies.get(name) and for proxies.remove(name, proxy).
> So if you find the FencedLockProxy value by the key, it will be removed. And if you don't find the value, it means that there is no such key, and is nothing to remove.

Correct. You could have a `null` check before calling the `remove` but it's surplus.

Logic looks good here unless I am misunderstanding something?

Comment (arodionov) [reply hazelcast/src/main/java/com/hazelcast/cp/internal/datastructures/lock/LockService.java:252]: I've slightly changed the code to eliminate the confusion between Lock's name and the fully qualified name, and created a Lock with the `UUID + "@myGroup"` name.

image
So, after the call of `withoutDefaultGroupName`, we have a fully qualified name of the lock. The key with the same name is in the `proxies` map.

image

File: hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java [hunk 2]
```diff
@@ -103,4 +109,46 @@ public void test_lockFailsAfterCPGroupDestroyed() throws ExecutionException, Int
...
+        try {
+        } finally {
+            myLock.unlock();
+        }
+        myLock.destroy();
+
+        assertTrueEventually(() -> {
+            LockService service = getNodeEngineImpl(instances[0]).getService(LockService.SERVICE_NAME);
+            ConcurrentMap<String, FencedLockProxy> proxies = ReflectionUtils.getFieldValueReflectively(service, "proxies");
+            assertFalse(proxies.containsKey(lockName));
```
Comment (arodionov) [inline hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java:127]: Since we can have confusion between Lock's name and Lock's fully qualified name, maybe it will be better to check that the `proxies` map is empty:
`assertEquals(0, proxies.size());`

File: hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java [hunk 3]
```diff
@@ -103,4 +109,46 @@ public void test_lockFailsAfterCPGroupDestroyed() throws ExecutionException, Int
 
         proxyInstance.getCPSubsystem().getLock(lock.getName());
     }
+
+    @Test(timeout = 60000)
```
Comment (arodionov) [inline hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java:113]: `assertTrueEventually` has a default timeout, so maybe the test timeout is redundant

File: hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java (hunk 2 above)
Comment (arodionov) [reply hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java]: Yes, I think it would be better to move this test to another test class (or a separate class) since it will also be executed during `FencedLockClientBasicTest` (no sense to run) and `FencedLockCompatibilityTest` (can fail).

Comment (gbarnett-hz) [reply hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockBasicTest.java]: Will move it.

**Review by arodionov — APPROVED** [review]
Looks good to me!
Thanks, Granville!

File: hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockProxyRemovalTest.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+        allMembersRemoveLockProxy(randomName() + "@mygroup");
+    }
+
+    private void allMembersRemoveLockProxy(String lockName) {
+        FencedLock myLockMember0 = instances[0].getCPSubsystem().getLock(lockName);
+        FencedLock myLockMember1 = instances[1].getCPSubsystem().getLock(lockName);
+        FencedLock myLockMember2 = instances[2].getCPSubsystem().getLock(lockName);
+
+        myLockMember0.lock();
+        try {
```
Comment (vbekiaris) [inline hazelcast/src/test/java/com/hazelcast/cp/internal/datastructures/lock/FencedLockProxyRemovalTest.java:63]: nit: I appreciate the try-finally style, but what is the point when there is no statement in the try block?

**Review by vbekiaris — APPROVED** [review]
thanks for the fix @gbarnett-hz
