### PR TITLE
Fixed wrong nextSeq when minimum read size is zero

### LINKED ISSUE #14185: com.hazelcast.ringbuffer.ReadResultSet#getNextSequenceToReadFrom returns always 0
com.hazelcast.ringbuffer.ReadResultSet#getNextSequenceToReadFrom returns always 0 when minSize is 0.

### PR DESCRIPTION
**Pull request by eminn**
Fixes #14185

### CODE REVIEW

File: hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReadOperation.java [hunk 1]
```diff
@@ -119,6 +119,7 @@ public boolean shouldWait() {
         if (minSize == 0) {
             if (!journal.isNextAvailableSequence(namespace, partitionId, sequence)) {
                 sequence = journal.readMany(namespace, partitionId, sequence, resultSet);
+                resultSet.setNextSequenceToReadFrom(sequence);
```
Comment (cangencer) [inline hazelcast/src/main/java/com/hazelcast/internal/journal/EventJournalReadOperation.java]: seems duplicate with lines 137-138, probably refactor to method?
