### PR TITLE
Remove InetSockedAddressCache From Client

### LINKED ISSUE #17062: Hazelcast Java client not resolving member address when trying to reconnect
Context: basic HZ setup in a docker environment : 1 server + 1 client, HZ configuration based on tcp-ip with network aliases (using docker service names that are resolved against docker internal DNS).
When HZ server restarts, docker reassigns a new IP address to the container but the client forever tries to reconnect to the old IP address without re-resolving the member name to obtain the new IP.

**Version used :** 3.12.7 (also tested on 4.0.1 : same issue)
**Cluster size :** single member
**Number of clients :** 1 Java client
**Java version :** 1.8 on client side / 11 on server side (Note : DNS network ttl cache is set to 0 everywhere)
**OS :** Host: CentOS with docker engine (Docker version 19.03.6). Client container with debian based image. Server container from public HZ image: Alpine Linux v3.8.
**Logs :** see below in the steps

**Steps to reproduce :**
Using Docker (docker-compose) :
Create a HZ single member cluster using the standard public image, with tcp-ip member configured with the Docker service alias names (https://hub.docker.com/r/hazelcast/hazelcast/)
Server configuration example :
```
            <tcp-ip enabled="true">
              <member-list>
                <member>hazelcast:5701</member>
              </member-list>
            </tcp-ip>
```
("hazelcast" here is the service name in docker-compose for the HZ server, it's just a standard network alias that gets resolved on the docker network)

Connect a Java client configured with cluster-members filled with the same Docker service alias name.
Client configuration example :
```
    <network>
        <cluster-members>
            <address>hazelcast:5701</address>
        </cluster-members>
    </network>
```
On server startup, HZ successfully starts up. Logs shows the member configured as:
```
hazelcast     | Members {size:1, ver:1} [
hazelcast     |      Member [hazelcast]:5701 - ed12db96-27b4-4f05-b99b-840799a6bebf this
hazelcast     | ]
```
On client startup, HZ resolves the IP address of the server and connects to the cluster:
```
hz-test-client              | 2020-06-08 12:25:44 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to cluster with name: hazelcast
hz-test-client              | 2020-06-08 12:25:44 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:25:44 INFO [hz.client_1.internal-3] com.hazelcast.client.connection.ClientConnectionManager.null hz.client_1 [hazelcast] [3.12.7] Setting ClientConnection{alive=true, connectionId=1, channel=NioChannel{/172.20.0.40:57827->hazelcast/172.20.0.39:5701}, remoteEndpoint=[hazelcast]:5701, lastReadTime=2020-06-08 12:25:44.343, lastWriteTime=2020-06-08 12:25:44.317, closedTime=never, connected server version=3.12.7} as owner with principal ClientPrincipal{uuid='cd0aefaa-df16-4699-88b5-a16e9f476c5d', ownerUuid='239fa3d4-8e13-4f3f-a11e-f3539db2a6fb'}
hz-test-client              | 2020-06-08 12:25:44 INFO [hz.client_1.internal-3] com.hazelcast.client.connection.ClientConnectionManager.null hz.client_1 [hazelcast] [3.12.7] Authenticated with server [hazelcast]:5701, server version:3.12.7 Local address: /172.20.0.40:57827
hz-test-client              | 2020-06-08 12:25:44 INFO [hz.client_1.event-5] com.hazelcast.client.spi.impl.ClientMembershipListener.null hz.client_1 [hazelcast] [3.12.7]
hz-test-client              |
hz-test-client              | Members [1] {
hz-test-client              |      Member [hazelcast]:5701 - 239fa3d4-8e13-4f3f-a11e-f3539db2a6fb
hz-test-client              | }
hz-test-client              |
hz-test-client              | 2020-06-08 12:25:44 INFO [hz.client_1.cluster-] com.hazelcast.core.LifecycleService.null hz.client_1 [hazelcast] [3.12.7] HazelcastClient 3.12.7 (20200430 - bf4b643) is CLIENT_CONNECTED
```
Everything works perfectly until you restart the HZ server service.
Note that on Docker, with the start/stop of a container, the IP address changes.
The client then looses the connection to the server and tries to reconnect.
But at this point the client will try to reconnect keeping the old IP address it found at startup time (although the JVM dns cache is set to 0).
In the logs, while the server is being restarted, I can see :
```
hz-test-client              | 2020-06-08 12:25:59 INFO [hz.hz.client_1.IO.thread-in-0] com.hazelcast.client.connection.nio.ClientConnection.null hz.client_1 [hazelcast] [3.12.7] ClientConnection{alive=false, connectionId=1, channel=NioChannel{/172.20.0.40:57827->hazelcast/172.20.0.39:5701}, remoteEndpoint=[hazelcast]:5701, lastReadTime=2020-06-08 12:25:59.755, lastWriteTime=2020-06-08 12:25:54.447, closedTime=2020-06-08 12:25:59.755, connected server version=3.12.7} closed. Reason: Connection closed by the other side
hz-test-client              | 2020-06-08 12:25:59 INFO [hz.hz.client_1.IO.thread-in-0] com.hazelcast.client.connection.ClientConnectionManager.null hz.client_1 [hazelcast] [3.12.7] Removed connection to endpoint: [hazelcast]:5701, connection: ClientConnection{alive=false, connectionId=1, channel=NioChannel{/172.20.0.40:57827->hazelcast/172.20.0.39:5701}, remoteEndpoint=[hazelcast]:5701, lastReadTime=2020-06-08 12:25:59.755, lastWriteTime=2020-06-08 12:25:54.447, closedTime=2020-06-08 12:25:59.755, connected server version=3.12.7}
hz-test-client              | 2020-06-08 12:25:59 INFO [hz.client_1.cluster-] com.hazelcast.core.LifecycleService.null hz.client_1 [hazelcast] [3.12.7] HazelcastClient 3.12.7 (20200430 - bf4b643) is CLIENT_DISCONNECTED
hz-test-client              | 2020-06-08 12:25:59 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to cluster with name: hazelcast
hz-test-client              | 2020-06-08 12:25:59 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:25:59 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address hazelcast/172.20.0.39:5701
hz-test-client              | 2020-06-08 12:25:59 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 1 of 2147483647.
hz-test-client              | 2020-06-08 12:26:05 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:26:10 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketTimeoutException
hz-test-client              | 2020-06-08 12:26:10 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 2 of 2147483647.
hz-test-client              | 2020-06-08 12:26:15 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:26:20 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketTimeoutException
hz-test-client              | 2020-06-08 12:26:20 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 3 of 2147483647.
hz-test-client              | 2020-06-08 12:26:25 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:26:30 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketTimeoutException
hz-test-client              | 2020-06-08 12:26:30 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 4 of 2147483647.
hz-test-client              | 2020-06-08 12:26:35 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:26:40 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketTimeoutException
hz-test-client              | 2020-06-08 12:26:40 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 5 of 2147483647.
hz-test-client              | 2020-06-08 12:26:45 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:26:49 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: No route to host to address hazelcast/172.20.0.39:5701
hz-test-client              | 2020-06-08 12:26:49 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 6 of 2147483647.
hz-test-client              | 2020-06-08 12:26:54 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:26:57 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: No route to host to address hazelcast/172.20.0.39:5701
hz-test-client              | 2020-06-08 12:26:57 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 7 of 2147483647.
hz-test-client              | 2020-06-08 12:27:03 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:27:06 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: No route to host to address hazelcast/172.20.0.39:5701
hz-test-client              | 2020-06-08 12:27:06 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 8 of 2147483647.
hz-test-client              | 2020-06-08 12:27:11 INFO [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Trying to connect to [hazelcast]:5701 as owner member
hz-test-client              | 2020-06-08 12:27:14 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Exception during initial connection to [hazelcast]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: No route to host to address hazelcast/172.20.0.39:5701
hz-test-client              | 2020-06-08 12:27:14 WARNING [hz.client_1.cluster-] com.hazelcast.client.connection.nio.ClusterConnectorService.null hz.client_1 [hazelcast] [3.12.7] Unable to get live cluster connection, retry in 5000 ms, attempt 9 of 2147483647.
```
but 172.20.0.39 is the old IP address of the hazelcast server, it has changed in docker since the restart and the client never attempts to resolve "hazelcast" again, leading to impossible reconnection.
It seems that when the client is executing its reconnection mechanism, it reuses the same connection object with the IP address resolved at startup time, but if it has changed since, it will never attempt to resolve the member address defined in the configuration again to reconnect.

I also tried the same thing with a 2 member cluster and it leads to the same errors.
On the server side whenever a member IP address changes, other members are capable of reconnecting to it automatically and see the address change, the issue is only present on the Java client side.
Tried with/without smart-routing but doesn't affect client behavior on this.
Tried with "hazelcast.diagnostics.enabled" on client side but didn't see anything more that would point me to a configuration issue or something onto which I can do anything.

Is this the expected behavior? 
Thanks for the feedback!

### PR DESCRIPTION
**Pull request by sancar**
InetSocketAddressCache was introduced in Blue/Green prd to make
a clear point where the failover takes place.
As long as fail over will not happen, the cache was not cleared.

A scenario that we can not support with the cache is as follows:
1. Members are configured via hostname.
2. When a member machine restarted the ip address that hostname
corresponds changes.
3. After this there could be several problems.
   a. A single member restarts in a multi member cluster.
   b. Whole cluster restarted.

In scenario a, the client can not connect to the single restarted
member ever. The operations that needs to go to that member fails
with exception constantly.

In scenario b, the client cannot connect to any of the members and
shutdown.

This fix aims to solve both problems so that client can continue
to work, while preserving the behaviours in Blue/Green case.

Since I could not find a way to test this with single machine no
test is provided. The tests are done in aws enviorenmenti with
multi member and CNAME changes.

Fixes #17062

### CODE REVIEW

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1493/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1493/Hazelcast-pr-builder-1493.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] COMPILATION ERROR : 
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:testCompile (default-testCompile) on project hazelcast: Compilation failure: Compilation failure: 
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/osgi/HazelcastOSGiIntegrationTest.java:[31,38] error: package org.ops4j.pax.url.maven.commons does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/osgi/HazelcastOSGiIntegrationTest.java:[31,38] error: package org.ops4j.pax.url.maven.commons does not exist
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/Hazelcast-pr-builder/hazelcast/src/test/java/com/hazelcast/internal/memory/impl/BaseMemoryAccessorTest.java:[28,15] Unsafe is internal proprietary API and may be removed in a future release
--------------------------
</details>
</pre>

**Comment by sancar** [comment]
run-lab-run

**Comment by hz-highfive** [comment]
The job `Hazelcast-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1499/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/Hazelcast-pr-builder/1499/Hazelcast-pr-builder-1499.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12:check (default) on project hazelcast: failed with 1 bugs and 0 errors -> [Help 1]
--------------------------
</details>
</pre>

**Comment by sancar** [comment]
run-lab-run

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 1]
```diff
@@ -824,18 +834,19 @@ private void handleSuccessfulAuth(TcpClientConnection connection, ClientAuthenti
                 logger.fine("Checking the cluster: " + newClusterId + ", current cluster: " + this.clusterId);
             }
 
-            boolean initialConnection = activeConnections.isEmpty();
-            boolean changedCluster = initialConnection && this.clusterId != null && !newClusterId.equals(this.clusterId);
-            if (changedCluster) {
+            boolean connectionsEmpty = activeConnections.isEmpty();
+            boolean clusterIdChanged = this.clusterId != null && !newClusterId.equals(this.clusterId);
+            if (clusterIdChanged) {
+                checkClientStateOnClusterIdChange(connection);
```
Comment (ihsandemir) [inline hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:840]: you can pass parameter `connectionsEmpty ` to this method.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 2]
```diff
@@ -586,6 +594,10 @@ TcpClientConnection getOrConnect(@Nonnull Address address) {
         }
     }
 
+    private Object getLockObject(InetSocketAddress inetSocketAddress) {
+        return mutexes[HashUtil.hashToIndex(inetSocketAddress.hashCode(), mutexes.length)];
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:598]: changing it with putIfAbsent

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java (hunk 1 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:840]: isEmpty is not an expensive call. I would rather leave it this way.

**Comment by ycordier-pro** [comment]
Hi @sancar :)
Thanks for this fix which will be included in V4.1 if I'm correct.
Is there any chance you'll be backporting this to any 3.X version ?
(I think the issue has been introduced in 3.12 with the new blue/green reconnection algorithm)

Thanks for your feedback and have a nice day !

**Comment by sancar** [comment]
@ycordier-pro It will not be a simple backport because 4.0 internals has changed, but I am optimistic. With some extra work, it should be possible.
This pr is in the verification process. So if we decide this is a verified fix, then I will take a look at if backport is possible. Keep following the thread, I will try to update as soon as I have spend more time on this.

**Comment by ycordier-pro** [comment]
Hello, just a quick dumb question : since this PR is not yet merged in the master branch, the 4.1-SNAPSHOT package does NOT include this fix, right ?
If I want to get it and test it, I need to rebuild HZ from the sancar:fix/removeIpCache/master branch, am I still right ?

**Comment by mmedenjak** [comment]
@ycordier-pro yes, you're right. It's not in SNAPSHOT so you have to build it yourself, but that shouldn't be too hard - just checkout the branch locally and run something like `mvn clean install -DskipTests` (make sure to skip tests since they will take hours to run probably).

**Comment by ycordier-pro** [comment]
Thanks @mmedenjak, I've been able to rebuild the jar and test the code from this PR, it seems to be OK and the network name gets now resolved again at each retry so that the client is able to reconnect to a member after a member/container restart (and IP change), so it looks perfect !

Now I have a subsequent question : in the Hazelcast client configuration, there is a parameter in the [connection-strategy/connection-retry](https://docs.hazelcast.org/docs/latest/manual/html-single/#configuring-client-connection-retry) which tells Hazelcast client how long it should continue to try to connect to the current cluster, namely "cluster-connect-timeout-millis" (20000ms by default).

If you have only 1 cluster, you may want that the client retry to connect infinitely (and does not SHUTDOWN after this time elapsed), and based on my tests there doesn't seem to be any value in this parameter for that case (let's say 0 or -1).
For the moment I have to put Long.MAX_VALUE (9223372036854775807ms) but that doesn't look clean IMHO.
Maybe I missed something in the client configuration settings...

**Comment by mdumandag** [comment]
@ycordier-pro Looking at the implementation (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/WaitStrategy.java#L57), it seems that there is no magic value that makes the client retry infinitely. For now, you have to set it to something high as you did

**Comment by ycordier-pro** [comment]
Hi everyone, is there any chance this PR will be merged soon 😅 ?

**Comment by Holmistr** [comment]
@ycordier-pro We're on it! So close! :D

**Comment by ucarak** [comment]
So as I understand, @ycordier-pro and @sancar this pull request will be fixed the problem : https://github.com/hazelcast/hazelcast/issues/17062#issue-634621779 that @ycordier-pro had defined, right? we have also the same scenario. It would be nice to have a fix for that :)

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 3]
```diff
@@ -571,18 +571,24 @@ TcpClientConnection getOrConnect(@Nonnull Address address) {
             return connection;
         }
 
-        synchronized (resolveAddress(address)) {
-            // this critical section is used for making a single connection
-            // attempt to the given address at a time.
-            connection = getConnection(address);
-            if (connection != null) {
+        InetSocketAddress inetSocketAddress = resolveAddress(address);
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:574]: I'm not sure about the speed at which these objects are created. 

The problem with creating (and destroying) objects with a potentially inflated monitor is that it can be a huge performance hog when doing GC. For example our initial future used the same approach; later we replaced it by lock support to get rid of this inflated monitor and performance increased and latencies became a lot better.

For such situations I would suggest using a striped lock.

Apart from that.. I see you are synchronizing while communicating with external systems. You create the connection, which needs to go through a 3 way handshake (and potentially a few extra steps due to TLS) and then you have authentication. Which is another set of remote steps.

If for whatever reason such a remote interaction stalls, this thread stalls and this can lead to serious problems in the system. 

I thin a bettter approach needs to be found than synchronization.

Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:574]: I had the striped lock approach in the first commit. See
https://github.com/hazelcast/hazelcast/pull/17239/commits/e9e36fca17a22c6a1e61e355a8d09acf6a93f402#r500794877
This comment was the reason I switched to putIfAbsent 
https://github.com/hazelcast/hazelcast/pull/17239#discussion_r470445160
Not sure which one is more important. Wdyt?

> I'm not sure about the speed at which these objects are created.

These objects will not be created on a stable cluster. They will be created when there is a disconnection, and the client tries to connect back. 

> Also, any other thread that hits the same address, could also block indefinitely.
About accessing remote under lock. All the remote invocations are given up with a timeout. It can block other threads but it will not block indefinitely.  

> I think a better approach needs to be found than synchronization.
I am open to suggestions.
We may allow opening connections concurrently and clean them up later when we detect they are not used. Seems more complicated to me.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 4]
```diff
@@ -571,18 +571,24 @@ TcpClientConnection getOrConnect(@Nonnull Address address) {
...
+        try {
+            Object mutex = ConcurrencyUtil.getOrPutIfAbsent(mutexes, inetSocketAddress, key -> new Object());
```
Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:576]: I'm thinking out loud.

What you could do is to create a CHM with address as key and a Future as value.

The future will either block if no value is set, or will return the correct connection.

You could add this future using e.g. a putIfAbcent. so that only 1 thread will wait for a connection and then set that value on the future.

Comment (pveentjer) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:576]: This way you prevent concurrent connection creations to the same address.

And you can use a CompletableFuture. Which also doesn't suffer from the monitor inflation problem.

And in theory a caller could timeut future.get with a timeout if needs to be.

Comment (pveentjer) [inline hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:576]: I had a closer look at the code and this is on the ConnectionManager. I don't see a problem if another thread blocks on acquring a concurrent connection. He can't do anything useful anyway since the method itself is blocking.

So using a lock isn't that much of a problem. 

I would be careful with using an intrinsic lock due to inflation/gc problems as I already indicated in my first comment. It will not immediately cause problems since connections will not be created and destroyed in a very high frequency. But eventuall you could still run into some GC issues.

**Comment by binchen-lin** [comment]
Hello, when will the pull request possibily be merged?

**Comment by Holmistr** [comment]
@binchen-lin @ucarak @ycordier-pro After a long discussion, we will need to postpone this fix a bit. It's not that trivial and it actually needs to be properly tested. The issue is that we in the final weeks of the 4.1 release and since this is not trivial, it creates a risk and we're not comfortable taking this risk this close to the release date.

However, we won't be postponing it by much and we plan to fix it in the very next patch release 4.1.1. That shouldn't be that far ahead, we're talking roughly about end of November.

**Comment by ycordier-pro** [comment]
Thanks @Holmistr for the feedback, I understood !
At this time I'm running with the client JAR rebuilt from this branch and things seem to work fine as of now.
Once 4.1.1 will be available I'll switch back to the public packages.

**Comment by binchen-lin** [comment]
> 
> 
> @binchen-lin @ucarak @ycordier-pro After a long discussion, we will need to postpone this fix a bit. It's not that trivial and it actually needs to be properly tested. The issue is that we in the final weeks of the 4.1 release and since this is not trivial, it creates a risk and we're not comfortable taking this risk this close to the release date.
> 
> However, we won't be postponing it by much and we plan to fix it in the very next patch release 4.1.1. That shouldn't be that far ahead, we're talking roughly about end of November.

Thanks for the information.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 5]
```diff
@@ -914,6 +911,30 @@ private TcpClientConnection onAuthenticated(TcpClientConnection connection,
         return connection;
     }
 
+    private void checkClientStateOnClusterIdChange(TcpClientConnection connection) {
+        if (activeConnections.isEmpty()) {
+            //We only have single connection established
```
Comment (puzpuzpuz) [inline hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:916]: nit: missing space (`//We` -> `// We`) here and in other comments below.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 6]
```diff
@@ -914,6 +911,30 @@ private TcpClientConnection onAuthenticated(TcpClientConnection connection,
...
+                if (switchingToNextCluster) {
+                    switchingToNextCluster = false;
+                } else {
+                    String reason = "Force to hard cluster switch";
+                    connection.close(reason, null);
+                    throw new ClientNotAllowedInClusterException(reason);
+                }
+            }
+        } else {
+            //If there are other connections that means we have a connection to wrong cluster.
```
Comment (puzpuzpuz) [inline hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:930]: What if there are other connections, but they're not yet closed by the `HeartbeatManager` (consider a situation when a cluster restarted fast enough)? Is it ok to close the connection in this case?

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 7]
```diff
@@ -876,18 +873,18 @@ private TcpClientConnection onAuthenticated(TcpClientConnection connection,
...
+                checkClientStateOnClusterIdChange(connection);
                 logger.warning("Switching from current cluster: " + this.clusterId + " to new cluster: " + newClusterId);
                 client.onClusterRestart();
             }
 
+            boolean connectionsEmpty = activeConnections.isEmpty();
             activeConnections.put(response.memberUuid, connection);
-
-            if (initialConnection) {
+            if (connectionsEmpty) {
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:885]: We can't. I want to check if the connections were empty before the current connection is put to active connections.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java [hunk 8]
```diff
@@ -914,6 +911,30 @@ private TcpClientConnection onAuthenticated(TcpClientConnection connection,
...
+    private void checkClientStateOnClusterIdChange(TcpClientConnection connection) {
+        if (activeConnections.isEmpty()) {
+            //We only have single connection established
+            if (failoverConfigProvided) {
+                //If failover is provided, and this single connection is established after failover logic kicks in
+                // (checked via `switchingToNextCluster`), then it is OK to continue. Otherwise, we force the failover logic
+                // to be used by throwing `ClientNotAllowedInClusterException`
+                if (switchingToNextCluster) {
+                    switchingToNextCluster = false;
+                } else {
```
[the remark this answers is not in the document]
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:923]: It is a behavior change, and it is actually a fix on the behavior. 

When this path is run there are two possibilities that happened in the cluster. 
1) There was a single cluster and it restarted. 
2) There were two clusters and the first one is closed. 

Note that there is no way for us to differentiate these two. In the second scenario, it could be the case that the same hostnames are used for both clusters and the user changed the hostname resolution before closing the first cluster. So even the addresses of the two clusters are the same for the client. 

There is no problem with the first case. And the behavior change for that looks unnecessary. But, it is an important fix for the second case. 
The problem of the second case is as follows. 
- Failover is configured. Now assume that two clusters have the same cluster name/credentials, meaning a client can switch between these two and will not notice any authentication failure. 
- First cluster has shutdown. 
- Also keep in mind that in failover config, users can provide different configurations for clusters.
- The client is will connect to the second cluster in the first attempt with the configuration of the first cluster. If we don't fail the connection, it will continue with the wrong configuration. We need to make sure that when failover config is provided, the client will remain connected to a cluster only if it is connected with the correct configuration.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (puzpuzpuz) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:885]: Yeah, my bad. Please ignore this comment.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java (hunk 6 above)
Comment (sancar) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:930]: Not sure if I understand the scenario correctly.  Let me try:
1. There were 2 members. 
2. The client is connected to the first one. 
3. While the client is trying to open the second connection, both members are restarted.
4. In this case we will close the connection to the second member first thinking that it is not part of the cluster we think we are in. 
5. The connection to the first cluster will be gone after that and we will initiate a reconnect to the cluster. 

Yes, you are right. It seems unfortunate that we close the connection to the second member at step 4. 
But there seems to be no way around this. It does not make sense to check if the connections on the active connections are closed or not. Because they can be closed right after we check them. 

Do you have a suggestion to avoid that?

Comment (puzpuzpuz) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:930]: Yes, that scenario describes the problem. It could be also slightly different, but with the same outcome:

1. There were 2 members.
2. The client is connected to both members.
3. Both members are restarted in slightly different time and `HeartbeatManager` detects that for the connection to the first one. Then the re-connect logic kicks in.
4. In this case we will close the connection to the first member thinking that it is not part of the cluster we think we are in.
5. After a while we're going to start re-connect procedure for the second member.

Do you find this scenario possible?

As for the ways to avoid it, both scenarios may be not that critical critical, since we're going to keep trying to re-connect to all members in `ConnectToAllClusterMembersTask`. So, for the very last re-connection attempt (i.e. when `activeConnections.isEmpty() == true`) we should be able to connect to the new cluster. WDYT?

**Review by puzpuzpuz — APPROVED** [review]

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java (hunk 6 above)
Comment (puzpuzpuz) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:930]: After further discussion we came to a conclusion that both described scenarios shouldn't be a problem as the client should recover and connect to all members eventually.

File: hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (mdumandag) [reply hazelcast/src/main/java/com/hazelcast/client/impl/connection/tcp/TcpClientConnectionManager.java:923]: I see the problem with the second scenario. That makes sense then

**Review by mdumandag — APPROVED** [review]

**Comment by Holmistr** [comment]
@binchen-lin @ucarak @ycordier-pro As promised, the fix is not merged. This PR (https://github.com/hazelcast/hazelcast/pull/17911) is the backport to 4.1.1 which will be released soon.

**Comment by ycordier-pro** [comment]
Thanks for the work & merge, I'll get 4.1.1 as soon as it is released !!
Have a nice day all !

**Comment by mmedenjak** [comment]
@binchen-lin @ucarak @ycordier-pro has been released so feel free to try it out.

**Comment by ucarak** [comment]
Thanks to all
