### PR TITLE
Increase Kafka timeouts in WriteKafkaPTest

### LINKED ISSUE #21792: com.hazelcast.jet.kafka.impl.WriteKafkaPTest.stressTest_forceful_exOnce [HZ-1818]
_5.1.z_ (commit a56e6d5c44eb85926b346588d1d9cc28ef5cc85c)

Failed on Openj9-11: https://jenkins.hazelcast.com/view/Official%20Builds/job/Hazelcast-5.maintenance-Openj9-11/43/testReport/com.hazelcast.jet.kafka.impl/WriteKafkaPTest/stressTest_forceful_exOnce/

<details><summary>Stacktrace:</summary>

```
org.junit.ComparisonFailure: 
expected:<...=1
767=1
768=1
769=1[
770=1
771=1
772=1
773=1
774=1
775=1
776=1
777=1
778=1
779=1
780=1
781=1
782=1
783=1
784=1
785=1
786=1
787=1
788=1
789=1
790=1
791=1
792=1
793=1
794=1
795=1
796=1
797=1
798=1
799=1
800=1
801=1
802=1
803=1
804=1
805=1
806=1
807=1
808=1
809=1
810=1
811=1
812=1
813=1
814=1
815=1
816=1
817=1
818=1
819=1
820=1
821=1
822=1
823=1
824=1
825=1
826=1
827=1
828=1
829=1
830=1
831=1
832=1
833=1
834=1
835=1
836=1
837=1
838=1
839=1
840=1
841=1
842=1
843=1
844=1
845=1
846=1
847=1
848=1
849=1
850=1
851=1
852=1
853=1
854=1
855=1
856=1
857=1
858=1
859=1
860=1
861=1
862=1
863=1
864=1
865=1
866=1
867=1
868=1
869=1
870=1
871=1
872=1
873=1
874=1
875=1
876=1
877=1
878=1
879=1
880=1
881=1
882=1
883=1
884=1
885=1
886=1
887=1
888=1
889=1
890=1
891=1
892=1
893=1
894=1
895=1
896=1
897=1
898=1
899=1
900=1
901=1
902=1
903=1
904=1
905=1
906=1
907=1
908=1
909=1
910=1
911=1
912=1
913=1
914=1
915=1
916=1
917=1
918=1
919=1
920=1
921=1
922=1
923=1
924=1
925=1
926=1
927=1
928=1
929=1
930=1
931=1
932=1
933=1
934=1
935=1
936=1
937=1
938=1
939=1
940=1
941=1
942=1
943=1
944=1
945=1
946=1
947=1
948=1
949=1
950=1
951=1
952=1
953=1
954=1
955=1
956=1
957=1
958=1
959=1
960=1
961=1
962=1
963=1
964=1
965=1
966=1
967=1
968=1
969=1
970=1
971=1
972=1
973=1
974=1
975=1
976=1
977=1
978=1
979=1
980=1
981=1
982=1
983=1
984=1
985=1
986=1
987=1
988=1
989=1
990=1
991=1
992=1
993=1
994=1
995=1
996=1
997=1
998=1
999=1]> but was:<...=1
767=1
768=1
769=1[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.hazelcast.jet.impl.connector.SinkStressTestUtil.test_withRestarts(SinkStressTestUtil.java:114)
	at com.hazelcast.jet.kafka.impl.WriteKafkaPTest.stressTest(WriteKafkaPTest.java:226)
	at com.hazelcast.jet.kafka.impl.WriteKafkaPTest.stressTest_forceful_exOnce(WriteKafkaPTest.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:115)
	at com.hazelcast.test.FailOnTimeoutStatement$CallableStatement.call(FailOnTimeoutStatement.java:107)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:866)
```

</details>

Standard output is located here - https://console.aws.amazon.com/s3/buckets/j-artifacts/Hazelcast-5.maintenance-Openj9-11/43/

### PR DESCRIPTION
**Pull request by TomaszGaweda**
To make test less likely to be flaky, I've:
- increased timeout of operations
- bumped image to newest versions, so that Mac users will be able to test everything normally.

Fixes #21792

Checklist:
- [x] Labels (`Team:`, `Type:`, `Source:`, `Module:`) and Milestone set
- [x] Label `Add to Release Notes` or `Not Release Notes content` set
- [x] Request reviewers if possible

### CODE REVIEW

File: extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java [hunk 1]
```diff
@@ -49,19 +48,21 @@
...
     protected Admin admin;
     protected KafkaProducer<Integer, String> producer;
     protected String brokerConnectionString;
     private KafkaProducer<String, String> stringStringProducer;
 
     public static KafkaTestSupport create() {
-        if (!DockerTestUtil.dockerEnabled() || OsHelper.isArmMac()) {
+        if (!DockerTestUtil.dockerEnabled()) {
             if (System.getProperties().containsKey("test.kafka.version")) {
                 throw new IllegalArgumentException("'test.kafka.version' system property requires docker and x86_64 CPU");
```
Comment (ldziedziul) [inline extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java:67]: - Could you leave a comment here that Kafka older than 7.2.0 will fail on Arm machines? 
- The exception message here needs to be changed as well. 
- `OsHelper#isArmMac` is not used and can be removed.

File: extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java [hunk 2]
```diff
@@ -113,6 +114,7 @@ private KafkaProducer<Integer, String> getProducer() {
             producerProps.setProperty("bootstrap.servers", brokerConnectionString);
             producerProps.setProperty("key.serializer", IntegerSerializer.class.getCanonicalName());
             producerProps.setProperty("value.serializer", StringSerializer.class.getCanonicalName());
+            producerProps.setProperty("max.block.ms", String.valueOf(KAFKA_MAX_BLOCK_MS));
```
Comment (frant-hartm) [inline extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java:117]: The default for this is 1 minute, this seems large enough to me, in what case is it not sufficient?

We have timeout 5 mins for each test, so 10 mins doesn't make sense (if the operation would take more than 5 min the test would timeout and fail anyway).

**Review by frant-hartm — CHANGES_REQUESTED** [review]

File: extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java (hunk 2 above)
Comment (TomaszGaweda) [reply extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java:117]: There were cases that Jenkins overload made Kafka struggle to response in that time - the related issue is just Kafka not responding in time, probably due to Jenkins load as it's quite rare. This change was solely to minimise the risk of such Timeouts.

I see your point of value not making sense; I can switch it to 2 mins for example, but it's also rather arbitrary value I hope will help avoid the issue in the future. WDYT?

**Review by ldziedziul — APPROVED** [review]

File: extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java (hunk 2 above)
Comment (TomaszGaweda) [reply extensions/kafka/src/test/java/com/hazelcast/jet/kafka/impl/KafkaTestSupport.java:117]: I've reduced timeout to 2 mins

**Comment by TomaszGaweda** [comment]
run-lab-run

**Comment by TomaszGaweda** [comment]
run-lab-run
